### ISSUE TITLE
#1000 Optifine

### ISSUE THREAD

**Issue by lynrayy** [ChiselsAndBits/Chisels-and-Bits#1000]
![image](https://user-images.githubusercontent.com/59417884/191582970-bf18a485-b0f9-41f4-8841-cbab427d7cb6.png)
I (and others) will not remove optifine.
**Please make it compitable with optifine.**

**Comment by marchermans** [comment]
Due the way optfine works it is simply not possible. I did my best to make it work but they keep on changing their code without support for modders, go yell at them!
