### ISSUE TITLE
Adding back `forge:storage_blocks/copper` to Cut Copper

### ISSUE THREAD

**Issue by rlnt** [ChiselsAndBits/Chisels-and-Bits#1001]
* MC Version: 1.18+
* C&B Version: 1.18.2-1.2.114-universal
* Do You have Optifine: no

The mod is adding the `forge:storage_blocks/copper` tag to Cut Copper which is not correct. It was added in an earlier version of Forge but removed later.
Reference: https://github.com/MinecraftForge/MinecraftForge/commit/8f0d3da1e4228c326e9eaa676165bb150a348870

Another reference from a mod that also added the tag: https://github.com/klikli-dev/occultism/issues/784

Your tag: https://github.com/ChiselsAndBits/Chisels-and-Bits/blob/version/1.18.2/common/src/datagen/generated/data/forge/tags/items/storage_blocks/copper.json

**Comment by ShadowJonathan** [comment]
Fwiw this seems to cause issues with Unify; https://github.com/AlmostReliable/almostunified/wiki/Mod-Support

**Comment by rlnt** [comment]
Seems to be fixed for 1.19.2+.
