### ISSUE TITLE
Hotkeys with modifiers do not work

### ISSUE THREAD

**Issue by ouroborus** [ChiselsAndBits/Chisels-and-Bits#1008]
The items that have forced modifier keys don't seem to be able to be triggered. One of the side effects of this is the inability to clear marks from the tape measure.

For any bug reports please provide the following details as well,
* MC Version: 1.18.2
* C&B Version: 1.2.113 Fabric
* Do You have Optifine: No

**Comment by sayore** [comment]
Seems to be linkedto this then https://github.com/ChiselsAndBits/Chisels-and-Bits/issues/1012

**Comment by ouroborus** [comment]
Seems fixed in #1012
