### ISSUE TITLE
Blocks bug with shaders

### ISSUE THREAD

**Issue by Chumder** [ChiselsAndBits/Chisels-and-Bits#1011]
this
![Captura de pantalla 2022-10-14 145843](https://user-images.githubusercontent.com/108234830/195932157-b59d27bc-75ce-4944-883e-3f57dab1d257.png)

* MC Version: 1.18.2
* C&B Version: 1.2.114
* Shader Version: BSL v8.1.02.2
* Do You have Optifine: yea

**Comment by marchermans** [comment]
Remove optifine.
