### ISSUE TITLE
Meaurement Measures cannot be resettet.

### ISSUE THREAD

**Issue by sayore** [ChiselsAndBits/Chisels-and-Bits#1012]
Meaurement Measures cannot be resettet.

The keybind even allows for SHIFT + Left Shift and other sheanigans, any combination of Shift of Button wont work.

For any bug reports please provide the following details as well,
* MC Version: 1.18.2
* C&B Version: 1.2.114
* Do You have Optifine: No

**Comment by Ejz9** [comment]
I'm having this as well!!! I would like to mention this is on the fabric side of things for me.

**Comment by sayore** [comment]
https://github.com/ChiselsAndBits/Chisels-and-Bits/blob/ad96e164fea2a93ca295b1c29e2414937ef602b4/common/src/main/java/mod/chiselsandbits/keys/KeyBindingManager.java#L75-L81

This is most likely the issue, you demand a SHIFT + Key + Mouse click instead of just the keypress, remove Mouse and Shift from this register and it should work.

(I actually forked and fixed it and could succesfully make a working build, maybe i will PR it later)
EDIT: Here is the Hotfix PR
https://github.com/ChiselsAndBits/Chisels-and-Bits/pull/1014
