### ISSUE TITLE
I cant see the bits

### ISSUE THREAD

**Issue by McBoiMally** [ChiselsAndBits/Chisels-and-Bits#1021]
When ever I place a bit it does not let me see it but the hitbox is still there please help.

MC Version: 1.18.2
C&B Version: ChiselsBits-fabric-1.18.2-1.2.114.jar
Do You have Optifine: No

**Comment by SirenGlitch** [comment]
i had the same problem, if you have it installed, i'd recommend turning off quark in curseforge app. for me that didn't work but its worth the try since it seems to be a compatibility problem with quark.

**Comment by marchermans** [comment]
Either remove quark or install indium if you run with sodium
