### ISSUE TITLE
After chiseling block, texture becomes invisible

### ISSUE THREAD

**Issue by SirenGlitch** [ChiselsAndBits/Chisels-and-Bits#1025]
Place down block of stone, left click anywhere with netherite chisel. texture disappears but hitbox is still there

For any bug reports please provide the following details as well,
* MC Version: 1.18.2
* C&B Version: ChiselsBits-forge-1.18.2-1.2.114-universal.jar
* Do You have Optifine: No

**Comment by marchermans** [comment]
There has been an incompatibility report with Quark
Could you check if you have this installed.

If not you will need to track down what mod causes the conflict.

**Comment by SirenGlitch** [comment]
> There has been an incompatibility report with Quark
> Could you check if you have this installed.
> 
> If not you will need to track down what mod causes the conflict.

Yes I do have quark installed, is there a way of circumventing this issue?

**Comment by marchermans** [comment]
No clue
I don't understand why it happens. Some say it fixes it when they remove it some say it does not.

**Comment by SirenGlitch** [comment]
> No clue
> I don't understand why it happens. Some say it fixes it when they remove it some say it does not.

Does there seem to be a way of fixing it without removing it, just turning it off in some way? Or do I need to remove?

**Comment by marchermans** [comment]
Up to this day, I have no idea what the cause is.

**Comment by Xamos** [comment]
I don't have Quark, still happening to me. I do have the 4.8.4 DarkRPG modpack though. Edit: Oh it's 1.19.2 for me though with chisels-and-bits-fabric-1.3.122

**Comment by marchermans** [comment]
> I don't have Quark, still happening to me. I do have the 4.8.4 DarkRPG modpack though. Edit: Oh it's 1.19.2 for me though with chisels-and-bits-fabric-1.3.122

Do you have sodium?

**Comment by Xamos** [comment]
> > I don't have Quark, still happening to me. I do have the 4.8.4 DarkRPG modpack though. Edit: Oh it's 1.19.2 for me though with chisels-and-bits-fabric-1.3.122
> 
> Do you have sodium?

Yes I do

**Comment by marchermans** [comment]
Install Indium
