### ISSUE TITLE
Crashes Before everything even loads

### ISSUE THREAD

**Issue by Mox435** [ChiselsAndBits/Chisels-and-Bits#1026]
Ok when I load up Minecraft(1.12.2) on forge it loads the mods doesn't even get to the title screen and crashes and if I uninstall it it loads up and works I don't have Opti fine and I'm using version 14.33 the newest version I can find on forge.

**Comment by marchermans** [comment]
1.12.2 is not supported anymore.

**Comment by Mox435** [comment]
ok thank you
