### ISSUE TITLE
1.19.x compatibility

### ISSUE THREAD

**Issue by zhenlige** [ChiselsAndBits/Chisels-and-Bits#1027]
While Minecraft 1.19 has been released for 5 months, and 1.19.2 has been released for 3 months, C&B does not support Minecraft 1.19.x. Are there any plans to support 1.19.x (or even the coming version 1.20)?

For any bug reports please provide the following details as well,
* MC Version: 1.19.2
* C&B Version: 1.2.114
* Do You have Optifine: No

**Comment by CobaltMongoose** [comment]
I'd like to know too. It may be that there is a patreon beta version that does this? I saw that Chisels and Bits is working on Create Mod server run by some Hermitcraft folk and it recieved an update just a few days ago BUT I'm not sure what version of Minecraft they are running on the Create server. Typically Hermitcraft and related servers the latest version of Minecraft.

Anyway, I would love to know if 1.19 is coming soon so i could judge if I should wait or just skip C&B for my 1.19.2 modpack.

**Comment by marchermans** [comment]
Yes it is being updated.
Patreons already have access to the pre release, but it still contains to many bugs for wide consumption

**Comment by CobaltMongoose** [comment]
Perfect. Thank you!

**Comment by marchermans** [comment]
It has been released.
