### ISSUE TITLE
Block turns invisible after a chisel

### ISSUE THREAD

**Issue by jinxybri** [ChiselsAndBits/Chisels-and-Bits#1028]
Before continuing if you are reporting an issue, please ensure that all mods involved are updated to the latest version available, if your issue with with intermod compatibility such mixing C&B bits with other blocks make sure that MCMP is also updated. If your issue is a crash, be sure to include the crash log with your report.

Hello! I have an issue where if I remove a bit from a block, it turns invisible. I also don't have quark installed. 
Mods I have: 
Botany Pots
Clumps
Collective (Fabric)
Croptopia
Extra Origins
Full Brightness Toggle
JourneyMap
JEI
More Axolotl Variants
Origins
Pehkui
Sodium

For any bug reports please provide the following details as well,
* MC Version: 1.18.2
* C&B Version: ChiselsBits-fabric-1.18.2-1.2.115.jar
* Do You have Optifine: No

**Comment by marchermans** [comment]
Please install indium
