### ISSUE TITLE
In version 1.18.2, Bits don't show up but collision is still there

### ISSUE THREAD

**Issue by Aidain21** [ChiselsAndBits/Chisels-and-Bits#1029]
For any bug reports please provide the following details as well,
* MC Version: 1.18.2
* C&B Version: 1.2.115
* Do You have Optifine: No

I want to make an Aternos server for me and my friends to play on. This server will have immersive portals v1.4.12, pehkui v3.6.0+, and chisels & bits. However when running the server, or in a single player world, so probably not server side, placing bits are invisible, and using a chisel makes the entire block invisible. After looking at other comments, no, I don't have quark or sodium either.

**Comment by Aidain21** [comment]
After even more testing, turning off the other mods seems to fix it, but I would really like to know if there is a way to get this to work with immersive portals/pehkui

**Comment by marchermans** [comment]
Immersive portals breaks rendering.
There is no way for me to support it.
