### ISSUE TITLE
Creative Pick Block (missing)

### ISSUE THREAD

**Issue by MarkiMark34** [ChiselsAndBits/Chisels-and-Bits#1033]
MC Version: 1.18.2

   In the older versions of Chisels and bits 1.12 is was possible to pick a block (middle-click) and paste it with a ghost previewing its rotation and location.  This is of course left only for creative but its incredibly useful when making repeating structures, as well as rotating them via your direction (without a wrench).  I'd like to see a return of this feature as I think its a really important yet overlooked feature, and I hate using convoluted tools and paper.

**Comment by marchermans** [comment]
Hold shift while picking your block. There is a config option to swap the behaviour so that it picks the entire block by default and with shift a bit.

**Comment by MarkiMark34** [comment]
Oh sweet, I’ll try that out.
