### ISSUE TITLE
Crash in 1.19.2 upon launching game

### ISSUE THREAD

**Issue by HacoKavanah** [ChiselsAndBits/Chisels-and-Bits#1036]
[crash-2022-12-11_19.29.03-client.txt](https://github.com/ChiselsAndBits/Chisels-and-Bits/files/10202811/crash-2022-12-11_19.29.03-client.txt)

**Comment by Xamos** [comment]
Same here.

**Comment by ItsCliffGaming** [comment]
Same, both 1.3.119 and 1.3.120 crash with the same error as above. Also, even though its the Fabric version the Change Log for 120 says:

chisels-and-bits Changelog
Version: 1.3.120
Changes:
Publishing Forge.

**Comment by pokesmells** [comment]
[crash-2022-12-11_17.30.28-client.txt](https://github.com/ChiselsAndBits/Chisels-and-Bits/files/10203563/crash-2022-12-11_17.30.28-client.txt)

Also same here, crash on 1.19.2 FABRIC 0.14.11, with chisels-and-bits-fabric-1.3.120.jar and 
fabric-api-0.69.0+1.19.2.jar

**Comment by marchermans** [comment]
Fixed in 1.3.122
