### ISSUE TITLE
Incompatibility with Compact Machines on Fabric 1.19.2

### ISSUE THREAD

**Issue by Swedz** [ChiselsAndBits/Chisels-and-Bits#1037]
Running:
- Fabric 1.19.2 0.14.11
- Chisel & Bits 1.3.122
- Compact Machines 5.1.0

When both compact machines and chisel & bits are installed the textures for the bits appear as black and purple missing textures.

**Comment by marchermans** [comment]
Which mod is this exactly?

**Comment by Swedz** [comment]
[Compact Machines](https://www.curseforge.com/minecraft/mc-mods/compact-machines)

**Comment by marchermans** [comment]
@robotgryphon Do you have any idea?

**Comment by marchermans** [comment]
@Swedz Just for their models or for all?

**Comment by Swedz** [comment]
All
