### ISSUE TITLE
Blocks won't appear after I chisel them [1.19.2, Fabric ver.]

### ISSUE THREAD

**Issue by MrTophatMan** [ChiselsAndBits/Chisels-and-Bits#1038]
I have configured the settings for the indigo renderer btw

My mods: C&B, Optifabric, Optifine, Boosted Brightness (Fullbright for fabric), Fabric API 0.69.0, Essential

Optifine: HD_U_H9
Optifabric: 1.13.16
C&B: 1.3.122

**Comment by marchermans** [comment]
Remove Optifine

**Comment by MrTophatMan** [comment]
what should I use instead?
