### ISSUE TITLE
(Fabric) Adding C&B to an existing world crashes Server

### ISSUE THREAD

**Issue by Tiegertosch** [ChiselsAndBits/Chisels-and-Bits#1040]
When adding C&B to an existing world on a server, the server crashes after world loading (fabric). When I create a new world everything works fine
[crash-2022-12-17_22.20.33-server.txt](https://github.com/ChiselsAndBits/Chisels-and-Bits/files/10252774/crash-2022-12-17_22.20.33-server.txt)

**Comment by mnetwork** [comment]
same with Forge v. 40.1.87, if i exit the world and try to reconnect, the game crush

**Comment by marchermans** [comment]
Fixed in latest version.
