### ISSUE TITLE
Block texture disappears 1.19.2  (1.3.22)

### ISSUE THREAD

**Issue by Lagominer** [ChiselsAndBits/Chisels-and-Bits#1043]
![2022-12-18_09 51 27](https://user-images.githubusercontent.com/29659841/208284263-4f011a9f-81f9-44e4-92b5-8f171266891d.png)
This happens because of the snow lying at a close distance.

**Comment by Lagominer** [comment]
this happens when connecting with fences and semi-blocks

**Comment by ItsJirho** [comment]
I've got the exact same issue, happens with all semi-blocks except semi-blocks created with the mod itself.

**Comment by marchermans** [comment]
Fixed
