### ISSUE TITLE
1.18.2 Forge V1.2.116 Blocks Dissapear

### ISSUE THREAD

**Issue by JessVSGaming** [ChiselsAndBits/Chisels-and-Bits#1044]
Every once in a while when I chisel a block, said block disappears. Oh and every time I chisel a block it pops up a notifications saying "state invalid" or something along those lines. It basically tells me it can not do that action, but it still does the action.

![Minecraft_ 1 18 2 12_18_2022 9_34_59 PM](https://user-images.githubusercontent.com/120999644/208342470-7c11f158-7328-4fca-be42-6b2b13185daa.png)

**Comment by marchermans** [comment]
Do you have quark installed?
