### ISSUE TITLE
Blocks turn half-invisible

### ISSUE THREAD

**Issue by Schnitzelmoerder** [ChiselsAndBits/Chisels-and-Bits#1045]
Version 1.18.2
Forge Version 40.1.86
Optifine Enabled (40.1.85)

as stated in the title, chiseling blocks and placing bits results in them turning half invisible (made sure it's not shaders or texture pack, I'm also on a Server and the only one having this Issue)
![2022-12-19_15 25 50](https://user-images.githubusercontent.com/121040099/208447756-5d73e8c4-1616-4ff2-91a0-b8e2832957e2.png)

**Comment by marchermans** [comment]
Uninstall Optifine.
