### ISSUE TITLE
[FABRIC/QUILT] (1.19.2) Light blocks stop being fullbright after chiseling

### ISSUE THREAD

**Issue by neonishere** [ChiselsAndBits/Chisels-and-Bits#1047]
I tried to chisel blocks like glowstone with and without other mods and the situation is identical. I'm not trying to make bits emit light levels, I want to make them "glow in the dark".

I saw some person playing on 1.18 fabric with them and even a single bit of glowstone is fullbright without giving any light levels.

Even if a single bit is missing from a full glowstone block it just loses the fullbright glow.

**Comment by marchermans** [comment]
I can not reproduce this.
But I remember fixing something like that already. 
So I am going to call this fixed.
