### ISSUE TITLE
Features loss on 1.16.5 Forge

### ISSUE THREAD

**Issue by ghost** [ChiselsAndBits/Chisels-and-Bits#1049]
I'm using 36.2.34 which is the latest "**recommended**" version for 1.16.5. When I chisel in the plane mode it chisels the whole block, not the area I want, and also the drawn mode no longer exists (I chisel blocks in this mode completely freely). In addition, the 4x4 grid placement is removed and that forces me to control my movements extremely firmly. Briefly, I want the features in 1.12.2 to be in 1.16.5 as well.

**Comment by marchermans** [comment]
This is known
1.16.5 was the minecraft version were I initially ported to, however I was late in the release cycle so not all features made it. Sorry.

The only solution is to update.
