### ISSUE TITLE
Mod just doesn’t work at all

### ISSUE THREAD

**Issue by Biulixer** [ChiselsAndBits/Chisels-and-Bits#1050]
I find the items in my inventory but they don’t work at all then it doesn’t let me leave it gets stuck on saving world

this happens with the mod by itself on any version and any modpack

Rtx 3050
Ryzen 3 2300X
32GBS of ram 

i don’t have a image or video as I am typing this on mobile

**Comment by marchermans** [comment]
What game version
What platform
What mod version

**Comment by Biulixer** [comment]
As I said in the post this happens in any version it doesn’t matter I’ve only tried it on Java

**Comment by marchermans** [comment]
Sorry
But without that information and logs I can not help you.

**Comment by Biulixer** [comment]
The one I want it to work on is Stoneblock 3 if that helps I’m on the most recent update of it Minecraft version is 1.18.2 and sorry but idk what version the chisel and bits mod is 

my game doesn’t crash the mod just simply doesn’t work I can play fine

**Comment by marchermans** [comment]
Yeah sorry I never heard of that issue, nor can I reproduce it in that pack.
And if you are unable to send me more information, then I can not help you. And as such I will be closing this issue.
