### ISSUE TITLE
[Fabric 1.18.2] Shift for C & B overriding shift as a vanilla input

### ISSUE THREAD

**Issue by FredTheNerd** [ChiselsAndBits/Chisels-and-Bits#1052]
I launched into a server, one that I had played before, and found out that I couldn't sneak. I did some digging and concluded that this was due to the keybind: "Reset measuring tape measurements', as it was also preventing me from right clicking. I tried rebinding it, but I couldn't remove the shift.

Yes, this is part of a modpack, Valhelsia, and the issue only occurred after I removed mousetweaks and mouse wheelie in favor of itemscroller by masa.

**Comment by marchermans** [comment]
Yes, sadly I won't be updating 1.18.2 anymore, but this is fixed in 1.19.2
