### ISSUE TITLE
Forge 43.2.2 Minecraft 1.19.2 Chiseled block render trouble

### ISSUE THREAD

**Issue by CACOKKOTA** [ChiselsAndBits/Chisels-and-Bits#1053]
While placing slab, snow, stairs, fence, etc near with the chiseled block connected side of chiseled block becomes pransparent
I'm using OptiFine 1.19.2_HD_u_I1_pre4
![image](https://user-images.githubusercontent.com/113460989/210199353-da9358d7-e471-45f3-82fe-0a68ac1cf6d8.png)
![image](https://user-images.githubusercontent.com/113460989/210199461-079046ea-dcbe-4f2d-92ef-0670a9a5c799.png)
![image](https://user-images.githubusercontent.com/113460989/210199492-597a7474-6d81-4566-b3db-91998c646cc9.png)
![image](https://user-images.githubusercontent.com/113460989/210199528-dbef5653-e541-45c3-ab83-f3c81a721f7e.png)
![image](https://user-images.githubusercontent.com/113460989/210199540-4bcb9a14-9b9c-40dc-aa3e-c46e27793cc6.png)

**Comment by CACOKKOTA** [comment]
Also same thing but with chiseled block
![image](https://user-images.githubusercontent.com/113460989/210199993-6312b25e-843d-4d93-b536-98d42b1726c8.png)

**Comment by CACOKKOTA** [comment]
Tested w/o OptiFine, same thing

**Comment by RandomDaydreamer** [comment]
I'm also having this issue. Tested on Fabric with no other mods installed except for Chisel & Bits (including not having optifine installed) and still got this rendering bug.

**Comment by marchermans** [comment]
Fixed
