### ISSUE TITLE
Lag issue

### ISSUE THREAD

**Issue by claymore147** [ChiselsAndBits/Chisels-and-Bits#1054]
I was about to play my skyblock and could not load world again now. 
I have these 2 mods: Falling Tree, Chisel & Bits.

**EDIT:**
I have changed render distance and that helped. This mod is consuming many resources. There may be issue with rendering of blocks on mod side. I think it is that minecraft renders one chiseled block as 16x16x16 = 4096 separate objects? Maybe you can override this behavior by sealing that block programatically somehow.

From current behavior I suppose that one chiseled block is an array of 4096 objects which takes a lot of resources.

Solution would be to convert that array into one object with specific texture - this will cause that block could not be edited anymore as an side effect. I would give a player that choice - a tool that seals a chiseled block.

I consider lag issues as biggest in perspective of mod Chisels & Bits...

**Comment by claymore147** [comment]
I have changed render distance and that helped. This mod is consuming many resources. There may be issue with rendering of blocks on mod side. I think it is that minecraft renders one chiseled block as 4096 separate objects? Maybe you can override this behavior by sealing that block programatically somehow. 

From current behavior I suppose that one chiseled block is an array of 4096 objects which takes a lot of resources. 

Solution would be to convert that array into one object with specific texture - this will cause that block could not be edited anymore as an side effect. I would give a player that choice - a tool that seals a chiseled block.

**Comment by marchermans** [comment]
So since you provide no information on your setup I can't help you.

The latest versions of candb have had sealed models from day one.

Te pen the issue of you feel serious about this and want to help improve the situation.

**Comment by no-defun-allowed** [comment]
I've had similar issues with Chisel and Bits; looking at and near chiseled blocks causes render time to increase substantially, dropping from 200 FPS to about 60 on my machine, and allocation rate increases from about 200 MB/s to 1.5 GB/s. Looking through VisualVM, it seems `mod.chiselsandbits.utils.SimpleMaxSizedCache.get()` is rather hot; maybe some cache is not large enough?

Nah, the `ChiseledBlockBakedModelManager` cache should be big enough, so probably not that.

![Screenshot_2023-01-05_14-08-41](https://user-images.githubusercontent.com/43771738/210692753-8d380c60-109d-4db9-bb23-d25771251522.png)
