### ISSUE TITLE
Flan claiming incompat

### ISSUE THREAD

**Issue by Flemmli97** [ChiselsAndBits/Chisels-and-Bits#1057]
Chisel and bits ignoring claimed areas.
With chisel and bits you can place any blocks inside claimed areas.

Solution is here:
see [https://github.com/Flemmli97/Flan/issues/173#issuecomment-1193081243](https://github.com/Flemmli97/Flan/issues/173#issuecomment-1193081243)

**Comment by marchermans** [comment]
Giving that flan is not properly cancelling the event, and that they are not responding to my inquiry: I am going to close this ticket as not planned.

**Comment by Flemmli97** [comment]
i cannot cancel the event completely as i depend on the split of item use and block use of that event.

**Comment by marchermans** [comment]
> 

What do you mean?
You can either just allow the interaction or you do not.

And again, the methods mentioned in the FLAN ticket do not exist, nor does the mentioned class; I checked yarn, mcp and official. What do you expect C&B to do or what does your mod want from C&B here? I listen to somebody right-clicking or left-clicking a block and then act accordingly if he or she holds the relevant item. 

This is not rocket science, and many other mods out there do the same. So how do you handle those?
I want to provide compatibility but you will need to meet me half way here.

**Comment by Flemmli97** [comment]
RightClickBlock is a forge event. 

idk what exactly changed with 1.19 but here in 1.18:
[https://github.com/ChiselsAndBits/Chisels-and-Bits/blob/version/1.18.2/platforms/forge/src/main/java/mod/chiselsandbits/forge/events/RightClickEventHandler.java](https://github.com/ChiselsAndBits/Chisels-and-Bits/blob/version/1.18.2/platforms/forge/src/main/java/mod/chiselsandbits/forge/events/RightClickEventHandler.java)

i guess since you simply return DEFAULT here
[https://github.com/ChiselsAndBits/Chisels-and-Bits/blob/version/1.18.2/common/src/main/java/mod/chiselsandbits/logic/RightClickInteractionHandler.java#L57](https://github.com/ChiselsAndBits/Chisels-and-Bits/blob/version/1.18.2/common/src/main/java/mod/chiselsandbits/logic/RightClickInteractionHandler.java#L57)

the event handles item use on block and block use. cancelling the event causes neither to be processed yes. but you can also can only disable one of them without cancelling the whole event.

assuming you use similar logic in 1.19 this also applies to 1.19

**Comment by Killasaurus-Warbear** [comment]
Wondering if there's a fix or workaround for this as I'm experiencing the same issue in 1.19.2.

**Comment by marchermans** [comment]
Not at the moment.
I am working on a fix. But this should already be fixed in 1.19.2

**Comment by KBMC1364** [comment]
Hello i wanted to ask if this would be possible to be fixed in 1.18.2? I can see that you were working on a fix and should be fixed in 1.19.2 but i wanted to check for 1.18.2
Sorry if im a pain about this xd

**Comment by marchermans** [comment]
Sadly I won't be able to backport this
