### ISSUE TITLE
Another "Blocks turning invisible", but in 1.12.2

### ISSUE THREAD

**Issue by Froud17** [ChiselsAndBits/Chisels-and-Bits#1058]
Hello, i'm having the common issue of chiseled blocks dissapearing after reconnecting or leaving the chunks, but not all of them, just some specific blocks (they are still a lot of blocks).
I'm playing 1.12.2, no OptiFine
Mod list: 
![image](https://user-images.githubusercontent.com/102632037/213068189-d3a08149-b5fc-4fbb-b23b-ca77dd8f303e.png)
![image](https://user-images.githubusercontent.com/102632037/213068242-4c7a94e9-aebe-4082-b6c5-d8040b2aa438.png)
![image](https://user-images.githubusercontent.com/102632037/213068287-35d25cac-66bc-438d-8d98-0f22543e18cd.png)

I'm really sorry to bother here with an old version but it's the only one where i can gather all this mods together, if it's necessary i'll remove anyone. Thanks.

**Comment by Froud17** [comment]
PD: I've played a few worlds with the same modpack in the past and i didn't have this issue.

**Comment by marchermans** [comment]
Sorry 1.12 is not supported any more.
