### ISSUE TITLE
Consistent crash on undo.

### ISSUE THREAD

**Issue by ghost** [ChiselsAndBits/Chisels-and-Bits#106]
Something is going wonky between Chisel and Bits and mekanisms pipes/tubes. I crash every time I use undo where it would be undoing bits placed on a mekanism pipe/tube.

How to reproduce:
1. Place a mekanism pipe down. (I found this with advanced energy pipe)
2. Place some bits in the same block space as the pipe
3. Press Undo

Everything else seems to work OK between the two.
Crash report below:

http://pastebin.com/RASC0jhA

**Comment by AlgorithmX2** [comment]
Will be fixed by https://github.com/AlgorithmX2/Chisels-and-Bits/commit/778c4217b43a23cfdecac4ff798c2ed5edaf7993

**Comment by ghost** [comment]
I have an extension to this issue.

When I place a cable down and then put some bits inside the same block trying to remove bits with the chisel results in all the placed bits in that block to be broken in one lump.
The only way for the chisel to chisel away bits is if I wrench the cable out first.

No crash or error in the console either.

**Comment by AlgorithmX2** [comment]
Yes, I already discovered and fixed that as well, https://github.com/AlgorithmX2/Chisels-and-Bits/commit/d702567856ee54db25c8e39385f148f99fb0623b
