### ISSUE TITLE
[1.18.2] Putting fluid into Bit Storage on a server results in client crash

### ISSUE THREAD

**Issue by JetStream4396** [ChiselsAndBits/Chisels-and-Bits#1060]
Some friends have gotten a server running 119 mods including create, Chipped, and Chisels And Bits. I tried using Bit Storage to get lava for a build and I get an instant CTD, but the server is perfectly fine. Below is the crash log.

---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 1/20/23, 7:43 PM
Description: Unexpected error

java.lang.IllegalStateException: An outer transaction is already active on this thread.
	at net.fabricmc.fabric.impl.transfer.transaction.TransactionManagerImpl.openOuter(TransactionManagerImpl.java:40)
	at net.fabricmc.fabric.api.transfer.v1.transaction.Transaction.openOuter(Transaction.java:89)
	at mod.chiselsandbits.fabric.platform.fluid.FabricFluidManager.get(FabricFluidManager.java:39)
	at mod.chiselsandbits.fabric.platform.fluid.FabricFluidManager.extractFrom(FabricFluidManager.java:66)
	at mod.chiselsandbits.block.entities.BitStorageBlockEntity.addHeldBits(BitStorageBlockEntity.java:242)
	at mod.chiselsandbits.block.BitStorageBlock.method_9534(BitStorageBlock.java:91)
	at net.minecraft.class_4970$class_4971.method_26174(class_4970.java:939)
	at net.minecraft.class_636.method_2896(class_636.java:320)
	at net.minecraft.class_310.method_1583(class_310.java:1659)
	at net.minecraft.class_310.method_1508(class_310.java:1912)
	at net.minecraft.class_310.method_1574(class_310.java:1739)
	at net.minecraft.class_310.method_1523(class_310.java:1091)
	at net.minecraft.class_310.method_1514(class_310.java:737)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.fabric.impl.transfer.transaction.TransactionManagerImpl.openOuter(TransactionManagerImpl.java:40)
	at net.fabricmc.fabric.api.transfer.v1.transaction.Transaction.openOuter(Transaction.java:89)
	at mod.chiselsandbits.fabric.platform.fluid.FabricFluidManager.get(FabricFluidManager.java:39)
	at mod.chiselsandbits.fabric.platform.fluid.FabricFluidManager.extractFrom(FabricFluidManager.java:66)
	at mod.chiselsandbits.block.entities.BitStorageBlockEntity.addHeldBits(BitStorageBlockEntity.java:242)
	at mod.chiselsandbits.block.BitStorageBlock.method_9534(BitStorageBlock.java:91)
	at net.minecraft.class_4970$class_4971.method_26174(class_4970.java:939)
	at net.minecraft.class_636.method_2896(class_636.java:320)
	at net.minecraft.class_310.method_1583(class_310.java:1659)
	at net.minecraft.class_310.method_1508(class_310.java:1912)

-- Affected level --
Details:
	All players: 1 total; [class_746['Jet_Stream96'/530381, l='ClientLevel', x=936.53, y=7.00, z=-2994.62]]
	Chunk stats: 1024, 464 F: 401 L: 0 U: 29
	Level dimension: minecraft:overworld
	Level spawn location: World: (-32,111,32), Section: (at 0,15,0 in -2,6,2; chunk contains blocks -32,-64,32 to -17,319,47), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Level time: 13242443 game time, 16150466 day time
	Server brand: fabric
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:407)
	at net.minecraft.class_310.method_1587(class_310.java:2376)
	at net.minecraft.class_310.method_1514(class_310.java:761)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 2228000264 bytes (2124 MiB) / 6358564864 bytes (6064 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz
	Identifier: Intel64 Family 6 Model 60 Stepping 3
	Microarchitecture: Haswell (Client)
	Frequency (GHz): 3.20
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 4
	Graphics card #0 name: AMD Radeon (TM) R9 390 Series
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x67b1
	Graphics card #0 versionInfo: DriverVersion=27.20.20903.8001
	Memory slot #0 capacity (MB): 4096.00
	Memory slot #0 clockSpeed (GHz): 1.33
	Memory slot #0 type: DDR3
	Memory slot #1 capacity (MB): 2048.00
	Memory slot #1 clockSpeed (GHz): 1.33
	Memory slot #1 type: DDR3
	Memory slot #2 capacity (MB): 4096.00
	Memory slot #2 clockSpeed (GHz): 1.33
	Memory slot #2 type: DDR3
	Memory slot #3 capacity (MB): 2048.00
	Memory slot #3 clockSpeed (GHz): 1.33
	Memory slot #3 type: DDR3
	Virtual memory max (MB): 20414.21
	Virtual memory used (MB): 17727.43
	Swap memory total (MB): 8189.91
	Swap memory used (MB): 764.43
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8192m -Xms256m
	Fabric Mods: 
		architectury: Architectury 4.10.88
		balm-fabric: Balm 3.2.1+0
		bedspreads: Bedspreads 1.6.0-1.18
		betteradvancements: Better Advancements 0.2.0.146
		betterf3: BetterF3 3.0.0
		bewitchment: Bewitchment 1.18-23
			fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
			impersonate: Impersonate 2.4.1
			playerabilitylib: Pal 1.5.0
			step-height-entity-attribute: Step Height Entity Attribute 1.0.0
			terraform-wood-api-v1: Terraform Wood API (v1) 3.0.0
		bobby: Bobby 3.1.1
			com_typesafe_config: config 1.4.2
			io_leangen_geantyref_geantyref: geantyref 1.3.13
			org_spongepowered_configurate-core: configurate-core 4.1.2
			org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		byg: Oh The Biomes You'll Go 1.4
		camerautils: Camera Utils 1.18.2-1.0.0
		chipped: Chipped 2.0.1
		chiselsandbits: Chisels & Bits 1.2.116
		cloth-config: Cloth Config v6 6.4.90
			cloth-basic-math: cloth-basic-math 0.6.1
		create: Create 0.5.0g-792+1.18.2
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			fake-player-api: Fake Player API 0.3.0
			flywheel: Flywheel 0.6.8-32
			forge_tags: Forge Tags 2.1
			forgeconfigapiport: Forge Config API Port 3.2.0
			milk: Milk Lib 0.3.2
				dripstone_fluid_lib: Dripstone Fluid Lib 1.2.0
			noindium: No Indium? 1.0.1+1.18.2
				omega-config: OmegaConfig 1.2.3-1.18.1
			porting_lib: Porting Lib 1.2.460-beta+1.18.2-dev.cca931b
				com_github_llamalad7_mixinextras: MixinExtras 0.0.11
				mm: Manningham Mills 2.3
				serialization_hooks: Serialization Hooks 0.3.23
			registrate-fabric: Registrate for Fabric MC1.18.2-1.1.5
		ctm: ConnectedTexturesMod for Fabric 1.0.0+1.18
		decorative_blocks: Decorative Blocks 2.1.1
		fabric-api: Fabric API 0.67.0+1.18.2
			fabric-api-base: Fabric API Base 0.4.4+d7c144a860
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.2+2373a54560
			fabric-biome-api-v1: Fabric Biome API (v1) 8.0.6+651bcc5960
			fabric-block-api-v1: Fabric Block API (v1) 1.0.0+ee3621fc60
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.12+3ac43d9560
			fabric-command-api-v1: Fabric Command API (v1) 1.1.9+d7c144a860
			fabric-commands-v0: Fabric Commands (v0) 0.2.8+b4f4f6cd60
			fabric-containers-v0: Fabric Containers (v0) 0.1.23+d7c144a860
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.1.1+c85f2e3860
			fabric-convention-tags-v1: Fabric Convention Tags 1.0.1+474e4f7960
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.1+ee261a3e60
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 3.0.2+9fcb91d260
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.20+489d6f8260
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.8+d7c144a860
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.19+d7c144a860
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.20+d7c144a860
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.13+d7c144a860
			fabric-item-api-v1: Fabric Item API (v1) 1.6.0+d8cf4e5a60
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.14+91896a4960
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.12+54e5b2ec60
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.10+b4f4f6cd60
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.0+cc71601c60
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.0+1997ad1260
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.2+e747827960
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.4+cc71601c60
			fabric-models-v0: Fabric Models (v0) 0.3.6+d7c144a860
			fabric-networking-api-v1: Fabric Networking API (v1) 1.0.23+2d30af4b60
			fabric-networking-v0: Fabric Networking (v0) 0.3.10+b4f4f6cd60
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 2.1.3+032c981d60
			fabric-particles-v1: Fabric Particles (v1) 0.2.12+526dc1ac60
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.11+bb2e047760
			fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.15+ee3621fc60
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.5.5+41a02c8a60
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.11+b4f4f6cd60
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.8+ee3621fc60
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 2.0.2+54e5b2ec60
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.13+b4f4f6cd60
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.7+54e5b2ec60
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.3+91b7aa6660
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.2+446e059560
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.10+d882b91560
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.2+1f6558e860
			fabric-textures-v0: Fabric Textures (v0) 1.0.12+3ac43d9560
			fabric-transfer-api-v1: Fabric Transfer API (v1) 1.6.3+f4563ac860
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.0+e747827960
		fabricloader: Fabric Loader 0.14.12
		farmersdelight: Farmer's Delight 1.18.2-1.2.5
		freecam: Freecam 1.1.8+1.18
		gravestones: Gravestones v1.11.1
		indium: Indium 1.0.7+mc1.18.2
		java: OpenJDK 64-Bit Server VM 17
		litematica: Litematica 0.11.5
		lithium: Lithium 0.10.3
		malilib: MaLiLib 0.12.1
		mcdw: MC Dungeons Weapons 5.0.4-1.18
			enchant_giver: Enchant Giver 1.2.1
			reach-entity-attributes: Reach Entity Attributes 2.2.0
		minecraft: Minecraft 1.18.2
		modmenu: Mod Menu 3.2.5
		patchouli: Patchouli 1.18.2-71.1-FABRIC
			fiber: fiber 0.23.0-2
		pehkui: Pehkui 3.6.3+1.14.4-1.19.3
			kanos_config: Kanos Config 0.3.1+1.14.4-1.19
		phosphor: Phosphor 0.8.1
		roughlyenoughitems: Roughly Enough Items 8.3.583
			error_notifier: Error Notifier 1.0.9
		sodium: Sodium 0.4.1+build.15
			org_joml_joml: joml 1.10.2
		terrablender: TerraBlender 1.2.0.126
			com_electronwill_night-config_core: core 3.6.4
			com_electronwill_night-config_toml: toml 3.6.4
		trinkets: Trinkets 3.3.1
			cardinal-components-base: Cardinal Components API (base) 4.1.3
			cardinal-components-entity: Cardinal Components API (entities) 4.1.3
		veinmining: Vein Mining 0.0.16-1.18.2
		voicechat: Simple Voice Chat 1.18.2-2.3.26
		waystones: Waystones 10.1.0
	Flywheel Backend: GL33 Instanced Arrays
	Launched Version: fabric-loader-0.14.12-1.18.2
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: AMD Radeon (TM) R9 390 Series GL version 3.2.14831 Core Profile Forward-Compatible Context 21.5.2 27.20.20903.8001, ATI Technologies Inc.
	Window size: 1920x1017
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i5-4460 CPU @ 3.20GHz

**Comment by marchermans** [comment]
This is fixed in 1.19.2.
I sadly do not have the time to update 1.18.2 with a fix.
