### ISSUE TITLE
Chisels and Bits for fabric - Invisible (transparent) blocks (1.19.2)

### ISSUE THREAD

**Issue by komunre** [ChiselsAndBits/Chisels-and-Bits#1065]
Chiseling causes rendering issue with the placed blocks. Log contains warning about empty NBT in rendering thread (`[06:18:35] [Render thread/WARN]: Empty NBT tag received, ignoring.`), but I assume it might be unrelated to the C&B, because I was unable to reproduce this warning during interaction with blocks. 

I would prefer to not update to 1.19.3, due to having relatively large custom modpack.

![2023-01-30_06 27 41](https://user-images.githubusercontent.com/49118681/215362110-3c73452c-a654-4c54-8e83-4c84921a0ac6.png)
![2023-01-30_06 27 45](https://user-images.githubusercontent.com/49118681/215362113-0985bd30-e06a-4d14-98b0-881c8145ebfc.png)

**Comment by Ste-Mich** [comment]
I have the same issue on 1.19.2 Fabric. Chisels & Bits is on the latest version (1.3.126).

Removing Sodium seems to fix the issue for me, making blocks visible again.

I tried playing around with the config, but to no avail. Is there some setting I missed?

**Comment by marchermans** [comment]
Install indium

**Comment by Ste-Mich** [comment]
Installing Indium solved the issue. Thanks
