### ISSUE TITLE
 Filling machined blocks with liquids

### ISSUE THREAD

**Issue by Hevartid** [ChiselsAndBits/Chisels-and-Bits#1068]
Minecraft 1.19.2. Fabris
The current fluid source can process processed blocks. In fact, this is an alternative machine for the extraction of water bits. She is almost indestructible. You can remove it completely with a chisel. Unfortunately, this destroys the architecture of the processed block.
![2023-02-02_12 53 03](https://user-images.githubusercontent.com/124005111/216293107-1fd53203-0c1a-4bb4-a885-7364b3447eb4.png)
![2023-02-02_12 53 20](https://user-images.githubusercontent.com/124005111/216293163-8d95ae22-63bd-4343-a031-1e035f1849f4.png)
![2023-02-02_12 53 31](https://user-images.githubusercontent.com/124005111/216293137-271f7f87-e199-4ed4-8a13-2190a712de09.png)

**Comment by marchermans** [comment]
Right click the block with a sponge removes the fluids inside it.
