### ISSUE TITLE
Setting off an explosion near a chiseled block crashes the game

### ISSUE THREAD

**Issue by sashakoshka** [ChiselsAndBits/Chisels-and-Bits#1073]
Fabric, 1.19.2, no other mods except chisels and bits + fabric API.
Setting off an explosion (creeper, TNT, etc.) near any block that has been chiseled causes the game to immediately crash.
I have uploaded the entire log file of one such crash below:
[crash-2023-02-08_12.33.01-server.txt](https://github.com/ChiselsAndBits/Chisels-and-Bits/files/10688360/crash-2023-02-08_12.33.01-server.txt)

**Comment by sashakoshka** [comment]
It is possible to crash a Minecraft server with chisels and bits installed this way.

**Comment by marchermans** [comment]
Yeah I reproduced it
I am going to try to fix it in the next week.

**Comment by Guest3905** [comment]
Is there any update on this fix?

**Comment by ahribellah** [comment]
I am also having this issue. Currently on v1.3.126.

EDIT: And now the server is crashing every time I attempt to log in.

**Comment by marchermans** [comment]
Fixed.
