### ISSUE TITLE
Bit Storage has no correct tool (fabric)

### ISSUE THREAD

**Issue by MissPotato** [ChiselsAndBits/Chisels-and-Bits#1077]
When trying to break a Bit Storage with any tool the block is destroyed instead of dropping. It also takes a very long time to mine regardless of tool. 

C&B: 1.3.129
Fabric: Loader: 0.14.14
Fabric API: 0.73.2+1.19.2
Log: https://pastebin.com/rXSTgK2x

**Comment by marchermans** [comment]
Fixed in the latest 1.19.2 and 1.19.3 builds.
