### ISSUE TITLE
[Fabric 1.19.2] Performance issues in v1.3.129

### ISSUE THREAD

**Issue by ahribellah** [ChiselsAndBits/Chisels-and-Bits#1079]
I recently installed v1.3.129 on a Fabric 1.19.2 server I admin and it causes increasing performance issues the more you use the chisels and bits, eventually leading to constant freezes lasting more than a second.

With only something like 8 blocks chiseled, being within render distance of those blocks made the game unplayable.

When the server was restarted, you could be within render distance of the blocks, but only until someone either chiseled a block or placed bits. Then, within 10 actions total, it would be completely unplayable again.

As a result, I downgraded to v1.3.126, which instantly fixed all performance issues, but https://github.com/ChiselsAndBits/Chisels-and-Bits/issues/1073 is causing problems, so I may very well end up having to remove the mod altogether.

**Comment by MissPotato** [comment]
I suggest downgrading to 1.3.126. 1.3.129 seems to be having some issues.

**Comment by marchermans** [comment]
Do you have create installed?

**Comment by ahribellah** [comment]
> Do you have create installed?

Yes, but the Create blocks that are in use are several thousand blocks away from any of the chiseled blocks that are in use.

**Comment by marchermans** [comment]
There compatibility plugin causes this.
It has a bug with regards to loading chunks.

**Comment by marchermans** [comment]
See: https://github.com/Fabricators-of-Create/Porting-Lib/issues/43

**Comment by ahribellah** [comment]
> See: [Fabricators-of-Create/Porting-Lib#43](https://github.com/Fabricators-of-Create/Porting-Lib/issues/43)

Will keep an eye on this issue, thanks!

**Comment by marchermans** [comment]
Closing as this is not related to C&B.
