### ISSUE TITLE
Fabric Server Crash potentially caused by CB

### ISSUE THREAD

**Issue by instinxx** [ChiselsAndBits/Chisels-and-Bits#1080]
[crash-2023-03-06_17.23.40-server.txt](https://github.com/ChiselsAndBits/Chisels-and-Bits/files/10902728/crash-2023-03-06_17.23.40-server.txt)

Minecraft Version: 1.19.2
Java Version: 17.0.6, Eclipse Adoptium
Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
fabricloader: Fabric Loader 0.14.17
chiselsandbits: chisels-and-bits 1.3.129
			org_lz4_lz4-pure-java: lz4-pure-java 1.8.0
			saeculariacaudices: Saecularia Caudices 1.0.15
			scena: Scena 1.0.93

Not entirely sure what the players were doing. One player has a Base built w/ CB but the crashes seem to occur when he moves around the world.

**Comment by marchermans** [comment]
This is caused by PortingLib. They are trying to load a chunk which is already being loaded via mixin.
Report it to them.
