### ISSUE TITLE
[Forge 1.19.2] Watchdog crashes server seemingly at random. v1.3.129

### ISSUE THREAD

**Issue by Hoi15A** [ChiselsAndBits/Chisels-and-Bits#1083]
This seems to be similar to https://github.com/ChiselsAndBits/Chisels-and-Bits/issues/1078 but I am running forge and not fabric. The server will just randomly lock up and die. I've not managed to pinpoint exactly what conditions are required to cause it but stack traces mention chisel and bits

Crashlogs (pretty much all identical I think):
https://mclo.gs/kziRVDG
https://mclo.gs/l6WlayT
https://mclo.gs/HgyxB1n

**Comment by marchermans** [comment]
I think this is fixed in the latest release.
