### ISSUE TITLE
Water and lava bits have a missing triangle

### ISSUE THREAD

**Issue by AleFunky** [ChiselsAndBits/Chisels-and-Bits#1085]
![imagen](https://user-images.githubusercontent.com/55950650/225342790-8346d745-2f17-4d94-bd22-ce98dc3b144e.png)
There is a missing triangle in water and lava bits.

**Comment by AleFunky** [comment]
Actually no, its not missing but its flipped
![imagen](https://user-images.githubusercontent.com/55950650/225343445-93deca07-cf64-475b-8f5c-e002287ab728.png)

**Comment by marchermans** [comment]
Interesting....

**Comment by marchermans** [comment]
Fixed in 1.3.334 and 1.2.335
