### ISSUE TITLE
can't use many chisel functions in creative mode

### ISSUE THREAD

**Issue by Numbersistaken** [ChiselsAndBits/Chisels-and-Bits#1086]
i'm forced to go into survival mode anytime i wanna use something like the line chisels or the drawn chisel patterns. this issue was previously brought up on the 1.18 version of minecraft, and was said resolved, but this is still here on 1.19.2, most recent current version of the mod (1.3.129)

**Comment by marchermans** [comment]
Are you on fabric?

**Comment by Numbersistaken** [comment]
nope

**Comment by marchermans** [comment]
Are you using the curse forge launcher?

**Comment by Numbersistaken** [comment]
yes i am

**Comment by marchermans** [comment]
Can you try an installation using the forge installer and the normal client (you can copy the mod jar from the curse install). I have been told that somehow on some installations the curse installer and runner for forge is broken.

**Comment by Numbersistaken** [comment]
i'm smoothbrained and can't understand what that all means, and my game keeps corrupting itself anyway so i'm just gonna stop being concerned about it
