### ISSUE TITLE
Freezes server after server movement (1.19.2 Forge 43.2.4)

### ISSUE THREAD

**Issue by Minelsgo** [ChiselsAndBits/Chisels-and-Bits#1087]
Crash Log:
https://drive.google.com/file/d/1W62_IXniT0gI6-rAJI9sM3Ttc_hox-CU/view?usp=sharing

Startup Sequence (Has a bunch of errors):
https://drive.google.com/file/d/1rbArWzMzYGt8WTTYU7m-UhiI2wSUdHx8/view?usp=sharing

Everything works perfectly on PloudOS and I want to move the server to an Ubuntu VM.
I tried copying everything, copying everything but the libraries folder and reinstalling Forge, and only copying the world and mods folder, nothing worked.

The Server freezes whenever someone loads a chunk, wich has bits in it.
One time the server didn't freeze, but all chunks with bits in it didn't load.

Bits work when you create a new world on the same server.
The world works without the Chisel and Bits mod installed. 

Why does the world work on PloudOS and not on my Ubuntu VM?
Opening the world in single player worked btw.

**Comment by marchermans** [comment]
Based on the crashlog, this looks like a mod compat issue.
Some mixin is breaking the setBlock call for the chiseled blocks own position.

Can you check if you can reproduce it without immersive portals?

**Comment by Minelsgo** [comment]
Thank you very much for your answer.

Removing immersive portals sadly didn't help, in fact, I now removed every mod but the Chisels and Bits mod, and still have the same problem. The Crash log also looks similar.

**Comment by marchermans** [comment]
Okey
I am building and publishing a new version
Can you check if that fixes it, it should be up any minute now on CF

**Comment by Minelsgo** [comment]
Yeah kinda, with Chisels and Bits as the only mod it seems to work now. With all mods installed, chunks with bits in them aren't loading. Now I have to find out wich mods are causing the problem... (It's not immersive Portals)

**Comment by marchermans** [comment]
Okey I will consider this fixed. If you find the mod incompatibility that prevents the render, let me know.

**Comment by Minelsgo** [comment]
I now found the mods that are causing problems:

Immersive Portals (I was wrong in my last message)
Ultimate Plane Mod (Chunks with Bits load, but the Sever freezes eventually)
TerraBlender (Chunks with Bits load, but the Server freezes immediately afterward)
Waystones (Chunks with Bits won't load and the server freezes eventually)

Everything on the latest version.

We don't really need Immersive Portals and Ultimate Plane Mod, but definitely TerraBlender and Waystones
I don't know how I can send you crash logs now, because the Server freezes the entire VM for several minutes and then there's just the Error that a tick took too long and "Killed" displayed, but no Crash log saved.

**Comment by marchermans** [comment]
Hmm

**Comment by marchermans** [comment]
https://access.redhat.com/solutions/18178 show zou a guide how you can get a thread dump from a hanging server but it requires shell access

**Comment by marchermans** [comment]
Alternatively you could try to create a minimal reproduction case

**Comment by Minelsgo** [comment]
Apparently, me messing around with the mods just messed the world up, I now loaded a Backup and everything works.

Many thanks for your help.

**Comment by marchermans** [comment]
So it is not broken anymore?

**Comment by Minelsgo** [comment]
Yes, now it works.
