### ISSUE TITLE
Crash with Oculus (likely)

### ISSUE THREAD

**Issue by Herobattler** [ChiselsAndBits/Chisels-and-Bits#1089]
chisels-and-bits-forge-1.3.135.jar
[crash-2023-03-21_19.39.00-client.txt](https://github.com/ChiselsAndBits/Chisels-and-Bits/files/11032503/crash-2023-03-21_19.39.00-client.txt)

**Comment by marchermans** [comment]
The stack trace does not seem to reference c and b

**Comment by Herobattler** [comment]
The crash doesn't happen when I remove the mod tho

**Comment by marchermans** [comment]
I highly doubt that.
Not even a mixin is loaded.

I would bet it is related to oculus, rubidium or iris somehow.

I am sorry but I can not help you, since there does not seem to be any involvement of C&B here. Please report it to those mods.
