### ISSUE TITLE
Doesn't Work

### ISSUE THREAD

**Issue by SKYG0AT** [ChiselsAndBits/Chisels-and-Bits#1091]
This mod-it just doesn't actually work. I've installed this mod-what, 17+ times? And it just NEVER WORKS. I just can't use Chisel and bits. I use Java, and I've seen OTHER people use it perfectly fine (EX. Smallishbeans, a Minecraft Youtuber) I have enough space on my computer, so I don't know. I just want to build walls a different color than the outside! I guess if I want to have nice-looking walls, I have to waste ALL of my time, placing stupid blocks!

**Comment by marchermans** [comment]
You can join our discord: https://discord.chisels-and-bits.com to get help.
