### ISSUE TITLE
Chisel and Bits incompatible with Optifabric

### ISSUE THREAD

**Issue by Dm5354** [ChiselsAndBits/Chisels-and-Bits#1092]
As the tittle suggest C&B, Optifine and Optifabric are incompatible!

Minecraft Version: 1.19.2
Java Version: 17
Fabric Version: 0.14.12

C&B Version: 1.3.135
Optifine Version: HD_U_H9
Optifabric Version: 1.13.16

No Crash Log only normal log file:

https://pastebin.pl/view/1ec0e979

The only mod I didn't mention is Cloth Config API (version: 8.2.88)

If more data needs to be provided hit me up!

**Comment by marchermans** [comment]
Yes and this is by design since optifabric ignores the fabric rendering api. Complain to them.
