### ISSUE TITLE
Can you use Optifine and Chisels & Bits together?

### ISSUE THREAD

**Issue by ghost** [ChiselsAndBits/Chisels-and-Bits#1093]
Hello! I am having an issue with the chisel & bits mod's texture and I think the problem may be Optifine! The texture of the blocks break when I go to use the chisel. Is there a way to fix this issue or is optifine not compatible with the chisels and bits mod?

MC Version: 1.18.2
C&B Version: ChiselsBits-forge-1.18.2-1.2.116-universal.jar
Do You have Optifine: Yes; OptiFine_1.18.2_HD_U_H7.jar

**Comment by marchermans** [comment]
No it is not compatible and support is not planned
