### ISSUE TITLE
Blocks go invisible once chiseled

### ISSUE THREAD

**Issue by iAmChizzle** [ChiselsAndBits/Chisels-and-Bits#1096]
![image](https://user-images.githubusercontent.com/130003818/230224290-bcccd17a-d153-404a-abad-d293edb7a879.png)

As shown in the photo above, as soon as I Chisel a block it will then go invisible, this is the same for if I chisel a block and place some of the bits, the bits will also be invisible.

If break the block fully and pick it up it is shown in my inventory normally (with the pieces chiselled out) but as soon as it's placed it is invisible.

Just for some context I am playing on 1.19.3 Fabric, I am also playing with a large list of other mods, most clientside but a few serverside such as friends & foes and pickable villagers. I am however pretty certain that other mods arent the problem as it's working for my friend on our server and just not me.

Thanks for taking the time to help me out, it is a pretty cool mod!

**Comment by marchermans** [comment]
If you are running sodium on fabric install indium.

If you are using optifine uninstall it
If you are using immersive portals uninstall it.
