### ISSUE TITLE
Chisel item doesnt works

### ISSUE THREAD

**Issue by Okamomille** [ChiselsAndBits/Chisels-and-Bits#1098]
Hi, I play this mod since a lot of time and everything is great. But, since it's in 1.19.2, I can't use it anymore. The mod works, I can play with in a world, but I can't chisel any blocks. I frequently have some visuals bugs when I try to chisel blocks but that's all.

**Comment by marchermans** [comment]
> Hi, I play this mod since a lot of time and everything is great. But, since it's in 1.19.2, I can't use it anymore. The mod works, I can play with in a world, but I can't chisel any blocks. I frequently have some visuals bugs when I try to chisel blocks but that's all. 

Please join our discord to get help.
