### ISSUE TITLE
certain mods make chiselled blocks invisible

### ISSUE THREAD

**Issue by DuskKat** [ChiselsAndBits/Chisels-and-Bits#1099]
Chiselled blocks go invisible with following mods-

Sodium
Iris (requires sodium)

Important information: 
I am playing on single player with few other mods, but these two are the only ones with issues, the block are still there (the outline of the block when focused on it shows up, and block is still treated as a normal block, just invisible)

**Comment by marchermans** [comment]
This is known install indium to fix it.
