### ISSUE TITLE
Crash when putting saw in crafting grid with custom made block.

### ISSUE THREAD

**Issue by Amperthorpe** [ChiselsAndBits/Chisels-and-Bits#11]
http://pastebin.com/yixdSzLF
I made my own pillar (http://i.imgur.com/LJBHHon.jpg) and first put it under the saw, it showed a preview of it being chopped in half. I put it to the left of the saw, and it crashed. I did it all in creative, if it matters.

**Comment by Amperthorpe** [comment]
Also: As you can see I built that pillar in the center of a block, when I cut it in half with the saw the piece is all the way to the corner. I'm not sure if that is intended.

**Comment by AlgorithmX2** [comment]
On the Second Comment:

For the most common cutting case, things like slabs, and corners and stuff pushing the result to the "bottom corner" is preferred, you can always hold shift and put things were ever you want tho, so even if it does that it shouldn't be too bad for things like the pillar.
