### ISSUE TITLE
minecraft crashes

### ISSUE THREAD

**Issue by kaindand** [ChiselsAndBits/Chisels-and-Bits#1102]
every time I create a new world and edit blocks with the mod, it crashes. At first it starts to lag, and then after a while it crashes and you can no longer enter the world. i5 11400 and 3060 t i and other mods are not installed

**Comment by marchermans** [comment]
Can I get a log from this?

**Comment by kaindand** [comment]
The game crashed whilst unexpected error
Error: java.lang.NullPointerException: Cannot invoke "mod.chiselsandbits.platforms.core.registries.deferred.IRegistryObject.get()" because "convertedItemProvider" is null

**Comment by marchermans** [comment]
What game version or mod version of are you running?

**Comment by kaindand** [comment]
1.18.2

**Comment by kaindand** [comment]
ChiselsBits-fabric-1.18.2-1.2.116

**Comment by marchermans** [comment]
I can not reproduce this.
And it is a duplicate of #977
