### ISSUE TITLE
1.18.2 Chisels and Bits causes huge lag within JEI when scrolling on older machines

### ISSUE THREAD

**Issue by xFirefalconx** [ChiselsAndBits/Chisels-and-Bits#1103]
I've added this mod to my pack a while ago, and I have an issue with how the items are displayed in JEI. 
When scrolling through the pages, the whole game gets enormous frame drops and lags out. It's a real pain to get past the chisels and bits items when looking through the entire stock. I assume you're rendering whole blocks in the JEI window hence the frame drops? Can they be pre-loaded and pooled instead to that it doesn't lag as horribly? 

Tech data:

JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8000m -Xms256m
	Loaded Shaderpack: ComplementaryReimagined_r2.0.3
		Profile: HIGH (+11 options changed by user)
	Launched Version: forge-40.2.0
	Backend library: LWJGL version 3.2.2 SNAPSHOT
	Backend API: NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2 GL version 3.2.0 NVIDIA 516.94, NVIDIA Corporation
	Window size: 1920x1040
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: 
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz
	

If you need my full mod list, let me know.

**Comment by marchermans** [comment]
I am sorry, but all things you suggest are already implemented.
Some versions already have a toggle to filter them when JEI is loaded, but most modern versions don't. I still need to reimplement it.
