### ISSUE TITLE
C&B Blocks get invisble after rejoin

### ISSUE THREAD

**Issue by Biggeheim44** [ChiselsAndBits/Chisels-and-Bits#1107]
Hello, as you can see some of my bits are invisible, when I place them and return to the world they are gone. What can I do ? -> Version: 1.12.2
![Screenshot_20230524_134731_Discord](https://github.com/ChiselsAndBits/Chisels-and-Bits/assets/46755008/da5e27bd-84d3-43fc-addc-91a852b401a1)

**Comment by marchermans** [comment]
Sorry 1.12 is not supported anymore.
