### ISSUE TITLE
[1.12.2, v14.33] 6 out of 7 Thermal Expansion fluids vanish when placed into Chiselled Fluid Bit Tank

### ISSUE THREAD

**Issue by Pulz-TCP** [ChiselsAndBits/Chisels-and-Bits#1108]
Thermal Expansion liquids disappear when placed into the Chiselled Fluid Bit Tank.

**Molten Constantan** works fine, but all below fail:

- Molten Platinum
- Molten Signalum
- Molten Invar
- Molten Lumium
- Molten Enderium
- Molten Iridium

There are no errors (or any verbose) printed to console when liquids fail.

**Comment by marchermans** [comment]
Which game version?

**Comment by Pulz-TCP** [comment]
> Which game version?

1.12.2 (as per title ;) )

**Comment by marchermans** [comment]
1.12 is not supported anymore.
The fluid probably is not redenering because it is missing some data.
