### ISSUE TITLE
Vanilla Pathfinding AI Compatibility Issue With Non-solid Chiseled Block

### ISSUE THREAD

**Issue by AlisonHuang777** [ChiselsAndBits/Chisels-and-Bits#1109]
Minecraft Version: 1.19.2
C&B Version: 1.3.135
Other mod installed: 
![screenshot](https://github.com/ChiselsAndBits/Chisels-and-Bits/assets/51637996/7e1f37d2-4614-4ff0-b9b3-33f81fbc3c70)

The pathfinding AI in vanilla minecraft seems to take non-solid chiseled block as if it's not exsit; Therefore cause mob trying to walk through such blocks, or take such blocks as invalid paths.

Footage video:
https://github.com/ChiselsAndBits/Chisels-and-Bits/assets/51637996/e9be11c1-9f2e-44b3-a21a-31bf95288813

**Comment by marchermans** [comment]
The behaviour you showed in the video is correct.

C&B calculates a bounding box for pathfinding which only includes the solid pathable materials. And returns that when asked.

So i assume that is the cause why the villager won't walk over it, because he can not completely stand on it.

**Comment by AlisonHuang777** [comment]
Will this issue get fixed then?

**Comment by marchermans** [comment]
In what way is this an issue?  You used bits which make the pathable bounding box to small for the entity. This is normal behaviour.
