### ISSUE TITLE
Mirror Not Working

### ISSUE THREAD

**Issue by Utildayael** [ChiselsAndBits/Chisels-and-Bits#111]
Apologize if this is a stupid user error but I just can't get the mirror plan to work.

Tried:
1. Use mirror plan on side I want to copy, use on side I want to copy to.. no dice. Ok no problem, tooltip says combine with pos/neg plan.
2. Use mirror plan on side I want to copy, combine with pos or neg plan, use pos or neg plan on side I want to copy to. No dice.

Using the combined mirror+pos or neg plan it simply puts the side I want to copy... on a different side and resets the original side to default. Almost like it is rotating the block instead.

Am I missing a step or is this not working in 11.9 on MC 1.10.2? I looked on your page, read the tooltip, etc and seems I'm doing it as described... unless it doesn't work the way I'm expecting it to work?

Thanks!

**Comment by AlgorithmX2** [comment]
Seems to be working fine.
1. Using the mirror pattern click on east face of a block.
2. Craft the written mirror pattern with a blank positive pattern, results in a written positive pattern.
3. Place positive pattern.

Results in mirrored copy across the east-west axis.

![Example](https://dl.dropboxusercontent.com/u/9117298/cb/testing/mirror_test.png)

**Comment by Utildayael** [comment]
Ya no luck. :(

For test.. block with chiseled bits on the top only.

In this case, clicked top of block with mirror. 
Combined written mirror with blank positive. 
Click blank positive on bottom of block. 

Bottom side and top side switched such that bottom has chiseled bits [as desired!] but the top is now untouched and no longer has the chiseled bits. Tried all 4 modes of pos pattern.

Just to confirm I'm using it properly and not assuming it does something it doesn't actually do...

I should be able to use this to copy one face of a block to another face _of the same block_ right?

**Comment by AlgorithmX2** [comment]
Mirroring affects the full block. I think you may be thinking its something different from what you are talking about.

The pattern is used to do precisely what my picture above demonstrates. Taking a Block, and reflecting it across one side to produce a mirrored copy.

Depending on what your doing you could potentially combine that with the additive/impose mode on the positive pattern to mirror details form one side to another, but only if there is nothing "reserving that space" that is no different from how the positive pattern works however, the mirror just provides an additional transformation beyond rotation.

**Comment by Utildayael** [comment]
I think that was my problem. I was thinking mirror in terms of a single block and not multiple which is what was tripping me up! I'll muck around with positive patterns more. I was trying to find easiest way to chisel out one side of a block the way I want it and then replicate that to all other sides quickly. My various attempts with mirror, pos, neg on different modes seemed to not be able to yield that effect.

**Comment by AlgorithmX2** [comment]
I would suggest removing the part of the block that isn't part of the part you want to copy. Then capturing that on a positive, pattern and rotating it around using impose, or additive.

You can use the wrench to rotate blocks in the world around other axis as well if you need to apply the pattern to the top or bottom. So you can spin it around after adding the pattern to the sides.

Also, negative patterns are great for imposing a shape, since they only remove, but they only work if you are applying a pattern tot he destination material, not not when you need to add a new material to the space your working on.

**Comment by Utildayael** [comment]
That makes sense the more I think about it since you have to account for the entire block. While I wish it was as simple as "click side, click side to copy to" I understand that given you have an entire solid block that's not really feasible.

Thanks again :)

**Comment by AlgorithmX2** [comment]
No problem. Any suggestion to the verbiage on the website to prevent a repeat of this confusion?

**Comment by Utildayael** [comment]
Not sure how often you get questions on the mirror pattern so maybe it was just me being dumb. :)

I think key would be adding some sort of verbiage [and maybe a picture] showing that yes it does mirror but it mirrors to _another block_ ... makes sense to me now that you've told me how it works but reading the page it isn't quite as clear. Using a picture of a sphere or something might help. Really key is making sure folks know it mirrors one block _onto another block_.

To be honest, had issues getting started on this mod. I read your site and left scratching my head and swearing C&B was too much of a hassle. Went to Youtube and watched your video and it became MUCH more clear and was able to jump in and go with it for [most] items. My suggestion would be to add more examples show how the different things work visually. For example, showing a positive pattern and what the different modes do to the same block, etc could be handy albeit time consuming to create.

Again, not sure how many questions you get but if you get a lot... this might help. Well, that's assuming people actually read which.. doesn't always happen. ;)

Cheers

**Comment by AlgorithmX2** [comment]
Thanks for the feedback, examples is probably the way to go, I'll make note of that.

**Comment by Utildayael** [comment]
Thank you sir!
