### ISSUE TITLE
Bug: Placing Vanilla Doors And Beds Replaces Chiseled Blocks

### ISSUE THREAD

**Issue by AlisonHuang777** [ChiselsAndBits/Chisels-and-Bits#1110]
Minecraft version: 1.19.2
C&B version: 1.3.135
Other mods installed:
![screenshot](https://github.com/ChiselsAndBits/Chisels-and-Bits/assets/51637996/f7cde0b6-9953-467a-957a-6a3182cce899)

Footage video:
https://github.com/ChiselsAndBits/Chisels-and-Bits/assets/51637996/f739e99d-375e-4af0-9e28-1dfc8378cff6

**Comment by marchermans** [comment]
Wtf?!?

**Comment by marchermans** [comment]
I tested this with a normal player placing it without the Create hand.
And I can not reproduce this.

Please report this to create.
