### ISSUE TITLE
Create Method copying pattern while changing bit types.

### ISSUE THREAD

**Issue by rslink** [ChiselsAndBits/Chisels-and-Bits#112]
A feature where you can change the block types of a chiseled block consisting of only one type of block

I.E.
Create a pattern consisting only of stone bits
put  the chiseled block into the crafting table along with enough cobble bits to recreate the pattern.
The crafting table outputs a chiseled block with the same pattern but in cobble instead of stone.

**Comment by AlgorithmX2** [comment]
Seems to me like you just want to use the negative pattern on a block, then use it on a second block of the desired material.

That will transfer the shape from the source block to the second block, thus changing the material.
