### ISSUE TITLE
weird shadow when using shaders

### ISSUE THREAD

**Issue by Tixter99** [ChiselsAndBits/Chisels-and-Bits#1124]
why do i get this weird shadow when i'm using chisel and bits latest version of 1.18.2? i have tried different shaders but it is the same and i have tried to remove the shaders and it works then but i wanna be able to play with chisel and bits with shaders, so is there a fix to this?
![Skärmbild 2023-07-02 114323](https://github.com/ChiselsAndBits/Chisels-and-Bits/assets/138367994/4ee5dd90-5d95-43a0-972f-a05edb3bf953)

**Comment by snailzoki** [comment]
I get this too. did you find a solution?

**Comment by marchermans** [comment]
Update to 1.19.x Shaders where not supported in 1.18.2
