### ISSUE TITLE
The blocks I've chipped into become invisible

### ISSUE THREAD

**Issue by TArda34** [ChiselsAndBits/Chisels-and-Bits#1125]
It's becoming invisible when I start chipping any block

https://github.com/ChiselsAndBits/Chisels-and-Bits/assets/134140819/65cf0d28-9999-4a34-aa05-76279b1f9daf

Fabric, 1.3.135

(I'm using translation, forgive typos)

**Comment by marchermans** [comment]
Install `indium`
