### ISSUE TITLE
Bits wont appear when I place them.

### ISSUE THREAD

**Issue by xmochz** [ChiselsAndBits/Chisels-and-Bits#1127]
so heres the rundown. im a fabric minecraft player using the fabric version, and when im on a superflat world im unable to place the bits, basically i place it down, BAM! gone

im currently looking for a fix for this

WHAT IM USING
*fabric 1.19.4
*iris 1.19.4
*sodium 1.19.4

**Comment by Frisk4973** [comment]
e

**Comment by marchermans** [comment]
Install indium
