### ISSUE TITLE
Bug using Chisel & Bits with shaders??

### ISSUE THREAD

**Issue by snailzoki** [ChiselsAndBits/Chisels-and-Bits#1132]
in 1.19.2 it works fine with shaders, but 1.18.2 it gets an invisible texture and is broken. How can i fix this?
![2023-08-14_15 58 10](https://github.com/ChiselsAndBits/Chisels-and-Bits/assets/141201737/8be34a6d-9368-4ebc-a4ae-3b1fe10a59ee)

**Comment by marchermans** [comment]
Yes this is known. Update to 1.19.x where compatibility with shaders was introduced.
