### ISSUE TITLE
Error code: -1

### ISSUE THREAD

**Issue by FteFik2** [ChiselsAndBits/Chisels-and-Bits#1135]
Hi,
I'm playing with Chiesels and Bits long time, I'm playing with more mods and especially with world edit.
When I loaded schematic, my game since then keeps crashing when I trying to play that world.
If someone can help me, I will be grateful. I don't want waste that world for a stupid mistake.
version of mod: 14.33 on MC 1.12.2
![image](https://github.com/ChiselsAndBits/Chisels-and-Bits/assets/142716303/1ce7c699-5cd1-40bf-a394-7527afc3d956)

[crash-2023-08-20_10.10.22-server.txt](https://github.com/ChiselsAndBits/Chisels-and-Bits/files/12387669/crash-2023-08-20_10.10.22-server.txt)

**Comment by marchermans** [comment]
1.12.x is sadly not supported anymore.
