### ISSUE TITLE
Roll / Rotate Patterns and Blocks from Alt-Menu

### ISSUE THREAD

**Issue by AlgorithmX2** [ChiselsAndBits/Chisels-and-Bits#114]
View Direction combined with Shift Mouse currently rotate around the Y Axis, but there is no way to roll the block around the X/Z Axis, the idea is to add buttons like Undo/Redo to roll the blocks, or spin ( like mouse wheel )

**Comment by Fasteroid** [comment]
This would be especially helpful for people that like to build structures around mekanism pipes
