### ISSUE TITLE
[1.20.1] Crash when viewing Chisels And Bits in EMI.

### ISSUE THREAD

**Issue by Gbergz** [ChiselsAndBits/Chisels-and-Bits#1143]
Title ^

### Versions:
MC: 1.20.1
Forge: 47.1.3
Chisels and Bits: 1.4.141
JEI: 15.2.0.27 (used to view jei plugins with EMI)
[EMI](https://www.curseforge.com/minecraft/mc-mods/emi): 1.0.19

### Crash Report:
https://gist.githubusercontent.com/Gbergz/1fd23d632daf8a3d536674be3d231234/raw/8695e3ff497c20d29576ec0640548054701a2555/gistfile1.txt

**Comment by marchermans** [comment]
Report this to EMI, they have the level set to null when they shouldn't.

**Comment by Gbergz** [comment]
Already did, was sent here
https://github.com/emilyploszaj/emi/issues/296

**Comment by marchermans** [comment]
Yeah but there is not really anything I can do.
EMI Is requesting a model at a point outside of the game having loaded a world, which is not possible for bits because no registries have been loaded......
