### ISSUE TITLE
Crash when placing a bit [Fabric 1.20.1]

### ISSUE THREAD

**Issue by TimmyTimer** [ChiselsAndBits/Chisels-and-Bits#1144]
It crashes at soon as i try to place or try to remove a bit. I changed the ambient-occlusion-mode to enhanced in indigo-renderer.properties but it didnt help.

This is my crash report.
[crash-2023-09-01_12.09.03-client.txt](https://github.com/ChiselsAndBits/Chisels-and-Bits/files/12496877/crash-2023-09-01_12.09.03-client.txt)

**Comment by JustDevs** [comment]
I have the same issue as well.

This is my crash report.
[crash-2023-09-02_13.38.56-client.txt](https://github.com/ChiselsAndBits/Chisels-and-Bits/files/12503796/crash-2023-09-02_13.38.56-client.txt)

**Comment by Gorgolyo** [comment]
same here (im not linking crash report cuz its probably the same)

**Comment by Noaski5** [comment]
same here (same as the guy above me)

**Comment by marchermans** [comment]
Fixed in latest release.
