### ISSUE TITLE
The game crashes on client 

### ISSUE THREAD

**Issue by JuanPacoPedrodelaMar** [ChiselsAndBits/Chisels-and-Bits#1148]
The game crashes on client when trying to remove a pixel from a block (Fabric 1.20.1)
Here is the crash report:
[](url)
[crash-2023-09-16_19.37.24-client.txt](https://github.com/ChiselsAndBits/Chisels-and-Bits/files/12641691/crash-2023-09-16_19.37.24-client.txt)

**Comment by marchermans** [comment]
Fixed in latest release.

**Comment by JuanPacoPedrodelaMar** [comment]
where is the new release being published? And thank you for fixing :)

**Comment by marchermans** [comment]
CurseForge it is under manual review, can take some time. Sorry-
