### ISSUE TITLE
The game crashes on client

### ISSUE THREAD

**Issue by xXshadowWolf** [ChiselsAndBits/Chisels-and-Bits#1149]
it say's  The game crashed whilst rendering overlay
Error: java.lang.IllegalArgumentException: No model for layer geode_plus:wrappist_pedestal#main
[crash-2023-09-16_19.46.31-client.txt](https://github.com/ChiselsAndBits/Chisels-and-Bits/files/12641760/crash-2023-09-16_19.46.31-client.txt)

**Comment by marchermans** [comment]
This is not related to C&B but to Geode Plus.
