### ISSUE TITLE
Tool for assisting with circles and arcs

### ISSUE THREAD

**Issue by brwnibkr** [ChiselsAndBits/Chisels-and-Bits#115]
I'd imagine this tool ("compass"?) would work similarly to the tape measure; imposing an overlay of an arc or circle with the specified radius.

With this overlay, it'd be easier to place accurate 'curves', especially when the curve exceeds 1 block space.

I'd imagine circle mode to be a single click and drag from center to circumference to specify the radius with the circles plane being closest axis locked plane to the normal of the player's view vector.

I'd imagine arc mode to require 1 click followed by a click and drag: First click to specify the center and click and drag to specify the start and end of the arc. The plane of the circle should be able to be inferred from the same interactions.

Love this mod.

**Comment by Utildayael** [comment]
++ would be super handy
