### ISSUE TITLE
Something is causing blocks to go invisible

### ISSUE THREAD

**Issue by TheFreemanKing** [ChiselsAndBits/Chisels-and-Bits#1150]
Using sodium and a few other mods. Removed all then left sodium & iris out, it worked fine then it didnt when i put it back.
My friends im playing with who are also using sodium are not having the same issue.

**Comment by vgrynch** [comment]
What MC version?

**Comment by marchermans** [comment]
> Using sodium and a few other mods. Removed all then left sodium & iris out, it worked fine then it didnt when i put it back. My friends im playing with who are also using sodium are not having the same issue.

Install indium
