### ISSUE TITLE
optiFire Incompability with Chisel & Bits

### ISSUE THREAD

**Issue by brunosou2** [ChiselsAndBits/Chisels-and-Bits#1167]
Describe the bug

Platform(s)

 Forge
Environment(s)

 Singleplayer
Versions

Minecraft 1.20.1
To Reproduce

I use the "cute mob models resource pack" I am forced to use "OptiFine" and when I use the "chisels & bits" mod, the game gives an error

**Comment by metalmaniac431** [comment]
tbf i cant even make it work all my shite invis

**Comment by UltimateGG** [comment]
I saw in other issues they do not support optifine. Chiseled blocks render fine for me, no invisibility or anything. However, the outline red/green is rotated/off to the side when optifine is installed. A transform is off, would be nice if that was fixed just a quick reflection check for optifine

**Comment by marchermans** [comment]
We do not support optifine
