### ISSUE TITLE
Invisible EVERYTHING

### ISSUE THREAD

**Issue by TheKing8900** [ChiselsAndBits/Chisels-and-Bits#1173]
No error messages, no missing dependencies (as far as I'm aware. The mod page makes it hard to know if and what any dependencies are there), so I am unsure of what is causing the issue

However using fabric 1.20.1 version of Chisels and Bits, whenever I chisel a block the entire block dissappears as if it's been deleted when it's still there, and on top of this issue no bits are showing up even when placed. Everything is invisible on interaction

My mod list: (Because I can't add the files)
3D Skin Layers, Additional Structures, Advanced Netherite, Adventurez, Applied Energetics 2, Architectury (Lib), Artifacts, BCLib, Better End, Better Nether, Better Third Person, Cave Dweller Evolved, Chisels and Bits (obviously), Collective (Lib), Deeper and Darker, True Ending: Ender Dragon Overhaul, Extra Origins, Fabric (API), Farlands Reborn, Fullbright, GeckoLib, Iris Shaders, JEI, Mythic Mounts, Origins, Origins++, Patchouli (Lib), Pehkui (Lib), Replanter, Sodium, Trinkets, Xaero's Minimap, Xaero's World Map, YetAnotherConfigLib

Am I missing something? Is there incompatible mods? Because I'm sure not seeing errors telling me there's any incompatibilities

**Comment by marchermans** [comment]
Please install Indium.

**Comment by duke4806-hub** [comment]
I have indium installed and the bits still don't show. I'm using curseforge Immersive portals essentials
