### ISSUE TITLE
It won't let me change to a new version

### ISSUE THREAD

**Issue by tOMI2112** [ChiselsAndBits/Chisels-and-Bits#1175]
I have a world with many things from this mod in version 1.16.3 and when I install the mod for version 1.20.1 none of the things appear, it's like they are automatically removed

**Comment by marchermans** [comment]
This is, sadly, a consequence of the Minecraft world height update.
You can only take your world up untill the 1.18.2 boundary. Trying to migrate an existing modded world beyond that point will cause all C&B blocks to disappear.

**Comment by tOMI2112** [comment]
> Lamentablemente, esto es una consecuencia de la actualización de la altura del mundo de Minecraft. Solo puedes llevar tu mundo hasta el límite 1.18.2. Intentar migrar un mundo modificado existente más allá de ese punto hará que todos los bloques C&B desaparezcan.

**Comment by tOMI2112** [comment]
okey, thaks

**Comment by WindlessCarpet** [comment]
> This is, sadly, a consequence of the Minecraft world height update. You can only take your world up untill the 1.18.2 boundary. Trying to migrate an existing modded world beyond that point will cause all C&B blocks to disappear.

Does upgrading from 1.19.2 to 1.20.1 work? I'm on a flat world server, so the height shouldn't matter, I guess? Tried upgrading from 1.19.2 to 1.20.1 but all the bits disappeared, no issues when updating 1.19.2 to 1.19.3/4.
