### ISSUE TITLE
Bits don't show when I place them or when I use a chisel on a block

### ISSUE THREAD

**Issue by CraftGamer9651** [ChiselsAndBits/Chisels-and-Bits#1176]
When I use a chisel on a block to make it smaller, the texture disappears. the same thing happens when I place a bit.
![Screenshot from 2023-12-27 18-03-54](https://github.com/ChiselsAndBits/Chisels-and-Bits/assets/140124034/70456b5b-a666-4329-9752-ae94046eff40)

**Comment by CraftGamer9651** [comment]
The red is where the game wants me to break a block with the chisel.

**Comment by marchermans** [comment]
I assume you are on fabric. Install indium
