### ISSUE TITLE
Trouble with patterns

### ISSUE THREAD

**Issue by Susjin** [ChiselsAndBits/Chisels-and-Bits#119]
Hello AlgorithmX2
I'm having problems with all the patterns in version 11.9 of C&B, neither of then are working, i can copy chiseled blocks but i can't use it in any other block

If more information is needed, tell me what you need

**Comment by AlgorithmX2** [comment]
I'll need more details then that, I was using patterns just the other day when I was testing something else.

What block are you copying from, and to? You can chisel the block your applying the design to right?

If you are transferring a shape your using a negative pattern?

**Comment by Susjin** [comment]
I'

**Comment by Susjin** [comment]
I'm copying from Light blue clay to the same type of block; and yes i can chisel the block; no i'm using positive pattern

**Comment by AlgorithmX2** [comment]
Survival or Creative? If Survival do you have chisel on you?

**Comment by Susjin** [comment]
Don't remember, i'll test with an chisel and see if it works

**Comment by Susjin** [comment]
Ok,that was an big derp of my, sorry for taking your time
