### ISSUE TITLE
Frame displaced

### ISSUE THREAD

**Issue by byakxya** [ChiselsAndBits/Chisels-and-Bits#1190]
the frame of the bits looks displaced ingame, I only have optifine and chisel bits. Anyone who knows how to solve this?
![Sin título](https://github.com/ChiselsAndBits/Chisels-and-Bits/assets/160802352/8420e1e1-9d6b-44b5-afbd-da3945e492c9)

**Comment by marchermans** [comment]
Do you have optifine or sodium installed.?

**Comment by byakxya** [comment]
yes, i have optifine because without it my game runs horrible

**Comment by Eraldoh** [comment]
I have a similar issue too.
I cannot see the frame and the solution may be the same.
I'm still trying to solve this but i don't know what to do anymore (i'm playing Pokehaan craft 1.16.5 modpack)

**Comment by marchermans** [comment]
This is because of optifine. It breaks a lot of the custom rendering mods do, and this is a Consequence. There is sadly.nothing I can do.
