### ISSUE TITLE
Quill isn't creating a pattern

### ISSUE THREAD

**Issue by Spika-Akuma** [ChiselsAndBits/Chisels-and-Bits#1193]
So I'm not 100% sure if it's not working or if I'm doing something wrong. 
When I hold a quill (paper in offhand, I've tried the other way around too though) and right-click on a chiseled block, the paper disappears and then reappears in a different inventory slot unchanged. I do not receive a pattern that I could use to copy/paste.

Minecraft version: 1.20.1
C&B: chisels-and-bits-fabric-1.4.147.jar
Fabric: 0.15.7
Optifine: No

**Comment by CJaner08** [comment]
im on the same version but forge and have the same problem

**Comment by Official-Husko** [comment]
Try to hold right click on it for about 5 - 15 seconds

**Comment by Spika-Akuma** [comment]
Omg that worked, thank you so much! I always stopped too early because the paper disappeared.
