### ISSUE TITLE
Re-enter worlds make chiseled blocks to be invisible

### ISSUE THREAD

**Issue by Susjin** [ChiselsAndBits/Chisels-and-Bits#120]
Everytime i enter in my singleplayer world, all the C&B blocks in the chunk that i am became invisible, and i need to breake then all and place back

Screenshots:
http://imgur.com/a/DZ88F

I only used colored blocks, none of then are glowing or transparent

**Comment by AlgorithmX2** [comment]
Version? So only the chunk your standing in? Can you reproduce this in a new empty world?

**Comment by Susjin** [comment]
Version 11.9; Yes only in the chunk that i am; yes happening in a blank world

This only started to happen when i updated to 11.9

**Comment by AlgorithmX2** [comment]
Can you try https://dvs1.progwml6.com/jenkins/job/Chisels-and-Bits/8/artifact/build/libs/chiselsandbits-11.0.8.jar and see if the issue still exists?

**Comment by AlgorithmX2** [comment]
If the issue persists please post your F3 screen.

You could also try "Mod Options->C&B->Client Performance" and change "Use VBO" to "No" and see if the issue continues.

**Comment by Susjin** [comment]
I'll try it out

**Comment by AlgorithmX2** [comment]
I also tried this and I was unable to reproduce the issue, all the C&B blocks in the chunk i'm standing in are rendering fine.

**Comment by AlgorithmX2** [comment]
Please try,
https://dvs1.progwml6.com/jenkins/job/Chisels-and-Bits/10/artifact/build/libs/chiselsandbits-11.0.10.jar

**Comment by Susjin** [comment]
Tried with version 11.0.10 and it worked, the chunk that i was when i left don't have any invisible blocks
Thanks for the help!!

**Comment by AlgorithmX2** [comment]
Duplicate of https://github.com/AlgorithmX2/Chisels-and-Bits/issues/118
