### ISSUE TITLE
NPE on TileEntityBlockChiseled.triggerDynamicUpdates

### ISSUE THREAD

**Issue by mezz** [ChiselsAndBits/Chisels-and-Bits#121]
https://gist.github.com/mezz/b79c7c8bd56e1ea97279a42ca02665ea

Not sure what happened, I was just messing with my smeltery and haven't been chiseling any bits today.

**Comment by AlgorithmX2** [comment]
This was a pre-release bug, and is already fixed, FC needs to update .
