### ISSUE TITLE
Grass Tinting doesn't work in MCMP Blocks

### ISSUE THREAD

**Issue by WenXin20** [ChiselsAndBits/Chisels-and-Bits#122]
When a grass block bit is placed in a same-block space as a charset wire, the grass shows up as gray instead of green

**Comment by AlgorithmX2** [comment]
@amadornes does face tints work?

**Comment by WenXin20** [comment]
I'm not sure what you mean,  if you mean other blocks, then yes

**Comment by AlgorithmX2** [comment]
I was asking @amadornes if face tinting works in MCMP blocks. Cause I don't remember if that worked, or if I needed to do something to make it work.

**Comment by WenXin20** [comment]
Ok

**Comment by amadornes** [comment]
Nope, MCMP doesn't support it - FMP (as in the version that was PRed into Forge, not ChickenBones') does. Since FMP doesn't seem to be going anywhere I may look into adding them to MCMP soon, though.

**Comment by AlgorithmX2** [comment]
Alright, well then for now this can't be added, I guess if you get around to adding to to MCMP let me know so I can add support for it then.

**Comment by WenXin20** [comment]
Has Grass Tinting been added to MCMultiPart in v1.3.0?

**Comment by Dushess** [comment]
@amadornes Now FMP released again, possible to work with new 1.10.2 version.
