### ISSUE TITLE
Invisible blocks

### ISSUE THREAD

**Issue by vipa-ch** [ChiselsAndBits/Chisels-and-Bits#1221]
So, hello, im vipach, recently i started my survival, and i have C&B in my modpack. When i using chisel - block, where i deleted bit becomes invisible, but when im placing bit - block becomes visible.
My mods
appleskin
architectury
better f3
boat item view fabric
camera overhaul
C&B
CIT resewn
coroutil
dark loading screen
eating anmation
emotecraft
EMF (entity model features)
ETF (entity texture features)
entity culling - fabric
explosive enchancement
fabric language kotlin
falling trees
fancy block particles
fast load
inventory profiles next
iris
light overlay
litematica
litemoretica
malilib
mod menu
model gap fix
ok boomer
pandalib
plasmo voice
presence footsteps
replay mod
saecularia caudices
scena
screenshot to clipboard
shoulder surfing reloaded
shulker box tooltip
sodium
survival debug stick
symbol chat
tiefix
wakes
worldedit
what are they up to
fabric permissions api

Thats all

**Comment by marchermans** [comment]
Install indium
