### ISSUE TITLE
Chiseled bits are not relighting correctly

### ISSUE THREAD

**Issue by mezz** [ChiselsAndBits/Chisels-and-Bits#124]
![2016-08-10_14 53 39](https://cloud.githubusercontent.com/assets/916092/17572648/78dc4d16-5f0a-11e6-8068-4efc30b8051c.png)

We have partially transparent chisels and bits over several redstone lamps. When these lamps are turned on and then off with a lever, the chiseled bits stay lit. After breaking and replacing one piece, the ones around it all update to the correct state, but then when the lever is activated they may stay unlit as well.

![2016-08-10_14 57 11](https://cloud.githubusercontent.com/assets/916092/17572729/f8f823d0-5f0a-11e6-9f9c-4871bfea7e02.png)

**Comment by AlgorithmX2** [comment]
Is this with the current version? ( no pending updates? )

**Comment by mezz** [comment]
Yes, 11.9

**Comment by AlgorithmX2** [comment]
So this isn't FC? ( Jenkins Build 11.0.10 )

**Comment by mezz** [comment]
This is on a custom server, not FC, so we're using the latest from CurseForge.

**Comment by AlgorithmX2** [comment]
Ok, it might be fixed then, need to publish a new build, in the mean time feel free to test with the FC build if you want too.

**Comment by mezz** [comment]
Would the fix be clientside only? I do not have access to update the server at the moment.

**Comment by AlgorithmX2** [comment]
It is but the versions different so it'll probably complain

**Comment by mezz** [comment]
Ok, I'll get back to you when I can update. Thanks!
