### ISSUE TITLE
Sort Bag

### ISSUE THREAD

**Issue by Utildayael** [ChiselsAndBits/Chisels-and-Bits#125]
This isn't really a bug persay but I guess more of a feature request?

If you launch a server with options set for say...

I:bagStackSize=1024
D:bitLightPercentage=0.0001

Two things happen.
1. While stack size does update properly, your bags full of bits that are still on the old stack size stay on that size, ie 512 if default config. You have to remove them from the bag and add them back to get them into the new stack size, ie 1024 above.

Why this is... not great... if you have a dozen bags full of bits it's really, REALLY hard to actually do this as there is no easy way to empty bags out and given the already large stack sizes of 512, simply not enough inventory to dump all the bits in without repeating a horribly tedious process. :)

While I could dump the bits into block-form and then re-chisel them, that's not generally ideal either as you have to find all the types of blocks to pattern from to dump bits too. Takes a long time as well.

Request: Some form of control on the bag to have it "recalculate stacks" much like inventory tweaks will sort inventory. Heck bonus points if you can make it just a button that will re-arrange items in the bit bag and auto-stack everything to max stack size as it can identical to inventory tweaks functionality.
1. Config changes to bitLightPercentage require updating every C&B block to make them "light up" as any block on previous config that didn't meet light reqs was not lit and stays unlit with the new config value until you update that block. Update can be to whack it with a chisel, copy it with a pattern and replace it, etc and it is fine after that but it requires SOME update from C&B tools.

Request: This one is probably more of a stretch but would be nice if you could somehow fix that behavior.

Cheers

**Comment by AlgorithmX2** [comment]
I'm honestly not sure what you mean about the bags, you should be able to simply just add more bits to the bag. If your asking to magically sort them upon opening.. not sure about that...

I guess I could add a sort button though.

The second one probably won't happen, simply because that would require re-calculating every block, ever load, or to save the previous light value setting in every block, pretty much a waste of resources either way.

**Comment by Utildayael** [comment]
The problem is say you have a bag full of stacks of 512. You update config so max size is 1024. Bag still has stacks of 512. While you can add more and that works proper, the problem is when you have a dozen bit bags all packed full of 512 stacks and you need that space back! Since you can't move items around inside the bag you have to take them out of bag and put them back in for the new stack sizing to calc thus freeing up space since a bag full of say, the same blocks, now has 50% free after all the 512's become 1024's.

So ya, a manual sort button that would well, sort, the bag and combine bits into stacks would fix this behavior as well as my OCD. :)

Ya I figured #2 was a far reach but thought I'd ask!

Thanks
