### ISSUE TITLE
Pattern Book

### ISSUE THREAD

**Issue by weeryan17** [ChiselsAndBits/Chisels-and-Bits#126]
It would be nice if we had a better way to store and use are patterns for those of us who have 500 different patterns and not a big enough inventory. if you know the game factorio something like their new blueprint system would be nice. If you don't know how the factorio system works here's a brief explanation.
You have a books that stores your blueprints (well in this case patterns) and you can cycle through the patterns in your book to place one down.
If you do implement this it would also be nice if you could name your books (without using an anvil).

**Comment by weeryan17** [comment]
![2016-08-11_10 57 43](https://cloud.githubusercontent.com/assets/10491247/17595395/85cef944-5fb2-11e6-829f-05627ae9d0af.png)
just for reference in case you ask how many i have

**Comment by AlgorithmX2** [comment]
I'll have to look at the factorio system, I've not played it in a while and I don't remember it existing last time I tried it.

**Comment by weeryan17** [comment]
@AlgorithmX2 that's because it was just added in the latest big patch

**Comment by Utildayael** [comment]
++ to this idea... I have the same issue :)

**Comment by weeryan17** [comment]
@AlgorithmX2 so how do you usually decide if a feature should be added, and then how long does it usually take you to add it? (I really want a better way of storing and using patterns).

**Comment by monkeybug34** [comment]
+1 to this idea, also it wuld be nice to have a library(block?) that lets you save a pattern to file and retrieve it in a different world.
