### ISSUE TITLE
A problem with using this mod with Axiom

### ISSUE THREAD

**Issue by Lantonshile** [ChiselsAndBits/Chisels-and-Bits#1260]
![2024-10-10_21 12 12](https://github.com/user-attachments/assets/2eddf1db-8b38-4a71-9a37-140cab1a74f3)

It seems that when used together with Axiom, it may cause the wireframe to not appear in the correct position。

**Comment by Lantonshile** [comment]
I am not sure if this problem can be resolved by reason of Axiom is not open source. I am just trying to provide feedback on it.

**Comment by GormAuslander** [comment]
Confirm same issue. All wireframes are rendered incorrectly

**Comment by marchermans** [comment]
If axiom is not open source, then I have no ability to fix this.
