### ISSUE TITLE
Block to bits

### ISSUE THREAD

**Issue by Dijkstra1-zz** [ChiselsAndBits/Chisels-and-Bits#129]
In Chisels and bits and there way to turn a whole block into bits.

**Comment by AlgorithmX2** [comment]
The fastest way to convert a block into bits is to use a positive pattern for a full block that you have no bits for, for instance a positive pattern for a block of iron ore, as long as you don't have iron ore bits on you you can use the pattern to simply "chisel entire blocks"

Second to that would be the chisel on 1/2 block mode, where it takes 8 chisels to remove a block.

**Comment by Porcy** [comment]
Any plan to introduce this as a feature? Like, put your chisel next to a block (or stack of blocks) in a crafting grid and *boom*, thousands of bits!
