### ISSUE TITLE
Disappearing MCMP Parts

### ISSUE THREAD

**Issue by Discomanco** [ChiselsAndBits/Chisels-and-Bits#131]
Another issue regarding disappearing blocks!
I was covering my Mekanism wires (Universal Cable) with Chisels & Bits (11.10), and when using more than 1-2 types, the entire block would go invisible. Still functional, but invisible.
I thought at first it was because of rapid bit placement, but discovered after that it's because of multiple bit types. Seems to be the case once I reach the middle of the cable.

Also an issue with Refined Storage cables, although not as frequent, or bad (the cable itself will remain visible)

I currently have no way to see the block, or break it without the usage of TNT, which did inflict quite a bit of damage on the building itself.

Video: https://www.youtube.com/watch?v=Cqzyv9ViZZk

**Comment by AlgorithmX2** [comment]
Try https://dvs1.progwml6.com/jenkins/job/Chisels-and-Bits/lastSuccessfulBuild/artifact/build/libs/chiselsandbits-12.0.16.jar

I know there are some changes I've already made I don't know if its the same issue, I was playing around with refined storage cables and mekanism wires during the tests however, and I don't remember them disappearing in the latest build, but I might be wrong.

**Comment by Discomanco** [comment]
So I tried 12.0.16, and I could not replicate the block disappearing completely, which is great news.
It did on occasion when placing Planes fast, leave half-completed planes, as shown in the picture below, but that is very minor and can be worked around with by simply placing a plane again.
![2016-08-23_23 40 18](https://cloud.githubusercontent.com/assets/4707702/17910870/0d8bd0e6-698b-11e6-8de3-4e85470d717f.png)
I will have to wait for it to be up on Curse though.

**Comment by AlgorithmX2** [comment]
yeah, I'm not entirely sure what the deal is with the MCMP collision code producing that irregular pattern of bad data.

It never used to do that.

I've added an issue so I remember about it over here, https://github.com/AlgorithmX2/Chisels-and-Bits/issues/132

And 12.1 should be available on curse soon.
