### ISSUE TITLE
Lettering tool

### ISSUE THREAD

**Issue by NikitaVKalinin** [ChiselsAndBits/Chisels-and-Bits#134]
It would be nice to have a tool (or machine) for carving 3D letters.
A default MC font can be used, for example.

**Comment by AlgorithmX2** [comment]
I think this would be fine for an addon to do, if it is really necessary at all, letters are pretty easy to make by hand in my experience.

this to me feels more constraining then expressive, making everyone use the same font and letters for what they are doing, rather then letting them come up with their own variations and styles. It would be like adding a tool that prints tables... imo at least.
