### ISSUE TITLE
missing information

### ISSUE THREAD

**Issue by ebennett365** [ChiselsAndBits/Chisels-and-Bits#137]
You are missing basic information like if you need forge and if so what version or do you need some other file. download links for those other files are a great idea too.

**Comment by AlgorithmX2** [comment]
C&B only requires forge, which version depends on the build your using, and its usually older ( I don't usually update the requirements unless I have to ), also if your using a forge too old it will warn you on startup.

The thread is also labeled as "FORGE" I also added "Requires: Forge" to the the description page on curse forge.

**Comment by ebennett365** [comment]
You should put this info on the main download page so everybody knows.

**Comment by AlgorithmX2** [comment]
I cannot edit the download page on curse forge, and I already have edited the the thread and descriptions pages to add the details that apply.
