### ISSUE TITLE
Lit Redstone Lamp bit itemstacks have no name.

### ISSUE THREAD

**Issue by Phylogeny** [ChiselsAndBits/Chisels-and-Bits#139]
The display name is simply "Chiseled Bit", rather than "Chiseled Bit - Lit Redstone Lamp".

**Comment by AlgorithmX2** [comment]
Its probobly because there is no item for that state, still should probobly say something, I'll have to look at it.

**Comment by Phylogeny** [comment]
Hmm... yeah. Well, whether or not there's a good general solution to be found, at least making sure (by hard-coding, if necessary) that all bits of vanilla blocks display correctly would be nice. As far as I can tell, lit redstone lamp bits are the only vanilla block bits with this problem.

**Comment by AlgorithmX2** [comment]
Well, I can make it "Redstone Lamp" but not much in the way of getting "Lit" onto that without adding localization for it myself, honestly more tempted to black list it instead.. i'm not sure it makes sense to chisel a material that requires redstone signal.

**Comment by Phylogeny** [comment]
That's true. Redstone lamps being chiselable in the first place is relatively new anyway, if I'm not mistaken.

**Comment by AlgorithmX2** [comment]
Probably, I've been slowly relaxing the restrictions over time.

**Comment by AlgorithmX2** [comment]
I've added a test to ignore blocks without items, which in vanilla only blacklists the lit variant of the lamp, leaving the unlit variant alone.

I don't think this will change much mod wise, its a pretty unusual case, having a separate block for a state of another block.

**Comment by Phylogeny** [comment]
Sounds good.

**Comment by Phylogeny** [comment]
Lit redstone lamps are not blacklisted in 12.3 or 12.4.

**Comment by AlgorithmX2** [comment]
Take 2, https://dvs1.progwml6.com/jenkins/job/Chisels-and-Bits/27/

I'm honestly confused that my test some how worked the other night, I'm pretty sure this should resolve the issue for real now.

**Comment by Phylogeny** [comment]
Success! That does it.

**Comment by AlgorithmX2** [comment]
Cheers
