### ISSUE TITLE
Unable to fill tank when container holds more than 1 bucket

### ISSUE THREAD

**Issue by LemADEC** [ChiselsAndBits/Chisels-and-Bits#141]
As of chiselsandbits-12.1, when trying to fill with a fluid container (custom bucket) holding more than 1000 mB will fail.

**Comment by AlgorithmX2** [comment]
Well the tank can only hold 1000mb, What bucket are you testing with?

**Comment by LemADEC** [comment]
We're using SquareBuckets which is a mod in development.

**Comment by AlgorithmX2** [comment]
I'll need a copy of the mod to test and reproduce the issue.

**Comment by LemADEC** [comment]
--redacted--
please delete this message once downloaded

**Comment by AlgorithmX2** [comment]
I get a 403 response.

**Comment by stucuk** [comment]
If you modify your fill() so that resource.amount is 2000 it will simulate the issue with regular buckets.

aka:
`final int possibleAmount = 2000 - 2000 % TileEntityBitTank.MB_PER_BIT_CONVERSION;`

**Comment by LemADEC** [comment]
link is updated

**Comment by LemADEC** [comment]
wget fails on that link but browser can access it, weird

**Comment by AlgorithmX2** [comment]
Alright I have it.

**Comment by AlgorithmX2** [comment]
I'll take a look at it in a while when I have some time to try it out.

**Comment by AlgorithmX2** [comment]
Alright will be fixed next build.
