### ISSUE TITLE
java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by cookta2012** [ChiselsAndBits/Chisels-and-Bits#143]
http://pastebin.com/yeMHZzTS

I was loading into a old world fyi

**Comment by AlgorithmX2** [comment]
Hmm fun.. something in your instance only maps its ids one way, dose that only happen when loading the old world? or does it happen when opening a new world as well?

**Comment by AlgorithmX2** [comment]
When it shows up can you try the build at, https://dvs1.progwml6.com/jenkins/job/Chisels-and-Bits/24/

It should ignore the mapping issues instead of crashing.

**Comment by cookta2012** [comment]
I'll check the whole new instance thing in a few busy at school atm

On Oct 4, 2016 9:40 AM, "AlgorithmX2" notifications@github.com wrote:

When it shows up can you try the build at, https://dvs1.progwml6.com/
jenkins/job/Chisels-and-Bits/24/

It should ignore the mapping issues instead of crashing.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
https://github.com/AlgorithmX2/Chisels-and-Bits/issues/143#issuecomment-251408158,
or mute the thread

**Comment by AlgorithmX2** [comment]
Any chance you can confirm that this fixed the issue in the next hour or two?

I'd like to be sure before I release the next build officially.

**Comment by AlgorithmX2** [comment]
I just released the new version, I suppose let me know when you get around to trying out 12.4

**Comment by cookta2012** [comment]
It is fixed atm so thanks :p

**Comment by AlgorithmX2** [comment]
Thanks for confirming.
