### ISSUE TITLE
World hanging on "Building Terrain"

### ISSUE THREAD

**Issue by 99Blocks** [ChiselsAndBits/Chisels-and-Bits#144]
Hi, I updated to the recent 12.3 version and the pack loads up with no errors but then the world gets stuck on "Building Terrain" and it just hangs.
I'm not sure if it's a compatibility issue with one of the other mods in the pack and I will try with a new world as well as turning off displaying the "bits" in JEI. But I thought I'd just raise it in case it's something else. Many thanks

**Comment by AlgorithmX2** [comment]
Try https://dvs1.progwml6.com/jenkins/job/Chisels-and-Bits/24/artifact/build/libs/chiselsandbits-12.0.24.jar Someone else reported an issue with loading worlds with certain mods, your hang might be related.

**Comment by 99Blocks** [comment]
That version works perfectly fine but because it flags as "Unknown" it may cause issues with re-distribution of the pack. (I have shared the pack on curse) Currently the 12.1 version is working fine as well but if it's ok with you I'll share the link to that build on my channel/twitter so that people playing the pack can use the workaround too.

**Comment by AlgorithmX2** [comment]
If that fixes your issue i'll release an official build with it in a few hours, I was just wanting to make sure it was related and fixed.

**Comment by 99Blocks** [comment]
Thanks very much! Very rapid and helpful response from an author (makes a nice change! ;))
As far as I can see it all works fine with the version you pasted above.

**Comment by AlgorithmX2** [comment]
Thanks for the prompt feedback, once I have a few minutes I should be able to get the fix released officially for use with packs.
