### ISSUE TITLE
Undo/redo operations affect individual blocks rather than whole undo groups.

### ISSUE THREAD

**Issue by Phylogeny** [ChiselsAndBits/Chisels-and-Bits#145]
Pressing undo or redo causes only a single block of an undo group to be undone/redone. So if 20 blocks were affected in a single click, undo must be pressed 20 times to undo the group. And if more blocks were affected than the config specified 'undo level', the operation cannot even be entirely undone.

This was introduced in 10.7 for MC 1.9.4 (not sure when it was introduced into other versions), and is true for all the latest versions of C&B. That alone seems to indicate that it's intended, but surly it's a bug... I mean one operation can clear your entire undo history and can't even be fully undone, if large enough. And even if the group is small enough to be completely undone, since it may not even be clear how many blocks you affected, it may be impossible to know how many times you must click/press to undo an operation.

**Comment by AlgorithmX2** [comment]
Is this true of C&B's native Drawn region feature? I was almost positive that it does the entire range at once, and not one block at a time.

**Comment by Phylogeny** [comment]
Yes, this is so even with the standard chisel.

**Comment by AlgorithmX2** [comment]
Turns out EntityPlayerSP.isServerWorld is always true, even if its on the client thread, I think this was only an issue for single player once I replaced that call the grouping behavior started working again.

So it must have been caused by a bug fix at some point.

**Comment by AlgorithmX2** [comment]
https://dvs1.progwml6.com/jenkins/job/Chisels-and-Bits/26/ should be fixed if you want to try it out, so far in my testing it seems to resolve the issue.

**Comment by Phylogeny** [comment]
It is indeed fixed. Very nice.
