### ISSUE TITLE
Placing flower pots on top of chiseled bits.

### ISSUE THREAD

**Issue by atakle** [ChiselsAndBits/Chisels-and-Bits#147]
It's not currently possible to place flower pots on top of chiseled creations. It would be nice for furniture creation etc. if it was.

**Comment by AlgorithmX2** [comment]
This probably requires a forge patch to change the test in the flower pot, Its likely testing for opaque blocks, rather then solid sides.

**Comment by AlgorithmX2** [comment]
Confirmed, its using IBlockState.isFullyOpaque - so it will require a forge patch.

**Comment by AlgorithmX2** [comment]
Forge patch submitted and accepted as of 1.12
