### ISSUE TITLE
Clientside crash while playing on a server

### ISSUE THREAD

**Issue by awkwaRdcaRRot** [ChiselsAndBits/Chisels-and-Bits#150]
http://pastebin.com/vwBZkGhR

Crashes with one of my profiles, made another one with the same mods and it doesn't crash. Only crashes when I have the chisel in my inventory. I logged in on another profile and put the chisel in a chest, went back to the original profile and got in just fine, took the chisel out of the chest and it crashed again. Server doesn't crash, just the client.

**Comment by AlgorithmX2** [comment]
Please post your config for C&B, I think one of the values is corrupted.

**Comment by awkwaRdcaRRot** [comment]
They're the default. I deleted the config for it and let it make a new one and the same thing happened.

**Comment by AlgorithmX2** [comment]
I'm rather uncertain of what would be the cause of a crash between to different instances then, if one instance is fine, and the other crashes. What else could be different? Different version of the mod? A corrupt Jar file?

**Comment by awkwaRdcaRRot** [comment]
It might have been a corrupt jar. I browsed around while avoiding the chisel and noticed all the extra utilities textures weren't loading. I just decided to delete that instance and stick with the new one. Thanks for the quick replies!
