### ISSUE TITLE
crash with refined storage 1.10.2 simalar but diffrent more info

### ISSUE THREAD

**Issue by ilordnightmarei** [ChiselsAndBits/Chisels-and-Bits#151]
http://pastebin.com/zRF3LezR
chiselnbits:12.4
i found the block atleast

**Comment by AlgorithmX2** [comment]
Not sure why you opened a new issue, you can't get the test build on the server to confirm the fix?

Related https://github.com/AlgorithmX2/Chisels-and-Bits/issues/149

**Comment by ilordnightmarei** [comment]
its not my server but ill ask if he can and sadly no i cant for now  lol i made a diffent post cause the logs diffrent and it could be a diffrent thing

**Comment by AlgorithmX2** [comment]
Its likely related, but the issue seems to be masked behind vanilla code, since we can't confirm the I'll just have to release the untested fix.

**Comment by ilordnightmarei** [comment]
cool when whatthedrunk updates chiselnbits ill be the firt thing i test but ima try to remove the bit from my system now lol

**Comment by AlgorithmX2** [comment]
Any results?

**Comment by AlgorithmX2** [comment]
No Response, Closing.
