### ISSUE TITLE
Crash - During World Generation

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [ChiselsAndBits/Chisels-and-Bits#153]
https://gist.github.com/DPxKnightxZero/237043df0faca7ef0424b976fff558e3

**Comment by AlgorithmX2** [comment]
What version of C&B, and any idea where I can look at mod WTF, BlockDecoAnim? the crash is happening when asking it about which layers it can render in.

**Comment by P3rf3ctXZer0** [comment]
States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAA    mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAA    FML{8.0.99.99} [Forge Mod Loader](forge-1.10.2-12.18.2.2099-universal.jar) 
    UCHIJAAA    Forge{12.18.2.2099} [Minecraft Forge](forge-1.10.2-12.18.2.2099-universal.jar) 
    UCHIJAAA    ivtoolkit{1.2.8.5} [IvToolkit](minecraft.jar) 
    UCHIJAAA    JEI{3.12.7.312} [Just Enough Items](U-1.10.2-jei-3.12.7.312-D-R.jar) 
    UCHIJAAA    jet{2.1.37} [JustEnoughTooltips](C-1.10.2-JustEnoughTooltips-2.1.37-R.jar) 
    UCHIJAAA    ReAuth{3.2} [ReAuth](C-1.10.2-ReAuth-3.2-R.jar) 
    UCHIJAAA    betterquesting{1.3.161} [Better Questing](U-1.10.2-BetterQuesting-1.3.161-D-R.jar) 
    UCHIJAAA    bq_themed{0.0.2 Alpha} [ThemedQuestingPack](C-1.10.2-themedquestingpack-1.3.0-R.jar) 
    UCHIJAAA    torohealthmod{1.10.2-1} [ToroHealth Damage Indicators](C-1.10.2-torohealth-1-R.jar) 
    UCHIJAAA    WailaHarvestability{1.1.9} [Waila Harvestability](C-1.10.2-WailaHarvestability-1.1.9-R.jar) 
    UCHIJAAA    Waila{1.7.0} [Waila](C-1.9.4-Waila-1.7.0-B3-D-R.jar) 
    UCHIJAAA    abyssalcraft{1.9.3-pre-1} [AbyssalCraft](U-1.10.2-AbyssalCraft-1.9.3-pre-1-R.jar) 
    UCHIJAAA    acblocks{1.2.0} [AbyssalBlocks](U-1.10.2-AbyssalBlocks-1.2.0-R.jar) 
    UCHIJAAA    agriculturalexpansion{r-1.2.0} [Agricultural Expansion](U-1.10.2-AgriculturalExpansion-r1.2.2-R.jar) 
    UCHIJAAA    architecturecraft{1.5.0.0} [ArchitectureCraft](U-1.10.2-ArchitectureCraft-1.5.0.0-B.jar) 
    UCHIJAAA    atlcraft{1.10.2-Ver1.2} [ATLCraft Candles Mod](U-1.10.2-ATLCraftCandles-Ver1.2-R.jar) 
    UCHIJAAA    bagginses{2.4.2d} [Bagginses](U-1.10.2-Bagginses-3.0.4e-R.jar) 
    UCHIJAAA    BetterAchievements{0.3.1.34} [Better Achievements](U-1.10.2-BetterAchievements-0.3.1.34-A.jar) 
    UCHIJAAA    betterbuilderswands{0.6.5} [Better Builder's Wands](U-1.10.2-BetterBuildersWands-0.6.5-r138+8595fc7-R.jar) 
    UCHIJAAA    BiomesOPlenty{5.0.0.2088} [Biomes O' Plenty](U-1.10.2-BiomesOPlenty-5.0.0.2088-B.jar) 
    UCHIJAAE    chiselsandbits{12.5} [Chisels & Bits](U-1.10.2-chiselsandbits-12.5-D-B.jar) 
    UCHIJAAA    cosmeticarmorreworked{1.10.2-v2a} [CosmeticArmorReworked](U-1.10.2-CosmeticArmorReworked-v2a-R.jar) 
    UCHIJAAA    MineTweaker3{3.0.11} [MineTweaker 3](U-1.10.2-CraftTweaker-3.0.11-D-R.jar) 
    UCHIJAAA    DimensionRules{1.1} [Dimension Rules](U-1.10.2-DimensionRules-1.1-R.jar) 
    UCHIJAAA    dooglamoocitiesmod{1.10.2-1.1.1} [Dooglamoo Cities Mod](U-1.10.2-dooglamoocitiesmod-1.1.1-R.jar) 
    UCHIJAAA    DungeonTactics{DT0.10.0} [DungeonTactics](U-1.10.2-DungeonTactics-0.10.0-R.jar) 
    UCHIJAAE    ExtraBitManipulation{1.10.2-2.1.0} [Extra Bit Manipulation](U-1.10.2-ExtraBitManipulation-2.1.0-R.jar) 
    UCHIJAAA    flatcoloredblocks{mc1.10-v4.2} [Flat Colored Blocks](U-1.10.2-flatcoloredblocks-v4.2.jar) 
    UCHIJAAA    helpfixer{1.0} [HelpFixer](U-1.10.2-HelpFixer-1.4.15-B.jar) 
    UCHIJAAA    journeymap{1.10.2-5.2.4} [JourneyMap](U-1.10.2-journeymap-5.2.4-unlimited-B.jar) 
    UCHIJAAA    KeepingInventory{2.1} [Keeping Inventory](U-1.10.2-KeepingInventory-2.1-R.jar) 
    UCHIJAAA    labyrinth{${version}} [Daedalus' Labyrinth](U-1.10.2-Labyrinth-1.3-R.jar) 
    UCHIJAAA    lycanitesmobs{1.15.1.4 - MC 1.10.2} [Lycanites Mobs](U-1.10.2-LycanitesMobsComplete-1.15.1.4.jar) 
    UCHIJAAA    arcticmobs{1.15.1.4 - MC 1.10.2} [Lycanites Arctic Mobs](U-1.10.2-LycanitesMobsComplete-1.15.1.4.jar) 
    UCHIJAAA    demonmobs{1.15.1.4 - MC 1.10.2} [Lycanites Demon Mobs](U-1.10.2-LycanitesMobsComplete-1.15.1.4.jar) 
    UCHIJAAA    desertmobs{1.15.1.4 - MC 1.10.2} [Lycanites Desert Mobs](U-1.10.2-LycanitesMobsComplete-1.15.1.4.jar) 
    UCHIJAAA    forestmobs{1.15.1.4 - MC 1.10.2} [Lycanites Forest Mobs](U-1.10.2-LycanitesMobsComplete-1.15.1.4.jar) 
    UCHIJAAA    freshwatermobs{1.15.1.4 - MC 1.10.2} [Lycanites Freshwater Mobs](U-1.10.2-LycanitesMobsComplete-1.15.1.4.jar) 
    UCHIJAAA    infernomobs{1.15.1.4 - MC 1.10.2} [Lycanites Inferno Mobs](U-1.10.2-LycanitesMobsComplete-1.15.1.4.jar) 
    UCHIJAAA    junglemobs{1.15.1.4 - MC 1.10.2} [Lycanites Jungle Mobs](U-1.10.2-LycanitesMobsComplete-1.15.1.4.jar) 
    UCHIJAAA    mountainmobs{1.15.1.4 - MC 1.10.2} [Lycanites Mountain Mobs](U-1.10.2-LycanitesMobsComplete-1.15.1.4.jar) 
    UCHIJAAA    plainsmobs{1.15.1.4 - MC 1.10.2} [Lycanites Plains Mobs](U-1.10.2-LycanitesMobsComplete-1.15.1.4.jar) 
    UCHIJAAA    saltwatermobs{1.15.1.4 - MC 1.10.2} [Lycanites Saltwater Mobs](U-1.10.2-LycanitesMobsComplete-1.15.1.4.jar) 
    UCHIJAAA    shadowmobs{1.15.1.4 - MC 1.10.2} [Lycanites Shadow Mobs](U-1.10.2-LycanitesMobsComplete-1.15.1.4.jar) 
    UCHIJAAA    swampmobs{1.15.1.4 - MC 1.10.2} [Lycanites Swamp Mobs](U-1.10.2-LycanitesMobsComplete-1.15.1.4.jar) 
    UCHIJAAA    mantle{1.10.2-1.0.0.jenkins170} [Mantle](U-1.10.2-Mantle-1.0.0-D-R.jar) 
    UCHIJAAA    mobcapper{1.0.0} [Mob Capper](U-1.10.2-mobcapper-1.0.1-R.jar) 
    UCHIJAAA    modtweaker{2.0.4} [Mod Tweaker](U-1.10.2-ModTweaker2-2.0.4-R.jar) 
    UCHIJAAA    Morpheus{1.10.2-3.1.8} [Morpheus](U-1.10.2-Morpheus-3.1.8-R.jar) 
    UCHIJAAA    mysticalagriculture{1.2.4} [Mystical Agriculture](U-1.10.2-mysticalagriculture-1.2.4-R.jar) 
    UCHIJAAA    neid{1.5.0} [NotEnoughIDs](U-1.10.2-NotEnoughIDs-1.5.1-A.jar) 
    UCHIJAAA    powerinventory{2.3.0} [Overpowered Inventory](U-1.10.2-OverpoweredInventory-2.3.0-R.jar) 
    UCHIJAAA    morepaintings{2 for 1.10.2} [Paintings++](U-1.10.2-paintings++-3.1.0.0-R.jar) 
    UCHIJAAA    harvestcraft{1.9.4-1.10.2f} [Pam's HarvestCraft](U-1.10.2-Pam's HarvestCraft-1.10.2f-R.jar) 
    UCHIJAAA    thutcore{3.6.5} [ThutCore](U-1.10.2-thutcore-3.6.5.1-D-R.jar) 
    UCHIJAAA    pceditmod{1.10.2-2.0.0} [In-game NBTEdit - Pokecube Edition](U-1.10.2-Pokecube Core-4.13.6-D-R.jar) 
    UCHIJAAA    pokecube{4.13.6} [Pokécube Core](U-1.10.2-Pokecube Core-4.13.6-D-R.jar) 
    UCHIJAAA    pokecube_ml{0.1.0} [Pokecube Model Loader](U-1.10.2-Pokecube Core-4.13.6-D-R.jar) 
    UCHIJAAA    pokecube_mobs{2.3.1} [Pokécube Mobs](U-1.10.2-Pokecube Mobs-2.3.1-R.jar) 
    UCHIJAAA    pokecube_origin{@VERSION@} [Pokecube Origin](U-1.10.2-Pokecube Mobs-2.3.1-R.jar) 
    UCHIJAAA    pokecube_adventures{4.9.12} [Pokécube Revival](U-1.10.2-Pokecube Revival-4.9.12-R.jar) 
    UCHIJAAA    pokecube_compat{1.0} [Pokecube Compat](U-1.10.2-Pokecube Revival-4.9.12-R.jar) 
    UCHIJAAA    pokeplayer{@VERSION} [Pokecube Mystery Dungeon](U-1.10.2-Pokecube Revival-4.9.12-R.jar) 
    UCHIJAAA    pokecubeserverutils{1.0.0} [Pokecube Server Utils](U-1.10.2-pokecubeserverutils-1.2.0-R.jar) 
    UCHIJAAA    prefab{1.1.1.4} [Prefab](U-1.10.2-prefab-1.1.1.4-R.jar) 
    UCHIJAAA    guilib{1.0.7.2} [GUI Library](U-1.10.2-PSG Revamped-1.0.0.0-D-R.jar) 
    UCHIJAAA    paintingselgui{1.7.2.0} [PaintingSelectionGui](U-1.10.2-PSG Revamped-1.0.0.0-D-R.jar) 
    UCHIJAAA    reccomplex{1.2.1} [Recurrent Complex](U-1.10.2-RecurrentComplex-1.2.1-D-R.jar) 
    UCHIJAAA    RuinsAndConstructs{1.0.4} [RuinsAndConstructs](U-1.10.2-Ruins And Constructs-v1.0.4-R.jar) 
    UCHIJAAA    SilentLib{1.0.12} [Silent Lib](U-1.10.2-SilentLib-1.0.12-20-D-R.jar) 
    UCHIJAAA    SilentGems{2.1.1} [Silent's Gems](U-1.10.2-SilentsGems-2.1.1-77-D-R.jar) 
    UCHIJAAA    sgextraparts{1.1.0} [Silent's Gems: Extra Parts](U-1.10.2-SGExtraParts-1.1.0-5-R.jar) 
    UCHIJAAA    SimpleDimensions{1.3} [Simple Dimensions](U-1.10.2-SimpleDimensions-1.3-R.jar) 
    UCHIJAAA    spikemod{1.0} [Spike Mod](U-1.10.2-spikemod-1.0-R.jar) 
    UCHIJAAA    bq_standard{1.3.92} [Standard Expansion](U-1.10.2-StandardExpansion-1.3.92-R.jar) 
    UCHIJAAA    StevesInferno{1.1} [StevesInferno](U-1.10.2-StevesInferno-1.1-R.jar) 
    UCHIJAAA    tconstruct{1.10.2-2.5.5.jenkins393} [Tinkers' Construct](U-1.10.2-TConstruct-2.5.5-R.jar) 
    UCHIJAAA    teletoro{1.10.2-19} [TeleToro](U-1.10.2-teletoro-19-R.jar) 
    UCHIJAAA    thutessentials{1.3.1} [Thut Essentials](U-1.10.2-thutessentials-1.4.4-R.jar) 
    UCHIJAAA    thutperms{0.1.1} [Thut Permissions](U-1.10.2-thutpermissions-0.2.5-R.jar) 
    UCHIJAAA    treechopper{1.1.0a} [Tree Chopper](U-1.10.2-TreeChopper-1.1.0a-R.jar) 
    UCHIJAAA    universalcoins{1.9.4-0.5} [Universal Coins](U-1.10.2-UniversalCoins-Unofficial-Thutfix-TEST2-B.jar) 
    UCHIJAAA    waystones{2.0.8} [Waystones](U-1.10.2-Waystones-2.0.8-R.jar) 
    UCHIJAAA    wtfcore{1.10.2_v1.0} [wtfcore](U-1.10.2-WTF-Expedition-1.0-R.jar)

**Comment by AlgorithmX2** [comment]
I assume that the block inside the WTF package is WTFCORE, however I don't see any public releases for anything after 1.7 on curse, and its closed source, so I am unable to look at the method in question.

Any help?

**Comment by P3rf3ctXZer0** [comment]
Yeah

https://github.com/WhiskyTangoFawks/Expedition/tree/master/1-9Forge

**Comment by AlgorithmX2** [comment]
Strange, for some reason the state id for one of the states for the block is mapping to air.. most particular. I guess I'll detect if that happens and ignore it like I do the invalid mappings.

**Comment by AlgorithmX2** [comment]
Give  https://dvs1.progwml6.com/jenkins/job/Chisels-and-Bits/lastSuccessfulBuild/artifact/build/libs/chiselsandbits-12.0.31.jar a try

**Comment by P3rf3ctXZer0** [comment]
No problem I am on discord. If you have one.

**Comment by P3rf3ctXZer0** [comment]
Seems to have fixed it at least client side I will close this for now but if it fails server-side I will re-open it.

**Comment by AlgorithmX2** [comment]
Thanks for confirming that code only runs on the client side, so it should probably work fine.
