### ISSUE TITLE
Keybinds do not work

### ISSUE THREAD

**Issue by umnikos** [ChiselsAndBits/Chisels-and-Bits#154]
When I try to make a keybind to change the block mode on the tape from bits to blocks by pressing L, it does nothing. The way I try to change it: holding the tape while pressing L. No, there aren't any other keybinds connected to L. I tried this with the chisel (and other keybinds) and it did not work. The only keybinds that work are undo and redo.(as far as I know)

**Comment by umnikos** [comment]
My mod version is 12.4

**Comment by AlgorithmX2** [comment]
Are you sure that "ALL" other key binds but undo/redo are not working?

I have confirmed that the binds for the modes for the Tape Measure are not working but so far in my testing other binds such as rotation and chisel/bit/positive pattern modes seem to be functioning for me.

**Comment by umnikos** [comment]
No I haven't tried them all, only undo, the plane keybind and the block keybind...

I hope the bug gets fixed.

**Comment by AlgorithmX2** [comment]
If you can try https://dvs1.progwml6.com/jenkins/job/Chisels-and-Bits/33/artifact/build/libs/chiselsandbits-12.0.33.jar see if that fixes your issue(s).

**Comment by umnikos** [comment]
It did. Thanks! (but only for singleplayer, on multiplayer the keybind still doesn't work (the server doesn't have chisels and bits installed, but I saw that the tape still worked and hoped that I could use it...))

**Comment by AlgorithmX2** [comment]
How do you have an item on a server that doesn't support the mod? That shouldn't be possible, and is certainly not supported.

**Comment by umnikos** [comment]
The server is a plot creative server. You just go to the chisels and bits tab, grab the tape and use it as normal. The thing that doesn't work with the tape on multiplayer is the radial menu and the keybinds, I can change color with shift + scroll... also the item dissapears when you update your inventory (by opening a chest for example)

The chisel also worked, sooort off, you can grab it from the creative menu, then go to survival mode and start putting and taking out bits. The thing is that 1. only you can see it 2. it goes away with a right click 3. doesn't stay there when you reload the chunks.

**Comment by AlgorithmX2** [comment]
Yeah... can't really expect content mods to work on a server without them, the sever isn't capable of responding to the clients commands and directives, thus why you can't use the key-binds and radial menu, those send packets to the server.

So most of what your seeing is "client prediction" an illusion that the client creates to minimize latency which goes away once the server re-sends the blocks or chunks.

I'm honestly surprised it doesn't just crash outright.

**Comment by umnikos** [comment]
Thanks for the help anyway.
