### ISSUE TITLE
Dependency info for JEI is incorrect

### ISSUE THREAD

**Issue by mezz** [ChiselsAndBits/Chisels-and-Bits#155]
https://github.com/AlgorithmX2/Chisels-and-Bits/blob/1.10.2/src/main/java/mod/chiselsandbits/core/ChiselsAndBits.java#L60

JEI's modId should be capital JEI. Also the version string there is a Forge version, not a JEI version. ¯\_(ツ)_/¯

**Comment by AlgorithmX2** [comment]
Whoops
