### ISSUE TITLE
Can't place bits in the same space as conduits

### ISSUE THREAD

**Issue by ghost** [ChiselsAndBits/Chisels-and-Bits#156]
Non sneaking: https://clips.twitch.tv/xidik_uk/FineFlamingoMcaT
Sneaking: https://clips.twitch.tv/xidik_uk/PlainAlbatrossTriHard

Not sure if it can be fixed due to the nature of the bits.

**Comment by Phylogeny** [comment]
No, this can't be fixed due to the nature of conduits; Ender IO doesn't provide MC MultiPart support, while C&B does. As soon as Ender IO does as well, it will work. By the way, Ender IO 3.0.1.120 and C&B 12.6 are being used in those clips.

**Comment by AlgorithmX2** [comment]
Its as @Phylogeny says.

C&B works with several mods see https://minecraft.curseforge.com/projects/mcmultipart/relations/dependents?filter-related-dependents=3

Seems that it has been suggested for EnderIO some time ago,
https://github.com/SleepyTrousers/EnderIO/issues/3654

**Comment by ghost** [comment]
@Phylogeny @AlgorithmX2 as i thought :/ thanks for confirming this is on eio's end, ill go bug them more :P
