### ISSUE TITLE
Null Pointer Exception

### ISSUE THREAD

**Issue by UberAffe** [ChiselsAndBits/Chisels-and-Bits#157]
[crash log](url=http://paste.feed-the-beast.com/view/376747e4) this is from a player on my server. The have a few chisel and bit designs near them and they had chiseled blocks in their inventory(bricks shaped like slabs) I can ask them for any other information you might need.

**Comment by AlgorithmX2** [comment]
I need the crash log for starters.

**Comment by UberAffe** [comment]
whoops, there was supposed to be a hyperlink, here is the link: http://paste.feed-the-beast.com/view/376747e4

**Comment by AlgorithmX2** [comment]
The pattern in the players hand appears to be corrupt in some fashion, any idea what actions were taken to achieve that?

If you could provide the NBT on the item as well that would work.

Also the version of the mod is two versions old. I tried several approached to I thought might do it, but I didn't have any luck with the latest version, so there is either another process, or its been patched already.

**Comment by AlgorithmX2** [comment]
Any information?

**Comment by UberAffe** [comment]
No,  that player and others who experienced it were able to throw away the "broken" bits and it fixed the problem for them so I couldn't get the nbt info on them. But they say it was bit blocks that were showing up as invisible in their inventory.

**Comment by AlgorithmX2** [comment]
Alright, well I have already added some checks for the crash in the log, and since we don't have any other in formation or a way to reproduce it I guess I'll just call it fixed for now.
