### ISSUE TITLE
Error while "Tesselating block model"

### ISSUE THREAD

**Issue by timtomtim7** [ChiselsAndBits/Chisels-and-Bits#16]
I was building a book when this happened
![](http://puu.sh/nGdjs/d0225f8f55.jpg)

I had a look in the console and it had [this error](http://puu.sh/nGdGH/6021f28d34.txt).
It was being spammed in the console VERY quickly (every frame or tick, not sure which)
(Pasted in link because it's a bit big)

It was fixed after reloading the world, though oddly enough reloading the chunks didn't fix it.
Here is what it was meant to look like (not finished)
![](http://puu.sh/nGdM7/a3b474ec2a.png)

As you can see on the block one away from the far right has a piece missing, that was the piece that I added when the error started. I removed those bits to try to fix it but reloading the world is the only thing that did. (It is possible that I didn't go far enough away to reload the chunks however. Difficult to test as the error has stopped now.)
# Mod List:
- chiselsandbits-8.3.jar
- flatcoloredblocks-mc1.8.9-v1.8.jar
- InventoryTweaks-1.60-beta-33.jar
- jei_1.8.9-2.28.2.166.jar
- journeymap-1.8.8-5.1.3-unlimited.jar
- LLOverlayReloaded-1.0.5-mc1.8.9.jar
- OptiFine_1.8.9_HD_U_H3.jar

**Comment by timtomtim7** [comment]
I removed mods to see if it would stop happening, it seems to be OptiFine

**Comment by AlgorithmX2** [comment]
Please see https://github.com/AlgorithmX2/Chisels-and-Bits/issues/7

**Comment by timtomtim7** [comment]
I wasn't using shaders at all, I don't even have an shader packs installed, it just did it with optifine installed.

**Comment by AlgorithmX2** [comment]
Yes, its just optifine, for some reason its not compatible with C&B's multithreaded renderer. The issue has nothing to do with shaders, that is just what he named the issue ( I just renamed it ).

Did you see the workaround?

**Comment by timtomtim7** [comment]
No I didn't, thank you.
