### ISSUE TITLE
Server Crash - bitbag emptying.

### ISSUE THREAD

**Issue by ProsperCraft** [ChiselsAndBits/Chisels-and-Bits#161]
Modpack Allthemods 1.41

Steps to reproduce-
Take any bit bag - place any bits into - open up the bit bag -then double click the "empty" button in the upper left hand corner - server then crashes.

I saw Sponge in the stacktrace so we reproduced it without sponge.
Without Sponge mod-
https://gist.github.com/ProsperCraft/7a22535e1a750a89e6258ec7a35cac8e

With Sponge mod-
https://gist.github.com/ProsperCraft/32d585ce30badf780faef48b0f8e34f9
https://gist.github.com/ProsperCraft/aa6e57920c59ec1e9d27f6a26f98db72
https://gist.github.com/ProsperCraft/213c905f0e6da0c8fd3a13a648b8db7c
https://gist.github.com/ProsperCraft/3f11c5503ab96e8788a7383804ad6ff7

**Comment by AlgorithmX2** [comment]
https://github.com/whatthedrunk/allthemods/issues/264 - Already Fixed.
