### ISSUE TITLE
Recombining bits into original blocks

### ISSUE THREAD

**Issue by aparhatus** [ChiselsAndBits/Chisels-and-Bits#163]
When left with excess bits, one often wants to restore those back to the original blocks. Doing so by first placing down a full block with a positive pattern and then mining that block can get tedious with a large amount of blocks.

Could a more conveninet method of turning bits back into the original blocks be added, perhaps via the crafting grid?

**Comment by AlgorithmX2** [comment]
If you make a full positive pattern and craft it in the crafting table you presently get a chiseled block version that immediately converts into a real block, I've allowed it to output the original block instead, with an option to disable this function.
