### ISSUE TITLE
RFTools Builder burping on chiselled bits

### ISSUE THREAD

**Issue by xenoflot** [ChiselsAndBits/Chisels-and-Bits#164]
Hi, McJty suggested this was one for you guys to look at. https://github.com/McJty/RFTools/issues/827

I lost a few quarry cards tonight trying to disassemble an old base. The RFTools builder appears to be being reset as per https://github.com/McJty/RFTools/issues/545 in that the quarry card vanishes and the power buffer is emptied. The crash log suggests that it's burping when its hitting something from C&B.

However it wasn't consistent. To try to narrow down what was causing the problem, I pulled apart the base chunk by chunk and when I noticed C&B in the crash log, I explicitly selected a small area containing some chiseled bits and it quarried them without a problem. So sadly I can't give you a more specific pointer to where the problem is.

This base only had a tiny bit of C&B in it and I'm pretty confident that the only blocks used were quartz blocks, glowstone and EnvironmentalTech's Hardened Stone.

chiselsandbits 12.7
mcjtylib 1.10-2.20
rftools 1.10-5.58
environmentaltech 1.10.2-0.10.5g

http://pastebin.com/KwudaF6u

**Comment by AlgorithmX2** [comment]
I'm not sure why it was generating an empty C&B Item, but that was the cause, It should just produce nothing now instead of crashing.
