### ISSUE TITLE
ComputerCraft integration

### ISSUE THREAD

**Issue by za3k** [ChiselsAndBits/Chisels-and-Bits#166]
I think it would be really fun to do displays (think randomly generated maze, 3-D maps, etc) with computers.

If this sounds fun (but not fun to implement), let me know and I can probably do a pull request when I have time.

**Comment by AlgorithmX2** [comment]
If you want creative mode support just enable the "/setbit" command, other wise it will probobly require an addon to manage using bits via some peripheral.

**Comment by za3k** [comment]
Right, I was imagining the version with the peripheral (or I believe CCTweaks lets you equip any tool as a peripheral directly).

I may as well implement this, I'll play around with the mod a bit more first to make sure I understand the right way to design it.

**Comment by AlgorithmX2** [comment]
Go for it, I want to keep C&B itself on the leaner side since it tends to be complicated anyway.

The API should work very well for something like a CC Peripheral.
