### ISSUE TITLE
Crash rendering Actually Additions lamp in Enchiridon mod's Editor

### ISSUE THREAD

**Issue by kd8lvt** [ChiselsAndBits/Chisels-and-Bits#167]
I've already posted this on AA's issue tracker, so I hope you don't mind me just referencing that issue over there :) [https://github.com/Ellpeck/ActuallyAdditions/issues/351](https://github.com/Ellpeck/ActuallyAdditions/issues/351) Basically, when rendering the lamp from Actually Additions in bit form via the Enchiridion mod's book editor, it crashes the client

**Comment by AlgorithmX2** [comment]
Does it also crash when scrolling though the C&B Creative Tab?

**Comment by kd8lvt** [comment]
Let me check, just a second

**Comment by kd8lvt** [comment]
No, it doesn't. I also searched for them in the C&B tab, and they did appear.

**Comment by AlgorithmX2** [comment]
That is odd, If one gui crashed rendering the item, I'd expect it to crash in there as well.

**Comment by kd8lvt** [comment]
And it's not that bits in general are crashing, it's just the lamps

**Comment by AlgorithmX2** [comment]
Right, but if the lamp bits crash in Gui A, why not Gui B?

**Comment by kd8lvt** [comment]
No idea, maybe it's how Enchiridion handles rendering?

**Comment by AlgorithmX2** [comment]
Doubtful, have the lamps changed at all? Maybe the book has a bit displaying in it that is "no longer valid?" or have no updates or changes been made to the pack since the "book" was made?

**Comment by kd8lvt** [comment]
I updated FTBUtils and Lib, then downgraded them again because they were being buggy, I also installed and uninstalled Optifine, and I don't have any bits in the book.

**Comment by AlgorithmX2** [comment]
Ok.. so it shouldn't be a bad bit item... This is quite unusual.

**Comment by kd8lvt** [comment]
Yeah, the only thing I can think of is the item selector has a bad bit in it somehow?

**Comment by AlgorithmX2** [comment]
Seems like the only real explanation, since the C&B tab which has all the "real bits" isn't showing any issues, but why would it contain items that aren't in the creative tab?

**Comment by kd8lvt** [comment]
Exactly, it should only be able to pull from the item registry at most, preferably creative tabs.

**Comment by AlgorithmX2** [comment]
I installed Actually Additions, and Enchiridion - I was unable to reproduce the crash however, I scrolled though the entire item list in the editor and it never crashed... there was a lot of items to say the least...

I'm not sure what the deal is here.

**Comment by AlgorithmX2** [comment]
I can't reproduce the issue, are you able to reproduce this consistently? What about in a fresh instance?

Any other details to help reproduce the issue would be helpful.
