### ISSUE TITLE
Redstone signal from bits to blocks nearby.

### ISSUE THREAD

**Issue by Dushess** [ChiselsAndBits/Chisels-and-Bits#168]
As i know, Chiseled block is not chunk-section emulation. Exist any way to transmit signal from "redstone block" bit to a normal block nearby? Will not even talk about controllable redstone line inside...
I asking this because thinking about tiny redstone controlled lamp.

**Comment by AlgorithmX2** [comment]
No, there are some other MCMP Compatible mods that support redstone or other things, I'd suggest looking in that direction. For such things.

Redstone is complicated, and I'd rather avoid it for the sake of performance.

**Comment by Dushess** [comment]
Just i know right now exist only one mod, that can provide tiny redstone controlled things, LittleBlocks, but it stuck in 1.7.10. Maybe SlimeVoid team will find solution, how to adapt their mod to 1.8+
