### ISSUE TITLE
Load Issue

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [ChiselsAndBits/Chisels-and-Bits#17]
Full Log -> https://gist.github.com/DPxKnightxZero/8693f048df372c3e64ec
Partial Log -> https://gist.github.com/DPxKnightxZero/b969a569eb5786bc63c2

**Comment by AlgorithmX2** [comment]
The C&B error in your log was just a message, it didn't crash. It happened when MCMP tries to test making a part during launch.

In the next version it won't print that out anymore however. ( https://github.com/AlgorithmX2/Chisels-and-Bits/commit/c9cb679a48fd28880c82303aea626b90a152ebe4 )
