### ISSUE TITLE
Villager Pathfinding on Chisel and bits half slab

### ISSUE THREAD

**Issue by Jukari** [ChiselsAndBits/Chisels-and-Bits#170]
I used chisel and bits to make blocks into half slabs that didn't have one, like wool, and when villagers walk over them, they end up just standing there and never moving again.  Is this a bug and something that can be fixed or is it just a limitation and I need to find an alternative flooring solution?

Thanks for the wonderful mod, btw.

**Comment by AlgorithmX2** [comment]
From what I recall the AI has special cases for slabs and stairs inside of their code, rather then referring to the Blocks for details about their "shape" I'll glance into it, but from what I recall it didn't seem feasible to change.

**Comment by Dushess** [comment]
I think, this is not only C&B mod feature, I seen this behavior on FMP, any mob (but often not Villagers) often walks especially over SavedMultiparts (and simiar to Jukari standing on it) and even if I banish them, they comes back. 
P.S. With Chisels&Bits I not detected that yet.
