### ISSUE TITLE
internal exception: connection forcibly closed

### ISSUE THREAD

**Issue by esge** [ChiselsAndBits/Chisels-and-Bits#172]
Internal Exception: java.io.IOException: An existing connection was forcibly closed by remote host

this is connected with what i wrote in #81

was on a server
i placed a plane of glowstone bits, light didn't update, so i decided to relog, after that i was constantly being desconnected

**Comment by AlgorithmX2** [comment]
This doesn't really help, the server is kicking you, and I doubt it has anything to do with some slightly inaccurate lighting calculations.

You need to see the exception on the server to know whats wrong, since the client is just saying, "Nope!"
