### ISSUE TITLE
Crash on world Load/Create

### ISSUE THREAD

**Issue by vrork** [ChiselsAndBits/Chisels-and-Bits#173]
Welp, here are the logs:

https://gist.github.com/vrork/9bd6a10e3211d32d80e14ba9b5964c0b

**Comment by AlgorithmX2** [comment]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class mod.chiselsandbits.chiseledblock.data.VoxelBlob

Seems like for some reason java is not finding the class, its certainly included in the mod, so there is no reason for that.

I'd suggest reducing mod count and seeing if the issue is caused by a second issue, or perhaps your java installation.

**Comment by vrork** [comment]
Tried both alredy. It keeps happening.

**Comment by AlgorithmX2** [comment]
So you get the same error with just C&B and forge?

**Comment by vrork** [comment]
Strange, not getting it anymore... i was getting it last time i tested (i had this crash a few time on the past)

**Comment by AlgorithmX2** [comment]
its a very unusual error that makes no sense, it would be different if that class was part of a another mod, or some library, but its part of C&B, and is most certainly in the mod.

If there are more mods a core mod might be causing problems, or like I said maybe there is an issue with java.

**Comment by vrork** [comment]
Shouldnt be a problem with Jave since it works without the rest of the mods.  All the core mods are needed on the modpack, no extra ones, so i dont know. I will wait for some updates of other mods, maybe it fixes.

**Comment by APolarBaer** [comment]
started getting this while testing 12.4 and 12.5 for #181

**Comment by AlgorithmX2** [comment]
@APolarBaer thats very strange, your sure its related to the update in forge?

**Comment by APolarBaer** [comment]
no thats why ive edited the post again lol

http://pastebin.com/FfJRDXxM

**Comment by AlgorithmX2** [comment]
I still have no idea what would cause this, C&B includes that class, and theres nothing special about it. From what I have found online it seems that "Could not initialize class " indicates an issue with the class loader.

Which points to either a coremod, or forge failing that.

**Comment by APolarBaer** [comment]
Common Mods:
-Advanced Rocketry        -AppleSkin
-Aquaculture                   -Armory
-Armory Weaponry         -AutoRegLib
-Baubles                          -BetterAchievements
-Biomes O Plenty            -Blood Arsenal
-Blood Magic                   -BookshelfAPI
-Botania                           -Bullseye
-Chameleon                     -ChestTransporter
-Cooking for Blockheads  -CraftTweaker
-Crossroads                     -Cyclops Core
-Elec Core                        -Ender Core
-EnderIO                          -Ender Tanks
-Ender Thing                    -Everlasting Abilities
-Evilcraft                           -Extra Alchemy
-Extra Utilities                   -Guide API
-Hopper Ducts                  -IC2
-InfernalMobs                   -Inventory tweaks
-JEI                                   -Journeymap
-Just Enough Resources    -LibVulpes
-Mantle                            -McJtyLib
-MCMultiPart                   -Morpheus
-Multistorage                    -Natura
-NetherCore                     -NoMoreRecipeConflict
-NotEnoughIDs                 -Open Computers
-OreDictionaryConverter    -PackingTape
-Pams HC                          -Platforms
-PotionPacks                      -Progressive Automation
-Psi                                    -Psionic Upgrades
-Railcraft                            -Reliquary
-RFTools                             -RFToolsControl
-RFToolsDimensions            -Roots
-Realistic Terrain Generation   -Shetiphiancore
-Simple Corn                      -Smithscore
-Steves Carts                      -Steves Factory Manager
-StorageDrawers                 -TConstruct
-TESLA                                -TinkerIO
-Tinkers Defense                 -Tinker Tool LEveling
-Waila                                 -Waila Harvestability
