### ISSUE TITLE
Remove it

### ISSUE THREAD

**Issue by Dushess** [ChiselsAndBits/Chisels-and-Bits#175]
Even Ultra_D3 does not correct issue from [sp614x/optifine#60](https://github.com/sp614x/optifine/issues/60)
Happened only on Win XP. With both chiselsandbits-12.getTileEntitySafely-extra.jar or just 12.7
(Don't know, can you reproduce it, but it's stable for me)

My minecraft intallation is so bizarre, heh. Uhhh...

**Comment by Dushess** [comment]
Wait a second, cheching one more thing.

**Comment by AlgorithmX2** [comment]
CTM? as in the method for how Optifine / Chisel renders its blocks with different versions?

As for why you have an issue with windows XP I have no idea, but i can say I have no intention in supporting a version of windows that is 16 years old.

I also do not actually support optifine, i have gone out of my way in the past to try and get it to work with optifine in the common case, however this is just ridiculous.

**Comment by Dushess** [comment]
Just in first looking i suspected only chiselsandbits-12.getTileEntitySafely-extra, but it's not.
Right, wrong way.

**Comment by Dushess** [comment]
I suspect OS version, it working on Win 7 64bit, My XP is 32 bit, i need to check also on Win 7 32 bit.
