### ISSUE TITLE
Chiseled blocks dissapearing and reappearing.

### ISSUE THREAD

**Issue by supersannajin** [ChiselsAndBits/Chisels-and-Bits#176]
It started with me chiseling with grass blocks. After some time, the modifications I did wouldn't show up no matter what I did. I saved and quit, then came back, and that's when it really started. The two blocks that wouldn't show my modifications were invisible.
When I am chiseling blocks, they sometimes dissapear. They are still physically there. I can walk on them and break them.

I am playing Minecraft 1.8.9 with Chisel and bits version 8.12 (that's what the zip file says).
I also have lots of other mods, but I don't think they're doing it as I remember having this problem before when I didn't have them.
I do have Optifine for 1.8.9, it's possible I also had optifine back then.
I am not using custom resource packs or shaders.

I did some testing and I can tell you this:
- It doesn't seem to happen after a specific amount of modifications. Sometimes after 4, sometimes 10, 12, etc.
- When pickblocked, the blocks I place with it will usually also be invisible. It doesn't always happen. They are visible in my inventory. Replacing the original block has the same varying results.
- I am using vanilla blocks.
- I can still chisel the invisible blocks, but it won't change it's visibility.
- One block I started chiseling also stopped showing modifications after a while. I pickblocked and that looked like it was supposed to look like in while in my inventory, though it was invisible when placed. So the changes are definitely logged, just not visible. This also happens when pickblocking invisible blocks.
- ^ That same block turned invisible for a few seconds after I saved and came back, fully modified.
- One of the original two blocks turned visible again after a few minutes and stayed visible after I saved and came back. Breaking the glitched block next to it turned it invisible again.
- Pickblocking and placing unaffected blocks so far always produces visible blocks.

![ffff](https://cloud.githubusercontent.com/assets/23563422/20449147/f4c7b04c-ade7-11e6-9748-baaf3790ddad.png)
^The block I'm looking at is the glitched block mentioned in the last point. This one and the one to the right of it were the two original blocks.

I hope this is not confusing. If you want me to test some more or need some more info just ask and you shall receive.

**Comment by AlgorithmX2** [comment]
try to workaround specified here, https://github.com/AlgorithmX2/Chisels-and-Bits/issues/7#issuecomment-193875850

1.8.9 is no longer actively supported. Newer versions of C&B have this work around built in when they detect optifine.

**Comment by Dushess** [comment]
Disappearing chiseled blocks in 1.8.9 is beginning of long adventure of "will anything suddenly broke?" I think, it will not be fixed, main build is on 1.10.2. But at least here these blocks will autoupdate with lighting updating. Problem fixed in cb 11.10 on mc 1.10. If it will not help, there's 12.7 or hotfix for this version in #160

**Comment by supersannajin** [comment]
Thank you, Algorithm, but I can't seem to open the config gui. It says I don't have the right program for it.

**Comment by AlgorithmX2** [comment]
The config GUI is inside of minecraft, you select Mods > Chisels & Bit > Options from the Main Menu

**Comment by supersannajin** [comment]
Ah, sorry about that. My brother told me it was a file I had to edit.

I changed it and went back to my save, and all the blocks are normal again. Thank you very much!
