### ISSUE TITLE
antiblock-like bit possible in C&B?

### ISSUE THREAD

**Issue by rahangar** [ChiselsAndBits/Chisels-and-Bits#178]
I used Antiblocks in 1.7.10 for accents, but it looks like, as of now in 1.10.2, they don't glow - not implemented yet.

Using flat colored blocks, is there any way of creating bright bits (while not actually lighting up the environment) sort of like chisel's Antiblocks?

Are you inclined to add such a feature?

thanks

**Comment by AlgorithmX2** [comment]
As far as C&B goes, https://github.com/AlgorithmX2/Chisels-and-Bits/issues/55 is where this request goes, since that allows C&B to adjust the light value of the block.

As far as making an "antiblock" C&B dosn't add blocks, FCB could added another type of block, i'm not sure honestly, its a lot of blocks,

**Comment by rahangar** [comment]
Thanks for the reply.

I'm not sure I understand #55.  I was mainly looking to be able to have bits that I craete from existing blocks (or FCB) become bright like antiblocks (i.e. without emitting any light to the environment).

Do you still think #55 fits?

Thanks again!

**Comment by AlgorithmX2** [comment]
I'm saying that C&B doesn't add blocks, and this is a request for C&B. #55 is a request to control the "light level" of a block separate from its blocks, thus slowing glowstone or glowing FCB to not emit light. But still "glow in the dark"

A request for FCB to add "shiny" blocks that don't "glow" is something entirely separate.

**Comment by rahangar** [comment]
Thanks for the clarification.  I think I understand now.  It sounds like if #55 is implemented, then I'll get what I I'm looking for.  No need for an FCB request.  Thanks again!

**Comment by AlgorithmX2** [comment]
Alright i'll go ahead and merge this request with that one then.
