### ISSUE TITLE
Mobs Spawn in block

### ISSUE THREAD

**Issue by andrelec1** [ChiselsAndBits/Chisels-and-Bits#179]
Hello, i have a little private server with different mod including chisel&bits and mo'creature 
My house wall is full of mob ^^ ... 
![skelleton in wall ](https://cloud.githubusercontent.com/assets/3273204/20535277/7cbebe7e-b0e4-11e6-8567-7ee5ba3e89f2.png)

I don't know is your mod is faulty or if is Custom Mob Spawner for Mo' Creatures

**Comment by andrelec1** [comment]
forge version : 12.18.2.2125, Chisel & bits : 12.7, CustomMobSpawner 3.10.1, Mo' Creatures 10.0.6 
(Colossal Chests 1.4.0 ) 

I see one mob in my 5x5x5 Colossal Chest ... so i think your mod is not totaly faulty !

In first place i think you can add something for disabling spawn mob on all chiseled block but , 
if some one want chisel their floor and want mob spawning on  : / !!!

**Comment by AlgorithmX2** [comment]
Mob spawning in MC is pretty terrible in my opinion, but it is what it is. Its possibly that the spawner should be testing something else for where it can spawn things, I'm not sure how it does that, but I'll look into the vanilla mechanic to see if I can reproduce anything there.

**Comment by paille-boy** [comment]
same issue with just chisel and mo creature in 1.12.2 :/ house full of mob... it wouldn't be a issue if i wasn't playing on hardcore
