### ISSUE TITLE
Detecting performance issues while pushing C&B to its limits

### ISSUE THREAD

**Issue by rahangar** [ChiselsAndBits/Chisels-and-Bits#180]
Hello,

I have plans for very large, but very detailed build using C&B.  I've heard YouTubers indicate that C&B is quite optimized, and I haven't run into any major performance issues yet.  Awesome mod BTW.

However, given that my build will be huge I'm looking to understand a few things:

1.  Any advice...e.g. best practices that would prevent performance issues?
2.  Any indicators/metrics to watch for?  
3.  Any metric that I should look at to understand the capacity of my system so that I can scale my build back down to something it would support?

Regards,

**Comment by AlgorithmX2** [comment]
If you experience problems you can adjust several settings in the client performance tags.

For best performance less faces per block, videocards can only manage so many polygons before failing.

Overall there should simply be a gradual decline of general FPS as your system gradually approaches the point where your gfx card is stagnated.

If your build is purely cosmetic you may want to switch to use the static render by default, the dynamic one has better performance when dealing with changes, and other mods re-rendering the chunks.

In sort.. performance is complicated.

Things to Improve performance,
1. Don't make things that are empty, blocks with "inner faces" are still rendered, fill empty space where possible to eliminate extra "wasted" polygons.
2. Blocks with less detail are more performant, this boils down to more polygons = more work to render things.
3. Translucent blocks are also harder, where possible try to use opaque blocks/bits.

As for the other two, its basically just FPS, as long as nothing is going on if your FPS is high you should be fine, the limit is obviously defined by where you think the game becomes unbearable to play, most would say around 60fps.

Keep in mind that lots of things can effect FPS, and I'd say try not to focus on it too much, as long as you have a decent machine you should have a decent range.

**Comment by rahangar** [comment]
Wow.  Thank you.  That's great info, and I appreciate the fast reply.

Regarding static vs dynamic render...  where is that knob?   Are you referring to "Fancy" vs "Fast" graphics under Minecraft options menu?

thanks,

**Comment by AlgorithmX2** [comment]
No, thats refering the the many options under Mod Settings > Chisels & Bits > Client Preformance

**Comment by rahangar** [comment]
Thanks.  Sorry - I hit "close issue" by mistake I think.  Feel free to re-open if it helps your tracking, etc..

**Comment by AlgorithmX2** [comment]
No need, If your happy with the response I don't really have any thing else to add.

**Comment by rahangar** [comment]
Very happy.  Thanks.

**Comment by Dushess** [comment]
Optifine - only solution.

**Comment by AlgorithmX2** [comment]
@Dushess please stop posting on every other ticket that comes up, and please don't recommend optifine on my github, it breaks several C&B features.

**Comment by Dushess** [comment]
Right, sorry.

**Comment by rahangar** [comment]
I know this is likely a stupid question before I even ask it, but here it goes.

Regarding your first point:

- Don't make things that are empty, blocks with "inner faces" are still rendered, fill empty space where possible to eliminate extra "wasted" polygons.

Can I assume that if I fill it with clear glass (instead of empty) I won't see any improvements?  I guess this would fall under 100% translucence (relating to your third point) .... meaning that from a performance perspective, clear glass is just like empty, yes?

**Comment by AlgorithmX2** [comment]
Yes, anything with masked transparency ( glass ), or opacity based transparency ( water / stained glass ) do not cull faces, except for like materials.

If you want to improve performance by filling blocks, cobble, or stone or the like is best.

This only matters if your trying to eliminate faces you can't see. This usually only matters if your creation is opaque, but hollow, basically if that is the case, fill it with stone or cobble or something.

So in sort, yes, adding glass inside a block wouldn't help.

Also a random extra fact since It came to mind, grass is considered "mask transparent" weird stuff...

**Comment by rahangar** [comment]
Thanks again for the quick reply.
