### ISSUE TITLE
Showing textures from paintings on the faces of bits.

### ISSUE THREAD

**Issue by Dushess** [ChiselsAndBits/Chisels-and-Bits#184]
In dreams about something new and useful i thinking about this feature, if it's possible.
But idk, how to realise changing texture from paintings list, and how to implement a special block (bits) for it.
It's technically achievable or not?

**Comment by AlgorithmX2** [comment]
Paintings are not part of the standard texture atlas, and thus cannot be used in bits, since bits are parts of blocks, and not entities.

This also doesn't make much since from a C&B standpoint, its a mod about chiseling, you can't chisel paintings.
