### ISSUE TITLE
handheld filler does not work with Chisels & Bits blocks

### ISSUE THREAD

**Issue by rahangar** [ChiselsAndBits/Chisels-and-Bits#186]
I raised this issue against ActuallyAdditions, but it occurred to me that this might be a C&B issue.  If not, please disregard.

https://github.com/Ellpeck/ActuallyAdditions/issues/412

thanks,

**Comment by Ellpeck** [comment]
This is an issue with Actually Additions, so this can be closed :)

**Comment by rahangar** [comment]
thanks
