### ISSUE TITLE
Size of Draw Region size added to the hud

### ISSUE THREAD

**Issue by NanoCE** [ChiselsAndBits/Chisels-and-Bits#187]
This would be a feature that would greatly enhance the draw region function. I know this would a little bit harder to do but I believe would be a really helpful feature. I mainly use this draw region in my larger builds with chisel&bits enhancements and it can be a pain to count out the number of bits I am trying to place. Having some sort of indication of the size of an area I am trying to place/chisel would be very helpful.

**Comment by AlgorithmX2** [comment]
You might also be interested in using the tape measure.

**Comment by NanoCE** [comment]
This is very helpful and since it is already in the game then my suggestion might have to go to the back of the list. Because of the quick response, I have one more suggestion, now with the tape measure. Having some sort of outline marking where you are measuring could be quite useful to finish off the tape measure. Thanks for the quick response.

**Comment by AlgorithmX2** [comment]
I don't understand what you mean, "Outline marking?" Have you tried the tape measure yet?

**Comment by NanoCE** [comment]
I am currently using it now and maybe there should be an outline marking out the area the tape measure is measuring but currently for me there is not. Take this lightly as I'm not sure if I am using your latest release.

**Comment by AlgorithmX2** [comment]
Are you using optifine?

**Comment by NanoCE** [comment]
Forgive me then, the tape measure does show this, it is white and I am working with snow, in the middle of a bright day. This is not the best circumstance :P 

As for the enhancement, I suggested, maybe instead of a tape measure, it is added as an alt feature with the chisel. This way it is one less item in my already full inv of bits and their related bags :) Thanks for the quick replies, this mod is awesome. Just suggesting things to make it a bit better.

**Comment by NanoCE** [comment]
Maybe not.. this tape measure is pretty neat...
