### ISSUE TITLE
C&B designs merged into a stack, resulted in lost work

### ISSUE THREAD

**Issue by rahangar** [ChiselsAndBits/Chisels-and-Bits#188]
Hi Algo,

This is probably a third party issue; I've already raised it with Cyclic.  Just wanted to let you know in case you think it might be a C&B issue.

https://github.com/PrinceOfAmber/Cyclic/issues/187

**Comment by AlgorithmX2** [comment]
Yeah, whatever merged the items is at fault, since they are different NBT, and are stack limit 1. So the 'Sack' should keep them separate when dealing with them.
