### ISSUE TITLE
crash when clicking on creative tab

### ISSUE THREAD

**Issue by Sailren** [ChiselsAndBits/Chisels-and-Bits#19]
there seems to be an IOOBE between this mod and substratum

crash here: http://paste.ubuntu.com/15423211/

**Comment by AxolotlAccount** [comment]
it happened to me too

http://pastebin.com/GCJnvTJ0

**Comment by AlgorithmX2** [comment]
I've confirmed and Identified the issue, should be fixed soon.

**Comment by AlgorithmX2** [comment]
Resolved by https://github.com/AlgorithmX2/Chisels-and-Bits/commit/2eeb67b3a7262f03e8b64d9561d8f9294dd9a35e

Should be fixed in new build.
