### ISSUE TITLE
Redstone bits (always on)

### ISSUE THREAD

**Issue by acanady** [ChiselsAndBits/Chisels-and-Bits#190]
This is a feature request really, i'm not sure if it's possible but it'd be cool if you could add redstone block functionality to bits much like the glowstone block functionality. These redstone bits would just emit a redstone signal to the block space surrounding it just as a redstone block does. The level emitted would depend on the number of redstone bits present in the tile. So basically it'd be adding a [powered] variant to the normal and glowing flat colored blocks.

These bits would not read any signals at all, only emit them.

Normal redstone block bits would not emit a redstone signal, this functionality would only be possible with the flat colored blocks so that the redstone block isn't lost as a decorative bit.

Love the mod by the way Algorithm, though this was not the mod for someone like me to get. I literally spend days building stuff now because of the customizability it adds : )

**Comment by AlgorithmX2** [comment]
I'm mixed on this, I would have to cache the redstone value outside of the voxel data so that it didn't' cause performance issues which in turn adds another 4-8 bytes (32/64bit) of memory used, and 99% of them are going to be zero, I could potentially combat this with a different instance of the TE class.. but that just complicates things.

Plus adding any redstone functionality just seems like a slippery slop. C&B is mostly supposed to be focused on decorations, and maintaining good performance in that realm.

So overall, I'm just not sure I want to go down this road, IMO this adds very little, and may even cause issues with existing builds if players previously used redstone and suddenly it starts emitting signals.

**Comment by acanady** [comment]
That is fair, thanks for the quick response

**Comment by ghost** [comment]
@AlgorithmX2 could be possible with less of a performance hit if you set the redstone signal for the whole block the bit is in. Or maybe if you right-click the bit block with a bit of redstone it transforms into a different TE that looks the same but outputs redstone signal.

Or maybe I'm stupid and don't know how any of it works.

**Comment by AlgorithmX2** [comment]
@ThatGamerBlue No, thats what I was talking about with 'caching the value out side of the voxel data' basically I was saying that looking at the bits would be too slow, so I would have to keep it outside of that.

Which would be the same overhead as what your suggesting.

Which in turn requires more memory, which is the the thing I'm uncertain about.

That and the slippery slope I refer too, the one benefit that your idea has is that it wouldn't break any existing design.

**Comment by ghost** [comment]
@AlgorithmX2 ah, i thought i know nothing, thanks for confirming :P

**Comment by Drexl** [comment]
I could really use redstone functionality in chisels and bits right now. :(
When your redstone can't be hidden under your creation, and you can't have more than a one block thick wall hiding it with bits is great.

**Comment by AEnterprise** [comment]
could this maybe be achieved by making a new block that extends the current C&B stuff and defers to that for everything except added overrides to make it output redstone? this would make redstone output (on all sides) achievable by just using an extra blockid but nothing else

**Comment by ShaunDreclin** [comment]
Not totally related but if you're looking for miniature redstone, Super Circuit Maker probably does what you want here.

**Comment by Dushess** [comment]
@drexl wait for LittleTiles 1.6.0 release. Redstone wires planned. You able even convert yoir old C&B structures and then you may install wires. One more solution is revived ProjectRed, but only centered cables can be hidden, of course in 1block-thick wall.

**Comment by acanady** [comment]
@Dushess, this sounds awesome. I've never heard of little tiles before.
