### ISSUE TITLE
Bit Barrel, or some other block based bit storage.

### ISSUE THREAD

**Issue by nexitem** [ChiselsAndBits/Chisels-and-Bits#195]
I'd like it if you could store your bits somehow? Like a tank that only holds one specific bit kind but many stacks similar to the bits bag.

Right now I'm kinda forced to either delete my bits or place them somewhere for reuse. Chests are just not enough and storage drawers display the bits as small cubes so you can't see what kind of bit unless you zoom in.

**Comment by AlgorithmX2** [comment]
You try [drawers and bits](https://mods.curse.com/mc-mods/minecraft/247712-drawers-bits)? Seems like it could be useful.

As for a block to store bits, I've considered it, but for the most part it just seems like bags and placement or some other storage mod work pretty well.

**Comment by nexitem** [comment]
Yea I saw drawers and bits thanks for linking it, Only thing is that It seems to be rather hacky because if drawers has a update  most likely drawers and bits will not work anymore. ( That is what the author of the mod says btw. )

**Comment by AlgorithmX2** [comment]
I guess its that way because of how its implemented, I don't know much about it personally.

**Comment by monkeybug34** [comment]
honestly, I store my bits in block form. just keep a lump of "block of gold" in the corner to take bites out of whwn I need it. after I'm don using those bits, I put them back on the block. if it helps, I only use 1/8th grid locked chisel mode to take chunks out of my material block. it helps keep the bit count in the bag low.

**Comment by AlgorithmX2** [comment]
@monkeybug34 Thats how I generally use the mod as well, when I'm done I usually place any remaining materials back into the blocks.

However I can see the draw of some kind of storage block for them.

**Comment by nexitem** [comment]
Yea I did that myself too however you can only store so much bits in one block and soon enough you have a whole wall of chisel'dirt' that not only looks kinda ugly but also takes up way too much space.

**Comment by Utildayael** [comment]
TBH Drawers and Bits is crap. You can't put that many bits into it. :(

That's why I had the feature request for a "Bit AE" system a few months back. :)

**Comment by maxashen** [comment]
>honestly, I store my bits in block form

> soon enough you have a whole wall of chisel'dirt' that not only looks kinda ugly but also takes up way too much space

Storage and retrieval of materials is a real world problem. In the real world there are other people to supply just enough materials for the project. But even if you controlled the quarries and brickmakers and construction, you would probably store the resources in a large dedicated facility such as a stockpile or silo in a company stockyard.

I'm not saying Minecraft needs to be realistic, but in the real world it does take space and often looks ugly. So we store it somewhere else.

**Comment by brisingraerowing** [comment]
I usually play in creative, but after reading this I came up with an idea: A wall of Quantum Storage DSUs for all the bits (one DSU for each bit), possibly connected up to a Refined Storage grid system with External Storage connectors.

Quantum Storage also adds a Quantum Storage Disk to RS, so that possibly could be used as well.

**Comment by shishketti** [comment]
You know you can go into the config and change the number of bits that can be stacked right? i usually set mine to 10x the default. 

Basically my bit bag should be a singularity.

**Comment by asiekierka** [comment]
Charset Barrels will stack items to 64 stacks, but respects the Bit Bag's stack size for bits (by default, this means 64 stacks of 512 bits). They also let you extract from and insert to Bit Bags directly by left/right-clicking.

Of course, if you increase the Bit Bag's stack size in the C&B config, Charset will respect it.

**Comment by Cewkaurai** [comment]
Not sure if this is dead, but uh... Here's a kinda cool suggestion that would fit in well with this idea: A Bit Chest :D Like maybe have a kind of chest where you make the chest, and then surround it in 8 bits, and then get 1 "bit chest" out of it, possibly with say... like 10x the amount of space as a bit bag per slot?

**Comment by brisingraerowing** [comment]
There's also now [Byte Drives](https://minecraft.curseforge.com/projects/byte-drives), an integration between C&B and AE2 (with a lot of cool features planned).
