### ISSUE TITLE
chunks to bits

### ISSUE THREAD

**Issue by minrun** [ChiselsAndBits/Chisels-and-Bits#196]
It would be a very nice feature if we could create a block sized chunk into a bit block (or selection of blocks)
so map tables can be made with less intense scanning. Thank you!

**Comment by Dushess** [comment]
This is may be fully rewriting the mod, as i know, because it needs chunk-section emulation, like in LittleBlocks for 1.7.10.

upd: Yes, i understand.

**Comment by AlgorithmX2** [comment]
@minrun Someone could easily make an add on that produces chiseled bit blocks based on larger sections of the world, as long as those materials can be chiseled, however I don't think it makes sense to add this to C&B specifically its a very specialized function.

@Dushess I don't think hes asking for C&B to emulate chunks.

**Comment by Phylogeny** [comment]
@minrun I've recently added a [modeling tool](https://minecraft.curseforge.com/projects/extra-bit-manipulation/pages/items) that does just that in [Extra Bit Manipulation](https://minecraft.curseforge.com/projects/extra-bit-manipulation):

![village](https://cloud.githubusercontent.com/assets/16785880/20885470/d0460f64-baa5-11e6-861a-b441c5fdddd0.png)

![modelvillage](https://cloud.githubusercontent.com/assets/16785880/20885491/e580f77c-baa5-11e6-999d-ad2a71d0be6a.png)

By default, chiselable blocks map to their bit forms and unchiselable ones map to a config-defined default bit. A GUI allows any individual block states, and/or all states of given blocks, to be manually remapped. The maps are stored in an auto-accessed config file and/or in individual modeling tools, and initialize with mappings for all vanilla blocks (my strategy for choosing mappings was to replace blocks with high/moderate pixel color variation with ones with low pixel color variation, while trying to color match).

![bitmappinggui](https://cloud.githubusercontent.com/assets/16785880/20886047/e3cd05d0-baa8-11e6-9f29-08426794f685.png)

There are a few different drawing modes and chunk-snapping options, as well as [configs](https://minecraft.curseforge.com/projects/extra-bit-manipulation/pages/configs) for how the states are stored in the maps and for specifying the set of procedures for the modeling tool to implement when it looks for replacement bits in the event of unmapped/unchiselable blocks and the event of insufficient amounts of certain bit types in one's inventory.

**Comment by minrun** [comment]
Thank you, @Phylogeny for the tools. It will help modded map makers (not me I do this for decor for my main base) make replicas of maps to put on war tables.

updt: im not a map maker, im more of a unguided decorator thats my reasoning

**Comment by AlgorithmX2** [comment]
Why wouldn't it work for you?

**Comment by Phylogeny** [comment]
Then what are you asking for in this issue? What do you mean by "a block sized chunk into a bit block" if not a chunk in the world being converted to a chiseled block?

P.S. Editing a comment (like I'm doing right now) is fine if the person it responds to has yet to respond themselves, but it is an ineffective way of responding to a new comment, since it does not alert the person you are responding to that you have replied.

**Comment by AlgorithmX2** [comment]
@minrun What does being a map maker have to do with the feature in @Phylogeny 's mod? It seems to me its a way to do exactly what you want in game using items.

**Comment by minrun** [comment]
sorry, i was meaning i was going to use it as a guy who makes stuff then forgets to complete it. not a map maker. its a good mod (as i am now playing around with it). its just me going flinging my actions around in no visual order. again if i confused any of you, sorry.
updt:you may delete this if you want.
its serves what i asked yes its just i never answered what i thought
