### ISSUE TITLE
Chisel Designs: Notify of missing bits

### ISSUE THREAD

**Issue by Discomanco** [ChiselsAndBits/Chisels-and-Bits#197]
I made a semilarge structure, that I'm copying with 8 different Positive Chisel Designs (3x3 ring).
However, my 2 Chisel Bags are rather full with a lot of random chisel bits, so I can't stock it up with only the things I need to copy, which causes me to sometimes run out of a certain bit, not that there's none left, but not enough to put the Copy down.
That does make me having to look through the bags, taking some extra of every material (just in case), instead of just the ones I need, but I can't tell on a quick glance what it is, since I will still have like 100 of the material I need, but it needs say, 110.

So I suggest:
When holding Shift to see the total materials required, also show after if there's some missing.
Something like 
![c b missing suggestion](https://cloud.githubusercontent.com/assets/4707702/20901292/2a4d78c6-bb32-11e6-9c47-08ce1cbb4a3d.png)

**Comment by ShaunDreclin** [comment]
o/ I'd like this too.

I frequently find myself running out of bits when using blueprints and having no idea which kind I'm out of
