### ISSUE TITLE
Whitelisted & Blacklisted Bags

### ISSUE THREAD

**Issue by AlgorithmX2** [ChiselsAndBits/Chisels-and-Bits#199]
Configure A Filter for the bag, and allow only those whitelisted items into it.

**Comment by AEnterprise** [comment]
would a blacklist also be an option? togother with the whitelist you could then have one or a few types of bits only go in one bag but blacklist on another so the 2nd doesn't fill up with the excess (like when 'harvesting' alot of bits of a specific block for a build)

**Comment by AlgorithmX2** [comment]
Probably, its not much difference, if I do one might as well just add an option and do both.
