### ISSUE TITLE
Invisible Chiseled Blocks

### ISSUE THREAD

**Issue by Bulluk** [ChiselsAndBits/Chisels-and-Bits#20]
On any chunk, at the west side of the chunk border, the chiseled blocks become invisible.
any chiseled block
![chisel invisible bug](https://cloud.githubusercontent.com/assets/17952276/13900244/f739314e-ee01-11e5-866c-a1acd37bdc87.gif)

**Comment by AlgorithmX2** [comment]
Do you have optifine installed?

**Comment by Bulluk** [comment]
i forgot to mention that, yes i do

**Comment by AlgorithmX2** [comment]
Please see: https://github.com/AlgorithmX2/Chisels-and-Bits/issues/7

there is a workaround for optifine crashing C&B's multi-threaded rendered.

**Comment by Bulluk** [comment]
aight i see, thanks
