### ISSUE TITLE
Fluid bit tank inoperable [MC 1.11]

### ISSUE THREAD

**Issue by RViper80** [ChiselsAndBits/Chisels-and-Bits#201]
I am unable to put any fluids into the bit tank using buckets.  Right-clicking makes the fluid sound, but nothing else happens.

Forge 2188, C&B 13.2, nothing else loaded.

**Comment by AlgorithmX2** [comment]
https://dvs1.progwml6.com/jenkins/job/Chisels-and-Bits/60/artifact/build/libs/chiselsandbits-13.0.60.jar should resolve the issue.

**Comment by RViper80** [comment]
Yep, working with that fix, thanks.  )
