### ISSUE TITLE
[1.11]Duplication bug in bit bag

### ISSUE THREAD

**Issue by Myknakryu** [ChiselsAndBits/Chisels-and-Bits#204]
Minecraft Version: 1.11
Chisels and bits version: 13.4
Forge version: 2189

So this bug found my friend Minikreuz, when he was playing on server with chisel . He showed up this bug and i recorded that. I cannot explain what happens but i hope that video will be enough.
To make those bugged bits work you need to throw them.

Video link:
https://youtu.be/GLwmM3o972M

**Comment by AlgorithmX2** [comment]
Should be fixed in next release 13.5
