### ISSUE TITLE
[1.10.2] Client crash when "mining" a C&B block due to NPE in getPickBlock.

### ISSUE THREAD

**Issue by tetious** [ChiselsAndBits/Chisels-and-Bits#209]
This seems to happen most often when the destroyed block is combined with another FMP, such as a Refined Storage cable, but I'm not sure that's related. I can get it to happen pretty reliably when I mine a cable that I've covered with C&B. 

It doesn't seem to happen if I remove the C&B panel using a chisel. It only occurs when using a pick or similar.

https://gist.github.com/tetious/c3c5e1af9965f69e103ebe090d1cf5a8

There is a little more info in this issue: https://github.com/AlgorithmX2/Chisels-and-Bits/issues/203

**Comment by AlgorithmX2** [comment]
Try https://dl.dropboxusercontent.com/u/9117298/cb/anti-builds/chiselsandbits-12.9.jar see if that fixes it.

**Comment by tetious** [comment]
That build seems to fix the crash. Thanks! C&B is amazing, by the way! :)

**Comment by AlgorithmX2** [comment]
Thanks for confirming.
