### ISSUE TITLE
[1.11] - [Crash]: Crash on World Load - java.lang.NoSuchMethodError: net.minecraft.block.Block.canRenderInLayer

### ISSUE THREAD

**Issue by Lanse505** [ChiselsAndBits/Chisels-and-Bits#211]
**Minecraft:** 1.11
**CnB Version:** chiselandbits-13.7
**Chisel Version:** Chisel_DEV-MC1.11-0.0.8.3 [Gotten from Drullkus]

**Info:**
Crash on World Load

**"Relevant Parts":**
https://gist.github.com/Lanse505/c9ab87ff0bcd4a0bec1cfb03a3b5fbb1

**Full Log:**
https://gist.github.com/Lanse505/dea1557482ec72ff6f8af910891f8726

**Comment by Lanse505** [comment]
This is on a newly created world mind you.

**Comment by AlgorithmX2** [comment]
This looks like a Chisel Problem, I'm calling a standard Block method, and then It looks like chisel is trying to reflect a method that doesn't exist.

**Comment by Lanse505** [comment]
Oki, will poke drullkus and tterrag about it then ^^
Thanks for quick response :P

**Comment by Drullkus** [comment]
@Lanse505, discord style pings work. @drullkus @tterrag1098 but really, @minecreatr should be the one to know what might be the problem.

**Comment by tterrag1098** [comment]
https://github.com/Chisel-Team/Chisel/commit/5fc004edde47cbb3d7fe11e2bfe02e6e9357eef6
