### ISSUE TITLE
Bits missing feature

### ISSUE THREAD

**Issue by weeryan17** [ChiselsAndBits/Chisels-and-Bits#213]
It would be nice if with patterns it showed you the bits missing for placing it down eater when you try to place it it shows you in chat or maybe when you press shift over the item or something like that. It would also take the guess work out of what exactly the bit is your missing in complicated designs.

**Comment by AlgorithmX2** [comment]
Duplicate: https://github.com/AlgorithmX2/Chisels-and-Bits/issues/197
