### ISSUE TITLE
Rendering issue with some stained glass.

### ISSUE THREAD

**Issue by MarkSzita** [ChiselsAndBits/Chisels-and-Bits#214]
I made a short video to better demonstrate the issue.

https://youtu.be/EhaKOrZFeEM

**Comment by AlgorithmX2** [comment]
Please provide version details MC and C&B also confirm that you can reproduce your issue without any other mods, at a glance it looks like the glass is disappearing when it switches renders.

You can also change dynamicModelFaceCount  to a much higher value to check if this is the case, if you say raise it to 9000, it wouldn't switch renders. Thus allowing us to know if this is related to the render switch or not.

**Comment by MarkSzita** [comment]
MC 1.10.2
Latest forge and C&B.

With some testing, I found that the issues is specifically somewhere between C&B, Mekanism and the forgemultipart.

the below video contains C&B, Mekanism and Refined storage (also has multipart support cables) on 1.10.2 with the latest forge.
As you can see, the refined storage cables don't get the issue, and it only seems to be corner parts of the mekanism cables.

https://youtu.be/pHh84zictcA

I'm going to mirror the bug on the mekanism github.
thanks.
