### ISSUE TITLE
JsonModelExports.getName crash

### ISSUE THREAD

**Issue by Lyank01** [ChiselsAndBits/Chisels-and-Bits#215]
I'm tring to start my Client in my dev environment but it just crashed and i don't know how to fix it

Crash report http://pastebin.com/Q2dp08vU

**Comment by AlgorithmX2** [comment]
Looks like your using an obf jar inside a de-obf environment.

You cannot do this, if you need the API your better off building C&B in de-obf, if you don't just put it in the Mods folder.

This isn't an issue with C&B, its a environment issue with how your dev environment is setup.
