### ISSUE TITLE
Crash - During World Generation

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [ChiselsAndBits/Chisels-and-Bits#216]
https://github.com/WhiskyTangoFawks/Expedition/issues/22#issuecomment-253967933

The author believes the issue starts with Chisels and Bites so I am forwarding this issue.

**Comment by AlgorithmX2** [comment]
None of the links on the other issue link to anything.

**Comment by P3rf3ctXZer0** [comment]
Hm?
![here](https://cloud.githubusercontent.com/assets/10351221/21582442/18ab9a08-d01d-11e6-8483-adb405486bd5.PNG)
 He deleted it.

**Comment by AlgorithmX2** [comment]
I'm referring to https://gist.github.com/DPxKnightxZero/7da78feef2d08f1578df8dc237b7cbd5

and 

https://gist.github.com/DPxKnightxZero/237043df0faca7ef0424b976fff558e3

**Comment by P3rf3ctXZer0** [comment]
hm ... my gist got deleted.

**Comment by GirafiStudios** [comment]
They are still there, the problem is the username in the middle of the link.
Link 1 fixed: https://gist.github.com/P3rf3ctXZer0/237043df0faca7ef0424b976fff558e3
Link 2 fixed: https://gist.github.com/P3rf3ctXZer0/7da78feef2d08f1578df8dc237b7cbd5

**Comment by P3rf3ctXZer0** [comment]
Thank you I just figured that out too!

**Comment by AlgorithmX2** [comment]
What version of C&B is this?

**Comment by P3rf3ctXZer0** [comment]
I couldn't tell you; I forgot to add that info XD Also it was 3 months ago ... :( This issue is a dead end without that information.

**Comment by P3rf3ctXZer0** [comment]
Possibly this one 
https://minecraft.curseforge.com/projects/chisels-bits/files/2325908

**Comment by AlgorithmX2** [comment]
If that's the version its a dead issue anyway, that's like 8 versions behind.

I'd need an up-to-date crashlog with the latest version to look into it.
