### ISSUE TITLE
[1.11.2]Few bugs in newest version of minecraft.

### ISSUE THREAD

**Issue by Myknakryu** [ChiselsAndBits/Chisels-and-Bits#219]
Versions:
Minecraft version: 1.11.2
Forge version: 2201
Chisels and Bits version: 13.7

Of course i know that Chisels and bits aren't ready for 1.11.2 yet but for testing purpose i installed it. So i found few bugs. First is falling through chiseled blocks. They have no collision detection. And for me chiseled blocks looks strange. If i chisel one bit from grass block the chiseled block does not look quite the same as before.

Videos:
https://www.youtube.com/watch?v=TPFpbw1vEx4
https://youtu.be/uv0ZcCaTEWY

**Comment by AlgorithmX2** [comment]
https://dl.dropboxusercontent.com/u/9117298/cb/anti-builds/chiselsandbits-13.0.0.jar is a build made specifically against 1.11.2 - and as I assumed the collision methods changed so they reverted to the default ones which would cause the issues you saw, There is probobly a better solution then new 1.11 builds however.

But if you can test this build and report back any other bugs it will help. I'll see if I can get 1.11.2 support into the next 1.11 build when I have another few minutes to spend on it.

**Comment by Myknakryu** [comment]
Seems stable, i haven't found any bugs... two of those bugs that i posted there aren't present anymore. Thank you. Tested forge 2203 and 2204

**Comment by AlgorithmX2** [comment]
Thanks for the feedback.

**Comment by AlgorithmX2** [comment]
If you could please confirm that https://minecraft.curseforge.com/projects/chisels-bits/files/2368826 works on 1.11.2 this is a 1.11 build that should in theory be compatiable with 1.11.2 allowing me to support both versions at once...

My testing seems to indicate that it works, however if you could provide confirmation it would be helpful.

**Comment by Myknakryu** [comment]
Well it works. Thanks. Tested forge 2222.

**Comment by AlgorithmX2** [comment]
Thanks for confirming.
