### ISSUE TITLE
[1.9] Swimming in bits

### ISSUE THREAD

**Issue by pauljoda** [ChiselsAndBits/Chisels-and-Bits#22]
Seems to be possible to swim with bits that aren't water. This was able to cause this issue

https://gyazo.com/c99808d791f4f3cfc1fca7e1bcd143fb

**Comment by AlgorithmX2** [comment]
I can not reproduce, I attempted to repdouce this with tech-reborns cables and stone bits. The result was that everything worked as expected.

**Comment by pauljoda** [comment]
Grab our Neotech builds and try. It happens when bits are on pipes http://teambrmodding.com:8080/

**Comment by amadornes** [comment]
I fixed it in the latest experimental version of MCMP

**Comment by AlgorithmX2** [comment]
Closing as it was fixed in MCMP.
