### ISSUE TITLE
Pistons not pushing

### ISSUE THREAD

**Issue by etrun3** [ChiselsAndBits/Chisels-and-Bits#221]
# Enhancement Request

Just wondering if you could make chiseled blocks that are able to be moved by pistons

-Thanks

**Comment by AlgorithmX2** [comment]
Unfortunately this isn't something I can just turn on, pistons are hardcoded to ignore tile entities, this requires core modding pistons to move them, which is better left to a mod that is designed to mod pistons, and not add blocks that can be moved.

I have little doubt that a mod that did this would work fine with C&B, several mods that move blocks around seem to work with C&B without issues.

However I won't be modding pistons.

**Comment by Dushess** [comment]
Redstone++ is your answer.
