### ISSUE TITLE
[Potential Render Issue?] - [1.10.2]: Textures "Bugging Out" when Chiseled

### ISSUE THREAD

**Issue by Lanse505** [ChiselsAndBits/Chisels-and-Bits#229]
Hello!

Me and a few people on our build server have noticed issues with certain blocks rendering oddly when chiseled. 

This "odd behavior" comes in 2 ways: 
The first way is the texture simply "ignoring" or changing the texture oddly.
[(Example with Chisel Mossy Stone)](https://images-ext-1.discordapp.net/eyJ1cmwiOiJodHRwOi8vcHV1LnNoL3RtaHc1L2RiZTQ1ZjhiNDEuanBnIn0.UsFnU6T3eCzM5yZwHU2WQirukOA)

The second issue is that CnB blocks sometimes seem to "drop" bit rendering.
Either leaving blacked out bits, Invisible/see-through bits or oddly colored onces.
This has occured a few times but I've been so "good" as to not remember to take pictures >->
Will post a picture next time it happens.

Not sure if the first issue is a CnB/Chisel interaction issue or not, but it's happened in a few blocks.
Since these issue occurs on 1.10.2 I'm fully aware that we might not get a fix pushed /alt it might be fixed on the 1.11 branch. But I thought "better safe than sorry" and decided to report it.

//Best Regards
Lanse505 
Project: Horizon

**Comment by Lanse505** [comment]
Picture regarding the second issue:
http://i.imgur.com/rkZIwkG.png
http://i.imgur.com/p57ojKK.png
http://i.imgur.com/Jn53bvX.png

**Comment by Lanse505** [comment]
P.s Sometimes updating said CnB block fixes it, but it's abit "hit and miss" on that fix

**Comment by AlgorithmX2** [comment]
The textures changing are likely because chisels models are complicated, and C&B cannot use the real block models, it uses the item models, theirs not much I can do about this because chisel's block models require world context, which C&B cannot provide.

I've tested the blocks, and the only part that seems to change is the "moss" on them, the stone underneath appears to be the correct version, and isn't changing.

As for the second one, you'll need to provide a means of reproducing this.

**Comment by Lanse505** [comment]
@AlgorithmX2 
Best way to reliably reproducing that issue is by using ExtraBitManipulation and creating a CnB solid sphere, breaking your way in and looking from the inside out.

**Comment by AlgorithmX2** [comment]
Its possible that that is already fixed, there was a bug involving the API and EBM, can you test with https://dl.dropboxusercontent.com/u/9117298/cb/anti-builds/chiselsandbits-12.X.jar to see if its improved?

**Comment by Lanse505** [comment]
Tested with 12.X.
The render issue does seem to be limited to "solid" spheres.
Made a video to demonstrate:
https://www.youtube.com/watch?v=ETol2s7X1Q8&feature=youtu.be

**Comment by AlgorithmX2** [comment]
Ok, it wasn't the issue I was thinking of, It seems like its not updating the render when the neightbors are broken, I'll have to look into this.

**Comment by AlgorithmX2** [comment]
Try https://dl.dropboxusercontent.com/u/9117298/cb/anti-builds/chiselsandbits-12.X2.jar I think this might fix it.

**Comment by Lanse505** [comment]
That's fixed the update issue.
There seems to be abit of a update stutter when you break a block and it updates the CnB tile.
(Basically it blinks in and out for a second to update, nothing major)

**Comment by AlgorithmX2** [comment]
Yeah, its not too bad though, and not a lot I can do without making it be more freeze-y.

**Comment by Lanse505** [comment]
Yea I completely understand :P 
Didn't mean to imply it was something you had to fix ^^

Thanks for all the help Algo :D
