### ISSUE TITLE
Blocks aren't solid

### ISSUE THREAD

**Issue by DeadPigman17** [ChiselsAndBits/Chisels-and-Bits#230]
As you can see, I can't get on that sponge because I go through it.

![2017-01-14_20 54 50](https://cloud.githubusercontent.com/assets/22800252/21957667/f9ac4d8a-da9b-11e6-919c-25ac38859299.png)

I have version 13.8 of the mod.

**Comment by AlgorithmX2** [comment]
Are you on 1.11.2?

If so please try https://minecraft.curseforge.com/projects/chisels-bits/files/2368826
