### ISSUE TITLE
Chiseled 'Stairs' don't work correctly after changing gear

### ISSUE THREAD

**Issue by garath77** [ChiselsAndBits/Chisels-and-Bits#231]
I chiseled my own 'stairs' basically opposite the vanilla ones and they worked fine, until I changed gear, then the movement considered every other block to be a full block instead of a stair and made me jump up. Logging out and logging back in resets it, but it happens again as soon as you change any worn gear, including anything in a Baubles slot. Oddly enough, I haven't noticed the issue when changing the off-hand...

This is how my stairs are constructed. Let me know if you have any questions. Thanks
![2017-01-16_11 05 53](https://cloud.githubusercontent.com/assets/9463067/21992497/49d33d6e-dbdc-11e6-961d-9e4d3b19ba97.png)

**Comment by AlgorithmX2** [comment]
Whatever gear you switch to is probably changing the games step height to an improper value, I suggest isolating down to which piece of equipment and then reporting that step height is being reset improperly.

In older versions pre 1.8 step height was 0.5, however post 1.8 it should be 0.6 if memory serves.

Its probably a mod with some form of "Step Assist" Several mods have had this issue in the past but I don't know of any that still have it as the ones I know of have already fixed the issue.

PS: Its also possible that the equipment of the mod responsible isn't even being used, if it is checking to see if its item is not equipped with an event, if that is the case, tracking down the issue might be more difficult, and require testing by removing mods instead. ( if you do have to do this remember that mods with 'step assist' are the most likely to be responsible. )

**Comment by garath77** [comment]
You could be right about the 'Step Assist' issue. I'll play around with different gears and see what works right and what doesn't

**Comment by garath77** [comment]
Further testing indicates that the issues is tied to leggings only. Is happening with all leggings, including the vanilla ones.

**Comment by AlgorithmX2** [comment]
As i mentioned earlier the issue may reproduce without being directly related to the equipment in the mod tied to it, this means you'll have to remove mods to test them.

However, now that you've tied it to leggings, I'd think theirs probably only a handful of mods with leg armor that can do step assist in your pack?

**Comment by garath77** [comment]
Only 4 actually. Like you say, I removed each one at a time until I found the culprit. Seems to be NeoTech. I'll post in their issue tracker. Thanks for your help.

**Comment by AlgorithmX2** [comment]
No problem, glad you managed to track it down.
