### ISSUE TITLE
Chiseled Blocks doesn't get recognized as Blocks | Let light through

### ISSUE THREAD

**Issue by NitroxydeX** [ChiselsAndBits/Chisels-and-Bits#232]
Maybe there is something to enable it and I didn't found it until now but when building with Chisels & Bits they don't have a shadow and act like air so If you build a house with Chisels and Bits and building your cellar it's very bright in it because the Chiseled Blocks aren't recognized as real blocks.

Is there a solution to this phenomena?

**Comment by AlgorithmX2** [comment]
As long as a chiseled block is compressed of entirely opaque bits, it will be treated as an opaque block. This requires that the full block is opaque however, a single missing bit, or one made of glass instead of an opaque block and it will not be opaque.

Minecraft's lighting engine is very simple and cannot model complicated blocks to any success. This is visible with things like fences and slabs in vanilla.

**Comment by NitroxydeX** [comment]
So if I got this correct:
![2017-01-23_18 27 28](https://cloud.githubusercontent.com/assets/9305576/22214917/d03d2bc2-e199-11e6-81c1-f7bf98ec0770.png)

But on the other hand this happens: 
![2017-01-23_18 27 51](https://cloud.githubusercontent.com/assets/9305576/22214998/0bd5e2e6-e19a-11e6-88b1-1c3f13a47fa1.png)
![2017-01-23_18 27 56](https://cloud.githubusercontent.com/assets/9305576/22215000/0be7fa8a-e19a-11e6-8256-1025625cc2ee.png)
![2017-01-23_18 30 09](https://cloud.githubusercontent.com/assets/9305576/22214999/0be26476-e19a-11e6-8ab4-3ea0cd0007a2.png)

The block is made out of 15 plates of cobblestone and one plate of Sandstone but it is treated as an non opaque block which would mean this is a bug?

**Comment by AlgorithmX2** [comment]
What version of the mod are you using?

**Comment by NitroxydeX** [comment]
12.9 - should consider updating to 12.11 but after reading your changelogs it seems like there is no change to this specific problem. Will report back with 12.11

**Comment by NitroxydeX** [comment]
tested with 12.11. Still the same problem.

maybe it's conflicting with some settings?

**Comment by AlgorithmX2** [comment]
Its likely broken for some reason or another I'll have to look into it.

**Comment by AlgorithmX2** [comment]
This is a forge bug, fixed in 1.11 ( https://github.com/MinecraftForge/MinecraftForge/commit/e32cc2a60740f0f44567b8450dc8a4454b0cada5 )

Not much I can do unfortunately, since 1.10.2 is dead forge wise. ( also it seems to be fixed already )
