### ISSUE TITLE
my game is not opening 

### ISSUE THREAD

**Issue by alexmck345** [ChiselsAndBits/Chisels-and-Bits#234]
![2017-01-27](https://cloud.githubusercontent.com/assets/25393708/22386455/12632a50-e4cf-11e6-95aa-59706072d93a.png)

**Comment by AlgorithmX2** [comment]
It looks like you have installed something incorrectly, possibly the wrong version of forge, or the wrong version of the mod for your version of MC.

Please verify that You have the lastest forge for your version of MC, and that you have installed the correct version of the mod for the same version.

If the issue persists you'll need to provide additional details, Your MC Version, your Forge Version, you C&B Version.

Also ensure that you have used the forge installer, and place the C&B mod jar into your mods folder.

**Comment by alexmck345** [comment]
thanks that fixed the problem
