### ISSUE TITLE
Add rotation + mirror support to chiseled blocks

### ISSUE THREAD

**Issue by Ivorforce** [ChiselsAndBits/Chisels-and-Bits#235]
When a structure is randomly generated, it's often rotated and mirrored. 

You can either expose a rotational value in the block state (as Mojang does for all their blocks). 
Mojang structures (which are also capable of rotating and mirroring) expect this kind of setup from all the blocks to function properly. However, this will not 'properly' mirror the block, only the faces - which is not enough for a block with internal logic, like chiseled blocks. Only rotations will work properly.

Or you can consider implementing https://github.com/Ivorforce/IvToolkit/blob/master/src/main/java/ivorius/ivtoolkit/blocks/BlockTransformable.java (using @Optional.Interface), which I have written for this purpose. This will enable full compatibility with Recurrent Complex, but none with Mojang (until they add a rotation / mirror handler).

Both will work too, of course. If the latter is implemented, the former default practice will not be performed.

**Comment by AlgorithmX2** [comment]
Are the Mojang handlers no good? https://github.com/AlgorithmX2/Chisels-and-Bits/blob/f4268796251dfae4907bf654bdf9a121ce14d3df/src/main/java/mod/chiselsandbits/chiseledblock/TileEntityBlockChiseled.java#L413-L451

I'm a bit confused your methods seem to present no additional feature set from what I can tell.

**Comment by Ivorforce** [comment]
Nope, you are correct. Those must have been added in a more recent version.
I'll work on compatibility now :)
