### ISSUE TITLE
Custom bit grid

### ISSUE THREAD

**Issue by prado93** [ChiselsAndBits/Chisels-and-Bits#236]
an confing option to customize the bit grid to 32x32 or higher

**Comment by AlgorithmX2** [comment]
Going beyond 16x would require too many resources going to 32x would require 8x the resources. Going to 64x would require 64x the resources.

The core resources C&B needs are CPU and Memory, and I've already optimized what I think I can there, if every model suddenly required 8x the cpu time to generate it would screw many of default rendering settings off. Making even simpler models much harder to generate.

I'm afraid I can't support anything beyond 16x with the mod, going past that will only cause problems for performance and usability.
