### ISSUE TITLE
Rendering crash while scrolling through C&B creative menu

### ISSUE THREAD

**Issue by TheQuadShot** [ChiselsAndBits/Chisels-and-Bits#237]
I was looking at all the blocks in the mod pack and while scrolling through C&B creative menu I crashed, not all the time though. Sorry if this is a dupe (I didn't find anything in the db).

Here's the crash dump
http://pastebin.com/yutxngzT

Love the mod!!

Opps, derp...
Minecraft Version: 1.10.2
Forge - 1.10.2-12.18.3.2202
C&B 12.11

**Comment by AlgorithmX2** [comment]
From the crash it looks like a model is missing, rather unusual. I'll have to look into it a bit more.

**Comment by AlgorithmX2** [comment]
Please try https://dl.dropboxusercontent.com/u/9117298/cb/anti-builds/chiselsandbits-12.12.jar if it works I'll release this as a new standard build.

**Comment by TheQuadShot** [comment]
Works great. Thanks!!
