### ISSUE TITLE
Way to make invisible hit box area like above fences

### ISSUE THREAD

**Issue by Aedda** [ChiselsAndBits/Chisels-and-Bits#238]
I love C&B to death but one thing that has made me sad since I began using it is it cannot reproduce fences as mobs and players can hop right over the 1 block height. It is possible to build a second level on top but that is visible and no longer looks like a normal fence. It might be nice to have a way to extend the hit box above a structure or a way to make a structure invisible but still blocking.

**Comment by Dushess** [comment]
Here's one way, but it need a new, fully transparent, glass texture. It will be physical block but fully invisible.

**Comment by AlgorithmX2** [comment]
I believe this would be best handled not by C&B but by a mod with an invisible block.. maybe one that can be toggled as visible or invisible. ( it should be compatible with C&B Obviously )

I'm not sure if that makes sense for FCB ( transparent... is a flat color? probably not.. ) 

But on the same token I'm not sure it makes sense to make a "Solid Air" Mod either... Hmm..

**Comment by Aedda** [comment]
The problem with a transparent or like blocks that I've found however is it blocks projectiles like arrows and clicking through. A fence only blocks projectiles and clicking for its visible height but blocks movement for the additional height.

In any case I love C&B, it is a work of art, literally and figuratively.

**Comment by Dushess** [comment]
Because mobs jumps at 1block height, we can add just few bits of that glass on top of the fence.

**Comment by Aedda** [comment]
That actually seems to work pretty darn well, thank you Dushess! Never knew they didn't just as high as a player.
