### ISSUE TITLE
Losing Texture on Chisel

### ISSUE THREAD

**Issue by Utildayael** [ChiselsAndBits/Chisels-and-Bits#239]
This used to work... :)

So... scenario. Place a block that has been chiseled with Chisel mod, such as a factory block but can be any Chisel block.

Hit the block with a C&B chisel to take a bit out. Boom turns into purple/black checker no texture. Place bit back and it goes back to full block at is fine. Same if I use the diamond saw on it to try to make a slice, immediately goes to no texture.

Tried it with both Sphax and Soartex thinking it was a texture pack issue. Normal blocks work fine, for example a piece of cobblestone or wool. Ever seen this before? If not C&B, any idea what would cause that? I wasn't aware of any special texture pack requirements for C&B to work as it has always "just worked" with any texture pack that I've used. :)

Thanks!

MC 1.10.2
Forge 10.18.3.2221
Chisel and Bits 12.12
Chisel 0.0.8.11

**Comment by AlgorithmX2** [comment]
I cannot reproduce the issue with the latest code from the Chisel Repo, and C&B 12.12

https://dl.dropboxusercontent.com/u/9117298/cb/chisel_latest.png

Does this reproduce consistently? Or are there some other requirements for it to reproduce?

**Comment by Utildayael** [comment]
100% repro. 

Take any block from Chisel mod and try to use C&B on it. Poof. Missing texture. 

I will caveat that I am using Optifine as I know you've said it has caused some oddities in the past. I'll try to load er up with no Opti and maybe just Chisel/C&B and see if I can repro in a "clean" environment. 

Thanks

**Comment by SnowShock35** [comment]
I can confirm some issue exists where textures appear missing. However, like Algorithm says it doesn't occur with just Chisel and Chisel & Bits. Which means the issue occurs elsewhere. It's not foamfix either I've tested that.

**Comment by Ruaron** [comment]
Have same problem. I think you are playing Direwolf20 pack?

**Comment by SnowShock35** [comment]
Yes. I'm currently trying to figure out the issue. (I'm the one who works on Dire's pack)

**Comment by Utildayael** [comment]
Custom pack here. It's basically DW20 but with more mods as the 1.10 DW20 pack wasn't out when we started. It's Minereapers Genesis (it's on Curse). 

Glad to hear not just me. Still need to do a clean nothing but C&B/Chisel test but haven't had time yet.

**Comment by SnowShock35** [comment]
From what I can tell it's That specific version of Chisel (Again I imagine to do with something they changed in the way they render things.) 

A couple other pointers I've noticed:

- Reloading resource pack, fixes some of the issues
- Doesn't occur in 1.5.1 of DW20 pack. 
- Doesn't occur with Chisel 0.0.7.7
- Chiseled blocks aren't effected

**Comment by Ruaron** [comment]
> • Doesn't occur with Chisel 0.0.7.7

Yeap! Using this version of the mod is ok ^^
Great thx :)
p.s. btw direwolf20 pack doesn't like Flux Networks v.1.1.4 - each time u lunch your game, all networks shuts down, so u must repos  plugs and points in the world ^^

**Comment by SnowShock35** [comment]
Okay so I can confirm I'm 100% getting it with **just** the following mods:

- Chisel 0.0.8.11
- Chisel & Bits 12.12

With Forge 12.18.3.2185

![IMG](https://ss.blamesnow.co.uk/2017/02/1487539933-56decfd9.png)

Reloading textures seems to update any blocks with broken textures and then stops the issue from occurring. However, an issue with missing textures after Chiseling blocks is still present. Also, looking in the Chisel & Bits' creative tab you'll see that all Chisel blocks are missing textures. 
![IMG](https://ss.blamesnow.co.uk/2017/02/1487540145-17177430.png)

**Comment by AlgorithmX2** [comment]
What changed? Is it some how related to the forge version? Earlier you said you couldn't reproduce it.

**Comment by SnowShock35** [comment]
@AlgorithmX2 It's really odd. I can't 100% track down what it is. Besides the fact that it occurs with Chisel build higher than 0.0.7.7. 

I've tried different java versions, different forge versions and I still can't see what is causing it. 

~~@tterrag1098 Do you have any input on the issue at hand?~~

**Comment by AlgorithmX2** [comment]
Alright, well I'll offer up a test as soon as I can, something is causing the issue, and I'm working though an issue on 1.11 with missing textures.. so maybe the outcome is that it will fix this issue.

**Comment by SnowShock35** [comment]
Okay thanks Algorithm 🙂

**Comment by AlgorithmX2** [comment]
Try https://dl.dropboxusercontent.com/u/9117298/cb/1_10_2/chiselsandbits-12.0.jar and let me know how it goes.

**Comment by starg09** [comment]
Not snow, but just tested that build 😛 

Steps I went through:

1. Forge 2185 (version on DW20 pack), chisel 0.0.7.7, Curse's C&B 12.12 (Placed some chisel blocks, and removed some random bits from each one)
2. Updated chisel to 0.0.8.11, the bug happened and all blocks had no textures.
3. Updated to that C&B build, and the blocks seem to have recovered their textures :)

**Comment by SnowShock35** [comment]
@AlgorithmX2 Can confirm that 12.0 seems to be good 😄

**Comment by AlgorithmX2** [comment]
I've heard that this issue was actually resolve in a later build of chisel, can anyone confirm that its working on the new builds without the build above in use?

**Comment by starg09** [comment]
Won't be able to confirm for sure until later. But I'm almost certain it
was fixed using the build on curseforge of C&B.

**Comment by AlgorithmX2** [comment]
Well if the issue is not reproducing using the CF version of C&B, then that is probably true, since I've not released a new official build of C&B since before this issue was opened. ( Yikes! )

But if you can confirm later, that would be helpful. No rush.

I'm just trying to collect on some of these open issues that I've been losing track of.

**Comment by Utildayael** [comment]
Yes sir. It was a Chisel issue.

**Comment by starg09** [comment]
Yup, also confirming. Seems to be completely fixed! :smile:

**Comment by AlgorithmX2** [comment]
Thanks for confirming.
