### ISSUE TITLE
Unable to use mirror print

### ISSUE THREAD

**Issue by DanWehr** [ChiselsAndBits/Chisels-and-Bits#24]
On 9.5 (I never tried previous versions), after writing to a mirror print, it automatically clears when I open a crafting bench, or pick the print up (such as to move into the personal 2x2 crafting area). Because of this it can't be crafted with the positive/negative prints, and so mirroring doesn't appear to be possible right now.

**Comment by AlgorithmX2** [comment]
Fixed in https://github.com/AlgorithmX2/Chisels-and-Bits/commit/1af36e9285512f44e7b064566b70239fbeadfbe2

**Comment by AlgorithmX2** [comment]
New build should include this, 9.6

**Comment by DanWehr** [comment]
That was fast! Keep up the awesome work. LOVE this mod.
