### ISSUE TITLE
Chisel and bits + command block ?

### ISSUE THREAD

**Issue by boitameuh** [ChiselsAndBits/Chisels-and-Bits#240]
Hello,
So here I created doors through Chisel & Bits. So I wanted to know if it was possible to use the block controls to open the doors?
Thank you for your answers.

**Comment by AlgorithmX2** [comment]
C&B lets you manipulate bits with command blocks if you want ( you can enable this in the config )

I'm not sure what else you are after here. and I am not familiar with command blocks, so I have no idea what you can do with them.

If your interested in doors in particular theirs another mod "Little Tiles" which lets you create doors, and a few other things with details like C&B does. I've never sued this mod however, so I can't offer anything else about it.

**Comment by maxashen** [comment]
Yes, it is absolutely possible to use command blocks with Chisel to make functional doors. But it is a whole lot easier if you use structure blocks.

First, save a structure of your door closed, then open.
![2017-04-11_00 27 06](https://cloud.githubusercontent.com/assets/11188862/24892900/f811f8da-1e4d-11e7-865b-bf7981ed628c.png)
![2017-04-11_00 27 21](https://cloud.githubusercontent.com/assets/11188862/24892901/f8150b38-1e4d-11e7-99ae-3a7cb5b3f038.png)

Next, hook your door button up to two structure blocks in Load mode. I am using a command block here with the command `setblock ~ ~-6 ~ minecraft:redstone_wire 15`. When I punch this button, the command block sets the redstone wire below to level 15 (like a torch is next to it). The jailDoorOak_open structure load block is immediately activated, and the repeaters put a delay in before the jailDoorOak structure load block sets the door to closed again.

![2017-04-11_00 27 38](https://cloud.githubusercontent.com/assets/11188862/24892968/4de6d65e-1e4e-11e7-8a3d-22d3f3da1acc.png)
![2017-04-11_00 27 47](https://cloud.githubusercontent.com/assets/11188862/24892973/523f602c-1e4e-11e7-9591-4d30cdb3814e.png)

And here it is working!

![2017-04-11_00 28 03](https://cloud.githubusercontent.com/assets/11188862/24892999/78af1aae-1e4e-11e7-9e17-b6caa929c387.gif)
