### ISSUE TITLE
anything made of 2 or more types of bits and/or is at least 1 bit smaller than a normal block is not solid

### ISSUE THREAD

**Issue by The-Dark-Catto** [ChiselsAndBits/Chisels-and-Bits#242]

**Comment by AlgorithmX2** [comment]
Please make sure you are using the latest version of the mod, it sounds like your using an older version on 1.11.2

**Comment by The-Dark-Catto** [comment]
K. Thanks. I had 13.2, and I updated it to 13.10, and after I updated it, the glitch was gone. Also, you have made an absolutely amazing mod! I'm going to leave this issue open in case anybody needs it.
