### ISSUE TITLE
Various blocks (mostly chisel2 blocks) turning purple and black when using C&B chisel

### ISSUE THREAD

**Issue by Reliikgaming** [ChiselsAndBits/Chisels-and-Bits#243]
Hi,  Im seeing the above issue, particularly when using chisel2 limestone, jungle wood and cobble.  Also does it with non coloured hardened clay.  Is this something thats known?  Im playing on the Quantus modpack from curse and using faithful resource pack (although I tested the issue with vanilla resource pack and it was the same.

Hope you can help :)

Thanks
Reliik

**Comment by AlgorithmX2** [comment]
Please try the build towards the bottom of https://github.com/AlgorithmX2/Chisels-and-Bits/issues/239
