### ISSUE TITLE
NPE - 1 Key bound to 2 different commands 1.11.2

### ISSUE THREAD

**Issue by Dyonovan** [ChiselsAndBits/Chisels-and-Bits#244]
Not sure if this is an ExtraUtilities crash or not, but your at the top of the chain :)

Crash Report: https://gist.github.com/Dyonovan/fd355ced5733f34427f57a1c73dca801

**Comment by AlgorithmX2** [comment]
Did this crash before a world loaded? the crash is caused by the player not existing. And from the look of the callstack, it looks like its being called via some XU code, via an event.

Quite strange... I'm not sure what to make of it.

**Comment by Dyonovan** [comment]
It happened first time when I was logged in just after I switched the C&B ketbind to something that was already bound. Just wanted to get it out of the way from another keybind I was using.

Second crash was when logging in. This was all client side crashes. Server was ok
