### ISSUE TITLE
Invisible C&B Blocks + crash when paste a C&B Block selection with loaded shader

### ISSUE THREAD

**Issue by Spid3rdr4gon** [ChiselsAndBits/Chisels-and-Bits#248]
C&B-8.12 
C&B Blocks vanish sometimes and it seems to be affected to reload the complete world
the blocks doesnt vanish complete they are only invisible and the block hitbox is shown
it seems to be affected to with load and unload a shader with optifine 
not all of the blocks are vanishing they vanishing randomly and they are still invisible sometimes after a world reload
once i load a shader and all of the blocks are turning invisible i placed a copied C&B Block and the game crashed 
[crash-2017-03-18_16.26.52-client.txt](https://github.com/AlgorithmX2/Chisels-and-Bits/files/852538/crash-2017-03-18_16.26.52-client.txt)
after the crash in the same world all the blocks are visible 
block update do turn them back into invisible 
screenshots:

after loading a shader![2017-03-18_16 52 09](https://cloud.githubusercontent.com/assets/22280742/24073683/aa8eb8c8-0bfb-11e7-8bb0-a5f4ffe56666.png)

some blocks are visible some not
![2017-03-18_16 53 10](https://cloud.githubusercontent.com/assets/22280742/24073694/cb8b0aa4-0bfb-11e7-800e-f22a92d56fdf.png)

this side is visible the other completely not
![2017-03-18_16 54 48](https://cloud.githubusercontent.com/assets/22280742/24073706/eb118236-0bfb-11e7-982e-a74104cbba5c.png)

Mod List:
(forge-1.8.9-11.15.1.1902-1.8.9.jar) 
ArchitectureCraft{1.4.2} [ArchitectureCraft] (ArchitectureCraft-Mod-1.8.9.jar) 
chisel{@VERSION@} [Chisel] (Chisel-MC1.8.9-0.0.2.6 (1).jar) 
chiselsandbits{8.12} [Chisels & Bits] (chiselsandbits-8.12.jar) 
PTRModelLib{1.0.0} [PTRModelLib] (Decocraft-2.3.6.1_1.8.9.jar) 
props{2.3.6.1} [Decocraft] (Decocraft-2.3.6.1_1.8.9.jar) 
decorationmegapack{1.8.9.2} [Decoration Mega Pack] (Decoration-Mega-Pack-Mod-1.8.9.jar) 
flatcoloredblocks{mc1.8.9-v1.8} [Flat Colored Blocks] (flatcoloredblocks-mc1.8.9-v1.8.jar) 
Lantern{1.0} [Lanterns and Flashlights Mod] (Lanterns-and-Flashlights-Mod-1.8.9.jar) 
missing_pieces{1.4.0} [Missing Pieces] (Missing-Pieces-Mod-1.8.9.jar) 
cfm{3.6} [MrCrayfish's Furniture Mod] (MrCrayfishFurntiureModv3.6.1(1.8.9).jar) 
papertazermod{1.0} [Papertazers Base Mod] (Papertazer Base Mod-1.1 (1).jar) 
pokeminemeble{0.4} [PokeMine.pl Furniture/Equipment Mod] (Poke-Furnitures-beta0.4-1.8.9.jar) 
realtimeclock{1.8.8-0.4} [Real Time Clock] (Real-Time-Clock-Mod-1.8.9.jar) 
RTG{1.8.9-0.0.5} [Realistic Terrain Generation] (Realistic-Terrain-Generation-Mod-1.8.9.jar) 
roadmod{1.2} [Road Mod] (Road Mod 2.0.jar) 
roads{1.0.2} [Roads Mod] (Road-Mod-by-derfl007-1.8.9.jar) 
smf{1.4} [Scarab's Missing Furniture Mod] (smf-1.4.jar) 
worldedit{6.1.1} [WorldEdit] (WorldEdit-1.8.9.jar) 
OptiFine Version: OptiFine_1.8.9_HD_U_H7

**Comment by AlgorithmX2** [comment]
shadersmod.client.ShadersRender.setupTerrain(ShadersRender.java:55)

gcewing.architecture.BaseModClient$CustomBlockRendererDispatcher.func_175018_a(BaseModClient.java:705)

are both in the call stack for the crash. I would recommend trying without optifine and possibly try without architechteturecraft, I don't know why architecturecraft is in the trace for a block of chiseled grass, I know why optfine is there, but not the other.

I also must ask that you remove and reproduce without optifine, since if optifine is the issue, you should report it to optifine.
