### ISSUE TITLE
No Colour to tape measure lines. All Gray

### ISSUE THREAD

**Issue by Rosethorns** [ChiselsAndBits/Chisels-and-Bits#252]
When using the C&B tape measure all lines and text rendered are gray. Changing their colour in the options does nothing.

* MC Version: 1.11.2
* C&B Version: 13.10
* Do You have Optifine: no

**Comment by AlgorithmX2** [comment]
I just fired up a basic instance with C&B and the issue does not appear to be happening, it must be related to another mod changing something and not resetting it back to the way it was.

**Comment by Rosethorns** [comment]
Sorry Algo.
I forgot to update this. It is Roots 2

**Comment by JackTheRedCreeper** [comment]
Hmm, I have this error too in my modpack, but I don't have Roots 2.
I'll find what mod is borking mine and post it too, maybe there's something in common.

Edit: Found the cause, Impractical Storage. No idea why but it's messing the tapes.

**Comment by AlgorithmX2** [comment]
Any idea about something more specific? I tried installing Roots 2, but my colored lines still work? Do I need to use an item? or something else to get this to break?

**Comment by AEnterprise** [comment]
sounds like GL leakage as in the other issue

**Comment by AlgorithmX2** [comment]
@AEnterprise yes, but doesn't really narrow down the issue.

**Comment by tofof** [comment]
I'm experiencing this in the Age of Engineering pack (1.1.1c for mc1.10.2). Not always, but once it happens it seems persistent until minecraft is restarted. The pack has neither roots 2 nor impractical storage.

**Comment by AlgorithmX2** [comment]
The core issue with this is that another mod is changing GL State, and not setting it back tot he default when its done. So the responsible party needs to be tracked down and fixed.
