### ISSUE TITLE
Player-shadow doesn't render on any chiseled C&B block

### ISSUE THREAD

**Issue by vincentmet** [ChiselsAndBits/Chisels-and-Bits#253]
While i was building, i noticed that the shadow of players wasn't renderring when standing on a chiseled block :
![image](https://cloud.githubusercontent.com/assets/21321263/24323987/862a7444-117e-11e7-9110-d3072bc3fed7.png)
I also tested it with other entities, a pig for example, and the shadow also didnt show up:
![image](https://cloud.githubusercontent.com/assets/21321263/24324003/c37dcc38-117e-11e7-83aa-3136ab6ec224.png)
(This happens on both full chiseled block (16x16x16) and partually chiseled blocks (example: 14x10x6). The partual chiseled blocks i can understand, but not for the full blocks)

* MC Version: 1.10.2 (Forge-12.18.3.2254)
* C&B Version: chiselsandbits-12.12
* Do You have Optifine: No

**Comment by AlgorithmX2** [comment]
Shadows can only render on block states marked as "isFullCube" so this only will work with full blocks, but it will work.

**Comment by AlgorithmX2** [comment]
Link to build with shadows, https://www.dropbox.com/s/1a62adxtwjfcgtw/chiselsandbits-13.0.jar?dl=0
