### ISSUE TITLE
[1.11.2] Slab like forms not counting as solid for the purposes of placing beds/doors

### ISSUE THREAD

**Issue by Rosethorns** [ChiselsAndBits/Chisels-and-Bits#254]
Solid surface chiseled blocks are not counting as solid for the purpose of placing certain objects like beds and doors when they are less than a full block in size.

reproduce:
1. create a couple of top-slab-like blocks
2. try to place a bed ontop

Versions:
* MC Version: 1.11.2
* C&B Version: 1.3.10
* Do You have Optifine: no

**Comment by AlgorithmX2** [comment]
These blocks are checking for "Full Size Cubes" rather then solid tops, which requires forge patches to change which method they call.

Also for the record, beds probably aren't ever going to change, since that also requires changing spawning mechanics, that is a way more involved change.

**Comment by Rosethorns** [comment]
So to clarify, until Forge is patched to allow a change in which method is called, solving this issue is a no go?

**Comment by AlgorithmX2** [comment]
Basically if forge patches any of these, it will just work.

No change is necessarily from C&B's point of view, and I unfortunately don't have time to make the PRs myself however.

I do doubt however that the beds will make it in, because of the spawning implications.

**Comment by maxashen** [comment]
Doors correctly check for solid tops. It follows that I could place doors on chiseled top slabs.

![2017-04-09_00 34 17](https://cloud.githubusercontent.com/assets/11188862/24834770/9bfe423e-1cbc-11e7-9d94-4d20651f96d8.png)

Beds do not correctly check for solid tops, they check if the blocks underneath are fully opaque (which is deprecated by Forge). Beds also do not break if you dig under them. So place the bed on a solid block like dirt, then dig the dirt out and place your chiseled blocks underneath.

![2017-04-09_00 39 14](https://cloud.githubusercontent.com/assets/11188862/24834811/58ffcc72-1cbd-11e7-9278-f4b78728e939.png)

The weird bed behavior is a vanilla 'feature'.

**Comment by AlgorithmX2** [comment]
The weird bed behavior is weird, but it also breaks the spawn mechanic, since "it wont work" if the bed is not on an opaque block. So it sort of gets downgraded to decoration.

Nice that doors work though.

**Comment by maxashen** [comment]
If I remember correctly, for respawning to work the bed must have a valid spot under the blocks _next to it_, not under the bed itself. And even without a valid spot, it will still let you sleep - but when you wake up you may fall or suffocate. Without the valid spot, if you die you will respawn at the world spawn.

**Comment by Galindorf** [comment]
is this also why I can't place flower pots on my c&b shelves and side tables?

**Comment by AlgorithmX2** [comment]
Yes

**Comment by AlgorithmX2** [comment]
I have submitted a patch to forge on 1.12, and it has been merged.

Beds won't be changing unless vanilla changes them, I think that's about all that can be done regarding this issue.

**Comment by alphapapa** [comment]
@AlgorithmX2 So when we get the Forge update, we'll be able to put doors and flower pots on C&B blocks?  That's great!  Thank you for fixing that!

**Comment by nevercast** [comment]
Eugh looks like I'll have to finally suck it up and move to 1.12! Nice fix!
