### ISSUE TITLE
Chiseled grass blocks are always the same colour

### ISSUE THREAD

**Issue by ghost** [ChiselsAndBits/Chisels-and-Bits#257]
Chiseled grass blocks are always light green and don’t change their contrast depending on the biome.
![2017-04-01_23 59 53](https://cloud.githubusercontent.com/assets/25916106/24582776/88c92cfe-1737-11e7-93c7-ccd06324cf52.png)

****
**Minecraft version**: 1.10.2.
**Chisels & Bits version**: 12.12 (latest for 1.10.2)

Yes, I do have OptiFine (D7; latest) installed.

**Comment by AlgorithmX2** [comment]
![color_a](https://cloud.githubusercontent.com/assets/2846930/24582893/f47d0f16-16ff-11e7-8f15-554854dfd81f.png)
![color_b](https://cloud.githubusercontent.com/assets/2846930/24582894/f5f65db6-16ff-11e7-8026-d78881b21495.png)

This is how it looks for me, perhaps try without optifine?

**Comment by ghost** [comment]
It’s probably a bug with OptiFine, then.

It sucks that OptiFine causes so many issues with so many mods and that so many mods don’t support OptiFine. I’m almost considering not using OptiFine anymore, but the performance boost and the immense amount of video settings that OptiFine gives me is overpowering the reasons not to use OptiFine.
