### ISSUE TITLE
Block duplication bug

### ISSUE THREAD

**Issue by Piddagoras** [ChiselsAndBits/Chisels-and-Bits#26]
Copy type A block to positive pattern, place bits of type B block, apply pattern to type B bits with one stack of type A bits in inventory while holding a bit bag.  Application of pattern does not remove type A bits from inventory, and you can continue applying the pattern in this way to generate type A blocks with no cost.

Does not seem to depend on block type, as long as you have a single stack of the bits in your inventory and are using a different block's bits as your target for the pattern.

Bug occurred in chisels and bits version 8.4 while running the following mods with forge 11.15.1.1763
JEI, StorageDrawers, Thaumcraft, Mapwriter, Chameleon

**Comment by AlgorithmX2** [comment]
Fixed, a new build will be out shortly.
