### ISSUE TITLE
Chiseled blocks not counting as slabs/stairs

### ISSUE THREAD

**Issue by Stephenator0316** [ChiselsAndBits/Chisels-and-Bits#260]
Playing the FoolCraft modpack, and got around to chiseling some stairs for my base. But, when I walk into the blocks, I only automatically go up the first half of the block. The only way to go up is to jump or make the top half come down a pixel. Help me please! <3

For any bug reports please provide the following,

* MC Version: 1.10.2
* C&B Version: 12.12
* Do You have Optifine: No

**Comment by AlgorithmX2** [comment]
This sounds like another mod is changing the player step height.

Not much I can do, you'll need to track down the mod thats doing it and report it to them. Usually this sort of issue is related to step assist mods / items.

In old versions of MC this was 0.5, it was changed in MC 1.8 to 0.6

Here is a previous example of such an issue, https://github.com/AlgorithmX2/Chisels-and-Bits/issues/85

**Comment by Stephenator0316** [comment]
Hmmm... interesting.. Will look into it. Thanks!
