### ISSUE TITLE
Fluid Tanks not working

### ISSUE THREAD

**Issue by DSGFLynx** [ChiselsAndBits/Chisels-and-Bits#261]
I am not able to fill the fluid tanks with fluid.

For any bug reports please provide the following,

* MC Version: 1.11
* C&B Version: 13.1
* Do You have Optifine: No

**Comment by AlgorithmX2** [comment]
By what means are you adding fluid? The preferred method is buckets, C&B requires a minimum flow rate for pipes, and most mods do not support said flow rate.

**Comment by DSGFLynx** [comment]
Nevermind. Apparently I'm just a moron lol. I was doing it wrong. Thanks though :)
