### ISSUE TITLE
Existing chiseled blocks are invisible & new ones can't be made

### ISSUE THREAD

**Issue by Frost-Raven** [ChiselsAndBits/Chisels-and-Bits#262]
My chiseled blocks have all disappeared today, and when I attempt to chisel blocks they become invisible. The conflict seems to lie with Optifine, because removing it resolves both issues. My other mods aren't causing the conflict.
One thing I did notice though is that everything was fine until the latest Java update on Tuesday, April 18. I suspect that the update isn't playing well with these mods, but I don't know if the issue lies with C&B or Optifine.

![2017-04-19_03 25 25](https://cloud.githubusercontent.com/assets/27761236/25168714/94ad3956-24b2-11e7-9737-d7441a3a454c.png)
![2017-04-19_03 23 20](https://cloud.githubusercontent.com/assets/27761236/25168734/a54aff3c-24b2-11e7-9f6d-dec61324577c.png)

For any bug reports please provide the following,

* MC Version: 1.11.2
* C&B Version:13.10
* Do You have Optifine: yes

**Comment by SDUBZ** [comment]
this also happening on my server but only in certain areas is this also your experience?

**Comment by Frost-Raven** [comment]
I don't play on a server, so my experiences are probably going to vary from yours. This doesn't appeared to be an isolated incident. It's everywhere, including the Nether and in other saved files. I've also tested it in both creative mode and survival, but it doesn't make a difference. I have even gone so far as to create a brand new save, but I still experience the same issues.
I just deal with it by not using Optifine. Chunks can take longer to load, but most of my city is made of chiseled blocks, so I'd rather do without Optifine.

**Comment by Frost-Raven** [comment]
I don't know if this is useful in any way, but the issue persists with the current versions of everything.
Minecraft:  1.12
Forge: 14.21.1.2426
C & B: 14.4
Optifine: 1.12 HD U C4
Java RE: Version 8 update 144

**Comment by SynexWolf** [comment]
The bug is most likely due to optifine, don't quote me on it but I believe optifine changes how things are rendered, causing many rendering bugs with many mods...

**Comment by Frost-Raven** [comment]
I know you're retired now, but I thought I would let you know that I finally figured out how to get C&B and Optifine to work together. I had to go into C&B's configuration settings and set "default to dynamic renderer" and "disable static renderer" both to false.
