### ISSUE TITLE
[Wiki] Spelling Error on Wiki

### ISSUE THREAD

**Issue by brisingraerowing** [ChiselsAndBits/Chisels-and-Bits#264]
There is a spelling error on [this Wiki page](https://algorithmx2.github.io/Chisels-and-Bits/items/diamond-bit-saw/):

> Quickly and easily **but** blocks into slabs, panels, or other cuboid shapes.

That should be **cut**, right?

**Comment by AlgorithmX2** [comment]
Alright its fixed, thanks for pointing that out.
