### ISSUE TITLE
Game Crashes

### ISSUE THREAD

**Issue by Moving-Light** [ChiselsAndBits/Chisels-and-Bits#267]
Whenever I search up water in creative, my game crashes for some reason.  I am attaching a crash report for you to look at.
[crash-2017-05-08_17.22.15-client.txt](https://github.com/AlgorithmX2/FlatColoredBlocks/files/984888/crash-2017-05-08_17.22.15-client.txt)

For any bug reports please provide the following,

* MC Version: 1.10.2
* C&B Version: 12.12
* Do You have Optifine: yes

**Comment by AlgorithmX2** [comment]
Based on the stacktrace, com.infinityraider.infinitylib or codechicken.lib seem to be responsible.

I don't see any references to C&B in the the crash.

The item being rendered in the crash is
Item Type: com.infinityraider.agricraft.items.ItemAgriSeed - So I would go with that as the source for now.
