### ISSUE TITLE
C&B tool menu unusable with Vivecraft

### ISSUE THREAD

**Issue by mracsys** [ChiselsAndBits/Chisels-and-Bits#268]
I ran into this last week and fixed it for myself. See the attached patch files at the end of this comment. I didn't make a pull request as it changes the menu key behavior.

In seated mode, Vivecraft is grabbing the mouse immediately after C&B ungrabs it for the tool mode menu. The mouse stays in the middle of the screen and continues to control the player, preventing selection of a C&B mode.

Setting mc.currentScreen to ChiselsAndBitsMenu.instance (treating the mode menu as a regular GuiScreen) works as expected. However, the menu does not disappear after releasing the bound key. Pressing Esc closes the menu and selects the highlighted tool mode without issue. To make this more user friendly, I added the mouseClicked method to ChiselsAndBitsMenu from GuiScreen to close the menu on left mouseclick.

I also opened an issue with Vivecraft [here](https://github.com/jrbudda/Vivecraft_110/issues/92).

For any bug reports please provide the following,

* MC Version: 1.10.2
* C&B Version: 12.12
* Do You have Optifine: Yes (bundled in Vivecraft)
* Vivecraft Version: 1.10 v9 [(github)](https://github.com/jrbudda/Vivecraft_110)

Patch files:
[chisels_and_bits_vivecraft_patch-mod.chiselsandbits.client.gui.ChiselsAndBitsMenu.txt](https://github.com/AlgorithmX2/Chisels-and-Bits/files/999795/chisels_and_bits_vivecraft_patch-mod.chiselsandbits.client.gui.ChiselsAndBitsMenu.txt)
[chisels_and_bits_vivecraft_patch-mod.chiselsandbits.core.ClientSide.txt](https://github.com/AlgorithmX2/Chisels-and-Bits/files/999796/chisels_and_bits_vivecraft_patch-mod.chiselsandbits.core.ClientSide.txt)

**Comment by AlgorithmX2** [comment]
I can't really test vivecraft, however if you can make a pull request to enable this mode when vivecraft is installed ( or enabled; I really have no context to reference here ) or make it an option that would be acceptable.

I wouldn't mind pulling the fix as long as it leaves the non-vivecraft / default configuration in tact.

**Comment by mracsys** [comment]
No problem. I'll work on making this configurable when I have time.
