### ISSUE TITLE
Chiseled Blocks have no texture in Inventory.

### ISSUE THREAD

**Issue by VsnGamer** [ChiselsAndBits/Chisels-and-Bits#27]
Chisels and Bits[9.6], Forge[1.9-12.16.0.1802]
![screenshot_2](https://cloud.githubusercontent.com/assets/18006201/14001358/4b4e9ccc-f13d-11e5-9b57-c53bcb60fe9a.png)

**Comment by AlgorithmX2** [comment]
Gotta love when the simple fixes cause random bugs like this..

Fixed in next build.

**Comment by VsnGamer** [comment]
Nice !
