### ISSUE TITLE
Can't chisel certain blocks

### ISSUE THREAD

**Issue by toriswaifu** [ChiselsAndBits/Chisels-and-Bits#271]
* MC Version: 1.11.2
* C&B Version: MC1.11.2 - 0.0.9.11
* Do You have Optifine: Yes

Hey, I can't chisel some of my blocks. I'm guessing the requirements to chisel certain blocks are that it fits the average hit box, (as in the hit box of stone, cobblestone, dirt, etc,.) but with the blocks that fit this requirement, I can't chisel them. 
Example:
https://cloud.githubusercontent.com/assets/28850168/26288768/a728c762-3e66-11e7-98a9-922698cbceb2.png

The two blocks, are normal blocks, yet I can't chisel them. I checked the config, I checked the chisel options, everything I can find and they refuse to edit.
Help?

**Comment by AlgorithmX2** [comment]
Some blocks in other mods do not by default fit the requirements of being chisel-able, if you want to chisel them, I suggest you ask the mod author to use the API to mark them as chisel able, C&B doesn't white list blocks because there are far to many mods to deal with.
