### ISSUE TITLE
Veinmined chisel and bits

### ISSUE THREAD

**Issue by CamaroKing59** [ChiselsAndBits/Chisels-and-Bits#272]
https://pastebin.com/Kn4rUJ58

Crash was on a server

For any bug reports please provide the following,

* MC Version: 1.10.2
* C&B Version: 12.12
* Do You have Optifine:
no

**Comment by AlgorithmX2** [comment]
Hmm.. looks weird, but it seems fixable.

Does this crash reproduce? or was it a one off sort of crash?

**Comment by AlgorithmX2** [comment]
If possible you can test the fix with this build, https://www.dropbox.com/s/gtqsx2s57jrg5g8/chiselsandbits-12.0.jar?dl=1
