### ISSUE TITLE
[SOLVED]Cant collide with chiseled stuff!

### ISSUE THREAD

**Issue by StardustAlpha** [ChiselsAndBits/Chisels-and-Bits#273]
THIS ISSUE HAS BEEN SOLVED. IF YOU ARE GETTING THIS PROBLEM, UPDATE TO C&B 13.9 OR NEWER
For some reason, chiseled bits don't collide with the player.
I am 100% sure that this is unintended.
* MC Version: 1.11.2 release
* C&B Version: chiselsandbits-13.8.jar
* Do You have Optifine: Yes
Forge Version: 1.11.2-forge1.11.2-13.20.0.2294
LiteLoader Version: 1.11.2 snapshot

LiteLoader Mods (6)
mod-mcxray1.11-1.0.0-mc1.11.litemod
VoxelMap-Mod-1.11.2.litemod
mod_Autofish_0.7.1_mc1.11.2.litemod
mod_macros_0.14.4_for_1.11.2.litemod
mod_mineAmp_1.2.1_for_1.11.2.litemod
mod-armorshudrevived-1.1.0-beta-mc1.11.litemod

Forge Core Mods (5)
AppleCore-mc1.11.2-2.1.2.jar
Ore Core 1.11.2 (v.1.3.0).jar
Mantle-1.11.2-1.2.0.26.jar
HammerCore_1.11.2-1.7.9.jar
AutoRegLib-1.1-4.jar

Everything in the mods folder (insert number here)
![current mod list](https://cloud.githubusercontent.com/assets/28673956/26766610/90930f84-4952-11e7-92ac-80a385194050.png)

Chisel and bits config:
https://pastebin.com/58u53zcZ

**Comment by AlgorithmX2** [comment]
Why are you not using the 13.9 or 13.10? This issue was fixed in 13.9

as indicated by the change log, "Added collision methods for 1.11.2"

**Comment by StardustAlpha** [comment]
Oh. Whoops. Did not know of that update. now gonna try it

**Comment by StardustAlpha** [comment]
Its working now! Now I just need to find out how to close this issue.
