### ISSUE TITLE
Attempting to place bits in a MCMP area causes a non-collidable missing texture block to appear.

### ISSUE THREAD

**Issue by brisingraerowing** [ChiselsAndBits/Chisels-and-Bits#275]
C&B: 12.13
MC: 1.10.2
No Optifine

When trying to place a bit to cover a MCMP compatible block (e.g.  a Refined Storage cable), a full block missing texture appears and cannot be gotten rid of. It has no hitbox or collision box.

I am going to downgrade to 12.12 until this is figured out.

I'll post a screenshot shortly.

**Comment by brisingraerowing** [comment]
![2017-06-12_17 14 31](https://user-images.githubusercontent.com/250409/27055501-aa04520c-4f92-11e7-8238-34994fb43dfb.png)

**Comment by AlgorithmX2** [comment]
Confirmed and reproducible.

**Comment by AlgorithmX2** [comment]
https://www.dropbox.com/s/31wg87rkvohge0s/chiselsandbits-12.14.jar?dl=1 Can you please verify that this build fixes the issue? If there are no issues I'll push the build as an official release.

**Comment by brisingraerowing** [comment]
I'll take a look.

**Comment by brisingraerowing** [comment]
Everything seems in order

**Comment by AlgorithmX2** [comment]
Works for me!
