### ISSUE TITLE
[1.10.2] [C&B 12.14] Transparent Bits (such as glass and leaves) are completely invisible.

### ISSUE THREAD

**Issue by kirokadura** [ChiselsAndBits/Chisels-and-Bits#277]
* MC Version: 1.10.2
* C&B Version: 12.14
* Do You have Optifine: Yes, version 1.10.2_HD_U_D8 (tried multiple versions from D4 to D8)

Been using the mod at version 12.12 for a while, but yesterday I updated it to version 12.14 and now all transparent bits are completely invisible. This includes the default glass, leaves and any custom transparent block from other mods. I was using Optifine version HD_U_D4 at the time, but updating it to any other version up to D8 held the same result. I messed around with Optifine settings a bit, but nothing seems to be affecting it. Going back to 12.12 turns them visible again.

In the next picture, I have a full glass block and I'm going to replace one bit with a cobblestone one:
![2017-06-15_22 07 40](https://user-images.githubusercontent.com/29471180/27207793-c7b79156-5217-11e7-8548-e976693b7073.png)
Immediately after replacing it, every transparent bit in that blocks goes invisible. You can still see the cobblestone bit floating there:
![2017-06-15_22 07 41](https://user-images.githubusercontent.com/29471180/27207794-c7b7d1e8-5217-11e7-9baf-a2b79ddddea3.png)
Picture showing the the block outline (the one I'm looking at is a leaf block, the right one below the minimap is the glass block):
![2017-06-15_22 07 54](https://user-images.githubusercontent.com/29471180/27207795-c7bbb0c4-5217-11e7-91a3-4c7650ab40d0.png)

**Comment by AlgorithmX2** [comment]
I cannot reproduce this, it might be another optifine related issue.

**Comment by RepoDraghon** [comment]
the funny thing is, none of my same issues happened till I updated C&B to 12.12 all my other setting like Optifine were the same as before I'll check out the beta I see available...

**Comment by PSILONCRAFT** [comment]
I also experience the same as RepoDraghon

**Comment by nraikm** [comment]
![image](https://user-images.githubusercontent.com/18247709/37877700-edc16c8e-302c-11e8-9eed-16df665d8ea7.png)
I have an issue with it displaying in the inventory
