### ISSUE TITLE
[1.11.2] Funky Rendering

### ISSUE THREAD

**Issue by deathaplenty** [ChiselsAndBits/Chisels-and-Bits#278]
* MC Version: 1.11.2
* C&B Version: 13.11
* Do You have Optifine: No
* Manual crash report: https://pastebin.com/z4gY7MLa
So I'm getting some weird rendering on these banisters I made:
![2017-06-15_21 22 25](https://user-images.githubusercontent.com/16640794/27209974-d31b7330-5214-11e7-83e4-bd8eaaa0e9ae.png)

And I figured I'd let you guys know about it. If there's any other info you need, let me know.

**Comment by deathaplenty** [comment]
Update: I reloaded the world and the strange rendering has stopped. You might be chasing ghosts on this issue.

**Comment by AlgorithmX2** [comment]
I've seen this from time to time ( maybe like 6 times total over all the time I've worked on C&B ), but I was never able to find anything, and I have in cumulative time have spent days on it. ( probably )

it starts for seemly no reason, usually when I think I changed something... 

The first time I saw it I adjusted numbers and things to get it to look normal. Then I thought it was fixed.. restarted, and suddenly everything was messed up... Undid the changes, suddenly back to normal...

After that I found it a few more times, and spent a lot of time on it, though to no avail, I simply have no idea why it happens. It always vanishes when the game restarts, and everything I've tried to fix it has resulted in the non-bugged game looking just as broken ( or just not doing anything. )

**Comment by deathaplenty** [comment]
I've got another case of this for ya: 
Normal rendering at one angle:
![2017-06-20_18 53 33](https://user-images.githubusercontent.com/16640794/27360989-19713666-55ea-11e7-9a7f-e6239124675f.png)

Funky rendering at a different angle:
![2017-06-20_18 53 40](https://user-images.githubusercontent.com/16640794/27360995-1fd8febc-55ea-11e7-8b51-3c34b364cf7f.png)

Likewise, here's another forced crash report: https://pastebin.com/vf2huU5A

**Comment by AlgorithmX2** [comment]
Well That part of the issue is probably a mod disabling depth testing. I bet there is a mod, or mod block, or gui that is disabling depth and thus resulting in layers rending though one another in C&B.

Any way you can try and track down the source?

**Comment by deathaplenty** [comment]
Well, I could play a while with just C&B and slowly add my mods back. As for which of them might be disabling depth testing, I have no idea.
Another idea I have is if I disable half of my mods and play for a while, I can sort of binary search through them. I have 19 mods, so it'd take 4 divisions to get down to one mod. 
I'll try the binary search first before trying one at a time.
I never immediately have rendering issues; it normally happens after playing for a while, and even then it doesn't happen often.

**Comment by AlgorithmX2** [comment]
I understand, this sort of thing is always difficult to track down.
