### ISSUE TITLE
Lava is supposed to hurt. Right ?

### ISSUE THREAD

**Issue by VsnGamer** [ChiselsAndBits/Chisels-and-Bits#28]
Chisels and Bits[9.7], Forge[1.9-12.16.0.1804]
![screenshot_4](https://cloud.githubusercontent.com/assets/18006201/14022951/01713cc0-f1da-11e5-967b-9dc7e902d05e.png)

**Comment by AlgorithmX2** [comment]
At the moment no fluids have any special behavior, I can't really emulate mod fluids as bits, and special casing lava...  Not sure there is much of a point, I honestly thought it might be more fun this way so you can make secret entrances and stuff.

**Comment by VsnGamer** [comment]
"I honestly thought it might be more fun this way so you can make secret entrances and stuff."
Dont fix it !
You gave me some good ideas :+1:

**Comment by AlgorithmX2** [comment]
Lol, well like I said I didn't really plan on doing it anyway.
