### ISSUE TITLE
[1.11.2] Chisel & Bits cause Refined Storage parts to glitch out

### ISSUE THREAD

**Issue by Andronomos** [ChiselsAndBits/Chisels-and-Bits#285]
Not entirely sure if it's C&B's fault or RS but if I attempt to place bits in the same block space as a Refined Storage cable or importer/exporter etc.. the RS item disappears and the block space containing it glitched out and acts like there's a ghost block preventing you from breaking or placing anything. Reloading the world doesn't fix it.

EDIT: Deleting the entity data for that block space in MCEdit worked.

**MC version:** 1.11.2
**C&B version:**  13.11
**Optifine:** No

**Short clip of the bug in action**
https://gfycat.com/ThoughtfulSourHeterodontosaurus (first time using gfycat, the video starts playing at about 70% on the seek bar)

**Screenshots**
Before using C&B: http://i.imgur.com/vKYzxp0.png
While using C&B: http://i.imgur.com/GwUyGBy.png
After using C&B: http://i.imgur.com/EvlpA9P.png
Entity Data in MCEdit: http://i.imgur.com/KMRJY3k.png

**Steps to reproduce:**

**1.** Create new world.
**2.** Place 1 or more RS cables down (also happens with exporters/importers etc..).
**3.** Place some blocks around the cable so you can easily use C&B. 
**4.** Select the draw region mode and attempt to cover the cable or place a bit in the same block space.

**Comment by brisingraerowing** [comment]
What MCMultiPart version? MCMP >= 2.0.1 have a bug that causes this. Downgrade to 2.0.0 to fix it.

Ref: Beyond-Reality/Beyond-Realty-Farscapes#32

**Comment by cragrim** [comment]
Same issue for me. Downgrading to 2.0.0 as specified by BrisingrAerowing fixes it. No need to remove the block in MCEdit.
