### ISSUE TITLE
/setbit command not showing

### ISSUE THREAD

**Issue by jgrimes900** [ChiselsAndBits/Chisels-and-Bits#287]
the /setbit command is not acting like it is in the game. I can't get it to work, it does not even show in the command list.

MC Version: 1.11.2
Forge Version: 13.20.1.2393
C&B Version: 13.11
No Optifine.

**Comment by AlgorithmX2** [comment]
Have you enabled the command in your config?

**Comment by jgrimes900** [comment]
Whoops... did not know you needed to enable it...
It works now.
Sorry, case closed.
