### ISSUE TITLE
[suggestion] Select bit with chisels

### ISSUE THREAD

**Issue by Blue-Beaker** [ChiselsAndBits/Chisels-and-Bits#289]
When I middle-click any full block with any chisel in this mod, I got the original block.
I want to get a bit of the block when middle-clicking blocks with a chisel.

**Comment by AlgorithmX2** [comment]
I'm afraid the reason this is not the case, is because doing so would require a forge event. If I had the time I might do it, but I'm afraid I don't at the moment.

However There is a "Pick Bit" key bind you can use if you would rather use that, I know its not perfect however.

**Comment by AlgorithmX2** [comment]
The forge event was rejected, in the future there will be a "Pick Bit" button on the radial menu that might help.
