### ISSUE TITLE
crash loading server 1.12

### ISSUE THREAD

**Issue by redo6565** [ChiselsAndBits/Chisels-and-Bits#290]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (ResourceLoader-MC1.12-1.5.2.jar)
  BCModPlugin (zz-backpacks 1.12 - 3.2.1.jar)
  ForgelinPlugin (Forgelin-1.5.1.jar)
  CTMCorePlugin (CTM-MC1.12-0.2.0.3.jar)
  CoreMod (Aroma1997Core-1.12-1.3.0.0.b94.jar)
  MalisisCorePlugin (malisiscore-1.12-6.0.1.jar)
  ShetiPhian-ASM (shetiphiancore-1.12.0-3.5.0.2.jar)
  LoadingPlugin (Quark-r1.2-102.jar)
  Default Options (DefaultOptions_1.12-9.2.1.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63+beta.107.jar)
  AppleCore (AppleCore-mc1.12-2.2.2.jar)
Contact their authors BEFORE contacting forge

// Oh - I know what I did wrong!

Time: 7/21/17 11:14 PM
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Chisels & Bits (chiselsandbits)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/util/ITooltipFlag
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
	at java.lang.Class.privateGetPublicMethods(Unknown Source)
	at java.lang.Class.getMethods(Unknown Source)
	at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:81)
	at mod.chiselsandbits.core.ChiselsAndBits.registerWithBus(ChiselsAndBits.java:266)
	at mod.chiselsandbits.items.ItemBitBag.<init>(ItemBitBag.java:50)
	at mod.chiselsandbits.registry.ModItems.<init>(ModItems.java:45)
	at mod.chiselsandbits.core.ChiselsAndBits.preinit(ChiselsAndBits.java:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:614)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:252)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:230)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:147)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:604)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:331)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:122)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:483)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.util.ITooltipFlag
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 44 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12
	Operating System: Linux (amd64) version 3.10.0-514.16.1.el7.x86_64
	Java Version: 1.8.0_77, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 317566016 bytes (302 MB) / 934948864 bytes (891 MB) up to 6372720640 bytes (6077 MB)
	JVM Flags: 18 total; -Xms256M -Xmx6144M -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:MaxTenuringThreshold=15 -XX:MaxGCPauseMillis=30 -XX:-UseGCOverheadLimit -XX:+UseBiasedLocking -XX:SurvivorRatio=8 -XX:TargetSurvivorRatio=90 -XX:+UseCompressedOops -XX:+OptimizeStringConcat -XX:+AggressiveOpts -XX:ReservedCodeCacheSize=2048m -XX:+UseCodeCacheFlushing -XX:SoftRefLRUPolicyMSPerMB=20000 -XX:ErrorFile=/dev/null -XX:UseSSE=3
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.40 Powered by Forge 14.21.1.2420 105 mods loaded, 105 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	minecraft{1.12} [Minecraft] (minecraft.jar) 
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (custom_server.jar) 
	UCH	forge{14.21.1.2420} [Minecraft Forge] (custom_server.jar) 
	UCH	aroma1997core{1.3.0.0.b94} [Aroma1997Core] (Aroma1997Core-1.12-1.3.0.0.b94.jar) 
	UCH	backpacks16840{3.2.1} [Backpacks!] (zz-backpacks 1.12 - 3.2.1.jar) 
	UCH	uncraftingtable{1.8-beta4} [Uncrafting Table] ([1.12]UncraftingTable-1.8-beta4.jar) 
	UCH	actuallyadditions{1.12-r116} [Actually Additions] (ActuallyAdditions-1.12-r116.jar) 
	UCH	applecore{2.2.2} [AppleCore] (AppleCore-mc1.12-2.2.2.jar) 
	UCH	aroma1997corehelper{1.3.0.0.b94} [Aroma1997Core|Helper] (Aroma1997Core-1.12-1.3.0.0.b94.jar) 
	UCH	aroma1997sdimension{1.3.0.0.b37} [Aroma1997's Dimensional World] (Aroma1997s-Dimensional-World-1.12-1.3.0.0.b37.jar) 
	UCH	quark{r1.2-102} [Quark] (Quark-r1.2-102.jar) 
	UCH	autoreglib{1.3-13} [AutoRegLib] (AutoRegLib-1.3-13.jar) 
	UCH	bedbugs{@VERSION@} [Bed Bugs] (BedBugs-1.12-1.0.1.jar) 
	UCH	betterbedrockgen{6.0.1} [BetterBedrockGen] (BetterBedrockGenerator-1.12-6.1.0.jar) 
	UCH	betterbuilderswands{0.11.1} [Better Builder's Wands] (BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar) 
	UCH	bibliocraft{2.4.2} [BiblioCraft] (BiblioCraft[v2.4.2][MC1.12.0].jar) 
	UCH	biomesoplenty{7.0.0.2291} [Biomes O' Plenty] (BiomesOPlenty-1.12-7.0.0.2291-universal.jar) 
	UCH	bookshelf{2.0.415} [Bookshelf] (Bookshelf-1.12-2.0.0.415.jar) 
	UCH	codechickenlib{3.1.1.288} [CodeChicken Lib] (CodeChickenLib-1.12-3.1.1.288-universal.jar) 
	UCH	redstoneflux{2.0.1} [Redstone Flux] (RedstoneFlux-1.12-2.0.1.2-universal.jar) 
	UCH	brandonscore{2.3.0} [Brandon's Core] (BrandonsCore-1.12-2.3.0.120-universal.jar) 
	UCH	chameleon{1.12-4.1.3} [Chameleon] (Chameleon-1.12-4.1.3.jar) 
	UCH	chancecubes{1.12-3.0.1.199} [Chance Cubes] (ChanceCubes-1.12-3.0.1.199.jar) 
	UCH	chisel{MC1.12-0.0.13.14} [Chisel] (Chisel-MC1.12-0.0.13.14.jar) 
	UCE	chiselsandbits{14.1} [Chisels & Bits] (chiselsandbits-14.1.jar) 
	UCH	claybucket{1.0} [Clay Bucket] (ClayBucket-1.12-1.0.jar) 
	UCH	cofhcore{4.3.3} [CoFH Core] (CoFHCore-1.12-4.3.3.11-universal.jar) 
	UCH	cofhworld{1.0.0} [CoFH World] (CoFHWorld-1.12-1.0.0.6-universal.jar) 
	UCH	cyclopscore{0.10.9} [Cyclops Core] (CyclopsCore-1.12-0.10.9.jar) 
	UCH	ic2{2.8.7-ex112} [IndustrialCraft 2] (industrialcraft-2-2.8.7-ex112.jar) 
	UCH	commoncapabilities{1.3.4} [CommonCapabilities] (CommonCapabilities-1.12-1.3.4.jar) 
	UCH	draconicevolution{2.3.0} [Draconic Evolution] (Draconic-Evolution-1.12-2.3.0.255-universal.jar) 
	UCH	earthworks{1.3.4.3} [Earthworks] (Earthworks-1.12-1.3.4.3.jar) 
	UCH	embers{0.221} [Embers] (embers-0.221.jar) 
	UCH	everlastingabilities{1.3.1} [EverlastingAbilities] (EverlastingAbilities-1.12-1.3.1.jar) 
	UCH	extrautils2{1.0} [Extra Utilities 2] (extrautils2-1.12-1.5.1.jar) 
	UCH	zerocore{1.12-0.1.0.9} [Zero CORE] (zerocore-1.12-0.1.0.9.jar) 
	UCH	bigreactors{1.12-0.4.5.34} [Extreme Reactors] (ExtremeReactors-1.12-0.4.5.34.jar) 
	UCH	flatcoloredblocks{mc1.12-6.2} [Flat Colored Blocks] (flatcoloredblocks-mc1.12-6.2.jar) 
	UCH	jei{4.7.1.69} [Just Enough Items] (jei_1.12-4.7.1.69.jar) 
	UCH	forestry{5.4.3.137} [Forestry] (forestry_1.12-5.4.3.137.jar) 
	UCH	forgelin{1.5.1} [Shadowfacts' Forgelin] (Forgelin-1.5.1.jar) 
	UCH	mcmultipart{2.2.2} [MCMultiPart] (MCMultiPart-2.2.2.jar) 
	UCH	ftbl{0.0.0} [FTBLib] (FTBLib-4.0.5.jar) 
	UCH	ftbu{0.0.0} [FTBUtilities] (FTBUtilities-4.0.3.jar) 
	UCH	gravestone{1.8.4} [Gravestone Mod] (gravestone-1.8.4.jar) 
	UCH	waila{1.8.19} [Waila] (Hwyla-1.8.19-B33_1.12.jar) 
	UCH	mantle{1.12-1.3.0.15} [Mantle] (Mantle-1.12-1.3.0.15.jar) 
	UCH	tconstruct{1.12-2.7.1.9} [Tinkers' Construct] (TConstruct-1.12-2.7.1.9.jar) 
	UCH	tesla{1.0.60} [TESLA] (Tesla-1.12-1.0.60.jar) 
	UCH	theoneprobe{1.4.15} [The One Probe] (theoneprobe-1.12-1.4.15.jar) 
	UCH	immersiveengineering{0.12-67} [Immersive Engineering] (ImmersiveEngineering-0.12-67.jar) 
	UCH	teslacorelib{1.12-1.0.5} [Tesla Core Lib] (tesla-core-lib-1.12-1.0.5.jar) 
	UCH	industrialforegoing{1.11.2-1.0-BETA} [Industrial Foregoing] (industrialforegoing-1.12-1.0-BETA-22.jar) 
	UCH	industrialwires{1.5-15} [Industrial Wires] (IndustrialWires-1.5-15.jar) 
	UCH	integrateddynamics{0.8.1} [Integrated Dynamics] (IntegratedDynamics-1.12-0.8.1.jar) 
	UCH	integrateddynamicscompat{1.0.0} [IntegratedDynamics-Compat] (IntegratedDynamics-1.12-0.8.1.jar) 
	UCH	integratedtunnels{1.2.5} [Integrated Tunnels] (IntegratedTunnels-1.12-1.2.5.jar) 
	UCH	inventorytweaks{1.63+beta.107.015dbec} [Inventory Tweaks] (InventoryTweaks-1.63+beta.107.jar) 
	UCH	ironchest{1.12-7.0.31.818} [Iron Chest] (ironchest-1.12-7.0.31.818.jar) 
	UCH	journeymap{1.12-5.4.9} [JourneyMap] (journeymap-1.12-5.4.9.jar) 
	UCH	malisiscore{1.12-6.0.1} [MalisisCore] (malisiscore-1.12-6.0.1.jar) 
	UCH	malisisdoors{1.12-7.0.2} [MalisisDoors] (malisisdoors-1.12-7.0.2.jar) 
	UCH	minecoprocessors{1.12-1.2} [Minecoprocessors] (minecoprocessors-1.12-1.2.jar) 
	UCH	storagedrawers{1.12-5.2.5} [Storage Drawers] (StorageDrawers-1.12-5.2.9.jar) 
	UCH	refinedstorage{1.5.13} [Refined Storage] (refinedstorage-1.5.13.jar) 
	UCH	moartinkers{0.5.0} [Moar Tinkers] (moartinkers-0.5.0.jar) 
	UCH	mob_grinding_utils{0.3.2} [mob_grinding_utils] (MobGrindingUtils-0.3.2.jar) 
	UCH	morpheus{1.12-3.3.2} [Morpheus] (Morpheus-1.12-3.3.2.jar) 
	UCH	ob_stuff{1.1} [MSU: OpenBlocks Stuff] (MSU-OpenBlocks Stuff-1.1.jar) 
	UCH	mysticalagriculture{1.6.1} [Mystical Agriculture] (mysticalagriculture[1.12]-1.6.1a.jar) 
	UCH	natura{1.12-4.3.0.10} [Natura] (Natura-1.12-4.3.0.10.jar) 
	UCH	netherportalfix{1.0} [NetherPortalFix] (NetherPortalFix_1.12-5.3.1.jar) 
	UCH	notenoughwands{1.5.9} [Not Enough Wands] (notenoughwands-1.12-1.5.9.jar) 
	UCH	omegacraft{1.0.0} [Omega Craft] (Omega Craft 2.2.2 - 1.12.jar) 
	UCH	openglider{@VERSION@} [Open Glider] (OpenGlider-1.12-1.0.1.jar) 
	UCH	oretweaker{1.0.2-1.12.0} [Ore Tweaker] (Ore Tweaker-1.0.2-1.12.0.jar) 
	UCH	getalltheseeds{1.12a} [Pam's Get all the Seeds!] (Pam's Get all the Seeds! 1.12a.jar) 
	UCH	harvestcraft{1.11.2i} [Pam's HarvestCraft] (Pam's HarvestCraft 1.12 Alpha - RECIPES ARE BROKEN.jar) 
	UCH	shetiphiancore{3.5.0.2} [ShetiPhian-Core] (shetiphiancore-1.12.0-3.5.0.2.jar) 
	UCH	platforms{1.4.0.1} [Platforms] (platforms-1.12.0-1.4.0.1.jar) 
	UCH	quickleafdecay{1.2.3} [Quick Leaf Decay] (QuickLeafDecay-MC1.12-1.2.3.jar) 
	UCH	reborncore{3.2.5.88} [Reborn Core] (RebornCore-1.12-3.2.5.88-universal.jar) 
	UCH	rftools{6.12} [RFTools] (rftools-1.12-6.12.jar) 
	UCH	rftoolsdim{5.04} [RFTools Dimensions] (rftoolsdim-1.12-5.04.jar) 
	UCH	roots{0.025} [Roots 2] (roots-2-0.025.jar) 
	UCH	lteleporters{1.11.2-2.1.5} [Simple Teleporters] (simpleteleporters-1.12-2.1.5.jar) 
	UCH	simplyconveyors{3.0.6} [Simply Conveyors & More] (SimplyConveyors-4.0.4.jar) 
	UCH	skyresources{2.0.18} [Sky Resources 2] (skyresources-2.0.18.jar) 
	UCH	soulshardstow{1.12-2.7.3-52} [Soul Shards - The Old Ways] (SoulShards-TOW-1.12-2.7.3-52.jar) 
	UCH	stevescarts{${version}} [Steve's Carts 2] (StevesCarts-1.12-2.4.5.29.jar) 
	UCH	storagedrawersextra{@VERSION@} [Storage Drawers Extras] (StorageDrawersExtras-1.12-3.1.0.jar) 
	UCH	tails{1.12-1.10.0} [Tails] (Tails-1.12-1.10.0.jar) 
	UCH	thermalfoundation{2.3.3} [Thermal Foundation] (ThermalFoundation-1.12-2.3.3.10-universal.jar) 
	UCH	thermaldynamics{2.3.3} [Thermal Dynamics] (ThermalDynamics-1.12-2.3.3.10-universal.jar) 
	UCH	thermalexpansion{5.3.3} [Thermal Expansion] (ThermalExpansion-1.12-5.3.3.15-universal.jar) 
	UCH	torchmaster{1.4.3.8} [TorchMaster] (torchmaster_1.12-1.4.3.8.jar) 
	UCH	traverse{1.2.1} [Traverse] (Traverse-1.12-1.2.1-22.jar) 
	UCH	usefulnullifiers{1.4.1} [Useful Nullifiers] (usefulnullifiers-1.4.1.jar) 
	UCH	vc{5.0.6} [ViesCraft] (ViesCraft-1.12.0-5.0.6.jar) 
	UCH	xnet{1.3.5} [XNet] (xnet-1.12-1.3.5.jar) 
	UCH	yabba{1.12-0.5.3} [YABBA] (YABBA-1.12-0.5.3.jar) 
	UCH	gravelores{1.5} [Gravel Ores] (gravelores-1.5.jar) 
	UCH	teslacoreregistries{1.12-1.0.5} [Tesla Core Registries] (tesla-core-lib-1.12-1.0.5.jar) 
	Loaded coremods (and transformers): 
LoadingPlugin (ResourceLoader-MC1.12-1.5.2.jar)
  lumien.resourceloader.asm.ClassTransformer
BCModPlugin (zz-backpacks 1.12 - 3.2.1.jar)
  brad16840.common.asm.ClassTransformer
ForgelinPlugin (Forgelin-1.5.1.jar)
  
CTMCorePlugin (CTM-MC1.12-0.2.0.3.jar)
  team.chisel.ctm.client.asm.CTMTransformer
CoreMod (Aroma1997Core-1.12-1.3.0.0.b94.jar)
  
MalisisCorePlugin (malisiscore-1.12-6.0.1.jar)
  net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
  net.malisis.core.util.chunkblock.ChunkBlockTransformer
  net.malisis.core.renderer.transformer.MalisisRendererTransformer
  net.malisis.core.renderer.icon.asm.TextureMapTransformer
  net.malisis.core.util.clientnotif.ClientNotifTransformer
ShetiPhian-ASM (shetiphiancore-1.12.0-3.5.0.2.jar)
  shetiphian.asm.ClassTransformer
LoadingPlugin (Quark-r1.2-102.jar)
  vazkii.quark.base.asm.ClassTransformer
Default Options (DefaultOptions_1.12-9.2.1.jar)
  net.blay09.mods.defaultoptions.coremod.DefaultOptionsClassTransformer
Inventory Tweaks Coremod (InventoryTweaks-1.63+beta.107.jar)
  invtweaks.forge.asm.ContainerTransformer
AppleCore (AppleCore-mc1.12-2.2.2.jar)
  squeek.applecore.asm.TransformerModuleHandler
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- theoneprobeIntegration (Enabled/Not Forced)

	Pulsar/natura loaded Pulses: 
		- NaturaCommons (Enabled/Forced)
		- NaturaOverworld (Enabled/Not Forced)
		- NaturaNether (Enabled/Not Forced)
		- NaturaDecorative (Enabled/Not Forced)
		- NaturaTools (Enabled/Not Forced)
		- NaturaEntities (Enabled/Not Forced)
		- NaturaOredict (Enabled/Forced)
		- NaturaWorld (Enabled/Not Forced)

	RebornCore: 
		Plugin Engine: 0
		RebornCore Version: 3.2.5.88
		Runtime Debofucsation 1
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

For any bug reports please provide the following,

* MC Version:
* C&B Version:
* Do You have Optifine:

**Comment by redo6565** [comment]
this is for 1.12 the release that was an hour ago

**Comment by AlgorithmX2** [comment]
Yeah, I figured. And it figures I forget something silly like testing the server.

**Comment by redo6565** [comment]
lol it happens i do that too when making my modpack. i upload becuase it work in Single player and then and to my server and then BOOM! there goes that idea

**Comment by AlgorithmX2** [comment]
Alright I pushed a new build, should resolve this.
