### ISSUE TITLE
[1.12] Bit Items Appear in All Creative Tabs

### ISSUE THREAD

**Issue by officialMECH** [ChiselsAndBits/Chisels-and-Bits#291]
Every default Creative Tab shows the entire collection of Chiseled Bit items. I'm unsure if this persists with other modded tabs, and I assume this is not intended.

* MC Version: 1.12 (forge-14.21.1.2420)
* C&B Version: chiselsandbits-14.2
* Optifine Not Loaded

![2017-07-22_13 47 31](https://user-images.githubusercontent.com/28495960/28493868-798c3c72-6ee4-11e7-9077-0048e5f5b299.png)

**Comment by AlgorithmX2** [comment]
I was just saving you a click, now you can just get bits from any tab!

Will be fixed in the next release.
