### ISSUE TITLE
Water bit causes waterfall next to actual water

### ISSUE THREAD

**Issue by RightInfinity** [ChiselsAndBits/Chisels-and-Bits#293]
* MC Version: 1.11.2
* C&B Version: 13.10
* Do You have Optifine: Yes, HD_U_C3

I'm building an in-water consctruction and have found that water bits cause a "waterfall" next to actual water
I know they render at a different height, but the difference is so minute that it's ignorable.

 In the picture all of these sections aren't playing nice with the water bits I placed their to prevent this look.  Is there any way to fix this and create a seamless look??

![2017-07-25_14 19 23](https://user-images.githubusercontent.com/9588560/28555831-a6ef723e-7145-11e7-9eb4-441158c42455.png)

**Comment by n-aspen** [comment]
![2017-07-29_21 44 09](https://user-images.githubusercontent.com/16448318/28749960-2014e392-74a7-11e7-80ef-e8149c460f22.png)

still happens without optifine same optifine version fresh install, helping out because this is very annoying :)

**Comment by tobi1449** [comment]
If you have the mod "RandomThings" you should take a look at its config. There's a setting that apparently fixes this.
