### ISSUE TITLE
1.12

### ISSUE THREAD

**Issue by ghost** [ChiselsAndBits/Chisels-and-Bits#294]
* MC Version: 1.12
* C&B Version: 14.3
* Do You have OptiFine: Yes.

The mod causes the game to stop responding randomly when loading a block that has been affected by chisel and bits.
I also can't exactly remember, but either placing a chisel block or chiseling a block causes crashes. (Log unavailable)

**Comment by AlgorithmX2** [comment]
I assume you mean it locks up, and not crashes. 

If this is the case, please wait for this to happen again, and when it happens, follow the directions here, http://ae-mod.info/profiling/ send me the resulting sampler report (rather then the directions on the page), and I should know where why the application is locked up, or at least what it was doing when it locked up.

That goes a long way in determining the issue.

**Comment by ghost** [comment]
Yes and No, the game locks up when seemingly loading a block that has been modified by Chisel,
but I had an instance where I crashed after trying to place or break a block in chisel.
Log unavailable because It's been ages since this crashed happened(Not another version though, I do believe) so I can't actually find the log.
OK, So I've just been trying stuff out, when I break a piece of block while holding a chisel block in my hand, the game crashes.
Here is the snapshot for that crash:
http://www.filedropper.com/2017_14
(Github doesn't support the nps file)

Tell me if this is alright, if I've done something wrong I'll happily oblige to do some more trial and error.
Regards,
**-L0ST**

**Comment by AlgorithmX2** [comment]
If the game crashes I need the log instead, the sampling with JVIsualVM is only useful for performance issues, and lockups ( where no crash log is generated )

**Comment by ghost** [comment]
Here's the crash:
[crash-2017-08-04_13.20.26-client.txt](https://github.com/AlgorithmX2/Chisels-and-Bits/files/1201792/crash-2017-08-04_13.20.26-client.txt)
Here's the most recent log(I haven't played since last crash):
http://www.filedropper.com/fml-client-latest

**Comment by AlgorithmX2** [comment]
From the crash log:
 
> Description: The minimap has failed! Please contact me at planetminecraft.com/member/xaero96 or minecraftforum.net/members/xaero96
> 
> java.lang.ClassCastException: java.util.Optional cannot be cast to com.google.common.base.Optional
> 	at xaero.common.util.BlockStateUtil.getHashCode(BlockStateUtil.java:19)
> 	at xaero.common.minimap.Minimap.loadBlockColourFromTexture(Minimap.java:540)
> 	at xaero.common.minimap.Minimap.findBlock(Minimap.java:769)
> 	at xaero.common.minimap.Minimap.loadBlockColor(Minimap.java:820)
> 	at xaero.common.minimap.Minimap.updateTile(Minimap.java:517)
> 	at xaero.common.minimap.Minimap.updateAChunk(Minimap.java:342)
> 	at xaero.common.minimap.Minimap.access$200(Minimap.java:73)
> 	at xaero.common.minimap.Minimap$1.run(Minimap.java:105)
> 	at java.lang.Thread.run(Thread.java:745)

You'll probably want to talk to xaero.
