### ISSUE TITLE
Diamond Bit Saw not working!?

### ISSUE THREAD

**Issue by zISKo666** [ChiselsAndBits/Chisels-and-Bits#296]
Hi,

I've tried to use the Diamond Bit Saw to make slabs but what ever I do in the crafting table nothing happend. No error, no crash ... just nothing at all.
Is it somewhere disabled or not fully implemented?

Kind regards

* MC Version: 1.12
* C&B Version: 14.4
* Do You have Optifine: no

**Comment by AlgorithmX2** [comment]
Recipes changed in 1.12, I suspect I forgot to verify that they were still working/registering after the port.
