### ISSUE TITLE
Unable to get Bits i got before

### ISSUE THREAD

**Issue by Medusalem** [ChiselsAndBits/Chisels-and-Bits#298]
For any bug reports please provide the following,

* MC Version: 1.11.2
* C&B Version: 13.13/13.11
* Do You have Optifine: Yes
* Forge: 13.20.1.2393

When we started Our Project we were able to Chisel Alf Glaß and Mana glaß, for example, Today i found out it is not Working anymore. Already Chiseled Alf Glass and Mana Glass is Still existing.
More Strange is: You can't take bit of these materials out of the Creativ Menu BUT if you have a chisel in your hand and Middelklick on a chiseled Block of these Materials They are Usable as Bits.

Is this a Bug which comes from the side of Botania like it was in here: https://github.com/AlgorithmX2/Chisels-and-Bits/issues/135

If Yes i will  add a Issue tab there.

Greetings

**Comment by AlgorithmX2** [comment]
Its possible, what mod is the block from?

**Comment by Medusalem** [comment]
Botania, that was unclear, i am sorry.

I also Tested for Version 13.10, which was the First Version in The Modpack. Still not Working, but it is whitelisted in the Modconfig of Chisel and bits, so i thought it may be from this side.

**Comment by AlgorithmX2** [comment]
If the you tried the first version of C&B in the pack, and it didn't change, then there is a good chance that the change was in botania instead. I can't say at this very moment what it is however, and that would be useful for them to know. You could try rolling back botania as well if you want to confirm.

In either cause sending over what is causing the issue would be helpful to them.

You can can also check your log as well, it might shed some light on it as well. There's a possibility. C&B will print out a certain set of errors in the log.

Beyond that I'll need to sit down and look at it myself, and see what is preventing C&B from supporting the block.

**Comment by Hubry** [comment]
Saw this in the Botania repo - [this commit](https://github.com/Vazkii/Botania/commit/2494a5d2b0288cc58d1f3f1fdd6dcc42375ef976) is the only change that happened for the glass blocks since October.

**Comment by AlgorithmX2** [comment]
That looks like it might be related, seems like they fixed another issue by changing this. Good find.
