### ISSUE TITLE
[1.10.2] Crash when placing a Positive Chisel Design.

### ISSUE THREAD

**Issue by crosenquist** [ChiselsAndBits/Chisels-and-Bits#299]
**Details:**
* MC Version: 1.10.2
* C&B Version: 12.15
* Do You have Optifine: No

**Summary:**
Upon using a Positive Chisel Design and right-clicking to place it, the client will freeze momentarily and then crash.

I have been using Chisel and Bits without issue up until this crash, so I'm not sure why it would start happening all of a sudden. I've provided gist links the crash report, configuration file, and clipboard below.

**Crash Report:**
https://gist.github.com/crosenquist/0be7653901359b91eede84b704141201

**Configuration File:**
https://gist.github.com/crosenquist/4336d08a40a78f7ba4898206e7468a47

**Clipboard:**
https://gist.github.com/crosenquist/0303fd5d16a27ab2577ab9acfe4a56c5

**Comment by AlgorithmX2** [comment]
@gr8pefish can you look at this?

I'm not really sure what iron backpacks is doing here, but from the crash it looks like RayTraceResult being sent to getPickBlock is null, which shouldn't happen since vanilla does null checks before calling into that method.

**Comment by gr8pefish** [comment]
@crosenquist Can you update your Iron Backpacks version to the latest one and try again? It should be fixed there (but post again if it isn't).

The update just added the null checks that needed to be there.

**Comment by crosenquist** [comment]
I'll update and test it right now. I'll report back as soon as I know.

Thanks for the speedy reply as well! Super awesome.

**Comment by crosenquist** [comment]
Noice. That solved the issue! 

Thanks again for the speedy response - it's more appreciated than you know!

**Comment by gr8pefish** [comment]
Glad that fixed it!

Thanks for the ping @AlgorithmX2 👍

**Comment by AlgorithmX2** [comment]
Sure thing, thanks for the fix!
