### ISSUE TITLE
Some way to transport designs between worlds

### ISSUE THREAD

**Issue by BraynStorm** [ChiselsAndBits/Chisels-and-Bits#30]
Something similar to the Architect table from BC will be really good.

Very addicting mod, keep it up.

**Comment by AlgorithmX2** [comment]
If your worlds are both creative you can use the clipboard, its pretty limited right now.

However I've been working on this exact feature for a few weeks now, hopefully I'll get it released some time soon.

**Comment by BraynStorm** [comment]
Oh, so that's why the chiseled blocks I picked up appeared in JEI :D. I didn't know it had a clipboard. It will do the job. Also, this supposed Bit Design Table will probably take up a lot of space - every bit's ID in a list.
