### ISSUE TITLE
Modpack Permissions

### ISSUE THREAD

**Issue by CIockworkGhost** [ChiselsAndBits/Chisels-and-Bits#301]
I am currently working on a modpack: "Immersive Experience - 1.10.2" and have this mod planned for addition. This mod will be on a Twitch/Curse launcher modpack. Sincerely, James.
For any bug reports please provide the following,

* MC Version: 1.10.2
* C&B Version: 12.5
* Do You have Optifine: The modpack will not have optifine.

**Comment by AlgorithmX2** [comment]
Please refer to FAQs for permissions - https://algorithmx2.github.io/Chisels-and-Bits/frequently-asked-questions/
