### ISSUE TITLE
[1.12] Structures made from Chisel bits going invisible when opening save from 1.10.2 in 1.12. 

### ISSUE THREAD

**Issue by kirokadura** [ChiselsAndBits/Chisels-and-Bits#303]
* MC Version: 1.12
* C&B Version: 14.6
* Do You have Optifine: Yes, OptiFine_1.12_HD_U_C5

Hello! Recently I've updated all my mods from 1.10.2 to 1.12, but some weird interaction between C&B and Chisel/CTM is causing any C&B structure I made that uses a bit from a Chisel block to either appear as a pink and black checkered texture or completely invisible. 
It only happens on structures created before updating, like the ones in the pictures. If I chisel a Chisel block after updating it works fine.
Not all structures are messed up, though. Some of them stay intact, so I don't know what conditions cause these issues.
Also important to note that all the blocks that appear invisible completely disappear if I exit and enter the world.

I don't know if this issue comes fom C&B or Chisel/CTM, but I tried all version of Chisel/CTM for 1.12 but to no avail.

BEFORE UPDATING:
![2017-08-29_14 34 08](https://user-images.githubusercontent.com/29471180/29835377-32b9481a-8cc8-11e7-9091-2b33efe7b986.png)

AFTER UPDATING (pink/black bits were Cobblestone Brick from Chisel):
![2017-08-29_14 21 21](https://user-images.githubusercontent.com/29471180/29835310-f9a50faa-8cc7-11e7-92bf-fbe05b0a2250.png)

This is the only example that didn't vanish. I assume it may be related to the addition of new blocks to Chisel changing the block values or something, but I'm not sure since it's the only place in the map like this.  The rusty fence is still intact, for some reason.

BEFORE UPDATING:
![2017-08-29_14 33 10](https://user-images.githubusercontent.com/29471180/29835489-8b2d833a-8cc8-11e7-8ce7-0e36472c59c0.png)

AFTER UPDATING (sorry for the dark pic, forgot to turn up brightness):
![2017-08-29_14 24 46](https://user-images.githubusercontent.com/29471180/29835506-996befc2-8cc8-11e7-92ba-75377d9d546a.png)

As you can see, the floor completely vanished. It was made of Laboratory Blocks and Stone from Chisel. The windows are intact because they are made entirely of Flat Colored Blocks. Oddly enough, the ladder at the bottom of the pic is made of a Iron Block from Chisel, but nothing happened to it.

BEFORE UPDATING:
![2017-08-29_14 32 42](https://user-images.githubusercontent.com/29471180/29836166-c1155c00-8cca-11e7-9548-9a928e85f004.png)

AFTER UPDATING (the layer of Marble at the top vanished, revealing the blocks below):
![2017-08-29_14 24 30](https://user-images.githubusercontent.com/29471180/29836177-cd61c494-8cca-11e7-8d33-d7b7d738eb1e.png)

I have more pictures if it's necessary.

I'm sorry if I wasted you time if this has nothing to do with C&B, but any help would be greatly appreciated. Thanks in advance!

EDIT: Oh, and I also messed around the settings for C&B, CTM and Chisel, but nothing happened.

**Comment by kirokadura** [comment]
Nevermind all that, it was all ID changes on 1.12. Case closed!

**Comment by AlgorithmX2** [comment]
Thanks for figuring that out, I only had a few minutes to test this yesterday, but I hadn't gotten to do a full test of converting a world with chisel blocks, so I didn't really have anything to reply back with yet.

But that would certainly explain it.

**Comment by Dushess** [comment]
kirokadura
Wait, as i know FML should resolve IDs itself, we need this scenario: it moves conflitcing with 1.12's IDs stuff to new ID positions instead of rewriting block by IDs or removing 'malfunctioning' of them.

Because i have situation: I build some things on 1.8.9, then port it to 1.9.4 (buildings contains C&B chiseled blocks), after that those blocks in MCEdit looks like End stuff, was added in 1.9.x. But yes, it's just special tile-entity, linked to described blocks IDs, altrough End stuff is presented (probably by own IDs). Little more offtop, since project was migrated to 1.10.2, i have other IDs for new placed chiseled blocks, but all the stuff saved on the map with no changes. (Also didn't test 1.12 environment for this)

**Comment by kirokadura** [comment]
I'm not an expert (far from it) when it comes to the more technical side of Minecraft, but what I could gather is that on 1.11 or 1.12 IDs had to change to lowercase or something, and that caused every C&B structure that contained a Chisel block to completely disappear. It wasn't all blocks though, only "Raw" Chisel Blocks, like Raw Sandstone, Raw Marble, Raw Basalt, etc. 

Unfortunately, I wasn't able to come up with a easy solution, so I'm working on replacing the broken stuff now. If anyone has this problem, take note of the blocks that break when porting, replace them with safer alternatives on the previous version and then update.
