### ISSUE TITLE
Diamond Bit Saw renders backwards in right hand

### ISSUE THREAD

**Issue by The-Fireplace** [ChiselsAndBits/Chisels-and-Bits#304]
In the left hand, it renders correctly, but in the right hand, the player is holding it strangely.
![2017-09-03_17 50 57](https://user-images.githubusercontent.com/5914284/30007287-0bfceb16-90d1-11e7-8243-fc22f4420eab.png)

For any bug reports please provide the following,

* MC Version: 1.12.1
* C&B Version: 14.6
* Do You have Optifine: Yes

**Comment by AlgorithmX2** [comment]
Turns out this was wrong for almost everything in the mod in one way or another ( most were wrong in left hand ), should be fixed for a feature release however.

**Comment by AlgorithmX2** [comment]
Released
