### ISSUE TITLE
[Suggestion] Allow Configuration of How The Chiseled Block Interact With Light Source

### ISSUE THREAD

**Issue by Pudassassin** [ChiselsAndBits/Chisels-and-Bits#306]
I would like a configurable option to alter how chiseled block be treated as when it interact with lighting. As I try to make use of this mod to do roof/floor, I have notice that chiseled block is treated as transparent block toward light sources (comparable to vanilla block of glass) with the following effects noticeable:
1) Dirt blocks directly below chiseled block turn into grassed dirt blocks
2) Doesn't effect/obstruct light source or sunlight

Example cases:
- A building with chiseled block as roofing let in the sunlight and thus prevent mob spawning inside during the day, even when it has no other light sources inside. (and also make interior lightning looks weird)

- A light source can "shine" through chiseled block; a room enclosed with chiseled block isn't completely dark if it has light source outside and nearby
![2017-09-07_06 51 28](https://user-images.githubusercontent.com/31712530/30139715-c44bb29a-9399-11e7-9ba1-c238c6c54e60.png)
_*number labels reflect the vanilla lighting system. Left : vanilla log block, Right : ditto, but with a few bit chiseled_ 

- (Tested with Optifine/shader mod) Chiseled block appeared lit if a light source is placed directly below it.
![2017-09-07_06 54 03](https://user-images.githubusercontent.com/31712530/30139724-d17233a4-9399-11e7-81a4-3c63d20eb2e5.png)

This is about atheistic in most case, but it can also affect balances/mechanics if it is involved with lighting (as a spawning condition). I would like to see the future of this super creative-oriented mod shining.

- Pud

**Comment by AlgorithmX2** [comment]
Blocks which are "full" of solid materials manifest as light blocking blocks, I don't know what else I can do besides this.

This is because lights with block light render inappropriately unless they full size.

**Comment by Dushess** [comment]
Simplier, all chiseled blocks, that is not full cube, is transparent for render.

**Comment by Pudassassin** [comment]
I see, so it's transparent for rendering its custom shapes. I copy that and thank you for the answer.
