### ISSUE TITLE
[suggestion] Scaffold Bits

### ISSUE THREAD

**Issue by Ricktrandom** [ChiselsAndBits/Chisels-and-Bits#308]
Essentially the idea is just to have a bit that will vanish either after a certain amount of time, or when the creation is broken. This way if you cant find an easy way to place a bit elevated in the creation, this would help let you.

**Comment by AlgorithmX2** [comment]
Can you explain what this is attempting achieve? You could easily use any material in a block then remove it with "Same Material" when your done, that would let you remove bits from anywhere inside, even the center hidden beyond complicated layers of fluid or glass or whatever.

**Comment by Ricktrandom** [comment]
Oh, I never noticed same material before, nevermind this then.
