### ISSUE TITLE
Coping patterns with bag creates strange pieces.

### ISSUE THREAD

**Issue by BraynStorm** [ChiselsAndBits/Chisels-and-Bits#31]
I can't phrase the issue probably, sorry. I did a [video](https://www.youtube.com/watch?v=Hk5KSfo3He0) on it though. Also, this ghosting mismatch happens with the created pieces without rotating them. It's really weird.
`Forge: 1808`
`C&B: 8.6`

**Comment by AlgorithmX2** [comment]
Fixed in new build.
