### ISSUE TITLE
Unable to add blocks to C&B list

### ISSUE THREAD

**Issue by orionSquared** [ChiselsAndBits/Chisels-and-Bits#311]
I am unable to find a place to add blocks to the chisels and bits list. I am wanting to add the grasses and dirts from BoP, the leaves from BoP, the leaves from Natura and the grasses from Botania.

For any bug reports please provide the following,

* MC Version: 1.10.2
* C&B Version: 13.13
* Do You have Optifine: No

**Comment by AlgorithmX2** [comment]
I do not white list any blocks from other mods and not all blocks are supported by default, if you want to ask those authors to white-list their blocks its quite simple to do so.

https://github.com/AlgorithmX2/Chisels-and-Bits/blob/1.12/src/main/java/mod/chiselsandbits/api/IgnoreBlockLogic.java#L18
