### ISSUE TITLE
Crash when placing bits in a Multipart container

### ISSUE THREAD

**Issue by brisingraerowing** [ChiselsAndBits/Chisels-and-Bits#314]
[Crash Log](https://gist.github.com/BrisingrAerowing/84b649b5d713fbe067cee9c0027e378c)

I tried to create a slab with a hole for a RS cable, and got this crash.

* MC Version: 1.12.2
* C&B Version: 14.8
* Do You have Optifine: No

**Comment by AlgorithmX2** [comment]
Duplicate of https://github.com/AlgorithmX2/Chisels-and-Bits/issues/310
