### ISSUE TITLE
MC1.12.2 Crash - Chisel & Bits v 14.8 + Chisel mod v MC1.12-0.0.14.18

### ISSUE THREAD

**Issue by CcytherR** [ChiselsAndBits/Chisels-and-Bits#316]
Just those 2 mods.
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 10/21/17 1:37 AM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at mod.chiselsandbits.core.ClientSide.interaction(ClientSide.java:838)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_36_ClientSide_interaction_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:342)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1706)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_151, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 662868160 bytes (632 MB) / 1004011520 bytes (957 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.0.2512 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID             | Version          | Source                        | Signature                                |
	|:----- |:-------------- |:---------------- |:----------------------------- |:---------------------------------------- |
	| UCH   | minecraft      | 1.12.2           | minecraft.jar                 | None                                     |
	| UCH   | mcp            | 9.42             | minecraft.jar                 | None                                     |
	| UCH   | FML            | 8.0.99.99        | forge-1.12.2-14.23.0.2512.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge          | 14.23.0.2512     | forge-1.12.2-14.23.0.2512.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | chisel         | MC1.12-0.0.14.18 | Chisel-MC1.12-0.0.14.18.jar   | None                                     |
	| UCH   | chiselsandbits | 14.8             | chiselsandbits-14.8.jar       | None                                     |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 384.77' Renderer: 'GeForce GTX 1050 Ti/PCIe/SSE2'
	Launched Version: forge-14.23.0.2512
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1050 Ti/PCIe/SSE2 GL version 4.5.0 NVIDIA 384.77, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: ChromaHills-64x-1.12.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz

**Comment by AlgorithmX2** [comment]
I'm not sure why, but for some reason C&B's keybindings failed to register.

**Comment by AlgorithmX2** [comment]
Your missing CMT, I'm not sure why its crashing in C&B and not displaying that Chisel is missing its dependency though... that makes no sense.

Chisel Requires: https://minecraft.curseforge.com/projects/ctm/files
