### ISSUE TITLE
Crash when placing bit tank

### ISSUE THREAD

**Issue by ghost** [ChiselsAndBits/Chisels-and-Bits#317]
For any bug reports please provide the following,

* MC Version: 1.12.2
* C&B Version: chiselsandbits-14.9
* Do You have Optifine: Yes

Crash report: https://pastebin.com/GSLzUyts

**Comment by AlgorithmX2** [comment]
The entire stack trace is for codechicken + connected textures and BlockModelCustomizer.
code chicken is obvious, but the other two I think are optifine.

It says it crashed rendering the bit tank, and the bit tank is just a standard json model, nothing special.
There shouldn't be any reason for a json model to crash, i think something else is breaking it.

**Comment by ghost** [comment]
Sorry I thought it was caused by this mod since it happened as soon as I placed it, guess I will just not use it, should I close this issue then?

**Comment by AlgorithmX2** [comment]
I suppose so.
