### ISSUE TITLE
Chiseled block tooltips say 'Left Click to place'

### ISSUE THREAD

**Issue by brisingraerowing** [ChiselsAndBits/Chisels-and-Bits#318]
Shouldn't that be the other button (right click [or whatever the user has set])? For me, left click is break blocks.

For any bug reports please provide the following,

* MC Version: 1.12.2
* C&B Version: 14.9
* Do You have Optifine: No

**Comment by AlgorithmX2** [comment]
I guess I'll have to extract which button is set and add a variable to the localization text for that... I was just trying to be helpful, but I guess you could map place block to any key.
