### ISSUE TITLE
Issue while using Chisels And Bits and Chiseled Me

### ISSUE THREAD

**Issue by Paradoxica6** [ChiselsAndBits/Chisels-and-Bits#319]
So, I Have The C&B mod and another mod called Chiseled Me (It adds different items which can change your size (In Minecraft, Of Course :) )).
So I watched a video on Youtube where people build Home`s inside of blocks, The problem is when I change size to 1/16 (Blocks in Minecraft are 16X16 Pixels) and try to carve out blocks to try and make them House`s, I ran into this Issue where in certain area`s of blocks (Mostly the edge`s),
Chiseling the blocks make a invisible force field which pushes players back.

My Minecraft version is: 1.10.2
C&B Version: 12.16
And i do not have optifine installed

Thank You in Advance

**Comment by AlgorithmX2** [comment]
I'm not exactly sure what your describing, are you saying that the bits you carve away are still colliding with you? or something else?

I think that C&B does a pretty good job of matching the collision shape to the bits now, and I think that was done in 1.9 or 1.8 so it should be fine in 1.10 as well.

**Comment by Paradoxica6** [comment]
From one side the bits I carve away are still colliding with me, But from the other side it pushes me to the side where there is collision

**Comment by Dushess** [comment]
Hm, it looks like vanilla block during carving becomes tile-entity, but with stock collision box. But why?

**Comment by AlgorithmX2** [comment]
I'm not sure what would cause this, from what I've been able to deduce my blocks collisions are as accurate as I can make them. 

I've also verified there is no "special" behavior in them, such as player only  collision, something that could make collision act differently depending on what is collision with it.

I'm not really sure what else to look at, I'm not familiar with mods that alter the player's scale or entity so it might be complications involved in that, I've heard that it is tricky. I know that there was another mod a few versions back I think, that  for a while seemed to work well with C&B at smaller scales, I remember someone sending me a video of them tunneling though the ground with a chisel. Though I cannot remember what mod it was.

Perhaps Chiseled Me is missing something important?

I'm not really sure what happen with that mod, but it seems like the author has deleted their github project for the mod.

If the author of the other mod was willing to work with me to try and figure out the problem that would be one thing, but from the looks of it its quite abandoned now.

**Comment by Paradoxica6** [comment]
I went to https://minecraft.curseforge.com/projects/chiseled-me, And the mod description said the mod was experimental and the last update was update 1.0 for 1.10. That was on Aug 20, 2016.
The Author of the mod did say that he may update it, https://minecraft.curseforge.com/projects/chiseled-me#c43, He said that on Sep 10, 2017

**Comment by AlgorithmX2** [comment]
If you click the source or issue links on that page you'll see that github repository for the mod is gone.

**Comment by CreeperGuy72192** [comment]
I have the same problem and for some reason I can't get chisel and bits to work with 1.10.2 after reinstalling Windows. I don't have the problem on 1.12.2 when I'm not using chisel and bits. Well now the issue is gone idk why I can enter small places with no problem. That is weird. Oh I know why I'm having the issue. It is due to UpAndDownAndAllAround. Do you have any other mods? Because that mod was why I was having that problem.

**Comment by Aeltumn** [comment]
Please don't necropost.
