### ISSUE TITLE
Crash when scrolling items from Bit bags

### ISSUE THREAD

**Issue by BraynStorm** [ChiselsAndBits/Chisels-and-Bits#32]
Title explains everything :)
[Crash Report](http://pastebin.com/XYTLa1Ej)
`Forge: 1808`
`C&B: 8.7` ( corrected version )
[Item Scroller](http://minecraft.curseforge.com/projects/item-scroller?gameCategorySlug=mc-mods&projectID=242064)

**Comment by AlgorithmX2** [comment]
Forwarding to ItemScroller to see if they will add a check.

**Comment by BraynStorm** [comment]
Ok, I just didn't have any other problems with it and assumed it must be on your end then. Sorry.

**Comment by AlgorithmX2** [comment]
Its kind of a fuzzy area, since it only happens when another mod uses its its fake slots, I wish I had an idea of how to fix it, but people can get access to the fake slots by asking for the active slot, and I can't really guard against that.

**Comment by maruohon** [comment]
This has now been fixed in Item Scroller 0.2.3.

**Comment by AlgorithmX2** [comment]
Thanks, I added a second issue to into find a better solution for the fake slots as well.

https://github.com/AlgorithmX2/Chisels-and-Bits/issues/34
