### ISSUE TITLE
Creative mode bit collection option

### ISSUE THREAD

**Issue by malice936** [ChiselsAndBits/Chisels-and-Bits#321]
Currently creating and testing a pack privately, and noticed that you can't get bits from chiseling blocks, would recommend a creative chisel or something to that effect.

**Comment by AlgorithmX2** [comment]
If your in creative mode you can use the creative tab to pull out bits, or you can use pick bit ( or use pick+block on a chiseled block + hot key ) to get bits.

This works much the same as how normal creative mode works, you don't get bits when you break a block, you have to pull it from the creative tab or use pick block.
