### ISSUE TITLE
["FIX"] Unable to determine blocks eligibility for chiseling

### ISSUE THREAD

**Issue by Frontrider** [ChiselsAndBits/Chisels-and-Bits#323]
I see that the config has a list for the blocks it can use. Could we manually add the ones we know it can't use to a config,(for me namely rftools stuff) so it wouldn't do the checks when we already know that it wouldn't work?

I would like to see it, because I'm currently investigating a timeout error, and its the first lead I have.

I did read the history of it on multiple sides, and this would probably be the safest way to do something about it. Safe, and also applicable to every other similar situation.

**Comment by AlgorithmX2** [comment]
Unfortunately "Enabled Blocks" uses the class name of the block, and C&B cannot determine the class name of the block because calling getClass() causes the exception that logs that error.

If your really worried about the message being logged, I suggest you simply install oneprobe, I believe its missing interfaces are what cause it for RFTools.

**Comment by Frontrider** [comment]
Understood. Altough, one probe is not a fix at least not on 1.12.

**Comment by AlgorithmX2** [comment]
Whats the full message that it reports? It should indicate what is missing.

**Comment by Frontrider** [comment]
There is no message, nothing changes.

**Comment by AlgorithmX2** [comment]
I don't really understand your response, You reported that the you received the messages regarding "Unable to determine blocks eligibility for chiseling" but now there are no messages?

Or are you saying that the blocks are still un-chisable even when there is no message? If thats the case it just means that the block wasn't enabled for chiseling either way, the error just means that C&B cannot run its code to determine if its possible ( it would normally crash when it tried, but C&B prevented the crash )

**Comment by Frontrider** [comment]
Sorry.

The messages are there (with or whitout The One Probe), and those blocks are not chiselable.

In the meantime the data what I found on the interactions of RF tools (and similar), and c&b were enough answer to me.
Our original issue with it was also a wierd one (don't ask), what we managed to resolve by now.
