### ISSUE TITLE
Slabs can't be placed in the upper half section of a block.

### ISSUE THREAD

**Issue by thaumictom** [ChiselsAndBits/Chisels-and-Bits#324]
* MC Version: 1.12.2 (FTB Horizons 1.1.0)
* C&B Version: 14.9
* Do You have Optifine: Yes
---
Following: The chiseled (saw-used) slabs (1/2 of a block) cannot be placed in the upper half section of the block, so you can't rotate it to 180° degrees.

**Comment by AlgorithmX2** [comment]
You can place them in the upper half of the block, you just need to use shift placement, or place them and flip them with the wrench, the saw doesn't really make for easy to use blocks.

**Comment by thaumictom** [comment]
Yes, sorry, I noticed it now with JEI.
