### ISSUE TITLE
[Suggestion] Make chiseled blocks not get covered in snow layers.

### ISSUE THREAD

**Issue by ghost** [ChiselsAndBits/Chisels-and-Bits#326]
For any bug reports please provide the following,

* MC Version: 1.12.2
* C&B Version: 14.9
* Do You have Optifine: Yes

Some blocks look weird when covered by snow

![2017-11-14_20 26 37](https://user-images.githubusercontent.com/30737871/32815835-84ff82ac-c97b-11e7-8942-4e3d38710675.png)
![2017-11-14_20 26 15](https://user-images.githubusercontent.com/30737871/32815836-85121296-c97b-11e7-9686-2a91e7c22c51.png)

**Comment by AlgorithmX2** [comment]
Yeah, I can certainly agree with that.

But the only way to change this is to make it so that the "solid" test is requires more bits, C&B has always been a little liberal with that, but since there have been changes to vanilla recently I might need to revisit that logic.

**Comment by AlgorithmX2** [comment]
Upon closer inspection it seems that its very vague... for instance torches by default check to see if its solid, but don't care if its anything else, most things seem to only care if its solid, or not. 

The only main exceptions to that logic are things like fences, panes and walls which use the various values for determining if things can connect... which isn't really what i'm interested in here...

**Comment by AlgorithmX2** [comment]
That complicates things unfortunately, if I want to just prevent snow I need to add a hook to forge so I can say, no snow, but everything else is still relevant... The only other option is to tighten up the "solid" behavior so that C&B really and truly only reports solid if the full side is solid.

I can still override torches I suppose... but it will make the solid behavior less "forgiving" I'll need to consider this.

**Comment by AlgorithmX2** [comment]
I tried to get a override for snow into forge, but it was declined, I'll need to alter face solidity rules then..

**Comment by thakyZ** [comment]
Is there any news on this? Because this gets really frustrating when having stairs made out of blocks from the chisel mod blocks with C&B get covered by snow, I'll have to use a torch for now.

**Comment by AlgorithmX2** [comment]
Not really, in the end I'm stuck between changing it and potentially breaking existing builds and leaving it as is and requiring people to use torches and such.

**Comment by Sourceshard** [comment]
@AlgorithmX2 
Changing how the sides are registered as solid would indeed break a lot of builds and also remove a very deeply used feature. How about flipping this on its head and approaching it from another angle. Is there a way you could make it so Light generation blocks like C&B Lava and Glowstone melt snow? Then to avoid snow one would need to place a single bit of lava or Glowstone inside their build to "Snow Proof" it. Also if more then one bit of lava or glow stone is needed to provide [Visable] Light levels then this method could be used to prevent snow generation even in Dark/Unlit Builds.

**Comment by AlgorithmX2** [comment]
That unfortunately would potentially cause other issues, many people alter the required bits to achieve max light level to 1 bit, thus making that solution caught a full brightness block for them.
