### ISSUE TITLE
Fill tool

### ISSUE THREAD

**Issue by ShastaCat** [ChiselsAndBits/Chisels-and-Bits#329]
Is there a way to fill a flat area with bits? Thanks.

**Comment by AlgorithmX2** [comment]
Have you tried using Drawn Region mode?

**Comment by ShastaCat** [comment]
No, how do I do that? I'm new to the mod

**Comment by AlgorithmX2** [comment]
Use Alt, or which ever key you have bound the the C&B Mode Menu while holding a bit in your hand and it opens a menu, on that menu you can select various modes which let you place or chisel bits in different ways.
