### ISSUE TITLE
Certain chiseled blocks decaying like leaves

### ISSUE THREAD

**Issue by GabsiGuy** [ChiselsAndBits/Chisels-and-Bits#33]
Absolutely love this mod, have been using it a lot recently. However there is this annoying bug where only in a certain area, chiseled blocks seem to disappear gradually over time like leaves do when you cut down a tree. I say that they **_seem_** to disappear because they are still apparently there, and I cannot walk through them but I jitter whilst attempting to do so.
I currently am running on 1.8 Forge, with 15 mods active, including Optifine-1.8_HD_U_H5, which may be the problem.

**Comment by GabsiGuy** [comment]
I **_think_** I have found what was causing the problem. OpenComputers was causing other errors while I loaded worlds and so I have just disabled the mod and all the missing blocks are back [Yay! :) ]. Still, this issue should not go unnoticed and should be taken into account.

Carry on with this great mod!

**Comment by AlgorithmX2** [comment]
It might also be Optifine, unless you have changed the dynamic rendering settings, or if optifine has fixed the crashes with the C&B Multithreaded Rendered.
