### ISSUE TITLE
Grammar and punctuation errors - JEI description

### ISSUE THREAD

**Issue by ghost** [ChiselsAndBits/Chisels-and-Bits#332]
![chisels bits grammatical error](https://user-images.githubusercontent.com/25916106/33405474-cc127aac-d568-11e7-9aeb-f1f982e3b35e.png)

Please fix. Chisels & Bits is literally unplayable at the moment.

**Minecraft version**: 1.10.2
**Chisels & Bits version**: 12.16

**Comment by AlgorithmX2** [comment]
Fixed for next release, though your using 1.10.2 and its probably not going to get a back port.

**Comment by ghost** [comment]
@AlgorithmX2 Have you dropped support for the 1.10.2 version?

**Comment by AlgorithmX2** [comment]
Unless there anything of significance, fix or feature to release something this minor isn't likely to make its way back.

**Comment by ghost** [comment]
Okay. Will it make its way in a future update, though?

**Comment by AlgorithmX2** [comment]
It will be in the next update for 1.12, and any future fixes or updates for 1.10+ ( at least for the moment ) but that all hinges on if there are those.

If you want to use the new language file you can always make a resource pack with it, or overwrite it locally, no changes were made in the code.

**Comment by ghost** [comment]
All right. Thanks.

I would still play on 1.12.2 if it weren’t for Ender IO not being there yet. Can’t live without that mod.
