### ISSUE TITLE
Internal server error that keeps kicking a player, and seems to blame your mod

### ISSUE THREAD

**Issue by Sunconure11** [ChiselsAndBits/Chisels-and-Bits#335]
https://pastebin.com/9GuP3MGe

For any bug reports please provide the following,

* MC Version: 1.12.2
* C&B Version: 14.9
* Do You have Optifine: No

**Comment by Nachtflame** [comment]
Also having this issue, but on world load in Single Player.
https://pastebin.com/2KuDi1Y9

:edit: When backing to 14.8 issue ceases to kick at world load. becomes seemingly random occurance after.

For any bug reports please provide the following,
MC Version: 1.12.2
C&B Version: 14.9
Do You have Optifine: No

**Comment by AlgorithmX2** [comment]
I suggest updating forge, or downgrading forge There are a select two or three versions where Forge removed a field from a class and it caused this issue.
