### ISSUE TITLE
Crash when picking up Wind Generator (MekanismGenerators)

### ISSUE THREAD

**Issue by CommandMC** [ChiselsAndBits/Chisels-and-Bits#336]
So, I got a crash when picking up a wind generator from mekanismgenerators, the crash report says something about "at mod.chiselsandbits.items.ItemBitBag.pickupItems(ItemBitBag.java:222)".

For any bug reports please provide the following,

* MC Version: 1.12.2
* C&B Version: Newest (14.9)
* Do you have Optifine?: Yes, OptiFine_1.12.2_HD_U_C6 (newest for 1.12.2)

Crash Report:
https://hastebin.com/evaqesesiq.sql

**Comment by armuell** [comment]
I am getting this same error but it does not matter what item I pick up. Every item I pickup crashes the game:

https://hastebin.com/cikapizoza.sql

**Comment by armuell** [comment]
This issue can be closed. The bug was related to a breaking change added by forge 2557 and was fixed in the latest forge. https://github.com/AlgorithmX2/Chisels-and-Bits/issues/333 @CommandMC Update your forge and you should be good.

**Comment by CommandMC** [comment]
Updated forge, and now it works, thanks!
The problem was that MultiMC has a delay between the release of the newest forge version, so the latest version for me was 14.23.1.2555
Thanks for the help!
