### ISSUE TITLE
Pls give back the 1.7.10 version :)

### ISSUE THREAD

**Issue by xTheAlex** [ChiselsAndBits/Chisels-and-Bits#339]
I don't like the 1.8x or others versions on minecraft whit mods i play only whit 1.7.10

**Comment by AlgorithmX2** [comment]
There was never a 1.7.10 version. So your title is inaccurate.

Your entitled to your choice of which version to play. However I am also as much entitled my opinion of which versions I support, and I already gave you my answer, as I do to everyone that asks for this.

This is a monumental time sink, probably over a hundred hours of my time, I do not have such time.  In fact I've been struggling to find a the time to even maintain and work on a feature that was 80% done almost a year ago.

Please do not create another issue.
