### ISSUE TITLE
Please create back version 1.7.10

### ISSUE THREAD

**Issue by xTheAlex** [ChiselsAndBits/Chisels-and-Bits#340]
Look here:

Mod-Minecraft.Net>

Brandon • 9 months ago
Still waiting on a 1.7.10 release.

Gobbyer • 2 years ago
please make for 1.7.10

9Minecraft.Net>

Viktor Stroh · Lohfelden

please 1.7.10!

Jacki Müller

Bitte 1.7.10

Bryclyn Matthews

1.7.10 pleaseee

Icee Amoto Marin

please 1.7.10 and soon?

Ashlee Latkovich

1.7.10 ??

Claudio Junior

1.7.10 pls

Xe Tự Lái

1.7.10 plsss

Everyone wants version 1.7.10 I give 5 euros if you do.

**Comment by Phylogeny** [comment]
Despite both being close to zero, one difference between 10<sup>-80</sup> and 10<sup>-81</sup> is that one number is *even closer* than the other.

By defying the instruction in #339 with this re-posting of your demand, you've just managed to do the same to the probability that C&B will be ported to 1.7.

&#65121;unapologetically patronizing slow clap&#65121;

**Comment by xTheAlex** [comment]
I understand, maybe you're playing another version but I do not play and C & B is the coolest way ..... I can not play without it's a boredom ... 
Do not I understand what stops you from doing the version?

**Comment by Phylogeny** [comment]
"Do not I understand what stops you from doing the version?"

http://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/2576750-chisels-bits-flat-colored-blocks?comment=581

**Comment by xTheAlex** [comment]
I do not care about problems or bugs, or what a bug or a blues mode is not a brilliant way.
so I would like many others to do for 1.7.10

**Comment by Phylogeny** [comment]
"I do not care about problems or bugs..."

You do care about problems. Porting C&B to 1.7 is a problem you care about.

It is one that almost certainly will not be fixed, and asking or demanding that should be either has no effect or makes it *even less* likely still.

Period.

Just chalk it up to another one of life's lamentable realities (like death and taxes) and move on.

Seriously; move on.

**Comment by xTheAlex** [comment]
YOU WILL NOT KNOW YOU DO NOT INTEREST THE BUDGET BEFORE YOU WERE NOT AND NONE. THE EU AND MULTI OTHER WANT BACK THE VERSION 1.7.10

**Comment by Phylogeny** [comment]
Not even the '*break glass in case of emergency*' caps-lock you've just engaged changes anything I've just said (and what you've just said amounts to an "I want! I want! We want!" tantrum, anyway).

Literally nothing you do will make a C&B 1.7 port any more likely than the virtual impossibility it is. It will only annoy its creator.

Again; move on.

**Comment by xTheAlex** [comment]
I'm not leaving until I get what they want ...
I said I want that and I will get it "once"

**Comment by Phylogeny** [comment]
"I'm not leaving until I get what they want ..."

Spoken like a red-faced, mid-tantrum toddler. Are you going to hold your breath too?

In all seriousness, you will eventually realize that literally nothing you can type here will ever cause a 1.7 port to materialize.

You will--thank heavens--eventually 'leave'.
