### ISSUE TITLE
Crash with MCMP Integration

### ISSUE THREAD

**Issue by Diamondman121314** [ChiselsAndBits/Chisels-and-Bits#342]
* MC Version: 1.12.2
* C&B Version: 14.10
* Do You have OptiFine: Yes.

I just updated to the latest version of Chisels & Bits, 14.10, and with the MCMP integration, it crashes.
https://pastebin.com/3fgYn69n

**Comment by AlgorithmX2** [comment]
Try https://dvs1.progwml6.com/jenkins/job/Chisels-and-Bits/99/artifact/build/libs/chiselsandbits-14.0.99.jar ? I'm thinking that the class is being created before C&B initializes, so that should fix it.

If it works I'll make a new release of it.

**Comment by Diamondman121314** [comment]
That fixed it. It works. :D

**Comment by AlgorithmX2** [comment]
I pushed 14.11 up to curse forge it should be out soon.
