### ISSUE TITLE
I'm unable to access the Mode Selection bound to Lmenu.  

### ISSUE THREAD

**Issue by Craftdad** [ChiselsAndBits/Chisels-and-Bits#343]
I'm currently playing the Project Ozone Lite and I can't get the mode selection to work.  I don't have a conflict with the keybinding of Lmenu.  MC Version: 10.2  and C&B Version 12.16 and I don't have Optifine installed.    Any help would rock.  Thanks.

**Comment by AlgorithmX2** [comment]
Do you have an applicable tool in hand? Chisel, or Bit?

**Comment by Craftdad** [comment]
I had the diamond chisel and the ichisel.   I’m unable to get a bit off of a block to make a bag.  All I can do is change the texture of a block currently.

**Comment by AlgorithmX2** [comment]
The ichisel is not from my mod, its from "Chisel" if your changing textures, also from chisel, make sure your using the chisel from "Chisels and Bits"

You can visit https://algorithmx2.github.io/Chisels-and-Bits/ and see what the items look like.
