### ISSUE TITLE
Visible seam between chiseled blocks

### ISSUE THREAD

**Issue by TakingItCasual** [ChiselsAndBits/Chisels-and-Bits#344]
* MC Version: 1.12.2
* C&B Version: 14.11
* Do You have Optifine: No

Noticed seams/lines cutting between chiseled blocks. Images with white concrete below. Is this known or recent? I just started using C&B recently.

![image](https://user-images.githubusercontent.com/4134115/33799357-a25c6c3c-dd32-11e7-894b-86b81c66ee3f.png)
![image](https://user-images.githubusercontent.com/4134115/33799363-abfab26c-dd32-11e7-94a7-f4bfad9389c0.png)

**Comment by Dushess** [comment]
I've tested it with Little Tiles and got same result. Probably rendering of custom tile-entities? 
Also i'm not have this thing with C&B.

**Comment by AlgorithmX2** [comment]
Have you tried restarting the game? I've not changed anything with rendering in some time, and this sometimes occurs even in vanilla.

**Comment by TakingItCasual** [comment]
Restarting the game has indeed fixed it. I just hope I won't come across this too often then...

**Comment by AlgorithmX2** [comment]
Yeah, I sort of thought it was that, I'm not sure why, but from time to time that bug has cropped up, I've seen it when developing changes and have spent hours trying to track down and understand it, then I "Fix it" only to restart the game and find that my fix actually broke the renderer instead.

Whatever it is, I think its a problem much deeper in the renderer or even OpenGL then C&B can touch.
