### ISSUE TITLE
So many issues where to even begin...

### ISSUE THREAD

**Issue by uehlbran** [ChiselsAndBits/Chisels-and-Bits#347]
Chisel and bits causes the following:

* Blocks to rotate when you look at them

* When looking at RS machines they just shutdown even if they have power

* If you place a chiseled bit or block in the same space as RS it crashes your game and then glitches everything out

* Prevents you from ever being able to place blocks where the chiseled bit/block was after a game crash.

* Causes any cables from any mod even remotely close to glitch out and appear not connected

* Putting any block in the same space as where a chiseled bit/block that has become glitched and disappeared will delete any placed blocks int eh same space.

* MC Version: 1.12.2
* C&B Version: 14.11
* Do You have Optifine: No

**Comment by AlgorithmX2** [comment]
Block rotating when you look at them? As in just vanilla blocks? C&B dosn't do anything to vanilla rendering, and is not a core mod, are you sure you don't have something else installed thats causing something so massive to break?

I don't even know what to say about C&B some how causing RS Machines to shutdown when they have power, C&B has no power system, is not a core mod, and has no integration with RS Directly. I don't see how C&B could do this.

Crashing, the glitching and ghost blocks are actually a problem with MCMP, you should update to the latest build.

I think that most of the issues on your list are actually MCMP causing tile entities to not completely load on the client side when RS tries to handle its packets without world data. Definitely update to the latest build.

**Comment by uehlbran** [comment]
So when you look at a block that can be rotated like a crater from RS or a fusion crafter from draconic it will rotate each time you glance at it. Almost as if you were using a wrench on it.

The machines shut down, but they  still have power. Breaking the cables connected to them fixes it till you look at them again, lol... Very frustrating. I tried to update MCMP from 2.3.3 to 2.4.0 the latest version. Will update back if that was the issue or not.

**I'll be damned you were right. I would have never guessed that was the issue. Thank you. How did you know though? I'd rather be able to figure these things out on my own rather than getting frustrated and posting.**

**Comment by AlgorithmX2** [comment]
I just fired up an instance and I am not seeing either behavior, crafters from RS are not rotating, in fact the C&B wrench doesn't even work on them.

As for power, I'm not seeing that either, I have a RS Controller and grid surrounded by C&B Blocks, and they are working fine, still powered, and I can use the grid to both put in items and extract them.

I'm not seeing any strange behavior related to where I am looking.

I am using mekanism to power the controller.

**Comment by uehlbran** [comment]
You were right the issue was with MCMP.

**Comment by AlgorithmX2** [comment]
https://github.com/AlgorithmX2/Chisels-and-Bits/issues/310 is the main reason I knew, If you check your client log you probably would have seen errors related to refined storage and MCMP as well, something to be aware of in the future.
