### ISSUE TITLE
Light passing through all C&B blocks

### ISSUE THREAD

**Issue by Spleenczar** [ChiselsAndBits/Chisels-and-Bits#349]
Chisels and Bits blocks that shouldn't be letting light pass through them are letting light pass through them.

I don't know if this is a known thing (didn't see it in open issues) but I don't recall it working this way before. Playing on the DW20 modpack. I can provide images if necessary.

For any bug reports please provide the following,

* MC Version: 1.12.2
* C&B Version: 14.11
* Do You have Optifine: No

**Comment by Dushess** [comment]
Vanilla related, any non solid block letting light to pass trough. But render cannot recognize custom tile-entity (chiseled block) as solid and thinks, that it's not opaque at all.

**Comment by Spleenczar** [comment]
Turns out that at night it gets weirder, but I think this is actually just a symptom of https://github.com/AlgorithmX2/Chisels-and-Bits/issues/315, since now it looks like this: https://imgur.com/a/116nK

**Comment by Dushess** [comment]
Should be game render feature. If vanilla block is not changed, it have isOpaqueCube=1, but any tile-entity have this =0, and since chiseledblock is tile-entity too, it fully transparent for renderer.

**Comment by AlgorithmX2** [comment]
@SpeedySpy52 
That does resemble #315, However we've had no luck isolating the cause of #315 as of yet.

Chisels and Bits blocks do resemble slabs in vanilla, so anything that not "entirely made of solid bits" lets light though, but that looks a little bit more like the blocks are not lit at all.

oitsjustjose said he tracked down the cause as being Chisel and CTM, but I'm not sure its that simple? If you could try and figure out what other mods might be involved or what conditions are needed to reproduce it I could figure it out, I'm honestly not sure at this point what is causing that.

@Dushess
isOpaqueCube really has nothing to do with tile entities specifically, and just that MC can only handle transparent and opaque blocks, if its not opaque, then its transparent. Things like furnaces that have tile entities can be opaque if they want too. C&B actually will do this if the block is "completely solid" but this doesn't apply to this case.

**Comment by Dushess** [comment]
However furnace acts like block, at least glass is block, but is transparent.

**Comment by Spleenczar** [comment]
Yeah, just seems like when it gets to night time all of my Chisels and Bits stuff starts "glowing". I seriously have no idea what's going on here, and I'm not familiar when it comes to the technical side of things, so I can't really diagnose that myself...

**Comment by AlgorithmX2** [comment]
I can only suggest trying to find the common element, does it happen in a empty world? Does it only happen around another block? is it gear related? Make a copy of your instance/pack and remove mods?

I know that it can take time, but the main problem is that I simply have no idea why the problem is happening, and I've not found a way to see the issue myself, so I can try and figure out whats wrong personally.

**Comment by AlgorithmX2** [comment]
If you do find anything let me know, for now I think it makes sense to merge this issue into the other one, I think we have enough evidence to do that at least.
