### ISSUE TITLE
[Mod Compat Request] MC Multipart

### ISSUE THREAD

**Issue by mariodk** [ChiselsAndBits/Chisels-and-Bits#35]
mod compat with:
http://mods.curse.com/mc-mods/minecraft/239431-mcmultipart

so kinda Chisel & Bits can become the Forge microblocks of +1.8.9 basically so we can use Chisels-and-Bits to cover up our cables/pipes & etc.

**Comment by amadornes** [comment]
This is already a thing and has been since MCMultiPart got released :P

**Comment by mariodk** [comment]
ohh did not know sorry about that then
"starting to make a private 1.8.9 modpack just moved from 1.7.10 to 1.8 mods basically"
and it did not seems with mods with MCmultipart support they worked with Chisels&bits
and did not find anything in FAQ say about this too(before i posted here)

**Comment by AlgorithmX2** [comment]
Which mod that is MCMP Compatible isn't work with C&B? It should work fine, I've tested it with quite a few mods over the past weeks, charset, tech reborn, and a few others.

**Comment by AlgorithmX2** [comment]
No Response, Closing.
