### ISSUE TITLE
Make the in world bit highlighter contrast block bit your looking at.

### ISSUE THREAD

**Issue by Guardian9978** [ChiselsAndBits/Chisels-and-Bits#351]
This feature request has to do with the small block wireframe that shows up when you look at a bit in world with a chisel or bit in hand.

Is it possible to make the bit highlighter in world change its color to contrast the bit your looking at so if your working with dark colors such as black you can see the bit highlighter easier. If having it change dynamically would be to much work then how about adding an option to change the highlighter in a menu somewhere.

**Comment by AlgorithmX2** [comment]
I think that this makes sense, though I'm not entirely sure of the best option at the moment.

**Comment by Guardian9978** [comment]
Another way would be to have the bit highlighter change colors between black and white either by fading or a delayed blink.

**Comment by loudwhitenoise** [comment]
What if you make it like the cursor, inverted colour? It would show up on any surface then... not sure it would look the best but it's an idea
