### ISSUE TITLE
SilentGem possibly causing an issue with C&B block placement

### ISSUE THREAD

**Issue by jc2xs** [ChiselsAndBits/Chisels-and-Bits#354]
Minecraft Version: 1.12.2
Silent's Gems Version: 2.5.11-250
Silent Lib Version: 2.2.15-96
C&B Version: 14.11
Modpack and Version (if applicable): EOD Synthesis 1.2.3
Optifine is not used.

Expected behavior
Using the shift key to place a Chisel & Bits positive template and left clicking should place the block. Removing Silent's Gems and the Lib from the pack does resolve the issue.

Actual behaviour
It will make the sound like it is placing it but will not place the block.

Steps to reproduce the problem
With a C&B bits make a structure/item then make a positive of it. Then try to place the new block using shift and left click. Disabling just Silent's lib and gems does enable this functionality work. Verified that there are no other shift key binding conflicts.

End-of-Days-Modpack-Team/Synthesis#7
https://github.com/SilentChaos512/SilentGems/issues/261

**Comment by AlgorithmX2** [comment]
It seems that SilentGems is modifying my itemstacks on the client side adding "SGProperties" to the NBT Data, so when that stack is sent to the client for use the ItemStack doesn't match the server.

@SilentChaos512 thoughts on this? Is adding this NBT Data to other items intended?

**Comment by SilentChaos512** [comment]
I added a check to prevent the tag from getting onto things it shouldn't be on. Seems to have fixed the issue.

**Comment by jc2xs** [comment]
Cool thanks SilentChaos512.  I'll the issue here then and let you close the one Silent's GitHub.
