### ISSUE TITLE
Compatibility with /Dank/Null

### ISSUE THREAD

**Issue by mohler7154** [ChiselsAndBits/Chisels-and-Bits#355]
I was wondering if it was possible to make chisel and bits compatible with the /Dank/Null allowing you to build with bits that are stored in it.  This would make it possible to use the DankNull as a bit bag with auto voiding when you have excessive amounts of bits.

**Comment by AlgorithmX2** [comment]
It seems that /Dank/Null is an inventory, is the only thing that I would need to do is pull out of it? Or would more coding be required. ( I have never used the mod and I don't know how it works )

**Comment by mohler7154** [comment]
As far as I know it is an inventory and uses the forge item handling.  When
I get home I'll get more information.

On Dec 20, 2017 4:53 PM, "AlgorithmX2" <notifications@github.com> wrote:

It seems that /Dank/Null is an inventory, is the only thing that I would
need to do is pull out of it? Or would more coding be required. ( I have
never used the mod and I don't know how it works )

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/AlgorithmX2/Chisels-and-Bits/issues/355#issuecomment-353193270>,
or mute the thread

**Comment by mohler7154** [comment]
This is the response I got from the developer for the dank null.  Hope it helps as I'd love this fearure.

commented about 10 hours ago
The reason the /dank/null works with BBW is because portablejim added support for pulling items out of items that implement Forge's IItemHandler capability. This would be on AlgorythmX2 to add such support

**Comment by AlgorithmX2** [comment]
That's what I meant by "it seems that it is an inventory."

I was merely asking that if I did pull bits out of /dank/null that it would be a complete solution, and wouldn't require for instance inserting bits into it, or anything else.

**Comment by mohler7154** [comment]
Yeah.  Danknull pulls items in and automatically voids when full, if chisel
and bits could pull it out it would be a complete system.  Btw thanks for
all your modded work.  Love the mods!

**Comment by AlgorithmX2** [comment]
Please try https://www.dropbox.com/s/68ycsiw5bmuudnd/chiselsandbits-14.0.jar?dl=1 see if its working. Also please verify to the best of your ability that there are no duplication or voids in the process... except for the obvious intentional voids because of the /dank/null

**Comment by mohler7154** [comment]
Tested in a pack with just /Dank/Null and the jar you sent me.  It works as intended and does not duplicate or void any bits.   There does however seem to be an issue where the bits prioritize going into the players inventory before being picked up by the /Dank/Null, but i believe this is something with the /Dank/Null mod, not something from chisel and bits.  Thanks for the fast response.

**Comment by AlgorithmX2** [comment]
@p455w0rd Which event or logic are you using to detect items being added to the inventory?

I'm presently using, player.inventory.addItemStackToInventory to insert bits into the inventory until the inventory is full. I imagine since this fires no event its causing the problem.

If you can let me know which event your using I can probably sort that out.

**Comment by p455w0rd** [comment]
net.minecraftforge.event.entity.player.EntityItemPickupEvent

https://github.com/p455w0rd/DankNull/blob/1.12/src/main/java/p455w0rd/danknull/init/ModEvents.java#L86-L100

**Comment by AlgorithmX2** [comment]
@mohler7154 I've updated the build above, please test and confirm that its working properly.

**Comment by mohler7154** [comment]
Works perfectly.

**Comment by mohler7154** [comment]
A little more testing and found a potential issue.  When I use the positive chisel design to replace, it does add the bits that you are replacing into the dank null if they are in there, as intended, but once the dank null reaches the point where the bits are full, it does not allow you to replace the block.  So it appears that when it reaches the maximum amount in the Dank Null instead of voiding them, it will not allow you to replace the block.

**Comment by mohler7154** [comment]
Disregard my last comment,  the problem is that my chisel ran out and i did not notice.  However, while the positive chisel design can put bits into the dank null, it cannot pull them out, it behaves as though you are out of the bits that are needed.

**Comment by AlgorithmX2** [comment]
It took a while but this is officially release in 14.12 now.
