### ISSUE TITLE
Thank you / Merry Christmas

### ISSUE THREAD

**Issue by alphapapa** [ChiselsAndBits/Chisels-and-Bits#356]
Hi there,

Just wanted to say Merry Christmas and thank you for this amazing mod.  Here are some things a friend and I did tonight in our ravine town, none of which would be possible without it!

![2017-12-25_01 02 38](https://user-images.githubusercontent.com/601365/34335484-af3d8cfe-e914-11e7-86c4-21655ad3057a.png)
![2017-12-25_00 20 12](https://user-images.githubusercontent.com/601365/34335490-ba8af6b4-e914-11e7-9bac-cab1e33800f7.png)

**Comment by AlgorithmX2** [comment]
Thanks, and thanks for sharing!
