### ISSUE TITLE
Incompatibility between chisel and bits and refined storage cables

### ISSUE THREAD

**Issue by jamthief** [ChiselsAndBits/Chisels-and-Bits#359]
Whenever I combine chisel and bits with refined storage cables in a single block, then leave and return to the world, I get an issue that causes client side rendering issues (demonstrated in the attached screenshots).

Steps to reproduce:

1. Place a chisel and bits piece in the same block as a refined storage cable.
2. Leave the world, so that the chunk is unloaded.
3. Rejoin the world.

Client log is also attached - relevant message is something like:

```
[21:27:25] [main/ERROR] [CodeChickenLib]: A CCL controlled model has reported an error and will NOT be rendered: 
Null tile. Position: MutableBlockPos{x=-298, y=55, z=270}
```

* MC Version: 1.12.2
* C&B Version: 14.10
* Do You have Optifine: No

[partiallog.txt](https://github.com/AlgorithmX2/Chisels-and-Bits/files/1598973/partiallog.txt)
![2018-01-02_20 55 31](https://user-images.githubusercontent.com/635017/34503645-7b9dc0ea-f011-11e7-8cbe-d8f7e1912ac3.png)
![2018-01-02_20 57 23](https://user-images.githubusercontent.com/635017/34503646-7bb68030-f011-11e7-86ce-b91224c39fda.png)

**Comment by AlgorithmX2** [comment]
Please make sure your using the latest version of C&B and MCMP.

C&B should be 14.11, and MCMP should be 2.4.1

**Comment by jamthief** [comment]
Hi, the problem goes away when upgrading to the latest version of MCMP (2.4.1). Thanks.
