### ISSUE TITLE
ExtraUtilities2 - Incompatability, Some bits are invisible

### ISSUE THREAD

**Issue by ghost** [ChiselsAndBits/Chisels-and-Bits#36]
Polished stone (from ExtraUtilities2)-Bits are most of the time (sometimes some of them work fine) invisible allowing you to see the caves (the thing that happens if a solid block has a transparent texture). I tested this at two diffrent days, with and without Optifine and with multiple restarts and texture-reloads.

![2016-04-03_20 54 02](https://cloud.githubusercontent.com/assets/15161537/14234241/6632fb42-f9de-11e5-80b4-5370cf3026de.png)
Here one side of the block shows the texture, the other doesn't. Both sides are Polished Stone (a third side stone bricks).

![2016-04-03_20 54 25](https://cloud.githubusercontent.com/assets/15161537/14234242/6929754c-f9de-11e5-969c-e68b814ef5ce.png)
This should be mostly polished stone....

Sorry for my english, it isn't my native language ;)

**Comment by ghost** [comment]
And one time a chiseld grass block went completely black. I wasn't able to reproduce it. Also chiseld grass has white grass on top when it is in the inventory and the shift key is pressed (to show the whole block)

**Comment by AlgorithmX2** [comment]
Which version are you using?

I can only reproduce a single issue with grass, in that the bit when holding shift renders as white, other wise grass seems to render fine in all cases.

I can reproduce the issue with Polished stone, but it will need some further research to see if I can solve it.

**Comment by ghost** [comment]
Im using [this](http://mods.curse.com/modpacks/minecraft/241720-enlight) modpack... Last time I checked, curse didn't show any updates. I can look up the version later...

**Comment by ghost** [comment]
I'm using chiselandbits-8.7 and forge-11.15.1.1808.

**Comment by AlgorithmX2** [comment]
Strange, that is the latest version, i'm not sure why your getting white grass in the world... Which biome is it inside of?

**Comment by ghost** [comment]
The white grass is in the inventory.
In the world the complete block went black. But that was with Optifine and could not be reproduced with or without Optifine

**Comment by AlgorithmX2** [comment]
Hmm, ok, so maybe its the same issue that I could reproduce.

**Comment by AlgorithmX2** [comment]
"Something" is weird with the XU2 block models.. I don't know what.. but its something... 

In other news I've simplified the model fall back plan in C&B which should resolve this in the next build.

**Comment by AlgorithmX2** [comment]
Included in latest build.

**Comment by ghost** [comment]
Thank You!
