### ISSUE TITLE
Shift placement deletes blocks

### ISSUE THREAD

**Issue by nicholasandrzej** [ChiselsAndBits/Chisels-and-Bits#362]
For any bug reports please provide the following details as well,
* MC Version: 1.12.2
* C&B Version: 14.11
* Do You have Optifine: Yes

When shift-placing (to ignore boundaries) using the blueprints, bits are removed from the bit bags, and nothing is placed. They don't seem to make ghost blocks, as I can see no hitbox and can place regular blocks in the same place just fine. In addition, if I don't shift-place the design, but place it normally, break it, and shift-place the bits from the block item, the same thing happens. Simply put, shift-placing just deletes bits.

**Comment by AlgorithmX2** [comment]
I was unable to re-produce this. Can you provide any other details? Dose it only happen in certain situations?

Perhaps test without other mods?

**Comment by nicholasandrzej** [comment]
I was making girders out of Immersive Engineering Steel and grates out of Chisel factory blocks. It also occurs with vanilla bits in the same profile. I made a fresh profile with just chisels and bits, but I can't replicate it. The pack I was having an issue with was FTB Horizons. I'll get back to you if I find anything else.

**Comment by AlgorithmX2** [comment]
Definitely sounds like another mod is conflicting some how. The question unfortunately is which, and how.
