### ISSUE TITLE
[Request] Reverse Crafting

### ISSUE THREAD

**Issue by scofrona** [ChiselsAndBits/Chisels-and-Bits#363]
Being able to combine appropriate slices or (assuming correctly) 32 bits from the same block on a crafting table back into the original block. I think this would possibly help resolve waste/storage issues for unused bits or accidental incorrect slices.

#113 

Currently playing on FTB Revelation.

For any bug reports please provide the following details as well,
* MC Version: 1.12.2
* C&B Version: Newest
* Do You have Optifine: Yes (No issues)

**Comment by AlgorithmX2** [comment]
Are you saying you want #113? if so... why did you post a new issue?

**Comment by AlgorithmX2** [comment]
If your asking for a way to re-merge planes you've cut out or something, which based on your other ticket seems likely, I think that the same issue I posed there is relevant here, does it make sense for the mod to special case very particular cases like "plane" + "identical plane" = thicker plane, when you can't take random object 1, and random object 2 and combine them in any meaningful way?

**Comment by scofrona** [comment]
I don't think it's necessarily special case to want to create a parent object out of the child. The reason I was referencing #113 was more because I was under the impression that combining parts in a crafting bench was already something you were considering.

When experimenting with the saw I found having several different child objects taking up inventory space is frustrating, and creating bits out of pre-cut slabs wears down the player's saw (or chisel if placed). Combining parts could also be limited to items that are exactly half of the parent size. Two 4x4x1 slabs combine into a 4x4x2. Two of those 4x4x2 combine back into the original block. It's part of why I mentioned the confusion between vertically oriented and horizontally oriented slabs in my other ticket.

I would argue that combining random objects together would be a different beast entirely. That's also something that, assuming they are combined in the same block space, might be possible through placing the objects together in the world and "mining" the newly compounded block, though admittedly I don't know if this is already the case. That's more about creating compound objects rather than what I would view as inventory clean up.

**Comment by AlgorithmX2** [comment]
Its not that I mean that creating a parent object out of children is a "special case" in the sense that its unique, but rather in development terms, that this is very specific case in the full scope of all possible options. in other words considering the ridiculous scope of possibility in the 16x16x16 by blocktypes 

in the case of #113, the idea was to put different objects you have created separately together into one block, however I think that this isn't as useful as it seems, at least in the scope of inventory based crafting. In world makes far more sense for such a feature, and general with C&B its easier to use bits/patterns to achieve your goals then using blocks. I recognize that this means spending durability, but at the same time the diamond chisel had a good amount of durability and only costs one diamond.

If durability is that much of a hangup you can always disable tool damage. 

As you say you can already achieve these steps via in world interactions, placing multiple parts together in the same block space is certainly possible, in the case of your saw cut planes as well as more complicated creations.

The saw was a feature request to try and fill in for people coming from microblocks, a way to create those common shapes that they are used too, and to be honest the idea doesn't mesh very well with the rest of the mod which encourages on demand creation of blocks from bits.

I think more then anything I'm inclined to try and solve this sort of "problem" with a gui that lets you "chisel" the block into bits rather then combine arbitrary blocks. 

I think such a solution would be an improvement for several reasons,

1. Combining smaller "slices" is a very specific operation only available to a very small subset of created blocks, specifically blocks that have been "sawed" that full size, or their equivalent.

2. It would be more streamlined, not requiring you to match up and combine blocks in logical order you would simply say "I don't need this anymore, give me the bits!" and your done, at this point you could use the bits to create blocks, or store them in bags for latter.

3. #113 is an example of my earlier ideas that crafting would be a core part of the mod, and you could use it for various functions, so far in my experience most people are unaware of these crafting related features on large, and I think that the the in world variation and side of things are far more intuitive. You can already achieve the the end goal as a means of placing and mining / chiseling, any feature added by this request is more or less a "quality of life" improvement.

**Comment by Unknow0059** [comment]
I also am behind this feature request. It would be great to join, let's say Wood Slices ×64×2 into full-sized blocks (those slices are identical).
