### ISSUE TITLE
A way to prevent 'bits' from spilling on the floor

### ISSUE THREAD

**Issue by Noxite** [ChiselsAndBits/Chisels-and-Bits#365]
* MC Version: 1.12.2
* C&B Version: chiselsandbits-14.12
* Do You have Optifine: Yes

I'm having a problem trying to run a survival server with Chisel & Bits, since 'chiselling' an entire block and not having space in your inventory for the bits will spill all the bits on the floor and cause **major** lag. 

It would be great for the mod to prevent the player from chiselling a block if they don't have the inventory space for it.

**Comment by Noxite** [comment]
Now **that's** a fix! When will this get pushed to Curseforge?

**Comment by AlgorithmX2** [comment]
Probably tonight to tomorrow, I'll close this issue once its released.

**Comment by AlgorithmX2** [comment]
The pull request has been included in 14.13
