### ISSUE TITLE
[1.10.2] chisels and bits crash with certain conquest reforged blocks

### ISSUE THREAD

**Issue by xemnes** [ChiselsAndBits/Chisels-and-Bits#367]
* MC Version: 1.10.2
* C&B Version: 12.16
* Do You have Optifine: yes

some blocks in conquest reforged are causing a crash when used with chisels and bits, but only if the block his held and is visible in the inventory.
the block ive used to test and replicate this crash is conquest:stone_log_1[variant=bravo]
it seems to affect blocks that act like logs which can be placed at different orientations, ive tested a few log type blocks. though it only happens if you place the block horizontally, chisel it then middle click it to get it into your inventory.
if the block is placed vertically, it doesnt crash.

client crash log:
https://pastebin.com/PdRfWCgT

server also spits out an error but doesnt crash the server:
https://pastebin.com/ecy9Tt0Q

**Comment by AlgorithmX2** [comment]
Give https://dvs1.progwml6.com/jenkins/job/Chisels-and-Bits/114/artifact/build/libs/chiselsandbits-12.0.114.jar a try, I changed how it determines names for those it might fix it.

**Comment by xemnes** [comment]
testing now, thanks.

**Comment by xemnes** [comment]
forge is reporting that extra bit manipulation requires chisels and bits 12.11 or above and wont start.

**Comment by AlgorithmX2** [comment]
https://www.dropbox.com/s/pgy11cvyvqu1cj5/chiselsandbits-12.13.jar?dl=1 here is a version built locally with a more correct version number.

**Comment by xemnes** [comment]
thank you! now testing

**Comment by xemnes** [comment]
yup that fixed it! thank you.

**Comment by AlgorithmX2** [comment]
This is fixed in the least builds from 1.10.2 up.
