### ISSUE TITLE
Add an in-game exporter for a selection's blockstate json, model json, and the textures. Or OBJ

### ISSUE THREAD

**Issue by SaadArdati** [ChiselsAndBits/Chisels-and-Bits#37]
It's so much simpler to just build the blocks you want to make a mod for :) I'd love a creative item in which you make a selection and hit a button to export all the json and textures for a static block. Or perhaps even an OBJ file option.

**Comment by AlgorithmX2** [comment]
use /c&b.exportmodel

it exports the held item as a block model json.

**Comment by SaadArdati** [comment]
Could you provide a link to the program please?

**Comment by AlgorithmX2** [comment]
What program?

/c&b.exportmodel is a in game command which is part of C&B. 8.x and 9.x

**Comment by SaadArdati** [comment]
Oh thank you.
