### ISSUE TITLE
How do i remove saved bits?

### ISSUE THREAD

**Issue by purple178** [ChiselsAndBits/Chisels-and-Bits#371]
I've made some mistakes on saved bits. If someone can tell me how to remove saved bits, that would be great.

Version of minecraft: 1.10.2 Forge
Version of C&B: 1.10.2
Do i have optifine: No

tell me if you need more information.

**Comment by AlgorithmX2** [comment]
Saved bits? do you mean the creative clipboard? If do you can open up the file, its chiselsandbits_clipboard.cfg I think in your clients config folder. Its probably hard to pick out which ones are the ones you want to remove, so you could potentially place the ones you want to keep in a world and just delete the whole file to reset the entire clipboard.

If you mean something else you might need to explain.

**Comment by purple178** [comment]
Thank you for helping AlgorithmX2. and yes i meant the Creative Clipboard.
