### ISSUE TITLE
Chiselling Immersive Engineering crates (1.10.2)

### ISSUE THREAD

**Issue by GabrielCorso** [ChiselsAndBits/Chisels-and-Bits#373]
Is there any way i can blacklist specific blocks?
I'm running C&B and Immersive engineering on 1.10.2 (versions 12.16 and 0.10-61, respectivelly) and would like to know what to input on the config to blacklist the chiseling of IE storage crates, as they don't have a texture when chiseled and lose their inventories when rearranged.

Thanks for the help :)

**Comment by AlgorithmX2** [comment]
Those are being specifically white-listed by IE, C&B settings for enable or disabling blocks don't override this at the moment, I'm not sure of a good solution at the moment.

**Comment by GabrielCorso** [comment]
Okay, thanks for answering. 
I guess i can ask blusunrize why it's coded as such, as it's a really weird interaction.

**Comment by AlgorithmX2** [comment]
It does seem odd for a block that has no texture when chseled to be marked as whitelisted for chiseling.
