### ISSUE TITLE
[Request] change button for presision set of blocks

### ISSUE THREAD

**Issue by whitequill** [ChiselsAndBits/Chisels-and-Bits#377]
I would like to see the button changed for precise setting of chiseled blocks from Shift to Ctrl or another key. Cause it is annoying dropping out of the sky when you are trying to set a chiseled block while flying.

For any bug reports please provide the following details as well,
* MC Version: 1.12.2
* C&B Version: 14.11
* Forge 14.23.2.2611
* Do You have Optifine: yes HD_U_C9

**Comment by AlgorithmX2** [comment]
Most likely an optional key-bind that overrides the default "sneak" behavior will be better then an universal change, lots of people are used to the sneak behavior, and changing it out right at this point will likely yield a large amount of confusion.

**Comment by whitequill** [comment]
I often find myself falling out of the sky while I "sneak" while trying to get a good position to see my work better if I'm working on something in the air.

**Comment by AlgorithmX2** [comment]
Give https://www.dropbox.com/s/9fvfn4siz3077qt/chiselsandbits-14.18.jar?dl=1 a try, I added a keybind you can set, that overrides the default behavior.

Hopefully it works great and doesn't explode!

**Comment by AlgorithmX2** [comment]
14.18 is released in beta.
