### ISSUE TITLE
Updated map from 1.8 to 1.12.2, now my chisles are all replaced with normalblocks.

### ISSUE THREAD

**Issue by Jonat1221** [ChiselsAndBits/Chisels-and-Bits#379]
Hi,
as Title states i just updated my 2k+ hours singleplayer map from 1.8 to 1.12.2.
I had quite a lot of custome made blocks. And they are all gone, but one. I had one block in my inventory and it got safed. But that does not help.
Is this a resourcepack fail, since i am not 100% sure that i updated my resourcepack correclty and its a looot of work to do, since i use diffrent once to make my own...

For any bug reports please provide the following details as well,

MC Version: 1.12.2
C&B Version: 14.16
Forge 14.23.2.2654
Do You have Optifine: yes HD_U_D1

First bug report so please let me know if you need to know further informations. 
I hope i just fucked up the updating process!
![2018-04-09_01 12 25](https://user-images.githubusercontent.com/38194249/38473637-a10385ae-3b93-11e8-8af5-bbc418d2c8e7.png)

![2018-04-07_00 20 20](https://user-images.githubusercontent.com/38194249/38473636-9bc33044-3b93-11e8-83bf-58bae82ba350.png)

I know that there also is a texturepack fail in the screenshot. Can fix it later by myself.

I have a lot of backups store on diffrent places, so if this is nothing we can work on i can always fall back to my 1.8 version, but there is a nasty visual glitch in that version that i need to get rid of and an easy way would be to update to 1.12.2!! I am talking about this one:
![2018-03-31_20 25 39](https://user-images.githubusercontent.com/38194249/38473653-dec8db6e-3b93-11e8-877c-24d09845225e.png)

Dissapearing "chunks" and i cant fix it. but thats just a side note if you know about it.

**Comment by AlgorithmX2** [comment]
I can't say much based on the pictures, I would suggest checking your log, 1.8 is pretty old and doing a single upgrade from 1.8 to 1.12 might have caused things to go a fowl for one reason or another, I know that several things like the block ids and name spaces changed at one point or another, I thought that the version that did that accounted for the change however.

The logs might indicate what the problem is when loading, you could also try loading up 1.9 or 1.10 first to see if it works in either of those versions.

**Comment by Jonat1221** [comment]
Okay, thanks. I updated now from a backup to 1.9 and i had no visual glitches from my last screenshot and thats the reason for me to update anyways, so i will try to stay with 1.9 for now. But now i have a new issue.
Some but not all C&B blocks are invis. I can not destroy and replace them, that does not work.
But these blocks render first and then turn invis. I can see them for a moment. Also some blocks seems to dissapear later then others.

For any bug reports please provide the following details as well,

MC Version: 1.9
C&B Version: 9.21
Forge 12.16.1.1887
Do You have Optifine: yes HD_U_E7

Edit: It is optifine related. When i dissable it, all blocks are back again. Is there a work around for it? Or should i try updating for newer versions?

**Comment by Jonat1221** [comment]
Fixed it by myself. Updated now to 1.10 in small steps and all blocks are here. Ty for your help.

**Comment by AlgorithmX2** [comment]
No problem, glad you've managed to resolve the issue.
