### ISSUE TITLE
Block-Map Mix-up On Sound / Texture Reload

### ISSUE THREAD

**Issue by oitsjustjose** [ChiselsAndBits/Chisels-and-Bits#38]
On Chisels & Bits v. 8.7:

So, I'll describe my steps carefully:
**Before:**
![2016-04-04_18 13 30](https://cloud.githubusercontent.com/assets/3887324/14265739/43a34eb6-fa91-11e5-97f1-a075979910ab.png)

**After F3 + S (also happens with F3 + T):**
![2016-04-04_18 11 43](https://cloud.githubusercontent.com/assets/3887324/14265746/51b941f4-fa91-11e5-84d6-8b38def0a340.png)

**After Server Re-Log / World Re-Load:**

![2016-04-04_18 12 18](https://cloud.githubusercontent.com/assets/3887324/14265758/636bcd36-fa91-11e5-9d34-4504604cdf87.png)

Notice how even after re-log, the metadata of the blocks is wrong: the stone bordering the glass is the wrong metadata, and the wool pixel art which you can see inside my house is pink instead of white.

**Comment by AlgorithmX2** [comment]
Well that is odd I could have sworn I fixed this before...

**Comment by AlgorithmX2** [comment]
Should be fixed in new builds.
