### ISSUE TITLE
[Request] Chiseled bits such as Glowstone and Sea Lanterns should produce light

### ISSUE THREAD

**Issue by Spearkiller** [ChiselsAndBits/Chisels-and-Bits#380]
Forge Microblocks had this ability, and it was really cool to be able to make blocks of glowstone and the likes much smaller and interfere less in buildings.
Maybe make it configurable in the configs though, so that you can't abuse hacking a block of glowstone into bits and having another 4095 light sources, if that was an issue for some people, but personally I see it as quite a handy feature, allowing you to make things like Floodlights and Computer monitors that actually glow.

**Comment by Dushess** [comment]
Set bitlightpercentage=1 or 0

**Comment by AlgorithmX2** [comment]
As Dushess has indicated C&B already supports glowstone and such, By default it requires 256 bits to archive full brightness, you can adjust this using the option mentioned above, it controls how much of the block is required to make the block glow with full intensity, 0 should make it work with a single bit, 1 will make it work with the entire block.

**Comment by Dushess** [comment]
I mean 1% is enought to get full brightness from only few bits.

**Comment by Overkil04** [comment]
Hello guys could u pls tell me where to adjust those settings i mean where do i find this bitlightpercentage ?
ty

**Comment by Dushess** [comment]
options file of course, \.minecraft\config
