### ISSUE TITLE
severe problem made the game crash and i dont know what crashed it

### ISSUE THREAD

**Issue by Buginator9000** [ChiselsAndBits/Chisels-and-Bits#382]
severe problem made the game crash and i dont know what crashed it please help

[crash-2018-04-21_12.12.47-client.txt](https://github.com/AlgorithmX2/Chisels-and-Bits/files/1934429/crash-2018-04-21_12.12.47-client.txt)

its 1.7.10

**Comment by Buginator9000** [comment]
if it helps here are my mods
![image](https://user-images.githubusercontent.com/37192150/39083644-d81d841c-4567-11e8-8545-cc3a0a6bb3ab.png)
![image](https://user-images.githubusercontent.com/37192150/39083646-e61499d4-4567-11e8-9cad-7596f2de35e5.png)
![image](https://user-images.githubusercontent.com/37192150/39083647-ef966f5a-4567-11e8-9bb4-8f9374c6b660.png)

i know they are a lot

**Comment by AlgorithmX2** [comment]
I would bet its because your mixing versions, you've got mods from 1.12 in there.

In the end this has nothing to do with C&B, and C&B isn't available for 1.7.10, so I'm closing this.

**Comment by Buginator9000** [comment]
oh
