### ISSUE TITLE
Chunk update lag - Block Placing/Breaking Lag

### ISSUE THREAD

**Issue by LuxerIThink** [ChiselsAndBits/Chisels-and-Bits#384]
Hi. I creating a microblocks world and I found a strange bug. I built a massive structure (picture 1) and I have a strange lag with it and other microblocks buildings. When I was placing or breaking blocks near the structure (8-13 blocks) I have a short lag to zero FPS (picture 2). The hugest lag in north side, but build is symmetrical. In Optifine lagometer I saw that it was a chunk update lag (picture 2). Lag Goggles doesn't see the lag. Changing structure of the microblock and placing or breaking blocks by worldedit also doesn't make a lag. Can you explain that?

Picture 1: https://imgur.com/Nms717L
Picture 2: https://imgur.com/4E6RYpe

Q&A
* MC Version: 1.12.2
* C&B Version: 14.13
* Do You have Optifine: YES

Mods:
Ambient Sounds [2.2.5]
Animania [1.4.5]
Auto Reg Lib [1.3-15]
Better Foliage [2.1.10]
Biomes O Plenty [7.0.1.2334]
Chisels And Bits [14.13]
Craft Studio [1.0.0.93]
Dynamic Trees [0.7.5c]
Dynamic Trees BoP [beta+2]
Earthworks [1.3.6]
Extra Bit Manipulation [3.2.1]
Familiar Fauna [1.0.4]
Foam Fix [0.9.5]
Horizontal Glass Pane [1.0]
Just Enough Items [4.8.5.159]
Mr Crayfish Furniture [4.2.0]
Multihotbar [3.2-build-T113]
Not Enough Roofs [0.6.1.0]
OptiFine [HD_U_C9]
Placeable Items [3.2]
Quark [r1.4-122]
Replay [2.1.2]
Rustic [0.4.10]
Sampler [1.73]
Serene Seasons [1.0.0]
Substrate [1.2]
Thicc Entities [1.2]
TIM's Expansion [3.0.1]
Worldedit [6.1.8]
Xtones [1.0.8-11]

My PC:
Intel Core i5 3550P 3.1GHz
Geforce GTX 970 4Gb
16 GB RAM DDR3 {2x8Gb}
120 Gb SSD
1Tb HDD
Windows 10 Pro

Sorry for my English :P

**Comment by AlgorithmX2** [comment]
I believe you are seeing the time it takes to re-build the chunk from scratch upon change. I believe its a proximity related thing, when you are near to the block during a break, it causes the client to rebuild it from scratch and upload it on the spot, rather then using the threaded renderer where it does it in the background and uploads it when ready.

Without optifine C&B tries to use Tile-entities when this sort of thing exceeds a certain limit to try and mitigate the problem, with optifine this causes rendering issues so its disabled.

I think this happens with most very complicated models.

**Comment by invalidtask** [comment]
I have this same issue, with and without optifine. Only happens in the chunks that contain chisel and bits. 

Minecraft 1.12.2
C&B: 14.17

**Comment by AlgorithmX2** [comment]
As I've described above, this has to do with MC's normal rendering calculations. Without Optifine, C&B Attempts to mitigate the problem, however this is a far cry from "solves the issue entirely" you can try switching the default renderer without optifine installed to Dynamic ( this is in the in game gui settings under Client Settings )

Switching to use dynamic as the default might improve lag in some cases. Unfortunately I've never found a configuration that solves all issues, just improves some sub set, the in-game lighting calculations that MC uses preform horribly with large numbers of polygons.

There is also a setting for MC Forge called alwaysSetupTerrainOffThread which might improve block lag, so you can also give that a try.
