### ISSUE TITLE
Eye Dropper Tool

### ISSUE THREAD

**Issue by acanady** [ChiselsAndBits/Chisels-and-Bits#387]
I don't think this is currently in Chisels and Bits but an eyedropper tool would be awesome! Let's say I have a grass block and I want a specific color of green from that block. I could use the eyedropper tool to get the rgb value of that specific bit. I could then craft a flat colored block that matches the rgb value that was returned.

**Comment by AlgorithmX2** [comment]
Think that this probably belongs to FCB, where there is already a similar request, https://github.com/AlgorithmX2/FlatColoredBlocks/issues/10
