### ISSUE TITLE
Forge Incompatibility : forge 12-1805

### ISSUE THREAD

**Issue by evansbl1997** [ChiselsAndBits/Chisels-and-Bits#39]
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 4/5/16 5:59 AM
Description: Unexpected error

java.lang.NoSuchMethodError: net.minecraftforge.event.entity.player.PlayerInteractEvent.getAction()Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$Action;
    at mod.chiselsandbits.events.EventPlayerInteract.interaction(EventPlayerInteract.java:20)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_19_EventPlayerInteract_interaction_PlayerInteractEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
    at net.minecraftforge.common.ForgeHooks.onLeftClickBlock(ForgeHooks.java:963)
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_180511_b(PlayerControllerMP.java:226)
    at net.minecraft.client.Minecraft.func_147116_af(Minecraft.java:1452)
    at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2166)
    at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1955)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1743)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1051)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:366)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at mod.chiselsandbits.events.EventPlayerInteract.interaction(EventPlayerInteract.java:20)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_19_EventPlayerInteract_interaction_PlayerInteractEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
    at net.minecraftforge.common.ForgeHooks.onLeftClickBlock(ForgeHooks.java:963)
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_180511_b(PlayerControllerMP.java:226)
    at net.minecraft.client.Minecraft.func_147116_af(Minecraft.java:1452)
    at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2166)
    at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1955)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityPlayerSP['ShadesCraft1997'/238, l='MpServer', x=177.50, y=67.00, z=130.50]]
    Chunk stats: MultiplayerChunkCache: 479, 479
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: World: (186,64,137), Chunk: (at 10,4,9 in 11,8; contains blocks 176,0,128 to 191,255,143), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 60 game time, 60 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
    Forced entities: 267 total; [EntityFallingBlock['Falling Block'/2054, l='MpServer', x=123.50, y=27.95, z=279.50], EntityFallingBlock['Falling Block'/2055, l='MpServer', x=123.50, y=28.95, z=280.50], EntityFallingBlock['Falling Block'/2056, l='MpServer', x=124.50, y=25.95, z=280.50], EntityFallingBlock['Falling Block'/2057, l='MpServer', x=124.50, y=26.95, z=279.50], EntityFallingBlock['Falling Block'/2058, l='MpServer', x=123.50, y=27.95, z=278.50], EntityFallingBlock['Falling Block'/2059, l='MpServer', x=124.50, y=26.95, z=278.50], EntityFallingBlock['Falling Block'/2060, l='MpServer', x=125.50, y=26.95, z=278.50], EntityFallingBlock['Falling Block'/2061, l='MpServer', x=122.50, y=29.95, z=278.50], EntityFallingBlock['Falling Block'/2062, l='MpServer', x=122.50, y=29.95, z=279.50], EntityFallingBlock['Falling Block'/2063, l='MpServer', x=123.50, y=27.95, z=277.50], EntityFallingBlock['Falling Block'/2064, l='MpServer', x=124.50, y=26.95, z=277.50], EntityFallingBlock['Falling Block'/2065, l='MpServer', x=122.50, y=29.95, z=277.50], EntityFallingBlock['Falling Block'/2066, l='MpServer', x=122.50, y=29.95, z=276.50], EntityFallingBlock['Falling Block'/2067, l='MpServer', x=123.50, y=26.95, z=276.50], EntityFallingBlock['Falling Block'/1559, l='MpServer', x=116.50, y=30.09, z=108.50], EntityFallingBlock['Falling Block'/1560, l='MpServer', x=117.50, y=29.09, z=108.50], EntityFallingBlock['Falling Block'/1561, l='MpServer', x=116.50, y=30.09, z=107.50], EntityFallingBlock['Falling Block'/1562, l='MpServer', x=116.50, y=30.09, z=109.50], EntityFallingBlock['Falling Block'/1563, l='MpServer', x=117.50, y=29.09, z=109.50], EntityFallingBlock['Falling Block'/1564, l='MpServer', x=115.50, y=31.09, z=108.50], EntityFallingBlock['Falling Block'/1565, l='MpServer', x=114.50, y=31.09, z=106.50], EntityFallingBlock['Falling Block'/1566, l='MpServer', x=114.50, y=32.09, z=107.50], EntityFallingBlock['Falling Block'/1567, l='MpServer', x=114.50, y=32.09, z=108.50], EntityFallingBlock['Falling Block'/1568, l='MpServer', x=114.50, y=32.09, z=109.50], EntityFallingBlock['Falling Block'/1569, l='MpServer', x=115.50, y=30.09, z=106.50], EntityFallingBlock['Falling Block'/1570, l='MpServer', x=115.50, y=31.09, z=107.50], EntityFallingBlock['Falling Block'/1571, l='MpServer', x=115.50, y=31.09, z=109.50], EntityBat['Bat'/548, l='MpServer', x=108.58, y=41.65, z=133.42], EntityFallingBlock['Falling Block'/1572, l='MpServer', x=115.50, y=31.09, z=110.50], EntityFallingBlock['Falling Block'/1573, l='MpServer', x=113.50, y=32.09, z=107.50], EntityFallingBlock['Falling Block'/1574, l='MpServer', x=113.50, y=32.09, z=108.50], EntityFallingBlock['Falling Block'/1575, l='MpServer', x=113.50, y=32.09, z=106.50], EntityFallingBlock['Falling Block'/1576, l='MpServer', x=114.50, y=31.09, z=105.50], EntityFallingBlock['Falling Block'/1577, l='MpServer', x=112.50, y=33.09, z=107.50], EntitySkeleton['Skeleton'/2089, l='MpServer', x=146.50, y=18.00, z=97.50], EntityFallingBlock['Falling Block'/1578, l='MpServer', x=112.50, y=33.09, z=108.50], EntityZombie['Zombie'/2091, l='MpServer', x=131.50, y=48.00, z=121.50], EntityCreeper['Creeper'/2092, l='MpServer', x=185.50, y=35.00, z=195.50], EntityFallingBlock['Falling Block'/1585, l='MpServer', x=105.50, y=23.09, z=134.50], EntityFallingBlock['Falling Block'/2100, l='MpServer', x=133.50, y=8.13, z=287.50], EntityFallingBlock['Falling Block'/1589, l='MpServer', x=105.50, y=24.09, z=133.50], EntityFallingBlock['Falling Block'/2101, l='MpServer', x=134.50, y=8.13, z=287.50], EntityFallingBlock['Falling Block'/2102, l='MpServer', x=135.50, y=8.13, z=287.50], EntityFallingBlock['Falling Block'/2103, l='MpServer', x=133.50, y=8.13, z=286.50], EntityFallingBlock['Falling Block'/2104, l='MpServer', x=134.50, y=9.13, z=286.50], EntityFallingBlock['Falling Block'/2105, l='MpServer', x=135.50, y=8.13, z=286.50], EntityFallingBlock['Falling Block'/1595, l='MpServer', x=118.50, y=48.09, z=131.50], EntityFallingBlock['Falling Block'/2107, l='MpServer', x=134.50, y=8.13, z=285.50], EntityFallingBlock['Falling Block'/1597, l='MpServer', x=116.50, y=48.09, z=131.50], EntitySheep['Sheep'/75, l='MpServer', x=141.50, y=69.00, z=136.50], EntitySheep['Sheep'/76, l='MpServer', x=141.50, y=69.00, z=138.50], EntitySheep['Sheep'/77, l='MpServer', x=140.50, y=69.00, z=140.50], EntitySheep['Sheep'/78, l='MpServer', x=139.50, y=69.00, z=142.50], EntitySheep['Sheep'/82, l='MpServer', x=150.50, y=64.00, z=210.50], EntityChicken['Chicken'/87, l='MpServer', x=167.50, y=75.00, z=147.50], EntityChicken['Chicken'/88, l='MpServer', x=165.50, y=75.00, z=147.50], EntityCreeper['Creeper'/2145, l='MpServer', x=155.50, y=28.00, z=142.50], EntitySheep['Sheep'/105, l='MpServer', x=206.50, y=73.00, z=68.50], EntitySheep['Sheep'/106, l='MpServer', x=206.50, y=73.00, z=70.50], EntitySheep['Sheep'/107, l='MpServer', x=205.50, y=75.00, z=70.50], EntitySheep['Sheep'/108, l='MpServer', x=205.50, y=75.00, z=68.50], EntityMinecartChest['container.minecart'/109, l='MpServer', x=218.50, y=25.06, z=76.50], EntityMinecartChest['container.minecart'/110, l='MpServer', x=226.50, y=25.06, z=91.50], EntityMinecartChest['container.minecart'/111, l='MpServer', x=224.50, y=25.06, z=89.50], EntitySheep['Sheep'/112, l='MpServer', x=225.17, y=65.00, z=124.49], EntitySheep['Sheep'/113, l='MpServer', x=224.18, y=65.00, z=124.38], EntitySheep['Sheep'/114, l='MpServer', x=221.50, y=64.00, z=126.50], EntitySheep['Sheep'/115, l='MpServer', x=219.50, y=65.00, z=122.50], EntityMinecartChest['container.minecart'/116, l='MpServer', x=235.50, y=24.06, z=63.50], EntityItem['item.tile.rail'/117, l='MpServer', x=240.88, y=24.00, z=87.25], EntityChicken['Chicken'/118, l='MpServer', x=242.50, y=68.00, z=78.50], EntityChicken['Chicken'/119, l='MpServer', x=245.50, y=68.00, z=77.50], EntityChicken['Chicken'/120, l='MpServer', x=242.50, y=68.00, z=76.50], EntityChicken['Chicken'/121, l='MpServer', x=242.50, y=68.00, z=77.50], EntityMinecartChest['container.minecart'/123, l='MpServer', x=236.50, y=15.06, z=131.50], EntityMinecartChest['container.minecart'/124, l='MpServer', x=243.50, y=19.06, z=123.50], EntityBat['Bat'/1148, l='MpServer', x=235.77, y=58.18, z=65.27], EntityMinecartChest['container.minecart'/125, l='MpServer', x=245.50, y=19.06, z=126.50], EntityFallingBlock['Falling Block'/1664, l='MpServer', x=103.50, y=8.27, z=173.50], EntityFallingBlock['Falling Block'/1667, l='MpServer', x=102.50, y=7.20, z=174.50], EntityFallingBlock['Falling Block'/1669, l='MpServer', x=101.50, y=6.09, z=176.50], EntityFallingBlock['Falling Block'/1670, l='MpServer', x=101.50, y=7.20, z=174.50], EntityCreeper['Creeper'/2183, l='MpServer', x=167.50, y=30.00, z=203.50], EntityFallingBlock['Falling Block'/2184, l='MpServer', x=152.50, y=60.94, z=125.50], EntityFallingBlock['Falling Block'/1673, l='MpServer', x=101.50, y=5.09, z=177.50], EntityFallingBlock['Falling Block'/2185, l='MpServer', x=151.50, y=60.94, z=124.50], EntityFallingBlock['Falling Block'/1674, l='MpServer', x=100.50, y=5.09, z=177.50], EntityFallingBlock['Falling Block'/2186, l='MpServer', x=150.50, y=60.94, z=123.50], EntityFallingBlock['Falling Block'/2187, l='MpServer', x=150.50, y=60.94, z=121.50], EntityFallingBlock['Falling Block'/2188, l='MpServer', x=149.50, y=60.94, z=121.50], EntityFallingBlock['Falling Block'/2189, l='MpServer', x=135.50, y=51.94, z=134.50], EntityFallingBlock['Falling Block'/2190, l='MpServer', x=136.50, y=51.00, z=134.50], EntityFallingBlock['Falling Block'/2191, l='MpServer', x=135.50, y=51.94, z=133.50], EntityFallingBlock['Falling Block'/2192, l='MpServer', x=134.50, y=51.94, z=133.50], EntityFallingBlock['Falling Block'/2193, l='MpServer', x=134.50, y=51.94, z=134.50], EntityFallingBlock['Falling Block'/2194, l='MpServer', x=135.50, y=51.94, z=132.50], EntityBat['Bat'/659, l='MpServer', x=139.48, y=16.88, z=99.80], EntityFallingBlock['Falling Block'/2195, l='MpServer', x=135.50, y=51.94, z=135.50], EntityFallingBlock['Falling Block'/2196, l='MpServer', x=134.50, y=51.94, z=132.50], EntityFallingBlock['Falling Block'/2197, l='MpServer', x=133.50, y=51.94, z=132.50], EntityFallingBlock['Falling Block'/2198, l='MpServer', x=133.50, y=51.94, z=134.50], EntityFallingBlock['Falling Block'/2199, l='MpServer', x=145.50, y=23.94, z=140.50], EntityFallingBlock['Falling Block'/2200, l='MpServer', x=146.50, y=23.94, z=140.50], EntityFallingBlock['Falling Block'/2201, l='MpServer', x=144.50, y=23.00, z=137.50], EntityFallingBlock['Falling Block'/2202, l='MpServer', x=143.50, y=20.94, z=137.50], EntityFallingBlock['Falling Block'/2203, l='MpServer', x=142.50, y=21.94, z=136.50], EntityFallingBlock['Falling Block'/2204, l='MpServer', x=143.50, y=21.94, z=136.50], EntityFallingBlock['Falling Block'/2205, l='MpServer', x=143.50, y=22.94, z=135.50], EntityFallingBlock['Falling Block'/2206, l='MpServer', x=144.50, y=21.94, z=135.50], EntityZombie['Zombie'/1219, l='MpServer', x=251.50, y=27.00, z=200.50], EntityFallingBlock['Falling Block'/2246, l='MpServer', x=144.50, y=23.25, z=135.50], EntityZombie['Zombie'/2265, l='MpServer', x=144.50, y=21.00, z=103.50], EntityFallingBlock['Falling Block'/2277, l='MpServer', x=145.50, y=62.63, z=289.50], EntityZombie['Zombie'/1262, l='MpServer', x=201.50, y=39.00, z=202.50], EntityZombie['Zombie'/2287, l='MpServer', x=177.50, y=35.00, z=193.50], EntitySkeleton['Skeleton'/1264, l='MpServer', x=188.50, y=33.00, z=186.50], EntityPlayerSP['ShadesCraft1997'/238, l='MpServer', x=177.50, y=67.00, z=130.50], EntityFallingBlock['Falling Block'/2297, l='MpServer', x=146.50, y=62.78, z=290.50], EntityFallingBlock['Falling Block'/2298, l='MpServer', x=147.50, y=62.78, z=290.50], EntityFallingBlock['Falling Block'/2299, l='MpServer', x=148.50, y=62.78, z=290.50], EntityFallingBlock['Falling Block'/2300, l='MpServer', x=149.50, y=62.78, z=290.50], EntityFallingBlock['Falling Block'/2301, l='MpServer', x=150.50, y=62.78, z=284.50], EntityFallingBlock['Falling Block'/2302, l='MpServer', x=151.50, y=62.78, z=289.50], EntityFallingBlock['Falling Block'/2303, l='MpServer', x=152.50, y=62.78, z=285.50], EntityFallingBlock['Falling Block'/2304, l='MpServer', x=152.50, y=62.78, z=288.50], EntityEnderman['Enderman'/1796, l='MpServer', x=162.50, y=28.00, z=145.50], EntitySkeleton['Skeleton'/2335, l='MpServer', x=146.50, y=23.00, z=193.50], EntityFallingBlock['Falling Block'/2338, l='MpServer', x=166.50, y=52.90, z=-7.50], EntityCreeper['Creeper'/803, l='MpServer', x=152.50, y=29.00, z=137.50], EntityFallingBlock['Falling Block'/2339, l='MpServer', x=166.50, y=53.90, z=-6.50], EntityFallingBlock['Falling Block'/2340, l='MpServer', x=167.50, y=53.90, z=-7.50], EntityFallingBlock['Falling Block'/2341, l='MpServer', x=167.50, y=53.90, z=-6.50], EntityFallingBlock['Falling Block'/2342, l='MpServer', x=168.50, y=52.90, z=-8.50], EntityFallingBlock['Falling Block'/2343, l='MpServer', x=168.50, y=53.90, z=-7.50], EntityFallingBlock['Falling Block'/2344, l='MpServer', x=168.50, y=54.90, z=-6.50], EntityFallingBlock['Falling Block'/2345, l='MpServer', x=168.50, y=54.90, z=-5.50], EntityFallingBlock['Falling Block'/2346, l='MpServer', x=169.50, y=53.90, z=-7.50], EntityFallingBlock['Falling Block'/2347, l='MpServer', x=167.50, y=51.90, z=-8.50], EntityFallingBlock['Falling Block'/2348, l='MpServer', x=169.50, y=52.90, z=-8.50], EntityBat['Bat'/301, l='MpServer', x=110.64, y=46.22, z=157.72], EntityFallingBlock['Falling Block'/2349, l='MpServer', x=165.50, y=52.90, z=-7.50], EntitySkeleton['Skeleton'/1336, l='MpServer', x=254.50, y=41.00, z=202.50], EntityCreeper['Creeper'/831, l='MpServer', x=211.50, y=24.00, z=57.50], EntityBat['Bat'/1858, l='MpServer', x=175.19, y=35.52, z=193.16], EntityZombie['Zombie'/839, l='MpServer', x=115.50, y=62.00, z=143.50], EntityFallingBlock['Falling Block'/2380, l='MpServer', x=155.50, y=28.94, z=65.50], EntityFallingBlock['Falling Block'/2381, l='MpServer', x=155.50, y=28.94, z=67.50], EntityBat['Bat'/1358, l='MpServer', x=129.70, y=29.08, z=136.48], EntityBat['Bat'/848, l='MpServer', x=112.22, y=58.52, z=162.42], EntitySkeleton['Skeleton'/339, l='MpServer', x=254.50, y=23.00, z=206.50], EntityFallingBlock['Falling Block'/1364, l='MpServer', x=97.50, y=54.18, z=132.50], EntityFallingBlock['Falling Block'/1365, l='MpServer', x=98.50, y=54.18, z=132.50], EntityFallingBlock['Falling Block'/1366, l='MpServer', x=98.50, y=54.18, z=133.50], EntityFallingBlock['Falling Block'/1367, l='MpServer', x=96.50, y=54.18, z=133.50], EntityFallingBlock['Falling Block'/1368, l='MpServer', x=97.50, y=54.18, z=133.50], EntityFallingBlock['Falling Block'/1369, l='MpServer', x=97.50, y=54.18, z=134.50], EntityCreeper['Creeper'/346, l='MpServer', x=144.50, y=24.00, z=192.50], EntityFallingBlock['Falling Block'/1370, l='MpServer', x=98.50, y=54.18, z=134.50], EntityFallingBlock['Falling Block'/1371, l='MpServer', x=99.50, y=54.18, z=133.50], EntitySkeleton['Skeleton'/348, l='MpServer', x=230.50, y=55.00, z=51.50], EntityFallingBlock['Falling Block'/1372, l='MpServer', x=96.50, y=54.18, z=134.50], EntityFallingBlock['Falling Block'/1373, l='MpServer', x=97.50, y=54.18, z=135.50], EntityZombie['Zombie'/2397, l='MpServer', x=233.50, y=18.00, z=195.50], EntityFallingBlock['Falling Block'/1374, l='MpServer', x=98.50, y=54.18, z=135.50], EntityCreeper['Creeper'/2399, l='MpServer', x=252.50, y=19.00, z=90.50], EntityZombie['Zombie'/2400, l='MpServer', x=228.50, y=25.00, z=69.50], EntityFallingBlock['Falling Block'/1889, l='MpServer', x=122.50, y=24.70, z=-0.50], EntityFallingBlock['Falling Block'/2401, l='MpServer', x=157.50, y=26.98, z=122.50], EntityFallingBlock['Falling Block'/1890, l='MpServer', x=121.50, y=25.70, z=0.50], EntityFallingBlock['Falling Block'/2402, l='MpServer', x=158.50, y=26.98, z=123.50], EntityZombie['Zombie'/1893, l='MpServer', x=157.50, y=23.00, z=134.50], EntitySkeleton['Skeleton'/1894, l='MpServer', x=186.50, y=33.00, z=186.50], EntityEnderman['Enderman'/1392, l='MpServer', x=133.50, y=24.00, z=179.50], EntityFallingBlock['Falling Block'/1905, l='MpServer', x=135.50, y=20.12, z=98.50], EntityFallingBlock['Falling Block'/1906, l='MpServer', x=136.50, y=21.12, z=98.50], EntityFallingBlock['Falling Block'/1907, l='MpServer', x=136.50, y=21.12, z=99.50], EntityFallingBlock['Falling Block'/1908, l='MpServer', x=135.50, y=20.12, z=100.50], EntityFallingBlock['Falling Block'/1909, l='MpServer', x=134.50, y=20.12, z=100.50], EntityFallingBlock['Falling Block'/1910, l='MpServer', x=135.50, y=20.12, z=101.50], EntityFallingBlock['Falling Block'/1911, l='MpServer', x=136.50, y=20.12, z=101.50], EntityFallingBlock['Falling Block'/1912, l='MpServer', x=134.50, y=20.12, z=101.50], EntityFallingBlock['Falling Block'/1913, l='MpServer', x=134.50, y=20.12, z=102.50], EntityFallingBlock['Falling Block'/1914, l='MpServer', x=135.50, y=20.12, z=102.50], EntityFallingBlock['Falling Block'/1915, l='MpServer', x=136.50, y=20.12, z=102.50], EntityFallingBlock['Falling Block'/1916, l='MpServer', x=134.50, y=20.12, z=103.50], EntityFallingBlock['Falling Block'/1917, l='MpServer', x=133.50, y=19.12, z=100.50], EntityFallingBlock['Falling Block'/1918, l='MpServer', x=133.50, y=19.12, z=101.50], EntityFallingBlock['Falling Block'/1919, l='MpServer', x=133.50, y=19.12, z=102.50], EntityFallingBlock['Falling Block'/1920, l='MpServer', x=133.50, y=19.12, z=103.50], EntityFallingBlock['Falling Block'/1921, l='MpServer', x=133.50, y=19.12, z=104.50], EntityFallingBlock['Falling Block'/1922, l='MpServer', x=134.50, y=19.12, z=104.50], EntityFallingBlock['Falling Block'/1923, l='MpServer', x=135.50, y=20.12, z=103.50], EntityFallingBlock['Falling Block'/1924, l='MpServer', x=135.50, y=20.12, z=104.50], EntityFallingBlock['Falling Block'/1925, l='MpServer', x=136.50, y=20.12, z=103.50], EntityFallingBlock['Falling Block'/1926, l='MpServer', x=133.50, y=19.12, z=105.50], EntityFallingBlock['Falling Block'/1927, l='MpServer', x=134.50, y=19.12, z=105.50], EntityFallingBlock['Falling Block'/1928, l='MpServer', x=133.50, y=19.12, z=106.50], EntityFallingBlock['Falling Block'/2440, l='MpServer', x=154.50, y=25.02, z=175.50], EntityFallingBlock['Falling Block'/2441, l='MpServer', x=154.50, y=26.02, z=176.50], EntityFallingBlock['Falling Block'/2442, l='MpServer', x=155.50, y=26.02, z=176.50], EntityFallingBlock['Falling Block'/1931, l='MpServer', x=134.50, y=16.12, z=145.50], EntityFallingBlock['Falling Block'/2443, l='MpServer', x=152.50, y=25.02, z=176.50], EntityFallingBlock['Falling Block'/1932, l='MpServer', x=134.50, y=16.12, z=146.50], EntityFallingBlock['Falling Block'/2444, l='MpServer', x=153.50, y=25.02, z=174.50], EntityFallingBlock['Falling Block'/1933, l='MpServer', x=135.50, y=16.12, z=145.50], EntityFallingBlock['Falling Block'/2445, l='MpServer', x=153.50, y=26.02, z=175.50], EntityFallingBlock['Falling Block'/1934, l='MpServer', x=135.50, y=16.12, z=146.50], EntityFallingBlock['Falling Block'/2446, l='MpServer', x=153.50, y=26.02, z=176.50], EntityFallingBlock['Falling Block'/1935, l='MpServer', x=135.50, y=16.12, z=147.50], EntityFallingBlock['Falling Block'/2447, l='MpServer', x=153.50, y=26.02, z=177.50], EntityFallingBlock['Falling Block'/1936, l='MpServer', x=136.50, y=16.12, z=146.50], EntityFallingBlock['Falling Block'/2448, l='MpServer', x=152.50, y=25.02, z=174.50], EntityFallingBlock['Falling Block'/2449, l='MpServer', x=153.50, y=24.02, z=173.50], EntityFallingBlock['Falling Block'/2450, l='MpServer', x=152.50, y=25.02, z=173.50], EntityFallingBlock['Falling Block'/2451, l='MpServer', x=151.50, y=24.02, z=172.50], EntityFallingBlock['Falling Block'/2452, l='MpServer', x=151.50, y=24.02, z=173.50], EntityFallingBlock['Falling Block'/2453, l='MpServer', x=151.50, y=24.02, z=174.50], EntityFallingBlock['Falling Block'/2454, l='MpServer', x=152.50, y=24.02, z=172.50], EntityFallingBlock['Falling Block'/2455, l='MpServer', x=153.50, y=23.02, z=172.50], EntityFallingBlock['Falling Block'/2456, l='MpServer', x=152.50, y=23.02, z=171.50], EntityFallingBlock['Falling Block'/2457, l='MpServer', x=168.50, y=12.02, z=190.50], EntityFallingBlock['Falling Block'/2458, l='MpServer', x=168.50, y=13.02, z=191.50], EntityFallingBlock['Falling Block'/2459, l='MpServer', x=169.50, y=12.02, z=190.50], EntityFallingBlock['Falling Block'/2460, l='MpServer', x=169.50, y=14.02, z=191.50], EntityFallingBlock['Falling Block'/2461, l='MpServer', x=167.50, y=12.02, z=190.50], EntityFallingBlock['Falling Block'/2462, l='MpServer', x=167.50, y=13.02, z=191.50], EntityFallingBlock['Falling Block'/2463, l='MpServer', x=166.50, y=12.02, z=191.50], EntityFallingBlock['Falling Block'/2464, l='MpServer', x=165.50, y=13.02, z=190.50], EntityFallingBlock['Falling Block'/2465, l='MpServer', x=166.50, y=11.02, z=190.50], EntityFallingBlock['Falling Block'/2466, l='MpServer', x=166.50, y=13.02, z=192.50], EntityFallingBlock['Falling Block'/2467, l='MpServer', x=167.50, y=13.02, z=192.50], EntityFallingBlock['Falling Block'/2468, l='MpServer', x=164.50, y=13.02, z=189.50], EntityFallingBlock['Falling Block'/2469, l='MpServer', x=164.50, y=14.02, z=190.50], EntityFallingBlock['Falling Block'/2470, l='MpServer', x=163.50, y=13.02, z=188.50], EntityFallingBlock['Falling Block'/2471, l='MpServer', x=163.50, y=14.02, z=189.50], EntityFallingBlock['Falling Block'/2472, l='MpServer', x=162.50, y=13.02, z=187.50], EntityFallingBlock['Falling Block'/2473, l='MpServer', x=161.50, y=60.02, z=225.50], EntityFallingBlock['Falling Block'/2474, l='MpServer', x=161.50, y=60.02, z=226.50], EntityWitch['Witch'/433, l='MpServer', x=154.50, y=62.00, z=162.50], EntityZombie['Zombie'/1457, l='MpServer', x=252.50, y=22.00, z=190.50], EntityZombie['Zombie'/435, l='MpServer', x=120.50, y=46.00, z=163.50], EntitySkeleton['Skeleton'/436, l='MpServer', x=148.50, y=15.00, z=160.50], EntitySpider['Spider'/1974, l='MpServer', x=242.50, y=56.00, z=56.50], EntityBat['Bat'/449, l='MpServer', x=252.14, y=39.75, z=183.72], EntityFallingBlock['Falling Block'/1987, l='MpServer', x=134.50, y=12.55, z=155.50], EntityFallingBlock['Falling Block'/1988, l='MpServer', x=135.50, y=13.55, z=154.50], EntityFallingBlock['Falling Block'/1989, l='MpServer', x=133.50, y=12.55, z=155.50], EntityFallingBlock['Falling Block'/1990, l='MpServer', x=135.50, y=13.55, z=155.50], EntityFallingBlock['Falling Block'/1991, l='MpServer', x=132.50, y=12.55, z=155.50], EntityFallingBlock['Falling Block'/1992, l='MpServer', x=132.50, y=12.55, z=156.50], EntityFallingBlock['Falling Block'/1993, l='MpServer', x=133.50, y=12.55, z=156.50], EntityFallingBlock['Falling Block'/1994, l='MpServer', x=133.50, y=12.55, z=157.50], EntityFallingBlock['Falling Block'/1995, l='MpServer', x=134.50, y=13.55, z=156.50], EntityFallingBlock['Falling Block'/1996, l='MpServer', x=134.50, y=13.55, z=157.50], EntityCreeper['Creeper'/1485, l='MpServer', x=171.50, y=8.00, z=136.50], EntityFallingBlock['Falling Block'/1997, l='MpServer', x=135.50, y=13.55, z=157.50], EntityFallingBlock['Falling Block'/1998, l='MpServer', x=132.50, y=12.55, z=157.50], EntityFallingBlock['Falling Block'/1999, l='MpServer', x=133.50, y=12.55, z=158.50], EntityFallingBlock['Falling Block'/2000, l='MpServer', x=132.50, y=12.55, z=158.50], EntityFallingBlock['Falling Block'/2001, l='MpServer', x=133.50, y=12.55, z=159.50], EntityFallingBlock['Falling Block'/2002, l='MpServer', x=134.50, y=12.55, z=159.50], EntityFallingBlock['Falling Block'/2003, l='MpServer', x=134.50, y=13.55, z=158.50], EntityFallingBlock['Falling Block'/2007, l='MpServer', x=129.50, y=27.55, z=170.50], EntityFallingBlock['Falling Block'/2008, l='MpServer', x=129.50, y=27.55, z=171.50], EntityFallingBlock['Falling Block'/2010, l='MpServer', x=128.50, y=27.55, z=170.50], EntityZombie['Zombie'/500, l='MpServer', x=116.50, y=46.00, z=156.50], EntityCreeper['Creeper'/505, l='MpServer', x=245.50, y=56.00, z=158.50]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:409)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2647)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:395)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by AlgorithmX2** [comment]
Seems like a Forge / C&B Version Mismatch. However your log doesn't contain the version information.

So I cannot confirm this, I would suggest updating forge, and C&B to their latest versions along with other mods to make sure that everything is up to date.

**Comment by Rorombik** [comment]
I have same problem, crash when right-clicking in world
`+  at mod.chiselsandbits.events.EventPlayerInteract.interaction(EventPlayerInteract.java:20)`
[https://gist.github.com/Rorombik/2ecb766914f2a7b632d3a90ffe99f911](url) (line 425)

And when left-clicking with chisel in hand
`[12:04:41] [Client thread/ERROR] [FML/]: Exception caught during firing event net.minecraftforge.event.entity.player.PlayerInteractEvent$LeftClickBlock@5d11a7f8:
java.lang.NoSuchMethodError: net.minecraftforge.event.entity.player.PlayerInteractEvent.getAction()Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$Action;`
[https://gist.github.com/Rorombik/38a132c62fc7e7d1e325791737818296](url)

**Comment by StarkRG** [comment]
I'm getting the same with Foge 1841 which is the minimum required for JEI.

**Comment by AlgorithmX2** [comment]
Forge has made more breaking changes so I will need to release a new build.

**Comment by AlgorithmX2** [comment]
Ok, released a new build.
