### ISSUE TITLE
ChiselsAndBitsBakedQuad.pipe doesn't pipe texture

### ISSUE THREAD

**Issue by fhntv24** [ChiselsAndBits/Chisels-and-Bits#392]
I think title is self-explaining .
This will cause crashesh when using builders with pipe method.

Steps to reproduce:
1. Install TConstruct
2. Put chisel&bit's block into any "fancy" tables from TConstruct ( crafting station, etc )

For any bug reports please provide the following details as well,
* MC Version: 1.12.2
* C&B Version: Latest ( forked )
* Do You have Optifine: no

p.s. calling `consumer.setTexture( getSprite() );` seems to work, but I'm not an export in C&B code. At least it does show block on table.
Also I didn't check any other Quad's.

**Comment by AlgorithmX2** [comment]
I wasn't able to get it to crash, maybe they fixed it on their end.

But I did add the call as it is correct.
