### ISSUE TITLE
Possible cross-mod compat issue with foamfix and chisel and bits

### ISSUE THREAD

**Issue by Sunconure11** [ChiselsAndBits/Chisels-and-Bits#393]
Before continuing if you are reporting an issue, please ensure that all mods involved are updated to the latest version available, if your issue with with intermod compatibility such mixing C&B bits with other blocks make sure that MCMP is also updated.

For any bug reports please provide the following details as well,
* MC Version: 1.12.2
* C&B Version: 14.17
* Do You have Optifine: No

I appear to have stumbled upon a weird issue with Foamfix and Chisel and Bits that prevents me from starting up

https://paste.dimdev.org/upocinanoz.mccrash

**Comment by Sunconure11** [comment]
This appears to be some weird issue with base metals and/or it's dependency.

https://github.com/MinecraftModDevelopmentMods/BaseMetals

**Comment by Sunconure11** [comment]
Issue cleared itself. Not sure what happened.

**Comment by asiekierka** [comment]
Not a FoamFix bug, this code mimics vanilla

**Comment by AlgorithmX2** [comment]
To my knowledge this crash looks the same as the one that vanillafix was causing. Which has been since reportedly fixed.
