### ISSUE TITLE
Chisel bypasses world claims

### ISSUE THREAD

**Issue by olie304** [ChiselsAndBits/Chisels-and-Bits#394]
* MC Version: 1.12.2
* C&B Version: 14.6
* Do You have Optifine: No

The mod can bypass worldguard and faction claims on servers by not modifying the land, but allowing the user of the chisel to pick up the bits from that block indefinitely.

**Comment by AlgorithmX2** [comment]
Please try the version at the bottom of this issue, https://github.com/AlgorithmX2/Chisels-and-Bits/issues/390

I was going to release it but since you posted a new issue I want to confirm that it works in whatever your doing to rather then having to back track again.

**Comment by AlgorithmX2** [comment]
Have you had a chance to test the build to see if it resolves your issue?

**Comment by Foulest** [comment]
This STILL is an issue.

**Comment by Aeltumn** [comment]
Please create a new issue instead of trying to re-open a closed one.
