### ISSUE TITLE
Draw Mode Isn't Working

### ISSUE THREAD

**Issue by AnimalisticArts** [ChiselsAndBits/Chisels-and-Bits#396]
When I'm trying to use draw mode in my 1.12.2 minecraft world it doesn't work. When I try to break or place any bits with draw mode it makes the sort of breaking particles but never actually breaks the bits of the block or places them. I don't know why this is happening and it's quite annoying. Please help find a solution to this.

For any bug reports please provide the following details as well,
* MC Version: 1.12.2
* C&B Version: 14.17
* Do You have Optifine: yes

**Comment by AlgorithmX2** [comment]
I just tried on the 14.18, and it should be the same for 14.17, I did not see any issues with drawn region either chiseling, or placing bits. I tried creative mode and survival, both were working fine.

You might want to check any other mods you have installed. Its possible that one of them is some how conflicting with C&B's operation.

**Comment by Naxelaboi** [comment]
I have this problem too, and if so what mods are possibly conflicting with C&B?
![image](https://user-images.githubusercontent.com/51536371/69006591-5efe6800-0931-11ea-9823-4ca14136d795.png)
Are any of these mods the problem?

**Comment by Aeltumn** [comment]
> 
> 
> I have this problem too, and if so what mods are possibly conflicting with C&B?
> Are any of these mods the problem?

The best way to find it is to remove a few mods, test if the problem persists, if the problem persists: re-add the mods and remove another few mods until you've tried removing all mods. If the problem is gone, try readding the removed mods one by one to find out which one causes the problem.
