### ISSUE TITLE
I keep crashing while breaking the chisel and bits block

### ISSUE THREAD

**Issue by WolfieeGaming** [ChiselsAndBits/Chisels-and-Bits#398]
Before continuing if you are reporting an issue, please ensure that all mods involved are updated to the latest version available, if your issue with with intermod compatibility such mixing C&B bits with other blocks make sure that MCMP is also updated.

For any bug reports please provide the following details as well,
* MC Version: 1.10.2-12.18.3.2185
* C&B Version: ChiselandBits-12.18.jar
* Do You have Optifine: yes

**Comment by AlgorithmX2** [comment]
You'll need to provide a crash log, without it I can't see what caused the crash.

**Comment by WolfieeGaming** [comment]
[crash-2018-06-22_20.19.59-client.txt](https://github.com/AlgorithmX2/Chisels-and-Bits/files/2129468/crash-2018-06-22_20.19.59-client.txt)

**Comment by AlgorithmX2** [comment]
You may want to try deleteing "chiselsandbits_clipboard.cfg" in your config folder.

And see if that fixes it, looking at the crash it looks like there might be something corrupt about it.

**Comment by WolfieeGaming** [comment]
i deleted it and it still is crashing

**Comment by AlgorithmX2** [comment]
Have you made changes to the default configuration settings? If your not sure you can just upload that as well and I can try it out.

**Comment by WolfieeGaming** [comment]
i havent done anything to the configuration settings

**Comment by AlgorithmX2** [comment]
https://www.dropbox.com/s/umdjayhwcgwp3fz/chiselsandbits-12.18.jar?dl=1 please post the crash log for this version, it should at least tell me which thing on that line is null so I can try and figure out why.

**Comment by WolfieeGaming** [comment]
OMG YAY ITS WORKING NOW

**Comment by AlgorithmX2** [comment]
what?

**Comment by AlgorithmX2** [comment]
I'm not entirely sure why the issue suddenly cleared up.. But I suppose I'm not entirely sure why there was an issue in the first place... yay?
