### ISSUE TITLE
Hide the cables Refined Storage

### ISSUE THREAD

**Issue by wandersonbrazdf** [ChiselsAndBits/Chisels-and-Bits#399]
Hello everyone, I would like to know how to hide the cables of the Refined storage I tried using the chisels & bits as I saw in some forums but I have experienced great difficulties I am putting 2 prints one of a video that I saw this being done and one of my map where I can not slip the cables.

https://imgur.com/a/z0o0r7k
...

Version (make sure you are on the latest version before reporting):
chiselsandbits-14.16
MCMultiPart-2.5.1
Minecraft 1.12.2 - MultiMC
refinedstorage-1.5.33
forge-1.12.2-14.23.3.2655-universal

**Comment by AlgorithmX2** [comment]
I'm not entirely sure what your asking.

I'm guessing that perhaps your asking why the cable isn't going though the bits? I think you need to open up a small hole in the middle for it to pass through.

**Comment by wandersonbrazdf** [comment]
Good night, creating a hole in the center would solve the problem, but you have a way to center it on the block.

It is when it needs to pass an importer such as a hole in the center it would solve already the importer and almost a whole block.

**Comment by AlgorithmX2** [comment]
Perhaps try this, https://gfycat.com/FarflungActualLaughingthrush
