### ISSUE TITLE
Compatibility with Quark's Cave Crystal blocks

### ISSUE THREAD

**Issue by st753m** [ChiselsAndBits/Chisels-and-Bits#400]
The colored cave crystal blocks from quark are really pretty and there are a number of ways I could think of using them in builds.  Unfortunately, they don't seem to be chisel and bits compatible.  I tried adding them to the "enabled blocks" section of the config, but it didn't work.  

They are full blocks, translucent, animated texture, no connected texture system.  

My attempt to add them to the config was to add to the "enabled blocks" list:

    B:vazkii.quark.world.block.BlockCrystal=true

Which appears to match what the other things in that list look like (I went into the quark jar and that seems to be where they're located).  When that produced no result, I attempted to add in:

    B:vazkii.quark.world.block.BlockCrystal$Variants=true

Which turned my previous config into a .errored file and generated a new one.

**Comment by AlgorithmX2** [comment]
The enabled blocks list is more for turning off blocks then it is for overwriting standard behavior. There are too many things that can go wrong to simply allow any block to be enabled, which many people would certainly try to do.

--

@Vazkii is there a chance you could add a call to send any translucent blocks over to C&B via 
FMLInterModComms.sendMessage( "chiselsandbits", "ignoreblocklogic", [myBlockName] ); ?

**Comment by Vazkii** [comment]
Mind opening an issue for it? I'll get to it when I'm back home.
