### ISSUE TITLE
Memory usage increases very quickly when looking at certain blocks while holding chisel

### ISSUE THREAD

**Issue by noob2star** [ChiselsAndBits/Chisels-and-Bits#401]
I have a strange issue where the memory usage shown in the F3 display ticks up at what looks like 1% every tick. This only occurs when I am **both** looking at one of the blocks that this affects **and** am holding a chisel or chiseled bit. The effect is much worse at my base, which is largely made of chiseled blocks, but it does happen in places with almost no chiseled blocks, except the rate is slower.

List of affected blocks:
* Chiseled bits
* Immersive Engineering blocks
* Vanilla wool (sometimes)
* Thermal Expansion pipe connectors (but **not** the center part of the block)
* Probably more

For any bug reports please provide the following details as well,
* MC Version: 1.12.2
* C&B Version: 14.17
* Do You have Optifine: Yes

**Comment by AlgorithmX2** [comment]
This is an interaction between MCMP and C&B.

I've worked around the code that creates the over abundance of objects, and hopefully that won't be an issue with MCMP moving forward.

You can test with this build, https://www.dropbox.com/s/991zq4jsury07jf/chiselsandbits-14.19.jar?dl=1

**Comment by AlgorithmX2** [comment]
Changes included in 14.19
