### ISSUE TITLE
Crash between Project E and Chisel and Bits

### ISSUE THREAD

**Issue by scalda** [ChiselsAndBits/Chisels-and-Bits#402]
Before continuing if you are reporting an issue, please ensure that all mods involved are updated to the latest version available, if your issue with with intermod compatibility such mixing C&B bits with other blocks make sure that MCMP is also updated.

Exact version (do not say "latest", "latest on Curse", or similar): 
ProjectE-1.12-PE1.3.1B
chiselsandbits-14.18
MCMultiPart-2.5.1

Exact Forge version:
forge-1.12.2-14.23.4.2705

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): 
https://pastebin.com/kkubZEaw

Steps to reproduce:

1. I am testing FC 1.4.3 and I am using both the latest files available to me as you can see above but on existing worlds, I am getting a server only crash whereas it works fine client side with an existing world

load an existing world with projectE and chisel and bits

What I expected to happen:
it to not crash on world load

What happened instead:

the server crashes with the report above

I am also reporting this to the Project e team https://github.com/sinkillerj/ProjectE/issues/1719

**Comment by AlgorithmX2** [comment]
It looks like initial EMC Calculations, and Initial Bit Determination are compounding when your server is loading

You can adjust this with max-tick-time inside of server.properties, apparently -1 disables it entirely.

**Comment by scalda** [comment]
That worked great thank you for the suggestion i have also added this solution to my changelog for the pack so people can do it on their servers aswell.

thanks again
