### ISSUE TITLE
Does C&B say if a block is an air block or not?

### ISSUE THREAD

**Issue by ShaneCourtrille** [ChiselsAndBits/Chisels-and-Bits#404]
MC Version: 1.12.2
C&B Version: chiselsandbits-14.18.jar

I've ran into an odd compatibility problem with OpenBlocks Elevators where if I have a single strip of C&B in the air block above the elevator it works fine but as soon as there are two strips making an L shape in the corner of the block I can't use them anymore.

This got me wondering if there is a threshold for number of bits that C&B uses to decide if the block should be treated as an air block vs not.. and more importantly is there a way to tell C&B that a block I've created should be treated as an air block even if it's past the threshold?

Thanks

**Comment by AlgorithmX2** [comment]
C&B cannot declare itself as an air-block,  Air blocks are treated very differently then physical blocks, allowing things like water to replace them, blocks to fall through them and other things.

OpenBlocks might be checking collision boxes or something, I honestly don't know, but C&B never will or can describe itself as Air.
