### ISSUE TITLE
Having an issue with glowstone.

### ISSUE THREAD

**Issue by Rhea** [ChiselsAndBits/Chisels-and-Bits#405]
bitLightPercentage is set to 0 (I've also tried 1), and the light level is still only scaling with what I assume are the default levels. 

* MC Version: 1.12.2
* C&B Version: 14.17
* Do You have Optifine: y

**Comment by Rhea** [comment]
Correction: It just seems to be that they don't produce full light unless you close the world and re-enter it, (or disconnect and reconnect to the server)

**Comment by AlgorithmX2** [comment]
https://gfycat.com/PassionateCheapCanvasback

I am not seeing what you are describing. It seems to continuously update the lighting as I work with the block. Not pictured in the video is me starting with a full block and working my way down, but it did work. I also tested with bitLightPercentage 0 to ensure that its not something wrong with the setting, when I tested it; it correctly reached full brightness with a single bit.

You may need to see if other mods you have installed are conflicting with it some how.
