### ISSUE TITLE
[Suggestion] Workbench for prebuilding blocks

### ISSUE THREAD

**Issue by ghost** [ChiselsAndBits/Chisels-and-Bits#406]
I would like to be able to provide materials and a blueprint and remove ready made copies of blocks that could then be placed. It's much more convenient than chopping up blocks on the go, especially when you need a lot of something. Perhaps have a variable design stencil that can take a chiseled block with up to 4 materials and players could place blocks in 4 slots to be used for the design. (Platforms does something sort of like that.)

Ideally, the bench would come with some premade stencils for some basic shapes, pillars, stairs, railings and the like (see ArchitectureCraft or Platforms), maybe even placed in the config so it could be customized by server theme.

Double bonus if there's a multi-block assist feature. i.e., I choose dome and set the diameter to 2 and the height to 3 and I can extract 12 blocks that can be assembled into the dome (or whatever basic shape).

I think something like this could close a number of open issues. Thanks for the fun.

**Comment by AlgorithmX2** [comment]
I'm not sure how this would be better then just using positive patterns in placement mode. If you really want to make a bunch of blocks at once you could also craft a pattern with a bag full of bits to make a bunch of blocks ahead of time.

As far as multi-block assist, if your making a dome or something you might want to checkout Extra Bit Manipulation, its an add on with some fancy tools for making big shapes and other things.

**Comment by ghost** [comment]
I wasn't aware you could craft a pattern with a bit bag to create blocks directly. I'll have to try it.

I'm playing with ArchitectureCraft this run, but last time I used C&B and I chopped up a pile of bricks and applied patterns and there were bits flying everywhere...

**Comment by AlgorithmX2** [comment]
Well, you can always carry a few extra bit bags around, or if they are too small for you you can increase their bit stack-size in the config.

Also, You can use the patterns in placement mode, rather then cutting up the blocks on the ground you can build new blocks from the bits in your bags already.

**Comment by ghost** [comment]
Ok, either I missed something or you added features when my back was turned. Now I have to start a new world with C&B!

**Comment by AlgorithmX2** [comment]
There is a lot of stuff in C&B, and I've not been able to work on it much, so its probably just features hiding in the shadows.

**Comment by ghost** [comment]
Great. Thanks.
