### ISSUE TITLE
Can't chisel Mycelium

### ISSUE THREAD

**Issue by Gamer025** [ChiselsAndBits/Chisels-and-Bits#407]
Chisel and Bits isn't able to chisel Mycelium. Neither the bit saw (no crafting recipe) works nor the diamond chisel (doesn't remove anything from the block).

For any bug reports please provide the following details as well,
* MC Version: 1.12.2
* C&B Version: 14.18
* Do You have Optifine: No

**Comment by AlgorithmX2** [comment]
Added in 14.19
