### ISSUE TITLE
1.13 Port

### ISSUE THREAD

**Issue by AlgorithmX2** [ChiselsAndBits/Chisels-and-Bits#408]
Porting to 1.13 will likely happen once forge 1.13 is stable/recommended.

However I can't say anything regarding the process until there are working 1.13 builds of forge to use.

**Comment by yll1s** [comment]
> Porting to 1.13 will likely happen once forge 1.13 is stable/recommended.
> 
> However I can't say anything regarding the process until there are working 1.13 builds of forge to use.

Now, there are a forge 1.13.2. How about porting?

**Comment by AlgorithmX2** [comment]
As indicated I plan on finishing the process when its stable, I may or may not find time prior to that to work on the project, but I don't really plan on releasing it until there is a stable release. I've been doing some research with FCB for instance, but that is just that preliminary research into the porting process.

I've had issues releasing against alpha/beta versions before, and would like to avoid that this time around. Especially with time so limited.

**Comment by loordgek** [comment]
1.13.2 never gets a RD build
rename this to "1.14 Port"
