### ISSUE TITLE
Chiseling Galacticraft blocks crashes game in SevTech

### ISSUE THREAD

**Issue by wiblu** [ChiselsAndBits/Chisels-and-Bits#409]
I've had an issue in the sevtech modpack using chisel and bits on galacticraft blocks (mercury stone, moon turf, mars cobblestone are all i've tested) are you able to have a look at the crash report to see if there is an issue with it in the pack.
Here is the crash report: https://pastebin.com/HBzA0Ttj
and here is link to SevTech Issue page: https://github.com/DarkPacks/SevTech-Ages/issues/3129
@MJRLedgends is happy to work with you if ther issue is their side

**Comment by AlgorithmX2** [comment]
This seems more of a conflict between Primal Core and C&B.

Thought it seems to be my fault. You can turn off "enableToolHarvestLevels" in the c&b settings to work around the issue for time being.

**Comment by AlgorithmX2** [comment]
Please try https://www.dropbox.com/s/991zq4jsury07jf/chiselsandbits-14.19.jar?dl=1 and see if that fixes the issue.

**Comment by wiblu** [comment]
The newer version solved this crash 
thank you

**Comment by AlgorithmX2** [comment]
I've pushed 14.20 which will contain the fix to curse forge.
