### ISSUE TITLE
[Render Glitch] Tape Measure

### ISSUE THREAD

**Issue by SirFlip** [ChiselsAndBits/Chisels-and-Bits#412]
I noticed it with Direwolf20s Building Gadget Mod
Normal:
![2018-08-01_00 26 47](https://user-images.githubusercontent.com/6735323/43490650-cc8db004-9521-11e8-83ed-a289ec06b877.png)
With Building Gadget in Hand:
![2018-08-01_00 26 50](https://user-images.githubusercontent.com/6735323/43490643-c6d35d3a-9521-11e8-9f20-ce9b7c57afe5.png)

* MC Version: 1.12.2
* C&B Version: 14.20
* Do You have Optifine: no

**Comment by RelicFades** [comment]
On ATM8 1.0.21b with this issue. What mod is causing this issue?
