### ISSUE TITLE
Replace function not working in new update.

### ISSUE THREAD

**Issue by MunchNStuff** [ChiselsAndBits/Chisels-and-Bits#417]
C&B and MCMP has been updated. Issue is not a crash.
* MC Version: 1.12.2
* C&B Version: 14.20 MCMP 2.5.1
* Do You have Optifine: NO

"Replace" bit function not working. Button toggles on ALT GUI but does nothing in game.

**Comment by AlgorithmX2** [comment]
It seems to be working fine for me, switching to replace mode is allowing me to replace bits that are already in place, and removes the bits that were in their place.

**Comment by MunchNStuff** [comment]
Still having this issue with Chisel Marble block. There is also a color issue with the lighting. Ref screeenie.
![image](https://user-images.githubusercontent.com/39834225/44059652-211f05e8-9f20-11e8-9ce4-11d3331122c1.png)

**Comment by MunchNStuff** [comment]
I made a video so you can see the issues but do not know how to send or share it with you. please let me know how I can send it to you.

**Comment by AlgorithmX2** [comment]
if its a video you can upload it to youtube and send me the link to it, or another service like dropbox or onedrive would work as well. I'm not sure what you have access too.

**Comment by AlgorithmX2** [comment]
I was able to reproduce the replacing issue when I tried a chisel block as indicated. Not sure about the lighting issue however my block looks normal.

**Comment by AlgorithmX2** [comment]
Try https://www.dropbox.com/s/g1o0h7lk25ymsh1/chiselsandbits-14.21.jar?dl=1 and see if it fixes your replacement issue.

**Comment by ResqDiver1317** [comment]
Dang, I should have looked at this issue before I rolled back the CandB version this morning (I'm the admin on the server Munch plays on). I just rolled us back to 14.17 to get it working right for now, but I will update this evening to the 14.21 version so Munch can test it out and see if that fixed it.

**Comment by AlgorithmX2** [comment]
Can anyone confirm that this issue is fixed?
