### ISSUE TITLE
Chiseled Bit Bag causing performance issues

### ISSUE THREAD

**Issue by Sir-Will** [ChiselsAndBits/Chisels-and-Bits#419]
Only one player used a Chiseled Bit Bag with chiseled marble pieces and it caused huge performance issues for some reason:
![](https://i.imgur.com/MUm4FgY.jpg)
![](https://i.imgur.com/CBUqzEf.jpg)

chiselsandbits-14.18
forge-1.12.2-14.23.4.2705-universal

**Comment by Sir-Will** [comment]
Update: The player had 5 bags and all of them had this content: ![](https://i.imgur.com/RbEbk2R.png), once the player started placing them the issue started.

**Comment by AlgorithmX2** [comment]
Seems rather strange that forge capabilities are so heavy hitting on bits which don't have a capability... I'll need to do some testing on my end, it seems likely that I'll have to rethink how that logic works.

**Comment by Sir-Will** [comment]
I noticed in the past months that multiple other mods are having performance issues with forge capabilities.

**Comment by AlgorithmX2** [comment]
Should be fixed in 14.21, thanks for the profiles and tracking down the source, made it super easy to reproduce and fix it.

**Comment by Sir-Will** [comment]
Thanks!
