### ISSUE TITLE
[1.9] Client Crash

### ISSUE THREAD

**Issue by squirrelkiller** [ChiselsAndBits/Chisels-and-Bits#42]
So I reported this to Optifine, because blame optifine when I see a render issue, but they believed it might actually be related to you. All relevant information is in it, and naturally I want to ensure that you have the same information in your report as I gave them to maintain a completely neutral stance to ensure that it is properly fixed.

Here is a copy paste of my post to Optifine: [(link to the post)](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1272953-optifine-hd-b1-fps-boost-hd-textures-shaders-and?comment=51105)

> I might as well report this, even if it has before I can offer probably a better understanding of what happened than most people have.
> 
> Minecraft Version: 1.9
> Forge Version: 1.9 - 12.16.0.1863
> Optifine Version: OptiFine 1.9.0 HD U B1
> Other mods: This mod pack "Episode 1 Edition" http://minecraft.curseforge.com/projects/sk-lets-play-season-1-pack
> Crash-log: http://pastebin.com/344qy24w
> What was I doing when everything broke: https://youtu.be/E4crQMm4vng
> 
> Additional Notes: I notice reviewing the video I was recording at the time to extract the portion where it crashed so I could show rather than tell the normally outlined regions when using the chisel or trying to work with bits was not present, because of this I think it is an interaction issue between you and Chisel & Bits, and because the crash-log referenced rendering, well "Blame Optifine", since in my experience that is a safe call when you see rendering issues when optifine installed.
> 
> The crash was caused when I was clicking and dragging for "Drawn Region" construction. This normally renders the area that will be filled upon releasing the right mouse button as you move the mouse to select the area, but in this case there was simply a crash and everything broke down as you saw in the short video I included above.

And the response from them: [(and a link to that post)](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1272953-optifine-hd-b1-fps-boost-hd-textures-shaders-and?comment=51106)

> Most probably "iblockstate.getCollisionBoundingBox()" returned NULL.
> When painting the selected block outlines, the mod block returned that it has no bounding box, which should never happen.
> This is a mod problem.

**Comment by AlgorithmX2** [comment]
sp614x is correct, this was changed from 1.8 to 1.9, that method can no longer return null.

I wasn't able to reproduce your crash in my testing, however the fact remains that if a certain set of criteria was met I was returning null.

So I've resolved this and the method should no longer be able to do so, so if it was C&B like we suspect this should resolve the crash.

Fixed in 9.14
