### ISSUE TITLE
Certain blocks act like fluids when chiselled

### ISSUE THREAD

**Issue by FallenEagle1** [ChiselsAndBits/Chisels-and-Bits#423]
* MC Version: 1.12.2
* Forge Version: 14.23.4.2756. 14.23.4.2715 as well
* C&B Version: 14.21
* Flat Colored Blocks Version: 6.6
* Do You have Optifine: Yes, but tested without as well
* Modpack: ATM 3 5.9.8d but most testing done lately on ATM3 6.0 ptr2

This originally was thought to be an issue with the mod Plants, and had been reported to them. Came to my attention that a user of the ATM3 pack had this happen with blocks from Flat Colored Blocks (FCB) as well.

Basically, these blocks are solid like expected, but when they are chiselled, they act like fluid blocks; you can walk through them and they give the water particle splash affect on your screen. Can also swim up them. These blocks also can not be directly interacted with if you try breaking them. You will just break the block behind it that you are looking at.
![image](https://user-images.githubusercontent.com/22630113/44491514-bf173900-a61e-11e8-8805-090224a0548c.png)

Did some testing with this to see if it was reproducible, and it is with certain blocks from FCB. This was done in single player, whereas the issue seen with Plants was only able to be done on a server.
![image](https://user-images.githubusercontent.com/22630113/44491180-a6f2ea00-a61d-11e8-8ba8-0c6439b82620.png)
These were acting like water when chiselled.

![image](https://user-images.githubusercontent.com/22630113/44491208-bc681400-a61d-11e8-8747-765e21f16fee.png)
These were not.

Thought at first it may be related to the nbt somehow, but it doesn't seem like they are. the nbt numbers of those in the chest overlap some. I can grab that info if you want, but not sure what info you may want with it.

AllTheMods/ATM-3#693
Shadows-of-Fire/Plants#88

**Comment by AlgorithmX2** [comment]
I looked into this a bit closer, and I think I might see an issue.

Try, https://www.dropbox.com/s/g1o0h7lk25ymsh1/chiselsandbits-14.21.jar?dl=1 and see if it helps.

**Comment by FallenEagle1** [comment]
Tried booting up with that, and making a new world and same issues. The existing world still had the same as well. I did a little more testing with flat colored blocks, and here is the result 
![image](https://user-images.githubusercontent.com/22630113/44500114-36ab8f00-a644-11e8-91a2-15c73dffbda5.png)

Used pink because I knew a number of them didn't work. The ones with cobblestone on top functioned as expected, the others have the fluid like property. The blocks are lined out just as you would find them in the colored block crafter.

**Comment by AlgorithmX2** [comment]
I don't think it really has anything to do with he blocks really, which is why FCB for instance which is really 3 type of block has such strange results, I think its related to the ID's they are given in the instance and or world.

https://www.dropbox.com/s/wi6seuaitpensn5/chiselsandbits-14.21x.jar?dl=1

A bit more digging and I spotted something else that might be related, if you want to give this build a try and let me know if it helps.

**Comment by FallenEagle1** [comment]
That last one worked. The blocks are back as solid now.

**Comment by AlgorithmX2** [comment]
Thanks for confirming, the fix should be available on curse shortly.
