### ISSUE TITLE
Spruce wood planks not working?!

### ISSUE THREAD

**Issue by romeospoke22** [ChiselsAndBits/Chisels-and-Bits#427]
* MC Version: 1.12.2
* C&B Version: latest
* Do You have Optifine: yes

hi there recently i realized that my spruce wood planks are turning into another block when chiseled, i recently updated CTM mod and Chisel and bits, i didnt chisel any spruce wood prior to the update so i cant tell if it was the update. i changed chisels versions but that didnt help, i upgraded CTM to reduce rendering crash and to make immersive engineering steel scaffolds show up. 

![2018-08-26_16 27 34](https://user-images.githubusercontent.com/42714074/44629909-eedf7d00-a94d-11e8-942d-7b4f39fb63b0.png)

spruce wood is not the only block, it also seems dorite (non chiseled ) does the same.

**Comment by AlgorithmX2** [comment]
Your sure your on the latest build of C&B? It seems to be working for me, and I think something regarding this changed recently.

![image](https://user-images.githubusercontent.com/2846930/44632886-601c3180-a948-11e8-9701-e75f77d5780c.png)

**Comment by romeospoke22** [comment]
im using           
C&B: 14.23
code chicken library: 3.2.1.351
chisel:  mc.1.12.2-0.2.0.31
CTM:   mc.1.12.2-0.3.2.18

optifine : 1.12.2_HD_U_E2
Forge: 14.23.4.2738
in case it may help, when on chisel, my spruce wood planks are called spruce wood planks on @minecraft but chisel says spruce planks @chiseled. still have the problem, not sure what it could be.

**Comment by AlgorithmX2** [comment]
Unfortunately none of that helps, I am able to chisel vanilla diorite, and spruce planks. As well as the chisel variants of said blocks.

There might be another mod interfering with C&B's auto detection or similar. It would be hard to say why however. You might want to check to see if there is anything in your logs, or try removing some mods and see if the situation improves.
