### ISSUE TITLE
[Request] Ambient Occlusion

### ISSUE THREAD

**Issue by yll1s** [ChiselsAndBits/Chisels-and-Bits#434]
Please, add Ambient Occlusion support for C&B creations. Without AO, C&B creations too strongly stand out from the rest of the blocks that support AO. I don't have an idea how to make this, but I hope it's possible.

**Comment by AlgorithmX2** [comment]
C&B uses the same AO as MC ( which is block wide AO ) So i'm not sure what you mean by it stands out from the rest, they should look more or less the same as all other MC Blocks.

**Comment by Phylogeny** [comment]
He's referring to the fact that, although chiseled blocks allow adjacent blocks to occluded the lighting they render with, chiseled blocks don't occlude the light of adjacent blocks. You would have to override `Block#getAmbientOcclusionLightValue(IBlockState)` or `IBlockProperties#getAmbientOcclusionLightValue` for that to work.

It's the exact same thing with `Block#getUseNeighborBrightness(IBlockState)` and `IBlockProperties#useNeighborBrightness` that I mentioned here:
https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/2576750-chisels-bits-flat-colored-blocks?page=28#c551

I trust that everything you said in your response to that still holds.

**Comment by AlgorithmX2** [comment]
Ahh, It should I imagine, though I haven't looked at it in some time. Same reason why blocks like stairs, fences and the like behave as they do. Because blocking light causes the behavior I described in the thread.

**Comment by yll1s** [comment]
> 
> 
> C&B uses the same AO as MC ( which is block wide AO ) So I'm not sure what you mean by it stands out from the rest, they should look more or less the same as all other MC Blocks.

The absence of AO in C&B is clearly seen if you remove one bit from the block.

Default block, with AO: 
![2018-09-20_00 14 38](https://user-images.githubusercontent.com/43315029/45769575-3f56ab80-bc6a-11e8-8b62-b8eb77be8823.png)

Chiseled block, without AO:
![2018-09-20_00 14 47](https://user-images.githubusercontent.com/43315029/45769608-572e2f80-bc6a-11e8-85dc-a4d2ac3393a2.png)

**Comment by Phylogeny** [comment]
@ErMANWood Read the comments by Algo and myself, above (as well as the posts by both of us in the thread I linked). It's clear that the issue is already understood, and that what you're asking for will not be implemented.

**Comment by yll1s** [comment]
Ok, thanks.
