### ISSUE TITLE
Question abot Minecraft: Windows 10 Edition

### ISSUE THREAD

**Issue by ErMANGaming** [ChiselsAndBits/Chisels-and-Bits#437]
I have a question - is there is a way to port this mod to Minecraft Windows 10 Edition? I don't very good in mod making so I don't know how it should be.

**Comment by AlgorithmX2** [comment]
As I understand it "mods" or addons for Windows 10 are little more then special files that can tweak certain things.

No real coding can be done, and C&B is a considerable amount of extra code. So its very doubtful that will ever happen. Even if they provided a full API, I'm not sure that I would have the time to re-write the whole thing for another version.
