### ISSUE TITLE
Severe Crash Report

### ISSUE THREAD

**Issue by RyanSquaredYT** [ChiselsAndBits/Chisels-and-Bits#438]
The Minecraft Launcher will load until it gets to chisels & bits. It crashed on the spot. I have version 14.25, the most current. Help please!

https://pastebin.com/JFymKPQ5

**Comment by AlgorithmX2** [comment]
Looks like I used the wrong method for an error log, but you can probably fix the issue by updating Little Tiles as well.

**Comment by AlgorithmX2** [comment]
Fixed in 14.26

**Comment by RyanSquaredYT** [comment]
Thanks alot! I updated to 14.26 and got rid of LittleTiles! 

Very much appreciate the support!
