### ISSUE TITLE
[Annoying Bug] Lighting Rendering Incorrectly

### ISSUE THREAD

**Issue by mrwallace888** [ChiselsAndBits/Chisels-and-Bits#439]
Okay... so I have this strange issue, I don't think anyone else might've had this before because I think I might be the only one that wants to do something like the thing I've done. I love making houses. I like making it so that there's an exterior wall (like wood) and then an interior wall (concrete) for the rooms. I figured I could do this by making mixed-blocks, like having a block that's wood on the outside and concrete on the inside. I used MalisisBlocks before but there's a few bugs with that (like shaders make mixed blocks transparent, for example). Anyways... so I noticed a strange lighting bug. If I were to build my house like normal, then reload the world or fly away until the chunk despawns and then come back (because doing A + F3 chunk reloading doesn't really do anything for this), the lighting seems okay. But once I place a block down or anything like that (or if I were to place a glowstone and remove it), the lighting gets all buggy and it stays like that till I reload or fly away and come back. Is there a way to fix this? I have Optifine and no other mods other than this (and of course, it's requirements/recommendations). Everything's up-to-date. And for some reason this lighting issue happens with it. Is there a fix per chance? Can it at least be patched or something? Here's some screenshots. For this example, I made it night and placed a block on the floor and broke it.
![2018-10-13_01 36 24](https://user-images.githubusercontent.com/39398330/46902339-7c891480-ce89-11e8-94ac-2fa44d972261.png)
![2018-10-13_01 36 30](https://user-images.githubusercontent.com/39398330/46902340-7c891480-ce89-11e8-8f79-ab96a1fb62dd.png)
![2018-10-13_01 36 34](https://user-images.githubusercontent.com/39398330/46902341-7c891480-ce89-11e8-9a38-a04a4c2f0280.png)

**Comment by mrwallace888** [comment]
Oh, and I have JourneyMap, but that's just clientside.

**Comment by AlgorithmX2** [comment]
I found an issue where lighting calculates different on load from post load, please try https://www.dropbox.com/s/aesczx4lm4xji51/chiselsandbits-14.27.jar?dl=1

**Comment by mrwallace888** [comment]
Okay. If it doesn't fix it I'll let ya know.

**Comment by mrwallace888** [comment]
It works. Thanks so much. Now I can resume my housebuilding!

**Comment by TheSnowyChickens** [comment]
Lul, I found this type of bug today on a Server (with a chiseled terracotta mix) and now its fixed. xD

Ty
