### ISSUE TITLE
Crash on trying to chiselate Extra Utils' compressed cobble.

### ISSUE THREAD

**Issue by MysteriousAges** [ChiselsAndBits/Chisels-and-Bits#44]
Client crashes on trying to chisel  XU's compressed cobble on a server: https://gist.github.com/anonymous/7262c9b564d4a32f22b39cfab235d77c

Attempting to immediately rejoin results in the same crash. Joining after a few minutes seems to be fine.

**Comment by AlgorithmX2** [comment]
Was this fixed by the way?

**Comment by AlgorithmX2** [comment]
Probably Fixed?
