### ISSUE TITLE
Request : Cannot SAW Forestry Leaves

### ISSUE THREAD

**Issue by HaniXP** [ChiselsAndBits/Chisels-and-Bits#440]
* MC Version: 1.12.2
* C&B Version: 14.26
* Do You have Optifine: Yes
================================

As said in the title, is it possible to update chisel and bits and also add compatibility with Forestry's Leaves?

Because i can chop or slice down forestry blocks with saw but except their leaves which is the only thing that's missing in chisel-bits.

**Comment by AlgorithmX2** [comment]
I'm fairly certain that forestry leaves are tile entities, and they cannot be chiseled. This is because they contain genetic information about the trees.

**Comment by AlgorithmX2** [comment]
https://github.com/ForestryMC/ForestryMC/blob/b92a1a10e96b216e8eb72cc0ee2a61a2065bc486/src/main/java/forestry/arboriculture/blocks/BlockForestryLeaves.java#L129
Confirmed, chiseling a leaves block from forestry would likely result in white leaves or something similar, making the feature broken.
