### ISSUE TITLE
Bits glitching out/invisible

### ISSUE THREAD

**Issue by HaniXP** [ChiselsAndBits/Chisels-and-Bits#441]
I made a long tiny block and placed on top right of the stone block.. and then i broke it with atomic disassembler, now the block didnt broke and its invisible and i am glitching out everytime i pass through it, and i cant literally find any way except using world edit to delete that invisible block completely , will there be a solution or a future update to fix this or i assume it's mekanism's problem and not to use the atomic thing?

EDIT : Nope, i dont think it is mekanism's problem, i also tried using a silktouch diamond pickaxe and repeated the same method.. it went invisible again and glitching out

Video : -

https://www.dropbox.com/s/r8peor0yu3njjmk/2018-11-02_10-26-46.mp4?dl=0

=========================================
I have also 2 other things to say uhm,

Many people told me Mekanism is compatible with C&B, So that i can create facades for mekanism pipes using C&B.. is that true? ive tried putting a single bit next to the pipe and its not even working.. like c&b and mekanism pipes just dont connect to each other.. which means i have to place the bits 1 block away from the pipe.. that wont even look good for a facade tho.

& Also what's your thought on this ? 

![sdr](https://user-images.githubusercontent.com/23115604/47899977-60770280-de8c-11e8-8fca-768794cb98fd.JPG)

=====================================

Solutions or any answer is appreciated.

For any bug reports please provide the following details as well,
* MC Version: 1.12.2
* C&B Version: 14.26
* Do You have Optifine: Yes

**Comment by AlgorithmX2** [comment]
1. So any chiseled block you break with the atomic disassembler becomes like this? What about with a pick axe?

2. Do you have MC Multipart installed? I believe it supports the mod, and C&B does as well, giving a layer of compatibility.

3. The question of chisel, or CTM support for C&B has come up several times, and to my knowledge several people have tried it, I've even looked into it. I think that at this point its just too complicated for C&B, since the idea of "connected bits" and "connected blocks" are not equivalent. You can get lost in the details of how it might work, or could work. But from what I can tell, there's not really any good answers.

**Comment by HaniXP** [comment]
1. Ive tried with a pickaxe as ive told on my 2nd line of statement.. same problem tho

2. I had MC Multipart installed but i removed it because i was thinking that i no longer need it anymore since i have C&B.. just to save some space in the mods file for my modpack.

3. Understood.

**Comment by AlgorithmX2** [comment]
1. So if I understand this correctly, it has to do with silk touch? I misunderstood your edit the first time I read it.

2. MCMulltipart is the mod that provides the functionality, Meckanism and C&B have no support to one another, but by both supporting MCMultipart it enables them to share the same block space. If your wanting to use that then re-installing it should do the trick.

**Comment by HaniXP** [comment]
Thanks for the info, yeah it was just a diamond pickaxe with silktouch in it.. i will just see if i can provide a proper & clear detailed information about the invisible glitch part sooner or later when i encounter it again. :+1:

**Comment by AlgorithmX2** [comment]
For the record, I tried with the silktouch pickaxe, and the atomic disassembler. I wasn't able to reproduce your issue however, the chiseled blocks break as expected and I can pick them up, and stuff.

I'd recommend checking your logs, its possible something else is causing issues, maybe crashing during the block breaking process in an event or something.
