### ISSUE TITLE
Patchouli books get Chiseled Fluid Bit tank model

### ISSUE THREAD

**Issue by stanhebben** [ChiselsAndBits/Chisels-and-Bits#443]
* MC Version: 1.12.2
* C&B Version: 14.27
* No Optifine

When running a modded setup with both Chisels & Bits and Patchouli present, the Patchouli books get the model of a Chiseled Fluid Bit tank. This model appears both in the player's inventory, JEI and the creative menu.

Considering only Chisels & Bits have this issue out of 180+ mods tested, we assume this is an issue from the Chisels & Bits side. This issue is easily reproducible with a setup containing only Chisels & Bits, Patchouli and JEI.

Patchouli is a mod by Vazkii allowing in-game documentation books to be written using JSON files. It is not yet publicly available, but access will be granted to both the mod and the source code. Some example books can be found here: http://stanhebben.net/download/patchouli_books.zip

**Comment by Vazkii** [comment]
I've added you to the private repository at https://github.com/Vazkii/Patchouli/ should you wish to check for yourself what's going on there. If you'd rather get a pre-compiled jar just come on my discord and I'll gladly get you in the testers room.

**Comment by AlgorithmX2** [comment]
Seems that we are both ending up calling ModelLoader.setCustomMeshDefinition( Item, ItemMeshDefinition ); before the item delegates have names.

This means that both are null, so they overlap.

In my case my ItemBlock's delegate never seems to be populated, even though I wait to register the mesh, in your case I think your just doing it early.

I managed to solve my issue by using a different method that doesn't resolve the delegate until later. And while I can see the books after that, I think its only a matter of time before someone else makes a similar mistake.

**Comment by Vazkii** [comment]
I guess I would need to do the same thing on my end then. I'll look into it.

**Comment by Vazkii** [comment]
Fixed by https://github.com/Vazkii/Patchouli/commit/4a176ab40ada6c6267684f67a04c023433e309c8

**Comment by AlgorithmX2** [comment]
Patched in new build.
