### ISSUE TITLE
Crash w/ Minecolonies Building Tool Preview

### ISSUE THREAD

**Issue by WenXin20** [ChiselsAndBits/Chisels-and-Bits#445]
Forge v1.12.2-14.23.4.2757
C&B v14.28
Minecolonies v0.10.48-ALPHA
Optifine vHD_U_E2

I recieve a crash with the minecolonies building tool if a custom schematic created with the scan tool contains chisel and bits. @Raycoms mentioned that it should use IBlockAccess instead of world in renderSpecific methods.

[Crash Report](https://paste.dimdev.org/kibayeduqo.mccrash)
More details at ldtteam/minecolonies#3093

**Comment by AlgorithmX2** [comment]
Please try this build, https://www.dropbox.com/s/z2kliwtcy7lkfjv/chiselsandbits-14.28.jar?dl=1

This is a bit of a mucked up situation because some mods are calling that method on the server and some are calling it on the client. I think this fixes the crash however.

**Comment by WenXin20** [comment]
Yes, that worked

**Comment by AlgorithmX2** [comment]
Thanks for confirming, I released a new build.
