### ISSUE TITLE
Is this correct or typo?

### ISSUE THREAD

**Issue by instinxx** [ChiselsAndBits/Chisels-and-Bits#446]
I found this in the config for 14.26:

SNIP...................................
troublershooting {
    B:disableCustomVertexFormats=false
    B:enableFaceLightmapExtraction=true
    B:useGetLightValue=true
}

troubleshooting {
    B:enableAPITestingItem=false
    B:logTileErrors=false

Was that a typo or do those two sections do different things?

Thanks!

For any bug reports please provide the following details as well,
* MC Version:
* C&B Version:
* Do You have Optifine:

**Comment by AlgorithmX2** [comment]
Yeah, looks like a typo put those options in two different categories instead of 1, thanks will be fixed in future releases.
