### ISSUE TITLE
[Enhancement] Bitbag: Blocks to Bits - Bits to Blocks

### ISSUE THREAD

**Issue by Sourceshard** [ChiselsAndBits/Chisels-and-Bits#447]
Would it be possible to Shift Click Full Blocks from your inventory into the bit bag while a Chisel is present in your inventory. Likewise Shift Click bits in your Bitbag to create new Full Blocks in your inventory. 

This would allow you to quickly and efficiently add a Palate of blocks to build with instead of placing them on the ground and breaking them down one by one. This would also create a quick option to recover full blocks from the bag to reuse elsewhere.

**Comment by AlgorithmX2** [comment]
I like the idea in theory, but for obvious reasons using shift clicking would cause issues, since it breaks the normal way inventories work, and would be very confusing to players expecting to shift click bits out of the bag.

Dropping or clicking a block into the bag makes sense, but retrieving a block from the bag is another story, need another idea there.

**Comment by Mr-B-l-a-c-k** [comment]
I came to suggest the same thing- I'd love to be able to place blocks (or stacks) directly into the bit bag. 

For extracting from the bit bag- currently left clicking a bit pulls out a stack of bits. Shift left clicking should pull out a stack of full blocks (imo)

**Comment by RyanJM93** [comment]
@AlgorithmX2 Perhaps just another option from the chisel to place an entire blocks worth of bits? Like 1/2, 1/4, 1/8, etc. A 1/1 option that would place a blocks worth, that way you can just break it to get the block back would be super useful. Currently, I just use the 1/2 option to fully construct a block and break it.

**Comment by AlgorithmX2** [comment]
@RyanJM93 There are already two options for this.

First, You can use a positive pattern to place full blocks, just use a blank pattern on a normal block, then use it in placement mode.

Second, you can use "Drawn Region" to place a lot of bits at once, just draw a large vertical block's worth.

Both work pretty well, the drawn region method is a bit more finicky, but the pattern method works almost as you describe, just with a first step.

**Comment by RyanJM93** [comment]
@AlgorithmX2 Thanks, I actually hadn't thought of that. I use patterns quite frequently, but didn't think of using them that way. Thanks for the tip!
