### ISSUE TITLE
cross sprites

### ISSUE THREAD

**Issue by electroCutie** [ChiselsAndBits/Chisels-and-Bits#449]
I was thinking about creating the cross sprites that vanilla uses to make flowers, mushrooms, and grass. It would be neat to be able to create them ourselves. The thickness of the voxels is a bit too much to create small things (I was thinking of making a new decorative mushroom)

**Comment by AlgorithmX2** [comment]
I'm assuming your making an suggestion.

In response to that, I don't think it belongs in C&B is after all about chisels and such. Creating those iffy 45 degree angle plants just doesn't fit with the mod in any meaningful way.

I'd say something like this would suit C&B more then to create 2D textures.
![image](https://user-images.githubusercontent.com/2846930/50464678-ea58be80-0957-11e9-8d5f-dfe1e98668a4.png)
