### ISSUE TITLE
Wrench rotation is only visual, v9.15

### ISSUE THREAD

**Issue by TherminatorX** [ChiselsAndBits/Chisels-and-Bits#45]
The wrench does rotate the block visually, but when the world is reloaded, the rotated block is back in its default position. Additionally, a rotated "stair" block causes you to glitch out when trying to walk up it.

Edit: also happens when the chunk is unloaded and reloaded.

**Comment by AlgorithmX2** [comment]
Fixed for 9.16

**Comment by TherminatorX** [comment]
Fix confirmed. Thanks Algo.

**Comment by AlgorithmX2** [comment]
No problem, thanks for the report.
