### ISSUE TITLE
NullPointerException: Ticking block entity

### ISSUE THREAD

**Issue by StoneLegion** [ChiselsAndBits/Chisels-and-Bits#451]
For any bug reports please provide the following details as well,
* MC Version: 1.12.2
* C&B Version: chiselsandbits-14.29

https://pastebin.com/ieA0C3f2

Someone who moving water with chisel and bits I really have no clue this what they said LOL:
```It was me
How did it cause a crash?
I was just using this setup```

```what were you chiseling```

```Water```

```I was actually moving the setup to a compact machine```

```chisels in the machine ?```

```Yup```

**Comment by AlgorithmX2** [comment]
https://github.com/AlgorithmX2/Chisels-and-Bits/blob/d91f5ce0cdb373f3e31cc348444d0b847f820eb2/src/main/java/mod/chiselsandbits/bittank/TileEntityBitTank.java#L434-L438

The only possibly null value on that line is the fluid that the tank is being filled with.

I have to say that seems like a bug with XU2. I can't see how a filling a tank will a null fluid should be possible.

**Comment by AlgorithmX2** [comment]
I just realized I'd committed a change for this almost half a month ago. There was still no release for it. I went ahead and added a test to cache the error, even though It seems more a problem on the other side. But less crashes in my code the better.
