### ISSUE TITLE
please make this mod compatible with 1.7.10

### ISSUE THREAD

**Issue by WilliamTubeHD** [ChiselsAndBits/Chisels-and-Bits#452]
Before continuing if you are reporting an issue, please ensure that all mods involved are updated to the latest version available, if your issue with with intermod compatibility such mixing C&B bits with other blocks make sure that MCMP is also updated. If your issue is a crash, be sure to include the crash log with your report.

For any bug reports please provide the following details as well,
* MC Version:
* C&B Version:
* Do You have Optifine:

**Comment by AlgorithmX2** [comment]
Please see item 2 on my [FAQ](https://algorithmx2.github.io/Chisels-and-Bits/frequently-asked-questions/)
