### ISSUE TITLE
Port C&B to Fabric

### ISSUE THREAD

**Issue by yll1s** [ChiselsAndBits/Chisels-and-Bits#453]
Hello! Can you port C&B to Fabric (1.14)?

* MC Version: 1.14
* C&B Version: None
* Do You have Optifine: No

**Comment by AlgorithmX2** [comment]
I'm afraid I don't have the time for such a large project. I'll be porting to whatever version forge is on once it updates.

**Comment by Phylogeny** [comment]
@ErMANWood To be clear, by all accounts, barring an act of God, this mod will never be ported to modding API other than Forge.

@AlgorithmX2 I'm just thankful you'll find a way to make enough time to port it to 1.13 (or whatever). :tada:

**Comment by liach** [comment]
if you don't have sufficient time, consider skipping 1.13 and go for 1.14 (when forge is out)

**Comment by Phylogeny** [comment]
@liach That's what I meant by "1.13 (or whatever)". Is the disapproval for accurately conveying the chance of a non-Forge port?

**Comment by liach** [comment]
i mean you shouldn't blindly believe in only forge as a viable modding api for minecraft.

**Comment by Phylogeny** [comment]
@liach I don't believe that... I said that as things stand, *this* mod will very likely never be ported to another platform. I try to steer clear of blind faith; thanks.
