### ISSUE TITLE
Console Spam

### ISSUE THREAD

**Issue by ghost** [ChiselsAndBits/Chisels-and-Bits#454]
For any bug reports please provide the following details as well,
* MC Version: 1.12.2
* C&B Version: 14.29
* Do You have Optifine: no

Chisel and Bits is spamming our server console with [Chiselsandbits]: Unable to determin blocks eligibility for chiseling, mrriegel.storagenetwork.block.cable.BlockCable attempted to load net/minecraft/client/util/ItooltipFlag

**Comment by AlgorithmX2** [comment]
The same one over and over again?

It should only log each block that produced an error one time.

**Comment by AlgorithmX2** [comment]
I've disabled logging of eligibility by default.
