### ISSUE TITLE
My mc keeps crashing on launch with my mods 

### ISSUE THREAD

**Issue by ZombieCrazy55** [ChiselsAndBits/Chisels-and-Bits#455]
I am currently trying to make a private modpack for me and my friends to play on but it keeps crashing on launch here's the crash report

---- Minecraft Crash Report ----
// You're mean.

Time: 1/30/19 11:19 PM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: wasliecore/misc/MiscRegister
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:544)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:208)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: wasliecore/misc/MiscRegister
	at wasliecore.main.WaslieCore.<clinit>(WaslieCore.java:39)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:440)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:513)
	... 10 more
Caused by: java.lang.ClassNotFoundException: wasliecore.misc.MiscRegister
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 35 more
Caused by: java.lang.NoClassDefFoundError: wasliecore/interfaces/IInitalization
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 37 more
Caused by: java.lang.ClassNotFoundException: wasliecore.interfaces.IInitalization
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 41 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 215496320 bytes (205 MB) / 884998144 bytes (844 MB) up to 1908932608 bytes (1820 MB)
	Mod Pack: ~~ERROR~~ NullPointerException: null
	LiteLoader Mods: ~~ERROR~~ NullPointerException: null
	LaunchWrapper: 43 active transformer(s)
          - Transformer: cpw.mods.fml.common.asm.transformers.PatchingTransformer
          - Transformer: optifine.OptiFineClassTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.MarkerTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.SideTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.EventSubscriptionTransformer
          - Transformer: net.minecraftforge.classloading.FluidIdTransformer
          - Transformer: am2.preloader.BytecodeTransformers
          - Transformer: appeng.transformer.asm.ASMIntegration
          - Transformer: blusunrize.aquatweaks.core.AquaTweaksCoreTransformer
          - Transformer: codechicken.lib.asm.ClassHeirachyManager
          - Transformer: codechicken.core.asm.InterfaceDependancyTransformer
          - Transformer: codechicken.core.asm.TweakTransformer
          - Transformer: codechicken.core.asm.DelegatedTransformer
          - Transformer: codechicken.core.asm.DefaultImplementationTransformer
          - Transformer: codechicken.nei.asm.NEITransformer
          - Transformer: ivorius.psychedelicraftcore.PsychedelicraftClassTransformer
          - Transformer: thaumic.tinkerer.preloader.AccessTransformer
          - Transformer: com.mumfrey.liteloader.launch.LiteLoaderTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.CrashReportTransformer
          - Transformer: me.guichaguri.betterfps.transformers.MathTransformer
          - Transformer: me.guichaguri.betterfps.transformers.EventTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.DeobfuscationTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.AccessTransformer
          - Transformer: net.minecraftforge.transformers.ForgeAccessTransformer
          - Transformer: appeng.transformer.asm.ASMTweaker
          - Transformer: aroma1997.core.coremod.asm.AromaAccessTransformer
          - Transformer: codechicken.core.asm.CodeChickenAccessTransformer
          - Transformer: thaumic.tinkerer.preloader.AccessTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ModAccessTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ItemStackTransformer
          - Transformer: com.brandon3055.brandonscore.asm.ClassTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.TerminalTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.JoinGamePacketTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.ServerChatPacketTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.LiteLoaderEventInjectionTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.LiteLoaderCallbackInjectionTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.MinecraftOverlayTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.LoginSuccessPacketTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.CustomPayloadPacketTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.ServerCustomPayloadPacketTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.ChatPacketTransformer
          - Transformer: com.thevoxelbox.voxelmap.litemod.VoxelMapTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ModAPITransformer
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1558 Optifine OptiFine_1.7.10_HD_U_D8 92 mods loaded, 92 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UC	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UC	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1558-1.7.10.jar) 
	UC	Forge{10.13.4.1558} [Minecraft Forge] (forge-1.7.10-10.13.4.1558-1.7.10.jar) 
	UC	AM2-Preloader{0.0.3} [AMCore] (minecraft.jar) 
	UC	appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core] (minecraft.jar) 
	UC	AquaTweaksCore{1.0} [AquaTweaks Core] (minecraft.jar) 
	UC	Aroma1997Core{1.0.2.16} [Aroma1997Core] (Aroma1997Core-1.7.10-1.0.2.16.jar) 
	UC	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UC	ivtoolkit{1.2.1} [IvToolkit] (minecraft.jar) 
	UC	NotEnoughItems{1.0.5.120} [Not Enough Items] (Not-Enough-Items-1.7.10-Latest.jar) 
	UC	psychedelicraftcore{1.4} [Psychedelicraft Core] (minecraft.jar) 
	UC	ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core] (minecraft.jar) 
	UC	debug{1.0} [debug] (Dense-Ores-Mod-1.7.10.jar) 
	UC	AnimationAPI{1.2.4} [AnimationAPI] (AnimationAPI-1.7.10.jar) 
	UC	arsmagica2{1.4.0.009} [Ars Magica 2] (1.7.10_AM2-1.4.0.009.jar) 
	UC	nevermine{2.3} [AdventOfAscension] (Advent-of-Ascension-Mod-1.7.10.jar) 
	UC	appliedenergistics2{rv2-stable-10} [Applied Energistics 2] (appliedenergistics2-rv2-stable-10.jar) 
	UC	bdlib{1.9.4.109} [BD Lib] (BdLib-1.7.10.jar) 
	UC	ae2stuff{0.5.0.56} [AE2 Stuff] (AE2-Stuff-Mod-1.7.10.jar) 
	UC	AWWayofTime{v1.3.3} [Blood Magic: Alchemical Wizardry] (Blood-Magic-Mod-1.7.10.jar) 
	UC	guideapi{1.7.10-1.0.1-20} [Guide-API] (Guide-API-1.7.10.jar) 
	UC	NOVA{2015-10-09} [NOVA] (Animus-Mod-1.7.10.jar) 
	UC	AquaTweaks{1.0} [AquaTweaks] (AquaTweaks-Mod-1.7.10.jar) 
	UC	Aroma1997CoreHelper{1.0.2.16} [Aroma1997Core|Helper] (Aroma1997Core-1.7.10-1.0.2.16.jar) 
	UC	AromaBackup{0.0.0.5.b20} [AromaBackup] (AromaBackup-1.7.10-0.0.0.5.b20.jar) 
	UC	AromaBackupRecovery{1.0} [AromaBackup Recovery] (AromaBackup-1.7.10-0.0.0.5.b20.jar) 
	UC	BiblioCraft{1.11.6} [BiblioCraft] (BiblioCraft-Mod-1.7.10.jar) 
	UC	Mantle{1.7.10-0.3.2.jenkins191} [Mantle] (Mantle-Mod-1.7.10.jar) 
	UC	Natura{2.2.0} [Natura] (Natura-Mod-1.7.10.jar) 
	UC	BiblioWoodsNatura{1.5} [BiblioWoods Natura Edition] (BiblioWoods-Natura-Edition-Mod-1.7.10.jar) 
	UC	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UC	ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UC	BuildCraft|Core{7.1.21} [BuildCraft] (BuildCraft-Mod-1.7.10.jar) 
	UC	ExtraUtilities{1.2.12} [Extra Utilities] (Extra-Utilities-Mod-1.7.10.jar) 
	UC	Waila{1.5.10} [Waila] (Waila-Mod-1.7.10.jar) 
	UC	TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct] (TConstruct-Mod-1.7.10.jar) 
	UC	BloodArsenal{1.2-5} [Blood Arsenal] (Blood-Arsenal-Mod-1.7.10.jar) 
	UE	BloodUtils{1.0} [BloodUtils] (Blood-Utils-Mod-1.7.10.jar) 
	UC	fw{1.3.0} [Fullscreen Windowed] (Borderless-Mod-1.7.10.jar) 
	UC	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-Mod-1.7.10.jar) 
	UC	Botania{r1.8-249} [Botania] (Botania-Mod-1.7.10.jar) 
	UC	BrandonsCore{1.0.0.12} [Brandon's Core] (Brandons-Core-1.7.10.jar) 
	UC	BuildCraft|Builders{7.1.21} [BC Builders] (BuildCraft-Mod-1.7.10.jar) 
	UC	BuildCraft|Energy{7.1.21} [BC Energy] (BuildCraft-Mod-1.7.10.jar) 
	UC	BuildCraft|Factory{7.1.21} [BC Factory] (BuildCraft-Mod-1.7.10.jar) 
	UC	BuildCraft|Robotics{7.1.21} [BC Robotics] (BuildCraft-Mod-1.7.10.jar) 
	UC	BuildCraft|Silicon{7.1.21} [BC Silicon] (BuildCraft-Mod-1.7.10.jar) 
	UC	BuildCraft|Transport{7.1.21} [BC Transport] (BuildCraft-Mod-1.7.10.jar) 
	UC	colorfularmor{1.7.10-2.6} [Colorful Armor] (Colorful-Armor-Mod-1.7.10.jar) 
	UC	diversity{ALPHA 1.6.1} [Diversity] (Diversity-Mod-1.7.10.jar) 
	UC	DraconicEvolution{1.0.2h} [Draconic Evolution] (Draconic-Evolution-Mod-1.7.10.jar) 
	UC	DragonMounts{r41-1.7.10} [Dragon Mounts] (Dragon-Mounts-Mod-1.7.10.jar) 
	UC	DurabilityShow{1.2.0} [Durability Show] (Durability-Show-Mod-1.7.10.jar) 
	UC	endercompass{1.2} [Ender Compass] (Ender-Compass-Mod-1.7.10.jar) 
	UC	EnderStorage{1.4.7.38} [EnderStorage] (Ender-Storage-Mod-1.7.10.jar) 
	UC	foxlib{1.7.10-0.7.0} [FoxLib] (FoxLib-1.7.10.jar) 
	UC	harvestcraft{1.7.10j} [Pam's HarvestCraft] (HarvestCraft-Mod-1.7.10.jar) 
	UC	iChunUtil{4.2.3} [iChunUtil] (iChun-Util-Mod-1.7.10.jar) 
	UC	IronChest{6.0.60.741} [Iron Chest] (Iron-Chests-Mod-1.7.10.jar) 
	UC	IronPP{3.4.4} [Iron Pressure Plate] (Iron-Pressure-Plate-Mod-1.7.10.jar) 
	UC	Mekanism{9.1.1} [Mekanism] (Mekanism-Mod-Core-1.7.10.jar) 
	UC	magicalcrops{4.0.0_PUBLIC_BETA_4b} [Magical Crops: Core] (Magical-Crops-Mod-1.7.10.jar) 
	UC	MekanismGenerators{9.1.1} [MekanismGenerators] (Mekanism-Mod-Generators-1.7.10.jar) 
	UC	MekanismTools{9.1.1} [MekanismTools] (Mekanism-Mod-Tools-1.7.10.jar) 
	UC	mochickens{1.5} [Mo Chickens] (Mo-Chickens-Mod-1.7.10.jar) 
	UC	MoreFurnaces{1.3.9} [More Furnaces] (More-Furnaces-Mod-1.7.10.jar) 
	UC	Morph{0.9.3} [Morph] (Morphing-Mod-1.7.10.jar) 
	UC	moEatableSwords{1.7.2} [moSwords Mod Eatables] (MoSwords-Mod-1.7.10.jar) 
	UC	moSwords{v3} [Mo Swords Mod] (MoSwords-Mod-1.7.10.jar) 
	UC	cfm{3.4.7} [§9MrCrayfish's Furniture Mod] (MrCrayfishs-Furniture-Mod-1.7.10.jar) 
	UC	OreSpawn{1.7.10.20.3} [OreSpawn] (Ore-Spawn-Mod-1.7.10.zip) 
	UC	pplus{1.7.10} [Peaceful+] (Peaceful Plus [1.7.10].jar) 
	UC	psychedelicraft{1.4.2} [Psychedelicraft] (Psychedelicraft-Mod-1.7.10.jar) 
	UC	RecipesPlus{1.1.2} [RecipesPlus] (Recipes-Plus-Mod-1.7.10.jar) 
	UC	Roguelike{1.5.0} [Roguelike Dungeons] (Roguelike-Dungeons-Mod-1.7.10.jar) 
	UC	Sanguimancy{1.7.10-1.1.9-35} [Sanguimancy] (Sanguimancy-Mod-1.7.10.jar) 
	UC	Tails{1.7.10-1.4.1a} [Tails] (Tails-Mod-1.7.10.jar) 
	UC	ThaumicTinkerer{unspecified} [Thaumic Tinkerer] (Thaumic-Tinkerer-Mod-1.7.10.jar) 
	UC	TMechworks{0.2.15.106} [Tinkers' Mechworks] (Tinkers-Mechworks-Mod-1.7.10.jar) 
	UC	Trapcraft{v2.2.1a} [Trapcraft] (Trapcraft-Mod-1.7.10.zip) 
	UC	bspkrsCore{6.15} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.15.jar) 
	UC	Treecapitator{1.7.10} [Treecapitator] (Tree-Capitator-Mod-1.7.10.jar) 
	UC	TwilightForest{2.3.7} [The Twilight Forest] (Twilight-Forest-Mod-1.7.10.jar) 
	UC	TwoGraves{1710.1.0} [Graves] (TwoGraves-Mod-1.7.10.jar) 
	UE	WaslieCore{1.1} [WaslieCore] (WaslieCore-1.7.10.jar) 
	UC	wawla{1.3.1} [What Are We Looking At] (Wawla-Mod-1.7.10.jar) 
	UC	witchery{0.24.1} [Witchery] (Witchery-Mod-1.7.10.jar) 
	UC	wolfarmor{1.3.0} [Wolf Armor and Storage] (Wolf-Armor-Storage-Mod-1.7.10.jar) 
	UC	XEZUpdate{2.0.17} [XEliteZ Update Utility] (XEliteZ-Mod-Update-Utility-1.7.10.jar) 
	UC	McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UC	denseores{1.0} [Dense Ores] (Dense-Ores-Mod-1.7.10.jar) 
	UC	ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	AE2 Version: stable rv2-stable-10 for Forge 10.13.2.1291
	Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine
	TConstruct Environment: Environment healthy.
	OptiFine Version: OptiFine_1.7.10_HD_U_D8
	Render Distance Chunks: 7
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.13543 Compatibility Profile Context 25.20.15002.58
	OpenGlRenderer: AMD Radeon (TM) R9 390 Series
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 6

**Comment by AlgorithmX2** [comment]
The error says something about "wasliecore/misc/MiscRegister"

So whatever Waslie core is? maybe its missing? maybe something requires it?

Not sure, but I don't think this is related to C&B.

**Comment by ZombieCrazy55** [comment]
I have the wastlie core mod installed which is why I don't understand why it keeps crashing

**Comment by AlgorithmX2** [comment]
Perhaps you should ask the developer that uses the mod? or wrote it? Or perhaps remove it, and any mod that requires it?
