### ISSUE TITLE
Cupboard Access Via File Explorer

### ISSUE THREAD

**Issue by TimeLordian01** [ChiselsAndBits/Chisels-and-Bits#457]
I cannot find a way to access the Chisels and Bits Cupboard via the game files, idk if its an issue or it just hasn't been added that you can do that, but if not, please add it, if it has been, where would i find the directory?

**Comment by AlgorithmX2** [comment]
Do you mean Clipboard? if so its in the config folder, and yes you should be able to use the same clipboard between worlds. It is one of the reasons it exists.

**Comment by TimeLordian01** [comment]
> Do you mean Clipboard? if so its in the config folder, and yes you should be able to use the same clipboard between worlds. It is one of the reasons it exists.

Yes the clipboard, i've tried looking in the config folder but i cannot find it? is it a file or a .cfg? cause its on a server instead of singleplayer?

**Comment by AlgorithmX2** [comment]
The clipboard is stored on the client-side, in the config folder its called "chiselsandbits_clipboard.cfg"

Not with the server.

**Comment by TimeLordian01** [comment]
So, if I were to join a server after creating the custom blocks they should appear in the clipboard? I tried that already but it doesn't seem to load them?

**Comment by AlgorithmX2** [comment]
I just went logged into a single player world, added a block to the clipboard, then joined a creative server. pulled it out of the clipboard and placed it, all without shutting down the client.

All seems to be working as intended.

**Comment by AlgorithmX2** [comment]
You might want to try 14.31 when it shows up on curse forge, there was an issue with the clipboard saving, it might be related to your issue.
