### ISSUE TITLE
Clipboard does not store items permanent

### ISSUE THREAD

**Issue by radiantraptor** [ChiselsAndBits/Chisels-and-Bits#459]
When I try to store chseled blocks in the clipboard with the "/c&b.exportmodel" command the items are stored and the file "chiselsandbits_clipboard.cfg" gets some content. But after closing Minecraft and start it again the file does not seem to be recognized and the clipboard is empty again.

MC Version: 1.12.2
C&B Version: 14.30
Do You have Optifine: OptiFine_1.12.2_HD_U_E3.jar
many other mods

but I also tested it with MC vanilla + jei + chiselandbits only.

**Comment by AlgorithmX2** [comment]
You seem to be confused regarding the word clipboard usage in the mod.

/c&b.exportmodel stores the JSON ( raw mincraft model data ) to the system clipboard, this part of windows/linux whatever OS your using. This feature is for resource pack and mod developers.

The creative clipboard, as provided by C&B is not related in anyway. To add a block to the creative clipboard there is a hotkey you can assign. It also by default adds blocks you break to it.

You'll want to use the keyboard shortcut to add a block your looking at too the clipboard, so you can then pull it back out and place it in the world.

**Comment by radiantraptor** [comment]
OK, thanks for clarifying the difference.
Anyway, the block was in the Chisel and Bits Clipboard tab in the inventory (since I was playin around and building and destroying the blocks), but after a Minecraft restart it was gone.

**Comment by AlgorithmX2** [comment]
Will be fixed in C&B 14.31

**Comment by radiantraptor** [comment]
That was very quick, thank you!
