### ISSUE TITLE
Shrinking

### ISSUE THREAD

**Issue by zac1228** [ChiselsAndBits/Chisels-and-Bits#460]
I was in the middle of trying to sculpt a duck and I realized how difficult it was to reach the places I needed ( the middle of the block ). I was really thinking about how nice it would be if it was possible to shrink down to the point where 1 bit was the size of a regular block! I know it would probably be really difficult to do something like that, but if it was possible, I think it would be an unbelievably great addition to the mod.

**Comment by AlgorithmX2** [comment]
I don't generally think that a way to shrink the player belongs in C&B, it might be a fun idea for another mod. But C&B at its core is a mod about chiseling and sculpting. I realize that shrinking could be used in conjunction with this, but it also adds a significant spike to the code base's requirements and surface area.

From what I have seen previously I think it would even require a coremod, which I have gone though great efforts to not have with C&B.

With that in mind, I don't think it should be part of C&B.
