### ISSUE TITLE
Flickering with Sildur's Shaders

### ISSUE THREAD

**Issue by mrwallace888** [ChiselsAndBits/Chisels-and-Bits#467]
Works really well, however there's a small issue with house-building. I built a house using custom blocks and it works fine, however the walls and such tend to flicker for some odd reason. Not sure why it does this. Without shaders it works fine and it works with other shaders too, however the only one I really use is Sildur's because either A), they lag my PC, or B), they are outdated or broken. Was just wondering if you had any idea.

* MC Version: 1.12.2
* C&B Version: 14.32
* Optifine: I have Optifine

**Comment by mrwallace888** [comment]
Anyone?

**Comment by mrwallace888** [comment]
Seriously?

**Comment by AlgorithmX2** [comment]
I don't have any experience with shaders and MC myself, and I don't know why those specific shaders would cause issues with the mod. I don't actively support shaders, since I cannot test with them, or optifine.

Not sure I can offer much help with your issue.
