### ISSUE TITLE
NPE when placing bit at Integrated Dynamics Cable

### ISSUE THREAD

**Issue by rubensworks** [ChiselsAndBits/Chisels-and-Bits#47]
Received this crash report a few days ago over here: https://github.com/CyclopsMC/IntegratedDynamics/issues/34

Apparently, placing a bit in an Integrated Dynamics cable causes the following crash: http://pastebin.com/UuwER4dj
I currently don't think this is being caused by ID (please correct me if I'm wrong).
If I can do anything to help, just let me know ;-)

**Comment by AlgorithmX2** [comment]
Seems like the part doesn't have a world assigned to it when your adding the bits, not sure if I broken MCMP support or what, I'll have to do some research.

This issue is C&B based.
