### ISSUE TITLE
Flat Colored Blocks Item Ids And World Edit

### ISSUE THREAD

**Issue by Velocity99YT** [ChiselsAndBits/Chisels-and-Bits#471]
I was trying to use world edit but then I didn't know what the item ids were for the flat colored blocks. How do I find the ids and how do I type the command to spawn it in.

**Comment by AlgorithmX2** [comment]
Mods no longer have set item or block ids, they are generated when MC creates the world. your best bet is to place blocks your interested in in the world in some way you can recognize them and copy them.

Thats about all I can offer as far as suggestions, I have never used world edit.
