### ISSUE TITLE
1.14 Port

### ISSUE THREAD

**Issue by kiritodragneel** [ChiselsAndBits/Chisels-and-Bits#472]
Hay,
I was wondering if you plan to bring to 1.14 now forge is out for 1.14
With all the improvements to minecrafts block detection etc....

I would LOVE to see this mod utilize them

**Comment by AlgorithmX2** [comment]
~~Porting to 1.14 will likely happen once forge 1.14 is stable/recommended.~~

I'm sorry, but I won't be able to do this.

**Comment by lukasino1214** [comment]
What is problem with versions 1.14.4 of minecraft?
I am really looking forward to chisel and bits for 1.14.4.

**Comment by Aeltumn** [comment]
> What is problem with versions 1.14.4 of minecraft?
> I am really looking forward to chisel and bits for 1.14.4.

You should give #474 a read. tl;dr AlgorithmX2, the developer of the mod, has retired.

**Comment by Aeltumn** [comment]
The mod has now been updated to 1.16 so I'll close this issue! Unfortunately there is no 1.14 version.
