### ISSUE TITLE
[1.10.2] Minecraft Crash - Caught exception from Chisels & Bits (chiselsandbits)

### ISSUE THREAD

**Issue by LEOSAURE** [ChiselsAndBits/Chisels-and-Bits#476]
Before continuing if you are reporting an issue, please ensure that all mods involved are updated to the latest version available, if your issue with with intermod compatibility such mixing C&B bits with other blocks make sure that MCMP is also updated. If your issue is a crash, be sure to include the crash log with your report.

Here the crash log:
https://pastebin.com/ds9b3WYq

For any bug reports please provide the following details as well,
* MC Version: 1.10.2
* C&B Version: Tested with the 12.18, the 12.15 and the 12.14
* Do You have Optifine: No

**Comment by Panduso** [comment]
he's not working on the mod anymore, there's no point in doing this

**Comment by Panduso** [comment]
he's not working on the mod anymore, there's no point in doing this

**Comment by Aeltumn** [comment]
If this is still an issue, please take a look at the settings relating to the creative clipboard. Either way, this issue won't be fixed as 1.10 is no longer receiving updates.
