### ISSUE TITLE
Could you let it compatible with Residence Plugin and PlotSquared Plugin?

### ISSUE THREAD

**Issue by xibo1212** [ChiselsAndBits/Chisels-and-Bits#477]
* MC Version: 1.12.2
* C&B Version: chiselsandbits-14.33
* Do You have Optifine: yes

**Comment by Panduso** [comment]
he's not working on the mod anymore, there's no point in doing this

**Comment by Aeltumn** [comment]
Compatibility with bukkit plugins is not guaranteed but they should be compatible. If you have issues when using these plugins you could report them to the plugin creators.
