### ISSUE TITLE
need help with my file

### ISSUE THREAD

**Issue by Skarred413** [ChiselsAndBits/Chisels-and-Bits#479]
this is my first time getting a mod and i don't know how to get a zip file/jar file i looked up for what a zip file is but it is kind of confusing cause i have never done this before and the jar file doesn't work. i need help!

MC Version - 1.14.4
C&B Version - idk what this is :/
i don't think i have optifine?

**Comment by Aeltumn** [comment]
Chisels & Bits is a mod for Minecraft 1.12.2, to use it you need to install Minecraft Forge and then put the Chisels & Bits jar in the /mods/ folder. I'd suggest looking up a tutorial if you've never used mods before.

You can download Chisels & Bits [on curseforge.](https://www.curseforge.com/minecraft/mc-mods/chisels-bits)
