### ISSUE TITLE
Any plans for 1.14.4 (Forge)?

### ISSUE THREAD

**Issue by sepsol** [ChiselsAndBits/Chisels-and-Bits#482]
Please support this version!

**Comment by Aeltumn** [comment]
You should have a look at #474.

**Comment by sepsol** [comment]
I wish you luck

**Comment by lukasino1214** [comment]
What is problem with vesion 1.14.4 of minecraft?
I am really looking forward to chisel and bits on 1.14.4

**Comment by Aeltumn** [comment]
> What is problem with vesion 1.14.4 of minecraft?
> I am really looking forward to chisel and bits on 1.14.4

You should give #474 a read. tl;dr AlgorithmX2, the developer of the mod, has retired.
