### ISSUE TITLE
how could i export my sculpture out of minecraft?

### ISSUE THREAD

**Issue by dablive** [ChiselsAndBits/Chisels-and-Bits#483]
i used the newest mod of 1.12.2 and i want to export the sculpture out of mc , and use it for other renderers , how can i do that ?

**Comment by Korynkai** [comment]
I think what you might be looking for is WorldEdit? WorldEdit allows you to copy selections within your Minecraft world, paste them elsewhere within the world, and create .schematic files from those selections, all while inside the game.

I suppose you could also examine and manipulate the NBT data yourself; I'd also recommend MCEdit but it currently has issues with Forge mods...

**Comment by Aeltumn** [comment]
> I think what you might be looking for is WorldEdit? WorldEdit allows you to copy selections within your Minecraft world, paste them elsewhere within the world, and create .schematic files from those selections, all while inside the game.
> 
> I suppose you could also examine and manipulate the NBT data yourself; I'd also recommend MCEdit but it currently has issues with Forge mods...

I think he means he wants to export C&B sculptures into external programs, not somewhere else in Minecraft. There's a command in C&B for exporting models but I don't know in which format that is and whether or not that format is useable in external programs. AlgorithmX2 was working on a model viewing website but that wasn't finished.

**Comment by Korynkai** [comment]
> I think he means he wants to export C&B sculptures into external programs, not somewhere else in Minecraft. There's a command in C&B for exporting models but I don't know in which format that is and whether or not that format is useable in external programs.

Hmm, looking at the code, it seems to be JSON format, requires each block section of the sculpture to be in your hand when copying (thus requires you to split the sculpture into blocks anyway), copies the JSON to clipboard (so you need an external text editor to copy it) and none of the localized strings the `mod.chiselsandbits.commands.JsonModelExport` class refers to are present (implying this feature was never completed).

There are methods to convert WorldEdit schematic files to JSON models, Qubicle and various other formats as well, if that's an option.

**Comment by dablive** [comment]
> > 我认为您可能正在寻找WorldEdit？WorldEdit允许您在Minecraft世界中复制选择，将选择粘贴到世界中的其他位置，并根据这些选择创建.schematic文件。
> > 我想您也可以自己检查和操作NBT数据。我也建议使用MCEdit，但是目前Forge mods存在问题...
> 
> 我认为他的意思是他想将C＆B雕塑导出到外部程序中，而不是在Minecraft中的其他位置。C＆B中有一个用于导出模型的命令，但我不知道该格式是哪种，以及在外部程序中是否可以使用该格式。AlgorithmX2正在一个模型查看网站上工作，但尚未完成。

yes that is what i'm thinking . it seems that the question couldn't be solved in easy ways . thanks for your information.

**Comment by dablive** [comment]
> > 我认为他的意思是他想将C＆B雕塑导出到外部程序中，而不是在Minecraft中的其他位置。C＆B中有一个用于导出模型的命令，但我不知道该格式是哪种，以及在外部程序中是否可以使用该格式。
> 
> 嗯，看一下代码，它似乎是JSON格式，在复制时需要将雕塑的每个块部分都放在您的手中（因此无论如何您都需要将雕塑分成多个块），然后将JSON复制到剪贴板（因此您需要一个外部文本编辑器来复制它），并且`mod.chiselsandbits.commands.JsonModelExport`该类所引用的本地化字符串均不存在（暗示此功能从未完成）。
> 
> 如果可以的话，有一些方法可以将WorldEdit示意图文件转换为JSON模型，Qubicle和其他各种格式。

Thanks for your reply, it provides me with a way to solve the problem indirectly,I’ll try it.

**Comment by Aeltumn** [comment]
Can I close this issue? Did you manage to solve your problem?

**Comment by dablive** [comment]
> 我可以解决这个问题吗？您设法解决您的问题了吗？

yeah please , though I still troubled with that...
