### ISSUE TITLE
Crashing (1.11.2)

### ISSUE THREAD

**Issue by PsyfiDerp** [ChiselsAndBits/Chisels-and-Bits#487]
When I try to launch the game in version 1.11.2 with the mod, it crashes while loading, with this crash report.

[crash-2019-11-30_23.37.32-client.txt](https://github.com/AlgorithmX2/Chisels-and-Bits/files/3907818/crash-2019-11-30_23.37.32-client.txt)

Help would be appreciated :)

* MC Version: 1.11.2
* C&B Version: chiselsandbits-13.16
* Do You have Optifine: no

**Comment by Aeltumn** [comment]
Could you try removing the chiselsandbits_clipboard.cfg file from the /config/ directory?
Otherwise try setting the configuration option persistCreativeClipboard to false.

**Comment by PsyfiDerp** [comment]
Removing the file worked, thank you!
