### ISSUE TITLE
[Question] how do you place Chisel log bits sideways rather than up and down?

### ISSUE THREAD

**Issue by RoseaBee** [ChiselsAndBits/Chisels-and-Bits#489]
I'm guessing it's impossible cause all Chisel I see involves a log facing up and down, but doesn't hurt to ask. I'm trying to build log fences on top of walls that all ready have Bits built as vanilla log walls can't be set in the same tile, but instead of getting th bark texture like I need, I'm getting the rings of the tree instead. And honestly it just looks tacky.

**Comment by Aeltumn** [comment]
~~This is unfortunately impossible in C&B as far as I'm aware~~, however log bits can be placed sideways just by placing them on the side of a block in Chisels & Bits 2 in 1.14+ so this will be added in the future.

**Comment by LeekZhangx** [comment]
You need to put a  log block sideways first ,then use the chisel to operate and get bit.
Logs in different directions are different blocks.
![2020-01-10_23 18 48](https://user-images.githubusercontent.com/45160221/72165054-c7ce0200-3401-11ea-9e4f-464012a15a43.png)
![2020-01-10_23 19 33](https://user-images.githubusercontent.com/45160221/72165065-cac8f280-3401-11ea-99d3-43cb42e853cc.png)
![2020-01-10_23 19 37](https://user-images.githubusercontent.com/45160221/72165071-cac8f280-3401-11ea-8aa5-55dba0989de5.png)
![2020-01-10_23 19 39](https://user-images.githubusercontent.com/45160221/72165074-cbfa1f80-3401-11ea-8efa-abb1ca50d7e9.png)

You can run '/fill ~ ~ ~ ~ ~ ~ minecraft:log 12'  commond to get the full bark log ,the full bark oak log id is '17:12' or 'minecraft:log 12' , and get logs of other textures like this.

![2020-01-10_23 24 59](https://user-images.githubusercontent.com/45160221/72165076-cbfa1f80-3401-11ea-95de-849b56396f83.png)

Similarly, blocks with directions (like log , hay block , bone block ......) need to be placed by yourself to get their bits.

**Comment by Aeltumn** [comment]
Didn't know you could do that, thanks for the answer @MPNanKing, that's also why I didn't close the issue before; I wasn't sure about it.
