### ISSUE TITLE
Can't chiselbits some blocks?

### ISSUE THREAD

**Issue by Inari-Whitebear** [ChiselsAndBits/Chisels-and-Bits#49]
Hi, got some odd issue in 1.9 (Forge 1904, chiselbits 9.18).

In singleplayer I can cut into psi decorative blocks just fine. As well as chisel blocks (like chiseled glowstone). However, on the server for a splitsecond it looks like it takes away something but then just puts the block back to as it was? Other blocks like stonebricks etc work fine though

The server admin also doesn't seem to have changed any configs for it, so they should be the same as on the client?

**Comment by Inari-Whitebear** [comment]
Booted up a local server, same issue on there, so its not somehow specific to that one server it seems.

Also can't use the handsaw to chop it into smaller pieces in crafting table (it shows up as craftable but when I take it out it just goes back into the table since the server seems to refuse doing that).

**Comment by Inari-Whitebear** [comment]
For Psi:
[this check](https://github.com/AlgorithmX2/Chisels-and-Bits/blob/1.8.9/src/main/java/mod/chiselsandbits/chiseledblock/BlockBitInfo.java#L172) fails, because it checks the superclass of vazkii.psi.common.block.BlockPsiDecorative (which is vazkii.psi.common.block.base.BlockMetaVariants) for quantityDropped. It then checks vazkii.psi.common.block.base.BlockMetaVariants and then vazkii.psi.common.block.base.BlockMod
At which it seems to get an exception:
https://gist.github.com/Inari-Whitebear/c4327f087dc7021e1f5ba9a9dfb1bc57
Since thats a client class that isn't found, I guess it explains why it only happens on the server

**Comment by Inari-Whitebear** [comment]
Same for chisel's glowstone, albeit another class:
https://gist.github.com/Inari-Whitebear/29572925d9bc6fbcf6c243c2ad4711cb

**Comment by AlgorithmX2** [comment]
That certainly answers the question as to why its failing on the server, but it does raise another question... why is reflection failing on those blocks but yet you can place those blocks without crashing the server...

quantityDropped shouldn't have any issues being called on the server. and no mod would use ItemMeshs or particle effects from that method either, that sounds pretty crazy and I have confirmed that the PSI block doesn't implement that method except for on its conjured blocks.

I honestly think that this rabbit hole just got a lot deeper...

**Comment by AlgorithmX2** [comment]
I cannot resolve this on my end, but I did add a nice log Item to the output about the exact issue,

"Unable to determine blocks eligibility for chiseling, vazkii.psi.common.block.base.BlockMod attempted to load net/minecraft/client/renderer/ItemMeshDefinition"

I also submitted a pull request to Psi to fix it.

Thats all for now I suppose.
