### ISSUE TITLE
Block changing color when selected by chisel

### ISSUE THREAD

**Issue by ricey125** [ChiselsAndBits/Chisels-and-Bits#491]
* MC Version: 1.12.2
* C&B Version: 14.33
* Do You have Optifine: Yes
* Conquest Reforged: 3.0.2-mc1.12.2

I want this block color to translate to my chisels build, but it changes color? Is there any fix for this?
![2020-01-16_09 34 09](https://user-images.githubusercontent.com/59389256/72548565-cb1f1e80-3843-11ea-845a-67a7f65fcd5d.png)

**Comment by Aeltumn** [comment]
I can't really help you with this, the code should color every bit just as a normal block would be colored at that location. No more code changes will be made to C&B so unless Conquest Reforged can add compatibility for C&B this can't be fixed.
