### ISSUE TITLE
Creating Cake-like Foods

### ISSUE THREAD

**Issue by AwesomeNoob999** [ChiselsAndBits/Chisels-and-Bits#493]
Could you add it so you could make cake-like foods like this  [https://www.youtube.com/watch?v=GZDBd6iIa08&t=331s] If you did impliment this it could give you 1.5 shanks of hunger per slice.

**Comment by AwesomeNoob999** [comment]
how you add labels

**Comment by Aeltumn** [comment]
Sorry but this request is too specific to be implemented nicely. How would the mod determine what is a slice of an arbitrary chiseled block? Perhaps someone would want a plate with cake on top, You can't make the plate disappear too.

Also, C&B is no longer being developed. You can however request features for C&B2 if you'd like.

**Comment by AwesomeNoob999** [comment]
ok
