### ISSUE TITLE
Missing chiseled blocks and bits when pasting

### ISSUE THREAD

**Issue by LeekZhangx** [ChiselsAndBits/Chisels-and-Bits#494]
I have tried many ways to copy the chiseled blocks to another map , the only way to successfully place those blocks is to use the C&B clipboard , but can only be placed separately each time , and no bits are missing. Now , I use the 'structure_block' to help me to save and copy them , strangely only the original map and new maps can be pasted those structures , and some maps that have been playing for a long time or added other mods cannot use this method normally , these bits will **be replaced** or **lost**.

![2020-01-19_00 25 47](https://user-images.githubusercontent.com/45160221/72667553-c2069b00-3a57-11ea-939e-d1401bc70769.png)
![2020-01-19_00 47 32](https://user-images.githubusercontent.com/45160221/72667556-c5018b80-3a57-11ea-8312-ce72bc3e9417.png)

I used FCB in the map , tow maps have same config files ,but these blocks appear in a different order in the UI.

![2020-01-19_00 51 40](https://user-images.githubusercontent.com/45160221/72667595-6dafeb00-3a58-11ea-8175-939b74cc57a9.png)
![2020-01-19_00 47 54](https://user-images.githubusercontent.com/45160221/72667593-6c7ebe00-3a58-11ea-8ca8-c69a1c9b3da9.png)

And some forbidden destruction blocks also appear as bits.

![2020-01-19_01 14 12](https://user-images.githubusercontent.com/45160221/72667649-11999680-3a59-11ea-9b4b-2701d7b1e75b.png)
![2020-01-19_00 46 26](https://user-images.githubusercontent.com/45160221/72667647-10686980-3a59-11ea-83dd-5a3c348ff79e.png)
![2020-01-19_00 47 09](https://user-images.githubusercontent.com/45160221/72667648-11010000-3a59-11ea-86d8-628851827363.png)

The bits of the original block will also be changed during pasting , and the complete FCB's block is not affected here.
This is a bug in 1.12, and I'm not sure what will happen in 1.14, so I submit it here.

[My World.zip](https://github.com/AlgorithmX2/Chisels-and-Bits/files/4081257/My.World.zip)

This is an anomalous map. It only retains one region, and the structures are stored under the 'My World/structures'. C&B and FCB use the default configuration.

* MC Version: 1.12.2
* C&B Version:14.33
* FCB Version: 1.12-6.7
* Do You have Optifine: Yes

**Comment by LeekZhangx** [comment]
WorldEdit's save schematic and copy region files are presented in the wrong blocks too.

**Comment by Aeltumn** [comment]
This is a known issue, you are not able to export creations to another world. Chiseled Blocks are saved in an optimized format that is world specific. This means you can use any kind of tool to copy chiseled blocks within the same world but if you copy it to another world you'll see there are issues. In 1.12 it should actually be possible to copy blocks between two worlds as long as the same mods are used in both at the same time. If more mods are installed ids can differ which also breaks things.

There will be a way to update worlds from 1.12 to 1.14 but there are quite a few issues that need to be addressed before that can happen.

**Comment by LeekZhangx** [comment]
But using a clipboard file is feasible, but very cumbersome. Are these blocks different from those in the map? Or does the mod currently not provide other methods to export the building itself?

**Comment by Aeltumn** [comment]
Those in the clipboard are stored in a custom crossworld format where they are stored as e.g. minecraft:stone instead of the id 1. Algorithm had plans to add blueprints to allow for easier exporting for years but he never had time to finish it.
