### ISSUE TITLE
 Can not place finished works

### ISSUE THREAD

**Issue by Depliix** [ChiselsAndBits/Chisels-and-Bits#497]
If I try to mine a finished work with an axe or pickaxe it works, but if I want to place it won't be placed but will disappear from the inventory

* Client Version: 1.12.2
* Server Version: Magma-45bb996
* C&B Version: 14.33
* Do You have Optifine: Yes (OptiFine_1.12.2_HD_U_E3)

**Comment by Aeltumn** [comment]
Looking at Magma it's a platform where you can also install bukkit plugins, what plugins do you have installed? It is possible some plugin might be cancelling the placement of chiseled blocks, like WorldGuard.

**Comment by Depliix** [comment]
I have no Plugins installed.

**Comment by L1GHT4** [comment]
I have the same issue, maybe it is a problem with the Magma, because i also have this platform installed.

**Comment by Aeltumn** [comment]
> 
> 
> I have the same issue, maybe it is a problem with the Magma, because i also have this platform installed.

Sounds likely. As this mod is no longer being developed it's up to Magma to have this issue fixed.
