### ISSUE TITLE
Not uppdated

### ISSUE THREAD

**Issue by IngLolVonAnka** [ChiselsAndBits/Chisels-and-Bits#498]
Before continuing if you are reporting an issue, please ensure that all mods involved are updated to the latest version available, if your issue with with intermod compatibility such mixing C&B bits with other blocks make sure that MCMP is also updated. If your issue is a crash, be sure to include the crash log with your report.

For any bug reports please provide the following details as well,
* MC Version:
* C&B Version:
* Do You have Optifine:

**Comment by IngLolVonAnka** [comment]
updated*****

**Comment by Aeltumn** [comment]
I don't understand what you're asking. If you are wondering about the current state of C&B you should have a look at #474 .
