### ISSUE TITLE
Can't place bits, and chiseling blocks (kind of) doesn't work.

### ISSUE THREAD

**Issue by Slurpiee** [ChiselsAndBits/Chisels-and-Bits#500]
If I interact with a block in any way after chiseling it, the chiseling is reverted, and the bits just disappear upon placement. (Not invisible, just gone.)

* MC Version: 1.12.2
* C&B Version: 14.33
* Do You have Optifine: No.

(Sorry if this has been brought up before, but I didn't see a solution for this anywhere.)

**Comment by Aeltumn** [comment]
Are you perhaps trying to build in an area where building is disabled? Like the spawn chunks when you're not OP. Are you running a single player world or on a server with something else than Forge, or if you are playing with other mods: which ones?

**Comment by Slurpiee** [comment]
> Are you perhaps trying to build in an area where building is disabled? Like the spawn chunks when you're not OP. Are you running a single player world or on a server with something else than Forge, or if you are playing with other mods: which ones?

I'm running on Forge, with no other mods, on my own Forge server as OP.

**Comment by Slurpiee** [comment]
Issue solved itself, NVM. Sorry.
