### ISSUE TITLE
Tape measure text doubling

### ISSUE THREAD

**Issue by Poetgetic** [ChiselsAndBits/Chisels-and-Bits#502]
Text on tape measure overlays itself, including when measuring more than 1 block in height, and makes it almost unreadable. The color options also do nothing.

* MC Version:1.12.2
* C&B Version: 14.33
* Do You have Optifine: Yes

**Comment by Aeltumn** [comment]
Could you attach a screenshot of this happening?

**Comment by Poetgetic** [comment]
Doesn't look as bad with these but it can make it real hard to tell like a 6 from an 8
![image-1](https://user-images.githubusercontent.com/44553540/80504740-72cae300-8941-11ea-8618-9c01f64651fa.png)

![image-2](https://user-images.githubusercontent.com/44553540/80504976-bd4c5f80-8941-11ea-8d5d-210953b60512.png)
