### ISSUE TITLE
Bit documenation : Question

### ISSUE THREAD

**Issue by NanoCE** [ChiselsAndBits/Chisels-and-Bits#503]
Im not sure where the best place is to ask this but Im attempting to fix a block id issue with one of my chisel and bit blocks. I have enough sense to navigate most of your code but am running into snags with the format of how the block nbt is stored. Would you be willing to point me to documentation on it and/or explain it? Thats all I need.

**Comment by Aeltumn** [comment]
Every chiseled block has a VoxelBlob, this VoxelBlob stores a int array that is 16x16x16 long which gives every bit in the block an int. These ints are the state ids of a block. You can find more information no how to read/write the int array (as it's formatted with some more information) in the [serialization package](https://github.com/AlgorithmX2/Chisels-and-Bits/tree/1.12/src/main/java/mod/chiselsandbits/chiseledblock/serialization), specifically [BlobSerializer](https://github.com/AlgorithmX2/Chisels-and-Bits/blob/1.12/src/main/java/mod/chiselsandbits/chiseledblock/serialization/BlobSerializer.java). I wrote a [tool](https://github.com/Aeltumn/Chisels-And-Bits-WorldFixer) to convert 1.12 C&B worlds to 1.14 but you can probably repurpose this code to have it instead update the state ids for a 1.12 world.

**Comment by Serega007RU** [comment]
@Aeltumn Hello. I apologize for the necropost. Could you provide a valid link to your 1.12 C&B worlds to 1.14 conversion tool? The link no longer works https://github.com/Aeltumn/Chisels-And-Bits-WorldFixer

**Comment by Aeltumn** [comment]
I unfortunately never finished the tool so I eventually delisted it to avoid confusion. It would've required some changes to Forge anyway because Mojang does not properly support updating between versions, it just deletes all block entities.
