### ISSUE TITLE
Vehicle mod for chisels and bits

### ISSUE THREAD

**Issue by terralord223** [ChiselsAndBits/Chisels-and-Bits#504]
Before continuing if you are reporting an issue, please ensure that all mods involved are updated to the latest version available, if your issue with with intermod compatibility such mixing C&B bits with other blocks make sure that MCMP is also updated. If your issue is a crash, be sure to include the crash log with your report.

For any bug reports please provide the following details as well,
* MC Version:
* C&B Version:
* Do You have Optifine:

i want to ask a question to all users,

is there a mod for chisels and bits to create moving vehicles?

thank you very much and have a great day,
Terralord223

**Comment by Aeltumn** [comment]
This is something you should ask on reddit or discord, not something to make a github issue for.
To answer your question: No, I don't think a mod exists that does that.
