### ISSUE TITLE
Chisel and bits mod not showing up and not loading into minecraft

### ISSUE THREAD

**Issue by KawaiiBoy63** [ChiselsAndBits/Chisels-and-Bits#506]
Hi. I just downloaded chisel and bits for 1.12.2 and its not showing up in the mods menu i am so confused im 1 billion percent sure i  have the right mod version and the right forge version

**Comment by Aeltumn** [comment]
There are a couple things that could cause your issue:
1) You are running vanilla instead of Forge
2) You put the mod file into the wrong /mods/ folder in the wrong location
3) You downloaded a jar from the wrong site, get forge from files.minecraftforge.net and C&B from curseforge

**Comment by KawaiiBoy63** [comment]
FIXED IT ALSO
