### ISSUE TITLE
getPickBlock() on a C&B block doesn't work server side

### ISSUE THREAD

**Issue by McJty** [ChiselsAndBits/Chisels-and-Bits#51]
This is a problem for my mod The One Probe which gets the block information using the recommended getPickBlock() way on the server side. When it does that it gets:

http://pastebin.com/ih5vGdzV

See https://github.com/McJty/TheOneProbe/issues/5

**Comment by McJty** [comment]
BTW, this is on 1.9.4

**Comment by AlgorithmX2** [comment]
Should be available on both 1.9 and 1.9.4 builds now.
