### ISSUE TITLE
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Chisels & Bits (chiselsandbits)

### ISSUE THREAD

**Issue by Jeremy5909** [ChiselsAndBits/Chisels-and-Bits#511]
### "The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Chisels & Bits (chiselsandbits)"

**Crash Report:**
https://anotepad.com/notes/qybk7kra

**For any bug reports please provide the following details as well,**
* _MC Version:_ **1.10.2 Forge**
* _C&B Version:_ **1.10.2-forge1.10.2-12.18.3.2185**
* _Do You have Optifine:_ **No**

**Comment by Jeremy5909** [comment]
Please someone?

**Comment by Aeltumn** [comment]
This is unfortunately a known issue for 1.10, this was also reported in #487. I commented the following there:
> Could you try removing the chiselsandbits_clipboard.cfg file from the /config/ directory?
> Otherwise try setting the configuration option persistCreativeClipboard to false.

**Comment by Jeremy5909** [comment]
Wow, Thanks Aeltumn!
