### ISSUE TITLE
Chiseling causes Textue block to go missing (purple & black)

### ISSUE THREAD

**Issue by MaDD26** [ChiselsAndBits/Chisels-and-Bits#513]
Everything is updated and I even removed all other mods except optifine with forge of course. Still causes it to do the same thing where the block texture goes missing and the whole block turns purpel and black squares of course. Can't use C&B at the moment for this patch and version.

For any bug reports please provide the following details as well,
* MC Version: 1.16.1
* C&B Version: 0.0.6 beta
* Do You have Optifine: yes

**Comment by sontersmctingle** [comment]
I had the same problem, removing Optifine from the mods folder fixed it.

**Comment by marchermans** [comment]
I can try to fix this but yeah this is a low priority at the moment.

**Comment by marchermans** [comment]
Fixed in the upcoming 1.0.11 or 1.1.5 releases
