### ISSUE TITLE
1.16.3 Failed to start up because ChiselAndBits 006-Beta license is missing...No Optifine

### ISSUE THREAD

**Issue by Neuron67** [ChiselsAndBits/Chisels-and-Bits#514]
Before continuing if you are reporting an issue, please ensure that all mods involved are updated to the latest version available, if your issue with with intermod compatibility such mixing C&B bits with other blocks make sure that MCMP is also updated. If your issue is a crash, be sure to include the crash log with your report.

[crash-2020-10-03_18.47.13-fml.txt](https://github.com/AlgorithmX2/Chisels-and-Bits/files/5322508/crash-2020-10-03_18.47.13-fml.txt)

For any bug reports please provide the following details as well,
* MC Version:
* C&B Version:
* Do You have Optifine:

**Comment by Aeltumn** [comment]
0.0.6 beta is specifically for Minecraft 1.16.1. Expect it to crash on 1.16.3. Can you please verify if this issue also occurs on 1.16.1?

**Comment by marchermans** [comment]
Yeah 1.16.1 only. See curseforge update will be working.

**Comment by MiloCookie** [comment]
> 
> 
> 0.0.6 beta is specifically for Minecraft 1.16.1. Expect it to crash on 1.16.3. Can you please verify if this issue also occurs on 1.16.1?

i think the problem is searching for 1.16.3 shows the mod witch is the problem
