### ISSUE TITLE
Chiseled Spruce Wood behaves like water

### ISSUE THREAD

**Issue by xJon** [ChiselsAndBits/Chisels-and-Bits#515]
Reported to my modpack over https://github.com/xJon/The-1.12.2-Pack/issues/532, and seems to be similar to https://github.com/AlgorithmX2/Chisels-and-Bits/issues/423:
_[Example gif](https://user-images.githubusercontent.com/8945347/95024588-a5190300-068c-11eb-8b3c-14b25726cbc9.gif)_

I did test this issue without other mods installed and could not reproduce it. Do you have any idea what's causing this?
Thank you!

> For any bug reports please provide the following details as well,
> * MC Version: `1.12.2`
> * C&B Version: `14.33`
> * MCMP Version: `2.5.3`
> * Do You have Optifine: `No`

**Comment by Aeltumn** [comment]
Unfortunately any issues for the 1.12 version of C&B won't be looked at anymore.
