### ISSUE TITLE
When a bit is placed on a block or when a bit is broken from a preexisting block the texture disappears and is non existent, all that is there is a purple and black checkered block.

### ISSUE THREAD

**Issue by EchoEarth** [ChiselsAndBits/Chisels-and-Bits#516]
Before continuing if you are reporting an issue, please ensure that all mods involved are updated to the latest version available, if your issue with with intermod compatibility such mixing C&B bits with other blocks make sure that MCMP is also updated. If your issue is a crash, be sure to include the crash log with your report.

For any bug reports please provide the following details as well,
* MC Version: 1.16.1
* C&B Version: Beta 0.0.6
* Do You have Optifine: yes

**Comment by Aeltumn** [comment]
Duplicate of #513.
