### ISSUE TITLE
[Feature Request][1.12] Larger Bits (1/2^3 instead of 1/16^3)

### ISSUE THREAD

**Issue by in-tension** [ChiselsAndBits/Chisels-and-Bits#520]
So while C&B is super cool, I was looking for something a little simpler. I would really love something like chisel and bits, but instead of a bit being 1/16^3 a bit would be 1/2^3. (Things like stairs or slabs would be easily replicated with this).

How hard would something like this be? Any chance there's a variable that could be changed from 16 to 2? Or is it more complicated?

Thanks

**Comment by Aeltumn** [comment]
There's an option to break/place in 1/2 grid-snapped bits on the radial menu, have you used that mode? However, the 1.12 version of the mod is not being worked on anymore.
