### ISSUE TITLE
When opening the game with the mod installed the mod fails.

### ISSUE THREAD

**Issue by IMakeRobits** [ChiselsAndBits/Chisels-and-Bits#525]
Before continuing if you are reporting an issue, please ensure that all mods involved are updated to the latest version available, if your issue with with intermod compatibility such mixing C&B bits with other blocks make sure that MCMP is also updated. If your issue is a crash, be sure to include the crash log with your report.

For any bug reports please provide the following details as well,
* MC Version:
* C&B Version:
* Do You have Optifine:

**Comment by Aeltumn** [comment]
Please properly fill in the bug report template.
