### ISSUE TITLE
[1.16.3] Some functions of the radial menu like connected material or plane doesn't work

### ISSUE THREAD

**Issue by sebibauklotz** [ChiselsAndBits/Chisels-and-Bits#528]
Before continuing if you are reporting an issue, please ensure that all mods involved are updated to the latest version available, if your issue with with intermod compatibility such mixing C&B bits with other blocks make sure that MCMP is also updated. If your issue is a crash, be sure to include the crash log with your report.

For any bug reports please provide the following details as well,
* MC Version: 1.16.3
* C&B Version: Alpha 0.2.2
* Do You have Optifine: No

**Comment by bigpotatosalad** [comment]
Hello, all my mods are updated to the latest version except MCMP. I *think* that MCMP is MCMultiPart right? MCMultiPart isn't updated to my version (1.16.1) so I don't have any clue what to do. Do you have any ideas on how to fix this?

MC Version: 1.16.1
C&B Version: 0.0.6-Beta
Yes, I have Optifine
