### ISSUE TITLE
breaks private

### ISSUE THREAD

**Issue by vadim908** [ChiselsAndBits/Chisels-and-Bits#529]
Hello, I wanted to see how your mod will work on the server and noticed one bug related to private, the chisel for some reason ignores private and breaks the blocks inside it, could you tell me how to fix this problem

**Comment by vadim908** [comment]
version 1.12.2

**Comment by vadim908** [comment]
plugin for private worldguard

**Comment by marchermans** [comment]
1.12.2 is sadly not supported anymore
Additionally private is not a forgemod.
