### ISSUE TITLE
Crash when opening C&B tab in creative inventory

### ISSUE THREAD

**Issue by Alex33212** [ChiselsAndBits/Chisels-and-Bits#530]
* MC Version: 1.16.1
* C&B Version: 0.0.6 BETA
* Do You have Optifine: No

With a 1.16.1 MultiMC instance that only has Forge 32.0.108 (last 1.16.1 release) and C&B installed, I crash to desktop the moment I open up the C&B tab in the creative inventory, similarly to issue #519 but without the use of Optifine.

Crashlog: https://docs.google.com/document/d/1IoNzbrbC9F5XWWbmSpvUoBU4XYSlbZAA6PGsy68f4aY/edit?usp=sharing

**Comment by marchermans** [comment]
Update to 1.16.3 it is fixed there.
Fix will **not** be backported at the moment due to the alpha state of the porting progress.

**Comment by Alex33212** [comment]
...Elsewhere it is explicitly stated that the current version is incompatible with 1.16.3.

**Comment by Aeltumn** [comment]
You are running an outdated version for 1.16.1, there are now versions for 1.16.3 that have this issue fixed, search for the 0.2.x alpha builds.
