### ISSUE TITLE
[1.16.3] Missing license info

### ISSUE THREAD

**Issue by boltyboi** [ChiselsAndBits/Chisels-and-Bits#531]
For any bug reports please provide the following details as well,
* MC Version: 1.16.3
* C&B Version: 0.0.6 Beta (from forge), latest one I can install
* Do You have Optifine: No

Here is a screencap: https://i.imgur.com/WLDHXz8.png
Missing License info in file Mod File: C:\.minecraft\mods\chiselsandbits-0.0.6-BETA.jar
Here's the crash report in full: https://pastebin.com/FarsqVN8
Thanks in advance!

**Comment by Aeltumn** [comment]
0.0.6 beta is for 1.16.1, use 0.2.0 or above on 1.16.3.
