### ISSUE TITLE
missing texture 

### ISSUE THREAD

**Issue by Likour** [ChiselsAndBits/Chisels-and-Bits#535]
i have an issue that i cant see the texture when i try and chisel and place the bits 

![Screenshot 2020-11-11 092356](https://user-images.githubusercontent.com/74308901/98823101-ac57cd00-23ff-11eb-8203-c7f8b4e1d81e.png)

![Screenshot 2020-11-11 092523](https://user-images.githubusercontent.com/74308901/98823244-d90be480-23ff-11eb-8d96-af224af332ce.png)

**Comment by marchermans** [comment]
Are you using optifine?

**Comment by kaaruchan** [comment]
> Are you using optifine?

same problem and yes I use optifine. Is that the problem?

**Comment by marchermans** [comment]
Yes
This is caused by optifine.
It is a known issue. Low priority due to optifine.
