### ISSUE TITLE
Glass cannot be chiseled

### ISSUE THREAD

**Issue by Haerar** [ChiselsAndBits/Chisels-and-Bits#536]
* MC Version: 1.16.1
* C&B Version: chiselsandbits-0.0.6-BETA.jar
* Do You have Optifine: Nope!

Unsure if this is a bug, oversight or intentional for technical reasons, but glass blocks and stained glass blocks (vanilla minecraft) are registering as "not a full block" (checked with magnifying glass) and as such cannot be chiseled - this is a shame as I've made some very nice stained glass windows in previous iterations of this mod!

**Comment by marchermans** [comment]
Update to 1.16,3.
This has already been fixed.

**Comment by nfcopier** [comment]
MC 1.16.5
C&B 0.3.4-RELEASE.jar
No Optifine

I'm encountering this same issue. Suggest reopening.
