### ISSUE TITLE
Radial Menu won't work

### ISSUE THREAD

**Issue by bigpotatosalad** [ChiselsAndBits/Chisels-and-Bits#537]
Before continuing if you are reporting an issue, please ensure that all mods involved are updated to the latest version available, if your issue with with intermod compatibility such mixing C&B bits with other blocks make sure that MCMP is also updated. If your issue is a crash, be sure to include the crash log with your report.

For any bug reports please provide the following details as well,
* MC Version: 1.16.1
* C&B Version: 0.0.6-BETA
* Do You have Optifine: Yes

**Comment by marchermans** [comment]
Not enough details

**Comment by bigpotatosalad** [comment]
> Not enough details

I'm trying to hold down alt to get to the menu but it won't show up on my screen. other features like the draw mode wont work. sorry for not giving enough details the first time around

**Comment by marchermans** [comment]
How do you think you need to press alt? Read the tooltip it says M for the menu.

**Comment by bigpotatosalad** [comment]
> How do you think you need to press alt? Read the tooltip it says M for the menu.
 
It won't let me open the menu either. nothing happens when I press M

**Comment by marchermans** [comment]
Can you record it?
Cause this works for me.

**Comment by bigpotatosalad** [comment]
> Can you record it?
> Cause this works for me.

I think I figured it out. It's a bit glitchy (at least on my computer) but it works. Thank you for helping me! I was about to give up but then you responded so I kept trying. Love this mod and I can't wait to use it in my future builds :)

**Comment by marchermans** [comment]
Okey
Can I close this then?

**Comment by bigpotatosalad** [comment]
> Okey
> Can I close this then?

Yeah. Again, thank you for helping
