### ISSUE TITLE
Performance concern 1.16.3-1.16.4

### ISSUE THREAD

**Issue by IchigoGames** [ChiselsAndBits/Chisels-and-Bits#539]
this is a reposting of some one who used this mod in my modpack
warning chisel an bits is a frame monster i did a tiny bit an the farme drop is bad you can see it as you pace the block.
to the point it was noticeable an getting worse ever block i was placing  from set 60fps down to 9 fps
this is all i did i would not expect anything really it probably less than 10 blocks
![2020-11-19_00 10 29](https://user-images.githubusercontent.com/11888162/99608645-f595b700-29d3-11eb-8e9b-6c0425f65191.png)

For any bug reports please provide the following details as well,
* MC Version:1.16.4
* C&B Version: chiselsandbits-0.2.2-ALPHA
* Do You have Optifine:no

**Comment by marchermans** [comment]
Please ensure that this happens with just c&b installed. Then upload a world with just c&b installed.

Also post your system specs.
I will see what I can do to improve it

**Comment by IchigoGames** [comment]
from user nvid 970ti  intel(r) core(tm) 17-4790 ram 16 gig system type 64 bit operating system x64 based processor

ill do what you said and post my spects in a min

**Comment by IchigoGames** [comment]
i can for sure say there is a big fps drop when taking out a block with chisel if change more then one block at a time you can drop from 120 to 8 fps

**Comment by IchigoGames** [comment]
just taking out 6-7 from one block droped me from 117 fps to 26 but it does recover

**Comment by IchigoGames** [comment]
![image](https://user-images.githubusercontent.com/11888162/99762846-0838ea80-2abf-11eb-975b-889a7a2445e4.png)
making this took me from 117fps to 93 not a huge change but i think if i keep going it will keep losing fps
my pc info https://pastebin.com/mMm976KZ

**Comment by marchermans** [comment]
Doe sit happen during normal play? Or during editing of the blocks?

If it is the later then I found the issue.

**Comment by IchigoGames** [comment]
when building but drops as you edit but it also effects overall fps by lowering like before i bult that i had 117 fps after it i had 93 still very much playable but thats with only that mod a good pc.

**Comment by wyrdlg** [comment]
Hi - I have the same problem. Started with MC 16.1 where ist first occured. Lag galore. It seems to me that the more altered objects you have the greater the lag. So I changed to MC 16.3 but it almost seems worce?

I made a new world - super flat, only glas, only C&B as a mod. There it seems to happen also, but not as pronounced... 
I've attached the world file here. When you go away from the chiseld block after a certain distance the lag is gone.
[C&B.zip](https://github.com/AlgorithmX2/Chisels-and-Bits/files/5610818/C.B.zip)

My System & Settings:
MC 16.3
Forge 34.1.40
chiselsandbits-0.2.2-ALPHA
Java 1.8.0_271
Dual Intel Xeon 2,5 Ghz
32 GB  (8 GB allocated to the game)

**Comment by marchermans** [comment]
@wyrdlg good that gives me something to work with.

Quick question: Is it a continuous decrease in performance: aka more blocks equals lower fps?

Or is it a spoke on placement that is the issue? Like when you edit a chiseled block, the more chiseled blocks around the higher and the longer the lag spikes?

**Comment by IchigoGames** [comment]
i know you asking him but for me it was both it happen as you where placing large spikes of fps lag that then would  go back to normal and overall more bits=less fps

**Comment by wyrdlg** [comment]
Hi. Yes my impression, following the test in that world, is that the number of blocks seems relevant. From there on the lag is constant. 
Like the first 1,2 or 3 blocks it is fine. But with a bunch of them present... Sure the editing suffers as well. But to me it clearly is the number. Just like ichiogames says. 
I’ll try to find a threshold when I encounter that. And at what distance it vanishes.

**Comment by wyrdlg** [comment]
Gave it a quick test in my simple "glass world". Noticable is the lag from the third block on. You need to stand next to the block (though i had the impression from my playing world that it extends?). Furthermore the blocks complexity does not matter - one bit is enough to produce the same lag as an completely altered block.

**Comment by marchermans** [comment]
@wyrdlg @IchigoGames Could you test the version packed into the attached zip?
[chiselsandbits-0.2.3-TEST.zip](https://github.com/AlgorithmX2/Chisels-and-Bits/files/5612888/chiselsandbits-0.2.3-TEST.zip)

I ran my test with the world that was included by @wyrdlg and in this version I did not notice any performance issues.
Looking at the structure I was able to achieve a steady 932 FPS teleporting a 1000 blocks away I was able to achieve the same performance give a frame here or there.
Granted I have a powerfull workstation backing me up. But if there was a noticeable performance drop I would have seen it there.

Could you please verify that it now works?

**Comment by IchigoGames** [comment]
only minor to no lag when editing removing and placing bits
![image](https://user-images.githubusercontent.com/11888162/100558039-28f90100-3272-11eb-8c92-2fba02b4e482.png) and after making this my fps did not go down any. edit ops forgot i had my other monitor connected

**Comment by IchigoGames** [comment]
definitely an improvement from last test

**Comment by wyrdlg** [comment]
Hy @OrionDevelopment. a Huge improvment. Having the weakest PC of us three I can still see some effects but quite less.
Thanks by the way for reviving! C&B Love that Mod!
And thanks @IchigoGames for starting this case.
PS in my heavily modded real world it helps too. Maybe still some leeway for us weakys ;-D
