### ISSUE TITLE
Crash while chiseling 

### ISSUE THREAD

**Issue by Crazy-KSK** [ChiselsAndBits/Chisels-and-Bits#54]
This crash happened seemingly randomly after a while of adding some bits from a "chisel" mod block to a vanilla block 
http://pastebin.com/hsX6dgTx

**Comment by AlgorithmX2** [comment]
I believe this should be fixed in the newest builds, this was caused by the server and client threads interfering.

Builds 8.10, 9.20 and 10.6 should resolve the issue.
