### ISSUE TITLE
Not Up to Date

### ISSUE THREAD

**Issue by FeelsWasTaken** [ChiselsAndBits/Chisels-and-Bits#540]
Before continuing if you are reporting an issue, please ensure that all mods involved are updated to the latest version available, if your issue with with intermod compatibility such mixing C&B bits with other blocks make sure that MCMP is also updated. If your issue is a crash, be sure to include the crash log with your report.

For any bug reports please provide the following details as well,
* MC Version: 1.16.4
* C&B Version: 14.33
* Do You have Optifine: Yes

When I try to use the mod forge says the mod is for an older version of forge. Is this an issue or am I just going to need an older version of forge to run C&B?

**Comment by oliandcharis** [comment]
MC Version: 1.16.3 and 1.16.4
C&B Version: tried both beta and alpha 1.16 versions
Do You have Optifine: Yes

i've tried a few versions of forge now and am still getting the error that a licence isn't in the mod, or that i require an earlier version of forge, same as above

**Comment by marchermans** [comment]
I do not specify a minimal requirement for the forge version.
Screenshots or logs would be required to track this down.

**Comment by ArchyTheArc** [comment]
MC Version: 1.16.4
C&B Version: 00.4-ALPHA to 0.0.6 BETA
Do You have Optifine: No (as of right now)

I'm getting said error message too. it happens with forge version 35+ which seems to be every 1.16.4 forge version (only fully c checked with 0.0.6 BETA)
![image](https://user-images.githubusercontent.com/23485234/100674545-363eea00-335d-11eb-8543-5be5334db27f.png)
[latest.log](https://github.com/AlgorithmX2/Chisels-and-Bits/files/5619140/latest.log)

**Comment by HyperHamster** [comment]
You need to edit your `mods.toml` file to include a `license` value like so:
```
modLoader="javafml"
loaderVersion="[28,)"
license="Unlicense" # <-- Like this
[[mods]] #mandatory
modId="chiselsandbits"
version="${file.jarVersion}"
displayName="Chisels & bits"
authors="OrionOnline, LDTTeam, AlgorithmX2 "
description='''
a mod about Sculpting, Decorating and Aesthetics.

Ported to 1.16.2 by the LDTTeam.
'''

```
Forge 1.16.x requires this; Leaving it out will result in a fatal error.

**Comment by HyperHamster** [comment]
For those who don't want to wait for a fix, I've patched the release jar for 0.0.6-BETA and you may download it [here](https://github.com/AlgorithmX2/Chisels-and-Bits/files/5620304/chiselsandbits-0.0.6-BETA.zip).

**Comment by marchermans** [comment]
Use the existing alpha 0.2.2 jar!

**Comment by marchermans** [comment]
https://www.curseforge.com/minecraft/mc-mods/chisels-bits/download/3093342

**Comment by HyperHamster** [comment]
Completely missed alpha 0.2.0-0.2.2 on the CurseForge page, my bad. They sure do their best to hide alpha releases, even if you go to the files tab you still need to click `View All` before they'll show up.

**Comment by marchermans** [comment]
Yeah they are alphas cause i am still in the process of porting features and they might contain bugs.

There is a project here in this repo that handles the release tracking. Once I have fixed all high and medium prio bugs I will make a new beta.
