### ISSUE TITLE
chisels and bits 1.6.4 IS BROKEN

### ISSUE THREAD

**Issue by Rockstar87** [ChiselsAndBits/Chisels-and-Bits#541]
mc version 1.6.4
optifine installed

chisels and bit used to be amazing, now its broken

replacing an bit is not working - only placing
placing an positive chisel design does not work - only replacing works
chisel design no longer remember its position, instead it changes directional of the block you are replacing
very big lag and preformence isues
chiseling on the bottom of a block sometimes removes a layer on top
connected materials is not working
connected pain is not working
places bit trough the block you are clicking on sometimes
undo and redo are not working

**Comment by Rockstar87** [comment]
replacing bits is not working, it places the intire block
removing 1 kind of bit from a block is not working, it removes the whole block

**Comment by Rockstar87** [comment]
Chiseled glowstone no longer gives a lightsource

All modes exept draw mode does not work with replacing bits, only placing and removing

The place function on the mirror and negative design also dont work, only replacing

 lag spikes when placing vanilla blocks next to chisel block

Small isue: when making an design of an block, the game trows the emty one out of your inventory, and a new written one into your inventory,  often at another spot

**Comment by marchermans** [comment]
Optifine is officially not supported.
Additionally this is an ALPHA build it is widely known to not be feature complete and some functions might or might not work.

Please be patient with me while I fix bugs, and update the missing features to the new MC version.
I do this in my free time. So it takes a bit.
