### ISSUE TITLE
Placing Design alters the result - no exact copy

### ISSUE THREAD

**Issue by wyrdlg** [ChiselsAndBits/Chisels-and-Bits#542]
For any bug reports please provide the following details as well,
* MC Version: 16.3.
* C&B Version: chiselsandbits-0.2.3-TEST
* Do You have Optifine: No

Hi there!
So if I copy a design (the blue one) with the block 1 (upper "slab" Oak planks and underneath some dark oak log) and place it on the new block 2, it comes out altered... The dark oak is somehow turned... Hard to say if this happened with the plank?!

![C B Design](https://user-images.githubusercontent.com/11816286/100637359-1397db80-3333-11eb-80e1-d3295090bca7.PNG)

**Comment by marchermans** [comment]
It happens with the plank too.

It is because the bits are blockstate specific it keeps the rotation of the original. But it rotates the schematic.

I will get to it eventually but this is a lower priority at the moment.
