### ISSUE TITLE
Chisels and Bits causes extreme lag spikes and occasionally crashes on breaking blocks

### ISSUE THREAD

**Issue by suburbGira** [ChiselsAndBits/Chisels-and-Bits#543]
Before continuing if you are reporting an issue, please ensure that all mods involved are updated to the latest version available, if your issue with with intermod compatibility such mixing C&B bits with other blocks make sure that MCMP is also updated. If your issue is a crash, be sure to include the crash log with your report.

For any bug reports please provide the following details as well,
* MC Version: 1.16.3
* C&B Version: 0.2.4
* Do You have Optifine: Yes

After building using Chisels and Bits bits, Minecraft seems to get extreme lag spikes when I break any block. In addition, breaking Chisels and Bits blocks sometimes causes a crash, so I can't even remove the blocks affecting the framerate without having to restart Minecraft many times.

[crash-2020-12-03_11.35.16-client.txt](https://github.com/AlgorithmX2/Chisels-and-Bits/files/5635774/crash-2020-12-03_11.35.16-client.txt)

**Comment by marchermans** [comment]
System parameters and a test world with just C&B are needed to test this.
I spend weeks with several people tracking this down, and we had it fixed.

So if you could it would be nice to get a proper test environment

**Comment by suburbGira** [comment]
So, to test fully, I need to remove all mods except Chisels and Bits and test in a separate world? Should I keep Optifine or remove it? And what do you mean by system parameters? My graphics card and other specifications?

**Comment by marchermans** [comment]
Yes remove optifine for sure. Optifine is not supported anyway. REmove all mods, and repeat the process with which you detected the spikes.

Also yes system parameters are your graphics card cpu etc.

**Comment by pseudosu** [comment]
I'm having this issue as well with the Enigmatica 6 modpack. I installed OptiFIne and there was about 1 second of hitching from breaking and placing blocks while there was also Chisel & Bits blocks near me. After removing OptiFine the lag was gone. So it's definitely just an issue with OptiFine, oddly, never had this issue in the past with these two mods, but hey, things change.


Update: The lag only happens when I break or place a block within a certain radius of a chiseled block. Approx. 8 blocks.
Update 2: Seems like the lag happens you place or break a block _in_ or _bordering_ a chunk that has a chiseled block in it.
Update 3: The more chiseled blocks there are in a chunk, the more it lags when you break or place a block. If there is only one chiseled block, it does not lag at all.

My Specs:

Ryzen 7 2700x
32GB RAM
RTX 2080
Samsung QVO SSD

**Comment by marchermans** [comment]
@pseudosu Enigmatica 6 runs with an outdated version of C&B where this was indeed a bug caused by collision shapes being calculated too often.

You will need to update to 0.2.4-RELEASE to have that fixed.

**Comment by marchermans** [comment]
@suburbGira I fixed the crash in 0.2.5.
I still need more information with regards to the spikes.

**Comment by airfaded** [comment]
Valhelsia 3 also has massive lag spikes when using C&B. Updating to the newest release of C&B helped a little but not much.

**Comment by marchermans** [comment]
@airfaded could you try with just c&b?

**Comment by airfaded** [comment]
Tested with just C&B, the lag spikes while just walking around with a lot of Bits are almost gone, but breaking blocks and bits around it still causes lag spikes.

**Comment by marchermans** [comment]
Is it just breaking? Or modification in general?

**Comment by airfaded** [comment]
Seems like it's just breaking things that are around it

**Comment by marchermans** [comment]
Okey interesting

**Comment by marchermans** [comment]
@airfaded So i tried to reproduce the lag spikes and I was not able to.
Ran the game normally with just a sampler and C&B. Tried catching lagspikes of more then 100ms and did not find anything that is caused by C&B.

**Comment by Parthurax** [comment]
Yep Mod isnt working. Donwloaded the newest version. Chiseld a lot of blocks and as soon i braek blocks it start lagging.

Just in case this is a thing -> I9-9900.

Tested in a real testing envirment with mods....
1.16.3 // Fogre 34.4.40 // CB 2.8
---
Tested with only CB, not that worse but noticeable. i guess it just needs more chiseled blocks

**Comment by marchermans** [comment]
@Parthurax Can you send me a test world?
Potentially even a recording of how you reproduce this?

I have not been able to reproduce this with my system and I have been working diligently to get this to work, and reduce the strain the mod has on a system.
If i run any profiler againt the current implementation, it does not even appear anymore. So it is something that happens in a particular case, or in a particular environment, which i either have not found. Or have no access to.

We test every version on an internal test server, but even there we ware not able to reproduce this.

**Comment by papaworld** [comment]
MC 1.16.3
FML 34.1.42
C&B 0.2.2-alpha > 0.2.8-release
OptiFine/OptiForge NO

Hi Ya'll... just wanted to throw my 2cents in. NO opti-stuff. With 022alpha the FPS decreased little-by-little for each C&B item placed. After placing 16 items the FPS was below 5, but would go back to normal FPS if I moved out of that chunk. With the 028-release, it all cleared up and works great with 28 items placed!!! Hope this is helpful. ThanX for a great mod... reaching back to even 1.12.2.
