### ISSUE TITLE
Chiseled Block glithes when I put in the floor

### ISSUE THREAD

**Issue by Rangelito1** [ChiselsAndBits/Chisels-and-Bits#544]
First of all, sorry for my poor english, i will try explain this in english but my first language is spanish

Im using a modpack for minecraft 1.12.2, and chisel and bits was working well, but two weeks later I introduce some mods more and the isuee appear, my modpack include the following mods:
    | LCHIJA | minecraft            | 1.12.2                | minecraft.jar                                    | None                                     |
	| LCHIJA | mcp                  | 9.42                  | minecraft.jar                                    | None                                     |
	| LCHIJA | FML                  | 8.0.99.99             | custom.jar                                       | None                                     |
	| LCHIJA | forge                | 14.23.5.2854          | custom.jar                                       | None                                     |
	| LCHIJA | creativecoredummy    | 1.0.0                 | minecraft.jar                                    | None                                     |
	| LCHIJA | otgcore              | 1.12.2 - v8.3         | minecraft.jar                                    | None                                     |
	| LCHIJA | foamfixcore          | 7.7.4                 | minecraft.jar                                    | None                                     |
	| LCHIJA | futuremccore         | 0.1.12                | minecraft.jar                                    | None                                     |
	| LCHIJA | securitycraft        | v1.8.15               | [1.12.2] SecurityCraft v1.8.15.jar               | None                                     |
	| LCHIJA | tombstone            | 3.6.5                 | tombstone-3.6.5-1.12.2.jar                       | None                                     |
	| LCHIJA | advanced-fishing     | 1.3.3                 | Advanced-Fishing-1.12.2-1.3.3.jar                | None                                     |
	| LCHIJA | applecore            | 3.4.0                 | AppleCore-mc1.12.2-3.4.0.jar                     | None                                     |
	| LCHIJA | jei                  | 4.15.0.293            | jei_1.12.2-4.15.0.293.jar                        | None                                     |
	| LCHIJA | appleskin            | 1.0.14                | AppleSkin-mc1.12-1.0.14.jar                      | None                                     |
	| LCHIJA | baubles              | 1.5.2                 | Baubles-1.12-1.5.2.jar                           | None                                     |
	| LCHIJA | astralsorcery        | 1.10.20               | astralsorcery-1.12.2-1.10.20.jar                 | a0f0b759d895c15ceb3e3bcb5f3c2db7c582edf0 |
	| LCHIJA | biomesoplenty        | 7.0.1.2444            | BiomesOPlenty-1.12.2-7.0.1.2444-universal.jar    | None                                     |
	| LCHIJA | bloodmoon            | 1.5.3                 | Bloodmoon-MC1.12.2-1.5.3.jar                     | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| LCHIJA | botania              | r1.10-363             | Botania+r1.10-363.jar                            | None                                     |
	| LCHIJA | chesttransporter     | 2.8.8                 | ChestTransporter-1.12.2-2.8.8.jar                | None                                     |
	| LCHIJA | chickens             | 6.0.4                 | chickens-6.0.4.jar                               | None                                     |
	| LCHIJA | chisel               | MC1.12.2-1.0.1.44     | Chisel-MC1.12.2-1.0.1.44.jar                     | None                                     |
	| LCHIJA | chiselsandbits       | 14.33                 | chiselsandbits-14.33.jar                         | None                                     |
	| LCHIJA | chococraft           | 0.9.8.0               | chococraft_1.12.2-0.9.8.0.jar                    | None                                     |
	| LCHIJA | morpheus             | 1.12.2-3.5.106        | Morpheus-1.12.2-3.5.106.jar                      | None                                     |
	| LCHIJA | comforts             | 1.4.1.2               | comforts-1.12.2-1.4.1.2.jar                      | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| LCHIJA | opframe              | 1.4.0                 | OnlinePicFrame_v1.4.32_mc1.12.2.jar              | None                                     |
	| LCHIJA | playerrevive         | 1.0                   | PlayerRevive_v1.2.28_mc1.12.2.jar                | None                                     |
	| LCHIJA | creativecore         | 1.9.9                 | CreativeCore_v1.9.87_mc1.12.2.jar                | None                                     |
	| LCHIJA | customnpcs           | 1.12                  | CustomNPCs_1.12.2-(01Oct19).jar                  | None                                     |
	| LCHIJA | props                | 2.6.3                 | Decocraft-2.6.3_1.12.2.jar                       | None                                     |
	| LCHIJA | demonicintervention  | 0.3                   | demonicintervention-mc1.12.2-v0.3.jar            | None                                     |
	| LCHIJA | dynamictrees         | 1.12.2-0.9.6          | DynamicTrees-1.12.2-0.9.6.jar                    | None                                     |
	| LCHIJA | elevatorid           | 1.3.14                | ElevatorMod-1.12.2-1.3.14.jar                    | None                                     |
	| LCHIJA | mclib                | 1.0.4                 | mclib-1.0.4-1.12.2.jar                           | None                                     |
	| LCHIJA | emoticons            | 0.3.2                 | emoticons-0.3.2-1.12.2-dist.jar                  | None                                     |
	| LCHIJA | explorercraft        | 2.2.14                | Explorercraft-2.2.14.jar                         | None                                     |
	| LCHIJA | extrautils2          | 1.0                   | extrautils2-1.12-1.9.9.jar                       | None                                     |
	| LCHIJA | eyesinthedarkness    | 0.1.0                 | EyesInTheDarkness-0.1.0.jar                      | None                                     |
	| LCHIJA | openterraingenerator | v8.3                  | OpenTerrainGenerator-1.12.2 - v8.3.jar           | None                                     |
	| LCHIJA | farfromhome          | 1.0                   | Far_From_Home-1.12.2-5.0.jar                     | None                                     |
	| LCHIJA | fastbench            | 1.7.3                 | FastWorkbench-1.12.2-1.7.3.jar                   | None                                     |
	| LCHIJA | fencejumper          | 1.0.5                 | fencejumper-1.12-1.0.5.jar                       | None                                     |
	| LCHIJA | ferdinandsflowers    | 1.10.4.1              | Ferdinand's Flowers-1.12.x-1.10.4.1.jar          | None                                     |
	| LCHIJA | foamfix              | 0.10.10-1.12.2        | foamfix-0.10.10-1.12.2.jar                       | None                                     |
	| LCHIJA | foamflower           | 1.12.2-1.0.0.0-beta1  | foamflower-1.12.2-1.0.0.0-beta1.jar              | None                                     |
	| LCHIJA | forgelin             | 1.8.4                 | Forgelin-1.8.4.jar                               | None                                     |
	| LCHIJA | llibrary             | 1.7.19                | llibrary-1.7.19-1.12.2.jar                       | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCHIJA | fossil               | 8.0.4                 | fossilsarcheology-8.0.4.jar                      | None                                     |
	| LCHIJA | cfm                  | 6.3.1                 | furniture-6.3.1-1.12.2.jar                       | None                                     |
	| LCHIJA | minecraftfuture      | 0.1.13                | future-mc-0.1.13.jar                             | None                                     |
	| LCHIJA | gottschcore          | 1.13.1                | GottschCore-mc1.12.2-f14.23.5.2768-v1.13.1.jar   | None                                     |
	| LCHIJA | hatchery             | 2.2.2                 | hatchery-1.12.2-2.2.2.jar                        | None                                     |
	| LCHIJA | waila                | 1.8.26                | Hwyla-1.8.26-B41_1.12.2.jar                      | None                                     |
	| LCHIJA | iceandfire           | 1.9.1                 | iceandfire-1.9.1-1.12.2.jar                      | None                                     |
	| LCHIJA | ichunutil            | 7.2.2                 | iChunUtil-1.12.2-7.2.2.jar                       | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA | mcjtylib_ng          | 3.5.4                 | mcjtylib-1.12-3.5.4.jar                          | None                                     |
	| LCHIJA | immcraft             | 1.6.0                 | immcraft-1.12-1.6.0.jar                          | None                                     |
	| LCHIJA | infernalmobs         | 1.7.6                 | InfernalMobs-1.12.2.jar                          | None                                     |
	| LCHIJA | ironchest            | 1.12.2-7.0.67.844     | ironchest-1.12.2-7.0.72.847.jar                  | None                                     |
	| LCHIJA | jjmeteor             | 1.0.10                | JJ+Meteor+1.12-1.12.2-v1.0.10.jar                | None                                     |
	| LCHIJA | journeymap           | 1.12.2-5.5.6          | journeymap-1.12.2-5.5.6.jar                      | None                                     |
	| LCHIJA | leatherworks         | 1.78.0                | LeatherWorks-1.12-1.78.0.42.jar                  | None                                     |
	| LCHIJA | magma_monsters       | 0.3.0                 | MagmaMonsters-0.3.0.jar                          | None                                     |
	| LCHIJA | magneticraft         | 2.7.0                 | Magneticraft_1.12-2.8.3-dev.jar                  | None                                     |
	| LCHIJA | malisiscore          | 1.12.2-6.5.1-SNAPSHOT | malisiscore-1.12.2-6.5.1.jar                     | None                                     |
	| LCHIJA | malisisdoors         | 1.12.2-7.3.0          | malisisdoors-1.12.2-7.3.0.jar                    | None                                     |
	| LCHIJA | mca                  | 6.0.1                 | MCA-1.12.2-6.0.1-universal.jar                   | None                                     |
	| LCHIJA | mcef                 | 0.9                   | Minecraft-Chromium-Embedded-Framework-1.12.2.jar | None                                     |
	| LCHIJA | modernlamps          | 1.0.3                 | ModernLights-1.0.3_1.12.jar                      | None                                     |
	| LCHIJA | morechickens         | 3.1.0                 | morechickens-1.12.2-3.1.0.jar                    | None                                     |
	| LCHIJA | mowziesmobs          | 1.5.8                 | mowziesmobs-1.5.8.jar                            | None                                     |
	| LCHIJA | offlineskins         | 1.12.2-v6             | OfflineSkins-1.12.2-v6.jar                       | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
	| LCHIJA | harvestcraft         | 1.12.2zb              | Pam's+HarvestCraft+1.12.2zf.jar                  | None                                     |
	| LCHIJA | placebo              | 1.6.0                 | Placebo-1.12.2-1.6.0.jar                         | None                                     |
	| LCHIJA | playerskins          | 1.0.4                 | playerskin-1.12.2-1.0.5.jar                      | None                                     |
	| LCHIJA | progressivebosses    | 1.5.4                 | ProgressiveBosses-1.5.4-mc1.12.x.jar             | None                                     |
	| LCHIJA | railcraft            | 12.0.0                | railcraft-12.0.0.jar                             | a0c255ac501b2749537d5824bb0f0588bf0320fa |
	| LCHIJA | randomenchantments   | @VERSION@             | randomenchants-0.1.5.jar                         | None                                     |
	| LCHIJA | reap                 | 1.5.3                 | reap-1.5.3.jar                                   | None                                     |
	| LCHIJA | rustic               | 1.1.6                 | rustic-1.1.6.jar                                 | None                                     |
	| LCHIJA | spartanshields       | 1.5.4                 | SpartanShields-1.12.2-1.5.4.jar                  | None                                     |
	| LCHIJA | stupidthings         | 1.1.6                 | Stupid+Things-1.12.2-1.1.6.jar                   | None                                     |
	| LCHIJA | cactusmod            | 1.3.2                 | The-Cactus-Mod-1.3.2.jar                         | None                                     |
	| LCHIJA | toolbelt             | 1.9.12                | ToolBelt-1.12.2-1.9.12.jar                       | None                                     |
	| LCHIJA | travellersbackpack   | 1.0.24.24             | TravellersBackpack-1.12.2-1.0.24.24.jar          | None                                     |
	| LCHIJA | traverse             | 1.6.0                 | Traverse-1.12.2-1.6.0-69.jar                     | None                                     |
	| LCHIJA | treasure2            | 1.7.0                 | Treasure2-mc1.12.2-f14.23.5.2768-v1.7.0.jar      | None                                     |
	| LCHIJA | of                   | 0.13.1                | Useful Interior - 0.13.1 [1.12.2].jar            | None                                     |
	| LCHIJA | variedcommodities    | 1.12.2                | VariedCommodities_1.12.2(21nov19).jar            | None                                     |
	| LCHIJA | vending              | 1.12.2-3.0.1.2        | vending-1.12.2-3.0.1.2.jar                       | None                                     |
	| LCHIJA | webdisplays          | 1.0                   | Web-Displays-Mod-1.12.2.jar                      | None                                     |
	| UD     | mclib_core           | 1.0.4                 | minecraft.jar                                    | None                                     |
* MC Version: 1.12.2

The mods creating conflict maybe are chickens, morechickens, hathery, ironchest o demonic intervention, because i put later

* C&B Version: chiselsandbits-14.33
* Do You have Optifine: Yes
https://streamable.com/hfhrms

**Comment by marchermans** [comment]
At the moment 1.12.2 does not receive any updates anymore and is, with th exception for game breaking world corrupting massive bugs not supported any more I am so sorry.
