### ISSUE TITLE
Sorry to bother you again. It seems when you chisel in creative, you don't get the bits. Can you make it so when you chisel bits, they go into your bit bag? MC Version: 1.16.4, C&B Version: 0.2.8, Do you have Optifine: Yes

### ISSUE THREAD

**Issue by TheGetGoodGit2211** [ChiselsAndBits/Chisels-and-Bits#548]
Before continuing if you are reporting an issue, please ensure that all mods involved are updated to the latest version available, if your issue with with intermod compatibility such mixing C&B bits with other blocks make sure that MCMP is also updated. If your issue is a crash, be sure to include the crash log with your report.

For any bug reports please provide the following details as well,
* MC Version:
* C&B Version:
* Do You have Optifine:

**Comment by marchermans** [comment]
Why?

You have a creative menu.
I see no reason why you would need this functionality.
