### ISSUE TITLE
Bit Placement Grid Bug

### ISSUE THREAD

**Issue by Dude20121** [ChiselsAndBits/Chisels-and-Bits#549]
* MC Version: 1.16.4
* C&B Version: 0.2.8
* Do You have Optifine: Yes

My friend and I were using Chisels & Bits on a server (with other mods), and everything worked fine, but after an hour or so, for whatever reason, we were suddenly able to place bits correctly. Now placed bits always place one space off of where clicked (as if the grid is expanded), and trying to click one space back to compensate causes the bit being placed to just get 'absorbed' into the block, making it almost impossible to correctly place bits back into a block. After restarting the server, the issue still persists, and even carries over to singleplayer worlds. I wasn't sure if this was related to the off-grid features, so I bound keys to "Place Off Grid" and "Placement" in the controls menu to test. This didn't fix the issue, but these binds also don't seem to do anything at all.

[Example image](https://imgur.com/a/xDrPjsS)

**Comment by marchermans** [comment]
Can you show me this in some screenshot?

**Comment by Dude20121** [comment]
I attached an Imgur link (https://imgur.com/a/xDrPjsS) at the bottom of the post

**Comment by marchermans** [comment]
Yeah but that image does not show me anything....
Really.

**Comment by Dude20121** [comment]
Here's a video: https://drive.google.com/file/d/1LwTn9N3o9p8WtRfwhvtojnB5lDVkiGsc/view?usp=sharing

**Comment by marchermans** [comment]
Okey thanks.

**Comment by oliverRosa** [comment]
I am also having the same or similar issue with having other mods installed and using the latest version of chisel and bits and version 1.16.4 of Minecraft. When I go to place the chisels they seem to go elsewhere rather than where I want to place them. I also have Optifine installed.

**Comment by Pygorable** [comment]
I am experiencing the same problems, both with and without optifine

**Comment by marchermans** [comment]
It is known.
And locally already fixed, which you can see on the Awaiting Commit label that this issue is marked with.
It is currently undergoing testing.

**Comment by desagas** [comment]
![2020-12-17_19 58 19](https://user-images.githubusercontent.com/8404632/102569241-516e6100-40a2-11eb-9308-0db3c4cb5d76.png)
So, in this image, it both extended it to the left by one pixel, and entire backwards all 16 pixels, when it should only be 1 pixel. This is with the draw region function enabled.

**Comment by desagas** [comment]
![2020-12-17_20 22 48](https://user-images.githubusercontent.com/8404632/102571148-20902b00-40a6-11eb-9084-e096898f3ea8.png)
In this one, still using drawn region, this is what happens. It does not draw where it is meant to, and the connected material feature places blocks one out from where it should, one pixel closer to the camera.

**Comment by desagas** [comment]
Another quick note: while right clicking to draw region does not work properly, the left click to draw away a region works fine.
