### ISSUE TITLE
2 Pick block issues 1.16.4 / 0.2.8 RELEASE (latest version)

### ISSUE THREAD

**Issue by sp2934598w3048** [ChiselsAndBits/Chisels-and-Bits#551]
If I pick block a chiseled block, it will put one in my hotbar normally but with no texture; it is invisible (No texture even when dropped), As well as while in creative, it will only place 1 before disappearing from your inventory (Like having 1 block in survival but in creative).

* MC Version: 1.16.4
* C&B Version: Latest version (0.2.8 RELEASE)
* Do You have Optifine: Yes

**Comment by marchermans** [comment]
Are you in creative?
Or survival?

**Comment by sp2934598w3048** [comment]
Creative
