### ISSUE TITLE
Block.chiselsandbits.chisel_station seem like not craftable on survival mode

### ISSUE THREAD

**Issue by Eadwine-15** [ChiselsAndBits/Chisels-and-Bits#552]
Hi, I notice the Chisel bits station seem not craftable on survival mode, I only just recently exploring towards this mod which is why I just found out this problem. Although it did appear on the grid when press "E" but it non-clickable. 

Thanks.

For any bug reports please provide the following details as well,
* MC Version: 1.16.3 - Forge ver. 34.1.42
* C&B Version: chiselsandbits-0.2.2-ALPHA.jar
* Do You have Optifine: Yes

**Comment by marchermans** [comment]
Fixed in the upcoming 1.0.11 or 1.1.5 releases
