### ISSUE TITLE
I can’t place bits properly, they leave a space between them or jump to the next block over. It is like I can only select a bit as though I am destroying but I’m trying to place them and it won’t let me.

### ISSUE THREAD

**Issue by chuckthechipmonk** [ChiselsAndBits/Chisels-and-Bits#553]
Before continuing if you are reporting an issue, please ensure that all mods involved are updated to the latest version available, if your issue with with intermod compatibility such mixing C&B bits with other blocks make sure that MCMP is also updated. If your issue is a crash, be sure to include the crash log with your report.

For any bug reports please provide the following details as well,
* MC Version:
* C&B Version:
* Do You have Optifine:

**Comment by marchermans** [comment]
Duplicate: #549
