### ISSUE TITLE
Positive Design Disappears After Use

### ISSUE THREAD

**Issue by bcrotty** [ChiselsAndBits/Chisels-and-Bits#554]
* MC Version: 1.16.4
* C&B Version: 0.2.8-RELEASE
* Do You have Optifine: No

When I use a positive design in placement mode (didn't check if this affects other modes as well), the design disappears the first time I use it to place something. Shouldn't it stay in my inventory?

**Comment by Dhvagra** [comment]
In the 'placement' mode it indeed disappears, in the 'impose' and 'additive' modes it does not. I haven't used 'replace' yet.
