### ISSUE TITLE
Mirror Chisel Design does not copy

### ISSUE THREAD

**Issue by ostrichlittledungeon** [ChiselsAndBits/Chisels-and-Bits#555]
* MC Version: 1.16.4
* C&B Version: Latest (0.2.8)
* Do You have Optifine: Yes

I am having issues copying a written mirror chisel design. Neither a crafting table nor my 4x4 crafting space is usable to this end, either in survival or creative.

![Screen Shot 2020-12-11 at 5 15 04 PM](https://user-images.githubusercontent.com/13596613/101960058-90993f80-3bd4-11eb-869e-45cdc5e7b929.png)

I am also having the already mentioned problem where placing bits skips one spot (this happens with bits and planes, but not with lines).

**Comment by ostrichlittledungeon** [comment]
The mirror design issues date back to the alpha builds of the 1.16 revamp of the mod. The skipping one spot issue is only one incarnation old, however, and does not exist in earlier versions of the 1.16.4 patch. It seems to be a consequence of however you reworked the grid for the most recent bugfix.

**Comment by marchermans** [comment]
After researching the crafting mechanics there is no way to actually copy the prints.
You can just reuse a print, or click on it with an entire stack to make multiples of the same print.

**Comment by ostrichlittledungeon** [comment]
No... the issue was that I was unable to craft a mirror chisel design AT ALL. Copy as in copy from a positive design to a mirror design, not copy as in produce multiple. I should have specified this, apologies. Hope you see this message.

**Comment by ostrichlittledungeon** [comment]
@OrionDevelopment pinging you to make sure you read.
