### ISSUE TITLE
Bits are placed strangely

### ISSUE THREAD

**Issue by theoretischer** [ChiselsAndBits/Chisels-and-Bits#556]
Hi, I'm playing C&B on my server (1.16.4) with friends, and since the last update, you can't place the Bits where you like to place them. When I place a single bit its floating 1 pixel in the air
![grafik](https://user-images.githubusercontent.com/75859777/101987173-bc7afa80-3c92-11eb-9b3c-35840ee7aedc.png)
When I try to use the draw region its drawing 2 pixels up 
![grafik](https://user-images.githubusercontent.com/75859777/101987220-fea43c00-3c92-11eb-9af2-65abfeb1383b.png)
or it's just drawing on the edge of the block
![grafik](https://user-images.githubusercontent.com/75859777/101987238-2398af00-3c93-11eb-9a59-cff2d2bb0888.png)
I'm using Optifine,
its the newest update

**Comment by theoretischer** [comment]
Sorry for my bad english ¯\_(ツ)_/¯

**Comment by ostrichlittledungeon** [comment]
Hey, just letting you know. There are already three tickets talking about this issue and the dev is well aware of it by now. In the meantime, if you want to keep using the mod, placing bits in lines works as expected.

**Comment by marchermans** [comment]
See #549
