### ISSUE TITLE
Block Placement Glitch

### ISSUE THREAD

**Issue by iGhoztman** [ChiselsAndBits/Chisels-and-Bits#557]
When placing bits, the bits don't place in the right spot. 

![chisel and bits glitch-min](https://user-images.githubusercontent.com/75952935/102024174-63789880-3d5e-11eb-89bf-eb0b8780cbc3.gif)

For any bug reports please provide the following details as well,
* MC Version: 1.16.4
* C&B Version: 0.2.8
* Do You have Optifine: Yes

**Comment by marchermans** [comment]
Duplicate of: #549
