### ISSUE TITLE
OpenGL error 1281

### ISSUE THREAD

**Issue by FillyRarity** [ChiselsAndBits/Chisels-and-Bits#560]
While using C&B alongside Optifine 1.16.4HD U G5 I get a repeating message of "OpenGL error 1281 (invalid value)".

* MC Version: 1.16.4
* C&B Version: 0.2.8
* Do You have Optifine: Yes (version above)

I was confused what was causing this so I did some tests.
-Clean mod folder, just forge, no issues game ran fine with no errors.
-Forge+optifine, fine, still no issues.
-Forge+optifine+C&B, OpenGL error.
-Forge+C&B- ran fine, no errors.

I can only assume the error is caused by something conflicting between C&B and Optifine.
I did all the usual good stuff; updated my java and graphics drivers (I have an Nvidia GPU if that is relevant) and the error still persisted.

For reference, it's not gamebreaking per-se; the game only crashed the first time I tried to chisel away a block but the subsequent times it seemed to work fine. My only worry is errors are naturally not good, so I can only wonder what effect it'll have on other mods I install or performance overall.
Any help would be appreciated!
Thanks!

**Comment by JohnnieJar** [comment]
This is kind of late but make sure you have render regions off. It's in video settings/performance.

**Comment by marchermans** [comment]
Fixed in the upcoming 1.0.11 or 1.1.5 releases
