### ISSUE TITLE
Waterlogging

### ISSUE THREAD

**Issue by WenXin20** [ChiselsAndBits/Chisels-and-Bits#563]
`Minecraft v1.16.4`
`Forge v35.1.13`
`C&B v0.2.8`

Is it possible to add waterlogging to bits, printers, & bit storage? This way placing a single bit won't just delete the water it is placed in. It would also allow for interesting underwater decorations.

**Comment by marchermans** [comment]
Water logging the bits is currently not under consideration, since you can use water bits to reach the same effect.
With regards to the machines I might add this, but it is under a low level of priority.
