### ISSUE TITLE
Bits placing wrong

### ISSUE THREAD

**Issue by HaydenRyder** [ChiselsAndBits/Chisels-and-Bits#564]
MC Version 1.16.4
C&B Version 0.2.8
I do have Optifine

Whenever I go to place a single bit it places a pixel above the space I'm aiming at. Such as trying to place on the ground there is a one pixel space between the ground and placed bit, same occurs trying to place a single bit on another. My only fix as of right now is using line or drawing bits

**Comment by ostrichlittledungeon** [comment]
Duplicate. See ticket [#549](https://github.com/ChiselsAndBits/Chisels-and-Bits/issues/549)

**Comment by HaydenRyder** [comment]
Thanks
