### ISSUE TITLE
Unable to read blob

### ISSUE THREAD

**Issue by otDan** [ChiselsAndBits/Chisels-and-Bits#565]
For any bug reports please provide the following details as well,
* MC Version: 1.16.4
* C&B Version: 0.2.8
* Do You have Optifine: Yes

I am unable to start the server and all I get in console is this type of error:
https://hastebin.com/ewezesuroy.properties

**Comment by marchermans** [comment]
I am not able to reproduce this issue.

**Comment by otDan** [comment]
Couldn't reproduce it when the pack was updated but the mod version is the same

**Comment by marchermans** [comment]
Closing due to no further response indicating that the issue still persists.
