### ISSUE TITLE
bits aren't appearing in the creative menu and all chiseled blocks are invisible when in my inventory

### ISSUE THREAD

**Issue by zachyaboyy** [ChiselsAndBits/Chisels-and-Bits#566]
Before continuing if you are reporting an issue, please ensure that all mods involved are updated to the latest version available, if your issue with with intermod compatibility such mixing C&B bits with other blocks make sure that MCMP is also updated. If your issue is a crash, be sure to include the crash log with your report.

when i middle click a block, i get an invisible block that i can only place once, even in creative. however, that might be because I'm not supposed to be able to get an item of it. **More importantly** all bits, including vanilla and modded blocks, are not appearing in the creative inventory. all that appears is 31 blank slots called "chisled bit". in the tooltip, there was red text saying "any bit is accepted". these do nothing, and all 31 are the same item. sadly this means I am unable to build using single bits in creative. due to the fact that all bits, both from vanilla and modded blocks, arent appearing, I do not think this is a mod compatibility issue. i will try with only chisels and bits installed to see if they appear.

For any bug reports please provide the following details as well,
* MC Version: 1.16.4
* C&B Version: 0.28.
* Do You have Optifine: yes, but I don't think this means anything as when i installed it, i accidentally installed a beta version and it still appeared, and i had optifine then. but when i realised my mistake and downloaded the latest version, then the bug happened. also, its a bug in the creative inventory, which i don't think optifine touches.

edit: ok when I right-clicked the "chiseled bit storage" when it was filled with water I got a stack of the same invisible item but without the red text. this time I could place it and when I did place it, it was invisible but I could still walk on it and stuff

**Comment by marchermans** [comment]
Optifine touches a lot of code including item and block model code.
As such I am unable to reproduce this in my Dev environment.

If you can reproduce this without optifine and in a sterile environment i can look at it again.

**Comment by zachyaboyy** [comment]
ohhhh ok i didnt know that. ill try without optifine then tell you if that fixes it
