### ISSUE TITLE
Netherite chisel unable to mine gold and diamond block

### ISSUE THREAD

**Issue by Peerius1701** [ChiselsAndBits/Chisels-and-Bits#567]
Hello, I use C&B 0.2.8 with Minecraft 1.16.3 and Optifine.
I came across the problem that the netherite chisel can't mine gold and diamond blocks, but I didn't test it with the other ore blocks yet.

**Comment by marchermans** [comment]
This can be configured via the configuration.
It requires the values of two options to line up:

1. `enableChiselToolHarvestCheck` -> This enables or disables the harvest check.
2. `enableChiselToolHarvestCheckTools` -> The comma seperated list of tool types chisels can immitate. For example "pickaxe".

The value for 1) was by default `true` is have updated this to false in the new release.
