### ISSUE TITLE
[1.16.4] Client code run on servers

### ISSUE THREAD

**Issue by NielsPilgaard** [ChiselsAndBits/Chisels-and-Bits#568]
We've been seeing a lot of the message below on the official Enigmatica 6 server:

```
[27Dec2020 02:36:20.414] [Server thread/INFO] [chiselsandbits/]: Unable to determine blocks eligibility for chiseling, wayoftime.bloodmagic.common.block.BlockBloodRune attempted to load net/minecraft/client/util/ITooltipFlag missing @OnlyIn( Dist.CLIENT ) or @Optional?
```

It happens for all sorts of blocks. 

For any bug reports please provide the following details as well,
* MC Version: 1.16.4
* C&B Version: 0.2.8-RELEASE
* Do You have Optifine: No

**Comment by marchermans** [comment]
@NillerMedDild This might be an issue with BloodMagic not marking its methods properly with @OnlyIn (Dist.Client)

Nothign I can do.
Please report it to them.

**Comment by NielsPilgaard** [comment]
Damn, I was hoping it was on your side, because it's several mods and about a hundred blocks :P Oh well. Thanks!

**Comment by marchermans** [comment]
Well the error is not really a problem.
It is just a warning.
You can t chemically just ignore it.
