### ISSUE TITLE
Incorrect chiseling

### ISSUE THREAD

**Issue by SouthernPixel** [ChiselsAndBits/Chisels-and-Bits#569]
Here is what I am getting an issue with https://imgur.com/a/XZUuTrD

For any bug reports please provide the following details as well,
* MC Version: 1.16.4 Forge
* C&B Version: chiselsandbits-0.2.8-RELEASE
* Do You have Optifine: Yes

**Comment by Terra777** [comment]
I have the same issue. It seems to be connected to connected texture blocks. So far only ever experienced it with glass tho.

**Comment by DreamingLamb** [comment]
Having similar issues where it seems the targeting for placing and chiseling blocks is incorrect.  Just wanted to add that this is happening with solid blocks too, like vanilla dirt or Astral marble.

**Comment by brisingraerowing** [comment]
I've seen this as well while trying to cut a notch in a block to access an otherwise hidden infinite water source. I ended up using a stair block instead. Was quite confusing at first.
