### ISSUE TITLE
Set Bit Command

### ISSUE THREAD

**Issue by AlgorithmX2** [ChiselsAndBits/Chisels-and-Bits#57]
Something like,
/setbit x,y,z bx,by,bz blockstate

This could be miss used so should probably be in the config and be disabled by default.

Suggested by timtomtim7
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2576750-chisels-bits-flat-colored-blocks?comment=344

**Comment by AEnterprise** [comment]
should also require OP permissions or extensive checking that the replaced blocks are air and can be replaced as it could be abused to bypass permissions otherwise

**Comment by AlgorithmX2** [comment]
I imagine that it should have the same permission requirements as /setblock

I think the idea is to allow command block sort of interactions, not to give users a way to cheat.

**Comment by AEnterprise** [comment]
i know it's not ment to give ways to cheat, just trying to help avoid that

**Comment by AlgorithmX2** [comment]
Sure, Its not a bad observation, guess it just seemed overly obvious at the time. Lol

**Comment by timtomtim7** [comment]
My original idea for this command wasn't for command blocks (though I'm sure someone would find that useful), but rather for command computers (ComputerCraft). I think this and a command computer would open up tons of possibilities for shapes that would have otherwise required a lot of time or an addon to create.

**Comment by timtomtim7** [comment]
Thanks!

Foiled by my own suggestion: I loaded up the game with the new version and completely forgot about it being disabled by default for a whole like 5 minutes.
