### ISSUE TITLE
Bit bag trash "Hold item to filter" drops bits on ground

### ISSUE THREAD

**Issue by ferdinandwinters** [ChiselsAndBits/Chisels-and-Bits#570]
Before continuing if you are reporting an issue, please ensure that all mods involved are updated to the latest version available, if your issue with with intermod compatibility such mixing C&B bits with other blocks make sure that MCMP is also updated. If your issue is a crash, be sure to include the crash log with your report.

For any bug reports please provide the following details as well,
* MC Version: 1.16.4
* C&B Version: chiselsandbits-0.2.8-RELEASE
* Do You have Optifine: Yes OptiFine_1.16.4_HD_U_G5

When I pick up a stack of bits and try to use the trash in the bit bag, it drops the bits on the ground and I cannot delete specific bits.

**Comment by Jonius7** [comment]
Having this issue, keeps deleting the whole bag and no other option but dropping the bits I DON'T want on the ground.

**Comment by marchermans** [comment]
Fixed in the upcoming 1.0.11 or 1.1.5 releases
