### ISSUE TITLE
[1.16.4] Bits are placed incorrectly

### ISSUE THREAD

**Issue by NielsPilgaard** [ChiselsAndBits/Chisels-and-Bits#575]
This is a duplicate of #572, but I thought I'd offer a more concise report, hope that's alright.

Bits don't place where you put them, here's a video of it: https://streamable.com/651rxq

For any bug reports please provide the following details as well,
* MC Version: 1.16.4
* C&B Version: 0.2.8-RELEASE
* Do You have Optifine: No

**Comment by marchermans** [comment]
As you stated your self: Duplicate.
Additionally the original issue already has the label "Awaiting Commit". In a sense meaning that I have it fixed internally but that something else is holding up a release. This something else a memory leak i am trying to find, which takes additional time.

Hope to have informed you on the state of the issue.

Greets Orion
