### ISSUE TITLE
Horizontal logs are seperate from vertical logs

### ISSUE THREAD

**Issue by Peach774** [ChiselsAndBits/Chisels-and-Bits#58]
The bits for horizontal logs are separate from vertical logs which is really strange. While it does allow you to make weird patterns on logs, it also makes repairing holes very difficult because the regular log bits don't work, only horizontal log bits will work. They should probably the same bit type

**Comment by AlgorithmX2** [comment]
I disagree, I quite like being able to use different log directions together in a single design, if they were the same, you could only use vertical logs, this to me would be far worse.

**Comment by Peach774** [comment]
What if they were the same type, but you could switch between them. This would reduce the types of bits when chiseling logs and would remove the confusion.

**Comment by AlgorithmX2** [comment]
How would you go about switching types? The only ideas I have on solving the confusion aspect of this is trying to better label the bits, in theory something like "Oak Log - East/West" instead of "Oak Log"

**Comment by Peach774** [comment]
That would be fine too. I just meant a keybind that could rotate log bits but if labeling can be done, that would be nice also.
