### ISSUE TITLE
Completed Water and Lava blocks have a different block state from their bucketed counterparts

### ISSUE THREAD

**Issue by wchen1990** [ChiselsAndBits/Chisels-and-Bits#580]
**Issue**: When completing a block with water or lava bits, the completed block has a block state that differs from if you placed water or lava down with a bucket. The block id would be of the flowing variant with various other block state properties to them. This can be observed with F3 up. Also, because the block is the flowing variant, the completed fluid block would disappear.

**Repro steps**: Use a bucket of lava or water on the bit storage block, get the bits, and then complete the block. 

**Expected behavior**: Completed fluid blocks using bits should have the same block state as though they were placed by a bucket.

Version Information:
* MC Version: 1.16.3
* C&B Version: 0.2.9-RELEASE
* Do You have Optifine: No
----
I personally tried to look into this myself, but I'm not entirely sure what the issue is. When registering fluid bits it does seem like it's registering the default state of the fluid so I'm not sure why it's registering the flowing state of the fluid rather than the block state. But, maybe the default fluid state is the flowing state?

Let me know if you need any more information. I'd be taking a look to see if I can figure this out as well.

**Comment by marchermans** [comment]
Fixed in 1.0.11 for 1.16.x or 1.1.5 for 1.17.1
