### ISSUE TITLE
Game Crashing With the Crash Message of: Tessellating Block in World

### ISSUE THREAD

**Issue by Phoenix615266** [ChiselsAndBits/Chisels-and-Bits#586]
This was on Minecraft version 1.16.4, Chisels and Bits version 0.2.9. Latest release. The game crashed, only most of the time, after placing a 1/4 sized block (or a single bit) on vanilla grass or sand. After the game crashed, it gave me the crash message: Tessellating Block in World. I did have Optifine on, as well as the Faithful resource pack. No shaders. This happened more than 6 times. I Opened a new world with the same mods and resource pack, and it did the same thing in the new world.

* MC Version: 1.16.4
* C&B Version: 0.2.9
* Do You have Optifine: Yes

Minecraft Crash Report (New Link):
https://pastebin.pl/view/0ec4849d

**Comment by ZoruaBit** [comment]
yeah i had the same problem (reported aswell) i would sugest fixing this asap. it happend with bolth optifine and without

**Comment by Intybyte** [comment]
The issue looks like the same for me too.

https://pastebin.com/CDh5f4Bb

No optifine, and some simple mods.
Btw if u have to paste a crash copy all the .txt in a pastebin and send the link
