### ISSUE TITLE
Tesselating Block Client crash while playing on server

### ISSUE THREAD

**Issue by zachsai** [ChiselsAndBits/Chisels-and-Bits#587]
Before continuing if you are reporting an issue, please ensure that all mods involved are updated to the latest version available, if your issue with with intermod compatibility such mixing C&B bits with other blocks make sure that MCMP is also updated. If your issue is a crash, be sure to include the crash log with your report.

https://pastebin.com/kfH0pRCA

For any bug reports please provide the following details as well,
* MC Version: 1.16.5
* C&B Version: 0.2.9
* Do You have Optifine: Yes

**Comment by notnem** [comment]
Same issue, also on a server. Happens when completing a block, like some closed issues.
https://pastebin.com/3Ce6iZAj
