### ISSUE TITLE
Water destroys water bits

### ISSUE THREAD

**Issue by WenXin20** [ChiselsAndBits/Chisels-and-Bits#590]
`Minecraft v1.16.5`
`Forge v36.0.1`
`C&B v0.2.10`

If I place water bits underwater of any size, water will immediately take it over and destroy the bits. 

And water bits doesn't really replace waterlogging as it still will display incorrectly underwater when combined with other bits, which doesn't look very good. There is a boolean called `shouldDisplayFluidOverlay` that is used with translucent blocks such as glass, that could work for full sized chiseled blocks, but not for anything smaller.

Also, if I pick up chiseled water block or grass block, it is invisible and doesn't show a placement preview.

![2021-01-21_20 14 36](https://user-images.githubusercontent.com/12000593/105437085-06f27e00-5c26-11eb-8ebe-8a06838d7232.png)

**Comment by marchermans** [comment]
Fixed in 1.0.11 for 1.16.x or 1.1.5 for 1.17.1
