### ISSUE TITLE
Mirror Chisel Design Does Not Work

### ISSUE THREAD

**Issue by ostrichlittledungeon** [ChiselsAndBits/Chisels-and-Bits#591]
* MC Version: 1.16.5
* C&B Version: 0.2.10
* Do You have Optifine: No

I had a ticket for this issue before, but you dismissed it. I guess I was not clear on what the problem is. Putting a mirror chisel design into a crafting table with a positive chisel design does not yield a transfer of the design.

![Screen Shot 2021-01-22 at 4 07 13 AM](https://user-images.githubusercontent.com/13596613/105470248-54430f80-5c67-11eb-8b15-c54fee79aa3f.png)

I can make a mirror chisel design just fine, but I cannot transfer it to a positive chisel design so it is unusable.

**Comment by ostrichlittledungeon** [comment]
This is what it shows on your website. Notice how the output positive chisel design is blank. The data is not being transferred over. This issue is also true for negative chisel designs.

<img width="382" alt="Screen Shot 2021-01-22 at 4 08 01 AM" src="https://user-images.githubusercontent.com/13596613/105470339-6d4bc080-5c67-11eb-971c-d9692189ac3f.png">

**Comment by marchermans** [comment]
Oooooh
I understood that indeed wrong.
I will take a look.

**Comment by AquaArisa** [comment]
Is there an update on this problem? Cause some of my projects are on hold until this bug is fixed

**Comment by Bablela26** [comment]
I too have C&B Version 0.2.10, and have this problem,
is it fixed in the multiples newer versions of the mod ?
and can i update my client without needing to update anything on the server i'm on ?
Thanks.

**Comment by Bablela26** [comment]
So, Version 0.3.4 didn't fix it.
but i found that combining the mirror chisel design with a positive chisel design result in a mirrored bloc, but only made out of stone
![image](https://user-images.githubusercontent.com/80642972/111081454-b4d22880-8503-11eb-93cc-8f0d9dbf8936.png)
![image](https://user-images.githubusercontent.com/80642972/111081469-ca475280-8503-11eb-82a3-ce15c0e4ba0a.png)

**Comment by ThinkWithPbody** [comment]
Would really appreciate it if this got fixed.

**Comment by marchermans** [comment]
Fixed in 1.0.11 for 1.16.x or 1.1.5 for 1.17.1
