### ISSUE TITLE
1.16.4 all the mods 6 crash when finishing block

### ISSUE THREAD

**Issue by Raffia16th** [ChiselsAndBits/Chisels-and-Bits#592]
Every time i finish a block fully from bits and it returns to its original full block state my game crashes with a block tessellation issue. I am running an older AMD R9 290 GPU is that helps any on latest amd software/drivers and latest java.

A crash report is included as an attachment.

For any bug reports please provide the following details as well,
* MC Version: 1.16.4
* C&B Version: 0.2.9
* Do You have Optifine: No
[crash-2021-01-22_13.02.55-client.txt](https://github.com/ChiselsAndBits/Chisels-and-Bits/files/5856026/crash-2021-01-22_13.02.55-client.txt)

**Comment by redeyesblackdildo** [comment]
I am having the same issue. My rig is somwhat better tho. 
Same mod pack also. There are also large stuttering lag spikes while working with and around bit blocks. Only after some type of interaction with the bits happens. I've played around 6 or 7 other mod packs with C&B and never had any issues, its also my favourite mod and if I can't use it I don't see a reason to play.

**Comment by marchermans** [comment]
There is 0.2.10 which has this fixed.
