### ISSUE TITLE
Feature Request: Allow Chiseled glass to color a beacon

### ISSUE THREAD

**Issue by Cerbrus** [ChiselsAndBits/Chisels-and-Bits#593]
I've currently got a few beacons covered with red stained glass on all sides, but sadly, a "pane" of red stained bits on top of the beacon didn't color the beacon. I'm stuck with vanilla MC glass:

![image](https://user-images.githubusercontent.com/2911988/105644081-f3e4e580-5e93-11eb-9563-e9107b0809ff.png)

It would be awesome if chiseled glass could color a beacon.

* MC Version:
1.16.4
* C&B Version:
chiselsandbits-0.2.9-RELEASE
* Do You have Optifine:
No

**Comment by marchermans** [comment]
Fixed in 1.0.12 for 1.16.x or 1.1.6 for 1.17.1 (Publish pending)
