### ISSUE TITLE
Collision bug

### ISSUE THREAD

**Issue by Jerome226** [ChiselsAndBits/Chisels-and-Bits#595]
So to explain the problem.
![image](https://user-images.githubusercontent.com/55724525/105756966-53d29f00-5f1b-11eb-9c1b-28802140191b.png)
Sometime when you chisel a block it lost his hitbox. Like the block is still here, but you can't hit and modify it.

For any bug reports please provide the following details as well,
* MC Version: 1.16.5
* C&B Version: C&B 0.2.10
* Do You have Optifine: No

**Comment by SodiumShine** [comment]
Also having this problem. Ending up with ghost blocks is troublesome.

**Comment by FireKeeper3** [comment]
I just encountered the same issue - I chiseled too many individual pixels out from a block and its collision turned off, so I couldn't get rid of it.      I figured out that you can use the /Fill command to surround a Ghost block on all sides with any other standard block, and when it fills the area it will overwrite the Ghost block. Then you can just delete the filled blocks and have a fresh work area.  

  Not sure how to prevent the collision bug from happening, but at least this method will be able to get rid of a block that has the bug. Hope this helps!

**Comment by reavenbroke** [comment]
I am also having the same issue, Upon chiseling a block it is no longer selectable. This was working a few months ago- Now when you add a block to something or chisel a bit out of it, it loses its selectable outline, you cant select the block at all, even in creative.

**Comment by Aurif** [comment]
Some additional info I noticed about this issue, this occurs if there are no pixels on the outer layer of the west side of the block. Adding even a single pixel on that side will revert the collision back to normal. This doesn't happen for other sides.

This probably isn't the only way to get this issue, but it's quite a regular one.

**Comment by marchermans** [comment]
Okey thank you

**Comment by marchermans** [comment]
Fixed in 1.0.11 for 1.16.x or 1.1.5 for 1.17.1
