### ISSUE TITLE
Wrench issue

### ISSUE THREAD

**Issue by Soma-81** [ChiselsAndBits/Chisels-and-Bits#596]
Using the wrench only rotates the block about the Y axis, not based on the face. I want to rotate a block so it's upside down, but even with aiming at the desired face as stated by the wiki, the rotation doesn't appear possible. I've tried loading C&N as the only mod to check for conflict and the issue persisted.

* MC Version: 1.16.4
* C&B Version: 0.2.9
* Do You have Optifine: No

**Comment by IrisEdelsmid** [comment]
I'm experiencing this same thing too, previous C&B version though, so just to clarify this issue was in C&B 0.2.8 too.

- MC Version 1.16.4
- C&B version 0.2.8
- Optifine: No

Experiencing many other bugs as well unfortunately.

**Comment by marchermans** [comment]
This won't be fixed sorry.

For now the wrench has been removed from the rebuild version.
The reported problem was due to changes in MC and without these being reverted I see no reason for the wrench to exist.
