### ISSUE TITLE
[1.16.5] Unable to determine blocks eligibility for chiseling

### ISSUE THREAD

**Issue by SirOMGitsYOU** [ChiselsAndBits/Chisels-and-Bits#597]
For any bug reports please provide the following details as well,
* MC Version: 1.16.5
* C&B Version: 0.2.10-RELEASE
* Do You have Optifine: No

When loading up my server C&B spams a whole lot of undetermined block eligibility. Unsure who to report it to so just thought I'd put it here, I'm unsure if it's something I need to be concerned with. 

https://gist.github.com/SirOMGitsYOU/e015d28321e4b18798a7c8a91ab09848

**Comment by koderian** [comment]
Same issue here

**Comment by Mondrethos** [comment]
Also have the same issue.

**Comment by marchermans** [comment]
Fixed in 1.0.11 for 1.16.x or 1.1.5 for 1.17.1
