### ISSUE TITLE
Chisel and Bit's crashes Minecraft after loading passing the experimental game play. 

### ISSUE THREAD

**Issue by LilBlueRose** [ChiselsAndBits/Chisels-and-Bits#599]
I've been trying to get Chisel's and Bit's mod to work for three days now. Every time I try to load it, it'll say "Experimental game play" and apparently no one else is getting that error.... I click proceed, it loads to 100 % and crashes. 

For any bug reports please provide the following details as well,
* MC Version: 1.16.4 & 1.16.5
* C&B Version: chiselsandbits-0.2.10-RELEASE
* Do You have Optifine: As a mod

**Comment by marchermans** [comment]
Hello could you send me the crash log?

**Comment by LilBlueRose** [comment]
https://controlc.com/4454a1bc
Password StormyBluethorn

Let me know if you need more info

**Comment by marchermans** [comment]
Sorry but this is not a c&b issue.
I am guessing you have problems with optifine.
