### ISSUE TITLE
Chisel printer hitbox rotation not working & Bit storage item model bugged

### ISSUE THREAD

**Issue by IchHabeHunger54** [ChiselsAndBits/Chisels-and-Bits#601]
* MC Version: 1.16.4
* C&B Version: 0.2.10-RELEASE
* Do You have Optifine: no

![2021-01-31_01 01 40](https://user-images.githubusercontent.com/52419336/106371043-4759a680-6360-11eb-8125-558253ae0846.png)
![2021-01-31_01 01 49](https://user-images.githubusercontent.com/52419336/106371044-4b85c400-6360-11eb-9af5-5600b35dba3c.png)

I think the error is obvious. The hitbox is not being rotated, neither to the west (as seen above) or to the east or south as well. I suppose its an easy fix.

The second thing is completely unrelated to the first, I just didnt want to open another issue right afterwards.
The bit storage item model is just... blank.
![2021-01-31_01 05 59](https://user-images.githubusercontent.com/52419336/106371080-aae3d400-6360-11eb-8efe-57d60b97ef28.png)
![2021-01-31_01 07 51](https://user-images.githubusercontent.com/52419336/106371087-c18a2b00-6360-11eb-9ae3-af9d42e702d0.png)

**Comment by marchermans** [comment]
Fixed in 1.0.11 for 1.16.x or 1.1.5 for 1.17.1
