### ISSUE TITLE
Water issue

### ISSUE THREAD

**Issue by Autumnlight02** [ChiselsAndBits/Chisels-and-Bits#602]
Issue: When placing chisel and bits water bits u cannot swim in them nor can you put fishes in it. The same goes for lava and burning. Additional at water if u stack the block to a full one it disappears

Repro steps: make a block with water chisels / fill it in half and put a fish in it.

Expected behavior: You can swim in the Water/fishes survive in it / in lava u get damage/water does not disappear at a full block.

Version Information: newest version 1.16.5

**Comment by marchermans** [comment]
C&B Water blocks are not actual water.
Due to the implementation of the requested features from Minecrafts side, this is not possible.
