### ISSUE TITLE
MULTIPLAYER BUG/GLITCHING AROUND

### ISSUE THREAD

**Issue by Autumnlight02** [ChiselsAndBits/Chisels-and-Bits#603]
issue: When you create a chisel and bit block and for example fill it to 1/3th and try to walk on it u glitch around and u cannot walk.
1 layer works
2 layer works
3 layer glitching around
4 layer glitching around
5 layer glitching around
6 layer glitching around
7 layer glitching around
8 layer glitching around
9 layer glitching around
10 layer glitching around
11 layer glitching around
12 layer glitching around
13 layer glitching around
14 layer glitching around
15 layer glitching around
16 layer works

with glitches around I mean that u teleport and can barely move, test it please in mp
* MC Version: 1.16.5
* C&B Version: chiselsandbits-0.2.10-RELEASE
* Do You have Optifine: no

**Comment by Autumnlight02** [comment]
![image](https://user-images.githubusercontent.com/68244453/106396424-1a60ce80-6408-11eb-954b-5a576a5164f7.png)

**Comment by marchermans** [comment]
Fixed in 1.0.11 for 1.16.x or 1.1.5 for 1.17.1
