### ISSUE TITLE
Game Crash  when I use "Copy to Clipboard" on Server

### ISSUE THREAD

**Issue by lays24mc** [ChiselsAndBits/Chisels-and-Bits#604]
Hi,

as soon as I use the "copy to clipboard function in Creativ on my server, the client crashes with this error: https://pastebin.com/x52kU6kd

* MC Version: 1.16.5
* C&B Version: 0.2.10-RELEASE
* Do You have Optifine: No

**Comment by marchermans** [comment]
The clipboard has been removed in the rebuild version, in favor of using patterns.
It might or might not be reintroduced in a later version.
