### ISSUE TITLE
[1.16.4/5] Protection problem for C&B events

### ISSUE THREAD

**Issue by Daejangnamu** [ChiselsAndBits/Chisels-and-Bits#605]
In use with FTBChunks mod (https://www.curseforge.com/minecraft/mc-mods/ftb-chunks)
Chunks are not protected when using the chisel tool

Video: https://youtu.be/U_r7LSkIWzU

* MC Version: 1.16.5
* C&B Version: C&B 0.2.10
* Do You have Optifine: Yes

**Comment by blix5** [comment]
Can confirm the same thing happens with WorldGuard on a Mohist Server

**Comment by marchermans** [comment]
This is indeed true.
At the moment C&B does not care for them.

**Comment by marchermans** [comment]
Fixed in 1.0.11 for 1.16.x or 1.1.5 for 1.17.1
