### ISSUE TITLE
when youre using a resize mod

### ISSUE THREAD

**Issue by MiloCookie** [ChiselsAndBits/Chisels-and-Bits#606]
do to 1.14 making you crawl under blocks if you go in a small structure you cant shift and you swim witch makes you slower this is not an issue just something i wonder if you can fix it
* MC Version:1.16.4
* C&B Version:newest
* Do You have Optifine:yes

**Comment by marchermans** [comment]
Sadly no, this is vanilla behaviour in relation to the bounding boxes.
