### ISSUE TITLE
Possible chiseled bit glitch in game. 

### ISSUE THREAD

**Issue by Qagabon** [ChiselsAndBits/Chisels-and-Bits#607]
UPDATE: The chiseled bits appeared again after I kept a game open for about an hour. See screenshot below. 
![why](https://user-images.githubusercontent.com/78516871/106938988-a8c99e80-66ed-11eb-9a9e-17172fb96575.JPG)
     

I am new to to Minecraft modding, so I am not sure if this is an issue with the mod itself or if I did something. About a week ago I was playing Minecraft in creative and messing around with the chiseled bits, I could search for them in the toolbar (ex: oak chiseled bit, stone chiseled bit, so on), and place them on blocks. Fast forward to today when I noticed none of the chiseled bits appeared when I searched for it in the toolbar, just the tools and sacks, and four empty squares called 'chiseled bit' which I could drag to by hot bar but I could not interact with it. During the span of a week I did download the latest version of Optifine, so it could be that did something. Sorry if my description is weird or vague, I added a screenshot to show the issue.

MC Version: 1.16.5
C&B Version: 1.16.5
Optifine Version: HD U G6 

![helple](https://user-images.githubusercontent.com/78516871/106833247-34e1b480-6661-11eb-9e1f-3ddbd2b8dcad.JPG)

**Comment by marchermans** [comment]
Seems like a resource loading issue. Normally restarting the game fixes it.
