### ISSUE TITLE
 [1.16.4] Compatibility problem with Modular Router

### ISSUE THREAD

**Issue by mmis1000** [ChiselsAndBits/Chisels-and-Bits#610]
Before continuing if you are reporting an issue, please ensure that all mods involved are updated to the latest version available, if your issue with with intermod compatibility such mixing C&B bits with other blocks make sure that MCMP is also updated. If your issue is a crash, be sure to include the crash log with your report.

Put stitched chisels and bits blocks in to `modular router with extruderII and mimic argument` cause client crash
https://paste.ee/p/KGqbp

For any bug reports please provide the following details as well,
* MC Version: 1.16.4
* C&B Version: 0.2.10
* Do You have Optifine: no

**Comment by marchermans** [comment]
Sorry, this is a ModularRouters issue.

I am simply querrying the light value from the C&B TE, which does not work when the block is mimiced due to it being a Modular Routers TE.
