### ISSUE TITLE
C+B causing extreme lag spikes on server

### ISSUE THREAD

**Issue by homicide-bunnie** [ChiselsAndBits/Chisels-and-Bits#611]
I've been building a house with lots of c+b bits for details and it seems like the more I add the worse and worse the issue gets. I've been having to disconnect/reconnect about every 5 minutes while building and sometimes while disconnecting the game just crashes. I tried making a singleplayer world to test out the issue but the game crashes every time I try to create a singleplayer world. The server has a modpack and I'm wondering if it might be conflicting with other mods in the pack?

The modpack includes:
aquaculture 2.1.11
byg 1.1.8
chiselsandbits 0.2.9 RELEASE
chocolate 1.3.0
create-mc v0.3e
decorative_blocks 1.7.2
extlights 3.3
fairylights 4.0.4
ironagefurniture 0.2.0.5
jei 7.6.1.65
mcw-doors 1.0.1
mcw-furniture 2.0.0
mcw-trapdoors 1.0.0
mcw-windows 1.0.2
simplefarming 1.3.5
supplementaries 0.9.19

* MC Version: 1.16.4
* C&B Version: 0.2.9 RELEASE
* Do You have Optifine: yes

**Comment by marchermans** [comment]
Update to 0.2.10.

This fixes a memory leak.
