### ISSUE TITLE
Chisel Station disappears after breaking with all of its contents

### ISSUE THREAD

**Issue by 2xMJet** [ChiselsAndBits/Chisels-and-Bits#612]
Played on my own server. Will try to reproduce in single a bit later.

Tried to build something with C&B and after breaking Chisel Station lost Design pattern and diamond Chisel in it. Station just disappeared, like i broke it with wrong tool with no drop at all. 

Tried to do new Stations to reproduce it then broke it and 3 consecutive times got the same result. It's just dissapears without dropping a block or even its contents.

 * **MC Version:** 1.16.5
 * **Forge:** 36.0.14
 * **C&B Version:** 0.2.10-RELEASE
 * **Optifine:** No
 * Multiplayer
 * **Modpack:** FTB Direwolf20 (version 1.6.1)
 
 
**UPD:** Same behavior in Singleplayer.
**UPD2:** Works even with mod alone so its not modpack issue i suppose.

**Comment by marchermans** [comment]
Fixed in 1.0.11 for 1.16.x or 1.1.5 for 1.17.1
