### ISSUE TITLE
Snow is blocking render of Bit Structures

### ISSUE THREAD

**Issue by 2xMJet** [ChiselsAndBits/Chisels-and-Bits#613]
What happens is on images. Texture disapearing when bit constructions placed next to snow layers.
![image](https://user-images.githubusercontent.com/26283528/107513849-6adfe500-6bdb-11eb-8bb9-3a063f9b2498.png)
![image](https://user-images.githubusercontent.com/26283528/107514413-3587c700-6bdc-11eb-80dc-6501a20e6ba4.png)

* **MC Version:** 1.16.5
* **Forge:** 36.0.14
* **C&B Version:** 0.2.10-RELEASE
* **No Optifine.**
* **Multiplayer**
* **Modpack:** FTB Direwolf20 (version 1.6.1)

**Comment by marchermans** [comment]
Fixed in 1.0.11 for 1.16.x or 1.1.5 for 1.17.1
