### ISSUE TITLE
Updating a Server from 1.12.2

### ISSUE THREAD

**Issue by vistangagh** [ChiselsAndBits/Chisels-and-Bits#614]
Hi there and a big thank you for bringing the Chisels and Bits mod to the newest Minecraft version, that's awesome!

Back in the days, actually way before 2012, we started a small Minecraft server in creative mode. It kinda survived all following Updates until 1.12.2, so the world has somewhat of a nostalgic value to us. 
With 1.12.2 we decided to start using chisels and bits and fell in love with the mod - so much, that when further updates came, we did not want to miss the features of it. So the Minecraft version was frozen with the mod in the Version 14.33 for quite some time and we are still playing.
 
With the news, that chisels and bits is now available to 1.16.x, we really wanted to get our server to the newest versions. So we backed the world up and tried our luck. 

First we tested the Mod-Version 0.2.10-RELEASE on 1.16.5 (newest). When everything was loaded, all chiseled blocks were gone. Also inventory items of bits were gone.
Likewise, we tried then the lowest possible transition by going from our old 14.33 to 0.0.4-ALPHA, which is the first one of the newly-ported versions. The same problem arose, sadly.
Basically, what the log-files are full with are lines like this one

> [10Feb2021 22:27:49.745] [Server thread/WARN] [net.minecraft.world.chunk.Chunk/]: Tried to load a block entity for block Block{minecraft:air} but failed at location BlockPos{x=2744, y=65, z=321}
> [10Feb2021 22:27:49.745] [Server thread/WARN] [net.minecraft.tileentity.TileEntity/]: Skipping BlockEntity with id minecraft:mod.chiselsandbits.tileentitychiseled

Just to make the list of information more complete: We don't use Optifine.

My question is: Is it planned to support updating from older C&B-Versions before the 1.16 port? I think, that there are many people, who would like to do that. So I don't want to have newer C&B-Features for 1.12.2, but I would like to be able to port my modded 1.12.2 world to 1.16.5 without losing all chiseled blocks. By the way: No other mods run on the server.

Thanks in advance.

**Comment by marchermans** [comment]
Sadly due to the fact that MC now needs proper blockstate ids, instead of block ids, this is not possible.

The ids would just not line up.
