### ISSUE TITLE
backport for chisels and bits and flat colored blocks to 1.7.10

### ISSUE THREAD

**Issue by firstdorsal** [ChiselsAndBits/Chisels-and-Bits#617]
do you think it would be possible to create a backport for chisels and bits as well as for flat colored blocks to 1.7.10 for the use in the awesome "new horizons" modpack?
i love both your mods and it would be awesome if they would be usable in 1.7.10
see https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/7467
all the best, paul

**Comment by marchermans** [comment]
Sorry no.
