### ISSUE TITLE
Designs cannot be copied or placed without crashing

### ISSUE THREAD

**Issue by fatherjenny** [ChiselsAndBits/Chisels-and-Bits#620]
* MC Version: 1.16.4
* C&B Version: All of the 1.16 versions (I tried most of them, all the same)
* Do You have Optifine: No

I used to use 1.12 and copying was very simple and easy to do using the positive blueprint thing (I'm sorry I don't really know the terminology ahaha). 
I wanted to use the new versions and I was making a custom fence for my world but once I had made the initial design for all the pieces, it refused to be copied or pasted, I messed about with it a while trying to find different solutions in-game like controls etc. but nothing.
I then saw a post saying I could use WorldEdit which I tried but when setting the second position the game would entirely shut down and crash.

I don't really know how to use these forums I just really want to make my world and was wondering if other people had this issue or a way to solve it.

**Comment by marchermans** [comment]
Fixed in 1.0.11 for 1.16.x or 1.1.5 for 1.17.1
