### ISSUE TITLE
Chisel Break Crash 1.16.5

### ISSUE THREAD

**Issue by TheBrainFire** [ChiselsAndBits/Chisels-and-Bits#623]
I have a lot of mods, so t's quite messy, but I tried to break 1 bit and crashed my whole game.
I haven't really experienced any mod crashes prior to this, so I think the mod is just incompatible with something.
If I try to reload the world, it crashes the exact same way.

* MC Version: 1.16.5
* C&B Version: 0.2.10-RELEASE
* Do You have Optifine: Yes

Crash Report:
[crash-2021-02-17_16.58.59-client.txt](https://github.com/ChiselsAndBits/Chisels-and-Bits/files/5997320/crash-2021-02-17_16.58.59-client.txt)

**Comment by marchermans** [comment]
This is not reproduceable for me with just Vanilla + Forge + C&B
