### ISSUE TITLE
Could not find parent net/minecraft/block/Block

### ISSUE THREAD

**Issue by ZandercraftGames** [ChiselsAndBits/Chisels-and-Bits#624]
When in the final stages of loading on a forge server, the Chisel and Bits mod hits this error. I am not sure if its importance is crucial to the proper functioning of the server or the mod, but I just wanted to report it here.

Error: [https://pastebin.com/04xP67Dj](https://pastebin.com/04xP67Dj)

For any bug reports please provide the following details as well,
* MC Version: 1.16.5
* C&B Version: 0.2.10-release
* Do You have Optifine: No (Running on server)
* Forge Version: forge-1.16.5-36.0.42

**Comment by marchermans** [comment]
Sorry but I can't reproduce this with Vanilla + Forge + C&B.
This means that this is a compatibility issue.

Please track it done by bisecting your mod list and trying to find the mod combination that causes it.

**Comment by ZandercraftGames** [comment]
> Sorry but I can't reproduce this with Vanilla + Forge + C&B.
> This means that this is a compatibility issue.
> 
> Please track it done by bisecting your mod list and trying to find the mod combination that causes it.

Will do. I don't have time to do that today, but I will get around to it in a little bit.

**Comment by marchermans** [comment]
Issue has gone stale and verified this in the latest Beta of the rebuild branch
Bug is for sure fixed.
