### ISSUE TITLE
Config file comments dont localize their text strings.

### ISSUE THREAD

**Issue by XDGrangerDX** [ChiselsAndBits/Chisels-and-Bits#626]
For example instead of "List of all block registry names, that are allowed to convert back into their normal block when chiseled but all bits are placed." this appears in the config: "mod.chiselsandbits.config.server.balancing.revertible.blocks.comment"

For any bug reports please provide the following details as well,
* MC Version: 1.16.4
* C&B Version: chiselsandbits-0.2.10-RELEASE
* Do You have Optifine: N

**Comment by marchermans** [comment]
This is not supported on forges side.
All the ones that i have translated will only be available in english.

If you want to help, we now have a crowdin page available for this project.

**Comment by XDGrangerDX** [comment]
Not sure what you mention? Im not asking about config translations for other languages, but reporting that the config file is hard to use because only untranslated strings (ie, these IDs) rather than the translated text for said string found only in the code.

**Comment by marchermans** [comment]
Ah okey.
This is a slow process. I have done virtually the entire client config at the moment. And am working on the server side.
I will reopen this issue then.
