### ISSUE TITLE
Placing chisel & bits blocks above a certain Y-Axis causes blocks within a certain area to not render (Y-axis changes every world)

### ISSUE THREAD

**Issue by MuzzikLuvrJR** [ChiselsAndBits/Chisels-and-Bits#627]
When placing the chisel & bit blocks above a certain y-axis they which varies from world to world it causes blocks to not render properly. As far as I can tell when it is only Optifine and chisel and bits the issue only causes water to become unable to see but when used with other mods (I haven't narrowed down which one was causing it) also causes other blocks like grass and glass to not render.

![2021-02-25_08 09 04](https://user-images.githubusercontent.com/79643172/109159598-c9ac6f00-7742-11eb-8586-965836cb4067.png)

For any bug reports please provide the following details as well,
* MC Version: 1.16.5
* C&B Version: 0.2.10
* Do You have Optifine: Yes

**Comment by marchermans** [comment]
This is not reproduceable for me.

**Comment by solman252** [comment]
Im having the same issue but only on water, and on V0.3.0
