### ISSUE TITLE
Placement of Positive chisel design removes Positive chisel design

### ISSUE THREAD

**Issue by bloodtap** [ChiselsAndBits/Chisels-and-Bits#628]
when using the positive chisel design in placement mode, it places the chisels as expected but deletes the Positive chisel design item (IE the blue schematic is deleted when right clicking)

Direwolf20 1.16.5 modpack

gif here: https://imgur.com/a/GLQsksY

For any bug reports please provide the following details as well,
* MC Version: 1.16.5
* C&B Version: C&B 0.2.10
* Do You have Optifine: No

**Comment by marchermans** [comment]
Fixed in 0.3.1-Release
