### ISSUE TITLE
Every time a mod is added or removed from the server the bits materials shift and collision breaks on all existing bit blocks making the mod unusable long term

### ISSUE THREAD

**Issue by tehbiga** [ChiselsAndBits/Chisels-and-Bits#630]
*Some version information:*
* MC Version: 1.16.5
* C&B Version: 0.2.10-RELEASE
* Do You have Optifine: No
* Modpack: ATM6 1.5.3b

*Whats broken:*
Every time I update the modpack and mods are added or removed all existing Chisels and Bits blocks are corrupted.
Almost all the materials change and all of the collision breaks. I've had to delete my bits bag and rebuild everything I've made every time the server updates.

*"Sounds like something is wrong on the server:*
I am the admin running the server. I migrated all the configs and the world without changes each pack update. I had diff the pack updates to make sure I get any changes the pack authors have made.
I've performed multiple pack updates and not a single one has touched Chisels and Bits. This should not be caused by me unless there is some unknown cache folder I'm not copying, but I was under the impression the C&B material mapping was stored in the world data.

**Comment by tehbiga** [comment]
Other people running into this:
https://discord.com/channels/254530689225981953/726665656854118481/809633562793607200
https://discord.com/channels/254530689225981953/726665656854118481/802861145965985822
https://discord.com/channels/254530689225981953/726665656854118481/804812345485295656
the list goes on...

**Comment by marchermans** [comment]
Fixed in 0.3.0.
