### ISSUE TITLE
Inventory/Dropped Block Previews are Invisible or Missing Texture

### ISSUE THREAD

**Issue by arisonas** [ChiselsAndBits/Chisels-and-Bits#634]
* MC Version: 1.16.5, Forge ver. 36.0.46
* C&B Version: chiselsandbits-0.3.3-RELEASE
* Do You have Optifine: Tested with and without Optifine installed; issue occured both times

On the latest release, blocks that have been chiseled and then dropped/added to inventory have either no image or a missing texture image. The hover-over tooltip also seems to have the item ID instead of a cosmetic name in addition to this.

Apologies also if this is a known issue I missed or if this feature is no longer supported - I had gone back to the C&B build for 1.12 and saw that block previews worked fine there, so I'm assuming this is a newer issue. This was tested on a clean 1.16.5 build as well as a 1.16.4 build with no other mods installed besides Forge with the issue occuring on both.

![javaw_2021-03-09_15-46-13](https://user-images.githubusercontent.com/10876611/110497893-c3c56f00-80ee-11eb-8039-cbd9a110c032.png)
![javaw_2021-03-09_15-46-47](https://user-images.githubusercontent.com/10876611/110497895-c45e0580-80ee-11eb-80fd-5437424192af.png)

**Comment by marchermans** [comment]
![C B Break and pickup](https://user-images.githubusercontent.com/5585406/110503852-e6f71b00-80fc-11eb-9a39-9bf26659d4eb.gif)

I am not able to reproduce this.

**Comment by arisonas** [comment]
Did you try this with any other blocks? Going back, Magenta Wool seems to work fine, but trying it on a grass block or log block causes the mentioned issues.

Edit: After testing a little more, this seems to happen (to me at least) only for certain blocks; tested wool/stone/andesite/granite and their previews are fine. Tried dirt + logs and I get purple boxes on them, and for whatever reason no texture at all for grass.

https://user-images.githubusercontent.com/10876611/110505130-c4adcf00-80f5-11eb-92d6-84e2e4bfaa96.mp4

**Comment by marchermans** [comment]
Okey will try again tomorrow

**Comment by marchermans** [comment]
Found the issue the item model is named wrongly.
Will fix.

**Comment by marchermans** [comment]
Fixed in 0.3.4
