### ISSUE TITLE
Bits are replaced by other bits

### ISSUE THREAD

**Issue by neijrr** [ChiselsAndBits/Chisels-and-Bits#636]
When I saved world and loaded it after closing and opening game, every bit of Create (mod) block was replaced with other bit from same mod (sometimes it was bits of block that can not be chiseled). Bits made out of vanila blocks wasn't replaced.
![image](https://user-images.githubusercontent.com/64156241/111070974-1b941980-84e5-11eb-9a8e-012e2df547ee.png)

Minecraft: 1.16.4 Forge
Java: 1.8.0_281 64 bits
Create: mc1.16.3_v0.3b
Chisel and Bits: 0.2.9-Release

**Comment by marchermans** [comment]
Yes this happens when mod updates are applied with older C&B releases. 

You need at least C&B 0.3.0 or better to prevent this from happening.
