### ISSUE TITLE
Chisel and Bits rejecting clientside version even if files and versions are the same.

### ISSUE THREAD

**Issue by archonxgames** [ChiselsAndBits/Chisels-and-Bits#638]
MC Version: 1.16.5
Chisels and Bits Version: 0.3.4 - RELEASE

Error when joining a server: Channels [chiselsandbits:chiselsandbits] rejected their client side version number

Reproduceable by copying the mod jar file to the server mods folder.

**Comment by marchermans** [comment]
I will need the logs from both the client and the server side.
Since i can't reproduce this locally.

**Comment by archonxgames** [comment]
Trying to locate the logs at the moment. It fixed itself when I downloaded the previous version and went back to the latest version after running the previous version (0.3.3) at least once on the server.

**Comment by marchermans** [comment]
So it fixed it self?
Even on the latest?
