### ISSUE TITLE
mode change requires 2nd key press to confirm

### ISSUE THREAD

**Issue by Rodg88** [ChiselsAndBits/Chisels-and-Bits#639]
When I press the keybind to bring up the radial menu, and change modes or select undo etc, the selected option doesnt take effect instantly, I need to press the menu keybind button a 2nd time to 'confirm' the choice. I've cleared any conflicting keybinds, and it still happens.

For any bug reports please provide the following details as well,
* MC Version: 1.16.5, forge 36.1.0, enigmatica 6 modpack
* C&B Version: 0.3.4
* Do You have Optifine: no

**Comment by marchermans** [comment]
Fixed in the latest beta
