### ISSUE TITLE
Potential Issue with C&B and "Farmer's Delight"

### ISSUE THREAD

**Issue by CptPICHU** [ChiselsAndBits/Chisels-and-Bits#640]
!Important
This issue should only happen when updating an EXISTING world. Farmer's Delight 0.3.2 -> 0.4

Description
I used "Chisels & Bits 0.3.4" at 1.16.4. and "Farmers Delight 4.0" at 1.16.4.
There i encountered a heavy issue: Chiseled Blocks from C&B had mixed materials.
Oddly enough not all materials have been replaced. The Problem occured right after updating Farmer's Delight to 4.0.
As i did a downgrade to Farmer's Delight 0.3.2 with a world Backup the issues where gone. Materials where no longer mixed.
It is important to say that i use a 90+ Mods Modpack and i absolutely CANNOT say for sure, that Farmer's Delight is the main issue here. However, 0.4 caused the issue 0.3.2 did not. It MAY have something to do with the FD Forge Tag rewrites? I'm really not sure. I can provide you the tools to replicate the issue.

1. Download my EXACT Modpack "PICHUPack PRO" in the Technic Launcher.
2. Create a world and build some Chisels and Bits Blocks with optimally lots of mixed materials.
3. The Pack includes FD 0.3.2. Replace it with 0.4 and open the world again.
4. The issue should be visible by some Chiseled Blocks being different.
If you have ANY issues testing, please comment here! Also please read logs if you want. I can't find anything in there. (No, reallly i did not)
If the issue is caused by something else in my Pack, i'm sorry for that.
But i have my reasons to believe that there might be a conflict between FD and C&B.

MC/FORGE: 1.16.4 / 35.1.36
FARMERS DELIGHT: 0.4
CHISELS & BITS: 0.3.4

If you CANT reproduce the material mixing, try using "Polished Lavastone" out of my Pack from Extended Caves Mod. Yeah i know what you think. It is not even from Farmer's Delight. That is true, but this is one of the Materials that got shuffled. Downgrading Farmer's Delight after Loading a Backup had the issue not happening again.

I'm not 100% if nothing else out of my Pack had anything to do with it.

Btw - OptiFine is included but i don't think there is anything related.

**Comment by marchermans** [comment]
Interesting
Can you send the affected world as well as your back up?

Preferably make a new world. Make a C&B block that you know changed. Then create a backup of that world and update and then send me the backup with the world as well, so I have an easier time debugging this.

**Comment by vectorwing** [comment]
Hi! I was able to replicate the issue above on a minimal instance, using the latest release of my mod alongside C&B and (seemingly) any block-adding mod. It reverts when my mod is downgraded back. I posted some details here:

https://github.com/vectorwing/FarmersDelight/issues/242

I'm really not sure what could be causing it, or if I made any mistakes during register, but I suspect Forge ID distribution might be involved. 0.4.0 only adds one block (Shepherd's Pie), and some chiseled blocks seem to adopt its different "facing" states in place of the original modded blocks.

**Comment by marchermans** [comment]
I found the issue.
C&B has a problem in its palette data.

I thought I fixed it, but I need to rewrite it as it looks like.

Will take me a some time to fix.

**Comment by Devoev** [comment]
Hi, I'm experiencing this issue as well. Is there any temporary fix (like downgrading C&B) until a new update is released?

**Comment by CptPICHU** [comment]
@Devoev downgrading Farmer's Delight until the issue is fixed seems to be the solution. If you corrupted any worlds, doing this should also revert the corruption.

**Comment by Devoev** [comment]
@CptPICHU Unfortunately this didn't work. I started my world with Farmer's Delight 0.4.0 and C&B 0.3.4. Anytime I downgrade Farmer's Delight and/or add/update any other block adding mods, all my C&B textures get mixed.

**Comment by CptPICHU** [comment]
@Devoev if you started on the newest FD cant you just keep it? Or does this not fix anything? Got any world backups?

**Comment by Devoev** [comment]
@CptPICHU Sorry I didn't describe my problem that well. The issue is, that I can't add any new mods, that add new blocks (or up/downgrade existing mods). Every time the C&B textures get mixed. The world and modpack in its current state work fine though.
