### ISSUE TITLE
Mode Wheel doesnt Appear, Mod Config Button dont work

### ISSUE THREAD

**Issue by GatorAli** [ChiselsAndBits/Chisels-and-Bits#641]
The Mod itself seams to work, as far as i can tell. Iam Totally new to this. 
Changing modes only work with caps+Mouse Wheel. The different modes seam to work as expected.

But, Mode Wheel and Off Grid placement dosnt work. No wheel visible. moving mouse while pressing alt does not reslut in a changed mode. So i assume its not only not visible.
The mod configuration button is grayed out. But not sure if this is a C&B thing or a different thing.

Testet it also with no mods except C&B, same thing

* MC Version: 1.16.5
* C&B Version: 0.3.4 RELEASE
* Do You have Optifine: yes
* FORGE 36.1.0

**Comment by marchermans** [comment]
Did you bind a keybinding in minecraft a keys menu?

**Comment by GatorAli** [comment]
Oh man i didnt thought on that. I thought keybinds for C&B are in the C&B specific Mod Config. Feeling stupid now :D

So there where no standard key binds set in the C&B section of the MC keybind menu. I set alt for radial menu.  Thanks and sry for wasting time.
