### ISSUE TITLE
Bug: Snapping and wrench

### ISSUE THREAD

**Issue by Wild-Rod** [ChiselsAndBits/Chisels-and-Bits#644]
Bug:
* MC Version: 1.16.5 forge
* C&B Version: C&B 0.3.4 for 1.16.5
* Do You have Optifine: no

so I'm kinda new to the chisel and bits mod so I don't know everything but when I was on chisel and bits (just chisel and bits no other mod) I found a bug I think. so I was watching the tutorial on the chisel and bits page on curse forge and when they say hold shift and the thing won't snap when you place it started snapping, also when I tried using the wrench it also didn't work for me so I don't know what to do. thank you. I don't know if this is for all versions or if it's me I have no clue.

**Comment by fireboy3100** [comment]
The wrench doesn't work for me either and I'm not sure why. However, I know the reason the grid doesn't work. It's because in the creator has made it a keybind now, meaning you have to go into controls and change it to something.

**Comment by marchermans** [comment]
Sot he wrench is currently disabled because the code it relied upon was removed from the game and/or heavily changed.

It will come back once the rebuild has finished.

The snapping to the grid is indeed a keybind you need to set.

**Comment by Wild-Rod** [comment]
thanks
