### ISSUE TITLE
The chisel isn't working

### ISSUE THREAD

**Issue by Gameri1** [ChiselsAndBits/Chisels-and-Bits#646]
I am playing on the mod pack sky bees and I am trying to use the chisel but it just doesn't work. When I try to break the bits the block just disappears for a second and then comes back as a vanilla block with no bits missing.

For any bug reports please provide the following details as well,
* MC Version: 1.16.5
* C&B Version: 0.3.2 release
* Do You have Optifine: no

**Comment by rayofsins** [comment]
I'm having the same issue

**Comment by marchermans** [comment]
Update to the newest beta
