### ISSUE TITLE
"Made for an older version"

### ISSUE THREAD

**Issue by OmegaX123** [ChiselsAndBits/Chisels-and-Bits#647]
* MC Version: 1.16.5
* C&B Version: 0.3.4
* Do You have Optifine: Yes, but the issue isn't in-game, it's with the versioning. Also tried it both with and without Optifine.

This mod (as well as several others, most of which I know are updated for 1.16.5 or at least have reported compatibility), are claiming to be "made for an older version of Minecraft" and not allowing me to create a world using them, only giving me the options to load in "Safe Mode" (load only the default datapack) or go back to the menu and fix it manually.

**Comment by marchermans** [comment]
I can't reproduce this.
Do you have any other mods loaded?

**Comment by OmegaX123** [comment]
I have 165 mods including this and Optifine, but I'm not sure how that would affect the version detection.
Here's my mod list:
https://pastebin.com/6Nc2x0Ek

**Comment by marchermans** [comment]
The screen you are getting is related to custom worldgen, not to C&B.
I tested this and asked around C&B is not the cause.

You can validate this, with just an instance that contains forge and C&B.

As such I am closing this.

**Comment by OmegaX123** [comment]
Premature close, because it's literally telling me that C&B specifically, as well as some other mods, are "made for an older version", lighting specifically them up in red (none of which are custom worldgen), and flagging them as "Incompatible".
EDIT: Specifically the datapacks that they install.

**Comment by marchermans** [comment]
Screenshots then please.

**Comment by OmegaX123** [comment]
[Screenshots](https://imgur.com/a/4g11PMx) - first one is most relevant to this discussion. I was mistaken in that some of them do _have_ worldgen, but not all of the ones being flagged (and again, this mod is specifically being flagged as incompatible/made for an older version).
EDIT: And most, if not all, of the ones being flagged (including yours) are either made for, or at least flagged compatible on Curseforge with, 1.16.5.

**Comment by marchermans** [comment]
Yeah so? Just because that datapack is not marked as being for 1.16.5 does not mean that C&B causes that window.
I need to mark that datapack to be for an older version to be compatible with older MC versions in one jar.

I still see no reason that C&B is the cause of the warning window, neither can I reproduce this.
Can you reproduce this with only C&B installed?

**Comment by OmegaX123** [comment]
It looks like we were both wrong about what the cause was, the original problem seems to have been caused by RFTools which I'm fairly sure doesn't have worldgen. Though now other mods (which the Blame logs seem to imply are worldgen based) are causing a different problem (lets me create a world, but gets stuck at a low % during worldgen). In any case, it looks like you were right about what the problem _wasn't,_ so I'm closing the issue.
