### ISSUE TITLE
Optifine and shaders give me Texture Error

### ISSUE THREAD

**Issue by FlameFer626** [ChiselsAndBits/Chisels-and-Bits#649]
Keeps giving me the texture error with shaders and optifine everything is up to date but just keeps giving me texture error how do i fix this 

* MC Version: 1.16.1 
* C&B Version: chiselsandbits-0.0.6-BETA.jar
* Do You have Optifine: yes

**Comment by markrobertstrange** [comment]
If it's the repeating OpenGL error I suspect, you can go the Video Settings, Other, the click Show GL Errors to Off.
