### ISSUE TITLE
Connected textures

### ISSUE THREAD

**Issue by ghost** [ChiselsAndBits/Chisels-and-Bits#65]
I have noticed when chiseling blocks with connected textures (nameley things like glass, blocks from Chisel) that the connected textures no longer work when the block is chiseled. I know it will be quite problematic to implement some way for connected textures to work, but it may be something to look into in the future.

**Comment by AlgorithmX2** [comment]
There are some plans to do integration and provide this feature with chisel but it requires some work on both sides to become viable.

Others mods are probably unlike, since it requires effort on both sides to make possible.

**Comment by MissPotato** [comment]
Kind of an old request, but I wanted to mention that Ender IO facades achieved Chisel connected textures support. I don't know if something in there can help.

**Comment by AlgorithmX2** [comment]
It doesn't really help, they do it by wrapping the world, an inherently dangerous thing to do in any cause, even if done however it doesn't necessarily solve the issue, since C&B is inherently 4096 times as complex ( cause its not just "full blocks" )

This has been looked into at least 3 times, and I've talked with chisel folks a number of times, so far there hasn't been any real developments.

**Comment by MissPotato** [comment]
I'm no coder, so I don't know about the possibility, but what about a texture-slider? Seeing as connected textures are saved as a map, one could just "select" the best texture spot.

**Comment by AlgorithmX2** [comment]
I don't think that is a good solution,  allowing people to just slide the textural around on bits could expose textures not intended for display, or allow you to change one block into another depending on how textures are used by the mod.

It would also require some kind of gui and behave in a way that is unusual for C&B.

**Comment by MissPotato** [comment]
Very fair point, hadn't even thought about that!

**Comment by ghost** [comment]
If you can't 'slide' textures, how about rotating them? It would allow for different orientations of blocks which only provide a single orientation.

As to the need for connected textures to be supported on both sides, it is possible to write some sort of library which would both make working with textures easier, and would automatically support connected textures for chisels and bits. You might find it easier to get devs to adopt a library that makes their texture work easier, than just getting them to support your mod.
