### ISSUE TITLE
Bamboo everything Forge and Styled Blocks Forge

### ISSUE THREAD

**Issue by Drycinhound** [ChiselsAndBits/Chisels-and-Bits#656]
Before continuing if you are reporting an issue, please ensure that all mods involved are updated to the latest version available, if your issue with with intermod compatibility such mixing C&B bits with other blocks make sure that MCMP is also updated. If your issue is a crash, be sure to include the crash log with your report.

For any bug reports please provide the following details as well,
* MC Version: 1.16.5
* C&B Version: Release 0.3.4
* Do You have Optifine: Yes

So the latest Update on Architectury API and Bamboo Everything Forge latest update. it causes the chiseled bits to go missing. and the same happens for both latest of Carrots Library and Styled Blocks.

**Comment by marchermans** [comment]
Fixed in the latest beta
