### ISSUE TITLE
Modded Bits mixed texture upon each world load

### ISSUE THREAD

**Issue by Drycinhound** [ChiselsAndBits/Chisels-and-Bits#657]
Before continuing if you are reporting an issue, please ensure that all mods involved are updated to the latest version available, if your issue with with intermod compatibility such mixing C&B bits with other blocks make sure that MCMP is also updated. If your issue is a crash, be sure to include the crash log with your report.

For any bug reports please provide the following details as well,
* MC Version: 1.16.5
* C&B Version: Release 0.3.4
* Do You have Optifine: yes.

So I think this is a bug, but every time I reload my world the bits mis/mixxed textures with other stuff. I don't believe it should do that. but so I am using latest stuff everything.

**Comment by marchermans** [comment]
Fixed after updating to latest version. Bug can and likely will happen once during the update process.
