### ISSUE TITLE
Any way to remove parts of the bark of a tree log?

### ISSUE THREAD

**Issue by ftzi** [ChiselsAndBits/Chisels-and-Bits#658]
I really wanted to do some arts in logs (properly removing the bark and having a naked wood below), but as I saw, this mod will keep the textures of each face of the block.

Is there a way to do it? If not, it is a feature request, at least for logs, where I can see it would be very good.

Thanks!

**Comment by marchermans** [comment]
Use the stripped log bits.

You can make bits of stripped logs and place those unplace of the bark to mix and match when you want to.
