### ISSUE TITLE
Mod works incorrectly with Mohist Servers [1.16.5]

### ISSUE THREAD

**Issue by blix5** [ChiselsAndBits/Chisels-and-Bits#659]
For any bug reports please provide the following details as well,
* MC Version: 1.16.5
* C&B Version: Release 0.3.4
* Do You have Optifine: Doesn't matter (Server)

When I switched from a Forge server to Mohist, all of the previously chiseled blocks disappeared and were untouchable until I placed any chiseled bit in the space and broke it with my hand. 

New chiseled structures work fine, but copying the block results in it having its preview and data removed when sent to the inventory according to the server, and when placed, nothing happens.

**Comment by marchermans** [comment]
External issue rates to mohist. Closing.
