### ISSUE TITLE
Additive Designs

### ISSUE THREAD

**Issue by Glockshna** [ChiselsAndBits/Chisels-and-Bits#66]
I would like to suggest an Additive mode and Destructive mode for positive designs. One will only add missing bits to the block space, and the other works as positive designs do currently. 

I made a video showing how I accomplish this currently, but thought it worthy of a feature request.

The video: https://www.youtube.com/watch?v=_XqFvCovFNI

**Comment by AlgorithmX2** [comment]
Done.
