### ISSUE TITLE
chiseled block has invisible side

### ISSUE THREAD

**Issue by EnderTrekkie** [ChiselsAndBits/Chisels-and-Bits#661]
when I chisel a block and place a slab or stair, etc, next to it, that side goes invisible, allowing for x-raying within that block. luckily, with how minecraft renders, the blocks past it are not x-rayable.

image:
![2021-04-15_15 34 26](https://user-images.githubusercontent.com/63455321/114946479-171e9180-9e00-11eb-9ab0-ae6654aab20c.png)

* MC Version: 1.16
* C&B Version: 0.3.4
* Do You have Optifine: no

**Comment by TheSnowyChickens** [comment]
Hi,
same issue for me.
(I play  Enigmatica 6)

![grafik](https://user-images.githubusercontent.com/29357962/115798385-70755a80-a3d6-11eb-90fc-21293ccdb8bf.png)
