### ISSUE TITLE
Block type of the chiseled object randomly changes

### ISSUE THREAD

**Issue by Guy-IV** [ChiselsAndBits/Chisels-and-Bits#663]
Version-1.16.5
Mod Version-0.3.4
Optifine-Yes
Reopening a world save or restarting a server makes some chiseled objects change their block type and texture. For example on my single-player world, I had a railing made of dark oak wood and black concrete (both vanilla) but when I opened it later the concrete changed to light blue glazed terracotta (also a vanilla block) but the dark oak wood didn't change. Just now I restarted my server and a statue that is made of multiple blocks had one type of block change to the bricks used in the floor. This does not just affect the singular block but all the blocks like it. Just to reiterate, it's not a visual glitch with the textures, it changed to a different block type completely, as if you break off a bit it will be light blue glazed terracotta not just black concreate with a different texture.
![2021-04-25_18 29 33](https://user-images.githubusercontent.com/77949703/116011745-90826500-a5f4-11eb-8e43-41d960f6ee92.png)

**Comment by S74RDU57** [comment]
Can confirm, had this issue as well on a server I play on. 
![Screenshot (1365)](https://user-images.githubusercontent.com/83199126/116103912-067ede80-a67e-11eb-9106-96cb932b01c1.png)
![Screenshot (1364)](https://user-images.githubusercontent.com/83199126/116103916-07b00b80-a67e-11eb-8dcf-7c7a47abf08e.png)
![Screenshot (1363)](https://user-images.githubusercontent.com/83199126/116103920-0848a200-a67e-11eb-9075-8a757d0cd2fc.png)

**Comment by DMangoldD** [comment]
modpack Valhelsia 3 (version 3.3.0)
minecraft (version 1.16.5)

I have the same issue. The block type and color of chiseled blocks changed after I updated Valhelsia from version 3.2.0b to 3.3.0.

**Comment by S74RDU57** [comment]
I use ATM6; are there any specific patch notes in the Valhesia update that
might refer to this? Trying to find the cause

**Comment by galotho** [comment]
This happened to me too! and then everything that changed, is now gone

**Comment by NielsPilgaard** [comment]
This also happened in Enigmatica 6 between update 0.4.8 and 0.4.9, C&B version 0.3.4 in both modpack versions. We added several mods in 0.4.9, I'm guessing that's the cause.

**Comment by jeffth92** [comment]
Same problem! friend updated our server and its modpack, and now my glowstone tiles became dark oak half drawers?
![2021-05-22_19 41 04](https://user-images.githubusercontent.com/79293267/119244923-28676600-bb43-11eb-8031-a8bd95f13880.png)

**Comment by chimericdream** [comment]
I see that this is tagged as "On Hold: Rebuild". Is there a Discord server or someplace where we can go for updates on the rewrite?

**Comment by marchermans** [comment]
https://discord.gg/G4rcMbxQ

Yes
The discord already contains a test build, which is incomplete.

**Comment by marchermans** [comment]
Fixed after updating to the latest beta. Can still occur once during the update process.
