### ISSUE TITLE
Mod causes blocks to become unbreakable

### ISSUE THREAD

**Issue by ZAMODA** [ChiselsAndBits/Chisels-and-Bits#668]
I was in my custom modpack on a server and I tried testing out the chisels and bits on a dark oak block, when I chiseled it I could no longer break it. It only happened once at X100 Y99 Z-293 When I moved it acted as it should.
I should mention that the block was next to a conveyor belt from the Create mod. When the Conveyor belt is next to the block, that face that is facing the conveyor goes invisible.

Mods:
Applied Energistics 2
Architectury API (Forge)
Biomes O' Plenty
Create : Stuff Additions
Create Crafts & Additions
Dynamic surroundings
JEI
Portality
Simple Guns: reworked
Tinkers Construct
AppleSkin
BetterEnd (Forge)
Blood Particles
Building Gadgets
Carry On
Chisels & Bits (of course)
Colds: Slimy Chunks (Forge)
Create
FTB Chunks (Forge)
FTB Library (Forge)
Gun Customization: Infinity
Immersive Engineering
Immersive Petroleum
Immersive Portals (for Forge)
Iron Chests
Mantle
Mekanism
Ore Excavation
Pams' HarvestCraft 2 - Crops
Pams' HarvestCraft 2 - Food Core
Pams' HarvestCraft 2 - Food Extended
Pams' HarvestCraft 2 - Trees
Storage Drawers
Titanium

All mods are the most recent they can be

* MC Version: 1.16.5
* C&B Version: 0.3.4 release
* Do You have Optifine: no

Any help is appreciated!

**Comment by ZilverLazarus** [comment]
I had this same problem a few minutes ago. Tried chiseling Nightshade Planks from BYG, in Creative Mode, using a Diamond Chisel (and Netherite Chisel) in plane mode. The block's hitbox disappears, and you can't destroy it by hitting it. The only way I managed to get rid of it was by using WorldEdit.

------------------------------------------------------------------------

Further info: Upon relaunching the game, it fixed itself. However, this bug might have to do with what I was doing beforehand.

Before using the chisels, I was playing around with a Netherite Saw in Creative Mode and placing down the blocks that were a result of it. Maybe that could have caused this to happen?

**Comment by ZilverLazarus** [comment]
Further info: Upon relaunching the game, it fixed itself. However, this bug might have to do with what I was doing beforehand.

Before using the chisels, I was playing around with a Netherite Saw in Creative Mode and placing down the blocks that were a result of it. Maybe that could have caused this to happen?

**Comment by RinateZ** [comment]
I also am having the same issue. Although it seems to mainly do it when I'm using draw region. My work around to break it is to have my friend break it because it only is unbreakable to me.

**Comment by Trawetsmail** [comment]
Can confirm this same issue. It also seems to worsen overtime, if you reload the game, and continue to edit the same block. It's gotten to a point where I literally can't play the game for more than ten seconds without it bugging out, and forcing a game reload.  This needs to be patched.

**Comment by SafsoufaS** [comment]
The same thing happens with me, but with every block. I can't fix anything because of this issue, and I don't want to have to waste 10 minutes loading a modpack just for one little bit that's out of place and that can't be broken

**Comment by marchermans** [comment]
Please update to the newest beta,
