### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by PortalOddities** [ChiselsAndBits/Chisels-and-Bits#669]
Current MC version: 1.16.5
C&B version: 0.3.4
Optifine: No

I'm making houses on a superflat [overworld] and it keeps crashing when I place more types of blocks [i.e. i can't place wool bits when there's already 15 other different blocks on there. doesn't matter on the amount of those 15 blocks] 

Simple crash report: The game crashed whilst unexpected error
Error: java.lang.StackOverflowError: Unexpected error
Exit Code: -1

[crash-2021-05-09_15.45.40-client.txt](https://github.com/ChiselsAndBits/Chisels-and-Bits/files/6448289/crash-2021-05-09_15.45.40-client.txt)

I have tried allocating more memory to it, and I'm running two games at once since the world with the bits is supposed to be a replica of another world. It is possible that the other instance is eating the memory, but I've yet to try that out.

**Comment by PortalOddities** [comment]
Tried it with only one game running, and it still crashes.

**Comment by PortalOddities** [comment]
Tried it out with only one of different bits [meaning, one block of different bits], and found the max of different blocks I can place on there without it crashing is 15. Is there a way to change this?

**Comment by marchermans** [comment]
Oeps that is a bug.

Sadly not something I can fix immediately.
I was able to reproduce it though.

At the moment c&b is undergoing a massive rebuild of it's internals including this logic.
This update should take care of all of this.

**Comment by marchermans** [comment]
Fixed in the latest beta
