### ISSUE TITLE
Using bags to place bits with some sort of radial menu implementation

### ISSUE THREAD

**Issue by Glockshna** [ChiselsAndBits/Chisels-and-Bits#67]
I would like to suggest allowing you to use the bit bag itself to place bits and use a radial menu to choose which bit types to place. The radial menu should include every bit type in all the bags in your inventory and remove the bits from the appropriate bag. This would free up inventory clutter substantially.

**Comment by AlgorithmX2** [comment]
Not sure if this will happen you could have a few thousand types of bits "in your inventory" displaying that in any sane way and letting you switch between them would be near nigh impossible.

I'd welcome other thoughts on it, but its something that would work well for a few items, and fall apart rapidly at scale.

**Comment by Glockshna** [comment]
Maybe the ability to open one bag and it displays all the bit types you have in your inventory in a searchable UI similar to Applied Energistics. From there you can set up to X favorite bit types you plan to build with to place on a radial menu. 

Spitballing here.

**Comment by AlgorithmX2** [comment]
That is probably more realistic, not sure that it really even needs any fancy GUI. Just the favorites is what makes the idea work.
