### ISSUE TITLE
Mirror designs are broken in 1.16.5 c&b 0.3.4

### ISSUE THREAD

**Issue by CorgiRetriever** [ChiselsAndBits/Chisels-and-Bits#670]
as title says, mirror chisel designs don't work. Whenever i craft them a blank comes out; 
![image](https://user-images.githubusercontent.com/75124521/117876631-e406db00-b2a3-11eb-94d9-3996b8849194.png)
It partially works with written positive designs but it's useless as they are made out of stone: 
![image](https://user-images.githubusercontent.com/75124521/117876765-06005d80-b2a4-11eb-86f6-7a2bce340619.png)
![image](https://user-images.githubusercontent.com/75124521/117876802-1284b600-b2a4-11eb-8771-6780b4f545ce.png)

**Comment by holyaurora21** [comment]
also have this same issue. Combinding them makes a blank design. It is not giving me a stone one with the positive though.....

**Comment by marchermans** [comment]
Fixed in the latest beta
