### ISSUE TITLE
create mod 1.15.2

### ISSUE THREAD

**Issue by emidblol** [ChiselsAndBits/Chisels-and-Bits#671]
hi i got the problem that if i start the mod up with create it crashes with a error about create

For any bug reports please provide the following details as well,
* MC Version:1.15.2

**Comment by COMarine1371** [comment]
Is the create mod up to date? i haven't had any crashes with that mod other than when trying to use the cannon on the chiseled and bits blocks lol

**Comment by emidblol** [comment]
Yes it is up to date

**Comment by emidblol** [comment]
If I use it in 1.16.5 it works really good

**Comment by marchermans** [comment]
As far as I know there is no 1.15.2 version of C&B 1?

**Comment by emidblol** [comment]
This is the version of c&b for 1.15.2

**Comment by marchermans** [comment]
![image](https://user-images.githubusercontent.com/5585406/118393844-7bbc4e80-b641-11eb-9531-5633105043ed.png)
There is no version for 1.15.2 of this mod.

As such closing this.
