### ISSUE TITLE
lighting error

### ISSUE THREAD

**Issue by IbexKitten** [ChiselsAndBits/Chisels-and-Bits#672]
The bits do not illuminate, I changed the setting of the percentage of light to 0, but it still does not illuminate.
1.16.5 optifine
0.3.4

**Comment by marchermans** [comment]
Is a known bug.

Will be fixed with the new bit engine once the update completes.

**Comment by Overkil04** [comment]
Hello guys could u pls tell me where to adjust those settings i mean where do i find this percentage of light ?
ty

**Comment by marchermans** [comment]
Ik the current it is still broken.
You need the prealpha from discord to fix it

**Comment by Overkil04** [comment]
Ok but where is the setting to control the the light percentage so when the update comes out i can use it?

**Comment by marchermans** [comment]
Fixed in the latest beta
