### ISSUE TITLE
Server Stall and Crash

### ISSUE THREAD

**Issue by liampearson96** [ChiselsAndBits/Chisels-and-Bits#674]
For any bug reports please provide the following details as well,
* MC Version: 1.16.5
* C&B Version: chiselsandbits-0.3.4-RELEASE.jar
* Do You have Optifine: Yes, however it is a server stall/crash.

https://pastebin.com/BiKQ5Q8W

**Comment by marchermans** [comment]
Arclight core problem.

They seem to be accessing block light strength during world load.
