### ISSUE TITLE
Half of my build is see through

### ISSUE THREAD

**Issue by COMarine1371** [ChiselsAndBits/Chisels-and-Bits#675]
I haven't played in maybe a week, everything is up to date. When I logged on half of my house was see through i.e. my custom walls. My roof is also custom but it's all there. I have seen other people have kind of the same issue where part of the block was missing but not all of it.. I have also tried doing some of the fixes that I looked up.... but all of those are also for the older versions. Please help I absolutely love this mod. Keep up the great work. 

For any bug reports please provide the following details as well,
* MC Version: Forge-36.1.3   1.16.5
* C&B Version: chiselsandbits-0.3.4-RELEASE.jar
* Do You have Optifine: yes OptiFine HD U G7
* Shaders: BSL v8.0.01

**Comment by marchermans** [comment]
The current version development is on hold.

We are aware of a bug that has problems with handling the world load/save and bit shifting which can indeed cause problems like this.

I am working as fast as I can on the update and only minor features are currently still missing before it is published into the wild.

**Comment by marchermans** [comment]
Should be fixed in the newest beta.
