### ISSUE TITLE
Glass & transparent blocks can't be chisled MC 1.16.5

### ISSUE THREAD

**Issue by UnassumingTroll** [ChiselsAndBits/Chisels-and-Bits#676]
MC 1.16.5
C&B 0.3.4-RELEASE.jar
No Optifine

I'm encountering this same issue. Suggest reopening.

_Originally posted by @nfcopier in https://github.com/ChiselsAndBits/Chisels-and-Bits/issues/536#issuecomment-826143758_

I have also encountered this issue, considering how long C&B 0.3.4-RELEASE has been out I'm sure someone has encountered this and the creators are aware of this bug.

**Comment by nfcopier** [comment]
This bug might be intermittent. Since I added the above comment, the issue has disappeared for me. It is also possible that my issues were due to user error. 😅

**Comment by UnassumingTroll** [comment]
Was using ATM6, but I re-downloaded the pack and now this works just fine.
I'm guessing something got borked in the first download.
