### ISSUE TITLE
Client crash - Unexpected Error

### ISSUE THREAD

**Issue by IITFA** [ChiselsAndBits/Chisels-and-Bits#678]
Before continuing if you are reporting an issue, please ensure that all mods involved are updated to the latest version available, if your issue with with intermod compatibility such mixing C&B bits with other blocks make sure that MCMP is also updated. If your issue is a crash, be sure to include the crash log with your report.

For any bug reports please provide the following details as well,
* MC Version: 1.16.5
* C&B Version: 0.3.4-RELEASE
* Do You have Optifine: yes

So, I was building a greenhouse on my server and placed a spruce door, then tried to chisel the inside edge of the block around the door and the client crashed. Server did not crash. The server is just a Forge server with a lot of mods.

Due to large size of crash log, had to gzip and attach.

[crash-2021-05-19_11.01.24-client.txt.gz](https://github.com/ChiselsAndBits/Chisels-and-Bits/files/6509948/crash-2021-05-19_11.01.24-client.txt.gz)

[modlist.txt](https://github.com/ChiselsAndBits/Chisels-and-Bits/files/6509958/modlist.txt)

**Comment by pj314cat** [comment]
SAME! >:( >:( >:(

**Comment by marchermans** [comment]
Please update to the latest beta 1.0.2
