### ISSUE TITLE
Bug: bits logging out each mod update and install

### ISSUE THREAD

**Issue by emeraldran** [ChiselsAndBits/Chisels-and-Bits#679]
Before continuing if you are reporting an issue, please ensure that all mods involved are updated to the latest version available, if your issue with with intermod compatibility such mixing C&B bits with other blocks make sure that MCMP is also updated. If your issue is a crash, be sure to include the crash log with your report.

everything is updated.
latest chisel and bits 0.3.4 release.
latest optifine
minecraft 1.16.5 

and the bits like disappear each time a mod is reinstalled or uninstalled or installed. seems like it is if the mod adds a block. but so I have to uninstall a shader or resource relaunch game and then when they are loaded I put the pack back in. it is annoying

For any bug reports please provide the following details as well,
* MC Version:
* C&B Version:
* Do You have Optifine:

**Comment by marchermans** [comment]
This is known. Please update to the latest beta.
