### ISSUE TITLE
 game crashes while opening

### ISSUE THREAD

**Issue by Dedemus** [ChiselsAndBits/Chisels-and-Bits#680]
* MC Version: 1.16.3-1.16.4-1.16.5 Forge
* C&B Version: C&B 0.2.4...-...C&B 0.3.4 
* Do You have Optifine: No
* Cant even see main menu, for now im using fabric version of this mod :( 

[crash-2021-05-24_00.58.10-client.txt](https://github.com/ChiselsAndBits/Chisels-and-Bits/files/6529010/crash-2021-05-24_00.58.10-client.txt)

**Comment by baconnob** [comment]
+1

**Comment by marchermans** [comment]
Fixed in the newest beta.
