### ISSUE TITLE
Please reintroduce /setbit command

### ISSUE THREAD

**Issue by VolterMC** [ChiselsAndBits/Chisels-and-Bits#685]
* MC Version: 1.16.5 (Direwolf20 1.16 pack)
* C&B Version: 0.3.4
* Do You have Optifine: No

I've tried using the /setbit command from earlier versions only to discover it's not present in 1.16.5 version of the mod. The config entry is not existing. Am I doing something wrong or is the feature not yet ready?

**Comment by marchermans** [comment]
It is not there yet.

**Comment by marchermans** [comment]
Is comming.

**Comment by marchermans** [comment]
Implemented in the latest beta
