### ISSUE TITLE
How to add more editable block

### ISSUE THREAD

**Issue by NazarDoeH** [ChiselsAndBits/Chisels-and-Bits#687]
Hi I'm playing with TFC and I want to edit tree log, but I can't.
So I tried to edit configs and add this "B:net.dries007.tfc.objects.blocks.wood.BlockLogTFC=true"
But it's dosen't work.

* MC Version: 1.12.2
* C&B Version:  14.33
* Do You have Optifine: Yes

**Comment by marchermans** [comment]
Sorry 1.12.x is not supported any more.
