### ISSUE TITLE
Crash on Start

### ISSUE THREAD

**Issue by xuumz** [ChiselsAndBits/Chisels-and-Bits#688]
* MC Version: 1.16.1
* C&B Version: chiselsandbits-0.0.6-BETA.jar
* Do You have Optifine: Yes

Everytime it gives me a different block? I'll start the game up a couple of times, here's what shows up:

`The game crashed whilst rendering overlay
Error: java.lang.NullPointerException: Registry Object not present: chiselsandbits:chiselediron
Exit Code: -1`

`The game crashed whilst rendering overlay
Error: java.lang.NullPointerException: Registry Object not present: chiselsandbits:chiseledleaves
Exit Code: -1`
(It gave me this one about 3 times)

**Comment by gruniu8** [comment]
you have installed BETA of C&B mod so try downloading newer version

**Comment by marchermans** [comment]
Update to the newest beta.
