### ISSUE TITLE
Add-on

### ISSUE THREAD

**Issue by gruniu8** [ChiselsAndBits/Chisels-and-Bits#689]
* MC Version: 1.16.5
* C&B Version: none?
* Do You have Optifine: it doesn't matter

Can you make that ExtraBitManipulation mod (bit armor) for 1.16.5? i know i sould ask him but he (he = creator of ExtraBitManipulation mod) doesnt answer anymore.
If you can make that add-on mod to do this i would be really happy
thank you <3

**Comment by marchermans** [comment]
No sorry.
