### ISSUE TITLE
Not working in survival mode

### ISSUE THREAD

**Issue by leggomyriego** [ChiselsAndBits/Chisels-and-Bits#69]
My mod seems to not be working in survival. When chiseling, I don't see the areas I'm chiseling being removed nor are they giving me bits. I can hit the block with the chisel like an axe/pick axe, but all it does it slowly crack like I'm breaking the block and distort it giving. But if I change the gamemode to creative, it's works perfectly fine like it's supposed to.

I'm using version 1.8 on a forge server. Any help?

**Comment by AlgorithmX2** [comment]
Why are you using a build of C&B for 1.8.9 from January?

I'd start by updating, if that doesn't help I'd suggest testing with less and less mods to identify any incompatibilities with the mod.

## 

Also on the off chance you meant MC 1.8, not sure I can help you there, 1.8 hasn't been supported for a while now.

**Comment by leggomyriego** [comment]
Yes, I meant minecraft 1.8. The 1.8 C&B version is the only one that is compatible with my server. Anything newer than that is not compatible with my server unfortunately and if I update the server most of my other mods will not work. I suppose I'm out of luck for now then. Thank you for your response.

**Comment by AlgorithmX2** [comment]
That is unfortunate, Its sad that so many mods do not have newer versions available.

**Comment by AlgorithmX2** [comment]
For the record this bug was never reported on the final builds for 1.8, so I imagine that something else is conflicting, however that would likely require you to remove another mod to resolve, and since your adding C&B to your server that unlikely to be a good solution.
