### ISSUE TITLE
Major texture error

### ISSUE THREAD

**Issue by schmoozlir** [ChiselsAndBits/Chisels-and-Bits#690]
I downloaded C&B for use with the pehkui mod however when I attempt to use a chisel the block transforms into a weird texture that seems to be a texture error ill add a screenshot into the report. If this isnt a C&B error can someone help me figure out whats going on? The texture looks like an amalgamation of every texture in the game
![2021-06-18_13 41 57](https://user-images.githubusercontent.com/86128674/122609797-6c129a00-d033-11eb-8638-167c0f1444d1.png)

**Comment by gruniu8** [comment]
i know for sure it's not by the C&B or Pehkui mod, i played on both and nothing happened, try uninstalling other mods, downloading optifine or update your java

**Comment by gruniu8** [comment]
if not then can you put error message somewhere here?
(if it exists)

**Comment by gruniu8** [comment]
i'v had newest version of C&B Optifine and Pehkui with java 8 btw

**Comment by marchermans** [comment]
Please fill in the issue template.
Cause else I have no idea what the cause is.
But my guest is Optifine.
