### ISSUE TITLE
Game crashes when 15 or more blocks are used

### ISSUE THREAD

**Issue by LittleChuck** [ChiselsAndBits/Chisels-and-Bits#691]
My game is crashing when there are more than 15 block types used in a normal sized block area.
![Capture](https://user-images.githubusercontent.com/38821454/123009350-5f62ae80-d371-11eb-8de9-72d573201946.PNG)

[crash-2021-06-22_16.46.22-client.txt](https://github.com/ChiselsAndBits/Chisels-and-Bits/files/6697807/crash-2021-06-22_16.46.22-client.txt)

For any bug reports please provide the following details as well,
* MC Version: 1.16.5
* C&B Version: 0.3.4
* Do You have Optifine: Yes, it also crashes without Optifine

**Comment by marchermans** [comment]
Update to the newest beta.
It won't fix already broken blocks, but it will prevent it.
