### ISSUE TITLE
Game Crashes when placing chiseled block at world height.

### ISSUE THREAD

**Issue by SarcasticSigma** [ChiselsAndBits/Chisels-and-Bits#692]
* MC Version: 1.16.5
* C&B Version: 0.3.4
* Do You have Optifine: No.

The game crashes when placing a chiseled block at world height. I tested in a clean instance with just forge and chisels and bits and it was still happened.

[crash-2021-06-27_07.23.22-client.txt](https://github.com/ChiselsAndBits/Chisels-and-Bits/files/6721487/crash-2021-06-27_07.23.22-client.txt)

**Comment by marchermans** [comment]
Update to the latest beta.
