### ISSUE TITLE
Blocks becoming invisible when using a chisel on them

### ISSUE THREAD

**Issue by KatsouLive** [ChiselsAndBits/Chisels-and-Bits#693]
Whenever i use a chisel on a block it just becomes invisible. Im certain its the right version so i dont know how to fix it ):

For any bug reports please provide the following details as well,
* MC Version: 1.16.5
* C&B Version:
* Do You have Optifine: No

**Comment by KatsouLive** [comment]
same here ):

**Comment by rayofsins** [comment]
Still haven't found a solution?

**Comment by marchermans** [comment]
C&B version please.

**Comment by Syndaryl** [comment]
Same issue on 1.0.0-ALPHA, forge 36.2.2, other mods JEI 7.7.1.120, mouse tweaks 2.14, The One Probe 3.1.4

**Comment by Syndaryl** [comment]
I'm also having the block *next* to the block I'm chiseling going invisible, and some times the entire block I'm chiselling (and the fussy neighbor block) just... self delete. I can put a new block in their place after this happens.

Log File Attached but there's no errors in there after the world is created:
[latest.log](https://github.com/ChiselsAndBits/Chisels-and-Bits/files/7039604/latest.log)

It's the east-side neighbor that keeps blinking in and out of existence, in case that matters.

**Comment by windows10win7posreadywoeskio** [comment]
> I'm also having the block _next_ to the block I'm chiseling going invisible, and some times the entire block I'm chiselling (and the fussy neighbor block) just... self delete. I can put a new block in their place after this happens.
> 
> Log File Attached but there's no errors in there after the world is created:
> [latest.log](https://github.com/ChiselsAndBits/Chisels-and-Bits/files/7039604/latest.log)
> 
> It's the east-side neighbor that keeps blinking in and out of existence, in case that matters.

This also happens to me too.

**Comment by marchermans** [comment]
I applied several fixes for this in 1.0.2 and could not reproduce it anymore.
So I consider this ticket fixed. If this still happens for you, please try to get me a reproduceable case, so I can fix it properly. Greets,
Orion
