### ISSUE TITLE
Cant place custom blocks

### ISSUE THREAD

**Issue by zaze06** [ChiselsAndBits/Chisels-and-Bits#694]
Before continuing if you are reporting an issue, please ensure that all mods involved are updated to the latest version available, if your issue with with intermod compatibility such mixing C&B bits with other blocks make sure that MCMP is also updated. If your issue is a crash, be sure to include the crash log with your report.

I have only tested whit vanilla stone not any from chissel more then making them
making them in the world is fine but I cant place them If i have broken them from the world

For any bug reports please provide the following details as well,
* MC Version: 1.16.5
* C&B Version: 0.3.4
* Do You have Optifine: Yes

**Comment by marchermans** [comment]
Please update to the newest beta.
