### ISSUE TITLE
most transparent blocks become invisible

### ISSUE THREAD

**Issue by N30N-N1NJ4** [ChiselsAndBits/Chisels-and-Bits#695]
I'm not sure why this is for my world but at some point all my torches, lanterns, doors, glass (and glass panes) become invisible in the vicinity of my C&B build. (Sometimes they are visible when I look in a certain orientation but mainly they are invisible).

MC Version: 1.16.5
C&B Version: 0.3.4
Do You have Optifine: Yes

![2021-07-09_15 54 09](https://user-images.githubusercontent.com/87194806/125097790-62c69b80-e0ce-11eb-955c-1047993d4434.png)
![2021-07-09_15 54 18](https://user-images.githubusercontent.com/87194806/125097799-64905f00-e0ce-11eb-8dcb-2c3e81b7a0b8.png)
![2021-07-09_15 54 29](https://user-images.githubusercontent.com/87194806/125097801-6528f580-e0ce-11eb-96eb-52faf12d031a.png)

**Comment by marchermans** [comment]
Optifine related.
Not reproducable for me without it.
