### ISSUE TITLE
Bits behind partially-translucent blocks (stairs) do not render

### ISSUE THREAD

**Issue by IchHabeHunger54** [ChiselsAndBits/Chisels-and-Bits#696]
Not sure if this has already been reported, but anyway. Bits behind blocks that render partially solid and partially translucent (stairs in my case) do not render. (And yes, those are bits, because Quark's Diorite Pavements sadly doesn't have a stairs variant.

![2021-07-12_19 18 23](https://user-images.githubusercontent.com/52419336/125329979-6fedbf80-e346-11eb-8723-4ca5d597c45a.png)

* MC Version: 1.16.5
* C&B Version: 0.3.4
* Do You Have Optifine: No

**Comment by marchermans** [comment]
There is sadly nothing that I can change here.

C&B uses the Rendering mechanics integrated with Minecraft and we render each bit in the same renderlayer as its parent block.
