### ISSUE TITLE
Textures/Blocks change after some time

### ISSUE THREAD

**Issue by Beniblach** [ChiselsAndBits/Chisels-and-Bits#697]
Idk what is going on but when playing with this mod after some time the textures or mainly the entire block used for a chisel creation just changes for no reason.

I am playing in the newest mod version so this makes it even weirder.
![2021-07-17_04 33 39](https://user-images.githubusercontent.com/63110785/126022783-16582e43-966b-48e4-b2f0-c229abb9a5a6.png)

it used to be a diagonal stone brick walkway and not, well that.

**Comment by marchermans** [comment]
Yeah it is a known bug at the moment.
The core of the mod is currently undergoing a massive rewrite needed to fix this.

**Comment by marchermans** [comment]
Please update to the newest beta.
