### ISSUE TITLE
Strange crash with C&B

### ISSUE THREAD

**Issue by Hamsterpouch** [ChiselsAndBits/Chisels-and-Bits#699]
I love the C&B mod. However, if I break a C&B block or go to the clipboard tab, it will crash. I play with MC 1.12.2, with C7B 14.33. It used to work fine, but just randomly started happening. I also have Optifine to reduce lag. Another thing is the MC launcher says exit code 0, but in the MC output log it gives me -805306369.

[crash-2021-07-12_17.04.41-client.txt](https://github.com/ChiselsAndBits/Chisels-and-Bits/files/6843494/crash-2021-07-12_17.04.41-client.txt)

**Comment by marchermans** [comment]
Disable the clipboard for now.
It should fix it.

No clue what the cause is.

C&B is undergoing a massive update at the moment hence no updates coming out.
I need to fix a memory leak before I can release that update though.

**Comment by Hamsterpouch** [comment]
I just went into the config and disabled it. I will check to see if your suggestion works. Thanks!

**Comment by Hamsterpouch** [comment]
Your suggestion worked. Thank you for the help.
