### ISSUE TITLE
disappearing blocks

### ISSUE THREAD

**Issue by savannahbrooks** [ChiselsAndBits/Chisels-and-Bits#70]
in 1.10 forge, if you chisel out more than four bits, the entire block will vanish completely.  doesnt matter where or what type of block.

**Comment by AlgorithmX2** [comment]
Do you have optifine installed? I cannot reproduce this.

If you have optifine please refer to https://github.com/AlgorithmX2/Chisels-and-Bits/issues/60

**Comment by savannahbrooks** [comment]
I don't have optifine! Which one works best with this mod?

**Comment by AlgorithmX2** [comment]
I am not recommending Optfine, I'm asking for information about your setup.

Try removing other mods and see if its a conflict with another mod, as I said I cannot reproduce this with just C&B and Forge.

**Comment by savannahbrooks** [comment]
No I just have 1.10 forge and c&b

**Comment by AlgorithmX2** [comment]
Place take screen shots of your F3 screen and in-game graphics settings.
