### ISSUE TITLE
Server crashing, corrupted blocks?

### ISSUE THREAD

**Issue by TheTechPny** [ChiselsAndBits/Chisels-and-Bits#700]
For any bug reports please provide the following details as well,
* MC Version: 1.16.5
* C&B Version: chiselsandbits-0.3.4-RELEASE.jar
* Do You have Optifine: No

When my world first began everything was working fine and no issues. Now when a player goes to their base with ChiselBit blocks there, the server crashes with an incredibly vague crash log. I went into single player and isolated it to chunk 2872, -1026 in region 89,-33. I have attached the related world file, there are other mods include in the modpack but this issue occurred even when only chiselandbits was installed.

Region File - https://ufile.io/r70tyeoc
Crash log - https://pastebin.com/raw/6jEsWNFj

**Comment by TheTechPny** [comment]
It is worth noting that the mod itself is not the problem, the mod works until that chunk is loaded however, it is the mod that is causing the server to crash when that chunk is loaded.

**Comment by marchermans** [comment]
I don't see anything related to C&B in this log.
Please provide more details why you think this is a C&B issue.

**Comment by TheTechPny** [comment]
A player made some stairs in the region file I provided. Any time the chunk was visited the server would crash, I removed C&B and the crashing stopped. I added MCMT into the server after the C&B blocks were placed so I think MCMT caused them to corrupt

**Comment by marchermans** [comment]
Okey, then I will close this issue, since I can't fix this.
I recommend updating to the beta, but this might cause some lag on large constructs at the moment
