### ISSUE TITLE
crashing while trying to launch MC

### ISSUE THREAD

**Issue by callme258** [ChiselsAndBits/Chisels-and-Bits#703]
Before continuing if you are reporting an issue, please ensure that all mods involved are updated to the latest version available, if your issue with with intermod compatibility such mixing C&B bits with other blocks make sure that MCMP is also updated. If your issue is a crash, be sure to include the crash log with your report.

For any bug reports please provide the following details as well,
* MC Version: 1.16.5
* C&B Version: 0.3.4
* Do You have Optifine: nope

**Comment by callme258** [comment]
hello there, im using 60+ mods and thats my second mod which is crashing the game while almost completely launched the game. tried to launch with and without other mods. same problem, still crashing.

**Comment by marchermans** [comment]
Log files please.

**Comment by callme258** [comment]
Did you mean that black screen with some data which is opening after crash?

10 Ağu 2021 Sal ÖS 11:26 tarihinde Marc Hermans ***@***.***>
şunu yazdı:

**Comment by marchermans** [comment]
No i mean the log files like latest.log and debug.log in your logs directory

**Comment by pj314cat** [comment]
SAME! HOW TO FIX IT!!!!!!!!

**Comment by marchermans** [comment]
@pj314cat please upload your logs then.

**Comment by marchermans** [comment]
Closed due to staleness of the issue
