### ISSUE TITLE
Question: will game performance be decresed if there are too many chiseled blocks?

### ISSUE THREAD

**Issue by creamIcec** [ChiselsAndBits/Chisels-and-Bits#706]
I will create an enormous structure with C&B, but i'm concerned about whether it will affect the performance of game if there are too many chiseled blocks. I know, for few chiseled blocks, there won't be any effects on game but i'm not sure about the maximum(maybe it has?) of chiseled blocks that won't crash the game. I know this question seems strange and it maybe depends on a particular computer, but i want to ensure this early to avoid the potential problems that may occur through the progress of building.

* MC Version: 1.16.5
* C&B Version: release-0.3.4
* Do You have Optifine: yes

**Comment by FlameyFaucet** [comment]
It depends really. A big structure with a lot of chisel details will definitely drop the performance on devices not able to handle it. Just take a look at your computer's hardware and think: "Will i be able to performantly load all these tiny pieces?".

Also, it looks like you have optifine installed. Prepare for any catastrophic graphic issues!

**Comment by creamIcec** [comment]
> It depends really. A big structure with a lot of chisel details will definitely drop the performance on devices not able to handle it. Just take a look at your computer's hardware and think: "Will I be able to performantly load all these tiny pieces?".

Thank you! This leads to one more question: CPU, RAM, or graphic card, which one's performance affects the game mostly when using C&B? 
I consider updating my hardware if needed(Because I really need this mod to finish my work as there is no other mod like this one).

> Also, it looks like you have Optifine installed. Prepare for any catastrophic graphic issues!

It seems Optifine causes tiny problems. However, up to now, I didn't catch any catastrophic problems, But hope C&B will be more compatible with Optifine in the future.

And is there any convenient way to test it?
Maybe the `/fill` command can do this? I didn't find any chiseled block I can place with `/fill`.

**Comment by marchermans** [comment]
The performance depends.
C&B does a lot of caching, but it is still a `chunksection` in a single, do 16 blocks vertical match up a single entire chunk.

Which means more memory and cpu usage. Additionally the models you can generate could potentially contain a lot of vertices which means more GPU work. However in general it does not require more performance then a lot of other mods.
