### ISSUE TITLE
sodium reforged breaks the rendering of chisel and bits blocks

### ISSUE THREAD

**Issue by Nathan22211** [ChiselsAndBits/Chisels-and-Bits#707]
Before continuing if you are reporting an issue, please ensure that all mods involved are updated to the latest version available, if your issue with with intermod compatibility such mixing C&B bits with other blocks make sure that MCMP is also updated. If your issue is a crash, be sure to include the crash log with your report.

sodium reforged: https://www.curseforge.com/minecraft/mc-mods/sodium-reforged breaks the rendering of chisel and bits blocks
![2021-08-10_06 30 03](https://user-images.githubusercontent.com/35241068/128859521-83fa7f7d-9e8f-4df4-8975-df8772e5d433.png)

For any bug reports please provide the following details as well,
* MC Version: 1.16.5
* C&B Version: 0.3.4
* Do You have Optifine:no, but I did have sodium reforged

**Comment by GaiaB0t** [comment]
just came here to submit a bug report about this, can confirm

**Comment by marchermans** [comment]
Not related to Chisels and Bits. These are normal block models as far as Minecraft is concerned.
Report to Sodium Reforged.
