### ISSUE TITLE
Weird texture problem

### ISSUE THREAD

**Issue by ImLighte** [ChiselsAndBits/Chisels-and-Bits#708]
Placing any bit, or chiseling any block causes a really weird texture glitch. I am using 1.16.5, I tried the last release as well as the alpha build and neither work. I do not have optifine.

Below are a few screenshots of the issues as well as what mods I am currently using.

![2021-08-11_15 33 19](https://user-images.githubusercontent.com/88799822/129093586-893625c4-1eb4-49c2-a1c9-20b63c3c5864.png)
![2021-08-11_15 33 35](https://user-images.githubusercontent.com/88799822/129093597-aecc1d1c-0b3e-4699-98f5-ad25154d34fb.png)
![Random mod image](https://user-images.githubusercontent.com/88799822/129093735-6aea9417-af92-40e5-b310-09a04ed3a686.png)

**Comment by North-West-Wind** [comment]
Hey there. I saw you closed this issue, so I want to ask you, how did you solve this problem?
