### ISSUE TITLE
Many C&B blocks disappeared

### ISSUE THREAD

**Issue by jordanhuard** [ChiselsAndBits/Chisels-and-Bits#709]
I was playing earlier today on 1.16.4 using C&B 0.2.10. I had made one block (a stadium seat) and was using the positive chisel design to create many of these. By the time I had filled in about 500 seats, I was lagging a lot so I decided to restart the server. I tried to get back on but my server host doesn't support 1.16.4 anymore so I updated to 1.16.5. 

I decided to try the newest C&B version so I downloaded 1.0.0. Upon loading up the world, I headed back to the stadium and everything I had made with C&B looked weird (dark colored grainy and hazy blocks). In addition, I was experiencing badly compressed packet errors which kept causing the game to crash. I left the world and restarted the server this time trying C&B 0.3.4. I no longer experienced any errors, but all of those blocks that looked weird before were now just replaced with air. 

Was it my large stadium and my low-powered server that caused my progress to go corrupt or was it the 1.0.0 version of C&B? I'm not sure but I'm curious what caused it. It seems that all C&B blocks within a certain radius of where I was working went corrupt. Is it safe for me to play 1.0.0 or are more of my blocks going to go corrupt? I probably have 12 hours of work ahead of me to replace what I lost and I don't want to add any more to that. 

Please help, thank you!

For any bug reports please provide the following details as well,
* MC Version: 1.16.4 --> 1.16.5
* C&B Version: 0.2.10 --> 1.0.0 --> 0.3.4
* Do You have Optifine: No

**Comment by Vyxxxx** [comment]
Same exact thing happened to me

**Comment by marchermans** [comment]
You can't go back from 1.0.0 to 0.3.4

**Comment by marchermans** [comment]
And I have no clue if it was the 1.0.0 version or your server since you did not collect any logs

**Comment by Vyxxxx** [comment]
I started on 1.)0.3.4 --> 2.)1.0.0 --> 3.)0.3.4 --> 4.)1.0.0
1.)Everything was fine and normal
2.) There was 2 little pixels on my hud, and whenever I tried to place/mine a chiseled bit it would make all of them in the surrounding area invisible
3.)Reverted to 0.3.4, now every chiseled block in my world was gone
4.) Went back to the 1.0.0, and now every chiseled block was invisible and it says "Chiseled Rock" or something like that

Not sure if this is helpful, or if you could help me.

Edit: Sorry if this is "Hijacking" a post, that is not my intention.

**Comment by marchermans** [comment]
Again you can not go back from 1.0.0

**Comment by marchermans** [comment]
Backporting is not supported.
