### ISSUE TITLE
Cannot access menu for Chisels in 18.9

### ISSUE THREAD

**Issue by DarkbutGood1** [ChiselsAndBits/Chisels-and-Bits#71]
I am using the latest build for 1.8.9 and I cannot access the menu for the chisels in any way pressing left alt does nothing at all.

Please help soon.

**Comment by AlgorithmX2** [comment]
Please check your controls screen, if its red there is a conflict and you'll need to change some key bindings.

**Comment by DarkbutGood1** [comment]
Yes that is the problem thank you
