### ISSUE TITLE
Glitch

### ISSUE THREAD

**Issue by 227Dante** [ChiselsAndBits/Chisels-and-Bits#712]
Whenever I cut a piece of a block it pushes me back from the block and lags me.

For any bug reports please provide the following details as well,
* MC Version: 1.16.5
* C&B Version: 1.0.0
* Do You have Optifine: no

**Comment by marchermans** [comment]
Logs and a gif recording please so that I can try to reproduce this.

**Comment by marchermans** [comment]
Fixed in the latest beta.
