### ISSUE TITLE
Crash when I try and make a pattern

### ISSUE THREAD

**Issue by PercyJames** [ChiselsAndBits/Chisels-and-Bits#713]
see above. I hold the quill and I hold the paper I right click and then it crashes. it also crashes when I try to pickblock the pattern

https://pastebin.com/9BkPVEuu

For any bug reports please provide the following details as well,
* MC Version: 1.16.5
* C&B Version: 1.0.0
* Do You have Optifine: no

**Comment by marchermans** [comment]
Found it thank you.
Will be awaiting a commit in the next few days.

**Comment by Chansey529** [comment]
I have the same bug exactly.
The bug only occurs when I try to quill with the blocks from the older version (C&B 0.3.4). Blocks chiseled with the new version (C&B 1.0.0) works well when quilling and sealing.
Hope that it's helpful

**Comment by marchermans** [comment]
Fixed in the latest beta
