### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by Sunekaer** [ChiselsAndBits/Chisels-and-Bits#714]
https://s1.sunekaer.com/i/18-08-2021_23-50-26_%25pn.gif

For any bug reports please provide the following details as well,
* MC Version: 1.16.5 36.2.2
* C&B Version: chiselsandbits-1.0.0-ALPHA-universal.jar 
* Do You have Optifine: No

**Comment by Sunekaer** [comment]
No errors in log

**Comment by marchermans** [comment]
I would still like the logs please.
Can you try it in creative please?

**Comment by Sunekaer** [comment]
I removed RoadRunner and now it's doing this: https://s1.sunekaer.com/i/19-08-2021_17-28-57_%25pn.gif
Log with RoadRunner: https://paste.sunekaer.com/apovaqubuh.sql
Log without RoadRunner: https://paste.sunekaer.com/fekoheneqa.sql

RoadRunner (https://github.com/MaxNeedsSnacks/roadrunner)

**Comment by marchermans** [comment]
Yeah okey.
Sorry but this is a RoadRunner problem.

I am doing nothing weird, on the player interaction, i just update my TE data and request a redraw. RoadRunner does not seem to respect that redraw request.
As such I mark this issue as solved from our end.

**Comment by Sunekaer** [comment]
But as you see on the second gif without roadrunner there still is some weird lighting updates and I'm being pushed back when using the tool on the block

**Comment by Sunekaer** [comment]
Just tested chiselsandbits-0.3.4-RELEASE.jar without roadrunner and everything works fine
but chiselsandbits-1.0.0-ALPHA-universal.jar without roadrunner is doing some weird lighting updates and is pushing me back as you can see in this gif https://s1.sunekaer.com/i/19-08-2021_17-28-57_%25pn.gif

**Comment by marchermans** [comment]
Yeah It is known
Currently trying to track that down.
