### ISSUE TITLE
Rendering & Crash problems after update to 1.0.0 on ATM6 modpack

### ISSUE THREAD

**Issue by LasXor** [ChiselsAndBits/Chisels-and-Bits#715]
Heyo Server Admin here. Reporting a problem a Player encountered.

After the update from 0.3.4 to 1.0.0 on ATM a few preexisting blocks create a problem.

Acording to the Player:
`Those were luminous glass blocks that were inset into the marble, they looked pretty cool and lit the pathways, but after this update they are clearly broken.`

They currently cause a client crash if you look at them with `the one probe` active. With it inactive it doesnt cause a crash but still do not render. 

Also the blocks are unbreakable except from one side and create a server crash when broken by player.

Find attached a few files to help describing the problem:

[crash-2021-08-20_14.19.10-client.txt](https://github.com/ChiselsAndBits/Chisels-and-Bits/files/7023714/crash-2021-08-20_14.19.10-client.txt)

https://user-images.githubusercontent.com/38936297/130283778-2ae863b4-f6bb-43f0-b0c1-6b40ac158b1e.mp4

https://user-images.githubusercontent.com/38936297/130283779-952ed61f-09b5-4986-84b7-65dc41c262e5.mp4

[crash-2021-08-20_19.31.50-server.txt](https://github.com/ChiselsAndBits/Chisels-and-Bits/files/7023788/crash-2021-08-20_19.31.50-server.txt)

For any bug reports please provide the following details as well,
* MC Version: 1.16
* C&B Version: 1.0.0-ALPHA
* Do You have Optifine: well server doesn't :D (client eighter)

**Comment by beaussan** [comment]
Hello, server admin here too, I have the same issue, 

* Client crash : https://pastebin.com/1rDnCX0X
* Server crash : https://termbin.com/7cslx

**Comment by marchermans** [comment]
Does this happen right after the update?
If so, yeah, there is a bug in the older versions of C&B for 1.16 that causes this. The whole aim of the rebuild was to fix this bug internally. However by fixing it, the update process makes it instantly clearly visible that the bits would change over time when mods and blockstates change. You will need to rebuild those blocks, and you can't downgrade.

**Comment by marchermans** [comment]
Issue went stale
