### ISSUE TITLE
Can't break or add onto already existing bits (bits are broken)

### ISSUE THREAD

**Issue by SafsoufaS** [ChiselsAndBits/Chisels-and-Bits#717]
I am currently playing the Valhesia 3 mod pack and wanted to build something with Chisel and Bits. After sometime trying to build something with my bits, it suddenly just stops working. It acts as if it's not there at all. I can see it, but I can't interact with it. I can't break it, add anything to it, nothing. Restarting seems to work, but that shouldn't be the only solution. I've also tried restarting the chunks but doesn't work either.  I haven't changed anything in the mod pack either. Modpack is up to date, and here is the list

abnormals_core-1.16.5-3.1.1.jar
abnormals_delight-1.16.5-1.1.1.jar
absentbydesign-1.16.5-1.5.0.jar
Abundance-1.16.5-1.0.5.jar
advancedperipherals-0.6.7b.jar
AI-Improvements-1.16.2-0.3.0.jar
aiotbotania-1.16.5-1.7.0.jar
AkashicTome-1.4-16.jar
alexsmobs-1.11.0.jar
allurement-1.16.5-1.2.0.jar
AmbientSounds_v3.1.9_mc1.16.5.jar
Apotheosis-1.16.4-4.6.1.jar
appleskin-forge-mc1.16.x-2.0.0.jar
Aquaculture-1.16.5-2.1.19.jar
archers_paradox-1.16.4-1.2.0.jar
architectury-1.18.25-forge.jar
Artifacts-1.16.5-2.9.3.jar
astralsorcery-1.16-1.16.5-1.13.12.jar
atmospheric-1.16.5-3.1.0.jar
Atum-1.16.5-2.2.5.jar
AutoRegLib-1.6-49.jar
autumnity-1.16.5-2.1.1.jar
BackTools-1.16.5-10.1.0.jar
Bayou-Blues-1.16.5-1.0.5.jar
BedBenefits-1.16.5-5.0.3.jar
bedspreads-forge-1.16.5-5.1.0.2.jar
berry_good-1.16.5-4.1.1.jar
Better-Badlands-1.16.5-2.0.3.jar
BetterAdvancements-1.16.5-0.1.0.108.jar
betterbiomeblend-1.16.4-1.1.5-forge.jar
BetterBurning-1.16.5-6.0.6.jar
BetterCaves-Forge-1.16.4-1.1.2.jar
betterendforge-1.16.4-1.6.0.jar
BetterF3-1.1.3-forge-1.16.5.jar
BetterMineshafts-Forge-1.16.4-2.0.4.jar
BetterStrongholds-1.16.4-1.1.jar
BetterTitleScreen-1.16.4-1.10.2.jar
BiomesOPlenty-1.16.5-13.1.0.477-universal.jar
blockcarpentry-1.16-0.3.6.jar
BloodMagic-1.16.4-3.1.0-15.jar
Bookshelf-1.16.5-10.1.11.jar
Botania-1.16.5-416.jar
buzzier_bees-1.16.5-3.0.1.jar
bwncr-1.16.4-3.9.16.jar
caelus-forge-1.16.5-2.1.3.0.jar
carryon-1.16.5-1.15.5.15.jar
catjammies-1.1.0.jar
cc-tweaked-1.16.4-1.96.0.jar
cherishedworlds-forge-1.16.4-5.1.0.0.jar
chiselsandbits-0.3.4-RELEASE.jar
chocolate-1.3.0-1.16.4.jar
ChunkAnimator-1.16.5-1.2.4.jar
citadel-1.7.1-1.16.5.jar
ClientTweaks_1.16.3-5.3.0.jar
cloth-config-4.11.26-forge.jar
Clumps-6.0.0.25.jar
CodeChickenLib-1.16.5-4.0.2.427-universal.jar
cofh_core-1.16.4-1.2.1.jar
Colony4ComputerCraft-1.16.4-1.2.5.jar
comforts-forge-1.16.5-4.0.1.1.jar
Controlling-7.0.0.23.jar
CookingForBlockheads_1.16.5-9.3.2.jar
CosmeticArmorReworked-1.16.5-v3a.jar
CraftingTweaks_1.16.5-12.2.1.jar
create-mc1.16.5_v0.3.1c.jar
createaddition-1.16.5-20210626a.jar
CreativeCore_v2.2.0_mc1.16.5.jar
CTM-MC1.16.1-1.1.2.6.jar
curioofundying-forge-1.16.5-5.2.0.0.jar
curios-forge-1.16.5-4.0.5.2.jar
CuriosQuarkOBP-1.16.5-1.0.2.jar
Curious Armor Stands-1.16.5-2.1.1.jar
curiouselytra-forge-1.16.5-4.0.2.3.jar
curiousshulkerboxes-forge-1.16.5-4.0.1.0.jar
customizableelytra-1.16.4-1.5.0.jar
DarkUtilities-1.16.5-8.0.10.jar
dash-1.16.4-1.0.1.jar
decorative_blocks-1.16.4-1.7.2.jar
decorative_blocks_abnormals-1.2.jar
DefaultOptions_1.16.5-12.2.1.jar
Druidcraft-1.16.5-0.4.52.jar
dusk-1.4.jar
DynamicSurroundings-1.16.4-4.0.4.2.jar
eidolon-0.2.7.jar
elevatorid-1.16.5-1.7.13.jar
enchantedbookredesign-3.3-1.16.4.jar
endergetic-1.16.4-3.0.0.jar
EnderStorage-1.16.5-2.8.0.168-universal.jar
engineersdecor-1.16.4-1.1.13.jar
Enhanced-Mushrooms-1.16.5-3.0.8.jar
ensorcellation-1.16.4-1.2.0.jar
environmental-1.16.5-1.0.0.jar
etched-1.1.0-1.16.5-forge.jar
expandability-2.0.1-forge.jar
extlights-3.3.jar
extraboats-1.16.5-2.1.0.jar
fairylights-4.0.5-1.16.5.jar
FarmersDelight-1.16.5-0.4.3.jar
fastbenchminusreplacement-1.4.jar
FastFurnace-1.16.4-4.4.0.jar
FastLeafDecay-v25.jar
ferritecore-2.0.4-forge.jar
filenames.txt
fishingreal-1.16.3-1.0.0.jar
FluxNetworks-1.16.5-6.1.7.12.jar
forbidden_arcanus-16.2.0-beta-4.jar
Fruitful-1.16.5-2.1.0.jar
ftb-backups-2.1.1.6.jar
ftb-library-forge-1605.3.1-build.36.jar
GameStages-1.16.5-7.2.7.jar
goblintraders-1.6.0-1.16.3.jar
HealthOverlay-1.16.4-2.1.7.jar
iChunUtil-1.16.5-10.4.1.jar
ImmersiveEngineering-1.16.5-5.0.0-135.jar
ImmersivePetroleum-1.16.5-3.3.0-4.jar
immersiveposts-1.16.5-4.1.0.jar
incontrol-1.16-5.1.9.jar
industrial-foregoing-1.16.5-3.2.13.1-5.jar
InventoryHud_[1.16.2-1.16.5].forge-3.3.0.jar
inventorysorter-1.16.1-18.1.0.jar
ironchest-1.16.4-11.2.10.jar
Jade-1.16.4-2.7.1.jar
JAOPCA-1.16.5-3.4.0.9.jar
jei-1.16.5-7.7.0.106.jar
jeiintegration_1.16.5-7.0.1.15.jar
JustEnoughResources-1.16.5-0.12.1.121.jar
Kiwi-1.16.5-3.5.1.jar
KleeSlabs_1.16.5-9.2.1.jar
kubejs-blood-magic-1604.1.0.4.jar
kubejs-create-1604.1.0.4.jar
kubejs-forge-1605.3.11-build.31.jar
kubejs-immersive-engineering-1604.1.0.12.jar
kubejs-mekanism-1604.1.1.6.jar
kubejs-ui-1605.1.4-build.7-forge.jar
lazydfu-0.1.3.jar
leap-1.16.4-1.1.1.jar
LibX-1.16.3-1.0.76.jar
light-overlay-5.8.1.jar
Lollipop-1.16.5-3.2.9.jar
mannequins-1.0.1-1.16.5-forge.jar
mcw-bridges-1.0.5-mc1.16.5-4.jar
mcw-doors-1.0.3-mc1.16.5.jar
mcw-fences-1.0.0-mc1.16.5.jar
mcw-furniture-2.0.1-mc1.16.5.jar
mcw-roofs-2.0.1-mc1.16.5-4.jar
mcw-trapdoors-1.0.2-mc1.16.5.jar
mcw-windows-1.0.3-mc1.16.5.jar
Mekanism-1.16.5-10.0.21.448.jar
MekanismAdditions-1.16.5-10.0.21.448.jar
MekanismGenerators-1.16.5-10.0.21.448.jar
MekanismTools-1.16.5-10.0.21.448.jar
mgui-1.16.5-3.2.0.jar
mightyarchitect-mc1.16.3_v0.5.jar
minecolonies-0.14.237-ALPHA-universal.jar
mining_helmet-1.16.5-2.0.1.jar
MouseTweaks-2.14-mc1.16.2.jar
mowziesmobs-1.5.19.jar
mysticalworld-1.16.5-0.3.2.15.jar
MythicBotany-1.16.4-1.3.15.jar
NaturesCompass-1.16.5-1.9.0.jar
neapolitan-1.16.5-2.1.0.jar
Neat 1.7-27.jar
neoncraft-2.0.jar
netheritehorsearmor-1.7.jar
Notes-1.16.5-1.2.3.jar
observerlib-1.16.5-1.5.3.jar
OpenLoader-1.16.5-9.0.3.jar
overloadedarmorbar-5.1.0.jar
PackMenu-1.16.4-2.4.2.jar
paintings-1.16.4-7.0.0.1.jar
Patchouli-1.16.4-53.jar
Peculiars-1.16.4-1.1.0.jar
performant-1.16.2-5-3.66m.jar
personality-1.16.5-1.0.2.jar
pitg-1.16.3-1.4.2.jar
Placebo-1.16.4-4.5.0.jar
polymorph-forge-1.16.5-0.24.jar
Powah-1.16.5-2.3.16.jar
Psi 1.16-94.jar
Quark-r2.4-314.jar
QuarkOddities-1.16.3.jar
randompatches-2.4.4-forge.jar
ReAuth-1.16-Forge-3.9.3.jar
refinedstorage-1.9.13.jar
refinedstorageaddons-0.7.2.jar
rhino-1605.1.1-build.21.jar
rsrequestify-1.16.3-2.0.1.jar
Runelic-1.16.5-7.0.1.jar
savageandravage-1.16.5-3.1.0.jar
scuba-gear-1.16.5-1.0.3.jar
serverconfigupdater-1.3.jar
ServerTabInfo-1.16.4-1.3.3.jar
SimpleDiscordRichPresence-1.16.4-1.3.5.jar
SnowRealMagic-1.16.4-2.5.7.jar
snowundertrees-1.16.5-v1.1.4.jar
sounddeviceoptions-1.4.2.jar
spark-forge.jar
step-1.16.4-1.1.0.jar
Storage4ComputerCraft-1.16.4-1.2.2.jar
StorageDrawers-1.16.3-8.2.2.jar
structure_gel-1.16.5-1.7.7.jar
structurize-0.13.195-ALPHA-universal.jar
supplementaries-1.16.5-0.14.1.jar
swingthroughgrass-1.16.4-1.5.3.jar
tetra-1.16.5-3.12.0.jar
tetranomicon-1.3.jar
the-conjurer-1.16.4-1.0.13.jar
titanium-1.16.5-3.2.8.4-10.jar
Toast-Control-1.16.4-4.3.1.jar
ToolStats-1.16.5-6.0.1.jar
torchmaster-2.3.7.jar
torchslabmod-1.16.4_v1.6.19.jar
toughnessbar-6.1.jar
Transport-1.16.5-3.6.0.jar
TrashSlot_1.16.3-12.2.1.jar
twilightforest-1.16.5-4.0.490-universal.jar
upgrade_aquatic-1.16.5-3.1.0.jar
valhelsia_core-16.0.9.jar
valhelsia_structures-1.16.5-0.1.3.jar
valhelsia_tweaks-16.0.6.jar
Waddles-1.16.5-0.8.13.jar
WailaHarvestability-mc1.16.x-forge-1.1.15.jar
Waystones_1.16.5-7.6.2.jar
windowlogging-mc1.16.3_v0.0.4.jar
XaerosWorldMap_1.14.1_Forge_1.16.5.jar
Xaeros_Minimap_21.10.0.3_Forge_1.16.5.jar
xercamusic-1.16.5-1.4.jar
YungsApi-1.16.4-Forge-6.jar

For any bug reports please provide the following details as well,
* MC Version: 1.16.5
* C&B Version: C&B 3.4
* Do You have Optifine: No

**Comment by marchermans** [comment]
Update to the newest beta,
