### ISSUE TITLE
Strange Block breaking Behaviour

### ISSUE THREAD

**Issue by jakecroftford** [ChiselsAndBits/Chisels-and-Bits#718]
Recently the Daedalus server attempted to add chisel and bits as its a fan favourite however after the update went live it was found that no matter what block was broken nothing would drop including but not limited to chisel and bits blocks/bits, dirt or grass. It seemed that no matter what was broken no drops came of it and to fix the issue we had to not only remove the mod but also revert to an old backup from before the mod was added. if you wish to check out the daedalus modpack for possible mod conflicts it can be found in the curseforge launcher called "Daedalus server modpack" but with only 118 mods the pack was kept fairly small to help with performance.
For any bug reports please provide the following details as well,
* MC Version:1.16.5
* C&B Version:0.3.4
* Do You have Optifine: No
* Modpack: It happened on a private servers own curated modpack when introduced
* How it was fixed: as a temporary fix we uninstalled the mod only to find it didn't help and a rollback from before the mod was introduced was needed

**Comment by marchermans** [comment]
C&B Does not modify block drops.
I tried to reproduce this, but without logs, I am not sure what is going on.

And sorry, I can not go through everybody's modpack to track conflicts. If you want to get this fixed, you will have to find the conflict yourself, and then report it so I can reproduce it myself.

**Comment by marchermans** [comment]
Issue went stale
