### ISSUE TITLE
Trying to get color from air interaction with JEI

### ISSUE THREAD

**Issue by frakier** [ChiselsAndBits/Chisels-and-Bits#719]
Before continuing if you are reporting an issue, please ensure that all mods involved are updated to the latest version available, if your issue with with intermod compatibility such mixing C&B bits with other blocks make sure that MCMP is also updated. If your issue is a crash, be sure to include the crash log with your report.

For any bug reports please provide the following details as well,
* MC Version: 1.16.5
* C&B Version: chiselsandbits-1.0.0-ALPHA-universal.jar
* Do You have Optifine: NO
* Forge: 36.2.2

Modpack: Valhelsia 3 - 3.4.2a

Third Party Interaction: jei-1.16.5-7.7.1.118.jar

Previous Issues:
Looks like this was a issue back in 1.12 and you had to patch it.
https://github.com/ChiselsAndBits/Chisels-and-Bits/issues/386

Problem:
Crashes the client if you right-click wool.

[crash-2021-08-23_23.48.14-client.txt](https://github.com/ChiselsAndBits/Chisels-and-Bits/files/7036488/crash-2021-08-23_23.48.14-client.txt)

**Comment by SweetlilTrinket** [comment]
I am experiancing something very similar on my custom modpack, downgrading to the release for 1.16.5 seems to fix it for me.

**Comment by marchermans** [comment]
Fixed in the latest beta.
