### ISSUE TITLE
Water in the Nether

### ISSUE THREAD

**Issue by Jayceena** [ChiselsAndBits/Chisels-and-Bits#72]
**Issue:** While*\* I was working on my blaze farm a thought occurred to me. Using fluid bits can I get water into the Nether. Short answer is yes, long answer, well there really isn't one.

**Opinion:** I personally feel like being able to have water bits in the Nether should be a thing but not being able to create full source blocks.

(Also tiny suggestion, you should make a C&B subreddit for people to post their builds as my blaze farm is almost entirely C&B)

**Comment by AlgorithmX2** [comment]
Yes I agree, when the water block is formed it should evaporate immediately.

**Comment by AlgorithmX2** [comment]
I don't have a Reddit account, as I previously deleted it however if someone else wants to start that subreddit I wouldn't be against it.

**Comment by Jayceena** [comment]
Alright, if Reddit will allow me then I'll try.

**Comment by Jayceena** [comment]
Ehh Idk how to so someone else can xD
