### ISSUE TITLE
Feature return for post 1.0.0: Continue subtracting/adding on plane

### ISSUE THREAD

**Issue by Syndaryl** [ChiselsAndBits/Chisels-and-Bits#720]
on 0.3.4 there was the feature of being able to pick an existing carved plane of some random shape, and continue carving it along the same axis to a required depth, or reduce the depth. I found this very handy and would like it back when you have a chance :)

**Comment by Syndaryl** [comment]
I just reloaded the older version, the feature is called "Connected plane"

**Comment by marchermans** [comment]
Okey. I will see what I can do.

**Comment by marchermans** [comment]
I checked and I was not able to reimplement it exactly in the same way as it was before, but I implemented a hybrid of plane / connected plane / same material, it tries to achieve something similar but yeah I was not able to get it to be exactly the same as before.

Sorry.
