### ISSUE TITLE
Feature Request: Config option hide bits in JEI

### ISSUE THREAD

**Issue by Syndaryl** [ChiselsAndBits/Chisels-and-Bits#721]
The more mods with blocks that I add to my pack, the more cluttered my JEI gets with bits, making it hard for me to find the actual blocks. I expect many people find getting the bit directly to be handy, but I strongly prefer to pull the actual block and then chew it up into bits. A client-side option to hide bits in JEI would be very handy.

**Comment by marchermans** [comment]
Will be added to the next upcoming beta.
