### ISSUE TITLE
Random Invisible blocks spawning and Bit Bag not Working

### ISSUE THREAD

**Issue by Auseawesome** [ChiselsAndBits/Chisels-and-Bits#723]
Before continuing if you are reporting an issue, please ensure that all mods involved are updated to the latest version available, if your issue with with intermod compatibility such mixing C&B bits with other blocks make sure that MCMP is also updated. If your issue is a crash, be sure to include the crash log with your report.

For any bug reports please provide the following details as well,
* MC Version: 1.16.5
* C&B Version: 1.0 Alpha
* Do You have Optifine: Yes

When chiseling any block random invisible blocks spawn that push you around. lag and pollute the world, these are breakable. When i try to take bits from the bit bag it creates ghost items and the items remain in the bag.

**Comment by Auseawesome** [comment]
Also if you get stuck inside one of these blocks you can't move and if you go into spectator while inside it the game crashes but no crash message or log is created

**Comment by marchermans** [comment]
This should be fixed in 1.0.1. There was a rounding error.
