### ISSUE TITLE
Incompatible with Platforms MOD

### ISSUE THREAD

**Issue by DocLockWork** [ChiselsAndBits/Chisels-and-Bits#724]
* MC Version: 1.16.5
* C&B Version: 1.0.0 & 0.3.5
* Do You have Optifine: Yes

Incompatibility on Mod: Platforms-1.16-1.7.11 (Showing Black & Purple Glitch Blocks)

**Comment by marchermans** [comment]
Logs please.

**Comment by marchermans** [comment]
No respone in a reasonable time. Issue has gone stale.
