### ISSUE TITLE
[1.12.2][C&B 14.33] Chisel bypasses world claims, creating bits indefinitely

### ISSUE THREAD

**Issue by Nivid-IT** [ChiselsAndBits/Chisels-and-Bits#726]
Claims made using the golden shovel from Grief Prevention remain intact when a chisel from C&B is used (the target block is not altered), and players receive a warning when trying to use the chisel on a block not part of their own claims, however bits are still created, and this process can be repeated indefinitely, generating infinite bits. 

* MC Version: 1.12.2
* C&B Version: 14.33
* Do You have Optifine: No
* griefdefender-sponge version: 1.5.8

**Comment by marchermans** [comment]
This is known, but since this is for an unsupported game version I won't be fixing this.
