### ISSUE TITLE
Place Off Grid Unavaliable

### ISSUE THREAD

**Issue by LouiseWhite212109** [ChiselsAndBits/Chisels-and-Bits#727]
It is quite simple, the "Place Off Grid" function doesn't work. I held the button, it seemed that it could be placed off grid; at the meantime, I clicked mouse right, the block is just placed into the grid.

while holding the button:
![IMG_3139](https://user-images.githubusercontent.com/90058062/132038477-5392ccec-fddb-4edd-a109-b8ac00c5cd01.JPG)

after clicking mouse right:
![IMG_3141](https://user-images.githubusercontent.com/90058062/132038538-f7f2e7a2-67ff-4120-8ba6-f8731b1df1b3.JPG)

* MC Version:1.16.5
* C&B Version:0.3.4
* Do You have Optifine:Tested with and without optifine both

**Comment by marchermans** [comment]
Implemented in 1.0.8 beta.
