### ISSUE TITLE
Dark Blocks

### ISSUE THREAD

**Issue by Voicingspy** [ChiselsAndBits/Chisels-and-Bits#728]
Blocks are dark despite being illuminated by light sources around them. 

For any bug reports please provide the following details as well,

* MC Version: 1.16.4
* C&B Version: 1.0.0
* Do You have Optifine: Yes

**Comment by marchermans** [comment]
Test 1.0.1. And this is most likely related to optifine.

**Comment by Voicingspy** [comment]
I've just tried 1.0.1. Still having the same issue. Is there any settings within optifine that I could change to try to fix the issue?

**Comment by marchermans** [comment]
1.0.3 or later fixes this
