### ISSUE TITLE
Visual Issue with Sodium ports

### ISSUE THREAD

**Issue by Furglitch** [ChiselsAndBits/Chisels-and-Bits#730]
A graphical issue occurs whenever a block is chiseled, but only when a Forge port of [Sodium](https://www.curseforge.com/minecraft/mc-mods/sodium) is used.
Port used in testing include Halogen ([v2.9.10](https://www.curseforge.com/minecraft/mc-mods/halogen/files/3410021)).

### Examples:

**No Sodium Port**
![2021-09-08_20 08 21](https://user-images.githubusercontent.com/78628049/132611022-fe64f234-d974-4148-a18e-d453227df202.png)

**Halogen mod installed**
![2021-09-08_20 12 52](https://user-images.githubusercontent.com/78628049/132611028-79fc48bb-a6b6-4b79-a8da-93ae1f603f13.png)

Instance with Chlorine ([v0.0.1.3](https://www.curseforge.com/minecraft/mc-mods/chlorine/files/3199916)) can be found [here](https://github.com/HalogenMods/Chlorine/issues/30)

For any bug reports please provide the following details as well,
* MC Version: 1.16.5 (Forge 36.2.2)
* C&B Version: 0.3.4
* Do You have Optifine: No

**Comment by marchermans** [comment]
This is related to sodium.
Please report the issue to them.
