### ISSUE TITLE
Chisels not working, instead invisible blocks appears around selected block.

### ISSUE THREAD

**Issue by Wooolfik** [ChiselsAndBits/Chisels-and-Bits#731]
No matter on what block i use it, around that block spawn invisible block that make your game crush if you touch some of them
https://i.imgur.com/eN74hPE.mp4

Only player that tried to use chisel sees those blocks etc.
only player that tried to use chisel crashes.
no matter what type of chisel player use (iron,diamond,golden etc and shape).
server does not see any errors in it only thing that i get in server console is:
[net.minecraft.server.management.PlayerInteractionManager/]: Mismatch in destroy block pos: x y z
after right-clicking invisible block

tried with and without optifine = same results

on singleplayer its half working, i can use chisel i get chiseled block (only 1) but invisible block still appear for some secounds and game is still able to crash.

For any bug reports please provide the following details as well,
* MC Version: 1.16.5
* C&B Version: 1.0.0 - ALPHA
* Do You have Optifine: No

**Comment by nstcrypted** [comment]
I am having the exact same issue. On my server the block you try to chisel becomes unbreakable (had to use worldedit to delete it) and invisible blocks spawn around it which you instantly destroy with 1 hit. Tried all chisels, same thing. Optifine is not causing this issue. Here is a complete mod list in case you need it:

[1.16.5] SecurityCraft v1.8.21.1.jar
2.33 MB
alexsmobs-1.5.0.jar
5.17 MB
baubles-1.8.5-1.16.4.jar
153.41 kB
BiomesOPlenty-1.16.5-13.1.0.482-universal.jar
3.48 MB
Bountiful Baubles FORGE-1.16.3-0.0.2.jar
319.76 kB
Bountiful-1.16.4-3.3.1.jar
328.69 kB
buildinggadgets-3.7.2.jar
877.68 kB
chiselsandbits-1.0.0-ALPHA-universal.jar
848.21 kB
citadel-1.8.1-1.16.5.jar
471.13 kB
curios-forge-1.16.5-4.0.5.2.jar
238.98 kB
Disenchanting-forge-1.16.5-1.7.1.jar
45.96 kB
DoggyTalents-1.16.4-2.0.1.3.jar
0.99 MB
DungeonCrawl-1.16.5-2.3.2.jar
738.57 kB
dungeonsarise1.16.4-1.2.63a.jar
4.82 MB
extrabows-v1.16.4 b3.jar
181.05 kB
gravestone-1.16.4-1.0.8.jar
207.33 kB
infernalmobs-1.16.2.1.jar
130.61 kB
inmis-1.0.1-1.16.4.jar
89.75 kB
jei-1.16.5-7.7.1.121.jar
795.13 kB
journeymap-1.16.5-5.7.3.jar
6.55 MB
kotlinforforge-1.15.1-obf.jar
6.37 MB
Ma-Enchants-1.16.3-3.5.0.jar
134.35 kB
mobplusplus-1.0.jar
11.09 kB
modifiers-0.1.2-forge.jar
73.77 kB
mowziesmobs-1.5.19.jar
5.27 MB
StorageDrawers-1.16.3-8.3.0.jar
489.05 kB
Waystones_1.16.5-7.6.3.jar
366.87 kB
worldedit-mod-7.2.5-dist.jar
5.07 MB

Forge 1.16.4 (35.1.37)
C&B Version: 1.0.0 - ALPHA

**Comment by marchermans** [comment]
I found the issue, and fixed it in 1.0.1.
Please test the new release.
