### ISSUE TITLE
Odd behaviour resulting in "ghost" blocks

### ISSUE THREAD

**Issue by bomkz** [ChiselsAndBits/Chisels-and-Bits#732]
MC: 1.16.5 
C&B:0.3.4
Optifine: Yes I do, client side only.

Hi there!

I'm having some issues that basically result in "ghost" blocks that I am unable to partiallyinteract with.
I was chiselling a block and it suddenly started to act like if there was no block there. I can't chisel, can't remove it, can't interact with it, furthermore, trying to place a block on it results in the block being placed in a phased position, say the bugged block is 1 block above ground and you try to place another block looking from above, it just gets placed below it. Same goes for the chiselled bits.

I can still walk on it, just not do anything other than that.

Attached: Video of bug. Low resolution due to Github's file size limit.

https://user-images.githubusercontent.com/59583625/133368932-21c80cc4-cdde-4a89-b342-2264683aaa12.mp4

**Comment by marchermans** [comment]
Update to beta 1.0.1, but make a backup before hand.

**Comment by marchermans** [comment]
Fixed in 1.0.2
