### ISSUE TITLE
1.17

### ISSUE THREAD

**Issue by Jtanner5674** [ChiselsAndBits/Chisels-and-Bits#734]
Hey, I was just wondering when this is going to be ported to 1.17/ the upcoming 1.18. Judging by the fact you had to completely remake it, and that takes time. Im guessing not for a while, I was just wondering if you had an idea of when it might be ported.

For any bug reports please provide the following details as well,
* MC Version:
* C&B Version:
* Do You have Optifine:

**Comment by marchermans** [comment]
Eventually.
The rebuild is not yet stable. BUt as always, it will be release when it is done.
