### ISSUE TITLE
Disappearing blocks when a chiseled bit is placed. 

### ISSUE THREAD

**Issue by Voicingspy** [ChiselsAndBits/Chisels-and-Bits#735]
Normal Blocks are disappearing when chiseled bits are placed in the world. The chiseled bits also seem to have shadows on them, despite being illuminated.

For any bug reports please provide the following details as well,
* MC Version: 1.16.4
* C&B Version: 1.0.1 Alpha
* Do You have Optifine: Yes
![2021-09-17_17 52 31](https://user-images.githubusercontent.com/82189913/133857970-bafa5836-7593-4d2f-ae38-f05dcc3cf357.png)

**Comment by marchermans** [comment]
C&B Is not compatible with Optifine as of now.
