### ISSUE TITLE
game crash when searching items with JEI (forge 1.16.5)

### ISSUE THREAD

**Issue by th3akmin3412** [ChiselsAndBits/Chisels-and-Bits#736]
i tried the C&B 0.3.4 version of Mar 10, 2021 and works well, the game no crash, but the latest (
Rebuild: 1.0.1 - Beta) , crash when using JEI to search items and im sure is this version wich no works 

forge 1.16.5

Rebuild: 1.0.1 - Beta

[latest.log](https://github.com/ChiselsAndBits/Chisels-and-Bits/files/7188764/latest.log)

**Comment by marchermans** [comment]
There is no information in this log.
Please also attach the debug.log.

**Comment by marchermans** [comment]
Fixed in latest beta.
