### ISSUE TITLE
Frame Dropping.

### ISSUE THREAD

**Issue by LazerBolter** [ChiselsAndBits/Chisels-and-Bits#737]
https://user-images.githubusercontent.com/85748661/133885126-7eaad3ff-cdbd-42b2-8c24-c8330d69a981.mp4

MC Version: 1.16.5 (36.2.0)
C&B Version: 1.0.1 ALPHA
Do You have Optifine: No

It runs smoothly but the problems and bugs are:
1. The display before i put down the blocks bits make my fps drop from 200-300 to 5-15.
2. Whenever I try to chisel a block it flash breaks for a second and sometimes the block doesnt even get chiseled.
3. Sometimes the bits glitch and 1 bit is a full block with Unit collision.

I do not have any other mods except C&B and i would like these bugs/problems to be fixed in the future! thank you so much!

**Comment by NielsPilgaard** [comment]
I am seeing the same behaviour.

**Comment by marchermans** [comment]
Yeah
So I was able to reproduce this, and was able to lessen it a bit in the new 1.0.2 beta. But I can not fix this entirely. Minecraft really does not like spheres, so I could only fix it to a certain degree.

**Comment by NielsPilgaard** [comment]
It also happens for all the other shapes, it's just not as bad. So I hope this fix improved it in general 😄

**Comment by NielsPilgaard** [comment]
My FPS is still in the 1-10 area when I hold a bit and see the outline, or use a Chisel.

**Comment by marchermans** [comment]
> My FPS is still in the 1-10 area when I hold a bit and see the outline, or use a Chisel. 

I ran tests of several different devices and i could only reproduce this on spheres and there it is related to voxelshapes just not being layed out for spheres. But the cubes work perfectly fine on those systems.

Please record your screen with the f3 graphs open please. Or run a spark analysis on your system

**Comment by marchermans** [comment]
Also please join discord so we can maybe discuss this a bit more directly

**Comment by LazerBolter** [comment]
> Yeah
> So I was able to reproduce this, and was able to lessen it a bit in the new 1.0.2 beta. But I can not fix this entirely. Minecraft really does not like spheres, so I could only fix it to a certain degree.

Okay thank you so much for reading my thread! have an amazing day!

**Comment by NielsPilgaard** [comment]
This issue appears to be almost entirely gone in 1.0.3, thank you :)
