### ISSUE TITLE
Blocks very dark no matter what shader I use

### ISSUE THREAD

**Issue by Laducatigg** [ChiselsAndBits/Chisels-and-Bits#739]
I updated the C&B to the beta 1.01 since the 0.3.4 keeps ghosting out on me, but when I load the game, the blocks are way to dark, no matter the lighting or shader I use.  I read before it could be an Optifine issue, but I have tried OptiFine HD U G6 up to OptiFine HD U G8.

For any bug reports please provide the following details as well,
* MC Version: 1.16.5
* C&B Version: 1.01 (Beta)
* Do You have Optifine: Yes

**Comment by NielsPilgaard** [comment]
This also happens without Optifine.

**Comment by marchermans** [comment]
I could not reproduce this without optifine on 1.0.2 so I consider this to be fixed.

**Comment by NielsPilgaard** [comment]
I still see the issue with 1.0.2 without Optifine, in Enigmatica 6 0.5.11 in-dev

**Comment by marchermans** [comment]
Screenshot please then.

**Comment by NielsPilgaard** [comment]
It's fixed for me in 1.0.3 without Optifine in Enigmatica 6 0.5.13 :)
