### ISSUE TITLE
Suddenly stopped working.

### ISSUE THREAD

**Issue by pyroarchvile** [ChiselsAndBits/Chisels-and-Bits#740]
When I try to break the bits the block just disappears for a second and then comes back as a vanilla block with no bits missing.

* MC Version: 1.16.5
* C&B Version: 1.0.7
* Do You have Optifine: Yes

**Comment by marchermans** [comment]
Logs please.

**Comment by pyroarchvile** [comment]
https://paste.atlauncher.com/view/a329c933-548e-46dc-8662-5d27c9ef927d here it is

**Comment by marchermans** [comment]
Okey there is nothing in your logs.

I see however that you are running with lots of different mods, and since I can not reproduce this, I would like to ask you to test if this still occurs if you just use MC + Forge + C&B?

Just to limit the options down you know.

**Comment by pyroarchvile** [comment]
It was on a server. It was fixed when C&B was downgraded to the latest stable release.

**Comment by marchermans** [comment]
You can't downgrade!

**Comment by marchermans** [comment]
The 1.0.x versions are highly incompatible with the 0.3.x versions
