### ISSUE TITLE
Chisel Bag & "r" radial menu

### ISSUE THREAD

**Issue by DestinedToSuffer** [ChiselsAndBits/Chisels-and-Bits#742]
* MC Version: 1.17.1
* C&B Version: 1.1.5
* Do You have Optifine: No

On a vanilla+ slightly modded server, no resource packs are enabled. List of mods below. Chisel bag does not show any items in it however I can still click and grab the items in the respected locations with guessing. Also the UI for "r" is hardly readable once you select cube, line, etc... the smaller sub menu.

Just Enough Items (JEI) (by mezz)
Feder's Scarecrows (by itayfeder)
Selectable Painting (by GeheimagentNr1)
Grass Seeds (Forge) (by Serilum)
Easier Sleeping (by GeheimagentNr1)
Nekoration (by DevBobcorn2)
Tiny Redstone (by Danny_and_Son)
Flat Bedrock (by Sunekaer)
Craft Saddles [FORGE & FABRIC] (by 00theblackwolf00)
Simple Voice Chat (by henkelmax)
MrCrayfish's Furniture Mod (by MrCrayfish)
Bad Wither No Cookie - Reloaded (by Kreezxil)
AppleSkin (by squeek502)
Craftable Chainmail Armor [FORGE & FABRIC] (by 00theblackwolf00)
Double Slabs (by CJMinecraft01)
Just Another Rotten Flesh to Leather Mod (by alexdaum1)
GraveStone Mod (by henkelmax)
Sit (by bl4ckscor3)
AI Improvements (by QueenOfMissiles)
Simply Light (by Flanks255)
LibX (by noeppinoeppi)
Jade 🔍 (by Snownee_)
Vanilla Hammers [Forge] (by MelanX)
Chisels & Bits (by AlgorithmX2)
WorldTime (by Giselbaer)
Better Ping Display (by Quintinity)
Trash Cans (by SuperMartijn642)
Double Doors (Forge) (by Serilum)
Citadel (by alex_khaan)
SuperMartijn642's Core Lib (by SuperMartijn642)
Biomes O' Plenty (by Forstride)
FramedBlocks (by XFactHD)
Macaw's Trapdoors (by sketch_macaw)
Advancement Plaques (by Grend_G)
Construction Wand (by ThetaDev)
Just Player Heads (Forge) (by Serilum)
Water Strainer (by Ruuubi)
Corail Woodcutter (by Corail_31)
Farsight (by someaddon)
JourneyMap (by techbrew)
Doggy Talents (by percivalalb)
Macaw's Windows (by sketch_macaw)
OpenBlocks Elevator (by vsngarcia)
Macaw's Lights and Lamps (by sketch_macaw)
Customizable Elytra (by Hidoni)
Macaw's Paintings (by sketch_macaw)
Music Maker Mod (by xerca0)
Mooshroom Tweaks (Forge) (by Serilum)
Finally Farmable Dyes (by Unixkitty)
Lighting Wand 🌟 (by Snownee_)
Serene Seasons (by TheAdubbz)
Just Enough Resources (JER) (by way2muchnoise)
Cosmetic Armor Reworked (by LainMI)
Aquaculture 2 (by Shadowclaimer)
Macaw's Fences and Walls (by sketch_macaw)
Beenfo (by Giselbaer)
Better Than Mending (by legobmw99)
CreativeCore (by CreativeMD)
More Villagers (by SameDifferent)
Collective (Forge) (by Serilum)
Clumps (by Jaredlll08)
Croptopia [FABRIC/FORGE] (by thethonk)
Reap Mod (by henkelmax)
Better Advancements (by way2muchnoise)
Nature's Compass (by Chaosyr)
Tom's Simple Storage Mod (by tom54541)
Ambient Environment (by Jaredlll08)
Comforts (Forge) (by TheIllusiveC4)
MoreVanillaLib (by MelanX)
Extended Bone Meal (Forge) (by Serilum)
Fast Leaf Decay (by olafskiii)
Additional Lights (by mgen256)
Lantern Colors (by schmecky90)
When Was That Again (by HorribleNerd)
Healing Campfire (Forge) (by Serilum)
Alex's Mobs (by alex_khaan)
Coffee Spawner (by Ruuubi)
Mouse Tweaks (by YaLTeR)
Ding (by ohaiiChun)
Torch Slabs Mod (by EndlesNights)
Macaw's Doors (by sketch_macaw)
Controlling (by Jaredlll08)
AmbientSounds 4 (by CreativeMD)

**Comment by marchermans** [comment]
Fixed in 1.0.12 and 1.1.6 respectively.
I increased the icon and font size in the outer selector ring slightly, there is not much more i can do.
