### ISSUE TITLE
Control menu keybinding, block picking issues, sphere grid reduce a significant amount of FPS while moving.

### ISSUE THREAD

**Issue by dejanubogdan** [ChiselsAndBits/Chisels-and-Bits#745]
* MC Version: 1.16.5
* C&B Version: 1.0.11
* Do You have Optifine: Yes - 1.16.5_HD_U_G8

 - Changing the original bind for Tool menu to keys like Alt, Ctrl, Shift, the menu wont pop up, only if the keys are ordinary letters or numbers. In 0.3.x any key was working for the menu.
 
 - Picking a chiseled block seems to be impossible now since trying to pick them with a free hand gives it's bit instead.
 
 - The Medium and Full sizes of the Sphere grid reduce a good amount of FPS, Medium reducing about 10+ ( Not much of a problem ) and Full size reducing between 40 and 80+ [ I'm running on a Ryzen 7 2700 3.2ghz, 16gb ram ( 8 of them allocated to Minecraft ) and Radeon R7 370 Sapphire Nitro 4gb ]

**Comment by marchermans** [comment]
Interesting, let me cover this a bit more accurate:

Picking a full block: Hold shift to pick the entire block and not just the targeted bit.
The spheres are known, there is sadly not much I can do, it is related to how MC treats the voxelshapes, but I will see what I can do in the future.

As for the keybind. I just use the vanilla keybinding system. And check if it is pressed to open.....
So not sure I can be of help there, but I will check.

**Comment by marchermans** [comment]
So I checked that menu keybinding issue and I had no problems binding CTRL + G or SHIFT + H to the key and opening the UI.
As such unless you have a better way for me to reproduce this, logs, video recordings etc, I can't really help you, and will be closing this issue.
