### ISSUE TITLE
Feature Return: Rotate menu

### ISSUE THREAD

**Issue by dejanubogdan** [ChiselsAndBits/Chisels-and-Bits#746]
Probably this have been asked for, but as i see in the current version of C&B ( 1.0.12 MC 1.16.5 ) holding the tool menu key doesn't bring up a menu to rotate the current chiseled block.
Suggestion: Rotation in all 3 directions if possible, not only X and Z as 0.3.x had.

**Comment by marchermans** [comment]
This was internally decided to be removed.
We wanted to consolidate all of the edit features into one place, and we did this for two reasons:
1) Simplicity from the users perspective. You break a block then that is the block it won't rotate. If you want to rotate or modify a block make a pattern of it.
2) Simplicity on the code side. Solidifying the code in one place, makes it easier to maintain for future versions.
