### ISSUE TITLE
invisible blocks

### ISSUE THREAD

**Issue by yggdrasil75** [ChiselsAndBits/Chisels-and-Bits#748]
When I use optifine (testing with HD U G5) chisels and bits blocks are invisible. I have tried the instructions in #7 but that does not work. is there a known workaround for 1.12 to make the blocks visible? settings I can change on either optifine end or on chisels and bits end to allow them to work? 

For any bug reports please provide the following details as well,
* MC Version: 1.12
* C&B Version: 14.33
* Do You have Optifine: yes.

if this should be working, I can provide more info, including a list of coremods which may be affecting the rendering engine.

**Comment by marchermans** [comment]
Sadly 1.12 is not supported anymore, and as far as I know if the workaround in #7 does not work, then there is no way for you to get it to work.
