### ISSUE TITLE
All chiseled blocks are dark

### ISSUE THREAD

**Issue by jochemvdmeulen** [ChiselsAndBits/Chisels-and-Bits#749]
When a block is turned into a chiseled block, the blok immediately becomes darker and almost emits negative light.
All chiseled blocks that have a relatively small amount of bits removed are very dark.
There seems to be a relation in how many bits there are in a block and how dark they are.

This happens in a clean Minecraft instance without any other mods

Here you see the dark chiseled blocks:
![2021-10-05_22 47 21](https://user-images.githubusercontent.com/42549531/136101175-80edc07b-5e6b-493a-938d-8a54575fbf5b.png)

Here you see a similar structure in Minecraft 1.12: (Notice that the gaps aren't dark)
![2021-10-05_23 00 22](https://user-images.githubusercontent.com/42549531/136102061-68e3c918-52e6-4016-8704-380de4381b1f.png)

* MC Version: 1.16.5
* C&B Version: 1.0.12
* Do You have Optifine: No

**Comment by marchermans** [comment]
I remodelled this and I was not able to reproduce this.
Can you do two things for me?

Make a screenshot of your graphics/videos settings.
And check if you have the forge pipeline enabled.

**Comment by jochemvdmeulen** [comment]
I looked up the forge light pipeline in the config file and found:
experimentalForgeLightPipelineEnabled = false
forgeLightPipelineEnabled = true

So I enabled experimentalForgeLightPipelineEnabled

Now when I load back into my test world, the lighting seems to be fixed. But when I break and replace any blocks it becomes dark again. However less dark then before editing the config file

Just after loading in:
![2021-10-06_23 04 34](https://user-images.githubusercontent.com/42549531/136282996-0f75ed20-ff00-4949-8226-d6e284e9be5b.png)

When I replace all blocks: (Note: I use middle click for copying chiseled blocks)
![2021-10-06_23 04 20](https://user-images.githubusercontent.com/42549531/136283123-88b0f11d-6d14-4eab-a200-2fb4fff4e960.png
)

Also here is a screenshot of my settings: (Yes i run my brightness in moody, but when I turn it to bright it is still to dark)
![2021-10-06_22 30 55](https://user-images.githubusercontent.com/42549531/136283320-d6ef5ab3-67ca-418c-b9d9-c2f550052b1b.png)

here is a screenshot with the config disabled again with brightness turned to bright
![2021-10-06_23 10 39](https://user-images.githubusercontent.com/42549531/136284005-8287abc7-c1cb-4443-92b0-da3cfee2d2f9.png)

**Comment by marchermans** [comment]
Can you see if you can reproduce this with chisels and bits only. And then send me your world.

Cause I don't get this at all and I think it might be related to model data somehow

**Comment by jochemvdmeulen** [comment]
Since the Minecraft instance I was using only has Chisels and Bits I just sent you the word where I have been testing in
[C&B Test.zip](https://github.com/ChiselsAndBits/Chisels-and-Bits/files/7305641/C.B.Test.zip)
.

**Comment by marchermans** [comment]
Original freshly loaded into the world:
![image](https://user-images.githubusercontent.com/5585406/136568494-61aa9134-ccf6-40ad-8854-f3cef8b6d8e7.png)

New one rebuild just as you described:
![image](https://user-images.githubusercontent.com/5585406/136568620-4fd27e12-5967-455d-9eae-7f708d19e924.png)

As you can see I don't have any issues like this. 
My test graphics settings:
![image](https://user-images.githubusercontent.com/5585406/136568805-083d5691-b9d1-44c3-82d1-95d7d1a1ea1c.png)
And these are my settings for the forge client:
![image](https://user-images.githubusercontent.com/5585406/136568928-858b1010-3f1c-4a8c-9191-70d83a4e34af.png)

As such I am not sure what the cause is.

**Comment by jochemvdmeulen** [comment]
Interestingly my forge config file is different
![Naamloos](https://user-images.githubusercontent.com/42549531/136637098-b67f1127-2688-4c81-8ca3-69178c542354.png)

Are we running a different version of forge or something else

**Comment by marchermans** [comment]
Yeah I am running a test version which cleans up the configs internally.
But nothing more.

So I have no clue what the cause is.....
Let me do some testing, but I can't promise anything and it might in the end be related to something that is not under my control.

**Comment by jochemvdmeulen** [comment]
Would it help if i sent over my whole test instance?

I use MultMC by the way

**Comment by jochemvdmeulen** [comment]
Also have you tried setting the brightness to moody?

And here is a new clean instance where I reproduced the issue:
[C&B 2.zip](https://github.com/ChiselsAndBits/Chisels-and-Bits/files/7315724/C.B.2.zip)
I used the latest version of forge that i could select in the MultiMC options.

**Comment by marchermans** [comment]
I did my best to fix this in the newest release.
There is not much more that I can do since I can not reproduce this on my end.
