### ISSUE TITLE
Can't connect to LAN worlds.

### ISSUE THREAD

**Issue by Iemelt** [ChiselsAndBits/Chisels-and-Bits#751]
When I try joining an LAN world I join for a second then immediately get disconnected and it says connection lost disconnected.  If I remove chisel and bits from my mods I can join perfectly fine. 
MC 1.17.1
 C&B: 1.17.1
Do you have Optifine: No

**Comment by marchermans** [comment]
Please add your log files

**Comment by Iemelt** [comment]
Where can I find the log files?

**Comment by marchermans** [comment]
`<Minecraft directory>/logs`

**Comment by marchermans** [comment]
I tried to test this on my end
But got no where
So I will need to get these logs, if you want this fixed.

**Comment by Grinkon** [comment]
I have similar Problem with Servers

**Comment by Grinkon** [comment]
[latest.log](https://github.com/ChiselsAndBits/Chisels-and-Bits/files/7404679/latest.log)
There is my latest.log

**Comment by marchermans** [comment]
@Grinkon since that is the same latest log as  posted on your other issue i will assume something went awry here.

Sadly i can not really test this properly until people provide me with better logs

**Comment by marchermans** [comment]
Fixed in the 1.18 update.
