### ISSUE TITLE
The wrench was a very useful tool, is it coming back (at least for creative builders)? Is there an alternative?

### ISSUE THREAD

**Issue by jkPlayer998** [ChiselsAndBits/Chisels-and-Bits#753]
Before continuing if you are reporting an issue, please ensure that all mods involved are updated to the latest version available, if your issue with with intermod compatibility such mixing C&B bits with other blocks make sure that MCMP is also updated. If your issue is a crash, be sure to include the crash log with your report.

For any bug reports please provide the following details as well,
* MC Version:
* C&B Version:
* Do You have Optifine:

**Comment by marchermans** [comment]
In what way was the wrench usefull?
Since the update to 1.12 and the reduction of its basic functionality it was nearly useless to have in your inventory.

If you can get me a decent usecase then yeah adding it back in is easily possible

**Comment by jkPlayer998** [comment]
Maybe im wrong, i just started playing with this mod again. The last time i played, the wrench was used for rotating blocks and right now as far as i know there isnt a quick way of rotating blocks without the use of patterns. Is there a an easy way of rotating custom blocks?

**Comment by woalk** [comment]
> If you can get me a decent usecase then yeah adding it back in is easily possible

I haven't played on 1.x versions yet, but in 0.x versions, if you rotated a chiselled structure via WorldEdit `//rotate`, the chisel blocks themselves would not get rotated, so the wrench was the only way to rotate entire structures like this.

**Comment by marchermans** [comment]
You could also always pick them up.

**Comment by marchermans** [comment]
But yeah I found a much better usecase for the wrench
So I will be implementing it again.
Will take me a bit though since RL is now pretty full again.

**Comment by jkPlayer998** [comment]
What do you mean pick them up

**Comment by woalk** [comment]
> You could also always pick them up.

That's not really practical if you try to rotate a large structure of tens of chisel blocks – much easier to just hit every block with a wrench.

**Comment by marchermans** [comment]
Reimplemented in the new release
