### ISSUE TITLE
Unable to interacted and crash while using bag.

### ISSUE THREAD

**Issue by SavageLykos** [ChiselsAndBits/Chisels-and-Bits#755]
MC Version: 1.16.5
C&B Version: 1.0.11
Do You have Optifine : no

I am having the similar issue  I was using chisel and bits and I died. After that I am unable to use the mod. I asked the server owner for the logs and he is stating there are none and he is also able to use it. Another bug I found is the chisel bag crashes my client anytime I try to pull chisels from it while placing down more than I have in my hand
[crash-2021-10-08_20.56.05-client.txt](https://github.com/ChiselsAndBits/Chisels-and-Bits/files/7314953/crash-2021-10-08_20.56.05-client.txt)
.
update: deleting client files for c&b fixed the issue with being unable to interact with the mod for now.

_Originally posted by @SavageLykos in https://github.com/ChiselsAndBits/Chisels-and-Bits/issues/744#issuecomment-939222622_

**Comment by marchermans** [comment]
Fixed in the new release.
