### ISSUE TITLE
Connected Material 1x1 not what was expected

### ISSUE THREAD

**Issue by LindaJuffermans** [ChiselsAndBits/Chisels-and-Bits#759]
* MC Version: 1.16.5
* C&B Version: chiselsandbits-1.0.12-RELEASE-universal.jar
* Do You have Optifine: No

Select Connected Material > 1x1 from the radial menu
![2021-10-13_11 06 47](https://user-images.githubusercontent.com/31929183/137103260-d434310f-e35a-477e-b203-1fecb2330f13.png)

Expected behaviour: Place 1 layer on top of the existing connected bits
Observed behaviour: Places 2 full planes on on the selected layer and one in front:
![2021-10-13_11 06 49](https://user-images.githubusercontent.com/31929183/137103336-cf69a9d2-e52a-4022-9f2a-2c13d3681ed8.png)
![2021-10-13_11 06 51](https://user-images.githubusercontent.com/31929183/137103482-50f22973-2d9e-489c-9a54-f01c49f00264.png)

Currently behaviour is the same for Connected Material > 1x1 and Plane > 1x1

**Comment by marchermans** [comment]
I am pretty sure placement of connected material is implemented as a plain.
We where unsure as to what the correct behaviour is supposed to be.

If you have any ideas as to how it has to behave in different circumstances, feel free to come into our discord.

**Comment by marchermans** [comment]
That also means, that yes I will indeed still need to fix this.

**Comment by LindaJuffermans** [comment]
Both Connected Plane & Connected Material in C&B 0.3.4:
![2021-10-13_11 46 29](https://user-images.githubusercontent.com/31929183/137109846-b9e13827-0fa6-40e4-94de-10972246911b.png)
![2021-10-13_11 46 30](https://user-images.githubusercontent.com/31929183/137109853-37ba3bf3-9eaf-49fd-8756-9092ca8660d9.png)

**Comment by marchermans** [comment]
So they just use the same projected shape....
Okey I will need todo some digging on how this needs to work now.
