### ISSUE TITLE
After using C&B, the bit preview and radial menu remain active without the items.

### ISSUE THREAD

**Issue by LindaJuffermans** [ChiselsAndBits/Chisels-and-Bits#761]
MC Version: 1.16.5
C&B Version: chiselsandbits-1.0.12-RELEASE-universal.jar
Do You have Optifine: No

I've put the bits and chisel away in a backpack but the UI is still showing the placement preview and `r` is still opening the radial menu:
![2021-10-13_11 18 49](https://user-images.githubusercontent.com/31929183/137105017-060b67dc-2bbc-4e67-98d8-0fdd28d0542f.png)
![2021-10-13_11 18 51](https://user-images.githubusercontent.com/31929183/137105025-5477b009-9a29-4386-9833-a1e42b33fe7d.png)

Even while holding a sword:
![2021-10-13_11 20 48](https://user-images.githubusercontent.com/31929183/137105224-c20d04ff-9051-4d1c-9bec-0aca3e039adf.png)

**Comment by marchermans** [comment]
You have bits in your offhand

**Comment by marchermans** [comment]
Since you can place blocks from the offhand, this behaviour is replicated with bits. Hence the UI behaving normally as if you are holding bits.

**Comment by LindaJuffermans** [comment]
Ah, I missed that one... that's caused by the "chiseling fills inventory" I reported in another thread.

**Comment by marchermans** [comment]
Yeah
Already fixed several of the things you reported internally.
But these tickets you created today are new.

The ghost block one is the one I am worried about.
There is specific code in the block to destroy itself when it is emptied......

**Comment by marchermans** [comment]
I will close this issue, and reopen another one for the bit filling.
