### ISSUE TITLE
Simple Pattern is not destroyed on use

### ISSUE THREAD

**Issue by LindaJuffermans** [ChiselsAndBits/Chisels-and-Bits#762]
MC Version: 1.16.5
C&B Version: chiselsandbits-1.0.12-RELEASE-universal.jar
Do You have Optifine: No

Unless "Single Use Pattern" (wiki) is not the same as "Simple Pattern" (in game) - but both are created with paper and a quill - I'm able to reuse it multiple times. (I quite like this but I don't think it's intended.):
![2021-10-13_11 36 31](https://user-images.githubusercontent.com/31929183/137108344-7973f256-6c3a-496a-b3c5-b26a3757d1dd.png)
![2021-10-13_11 36 34](https://user-images.githubusercontent.com/31929183/137108348-c1d65721-9b3f-447c-be2d-7560429b5fb0.png)

**Comment by marchermans** [comment]
It is indeed not intended, and likely slipped in as a bug later.
Will patch thanks for the report.

**Comment by marchermans** [comment]
Fixed in the new release.
