### ISSUE TITLE
chisel blocks took too long to load

### ISSUE THREAD

**Issue by ink717** [ChiselsAndBits/Chisels-and-Bits#764]
Minecraft 1.16.5, forge 36.2.8, just updated chisel from 0.3.4 to 1.0.12. With and without optifine.
All the chisel blocks that were made during 0.3.4 took at least 10 seconds to show up in 1.0.12, every time.
All airports lighting made by chisel even took longer, on some lower-end machines it took 40-60 seconds. it made all airfield lighting unuseable. Currently didn't find any config specific to that. Is there a way to turn of that kind of delay loading?

**Comment by marchermans** [comment]
Improved in 1.18.
But essentially not fixable.
The model geometry has to be calculated at some point.
