### ISSUE TITLE
wonky shadows

### ISSUE THREAD

**Issue by ElNico56** [ChiselsAndBits/Chisels-and-Bits#769]
shadows work weird

* MC Version: 1.16.5
* C&B Version: 1.0.38 alpha
* Do You have Optifine: no
![2021-10-23_19 43 45](https://user-images.githubusercontent.com/18220871/138573779-423be5a3-791d-4166-8b5c-fb88b53233e6.png)

**Comment by marchermans** [comment]
This is sadly normal behaviour.
Obviously that is not full
So the shadow calculations are different for chiseled vs none chiseled blocks.
There is not much I can do.
