### ISSUE TITLE
Can not connect any servers

### ISSUE THREAD

**Issue by Grinkon** [ChiselsAndBits/Chisels-and-Bits#770]
Hi, I can not connect to any Minecraft servers that runs in 1.16 or 1.17. I have not tested if there is same problem in all versions that is 1.13 or newer. In 1.12.2, there was not problems at all.  I want to connect my own server PinkieCraft (IP is pinkiecraft.pinkipiirakka.net) but when i have Chisels and bits (which is necessary in gamemode MetroCraft) I can't join and same issue repeats in every other server. logfile: [latest.log](https://github.com/ChiselsAndBits/Chisels-and-Bits/files/7404738/latest.log)
* MC Version: 1.17.1
* C&B Version: 1.1.39 (Same problem in all versions including 1.16.5 versions, 1.12.2 works instead)
* Do You have Optifine: Not in use at the time

**Comment by marchermans** [comment]
This is not related to c&b but likely with the server they are running.

Without details of the server setup there is not much i can do.
Can you get a server admin to write that down here so i can see what I can do?

**Comment by Grinkon** [comment]
I AM server admin, i own that server. what i have to tell? 
I use Velocity as a proxy and paper as hub. i guess Hub have something wrong, but i am not sure. Everything works when C&B is not in use.

**Comment by marchermans** [comment]
My best guess Velocity or Paper are not supported.
