### ISSUE TITLE
Suggestion: Protection compatibility

### ISSUE THREAD

**Issue by CptPICHU** [ChiselsAndBits/Chisels-and-Bits#772]
As i already mentioned some time ago, lemme just create this for better keeping track of the idea.

There are protection tools like "FTB Chunks" or "WorldGuard".
At the moment the chiseling mechanic seems to ignore protected areas.
It would be cool if that could be changed.

I dont really know how this works, but WorldGuard can even protect modded blocks and processes even if it was never made for mods to begin with. That means, there must be a certain check those mods or plugin does, that can probably be integrated.

My guess would be, that the mod somehow checks for permission for the server before performing an action.
This could be pretty useful i think.

**Comment by marchermans** [comment]
Research concluded. I will need to modify the mutators to be player aware somehow and then fire the events and check for modifications

**Comment by marchermans** [comment]
I added support for the block break event in the next release.
If for any of the positions which are about to be edited the event is cancelled then no modifications can be made.

This is also checked on the client side, so it should reflect in the previews as well.
