### ISSUE TITLE
1.17 Multiplayer failure-cannot join the room

### ISSUE THREAD

**Issue by LouiseWhite212109** [ChiselsAndBits/Chisels-and-Bits#774]
This mod works well in single mode. However when it comes to multiplayer, other players cannot join the room with this mod. If I remove this mod, other players can join the room, so I think there is something wrong in this mod.

Error:
Internal Exception: io.netty.handler.codec.EncoderException: io.netty.util.IllegalReferenceCountException: refCnt:0

![9C %~WHDD}Y_P18JSC2EH6J](https://user-images.githubusercontent.com/90058062/139373852-90771459-8b38-4985-b860-0637b72cf4ba.png)

For any bug reports please provide the following details as well,
* MC Version:1.17
* C&B Version:1.1.39/1.1.41
* Do You have Optifine:Yes
*

**Comment by marchermans** [comment]
Logs from both the server and the client please

**Comment by LouiseWhite212109** [comment]
[ClientLog-minecraft-exported-logs-2021-10-29T16-07-53.log](https://github.com/ChiselsAndBits/Chisels-and-Bits/files/7440058/ClientLog-minecraft-exported-logs-2021-10-29T16-07-53.log)
[ServerLog-minecraft-exported-logs-2021-10-29T16-08-31.log](https://github.com/ChiselsAndBits/Chisels-and-Bits/files/7440059/ServerLog-minecraft-exported-logs-2021-10-29T16-08-31.log)
Both two logs are uploaded. The client tried to log in twice and each time error occured.

**Comment by LouiseWhite212109** [comment]
In addition, there is only one mod, which is this mod, is added, so the problem is not about compatibility with other mods.  The  information that each time client tries to connect and gets lost may be a bit different, but you can see from the server log, the exceptions are the same: Internal Exception: io.netty.handler.codec.EncoderException: io.netty.util.IllegalReferenceCountException: refCnt:0. Another mod(CosmeticArmorReworked) also has the same problem and I also reported to the author. I think the problem is related to the interface. I know very few about programming and modding, so I cannot figure it out. Anyway, thank you and other authors for creating and continue maintaining this fancy mod! I like it.

**Comment by marchermans** [comment]
You are using a cracked or invalid client.
Closing and locking the issue
