### ISSUE TITLE
Only able to use chisel(s) on blocks ONCE in survival

### ISSUE THREAD

**Issue by Masqueeraded** [ChiselsAndBits/Chisels-and-Bits#775]
When I use a chisel(s) of any type, I'm only able to use it on a  block once. After chiseling the block, I am no longer able to interact with the block using a chisel again.

I am able to place bits. However, I'm unable to remove them after placing them unless its with a pickaxe.

This issue does not happen when I'm in creative mode.

I currently do not have any crash reports, logs, or errors at this time.

I'm currently playing on Divine Journey 2 Pack Version 2.8.0

For any bug reports please provide the following details as well,
* MC Version: 1.12.2
* C&B Version: 14.33
* Do You have Optifine: No

**Comment by marchermans** [comment]
1.12.x is not supported.
