### ISSUE TITLE
Repost: Multiplayer cannot connect to LAN worlds

### ISSUE THREAD

**Issue by LouiseWhite212109** [ChiselsAndBits/Chisels-and-Bits#777]
Since that last time it is considered that it is because cracked or invalid client, I redo the test. Sorry for that because it is difficult to test only by myself so I use 1 official account and 1 offline client. This time I use 2 computers, 2 official launchers with 2 official accounts. Everything is official.
The server and client are in the same LAN and both use the official launcher with different official accounts.
1. Only Forge, no mod: everything goes fine.
2. Only Forge and C&B, no other mods: single player goes fine, but client can not join the room. Server detects that the client joins the room but quits immediately.

Official launcher, normal account, vanilla doing well, only forge doing well, with some other mods doing well. Many tests are done and it all comes to that this mod may have some problem.

Both Server and client logs are uploaded. I hope that there is a solution.
For any bug reports please provide the following details as well,
* MC Version:1.17
* C&B Version:1.1.39 alpha/1.1.6/1.1.41 alpha
* Do You have Optifine:No

[ServerLog-ForgeAndMod.zip](https://github.com/ChiselsAndBits/Chisels-and-Bits/files/7446135/ServerLog-ForgeAndMod.zip)
[ServerLog-ForgeOnly.zip](https://github.com/ChiselsAndBits/Chisels-and-Bits/files/7446136/ServerLog-ForgeOnly.zip)
[ClientLog-ForgeAndMod.zip](https://github.com/ChiselsAndBits/Chisels-and-Bits/files/7446137/ClientLog-ForgeAndMod.zip)
[ClientLog-ForgeOnly.zip](https://github.com/ChiselsAndBits/Chisels-and-Bits/files/7446138/ClientLog-ForgeOnly.zip)

**Comment by LouiseWhite212109** [comment]
What server sees
![Server](https://user-images.githubusercontent.com/90058062/139527096-ebeb10dd-9582-4066-bfdf-112708abce5f.png)

What client sees
![BugReport](https://user-images.githubusercontent.com/90058062/139527108-70a52b76-b3cd-4d87-bf86-4beb8b11853f.jpg)

Thanks for the authors' attention. There is TRULY a problem here not because of launcher, account, network, or anything else. There IS a problem with this mod. I hope this mod could be better and more complete.

**Comment by marchermans** [comment]
I pushed the issue up upstream to somebody who understands the problem moren then i.

As far as i can see this is not really related to c&b but rather the forge handshaking protocol.

I hope to have more information for you soon.

**Comment by LouiseWhite212109** [comment]
Yes you are right, maybe it is because of forge. I saw someone who had reported a similar problem as me 3 weeks ago and you also labeled it as "Help Wanted". I'm ashamed that I don't know much about programming and can't provide more help. Anyway, thanks for your attention.

**Comment by marchermans** [comment]
This is a bug in forge
And requires an update on their side to fix.

However for now I found a way around it, and will apply this work around for the time being

**Comment by LouiseWhite212109** [comment]
Thanks very much for your continuous efforts. On Oct 31st forge provided an update and I am going to test it.

**Comment by LouiseWhite212109** [comment]
Sadly even if I updated forge, the same error occured again for now.

**Comment by marchermans** [comment]
Updating does not actually fix it.
I opened the Forge PR to get the change reverted that caused this, and I am working on publishing a 1.17 version of C&B with this fix inplace.

**Comment by marchermans** [comment]
Fixed in the 1.18 update
