### ISSUE TITLE
Crash to desktop by hovering over a single use pattern while crouching / holding shift

### ISSUE THREAD

**Issue by kartoffelsaretasty** [ChiselsAndBits/Chisels-and-Bits#778]
* MC Version: 1.16.5 // Enigmatica 6 ver 0.5.17 (latest at the time of writing)
* C&B Version: 1.0.42
* Do You have Optifine: no

my friend is crashing to desktop when he hovers over a single use pattern while holding the shift key (shift bound to crouch) - the button also does the whole enlarging texture thing on bits. we updated to latest to see whether the bug was gone already, but it has happened on .39 and .42.

Sadly don't have many more infos as of right now, but if you need any more i can try collecting some tomorrow evening.

**Comment by marchermans** [comment]
I will need more logs, else i won't be able to fix this.

**Comment by marchermans** [comment]
Closed because this went stale.
