### ISSUE TITLE
Antivirus and CurseForge Recognizes C&B as Virus

### ISSUE THREAD

**Issue by accessdenied0** [ChiselsAndBits/Chisels-and-Bits#779]
For any bug reports please provide the following details as well,
* MC Version: 1.16.5
* C&B Version: 1.0.0 Alpha +
* Do You have Optifine: No

![image](https://user-images.githubusercontent.com/8020013/139680279-62b51234-d69e-4ed5-a76e-b43e32054c43.png)

![image](https://user-images.githubusercontent.com/8020013/139679276-b756c6af-bf23-48ce-8d8a-ac2013bded70.png)
German for: "The Process couldn't finished successfully, because the File could be a Virus or an unwanted Software"

This really hinders me to use a newer Version of C&B....

I am not sure if this is fixable or what causes it, but I am thankful for any help (except whitelisting this file for every version)

**Comment by marchermans** [comment]
Please update to the lastest version.
Some nitwit has reported an earlier version of C&B 1.x and this is causing issues.

**Comment by accessdenied0** [comment]
Ahh thank you^^
