### ISSUE TITLE
Disappearing Bits Block, then crash

### ISSUE THREAD

**Issue by Severance213** [ChiselsAndBits/Chisels-and-Bits#78]
I am playing the FTB Unstable modpack and opened a void world to play around with Chisel and Bits. After chiseling some bits out of a block it disappeared. So i broke the block and replaced it a few times to make it show back up. When it did render for me properly when I tried to chisel a bit out again I crashed with this log: http://pastebin.com/hLeMjaVX

**Comment by AlgorithmX2** [comment]
That log was actually java crashing when using ig9icd64.dll

A quick google search says that you should update your intel drivers, https://bugs.mojang.com/browse/MC-94900

**Comment by AlgorithmX2** [comment]
As for the other issue you'll probobly want to make sure your on the lastest version and try that, I have no idea what version of MC your on, or what version of the mod your playing.

Make sure your on the latest of whichever, If your on 1.9.4 or 1.10 then we can see if the issue persists.

if your on 1.9 or a 1.8 build however I'm afield those versions will probably not be officially supported any longer.
