### ISSUE TITLE
Minecraft Crashes when opening radial menu for Chisel Patterns

### ISSUE THREAD

**Issue by BreadBxsket** [ChiselsAndBits/Chisels-and-Bits#780]
For any bug reports please provide the following details as well,
* MC Version: 1.16.5
* C&B Version: chiselsandbits-1.0.43
* Do You have Optifine: No

Upon pressing 'R' to open the radial menu on a single-use or multi-use pattern, the game immediately stops responding and crashes entirely shortly thereafter.

First file attached is the crash report for single-use patterns
Second file attached is the crash report for multi-use patterns

[crash-2021-11-01_12.43.07-client.txt](https://github.com/ChiselsAndBits/Chisels-and-Bits/files/7454831/crash-2021-11-01_12.43.07-client.txt)

[crash-2021-11-01_12.35.20-client.txt](https://github.com/ChiselsAndBits/Chisels-and-Bits/files/7454810/crash-2021-11-01_12.35.20-client.txt)

**Comment by marchermans** [comment]
Already reproduced. Hotfix is coming.

**Comment by BreadBxsket** [comment]
I experienced the same issue just now with opening the wrench's radial menu. Curious if this fix solves the wrench's crash as well.

**Comment by marchermans** [comment]
It will

**Comment by oParis90** [comment]
Hello! Was it fixed? I took the last 1.16.5 version on CurseForge and I still encounter this bug.

**Comment by Mike5357** [comment]
Also still experiencing this issue

**Comment by marchermans** [comment]
Fixed in the 1.18 update.
