### ISSUE TITLE
Rendering issues

### ISSUE THREAD

**Issue by Sunekaer** [ChiselsAndBits/Chisels-and-Bits#783]
For any bug reports please provide the following details as well,
* MC Version: 1.16.5 - forge 36.2.8
* C&B Version: 1.0.43
* Do You have Optifine: No
* No other mods installed

Other info:
![image](https://user-images.githubusercontent.com/18720460/140285832-1a0e6632-1c2c-43e5-b9f6-0e51329f7fb4.png)

Issue
![image](https://user-images.githubusercontent.com/18720460/140285983-13219b51-da64-4ce3-84bc-fb9399fe4a58.png)

Gif of the issue:
https://s1.sunekaer.com/i/04-11-2021_09-55-28_%25pn.gif

**Comment by marchermans** [comment]
You will need to expand what you think is wrong here?

**Comment by Sunekaer** [comment]
Sure,
Removed bits from a block shouldn't be pitch dark.
also if you see the gif the first time I use the chisel on a block the whole block becomes black for split-second

**Comment by marchermans** [comment]
Enable the Forge Experimental Rendering Pipeline.
