### ISSUE TITLE
[1.16.5] Crash with EvilCraft when taking chisel in hand

### ISSUE THREAD

**Issue by Lgmrszd** [ChiselsAndBits/Chisels-and-Bits#784]
Title pretty much says it.
How to reproduce:
1. Give yourself chisel
2. Game crashes when hotbar slot with the chisel is selected.

Crashlog: [link](https://gist.github.com/Lgmrszd/4f528c643a9905d31bff3e1a379b931d)

For any bug reports please provide the following details as well,
* MC Version: 1.16.5
* Forge version: 36.2.8
* C&B Version: 1.0.43
* Do You have Optifine: No
Other mods:
* EvilCraft: 1.16.5-1.1.8
* CyclopsCore: 1.16.5-1.12.0

**Comment by Lgmrszd** [comment]
Issue was on EvilCraft side and is fixed now.

**Comment by marchermans** [comment]
Oke thanks
