### ISSUE TITLE
Intense lag on none default bit size

### ISSUE THREAD

**Issue by Mbimajosh** [ChiselsAndBits/Chisels-and-Bits#785]
Before continuing if you are reporting an issue, please ensure that all mods involved are updated to the latest version available, if your issue with with intermod compatibility such mixing C&B bits with other blocks make sure that MCMP is also updated. If your issue is a crash, be sure to include the crash log with your report.

For any bug reports please provide the following details as well,
* MC Version: 1.16.5
* C&B Version: the one that's .43
* Do You have Optifine: Yes but if that's the problem considering i have had this mod with optifine before i'd be very suprised.

**Comment by marchermans** [comment]
Please upload your log files and any other related bit of information

**Comment by Mbimajosh** [comment]
No, it's clearly broken many people also say this i'm just gonna remove it from the modpack i am playing and swap it it's not my job to to bug test my dude i'm sorry. As much as i like mods and that i just really cannot be bothered sorry to seem rude.

**Comment by Mbimajosh** [comment]
Also just to add this happened with the old 1.16.5 and new 1.16.5 mod also i don't wanna put the chisel in my inventory to do this as it causes me to not respond everytime i try to scroll. You could try installing the enigmatica modpack and testing it there as that's where it is happening.

**Comment by marchermans** [comment]
I did install that pack.
And i do not have this issue.

Since you do not want to help fix the problem, i will close it.
