### ISSUE TITLE
Inability to rotate blocks, and pick block

### ISSUE THREAD

**Issue by Nikofluff** [ChiselsAndBits/Chisels-and-Bits#786]
Mc: 1.16.5
CBV: 1.0.43
Optifine: Yes

So, I'm no longer able to shift and scroll to rotate blocks in my hand, and I am also unable to pick block a fully chiseled brick and it just gives me a single bit instead of the finished block. I'm not sure if this is one of my own issues, or if this is on the mod itself. If this is an issue with the mod, I hope you are able to fix the issue unless it is intended.

**Comment by Nikofluff** [comment]
Ive found out the reasons for my issues except the pick block- sorry for wasting your time on that first part

**Comment by marchermans** [comment]
Hold shift while picking the block
