### ISSUE TITLE
When holding chisels rock in hand, pressing Tools menu key will cause the game to crash (bug)

### ISSUE THREAD

**Issue by wang-yupu** [ChiselsAndBits/Chisels-and-Bits#787]
Before continuing if you are reporting an issue, please ensure that all mods involved are updated to the latest version available, if your issue with with intermod compatibility such mixing C&B bits with other blocks make sure that MCMP is also updated. If your issue is a crash, be sure to include the crash log with your report.

When holding chisels rock in hand, pressing the hotkey 'R' (Tools menu) will cause the game to crash
(Use google translate to translate Chinese into English)

For any bug reports please provide the following details as well,
* MC Version:1.16.5
* C&B Version:1.0.43
* Do You have Optifine:Yes,I use Optifine G8 pre14

**Comment by gmfCoding** [comment]
Can confirm. playing the new Create: Above and Beyond mod pack, opening the tool menu while holding a chiseled block, will cause the game to cras
[crash-2021-11-14_00.53.42-client.txt](https://github.com/ChiselsAndBits/Chisels-and-Bits/files/7532234/crash-2021-11-14_00.53.42-client.txt)
h.

**Comment by Ruckius** [comment]
Have a similar issue but is not limited to holding bits, happens with all tools with or without optifine

**Comment by marchermans** [comment]
Fixed in the update to 1.18
