### ISSUE TITLE
Fabulous graphics setting causes graphical issues when holding chisel or bits

### ISSUE THREAD

**Issue by EvergreenSystems** [ChiselsAndBits/Chisels-and-Bits#788]
Before continuing if you are reporting an issue, please ensure that all mods involved are updated to the latest version available, if your issue with with intermod compatibility such mixing C&B bits with other blocks make sure that MCMP is also updated. If your issue is a crash, be sure to include the crash log with your report.

For any bug reports please provide the following details as well,
* MC Version: 1.17.1
* C&B Version: 1.1.39 Alpha
* Forge: 37.0.104
* Do You have Optifine: No

When the fabulous graphics setting is on the graphic that shows where the chisel is targeting does not appear. On lower graphic settings it works fine. Attached are screenshots of the setting off, and the setting on.
![2021-11-17_10 25 51](https://user-images.githubusercontent.com/23658767/142240424-b0732862-dff2-4007-8457-02048d666e89.png)
![2021-11-17_10 26 05](https://user-images.githubusercontent.com/23658767/142240427-9f88bff2-baff-4ba6-88d8-75e2c922e2be.png)

**Comment by marchermans** [comment]
Currently not fixable due to a limit with fabulous.
