### ISSUE TITLE
Crash when changing Measuring Tape colors (Shift + Mouse Wheel)

### ISSUE THREAD

**Issue by VsnGamer** [ChiselsAndBits/Chisels-and-Bits#79]
My game crashes when I try to change Measuring Tape colors (Shift + Mouse Wheel).
C&B(11.4)
Forge(2007)
Log:
[crash-2016-07-05_13.15.22-client.txt](https://github.com/AlgorithmX2/Chisels-and-Bits/files/347718/crash-2016-07-05_13.15.22-client.txt)

Edit:I have other mods too, but I think its C&B problem.

**Comment by AlgorithmX2** [comment]
This only happens if you do this before switching modes, since the item doesn't have any data yet. Will be fixed in next version.
