### ISSUE TITLE
Crashes within the Valhelsia 3 Modpack

### ISSUE THREAD

**Issue by CardForCard** [ChiselsAndBits/Chisels-and-Bits#790]
I'm having really horrible Issues within the Modpack "Valhelsia 3".
When I try to use to Pattern with Shift+Rightclick, it crashes. 
When I place any chiseld stuff inside of water, the Visual of it glitches out and whenever I touch that, I crash.
When I mine a block underwater that has Air in it, it crashes. (Accidentally chiseling a bit out of sand underwater, undo doesn't work and then mining that sand block)
I'm not using Optifine or anything else outside of that Modpack. I have 8GB RAM allocated
[crash-2021-11-19_16.36.33-client.txt](https://github.com/ChiselsAndBits/Chisels-and-Bits/files/7571381/crash-2021-11-19_16.36.33-client.txt)
[crash-2021-11-19_16.50.12-client.txt](https://github.com/ChiselsAndBits/Chisels-and-Bits/files/7571383/crash-2021-11-19_16.50.12-client.txt)
[crash-2021-11-19_16.30.51-client.txt](https://github.com/ChiselsAndBits/Chisels-and-Bits/files/7571384/crash-2021-11-19_16.30.51-client.txt)

**Comment by marchermans** [comment]
Fixed in the 1.18 update
