### ISSUE TITLE
Waterlogged bit blocks crash on 1.17.1

### ISSUE THREAD

**Issue by EvergreenSystems** [ChiselsAndBits/Chisels-and-Bits#792]
Before continuing if you are reporting an issue, please ensure that all mods involved are updated to the latest version available, if your issue with with intermod compatibility such mixing C&B bits with other blocks make sure that MCMP is also updated. If your issue is a crash, be sure to include the crash log with your report.

For any bug reports please provide the following details as well,
* MC Version: 1.17.1
* C&B Version: 1.1.41 ALPHA
* Forge Version: 37.0.104
* Do You have Optifine: Never

Steps to reproduce: Set chisel to connected material 8x8, chisel the top half of a block that is next to a water source block, and then break the chiseled block. Game will crash, and if the block is picked up by the player during the crash/when the game is next loaded, opening the inventory will also crash.

![2021-11-23_20 44 28](https://user-images.githubusercontent.com/23658767/143162520-55f57bb5-6910-43ce-8956-9a3fdaafd5fa.png)

Crash Log: https://pastebin.com/cfJxuNzR

Client Latest Log: https://pastebin.com/KN0e1j9j

Client Debug Log: https://pastebin.com/x3uVR4Gy

**Comment by marchermans** [comment]
![image](https://user-images.githubusercontent.com/5585406/147750152-5271b699-e389-4950-b387-0368db28cf67.png)

Not reproduceable, but possibly fixed in the 1.18 updates
