### ISSUE TITLE
Water flowing into a tile space with C&B bits will cause the entire negative space of that tile to be converted into water bits

### ISSUE THREAD

**Issue by douyabian** [ChiselsAndBits/Chisels-and-Bits#793]
For any bug reports please provide the following details as well,
* MC Version: 1.16.6
* C&B Version: 1.0.43
* Do You have Optifine: No

Expected behaviour: When water flows into a C&B tile, expected to be blocked without waterlogging and be stopped

Actual behaviour: When water flows into a C&B tile, it "waterlogs" and replaces all the negative space/air in the block with water bits

**Comment by marchermans** [comment]
![image](https://user-images.githubusercontent.com/5585406/147749981-302ac475-14cc-4889-a25d-46d531726bf7.png)
As long as the side the water tries to flow into from is full this won't happen.
This mirrors default vanilla behaviour of blocks like slabs, stairs, and trapdoors.
