### ISSUE TITLE
Enormous amounts of lag when chiseling, depending on mode

### ISSUE THREAD

**Issue by mosharky** [ChiselsAndBits/Chisels-and-Bits#795]
For any bug reports please provide the following details as well,
* MC Version: 1.16.5
* C&B Version: chiselsandbits-1.0.43
* Do You have Optifine: No

On [this modpack](https://www.curseforge.com/minecraft/modpacks/mos-mods/files/3528333), chiseling any block drops my FPS by insane amounts. I can't find the cause to it. The log doesn't output any issues relating to this mod at all.

When chiseling in full block mode, my frames drop all the way down to 5 FPS in an otherwise stable experience. Micro-stutters happen every time I chisel a block too, regardless of the mode. Is there an incompatibility somewhere that I haven't caught?

**Comment by marchermans** [comment]
It is related to the new chiselable checks.
Currently I fire an event to check if you are allowed to chisel a particular block... The system does not like that.
There is a patch incoming for this.

**Comment by marchermans** [comment]
Fixed in the 1.18 port.
