### ISSUE TITLE
Error Loading Mod

### ISSUE THREAD

**Issue by Voicingspy** [ChiselsAndBits/Chisels-and-Bits#796]
Before continuing if you are reporting an issue, please ensure that all mods involved are updated to the latest version available, if your issue with with intermod compatibility such mixing C&B bits with other blocks make sure that MCMP is also updated. If your issue is a crash, be sure to include the crash log with your report.

Fails to load.
[crash-2021-12-04_14.39.10-fml.txt](https://github.com/ChiselsAndBits/Chisels-and-Bits/files/7654567/crash-2021-12-04_14.39.10-fml.txt)

For any bug reports please provide the following details as well,
* MC Version: 1.16.4
* C&B Version: 1.0.43
* Do You have Optifine: Yes

**Comment by marchermans** [comment]
You are missing the flywheel dependency for Create.
Please add the dependency!
