### ISSUE TITLE
Drawn region on the new version, and problem

### ISSUE THREAD

**Issue by Merkulus** [ChiselsAndBits/Chisels-and-Bits#797]
1. I ran into one problem, very much missing a function: drawn region
This feature makes building easier, and cutting out 1 pixel at a time is very time consuming.

Please try adding this feature again.

2. There is one more problem, it lags when trying to cut, FPS goes down to zero. In multiplayer, this problem is very striking.

There are no such problems on the previous version to 1.12.2.

For any bug reports please provide the following details as well,
* MC Version: 1.16.5
* C&B Version:1.0.43
* Do You have Optifine: yes

**Comment by Avris** [comment]
Lacking Drawn Region makes the mod effectively unusable, especially with how unreliable single-bit manipulation is (overplacing/removing) and the lack of functional connected regions.

**Comment by marchermans** [comment]
Drawn region is coming to 1.18 and is already released to the patreons. 
Closing since this will come out in the next few days.
