### ISSUE TITLE
Map wont load after upgrading chisel and bits version

### ISSUE THREAD

**Issue by nrgyt** [ChiselsAndBits/Chisels-and-Bits#799]
When upgrading from chisel and bits version 0.3.4 on 1.16.5, to any rebuild version for 1.16.5, my map would not load and would crash after approximately a minute. The loading screen would pause around the 30% mark and then skip straight to 100%, it would then stay at 100% until the game crashes and gives me this error:  "An unexpected issue occurred and the game crashed. We're sorry for the Inconvenience." (Exit Code: 0) I do have Optifine installed for this version but I don't believe that to be the issue, since whenever I open a world that doesn't already have chiseled blocks in it, then it works perfectly fine. I would appreciate any advice on how to fix this if possible, as I have made substantial progress in that map.

**Comment by marchermans** [comment]
Could i get logs of this behaviour?

**Comment by nrgyt** [comment]
Sure thing, since this has happened more than once ill send a couple logs:

[crash-2021-12-07_21.43.52-client.txt](https://github.com/ChiselsAndBits/Chisels-and-Bits/files/7689118/crash-2021-12-07_21.43.52-client.txt)

[crash-2021-12-07_16.42.06-fml.txt](https://github.com/ChiselsAndBits/Chisels-and-Bits/files/7689119/crash-2021-12-07_16.42.06-fml.txt)

**Comment by marchermans** [comment]
Nothing indicates that this is related to Chisels and Bits.
Closing.
