### ISSUE TITLE
Tape Measure Rendering Bug

### ISSUE THREAD

**Issue by lim-n-to-infty** [ChiselsAndBits/Chisels-and-Bits#800]
This happens all the time. There is no outline to what i've measured and the text is duobled.

I have no other mods installed.

![grafik](https://user-images.githubusercontent.com/95927040/145598169-ab65d4d8-1fd6-42f7-81df-250c00df7d5b.png)

* MC 1.17.1
* C&B 1.1.6:
* No Optifine:

**Comment by marchermans** [comment]
Closed in the upcoming releases.
