### ISSUE TITLE
Wooden Wrench is named different in lang file

### ISSUE THREAD

**Issue by PutridNonsense** [ChiselsAndBits/Chisels-and-Bits#801]
In the lang file, the wrench is called item.chiselsandbits.wrench_wood but in-game its called _item.chiselsandbits.wrench_

* MC Version: 1.16.5
* C&B Version: 1.0.43
* Do You have Optifine: No

**Comment by marchermans** [comment]
I do not see the problem. Minecraft does not require the lang key to be identical to the item name.

With the rebuild the name changed but to keep the old translations i kept the old lang key, which is why they differ.
