### ISSUE TITLE
Chiseled blocks are invisible when using Sodium with and without Indium.

### ISSUE THREAD

**Issue by ShaneTRS** [ChiselsAndBits/Chisels-and-Bits#804]
* MC Version: 1.18.1
* C&B Version: 1.2.0
* Do You have Optifine: No

![image](https://user-images.githubusercontent.com/80662335/147800466-f725311a-2e3c-4273-b180-2962a7069d24.png)

**Comment by marchermans** [comment]
Which loader version are you running?
Also Sodium is not officially supported I have no clue what it does to model loading or other rendering systems to be able to support it.

Have the author contact me.

**Comment by marchermans** [comment]
Also contact me in discord

**Comment by marchermans** [comment]
Fixed in 1.2.58

**Comment by FrozenDragon0** [comment]
This bug still exists in the fabric version it seems.
