### ISSUE TITLE
[fabric] lag and light problems

### ISSUE THREAD

**Issue by Chuunkyz** [ChiselsAndBits/Chisels-and-Bits#806]
i'm using the fabric version and i noticed big lag spikes when using the chisels
also when you chisel leaves or even stone, the color of the whole block is changing and that's pretty meh, idk if that's the same with the forge version, but an other similar mod on fabric called bits and chisels doesnt have this problem

**Comment by marchermans** [comment]
I think I found the color issue.

The lag I can not reproduce
Can you get me something like a spark profile for this? Or at least join our discord, I am eager to find a solution for this.

Also in general try to be more precise when you create an issue, I have very little to go on, especially on the lag front.

**Comment by marchermans** [comment]
I tracked it down to the chiseled block conversion code.
I need to track it down further next week,

**Comment by marchermans** [comment]
Closed in #825 released in 1.2.65
