### ISSUE TITLE
[Suggestion] Feature/Config for hiding Block Bits from REI.

### ISSUE THREAD

**Issue by ImAK9** [ChiselsAndBits/Chisels-and-Bits#807]
* MC Version: 1.18
* Mod Loader: Fabric Loader

**Comment by itsdinkd** [comment]
There is one. 
![image](https://user-images.githubusercontent.com/35115304/147861216-0ae03115-04a2-4833-8a12-0fdc9053d284.png)
go in there and set it to false

**Comment by marchermans** [comment]
> There is one. 
> ![image](https://user-images.githubusercontent.com/35115304/147861216-0ae03115-04a2-4833-8a12-0fdc9053d284.png)
> go in there and set it to false

That is for forge. I assume he is talking about the fabric version

**Comment by ImAK9** [comment]
> > There is one.
> > ![image](https://user-images.githubusercontent.com/35115304/147861216-0ae03115-04a2-4833-8a12-0fdc9053d284.png)
> > go in there and set it to false
> 
> That is for forge. I assume he is talking about the fabric version

Correct, I’m using the Fabric version.

**Comment by marchermans** [comment]
Fixed in 1.2.100
