### ISSUE TITLE
[Fabric] Question : Is it normal for C&B blocks to damage players when they hit the block ?

### ISSUE THREAD

**Issue by vvenaya** [ChiselsAndBits/Chisels-and-Bits#808]
* MC Version: 1.18
* C&B Version: 1.2.60
* Do You have Optifine: Nope

Whenever i hit/touch a chiseled block i get damaged .. Kinda annoying as i need to watch where i am going around my build.

Also, When i chisel away a block entirely, the block does not get replaced by Minecraft:air .... leaving a ghost block behind.

TIA,
  VV

**Comment by marchermans** [comment]
Should be fixed in the latest version.
