### ISSUE TITLE
Screen appears to be inside block when there are bits occupying the headspace of player's hitbox.

### ISSUE THREAD

**Issue by BreadBxsket** [ChiselsAndBits/Chisels-and-Bits#809]
* MC Version: Forge 39.0.9, MC 1.18.1
* C&B Version: ChiselsBits-forge-1.18.1-1.2.62
* Do You have Optifine: no

The Issue: Having at least a single bit in the "headspace" of a player's hitbox will cause the entire screen to appear to be inside a block

How to recreate: Place a single bit (or more) in the block space above your feet. Stand in that blockspace.

Single bit placed in headspace:
![Screenshot_29](https://user-images.githubusercontent.com/30668741/147877597-5de9e3a4-31b4-443b-b490-c3a4f39292c4.png)
First Person appearance:
![Screenshot_30](https://user-images.githubusercontent.com/30668741/147877598-14ee2948-050f-419c-9223-cb8cb17828e7.png)

**Comment by marchermans** [comment]
Should be fixed now.
