### ISSUE TITLE
Bits that emit light don't always update the light level properly.

### ISSUE THREAD

**Issue by AlgorithmX2** [ChiselsAndBits/Chisels-and-Bits#81]
Seems be produce 100% when removing a plane from glowstone, or placing a single plane of glowstone.

It seems to only matter when moving from 15 -> 15 or 0 -> 15

I've attempted to track this down one already but so far I've been unable to figure out why the light level doesn't want to update properly.

Placing glowstone and next to it and breaking it always seems to resolve the issue, Also visiting any light level that doesn't equal 15 seems to work fine.

**Comment by FELITH** [comment]
:3
http://i.imgur.com/RsjV6ei.gif

**Comment by AlgorithmX2** [comment]
Uhh thanks?

**Comment by esge** [comment]
c&b v12.7
mc 1.10.2 
forge 2124

when using the connected plane(or any mode) to place bits of glowstone, light doesn't update
when i place a even a cobblestone block next to it, the light updates correctly
when i place an existing plane of chiseled glowstone, the light updates correctly

**Comment by AlgorithmX2** [comment]
This is fixed, and will be released in future releases.
