### ISSUE TITLE
Chisels and Bits 1.18 Drawn Region Issue

### ISSUE THREAD

**Issue by ThiccKitten** [ChiselsAndBits/Chisels-and-Bits#813]
I just got the new version set up on my PC. Everything is fine; however, I was really hoping to use the drawn region tool. For some reason, when I right click with the block I want and then right click again, nothing happens. It just continues to show me the region I chose and will not go away until I left click which just breaks a block as expected. Not sure what is happening and was hoping for assistance. 
* MC Version: 1.18 Forge
* C&B Version: 1.18
* Do You have Optifine: Yes. 1.18

**Comment by marchermans** [comment]
Reproduced, will be patched.

**Comment by marchermans** [comment]
Closed in #825 released in 1.2.65
