### ISSUE TITLE
Biome's o Plenty

### ISSUE THREAD

**Issue by TomJTaylor67** [ChiselsAndBits/Chisels-and-Bits#814]
Hi 
I'm playing FTB Revelations 1.12.2 and I want to be able to Chisel the Biome's o Plenty Mud block. I have managed to enable the ability to chisel the Biomes o Plenty dirt blocks thanks to the help of another thread on here and was wondering if someone could help me with this issue please.

**Comment by marchermans** [comment]
Sorry but 1.12 is not supported anymore.

**Comment by TomJTaylor67** [comment]
> Sorry but 1.12 is not supported anymore.

I know it isn't, but surely someone knows how to fix it because it was being played at one point, and unfortunately this is the version that I currently have to use.

**Comment by marchermans** [comment]
That might be so.
But tickets for 1.12.2 will be closed on this repository, as to not overflood our capabilities.
