### ISSUE TITLE
Walking into blocks containing any bits causes the screen to go blank

### ISSUE THREAD

**Issue by Nick-McKay** [ChiselsAndBits/Chisels-and-Bits#817]
Walking into blocks containing any bits causes the screen to go blank. To set up, place two dirt blocks on top of each other on a flat surface. Place a bit into the air block next to the top block. Enter the block you just placed a bit in. The screen is now black until you leave the block.

I have enabled the experimentalForgeLightPipelineEnabled

For any bug reports please provide the following details as well,
* MC Version: 1.18.1
* C&B Version: 1.18.1-1.2.62
* Do You have Optifine: No

**Comment by Hazard-Hat** [comment]
Did you do this in creative mode?
Because in survival I end up taking damage.
Which means the game bugs out and acts like your stuck in the block.

**Comment by Nick-McKay** [comment]
Yeah, this was in creative, and I did not take damage when switching to survival

**Comment by xigzagoon** [comment]
can confirm, I don't take suffocation damage but the screen still goes black.

MC Version: 1.18.1
C&B Version: 1.18.1-1.2.62
Do You have Optifine: No

**Comment by josiah-roberts** [comment]
+1, same issue, survival, no damage, `experimentalForgeLightPipelineEnabled = true`

**Comment by marchermans** [comment]
It is noted, at the moment I am working on a performance issue.
Hopefully I can get this solved afterwards.

**Comment by marchermans** [comment]
Closed in #825 released in 1.2.65

**Comment by gabemg421** [comment]
i am still having the same issue with both opdifine and without
