### ISSUE TITLE
Smooth lighting breaks the shading on edited blocks.

### ISSUE THREAD

**Issue by Hazard-Hat** [ChiselsAndBits/Chisels-and-Bits#818]
I have Chisels and Bits 1.18.1-1.2.62 and Optifine 1.18.1 HD U H4 only, and the blocks edited with bits have this weird shading with smooth lighting on. I even tried it with JUST C&B but the issue still persisted.
![Screenshot (817)](https://user-images.githubusercontent.com/96910731/147998656-954568b3-8cab-4a23-9b9f-616518203b4e.png)

**Comment by Hazard-Hat** [comment]
It goes away with Smooth Lighting off

**Comment by marchermans** [comment]
Yes this shadow is related to Ambient Occlusion calculations, Optifine uses Vanilla calculations and those are not compatible.
You will either need to enable the Forge Experimental Rendering Pipeline, or on fabric switch to either Indigo with its Enhanced Ambient Occlusion calculation or use Sodium + Indium with its Enhanced Ambient Occlusion calculation.

**Comment by Hazard-Hat** [comment]
> Yes this shadow is related to Ambient Occlusion calculations, Optifine uses Vanilla calculations and those are not compatible. You will either need to enable the Forge Experimental Rendering Pipeline, or on fabric switch to either Indigo with its Enhanced Ambient Occlusion calculation or use Sodium + Indium with its Enhanced Ambient Occlusion calculation.

How would I enable Forge Experimental Rendering Pipeline?
Is it something I activate in the config files?

My search engine (startpage) isn't giving me anything about enabling it.

**Comment by Hazard-Hat** [comment]
Okay, I actually found it, but the blocks are now all around dark, instead of the center just being dark.

**Comment by marchermans** [comment]
Then you disabled it. They turn black when you disabled it.
