### ISSUE TITLE
HotKeys Redo / Undo (Maybe Others) Triggering when typing in Chat.

### ISSUE THREAD

**Issue by StoneLegion** [ChiselsAndBits/Chisels-and-Bits#819]
So it was Y key maybe R? Anyways when you start chatting (t key) and the chat dialog is open you start seeing no undo's available, etc. Normally keybinds should be disabled while chat is open.

Thanks :) 

For any bug reports please provide the following details as well,
* MC Version: 1.18.1
* C&B Version: ChiselsBits-fabric-1.18.1-1.2.60
* Do You have Optifine: Never

**Comment by marchermans** [comment]
Same as #815 I found the issue, will get a patch.

**Comment by marchermans** [comment]
Closed in #825 released in 1.2.65
