### ISSUE TITLE
Subreddit.

### ISSUE THREAD

**Issue by ghost** [ChiselsAndBits/Chisels-and-Bits#82]
reddit.com/r/chiselsandbits

**Comment by AlgorithmX2** [comment]
Neat, maybe post some replies to some of the folks that have posted their builds in https://www.reddit.com/r/feedthebeast/ to see if they want to share their builds and things with the new subreddit?

Hopefully my sharing feature will be available soon and people will post various things to share them with everyone in the future.

**Comment by AlgorithmX2** [comment]
I also added it to http://algorithmx2.github.io/Chisels-and-Bits/ so it can get some attention.

**Comment by ghost** [comment]
Thanks for the responses, I'll post some replies on /r/feedthebeast and thanks for the share :)
