### ISSUE TITLE
Selection boxes have the wrong alpha value

### ISSUE THREAD

**Issue by GiantLuigi4** [ChiselsAndBits/Chisels-and-Bits#822]
There are two ways to reproduce this:
- get out a tape measure, scroll until you have the black color, measure a region
- go to C&B's client config, find `[settings.chiseling-previews.default.colors]`, set `chiseling` to `[0,0,0,1]` and `placement` to `[1,1,1,0`], then hold out a bit and look at a block

For any bug reports please provide the following details as well,
* MC Version: 1.18.1, forge
* C&B Version: 1.2.62
* Do You have Optifine: no

Client Config:
[chiselsandbits-client.toml.txt](https://github.com/ChiselsAndBits/Chisels-and-Bits/files/7815432/chiselsandbits-client.toml.txt)

Screenshots:
![image](https://user-images.githubusercontent.com/49770992/148230350-7d93f086-3eb4-4fb2-acad-f3497f2a7229.png)
![image](https://user-images.githubusercontent.com/49770992/148230921-a8b35626-b5b6-4091-bcbe-da996d052c36.png)

**Comment by marchermans** [comment]
Closed in #825 released in 1.2.65
