### ISSUE TITLE
Crash when bit placed at Height Limit

### ISSUE THREAD

**Issue by BreadBxsket** [ChiselsAndBits/Chisels-and-Bits#823]
MC Version: 1.16.5
C&B Version: 1.0.63
Do You have Optifine: No
[crash-2022-01-05_12.26.29-client.txt](https://github.com/ChiselsAndBits/Chisels-and-Bits/files/7816690/crash-2022-01-05_12.26.29-client.txt)

MC Version: 1.18.1
C&B Version: 1.2.62
Do You have Optifine: No
[crash-2022-01-05_12.22.30-client.txt](https://github.com/ChiselsAndBits/Chisels-and-Bits/files/7816693/crash-2022-01-05_12.22.30-client.txt)

Related to Issue #692 
Original Issue marked as closed, after being labeled "OnHold: Rebuild", and commented **Update to the latest beta.**

Issue Persists in the latest version of 1.16.5 and 1.18.1 C&B

**Comment by marchermans** [comment]
Closed in #825 released in 1.2.65
