### ISSUE TITLE
Latest version crashes on startup

### ISSUE THREAD

**Issue by BreadBxsket** [ChiselsAndBits/Chisels-and-Bits#826]
* MC Version: 1.18.1 Forge
* C&B Version: 1.2.65
* Do You have Optifine: No

[latest.log](https://github.com/ChiselsAndBits/Chisels-and-Bits/files/7828833/latest.log)

**Comment by agentwolf88** [comment]
+1
[latest.log](https://github.com/ChiselsAndBits/Chisels-and-Bits/files/7828860/latest.log)

**Comment by lhaeussler** [comment]
Having a simmilar Issue her. Doesnt produce a crash log
[latest.log](https://github.com/ChiselsAndBits/Chisels-and-Bits/files/7829060/latest.log)
I'm unfortunately not able to recover from the issue the error persitst to older c&b versions on my client.

**Comment by marchermans** [comment]
Yeah I am aware
There is an issue with CI not adding the required information into the jar
Bare with me for a hot minute

**Comment by nnn950711** [comment]
+1

**Comment by marchermans** [comment]
Update to the latest version.
