### ISSUE TITLE
Lighting issue and opacity

### ISSUE THREAD

**Issue by ShadowFantasy** [ChiselsAndBits/Chisels-and-Bits#827]
Before continuing if you are reporting an issue, please ensure that all mods involved are updated to the latest version available, if your issue with with intermod compatibility such mixing C&B bits with other blocks make sure that MCMP is also updated. If your issue is a crash, be sure to include the crash log with your report.

C&B blocks have light issues. And space that is inhabited with a C&B bit are treated like solid blocks and block my vision the same way it would when suffocating.

For any bug reports please provide the following details as well,
* MC Version:
* C&B Version:
* Do You have Optifine:

**Comment by marchermans** [comment]
Please update to the latest version. And enable the enhanced graphical processing on your platform. See the relevant curse forge page of your platform on what to set
