### ISSUE TITLE
Infinite Block Creation

### ISSUE THREAD

**Issue by DeDog103** [ChiselsAndBits/Chisels-and-Bits#828]
Before continuing if you are reporting an issue, please ensure that all mods involved are updated to the latest version available, if your issue with with intermod compatibility such mixing C&B bits with other blocks make sure that MCMP is also updated. If your issue is a crash, be sure to include the crash log with your report.

This bug allows the creation of infinite bits from any block. I used a hopper to funnel full blocks into a chisel bit storage tank. Then, using the chisel station I produced half slabs of the block. The block in the hopper never disappeared, yet the chisel storage kept getting filled up! Here are some videos I took using this bug. (the videos are too big, so here are the links to them on youtube)

[https://youtu.be/QH_vcYT0QEc] [https://youtu.be/TJ_YtB5xLW0](url)

For any bug reports please provide the following details as well,
* MC Version: 1.16.5
* C&B Version: 1.0.63
* Do You have Optifine: No

**Comment by marchermans** [comment]
Fixed in 1.2.100
