### ISSUE TITLE
Preview of crafted blocks 180° rotatet

### ISSUE THREAD

**Issue by Kasuyakema** [ChiselsAndBits/Chisels-and-Bits#83]
I crafted diagonaly cut stone brick blocks from a positive chisle design. The preview i got with the block in hand was 180° rotatet towards the position it was actually placed. Version was 1.8.9.

Prewiew:
![2016-07-10_11 37 41](https://cloud.githubusercontent.com/assets/20380301/16712818/d1499908-4692-11e6-8bb6-ec2162f87cdc.png)

Actual placement:
![2016-07-10_11 37 44](https://cloud.githubusercontent.com/assets/20380301/16712817/d148dfa4-4692-11e6-864e-c4b498632508.png)

By the way i realy love ur mod, its by far the best i ever played. keep up the good work.

**Comment by AlgorithmX2** [comment]
Seems that this is only an issue in the older version I cannot reproduce this in the 1.9.4/1.10 version.

**Comment by Kasuyakema** [comment]
sorry, I should have checked it with the newer versions. Here have my newest screenshot as an apology 
![2016-07-10_20 25 07](https://cloud.githubusercontent.com/assets/20380301/16715809/c18b7ce0-46ea-11e6-9dc5-b261af4f9447.png)

**Comment by AlgorithmX2** [comment]
Its alight, The screenshot  looks pretty good.
