### ISSUE TITLE
odd issue reguarding draw reigion

### ISSUE THREAD

**Issue by 40H4** [ChiselsAndBits/Chisels-and-Bits#830]
found a odd bug maby its my fault i doubt it so i was trying to chisel a vanilla oak log for a house and decided to use draw reigion as it would complete my goal quicker  so i turned it on via the menu wheel and  right clicked on the start point to chisel out what i wanted removed but the block flickered and i could no longer chisel blocks with any of the chisels currently crafted having to throw out all of them and craft/ enchant a new set this is really annoying and i would love a rapid reply and fix or assistance if its just me using the mod wrong 
* MC Version: 1.18.1
* C&B Version:1.18.1-1.2.68
* Do You have Optifine: yes im currently using version preview_OptiFine_1.18.1_HD_U_H5_pre4

**Comment by marchermans** [comment]
Optifine is the source of this,
It is known, and not supported.

**Comment by 40H4** [comment]
ah i see that kinda sucks but im willing to get rid of optifine for chisel and bits thanks for the reply
