### ISSUE TITLE
OpenGL errors

### ISSUE THREAD

**Issue by MishkoFreid** [ChiselsAndBits/Chisels-and-Bits#831]
Hi, for some reason when I put chiselsandbits blocks, it shows me OpenGL: 1281 (Invalid value) errors in chat. And when i break this blocks, the errors will dissapears. How to fix this?

Minecraft: 1.16.5 Forge
chiselsandbits-1.16.5-1.0.63
OptiFine_1.16.5_HD_U_G8
OptiForge-MC1.16.5-0.5.4_1

![2022-01-09_11 21 27](https://user-images.githubusercontent.com/96202762/148676729-678afc3c-912b-40a0-8a29-0e23d58af9c6.png)

**Comment by marchermans** [comment]
Remove optifine, it is officially not supported.
