### ISSUE TITLE
Random crash with no crash log

### ISSUE THREAD

**Issue by TheIrishStud** [ChiselsAndBits/Chisels-and-Bits#833]
Only thing I've found is in the "recent" log file where and error message shows an invalid mod icon for icon source chiselsandbits: logo-fabric.png "java.lang.IllegalStateException: Must be square icon"

The crash occured after building the chisel and compatible scope tool when I accidentally pressed the advancements key bind. Maybe a mod incompatibility with the custom advancements mod that I have installed for more vanilla achievement variety?

More Advancements - https://www.curseforge.com/minecraft/mc-mods/moreachievements-fabric

**Comment by marchermans** [comment]
Create an issue with them, it is not required for the logo to be square, they just make that assumption.

Besides it is not opensource so I won't be able to provide support for this anyway. sorry.
