### ISSUE TITLE
Add outline selection mode

### ISSUE THREAD

**Issue by Niko-O** [ChiselsAndBits/Chisels-and-Bits#834]
> Before continuing if you are reporting an issue, please ensure that all mods involved are updated to the latest version available

We are not using the latest version, but the behavior seems to be the same in the current version.

The tape measure, in the "Block" mode, measures the distance between the origins of the two selected blocks.
We find it much more useful in everyday use to see the outline of the volume that bounds the two selected blocks (and the lengths of the sides of that volume). This was the behavior in version 0.2.10 of the mod.

The current behavior is actually much more complicated than that, because it depends on which side of the block you click, so you get very unpredictable behavior. The suggested behavior is easily predictable in all cases, so it is much easier to use.

Depending on how much effort you would be willing to put into this, I can give you a rundown of all possible ways that things interact and what the implications are.

**Comment by marchermans** [comment]
Hit me up on discord

**Comment by marchermans** [comment]
Fixed in latest
