### ISSUE TITLE
Problem with 1.17.1 version of Chisels and Bits mod

### ISSUE THREAD

**Issue by Sarumanojh** [ChiselsAndBits/Chisels-and-Bits#835]
I have installed Chisels and Bits mod for Minecraft 1.17.1. When i run it with Minecraft forge 1.17.1 with Optifine 1.17.1:

1. It works, but I see there aren't a lot of options in the radial menu. For example there isn't the connected plane that is really important to make blocks detailed spending less time. 
2. If i create a world and then i close it and then i try to open it again, it takes something like 10 or 13 seconds to load a few chiseled blocks. The block are like invisible. Here there's a link for a google drive folder where there are some screenshots. But after few seconds texture work and the problem disappear. (my problem is that if i use a lot of theese block in a map it could take a lot ot time to load all of them, or probably not, i have just to know if it is my problem or is a problem of the mod)

- [https://drive.google.com/drive/u/0/folders/1XHRj4HS0VuOZ9jLd2UjEaroHUtmAvxEj ](url)

I wish you will update the current version of the mod for 1.17.1 as you did for 1.16.5 that worked perfectly for me. It had no problems with 1.16.5 version. You are amazing guys. I hope you will make this mod better and better resolving this little problems. Thank you! XD

**Comment by marchermans** [comment]
Connected plane exists but is renamed, the radial menu is paged so you can find additional modes on the second page.
All in all the total amount of modes has more then doubled.

Yes it can take a bit to compile and build the models.
The models are build off-thread and that means that it might take a hot-minute or so to get them build and then properly drawn on the screen.

That said I sadly can only support those version for which I myself receive support from Forge.
Per forge support guidelines that is the current major version (1.18) and one LTS which is 1.16.5 as writing, as such I am not able to support 1.17 anymore, sorry.

**Comment by Sarumanojh** [comment]
Thank you man. Now my problem is that I don't find the connected plane in the radial menu. Another problem is that i used to use  the "simple pattern" to copy and rotate the block, i shifted and rolling with the mouse to rotate them but in this version it doesn't work. I wanted to know how i could rotate them in the current version 1.17.1.    :)

**Comment by marchermans** [comment]
Patterns are considered massively powerfully and as such now require a table to be modified.

There are now different plane modes you can use. They are just named differently

**Comment by Sarumanojh** [comment]
thank you for your help! 😉

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Mail
priva di virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Il giorno dom 16 gen 2022 alle ore 20:22 Marc Hermans <
***@***.***> ha scritto:

**Comment by joeyfigaro** [comment]
@Sarumanojh where did you even find a release for 1.17.x?
