### ISSUE TITLE
Minecraft crashes when I press 'R' to open the radial menu

### ISSUE THREAD

**Issue by MitreLjetiNaKrof** [ChiselsAndBits/Chisels-and-Bits#836]
I'm playing the latest version of the "Create: Above & Beyond" modpack (by simibubi), on the CurseForge/Overwolf Launcher.
At first the mod was all good, and everything was functional. I have around 10 types of chiseled blocks, and multiple copies of them placed. The patterns still work, and I am able to place down and destroy bits, but I am unable to open the radial menu.

Note: When placing bits and using the chisel, I am able to open the radial menu. But when I try to open the radial menu with the wrench, or a pattern, the game crashes. That is the issue I am facing.

MC Version: 1.16.5
C&B Version: chiselsandbits-1.0.43
Do You have Optifine: No
Modpack Version: 1.3 [Latest Release: 12/15/2021]
Forge Release: 36.2.20

Attached are two crash reports, one from an attempt at opening the radial menu with a pattern, and the other with the wrench:

[crash-2022-01-11_01.10.29-client.txt](https://github.com/ChiselsAndBits/Chisels-and-Bits/files/7847933/crash-2022-01-11_01.10.29-client.txt)

[crash-2022-01-11_15.53.41-client.txt](https://github.com/ChiselsAndBits/Chisels-and-Bits/files/7847935/crash-2022-01-11_15.53.41-client.txt)

**Comment by marchermans** [comment]
Update to the latest version.
This has been fixed there.

**Comment by MitreLjetiNaKrof** [comment]
Thank you.
