### ISSUE TITLE
Drawn Region no longer works. 

### ISSUE THREAD

**Issue by ThiccKitten** [ChiselsAndBits/Chisels-and-Bits#837]
The feature no longer works entirely. There is still an option for it in the menu; however, no outline pops up and clicking any mouse buttons has zero effect. 

For any bug reports please provide the following details as well,
* MC Version: 1.18
* C&B Version: 1.18
* Do You have Optifine: Yes

**Comment by marchermans** [comment]
This problem is caused by optifine. It is officially not supported
