### ISSUE TITLE
Rendering Issue?

### ISSUE THREAD

**Issue by AlexdaCat** [ChiselsAndBits/Chisels-and-Bits#838]
Any block that has been chiseled not rendering

It was working before I switched to Iris Shaders

For any bug reports please provide the following details as well,
* MC Version: 1.18.1
* C&B Version: 1.2.73
* Do You have Optifine: No (but I do have Iris)

**Comment by AlexdaCat** [comment]
it seems to show the outline correctly...

**Comment by marchermans** [comment]
Iris is not supported it likely does not support the fabric rendering api needed for c and b blocks
