### ISSUE TITLE
Crashing when chiseling!

### ISSUE THREAD

**Issue by TaylorElisaB** [ChiselsAndBits/Chisels-and-Bits#84]
Please help! It randomly starts to crash whenever i'm chiseling. I can sometimes chisel a little bit and sometimes I just place one chisel piece down before it crashes. I'm using the version 8.12 for 1.8.9 and I don't think I'm doing anything different when it crashes than when I can actually chisel. I just want to be able to enjoy this mod. I don't see anyone else experiencing this issue, so maybe it's just me. Please, tell me if I'm doing something wrong.

Here is the crash report:

http://pastebin.com/3GmySjiD

**Comment by AlgorithmX2** [comment]
You'll need to provide at minimum a crashlog.

that said 1.8.9 is mostly not supported anymore, but it might give us an idea of why its crashing tho.

**Comment by TaylorElisaB** [comment]
@AlgorithmX2 I'm sorry. I was doing that actually. I put it in the post.

**Comment by AlgorithmX2** [comment]
make sure your video drivers are up to date, seems like they are crashing.

**Comment by TaylorElisaB** [comment]
@AlgorithmX2 I've already tried to update my intel driver and java, but nothing has changed. I tried to check for another update and it said everything was already up to date. Is there any other reason for why they would be crashing?

**Comment by TaylorElisaB** [comment]
@AlgorithmX2 I've already updated java and my intel drive. The crash is still happening. I tried again to see if there was a new update but it said it was already up to date.

**Comment by TaylorElisaB** [comment]
@AlgorithmX2 I already tried to update my java and my intel drivers. The crash is still happening. I checked again to see if there was a new update, but it said it was already up to date.

**Comment by AlgorithmX2** [comment]
I assume this is an integrated GPU? Can you report on your exact CPU?

Could you try the latest build for 1.10, I want to know if one of the changes I made in the later builds had any impact on this.

**Comment by TaylorElisaB** [comment]
@AlgorithmX2 I actually think I fixed it. I restarted my computer and it seemed to do the trick. Maybe something just needed to be fixed. I haven't crashed since.

**Comment by AlgorithmX2** [comment]
Huh... Alright then? Maybe you hadn't restarted since updating the driver?

**Comment by TaylorElisaB** [comment]
@AlgorithmX2 Oh! No, I didn't actually. I didn't know that was needed. Thank you so much for helping! Sorry to bother you with something that was so simple to fix.
