### ISSUE TITLE
server crash when the player using some chiseled blocks and make the sever lag

### ISSUE THREAD

**Issue by miosel** [ChiselsAndBits/Chisels-and-Bits#840]
my friend make a fabric server, server get a crash when the player try to chiseling some build blocks.Here is the server console screenshot
![console screen shot](https://user-images.githubusercontent.com/97658379/149283102-38e19435-c1db-41ab-bc6a-b8f4fdacfdea.png)
server also use some fabric optimization mods for the server client (lithum mod and c^2m Engine/Concurrent Chunk Management Engine mod). before the crash, my friend found some weired problems that chunk get "frezee"wthere the player placed some chiseled bits in the ground.my friend told me it seems like that the chunk render bug (the server get some "ghost chunkblock",friend said can't unload the "ghost chunk" ) and then server get the massive lag,tps go to a low bility level. I'm not the 100% percent sure the chisel& bit mod uncompatibility with other mods .but when the server removed the chisel& bits mod  the game is fine without any tps lag problem.
[server.log](https://github.com/ChiselsAndBits/Chisels-and-Bits/files/7860966/server.log)
 For any bug reports please provide the following details as well,
* MC Version:1.18.1 fabric server
* C&B Version: ChiselsBits-fabric-1.18.1-1.2.62.jar
* Do You have Optifine:no

**Comment by marchermans** [comment]
Can you try updating to the latest version?
I made some bugfixes to this area of the code.

**Comment by miosel** [comment]
> Can you try updating to the latest version? I made some bugfixes to this area of the code.

I'll tell my friend updating to the latest version and do some testing. the issue will close when the server dosen‘t have any lag problems ,but still thank you for reply my issue :D

**Comment by marchermans** [comment]
To analyze the lag, please run a spark profile while it is happening with some minimal tick time to analyze, see its documentation on finding the cause of lag spikes on how to use it.

**Comment by miosel** [comment]
> 

aha, i think it's an userful suggesstion for my friend's server but yesterday he caught some higher mspt problems during the server working with ChiselsBits-fabric-1.18.1-1.2.62.jar version a few days with carpet mod (gnebonm) a vanilla server client mod for minecraft can show some info for the mspt occupy.

**Comment by marchermans** [comment]
Well C&B Blocks don't tick...
So i highly doubt it.

**Comment by miosel** [comment]
> Well C&B Blocks don't tick... So i highly doubt it.

He has some Carpetmod info screenshots ,i check it out a picture info show unloading chunk area occupy has 123mspt. at the begining we don't think it's chiselbits bug. but player playing the server, the lag still happen until the crash coming.Then he remove the chisel mod without any lag problem.He think the“weird chunk ”can't unload it (carpet dosen't show the loading). so he let me do a issue I"ll let him try the newest version.hope it working fine <3:

**Comment by miosel** [comment]
> Well C&B Blocks don't tick... So i highly doubt it.
![1c5c4fc802bbbeb0](https://user-images.githubusercontent.com/97658379/149336295-1711de84-44d4-4eec-8027-f7a8e2385896.png)
![1c43ea61f3d33a7c](https://user-images.githubusercontent.com/97658379/149336514-fcf833d4-707c-405d-b2d7-9e345b3c5ed4.png)
![1f01bb6d213fc20](https://user-images.githubusercontent.com/97658379/149336644-1035fb53-81f5-4245-8497-da4ecceefe64.png)
Carpet mod info screen shot and low tps high mspt when the lag coming with old version

**Comment by marchermans** [comment]
Well indeed depending on the version the Save code indeed takes a bit.
The newer versions have improved here a lot, to the point that I don't notice it any more in my profiling runs.
