### ISSUE TITLE
Server crashes

### ISSUE THREAD

**Issue by Gimligs** [ChiselsAndBits/Chisels-and-Bits#841]
When i try to remove some Chisel stuff made before this update, my server/game crashes.
Are using the modpack called FTB Presents Direwolf20 1.16

For any bug reports please provide the following details as well,
* MC Version:1.16.5
* C&B Version: 1.0.63
* Do You have Optifine: No

Anything u can help with, or it there something u wanna know?

Hope u can help me

Best regards Peter

**Comment by marchermans** [comment]
I would need to crashlogs to be of any help.

**Comment by Gimligs** [comment]
[](url
[crash-2022-01-13_18.27.37-client.txt](https://github.com/ChiselsAndBits/Chisels-and-Bits/files/7865841/crash-2022-01-13_18.27.37-client.txt)
)Here

**Comment by marchermans** [comment]
Can you update to the newest version?

**Comment by Gimligs** [comment]
I have the newest version to 1.16.5 version 1.0.63 :)

**Comment by marchermans** [comment]
Looked like i missed a corner case

**Comment by marchermans** [comment]
Fixed in 1.2.79
