### ISSUE TITLE
Abbreviations in the bit bag

### ISSUE THREAD

**Issue by loving2** [ChiselsAndBits/Chisels-and-Bits#842]
If you modify the capacity of the bit bag to large values (say 32768 for example) the count of bits overlaps and looks not so great. I think a nice little enhancement could be to add abbreviations in! I've attached a few screenshots as examples. Thanks!

An example of the overlap
![image](https://user-images.githubusercontent.com/26778483/149540635-077a8e38-a44a-499c-93e6-6e241e30229e.png)
An example of an abbreviated count with a hover tooltip displaying the full value
![image](https://user-images.githubusercontent.com/26778483/149540794-74fc3511-a0f8-4113-923c-3c17a2baca90.png)

**Comment by marchermans** [comment]
Fixed in latest
