### ISSUE TITLE
The Chiseled Bit Storage does not work

### ISSUE THREAD

**Issue by TheOnlyRex** [ChiselsAndBits/Chisels-and-Bits#844]
Hello, the Chiseled Bit Storage does not seem to work. I can't put any liquids in it, and when I click on it with an empty bucket or a milk bucket, the game crashes.

[crash-2022-01-16_23.33.38-client.txt](https://github.com/ChiselsAndBits/Chisels-and-Bits/files/7878079/crash-2022-01-16_23.33.38-client.txt)

For any bug reports please provide the following details as well,
* MC Version: 1.18.1
* C&B Version: 1.2.76
* Do You have Optifine: no

**Comment by marchermans** [comment]
Fixed in 1.2.77
