### ISSUE TITLE
Add Fabric version to lower than 1.18.1.

### ISSUE THREAD

**Issue by xiaobaimao233** [ChiselsAndBits/Chisels-and-Bits#845]
My friend makes a server with Fabric API(because ofMTR mod)
I want to play C&B in Minecraft with FabricAPI, But Your mod don't have Fabric version that lower than 1.18.1. So can You add Fabric version to lower than 1.18.1?

* MC Version: 1.16.5
* C&B Version: No Fabric version
* Do You have Optifine: Yes

**Comment by marchermans** [comment]
Sadly this will not happen.
There is no way I can support that, because of technical differences which where solved during the 1.18 update cycle.
