### ISSUE TITLE
Config file not found

### ISSUE THREAD

**Issue by Fabriluc** [ChiselsAndBits/Chisels-and-Bits#846]
Im running a  Forge server on a  hosting platform, and the new "config.toml" does not have any configurations, i need to change things, for example i'm having a bug with the blocks containing glowstone not lighting, even if it 99.9% glowstone, so i wanted to set percentage to 0 or look around to what setting causes it, but there's no settings, just some lines on performance and hitbox (just like in the local config.toml)

any help with that? can't configure chisel server-side

* MC Version: 1.16.5
* C&B Version: 1.0.63
* Do You have Optifine: Yes

**Comment by marchermans** [comment]
It is in the world save directory under serverconfigs.
