### ISSUE TITLE
chisel and bits going invisible 

### ISSUE THREAD

**Issue by KylewingYT** [ChiselsAndBits/Chisels-and-Bits#848]
hello so i saw some other people are having the same problem but mine isnt caused by optifine nor pam's harvest craft, its in a private server with me and my friends we have another server with the same two mods chisel and bits and pam's harvest craft and everything we chiseled didnt disappeared but when we made another server for a roleplay the chiseled walls and prize corner table keeps disappearing each time we rejoin and the version we use is 1.12.2.

we need help to fix the problem please and thank you

**Comment by marchermans** [comment]
Sorry 1.12.2 is not supported any more
