### ISSUE TITLE
Disappearing Act

### ISSUE THREAD

**Issue by CurelessWereWolf** [ChiselsAndBits/Chisels-and-Bits#849]
Heyyo! So I've Been Using Chisel & Bits FOr Awhile But SomeThing New Came Up, Before I Was About To Stort Recording For A Rp. All The Chisels & Bits Black Just Disappeared. I'm Using 1.12.2 With Optifine! Please Help Me! Ty

-CurelessWereWolf

**Comment by marchermans** [comment]
1.12 is not supported anymore

**Comment by CurelessWereWolf** [comment]
Why?

**Comment by marchermans** [comment]
Because it is more then four years old, the mod has moved on and changed a lot
