### ISSUE TITLE
Chisels and Bits stairs not 100% functional

### ISSUE THREAD

**Issue by oitsjustjose** [ChiselsAndBits/Chisels-and-Bits#85]
So I've made a [video](https://youtu.be/m_NbL5SG9I8) to demonstrate the issue more clearly.

This has been a bug for a while (1.8.9) but I've just now gotten around to reporting it - making stairs simply doesn't work! The first step works, but the second one doesn't - is the AABB messed up for the second half making Minecraft think you can't walk up it?

**Comment by AlgorithmX2** [comment]
You probably have a second mod installed that is modifying the player step-height, common culprits of this are mods with step-assist.

in 1.8+ StepHeight should be 0.6, in 1.7 it was 0.5 so its not uncommon for a mod author to not realize it changed and use the old value.

I'd start by making sure that all your mods with step assist features are up to date, and if that doesn't help try removing them from the instance to isolate which one is changing the value to 0.5

**Comment by oitsjustjose** [comment]
Give me about 20 minutes and I'll have a response for you :)

**Comment by oitsjustjose** [comment]
[Son of a *@&$! it was my own mod](https://github.com/oitsjustjose/V-Tweaks/blob/master/src/main/java/com/oitsjustjose/vtweaks/enchantment/EnchantmentStepboostHandler.java#L19)

**Comment by AlgorithmX2** [comment]
Well at least it wasn't hard to track down :)

**Comment by oitsjustjose** [comment]
GitHub needs a tag for "Submitter was just retarded"

That would apply here. Sorry to waste your time Algo :P
