### ISSUE TITLE
C&B stops working randomly

### ISSUE THREAD

**Issue by Buffbud96** [ChiselsAndBits/Chisels-and-Bits#850]
I am using the most recent Divine Journey 2 build. When I try to use the "Large Cube" I can break a single patch of block, but once the block has been "updated" to the C&B model, I can no longer chisel it. I'm able to place stuff back onto it, but cannot re-chisel the bits I placed again. This issue doesn't seem consistent between all blocks, some will work, others will not. 

For any bug reports please provide the following details as well,
* MC Version: 1.12.2
* C&B Version: 14.33
* Do You have Optifine: No

**Comment by marchermans** [comment]
1.12 is not supported anymore sorry.
