### ISSUE TITLE
Cannot choose chisel modes

### ISSUE THREAD

**Issue by anicatcandy** [ChiselsAndBits/Chisels-and-Bits#851]
Even after reconfiguring the hotkeys, I'm unable to open the radial menu or cycle between chisel modes.. this was an issue on 1.17 as well

Thank you for your time and for making this awesome mod!

For any bug reports please provide the following details as well,
* MC Version: 1.18.1
* C&B Version: Forge 1.18.1-1.2.77
* Do You have Optifine: no

**Comment by marchermans** [comment]
What keybinding did you set it to?

**Comment by anicatcandy** [comment]
I usually set the radial menu to Left ALT, but have tried it with multiple keys, it still doesn't work

**Comment by marchermans** [comment]
Okey i will see if i can reproduce it

**Comment by anicatcandy** [comment]
Hi!
Just curious how things are going.. also wanted to note that the other day I tried reinstalling the mod and tried the former version/update of it just to see if that might work... if that makes sense... but it didn't, unfortunately

**Comment by Meagan-Denton** [comment]
I'm also having this issue, on MC version 1.17.1
The Forge mod menu says the Chisels & Bits version is 1.1.39 Alpha (as that's the most recent version CurseForge showed for 1.17.1)
I am also using Optifine.
Even when using Configured to enable the "Tool mode change: right click" setting, the radial menu does not come up.
Just in case it's relevant: I'm in Creative Mode

**Comment by marchermans** [comment]
Fixed in 1.2.79
