### ISSUE TITLE
Low FPS while in Chisel mode

### ISSUE THREAD

**Issue by RurouniDonut** [ChiselsAndBits/Chisels-and-Bits#853]
Hello, this mod is awesome. Unfortunately however, I am getting lots of fps lag when using the chisels depending on the various modes. The circle for example, causes the game to be unplayable fps wise. Placing down bits is laggy as well.
Here's the logs and [screenshots]

https://mclo.gs/w7G9sK3

For any bug reports please provide the following details as well,
* MC Version: 1.16.5
* C&B Version: 1.0.63
* Do You have Optifine: False

![2022-01-23_04 31 36](https://user-images.githubusercontent.com/2947985/150672577-8c61eb62-c634-4436-85f5-3c9779a7e3ca.png)
![2022-01-23_04 31 59](https://user-images.githubusercontent.com/2947985/150672579-c386a25e-d231-4b79-867b-d0cc4d7f9949.png)
![2022-01-23_04 32 05](https://user-images.githubusercontent.com/2947985/150672580-eb4a5e93-1574-4926-86be-29ebb5de0773.png)
![2022-01-23_04 31 32](https://user-images.githubusercontent.com/2947985/150672581-228b7f2e-0d3e-4061-8ba2-d000c6ea28aa.png)

**Comment by vertexofvortex** [comment]
Have the same issue in Minecraft 1.16.5 with C&B 1.0.63, but with installed OptiFine and other mods (I play in Enigmatica 6 modpack).

As I noticed, the amount of framerate drop depends on how large bits selection box is: in single mode the lags are almost unnoticeable, but in 1/4 block selection the FPS drops to 10 and the game becomes unplayable.

The link to video demonstration of this problem: https://youtu.be/8NYM09VCDpc.

**Comment by marchermans** [comment]
The sphere is known to cause these issues.
I would need a Spark Profile of this, both with and without a minimal tick time of something like 30 ms.

**Comment by marchermans** [comment]
Fixed in 1.2.79

**Comment by MachineRat8** [comment]
Will this fix be ported to 1.16.5? If it has already, I can't find it.
