### ISSUE TITLE
invisble blocks

### ISSUE THREAD

**Issue by dandyfae** [ChiselsAndBits/Chisels-and-Bits#854]
everytime I hit a block with the chisel it turns invisble, I can still select blocks with the wrench which outlines them and I can see the bits missing outline, I can rotate blocks. I can also pick up and place bits. But all of it is invisble.

* MC Version: 1.18
* C&B Version: 2.6.4
* Do You have Optifine: no

**Comment by marchermans** [comment]
2.6.4 is not a valid version for Chisels and Bits.

**Comment by Xico26** [comment]
I have the same issue using the latest Fabric release (1.2.77). I don't have optifine. 
![2022-01-24_19 33 34](https://user-images.githubusercontent.com/47830278/150851799-22fa03aa-36c2-438c-b613-5028e9a7522b.png)

**Comment by marchermans** [comment]
> I have the same issue using the latest Fabric release (1.2.77). I don't have optifine. 
> ![2022-01-24_19 33 34](https://user-images.githubusercontent.com/47830278/150851799-22fa03aa-36c2-438c-b613-5028e9a7522b.png)
> 
> 

Can you make a new ticket for this?
Since you have a different platform

**Comment by Xico26** [comment]
Sure.

**Comment by marchermans** [comment]
Since the ticket creator is not responding, and does not seem to want to give a proper version number, or log I am closing this ticket
