### ISSUE TITLE
Invisible Blocks in the latest Fabric Version

### ISSUE THREAD

**Issue by Xico26** [ChiselsAndBits/Chisels-and-Bits#855]
Every time I use chisel & bits in a block, whether it's vanilla or not, the block goes invisible (similar to [this issue](https://github.com/ChiselsAndBits/Chisels-and-Bits/issues/854))

* MC Version: 1.18.1 (Fabric)
* C&B Version: Latest (1.2.77)
* Do You have Optifine: No

![2022-01-24_19 33 34](https://user-images.githubusercontent.com/47830278/150873575-7c88d8fd-9d76-4631-8466-bd53f5c27f8b.png)

**Comment by marchermans** [comment]
Do you use sodium or canvas?

**Comment by Xico26** [comment]
I use Sodium.

**Comment by marchermans** [comment]
Have you installed indium?

**Comment by Dayese** [comment]
This happens to me as well, no sodium or canvas

**Comment by marchermans** [comment]
> This happens to me as well, no sodium or canvas

Can you send me your mod list?
Or a log?

**Comment by Dayese** [comment]
Not sure how to spoiler on here, sorry.
These are the mods ive got on, i dont think anything here changes the render engine

 ![modlist 1](https://user-images.githubusercontent.com/98420323/151053383-9de5d097-32ad-4bc6-bae7-d3b28c991d26.PNG)
 ![modlist 2](https://user-images.githubusercontent.com/98420323/151053388-5dd8cdb8-debc-40bb-8472-45ec60d00c09.PNG)

**Comment by marchermans** [comment]
I am still going to need a log file

**Comment by Dayese** [comment]
[latest.log](https://github.com/ChiselsAndBits/Chisels-and-Bits/files/7937095/latest.log)

my bad

**Comment by marchermans** [comment]
Try removing frex.
I am working with them author to get it properly implemented but it is not yet there

**Comment by Dayese** [comment]
yup that did it, thanks for the brill mod

**Comment by Xico26** [comment]
I don't have frex installed so it is probably something else then 
[latest.log](https://github.com/ChiselsAndBits/Chisels-and-Bits/files/7937586/latest.log)

**Comment by marchermans** [comment]
You are missing indium.
Install it and it should work

**Comment by Xico26** [comment]
Thanks :)
