### ISSUE TITLE
Invisible blocks with Magnesium (the Forge version of Sodium Fabric)

### ISSUE THREAD

**Issue by Finelarme9** [ChiselsAndBits/Chisels-and-Bits#856]
Hey there,

Unfortunately it doesn't work with Magnesium (the Forge version of Sodium Fabric). The little blocks are invisible, not matter if I change the Magnesium settings. I guess this problem is on Magnesium side ?

* MC Version: MC 1.18.1 - Force 39.0.14
* C&B Version: ChiselsBits-forge-1.18.1-1.2.77-universal.jar
* Do You have Optifine: No. I use "[Magnesium 0.4.0 Alpha6](https://www.curseforge.com/minecraft/mc-mods/sodium-reforged/files/3556734)"

**Comment by marchermans** [comment]
Magnesium is officially unsupported.
