### ISSUE TITLE
Why were drawn regions and middle clicking chiselled blocks removed?

### ISSUE THREAD

**Issue by Mr-Udders** [ChiselsAndBits/Chisels-and-Bits#859]
Both of these I feel were core features of the mod and removing this has made chisels and bits borderline unusable. I'm wondering what the reasons for their removal were.

I'm using version 1.16.5 and I can't switch to 1.18 as I am also using immersive engineering, which has not updated to 1.18.

**Comment by marchermans** [comment]
Drawn regions where removed because I needed space to port, and time.
Middle clicking was not removed, you can hold shift to get the entire block.

Update to 1.18 if you want drawn region back.
