### ISSUE TITLE
[1.10.2] Client side crash on chisel

### ISSUE THREAD

**Issue by kwpugh** [ChiselsAndBits/Chisels-and-Bits#86]
Forge: 2010
Mod: chiselsandbits-11.5.jar

crash report: http://pastebin.com/raw/7yptbeVG

Player was attempting to shift-right click with the chisel and crashed the client.   No impact to server.

**Comment by AlgorithmX2** [comment]
Any idea what was in the pattern? Based on how it crashed the pattern appears to be blank, I have no idea how one would get a blank pattern.

**Comment by Tearahk** [comment]
Hello, Algo, I was the one who crashed. Basically, what happened before I crashed was: I went and made the Positive Chisel Design, set it to Additive mode, went upstairs and shift-right clicked on chiseld block I wanted to make into a patter. That block being made of smooth birch wood planks from the Chisel mod. The moment I did so, it crashed me back to the launcher. I logged back in and messed around with the Positive Chisel Design a bit more to see what had happened, and it seemed to only break everything down into bit, which lead me to believe that it for some reason copied an air block  and was imposing that on everything it touched. When I tried to replace the pattern a second time, in a panic I clicked on a full block of smooth birch wood planks, and it crashed me again.

What was weird about this is I couldn't remove this "pattern" from it to try again. I acted as if it was both empty and written on at the same time.

**Comment by AlgorithmX2** [comment]
I think the real problem here comes from the first crash, but the crash above doesn't seem to be that one, it seems to be using the broken pattern.

Creating a corrupted pattern is a problem, using a corrupted pattern is a byproduct.

**Comment by Tearahk** [comment]
True true, I was just tryin to go through all of what happened in case there was something weird in what I did. All I know is that when I tried to shift-right click to add the smooth birch plank chiseled block to the pattern the first time I ever used it, it crashed me. ^^

**Comment by AlgorithmX2** [comment]
Turns out it was pretty simple, Modes don't do anything before you capture something on the pattern, so I've never seen what happens when you set a mode on a blank pattern, answer: a corrupt pattern.

I've added additional logic to ensure that patterns are only "written" when they have real data, and not just a mode.

**Comment by Tearahk** [comment]
Ohhhhhhh, so I should write the pattern before setting a mode. That makes sense. ^_^
