### ISSUE TITLE
Crashes with Optifabric

### ISSUE THREAD

**Issue by Amber-09** [ChiselsAndBits/Chisels-and-Bits#860]
I'm using the C&B for fabric, and I also use optifine as a mod, which means I need the optifabric mod to make it work (so I can use shaders with my mods). However, when I added C&B, the game would crash with exit code: 0.

I took all mods out except for C&B, and it did not crash. I put all mods back in expect the two optifine files, and it did not crash. I then just put optifine back in without optifabric, and it did not crash. Lastly, I put optifabric back in and took C&B out, and it did not crash. So, that means C&B and Optifabric won't work together? 

I also use C&B for fabric instead of forge so I can use the replay mod. 

It is not dire to me that C&B works with Optifabric. I was just going to open an issue to see if there's a possibility for the to be able to work together.

For any bug reports please provide the following details as well,
* MC Version: 1.18.1
* C&B Version: 1.18.1
* Do You have Optifine: yes

**Comment by marchermans** [comment]
Yes, we officially only support sodium as rendering engine

**Comment by Amber-09** [comment]
Oh okay, I did not know. Thank you
