### ISSUE TITLE
fps drop when placing/breaking bits

### ISSUE THREAD

**Issue by AleFunky** [ChiselsAndBits/Chisels-and-Bits#862]
Before continuing if you are reporting an issue, please ensure that all mods involved are updated to the latest version available, if your issue with with intermod compatibility such mixing C&B bits with other blocks make sure that MCMP is also updated. If your issue is a crash, be sure to include the crash log with your report.

May relate to #853 but that one was on forge, but in this one is fabric, and doesn't lag in bits mode

installed mods are:
-sodium
-indium
-dynamic fps
-enhanced block entities
-ferrite core
-lazy dfu
-ok zoomer
-pehkui
-starlight
-lamb dynamic lights

For any bug reports please provide the following details as well,
* MC Version: fabric 1.18.1
* C&B Version: 1.2.77
* Do You have Optifine: no

**Comment by marchermans** [comment]
It is know, it is related to the change tracker.
I have it fixed internally the release just needs some polishing.

**Comment by AleFunky** [comment]
wow nice! also thanks for the fast response 😃

**Comment by AleFunky** [comment]
is going to be released soon? i want to play with this but with the fps drop and with some dissapearing bits is hard to do

**Comment by marchermans** [comment]
Yeah it will be, last remaining bugs to iron out are in the preview system.
Once those are cleaned I will release them

**Comment by AleFunky** [comment]
nice

**Comment by marchermans** [comment]
Fixed in 1.2.79
