### ISSUE TITLE
[Bug] Modification Table not working

### ISSUE THREAD

**Issue by c0smicSalm0n** [ChiselsAndBits/Chisels-and-Bits#863]
Modification Table shows nothing when i put a pattern in it

* MC Version: 1.18
* C&B Version: 1.2.77
* Do You have Optifine: no

**Comment by marchermans** [comment]
Found and reproduced.

**Comment by marchermans** [comment]
Fixed in 1.2.79

**Comment by robmart** [comment]
Having the same issue on 1.19.2, mod version 1.3.135. No optifine.

**Comment by marchermans** [comment]
@robmart can you create a recording of what you are trying to do and what you see?

**Comment by robmart** [comment]
@marchermans It seems like it was a code 1D10T. I was just using the table incorrectly, trying to use a sealed pattern. My bad. Though perhaps having an error inside the UI if a sealed pattern is placed inside would make it clearer.

**Comment by marchermans** [comment]
Can you create a new issue for that? So I have a reminder....
