### ISSUE TITLE
bits renders invisible with indium

### ISSUE THREAD

**Issue by AleFunky** [ChiselsAndBits/Chisels-and-Bits#864]
Indium is installed.

New bits renders invisible, doesn't happen to bits placed before updating from 1.2.77.

installed mods are:
-sodium
-indium
-dynamic fps
-enhanced block entities
-ferrite core
-lazy dfu
-ok zoomer
-pehkui
-starlight
-lamb dynamic lights

For any bug reports please provide the following details as well,
* MC Version: 1.18.1
* C&B Version: 1.2.79
* Do You have Optifine: no

**Comment by marchermans** [comment]
Can you send me some screenshots?

**Comment by AleFunky** [comment]
ok so i can't reproduce again the glitch so i will just close the issue
