### ISSUE TITLE
Water renders brown

### ISSUE THREAD

**Issue by AleFunky** [ChiselsAndBits/Chisels-and-Bits#865]
Before continuing if you are reporting an issue, please ensure that all mods involved are updated to the latest version available, if your issue with with intermod compatibility such mixing C&B bits with other blocks make sure that MCMP is also updated. If your issue is a crash, be sure to include the crash log with your report.

literally what title says
![imagen](https://user-images.githubusercontent.com/55950650/152654894-003b3e7e-e198-4ecb-be74-c637c787532d.png)

For any bug reports please provide the following details as well,
* MC Version: 1.18.1
* C&B Version: 1.2.79
* Do You have Optifine: no

**Comment by marchermans** [comment]
Does normal water render brown in that biome

**Comment by AleFunky** [comment]
nope, water in that biome render blue, is a forest the biome

**Comment by AleFunky** [comment]
![imagen](https://user-images.githubusercontent.com/55950650/152686200-35682012-4591-4827-b3aa-eadc194adb90.png)

**Comment by marchermans** [comment]
Weird. I have never seen that one.
Will do some research

**Comment by marchermans** [comment]
Not reproducable to me:
![image](https://user-images.githubusercontent.com/5585406/152851716-39208598-dd48-47db-91d0-f0beea75e759.png)

**Comment by marchermans** [comment]
But I might have an idea what the cause is.

**Comment by netcore10** [comment]
Can confirm, happens to me too

**Comment by marchermans** [comment]
Fixed in 1.2.100
