### ISSUE TITLE
timeout issue

### ISSUE THREAD

**Issue by fit0883** [ChiselsAndBits/Chisels-and-Bits#866]
Before continuing if you are reporting an issue, please ensure that all mods involved are updated to the latest version available, if your issue with with intermod compatibility such mixing C&B bits with other blocks make sure that MCMP is also updated. If your issue is a crash, be sure to include the crash log with your report.

For any bug reports please provide the following details as well,
* MC Version: 1.18.1
* C&B Version:ChiselsBits-forge-1.18.1-1.2.79-universal
* Do You have Optifine:yes( not server)

[latest.log](https://github.com/ChiselsAndBits/Chisels-and-Bits/files/8008853/latest.log)

**Comment by fit0883** [comment]
[
[crash-2022-02-06_05.22.56-server.txt](https://github.com/ChiselsAndBits/Chisels-and-Bits/files/8008874/crash-2022-02-06_05.22.56-server.txt)
](url)

**Comment by marchermans** [comment]
Something in the save code is hanging.
Weird.

I will check it out

**Comment by marchermans** [comment]
Fixed in 1.2.100
