### ISSUE TITLE
bits become invisible after a certain amount of time

### ISSUE THREAD

**Issue by ghost** [ChiselsAndBits/Chisels-and-Bits#867]
every time I build using this mod the bits stop rendering and won't render again until I restart the game, no matter what I've tried it happens every single time, I've tried changing video settings, removing mods and even switching from the fabric version to the forge version and it keeps happening, I tried using optifine and the same thing happened so I'm unsure what to do

edit:forgot to mention the version is 1.18.1

another edit: also when I click save and quit after this happens, it endlessly says 'saving game' and just stays like that, I have to forcefully stop minecraft with task manager

tried downloading indium after reading some closed issues but it still happens

**Comment by AleFunky** [comment]
can relate, sometimes placing stops working and starts glitching and sometimes roll backs what i build

**Comment by oliverrook** [comment]
I think this is related to the previously mentioned timeout issue.

**Comment by marchermans** [comment]
Fixed in 1.2.100
