### ISSUE TITLE
Chisels and Bits crashes the client when trying to join the server

### ISSUE THREAD

**Issue by frikinjay** [ChiselsAndBits/Chisels-and-Bits#869]
Before continuing if you are reporting an issue, please ensure that all mods involved are updated to the latest version available, if your issue with with intermod compatibility such mixing C&B bits with other blocks make sure that MCMP is also updated. If your issue is a crash, be sure to include the crash log with your report.

Chisels and Bits crashes the client when trying to join the server. 
Steps to reproduce is pretty random, just play on the server have some diamond chisels and bits and bit pouches in your inventory and the crash will eventually happen.

Crah log: https://pastebin.com/di7TYiGf

For any bug reports please provide the following details as well,
* MC Version: 1.18.1
* C&B Version: 1.2.79
* Do You have Optifine: No

**Comment by marchermans** [comment]
Found will be fixed. Thanks for the report.

**Comment by frikinjay** [comment]
np
