### ISSUE TITLE
Texture Packs don't work well with mod.

### ISSUE THREAD

**Issue by Jestingtank** [ChiselsAndBits/Chisels-and-Bits#870]
Whenever I use texture packs the textures for the chiseled blocks get weird.
I tried it with and without optifine.

**Comment by marchermans** [comment]
Not reproduceable to me.

**Comment by marchermans** [comment]
Can you provide the texture pack and a video showing the effect

**Comment by marchermans** [comment]
Fixed in 1.2.100
