### ISSUE TITLE
Some issues.

### ISSUE THREAD

**Issue by lysy016** [ChiselsAndBits/Chisels-and-Bits#872]
* MC Version:1.18.1
* C&B Version:1.2.79
* Do You have Optifine:No
* Other Mods: Immersive Portals 1.2.5, Gravity Changer 0.3.0, Pehkui 3.1.0, Fabric API 0.46.4

1.
![2022-02-10_15 47 59](https://user-images.githubusercontent.com/54468474/153373433-cdea9ba3-f66d-480d-bedf-6ec87071ab62.png)
I can't read the full description, even if I put it into the last slot. And I don't know how to remove those items in the clipboard, or how to insert something into the bit storage(right click doesn't work).
2.
![2022-02-10_15 50 44](https://user-images.githubusercontent.com/54468474/153373623-f630cdf3-c2ec-422e-a152-7fe67fb0a6d0.png)
A rendering issue.
3.
![2022-02-10_16 03 36](https://user-images.githubusercontent.com/54468474/153373707-c7febfea-dc78-400e-86f9-d9c81fa837bb.png)
![2022-02-10_16 04 52](https://user-images.githubusercontent.com/54468474/153373873-7c23b2a8-4d0f-41fd-ba2b-3274195f5eb0.png)
Another rendering issue, the water is rendered brown.And when I jumped into the "water"(by using Pehkui),there seems to be no water...
4.
![2022-02-10_15 53 34](https://user-images.githubusercontent.com/54468474/153374126-19866915-6f9c-4d87-b909-8d0a1348ff08.png)
![2022-02-10_15 53 46](https://user-images.githubusercontent.com/54468474/153374154-49ea6c21-0d0d-4f4e-be60-e7ad9f16c92d.png)
When I use wrench, the block is turned into a "full" block - bits cannot fill the blank.
5.
![2022-02-10_15 54 48](https://user-images.githubusercontent.com/54468474/153374575-ab2e8715-88b5-4a65-9b73-88848b2ceca9.png)
![2022-02-10_15 56 31](https://user-images.githubusercontent.com/54468474/153374625-166aaf00-05cd-4fa6-85d2-4e03cff875d3.png)
When I use "Plane" mode, it's OK. But then I use 2x2, here is the problem.
![2022-02-10_15 56 52](https://user-images.githubusercontent.com/54468474/153374852-786653a2-8de1-45f0-be28-075bc07bb7bc.png)
Then the world feedback goes wrong, the water doesn't flow. And using chisel will destory the whole block. No particles.
I cannot quit normally, just "Saving world...". When I enter the world again, it was rolled back.
6.
![2022-02-10_15 59 30](https://user-images.githubusercontent.com/54468474/153376057-681d84ee-20ac-4cc8-bef3-b01d0ea499d6.png)
There is no grid.
7.This mod cannot work with sodium because chiseled blocks will be invisible.

**Comment by ghost** [comment]
pretty sure if you use sodiumyou have to install indium
 and that should fix the last issue
 didnt work for me but worth a try

**Comment by lysy016** [comment]
You're right. The 7th problem is immediately solved with indium. Thanks.

**Comment by marchermans** [comment]
Fixed in 1.2.100, at least most of this, what is not is not fixable.
