### ISSUE TITLE
Blocks completely disappearing 

### ISSUE THREAD

**Issue by FnafPizzaFan** [ChiselsAndBits/Chisels-and-Bits#873]
MC Version: 1.18.1
C&B Version: 1.18.1, latest - fabric
No optifine 

Mods used:
Immersive Portals
Gravity Changer
cloth-config

When chiseling, the blocks completely disappear 
quite hard to explain so I recorded a video 

https://youtu.be/DVCH-0ug6hY

**Comment by naly-best** [comment]
I'm also having this problem. I'm using C&B version 1.18.1 - 1.2.77

**Comment by marchermans** [comment]
Check the latest update.
It should fix it.
