### ISSUE TITLE
Bits Disappearing, but Not in the Same Way as Everyone Else Who is Having This Issue

### ISSUE THREAD

**Issue by PikaDominator** [ChiselsAndBits/Chisels-and-Bits#875]
Minecraft Version: 1.18.1, Forge Version 39.0.5
Chisels and Bits Version: 1.2.62
Optifine: No
Other Mods in Use: WorldEdit 7.2.8; JourneyMap 5.8.0beta4

Issue: 
(short story) When I destroy bits in a block and then replace them with other bits from another block, the new bits I added to the newly created full block disappear.

(explanation) Okay, so I am trying to make some road line blocks out of bits of the concrete blocks in Minecraft. I dug a 4x16 rectangle out of the middle of the top layer of a light gray concrete block, and then took bits from a white concrete block and replaced the removed bits. I would then, of course, have made light gray concrete block with a white line on the top.
It went all good, as I was replacing the removed bits, but as soon as I placed the last bit, the one that would have made the block a FULL block again, all of the white concrete bits I had placed disappeared. None of the light gray concrete bits that made up the same block disappeared. 

Everyone else seems to be having similar issues, except usually it is whole blocks disappearing, and almost every one I read had to do with Sodium or Indium or something like that. My situation is quite different, in an almost-vanilla otherwise Minecraft, and as such, I decided to open another issue.

Please comment for further details and/or answers. Thank you to whoever can help.

**Comment by marchermans** [comment]
Can you record the behaviour and upload it?
Also please test the new update.

**Comment by PikaDominator** [comment]
The file size was too large for GitHub so I uploaded it somewhere, since I'm not at all an expert or even remotely knowledgeable about video files, haha.
https://gofile.io/d/LOCUjN
The page should include the video imbedded so you don't have to download it.

**Comment by marchermans** [comment]
Ah yeah that was a bug in the model cache.
Update to the latest version and it should be fixed.
