### ISSUE TITLE
Bits disappear when breaking blocks.

### ISSUE THREAD

**Issue by Timtower** [ChiselsAndBits/Chisels-and-Bits#876]
For any bug reports please provide the following details as well,
* MC Version: 1.18.1
* C&B Version: 1.2.81
* Do You have Optifine: No

Breaking a full block with a chisel does not drop all bits.
Would expect the block to be not fully broken or the bits to be dropped on the ground.
It currently fills my inventory, offhand, and then bits disappear.

**Comment by marchermans** [comment]
There is a config option to control this.
