### ISSUE TITLE
[fabric] blocks are invisible for a few frames when chiseled

### ISSUE THREAD

**Issue by Chuunkyz** [ChiselsAndBits/Chisels-and-Bits#877]
this

**Comment by marchermans** [comment]
This is normal. The model compute engine runs off-thread and depending on your CPU it can take a hot second for it to compile.

**Comment by Chuunkyz** [comment]
so it will not be fixed ?

**Comment by marchermans** [comment]
No, this is literally by design, it should at most be a handful of frames. And if i did not do that you would have a decent amount of lag spikes.
