### ISSUE TITLE
Lighting Problems

### ISSUE THREAD

**Issue by MrFedora121** [ChiselsAndBits/Chisels-and-Bits#878]
MC Version: 1.18.1

 C&B Version: 1.2.81

Do You have Optifine: Yes

(When you have smooth lighting on is more visible) in any block sized chisel the lighting will bug and get darker arround the corners of the block face (happend me most when i used them in walls)

**Comment by marchermans** [comment]
Remove optifine, update to the latest version and enable Enchanced Ambient Occlusion / Experimental rendering pipelines.
