### ISSUE TITLE
Odd bit bug on servers

### ISSUE THREAD

**Issue by Prospector** [ChiselsAndBits/Chisels-and-Bits#88]
When you make a chiseled structure, then pick block it, and place it onto another chiseled structure (in the same block as it), no other players can see it except for you. Then when you relog, it disappears.

Steps to reproduce:
1. Get on a server (might work in single player, have not tested)
2. Make a bit structure (within 1 block)
3. Pick-block that bit structure
4. Make a second bit structure (within 1 block) and leave room for you to place the other structure in that same block
5. Use the shift hotkey to place your first structure inside of this one.
6. You will see it as you would expect. Then either relog or have another player look at it. The structure you placed on will not be visible.

Here is the way we found this bug:

I made a sign for our BTM booth, and I made the letters seperately from the background. When I placed the letters on the background, it looked like this to me:

![image](https://cloud.githubusercontent.com/assets/6166773/16896564/a77632ee-4b4c-11e6-9a9d-770c488d4253.png)

however to any other player on the server, it looked like this (look on the right outside of chat):

![image](https://cloud.githubusercontent.com/assets/6166773/16896567/b51b9092-4b4c-11e6-89f3-6cdb615f3293.png)

After disconnecting and reconnecting, the text also disappeared for me as well.

**Comment by AlgorithmX2** [comment]
Well found the problem...

from CPacketPlayerTryUseItemOnBlock
read: this.facingX = (float)buf.readUnsignedByte() / 16.0F;
write: buf.writeByte((int)(this.facingX \* 16.0F));

darn it Mojang... excuse me while I bang my head on the wall for several minutes and then try to think up a way to work around this nonsense.

**Comment by AlgorithmX2** [comment]
Well that was a lot of meh, ed4a3f7fec121e260a92992715a219da65524826 seems to resolve it.. and hopefully not cause any other problems.

**Comment by Prospector** [comment]
yay!
