### ISSUE TITLE
Issue 

### ISSUE THREAD

**Issue by Nikodem840** [ChiselsAndBits/Chisels-and-Bits#880]
* MC Version: 1.18.1
* C&B Version: 1.2.81
* Do You have Optifine: i have better fps

here's what happend like stone chisel should have like 500 durability yes? But there's something like that with black durability! (i maked second by chiseling blocks)
![image](https://user-images.githubusercontent.com/73533218/154460367-22b63eb7-eb6c-4e6c-a828-a785d193e568.png)
![image](https://user-images.githubusercontent.com/73533218/154460453-75e3a7db-e5e9-4dee-a86a-4832976a71a1.png)

Discord Contact: N0thing#5416

OH and i can't chisel moss

**Comment by marchermans** [comment]
Fixed in 1.2.100
