### ISSUE TITLE
Chisels & and bits startup error

### ISSUE THREAD

**Issue by VulDovahkiin** [ChiselsAndBits/Chisels-and-Bits#881]
Before continuing if you are reporting an issue, please ensure that all mods involved are updated to the latest version available, if your issue with with intermod compatibility such mixing C&B bits with other blocks make sure that MCMP is also updated. If your issue is a crash, be sure to include the crash log with your report.

For any bug reports please provide the following details as well,
* MC Version:1.16.5
* C&B Version:1.0.63
* Do You have Optifine:YES
[crash-2022-02-20_06.18.00-fml.txt](https://github.com/ChiselsAndBits/Chisels-and-Bits/files/8103955/crash-2022-02-20_06.18.00-fml.txt)

**Comment by marchermans** [comment]
Might be related to an outdated Create version?
I would need to talk with Simi and Jozu about this then.

**Comment by marchermans** [comment]
Related to create not C&B.
