### ISSUE TITLE
Crash: Tesselating Block Model

### ISSUE THREAD

**Issue by Alrena** [ChiselsAndBits/Chisels-and-Bits#883]
For any bug reports please provide the following details as well,
* MC Version: 1.18.1
* C&B Version: 1.2.81
* Do You have Optifine: Yes

[crash-2022-02-25_23.56.15-client.txt](https://github.com/ChiselsAndBits/Chisels-and-Bits/files/8148199/crash-2022-02-25_23.56.15-client.txt)

This crash happened when I was attempting to place a bit. Nothing else was happening as far as I know, but I have a small castle mockup that the bit was part of (around 3 blocks in total size)

**Comment by marchermans** [comment]
Fixed in 1.2.100
