### ISSUE TITLE
Bits not rendering w/ Shaders

### ISSUE THREAD

**Issue by DjPlezYT** [ChiselsAndBits/Chisels-and-Bits#885]
When playing in vanilla minecraft, Bits are showing. When playing with Shaders, they're not. Bits are invisible
Playing on 1.18.1 on Fabric with Iris & Sodium

**Comment by marchermans** [comment]
Iris is not supported.

**Comment by LilTwinky** [comment]
Spent forever trying to figure this out. After installing indium, I would get this ghostly effect on C&B blocks. Tried out a few different shaders and discovered that Sildur's Vibrant shader pack works (Do not use Sildur's Vibrant shaders v1.32 Extreme-Volumetric lighting) with C&B and Iris installed. Hope this helps anyone till Iris becomes supported. :)
