### ISSUE TITLE
Extreme lag from chisel on certain modes

### ISSUE THREAD

**Issue by NatMath** [ChiselsAndBits/Chisels-and-Bits#886]
Whenever setting the chisel to certain modes, my FPS drop massively. From my testing, it seems to be partly dependent on the amount of bits, as modes like 1x1x1, 1x1x16 and planes barely affect fps, while modes like 8x8x8 drop to 0FPS. Medium modes like 2x2x16 are in-between. This happens with all chisels. I havea attached a screenshot with all Optifine debug information.

This is what I gathered from my testing:
High Impact Modes:
-Lines bigger than 4x4x16
-Any Sphere
-Cubes bigger than 1x1x1
Low Impact Modes:
-Single bit
-Planes of any size
-1x1 lines

Specs:
-MC Version: 1.16.5 (Enigmatica 6 version 0.5.25)
-C&B Version: 1.0.63 (Same behaviour on 1.0.43)
-Optifine
-CPU: i7-9750H (6 core)
-GPU: GTX1650
-RAM: 8GB
-Dedicated server run on same PC.
![2022-03-02_19 48 34](https://user-images.githubusercontent.com/64751772/156476584-48c0d696-d6f9-4f33-b010-1e26b7f99327.png)

**Comment by marchermans** [comment]
Yeah I am aware.
At the moment though 1.16.5 is still outside of my timeline capabilities to fix.

I want to fix it but I don't have the time at the moment.

**Comment by GameStreakerDE** [comment]
Still lagging

**Comment by 123mind123** [comment]
Yeah it would appear this problem is still ongoing.

**Comment by marchermans** [comment]
This is known and fixed in modern versions of the mod especially those for 1.19.x.

It won't be backported to 1.16.5 due to time constraints
