### ISSUE TITLE
drawn region is not working i can only break blocks with it I'm playing in 1.18 can anyone help

### ISSUE THREAD

**Issue by panydralive** [ChiselsAndBits/Chisels-and-Bits#888]
Before continuing if you are reporting an issue, please ensure that all mods involved are updated to the latest version available, if your issue with with intermod compatibility such mixing C&B bits with other blocks make sure that MCMP is also updated. If your issue is a crash, be sure to include the crash log with your report.

For any bug reports please provide the following details as well,
* MC Version:
* C&B Version:
* Do You have Optifine:

**Comment by marchermans** [comment]
Please fill in the form, and provide logs.
