### ISSUE TITLE
Measure tape problems

### ISSUE THREAD

**Issue by sabera-7** [ChiselsAndBits/Chisels-and-Bits#889]
Before continuing if you are reporting an issue, please ensure that all mods involved are updated to the latest version available, if your issue with with intermod compatibility such mixing C&B bits with other blocks make sure that MCMP is also updated. If your issue is a crash, be sure to include the crash log with your report.

For any bug reports please provide the following details as well,
* MC Version: Minecraft 1.18.1 (Forge 39.0.88)
* C&B Version: 1.2.79
* Do You have Optifine: Yes

• I can't clear my measurements using keybinds
• In the description of the measure tape, instead of individual characters on the keyboard, there are the following characters: "{}"

**Comment by Marco-Zechner** [comment]
Same issue on 1.18.2
C&B Version 1.18.2 - 1.2.90
Forge 1.18.2 - 40.1.30
I have no Optifine (Instead I use Oculus)

**Comment by marchermans** [comment]
Fixed in 1.2.100
