### ISSUE TITLE
Crash/World corruption

### ISSUE THREAD

**Issue by perchy22** [ChiselsAndBits/Chisels-and-Bits#89]
Using FTB Unstable 4.1.2
[crash-2016-07-17_15.11.48-client.txt](https://github.com/AlgorithmX2/Chisels-and-Bits/files/368184/crash-2016-07-17_15.11.48-client.txt)

I've only been using the Tape Measure so far. Crash occurred a few seconds after taking it out of a Baggensis bag, going down a ladder with it selected (intending to use it in the room below). I might have accidentally clicked with it, but I'm pretty sure not. Same crash occurs when trying to reload the save. I tried to NBT edit out the tape measure, but no luck. Thankfully, a backup had run a few minutes prior.

I have a tarball of the corrupted save, if that would help.

**Comment by AlgorithmX2** [comment]
That's quite strange, for some reason the object in MC that stores what your looking at is null which is causing the crash, I've never seen this happen, another mod in your packet is probably resulting in the crash indirectly.

Should be resolved by https://github.com/AlgorithmX2/Chisels-and-Bits/commit/43eecf8a8b393265d36a2b75dd1195dccc03ee7d
