### ISSUE TITLE
Heavy lags with a large amount of compressions

### ISSUE THREAD

**Issue by Aviator737** [ChiselsAndBits/Chisels-and-Bits#891]
Every time a chunk with a chiseled block is loaded, compression starts and at large amounts the server crashes (or heavy lags at least).
There are not so many chiseled blocks, I think around a thousand is enough for the server to crash (3GB RAM allocated, 2 cores 3GHz) 

[debug.log](https://github.com/ChiselsAndBits/Chisels-and-Bits/files/8238755/debug.log)

spam at debug.log:
[mod.chiselsandbits.utils.CompressionUtils/]: Original: 4 Kb
[mod.chiselsandbits.utils.CompressionUtils/]: Compressed: 0 Kb

* MC Version: 1.16.5
* C&B Version: 1.0.63
* Do You have Optifine: yes

**Comment by marchermans** [comment]
This is indeed known on the 1.16.x versions.

In 1.18 I updated to a more complex saving system which took care of this, sadly I am not able to backport that mechanic to 1.16 due to me not having time to do so.

**Comment by TheHudsonHawk21** [comment]
Any update on if you'll have time to fix this? No pressure, just curious as I love this mod and would love to use it for 1.16.5.

**Comment by marchermans** [comment]
This will not be backported to 1.16.5
