### ISSUE TITLE
Could not set block error & crash

### ISSUE THREAD

**Issue by Cyranos** [ChiselsAndBits/Chisels-and-Bits#894]
* MC Version: 1.16.5
* C&B Version: 1.0.63
* Do You have Optifine: No, Not even Magnesium

I do not know how to really describe the issue so I have instead included a video, so I hope that is okay, as well this crash / bug doesn't incur a crash log being generated though in the lastes.log I see this spammed up until the game crashes
![image](https://user-images.githubusercontent.com/16463091/159979080-51c425f6-03c9-4ca7-8fe0-09eb5b9beada.png)

https://user-images.githubusercontent.com/16463091/159979969-4e25c80d-9a57-40a4-af40-5c1e784c24d3.mp4

**Comment by marchermans** [comment]
I will need logs for this please

**Comment by Cyranos** [comment]
[latest - Copy video.log](https://github.com/ChiselsAndBits/Chisels-and-Bits/files/8345034/latest.-.Copy.video.log)
Here ya go!

**Comment by Cyranos** [comment]
I apologize for commenting again, I am just curious if there is anything else you need?

**Comment by marchermans** [comment]
No
I just need to research it.
Had no time yet, IRL is really busy

**Comment by Cyranos** [comment]
Okay, np! I understand that IRL can be a pain so take it easy I would rather wait if it meant you don't burn out or have any major issues!

**Comment by marchermans** [comment]
Fixed in 1.2.100
