### ISSUE TITLE
Question: Maybe the newest C&B is incompatible with Optifine?

### ISSUE THREAD

**Issue by creamIcec** [ChiselsAndBits/Chisels-and-Bits#897]
For any bug reports please provide the following details as well,
* MC Version: 1.18.2
* C&B Version: ChiselsBits-forge-1.18.2-1.2.83-universal.jar
* Do You have Optifine: Yes
When I tried to start the game with C&B and Optifine together, it showed
"java.lang.reflect.InvocationTargetException: null" as the log file included, and then I just couldn't boot to the main menu but quit.
But when I tried to load the game with only C&B, it started successfully.
I guess that maybe this is caused by Optifine. Is it? If so, is there any way to solve this? I'm a little annoyed because I can't appreciate my work with shaders😣.

[latest.log](https://github.com/ChiselsAndBits/Chisels-and-Bits/files/8402762/latest.log)

**Comment by marchermans** [comment]
THis is known.
C&B is not compatible with optifine.
There is nothing I can do, since Optifine is closed source.
