### ISSUE TITLE
Bits not hiding with REI

### ISSUE THREAD

**Issue by ModernGamingWorld** [ChiselsAndBits/Chisels-and-Bits#899]
So I was wondering if there is a way to have the bits get hidden from REI as it does in JEI, Currently in my custom 1.18.2 mod pack, I am using REI and running into an issue where if inject-bits = false, it does not hide them. 

For any bug reports please provide the following details as well,
* MC Version: 1.18.12
* C&B Version: 1.18.2-1.2.83
* Do You have Optifine: no

**Comment by marchermans** [comment]
I use the JEI api on forge. There is no support for REI, not in forge nor on fabric

**Comment by ModernGamingWorld** [comment]
never mind, then I will just hide them one by one in rei. sorry for wasting your time

**Comment by marchermans** [comment]
It is not a problem,
I might add support for it.

**Comment by ModernGamingWorld** [comment]
> It is not a problem, I might add support for it.

If it helps, I am using REI on both 1.18.2 and 1.16.5

**Comment by marchermans** [comment]
Are you on fabric?

**Comment by 0gp** [comment]
same issue here. 1.18.2 Fabic
a config option to show bits in REI would be great.

**Comment by marchermans** [comment]
Fixed in 1.2.100
