### ISSUE TITLE
How does clipboard work?

### ISSUE THREAD

**Issue by Execoote** [ChiselsAndBits/Chisels-and-Bits#900]
Hey there,
Just a basic question here,
How does chisels and bits clipboard work?

**Comment by marchermans** [comment]
Which version are you in?

**Comment by Execoote** [comment]
> Which version are you in?

im in the latest version of the mod and im in mc 1.18.1

**Comment by Execoote** [comment]
> Which version are you in?

latest version of mod and im in 1.18.1

**Comment by marchermans** [comment]
Ah it stores the latest blocks you broke in creative mode
it functions as a cross save copy and placement logic.
