### ISSUE TITLE
Drawn region?

### ISSUE THREAD

**Issue by Jushylol** [ChiselsAndBits/Chisels-and-Bits#901]
So i just started using chisel n bits for the first time in a while and I guess there had to have been an update or something because everything seems completely different from how i remember. (Playing on 1.17.1 btw) my big question is where is the drawn region option? I can't seem to find it anywhere and it was my most used and most helpful tool back in the day. Did it get removed?

**Comment by marchermans** [comment]
It was added back in in 1.18.1 after the port completed.

**Comment by Jushylol** [comment]
> It was added back in in 1.18.1 after the port completed.

Damn. Sucks for me I guess. Thanks for the info tho
