### ISSUE TITLE
Cant craft anything

### ISSUE THREAD

**Issue by error44044** [ChiselsAndBits/Chisels-and-Bits#902]
Before continuing if you are reporting an issue, please ensure that all mods involved are updated to the latest version available, if your issue with with intermod compatibility such mixing C&B bits with other blocks make sure that MCMP is also updated. If your issue is a crash, be sure to include the crash log with your report.

For some reason when I try to use C&B crafting glitches out and it wont let me craft anything that involves more than one block, for example when I tried to craft sticks to make a chisel, when I put two oak planks it only resulted in a button, and when I craft the button it deletes my other plank. The rest of the mod works fine it's just this issue and I have no idea whats going on.

For any bug reports please provide the following details as well,
* MC Version: 1.18.2
* C&B Version: 1.2.83
* Do You have Optifine: Yes

**Comment by marchermans** [comment]
Please add logs and your mod list,
C&B does not interact with any crafting recipes, besides adding the ones for chisel, etc.
So I doubt this is a problem related to it.

**Comment by error44044** [comment]
Sorry i'm not the smartest so I don't know what you mean by logs besides crash logs, but this is my mods list:

appliedenergistics2-11.0.0-alpha.2
balm-3.0.1+0
betterfpsdist-1.18.1-1.4
Beyond-Earth-1.18.2-6.0k
Beyond-Earth-Giselle-Addon-1.18.2-2.2
comforts-forge-1.18.2-5.0.0.4
cookingforblockheads-forge-1.18.2-12.0.0
create-mc1.18.2_v0.4.1
createaddition-1.18.2-20220409a
DoggyTalents-1.18.2-2.5.0
flywheel-forge-1.18-0.6.2
jei-1.18.2-9.5.0.132
JustEnoughResources-1.18.2-0.14.1.164
lucky-block-forge-1.18.2-12.0
mcjtylib-1.18-6.0.12
Pehkui-3.2.1+1.14.4-1.19
pipez-1.18.2-1.0.0
preview_OptiFine_1.18.2_HD_U_H6_pre1
productivebees-1.18.2-0.9.0.1
refinedstorage-1.10.2
rftoolsbase-1.18-3.0.7
rftoolsbuilder-1.18-4.0.8
rftoolspower-1.18-4.0.4
supermartijn642configlib-1.0.9-mc1.18
supermartijn642corelib-1.0.16b-mc1.18
tesseract-1.0.25-mc1.18
waystones-forge-1.18.2-10.0.0
wirelesschargers-1.0.5-mc1.18
Xaeros_Minimap_22.3.0_Forge_1.18.2

**Comment by marchermans** [comment]
Given that there is no chisels and bits in that list, and you are not able to provide logs, there is not much I can do.
