### ISSUE TITLE
Imposing pattern onto block causes crash

### ISSUE THREAD

**Issue by Mattk4355** [ChiselsAndBits/Chisels-and-Bits#903]
* MC Version: 1.18.2
* C&B Version: 1.2.83
* Do You have Optifine: No

Issue description: I created a pattern that is empty except the top layer which was a pattern of some concrete. Every time I attempt to use impose to place the pattern the game crashes. However, the server which I am playing on correctly imposes the pattern onto the block that I have selected (tested in single player as well, the pattern is still correctly imposed).
(After some testing it seems this only happens when in survival mode - placement works fine in creative)
Edit: Forgot to mention the crash is client-side only (server continued to run fine)

Steps to reproduce:
* Create pattern that is mostly empty
* Attempt to impose the pattern onto a block

Crash Log:
[crash-2022-04-12_11.14.19-client.txt](https://github.com/ChiselsAndBits/Chisels-and-Bits/files/8475535/crash-2022-04-12_11.14.19-client.txt)

Screenshot of setup (left to right): block attempting to impose on (deepslate bricks), pattern to impose (combination of red & white concrete), and result after imposing pattern (after reloading from crash).
![2022-04-12_11 22 58](https://user-images.githubusercontent.com/9356838/163028913-05f7d2fa-59aa-47f9-941e-3110c5cc46cd.png)

**Comment by marchermans** [comment]
Reproduced. Will fix.

**Comment by marchermans** [comment]
Fixed in 1.2.84
