### ISSUE TITLE
Potential lag in 1.0.63

### ISSUE THREAD

**Issue by Kiliannb** [ChiselsAndBits/Chisels-and-Bits#904]
Before continuing if you are reporting an issue, please ensure that all mods involved are updated to the latest version available, if your issue with with intermod compatibility such mixing C&B bits with other blocks make sure that MCMP is also updated. If your issue is a crash, be sure to include the crash log with your report.

For any bug reports please provide the following details as well,
* MC Version: 1.16.5
* C&B Version: 1.0.63
* Do You have Optifine: no

**Comment by marchermans** [comment]
Logs and I need more information on your computer, and setup.

**Comment by marchermans** [comment]
No further information provided by creator of issue, and not reproducable.
Closing.
