### ISSUE TITLE
Not valid notification every time i break or place a bit?

### ISSUE THREAD

**Issue by netcore10** [ChiselsAndBits/Chisels-and-Bits#907]
For any bug reports please provide the following details as well,
* MC Version: 1.18.2
* C&B Version: 1.2.84
* Do You have Optifine: no, (but i do have sodium)

Every time a bit is placed or broken i get the not valid notification, 

Disabled all mods, except chisels and bits.

**Comment by netcore10** [comment]
found something. It happens when i have a bit in my hand, but when i use a chisel the notification doesn't appear.

**Comment by marchermans** [comment]
Hmm thanks for the heads up. I will check it out. What chisel mode are you using?

**Comment by netcore10** [comment]
it happens in any mode. Some less, but still there.

**Comment by netcore10** [comment]
![whathappens](https://user-images.githubusercontent.com/181536/163870244-83eb86a2-fbe2-4b09-829c-e2fdadd76e85.gif)
^here's a gif of what happens

**Comment by marchermans** [comment]
@netcore10 I can not reproduce that sorry.

**Comment by netcore10** [comment]
Even though it's loaded with absolutely no other mod?

**Comment by netcore10** [comment]
odd...

**Comment by marchermans** [comment]
I am going to see what I can do, maybe the cleanup that i applied already somehow fixed it and we got lucky. A release for that is coming in the next few days

**Comment by netcore10** [comment]
Cool! Is it possible to turn off the notification in some way, atleast?

**Comment by marchermans** [comment]
Not in this version. But i will add that now as well

**Comment by netcore10** [comment]
Thanks for everything. Chisels and bits is my life 😊

**Comment by Hiconel** [comment]
I have the exact same issue. I use Forge with Rubidium, which is a fork of Sodium, and everytime I break a bit I get the same notification.

**Comment by marchermans** [comment]
I am working on a patch.

**Comment by Hiconel** [comment]
Thank you! ❤

**Comment by Lunastuff** [comment]
> I am going to see what I can do, maybe the cleanup that i applied already somehow fixed it and we got lucky. A release for that is coming in the next few days

Hi! I'm also having this problem. Will the update still be coming out within the next day or so or is there an updated time frame? No rush, obviously. I also appreciate how upfront and quick to respond you are!

**Comment by netcore10** [comment]
> > I am going to see what I can do, maybe the cleanup that i applied already somehow fixed it and we got lucky. A release for that is coming in the next few days
> 
> Hi! I'm also having this problem. Will the update still be coming out within the next day or so or is there an updated time frame? No rush, obviously. I also appreciate how upfront and quick to respond you are!

It'll probably take a few more day's.

**Comment by marchermans** [comment]
Fixed in 1.2.85
