### ISSUE TITLE
Crash With RoughlyEnoughItems

### ISSUE THREAD

**Issue by HacoKavanah** [ChiselsAndBits/Chisels-and-Bits#909]
ChiselsBits-fabric-1.18.2-1.2.85.jar, Minecraft 1.18.2, No Optifine
[crash-2022-04-25_21.07.28-client.txt](https://github.com/ChiselsAndBits/Chisels-and-Bits/files/8556952/crash-2022-04-25_21.07.28-client.txt)

**Comment by marchermans** [comment]
I can't seem to reproduce this.
How did this crash happen?

**Comment by HacoKavanah** [comment]
Every player on our small server, who would search anything chisels & bits on rei, would crash.

**Comment by netcore10** [comment]
Can confirm that rei does indeed crash
[reicrash.txt](https://github.com/ChiselsAndBits/Chisels-and-Bits/files/8558061/reicrash.txt)

I searched a term and it crashed due to nbt of somekind

**Comment by marchermans** [comment]
This seems to be unique to rei then. I will contact @shedaniel and see what I can do

**Comment by HacoKavanah** [comment]
Did you guys fix the crash? I tried the newest release of the mod & looking at stuff in REI works without crashing the game!

Even if u fixed this by accident, thank you!

**Comment by marchermans** [comment]
Yeah this is fixed
