### ISSUE TITLE
dark chiselled blocks

### ISSUE THREAD

**Issue by Jlogue123** [ChiselsAndBits/Chisels-and-Bits#910]
Whenever I place a block on top of a chiseled block, the chiseled block, as well as surrounding blocks, are darker. Any tips to prevent this?

tent.com/104724956/166150266-70fe1821-47e3-4c89-a2f1-2a25539258d4.png

![Screenshot (12)](https://user-images.githubusercontent.com/104724956/166150300-b498dacb-6cbe-4e43-a305-99ef3e16102c.png)

**Comment by marchermans** [comment]
Enable the forge enhanced rendering pipeline

**Comment by Jlogue123** [comment]
How do I enable that?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
