### ISSUE TITLE
Crash when hovering over block with simple pattern item

### ISSUE THREAD

**Issue by bleh1245** [ChiselsAndBits/Chisels-and-Bits#913]
When attempting to hover over a block with a copied pattern, the game will proceed to crash

For any bug reports please provide the following details as well,
* MC Version: 1.18.2
* C&B Version: 1.2.78
* Do You have Optifine: No

[message.txt](https://github.com/ChiselsAndBits/Chisels-and-Bits/files/8680306/message.txt)

**Comment by marchermans** [comment]
Fixed in the latest version.
At least I was not able to reproduce this.
