### ISSUE TITLE
My red outline has dissapeared? I have deleted and reinstalled? 

### ISSUE THREAD

**Issue by eluxide** [ChiselsAndBits/Chisels-and-Bits#916]

**Comment by Changukim** [comment]
I'm going through the same phenomenon.
If you use chisels for blocks, the red outline disappears, and functions such as Drawn Region and Line do not work.
The 1x1 chisel also does not work if the mouse is pressed continuously.
I'm using the fabric version

MC Version: 1.18.2
C&B Version: from 1.2.87 to 1.2.90
Do You have Optifine: both with and without

**Comment by marchermans** [comment]
Fixed in 1.2.100
