### ISSUE TITLE
REI search + C&B crash

### ISSUE THREAD

**Issue by TheMightyMcGrew** [ChiselsAndBits/Chisels-and-Bits#917]
Searching REI with Chisels and Bits installed causes a crash unrelated to any given item's search parameter. Any search can cause a crash. Blacklisting Chisels and bits did not stop crash either.

[crash-2022-05-22_15.37.14-client.txt](https://github.com/ChiselsAndBits/Chisels-and-Bits/files/8749412/crash-2022-05-22_15.37.14-client.txt)

* MC Version: 1.18.1
* C&B Version: 1.2.82
* Do You have Optifine: No, but there is Sodium and Indium

**Comment by marchermans** [comment]
This is not related to C&B.
Please report this to REI.
