### ISSUE TITLE
PlotSquared + Chisel & Bits Block Data

### ISSUE THREAD

**Issue by SarahAquamarine** [ChiselsAndBits/Chisels-and-Bits#918]
I have a question. I want to make a creative 1.12.2 plots server. Is there a way that it will detect the **chisel & bits mod** blocks data? Players can still place/break chisels when they shouldn't have access to build/place normally. I'm also using the PlotSquared plugin.

**Comment by marchermans** [comment]
Not really no sorry.
1.12 is also out of support, and generally behaved more like a client side mod then anything else.
