### ISSUE TITLE
Chisel drawn region mode not working in creative (1.18.2)

### ISSUE THREAD

**Issue by ColorMeSurprised** [ChiselsAndBits/Chisels-and-Bits#923]
The chisel drawn region mode does not work in creative, here are some discoveries I've made after testing:
-I can use drawn region while holding a bit in creative
-if I switch to survival use the chisel in drawn region mode and then switch back to creative it works 
-if I get a new chisel after switching back drawn mode won't work.

only have chisel and bits installed:
![image](https://user-images.githubusercontent.com/68570053/170891189-4b72d6e7-e14b-45cb-8237-1d2a3a288b4b.png)

**Comment by marchermans** [comment]
Fixed in latest.
