### ISSUE TITLE
Greetings, I am currently in Minecraft version 1.16.5 and the mod version is 1.0.63, I do not use optifine, I noticed that the draw region mode is not available, is it because of the version? is it a bug? it was not integrated on purpose? and is there a way to build in a similar mode to draw region? I am getting a little tired of not being able to fill a selected area. Thank you.

### ISSUE THREAD

**Issue by bluebeazt** [ChiselsAndBits/Chisels-and-Bits#924]
Greetings, I am currently in minecraft version 1.16.5 and the mod version is 1.0.63, I am not using optifine. I noticed that the draw region mode is not available, is it a bug? is it because of the version? was it not included? is there a way I can build in a similar mode? I am a little tired of not being able to build on a selected area. Thank you.

For any bug reports please provide the following details as well,
* MC Version:
* C&B Version:
* Do You have Optifine:

**Comment by marchermans** [comment]
It is because of the version, it was added back into in 1.18.2
