### ISSUE TITLE
crash 1.18.2 Error: java.lang.ExceptionInInitializerError: null Exit Code: -1

### ISSUE THREAD

**Issue by BabyBanchee** [ChiselsAndBits/Chisels-and-Bits#926]
Before continuing if you are reporting an issue, please ensure that all mods involved are updated to the latest version available, if your issue with with intermod compatibility such mixing C&B bits with other blocks make sure that MCMP is also updated. If your issue is a crash, be sure to include the crash log with your report.

wont let me open the game just says
    Error: java.lang.ExceptionInInitializerError: null
Exit Code: -1

For any bug reports please provide the following details as well,
* MC Version: 1.18.2
* C&B Version:1.18.2
* Do You have Optifine: yes but even if i take it off it still doesn't work

**Comment by marchermans** [comment]
1.18.2 is not a valid version for C&B.
Could you supply the logs files please?

**Comment by marchermans** [comment]
No logs or comments for several days, not reproducable. Closing.
