### ISSUE TITLE
Config screen fabric 1.18

### ISSUE THREAD

**Issue by washinoboku** [ChiselsAndBits/Chisels-and-Bits#927]
There is no configuration screen as promised the wiki page :P

I don't know if its normal behavior but I don't want to get bits in my inventory when I chisel blocks. I need them dropped.
Is posible to do that?
I already change the extra bits deletion to false.

I playing 1.18.2 Fabric version.

**Comment by marchermans** [comment]
Fabric has no config screen since the fabric platform has no direct API for one.
As such I am not in the position to support that on the fabric platform.
