### ISSUE TITLE
Recurring 1.18.2 crash

### ISSUE THREAD

**Issue by vizthex123** [ChiselsAndBits/Chisels-and-Bits#928]
I keep having this crash whenever I load my modpack, and I've got no clue what's causing it.

For any bug reports please provide the following details as well,
* MC Version: 1.18.2
* C&B Version: 1.2.90
* Do You have Optifine: No

Crash report:
[crash-2022-06-04_22.52.50-client.txt](https://github.com/ChiselsAndBits/Chisels-and-Bits/files/8839293/crash-2022-06-04_22.52.50-client.txt)

Game log:
[latest.log](https://github.com/ChiselsAndBits/Chisels-and-Bits/files/8839294/latest.log)

**Comment by marchermans** [comment]
@vizthex123 I am unable to reproduce this with just vanilla + forge + c&b, can you validate that this happens with just those three components and get back to me?

**Comment by vizthex123** [comment]
> @vizthex123 I am unable to reproduce this with just vanilla + forge + c&b, can you validate that this happens with just those three components and get back to me?

Nope, it's only in my modpack; and fixed itself after I removed one of the performance mods I had (I want to say it was Rubidium, but I still have that so that's not it)

I'll go ahead and close the issue since it was a couple days ago, so I don't remember the details.
