### ISSUE TITLE
i seen in the forge section of your page instructing to enable something i cant remember what it said it was so long, in the config files but i am having trouble locating it in my config files

### ISSUE THREAD

**Issue by Th3Br0k3nmama** [ChiselsAndBits/Chisels-and-Bits#929]
Before continuing if you are reporting an issue, please ensure that all mods involved are updated to the latest version available, if your issue with with intermod compatibility such mixing C&B bits with other blocks make sure that MCMP is also updated. If your issue is a crash, be sure to include the crash log with your report.

For any bug reports please provide the following details as well,
* MC Version:
* C&B Version:
* Do You have Optifine:

**Comment by Th3Br0k3nmama** [comment]
well i figured my issue out. but the only reason i wanted to do this is because i was having so much lag with chisel and bits that i couldnt even move like i cant play it at all. if there could be something else you can suggest that may be wrong and that can help to where i can use your mod that would be greatly appreciated

**Comment by marchermans** [comment]
@Th3Br0k3nmama Please join our discord so we can help you: https://discord.chisels-and-bits.com/
