### ISSUE TITLE
Last update not compatible 

### ISSUE THREAD

**Issue by Amylubee** [ChiselsAndBits/Chisels-and-Bits#930]
Hi everyone. I downloaded the lastest update but it is not compatible with the 1.18.2 I downloaded yesterday from the minecraft website. It’s shown in red ( made for a previous version of the game) Will there be a new release soon ?
Thanks

For any bug reports please provide the following details as well,
* MC Version: 1.18.2
* C&B Version: chiselsBit-forge-1.18.2-1.2.90 universal
* Do You have Optifine:

**Comment by EntropicPariah** [comment]
Do you have Minecraft Forge installed? It won't work with the vanilla 1.18.2 installation.

**Comment by Amylubee** [comment]
Yes I have Forge, the latest version… Titan biomes mod works just fine.
Thanks for your answer.

**Comment by marchermans** [comment]
Log files please, since I just tested this and I have no problems with that jar.

**Comment by marchermans** [comment]
Fixed in 1.2.100
