### ISSUE TITLE
Several functions of chisels under creative mode abnormal

### ISSUE THREAD

**Issue by LouiseWhite212109** [ChiselsAndBits/Chisels-and-Bits#931]
While using chisels, I found the following functions don't work under creative mode:
Drawn Region
Line
Extrude
In the meantime, these functions seem to be found on bits. Left-click to destroy bits, and right-click to place bits. 
By the way, everything goes fine under survival mode.
I don't know whether it is a new feature or a bug. I just report it here.

For any bug reports please provide the following details as well,
* MC Version: 1.18.2
* C&B Version: from 1.2.87 to 1.2.90
* Do You have Optifine: both with and without

**Comment by marchermans** [comment]
Fixed in 1.2.100
