### ISSUE TITLE
Placing Chisel Station

### ISSUE THREAD

**Issue by Jasman922** [ChiselsAndBits/Chisels-and-Bits#935]
I placed a Chisel Station and put stuff in it, and then this white box appers. You cant get rid of it. If you restart the server, disconnect, reload. And I'm just gonna uninstall chisel and bits for a moment to fix it.

For any bug reports please provide the following details as well,
* MC Version: 1.18.2
* C&B Version: 1.2.90
* Do You have Optifine: No

**Comment by marchermans** [comment]
Fixed in 1.2.100
