### ISSUE TITLE
Chiseled block models generate and render many unnecessary quads

### ISSUE THREAD

**Issue by Phylogeny** [ChiselsAndBits/Chisels-and-Bits#943]
As expected, when two bits in a chiseled block with the same state have opaque textures and are next to each other in a block space, the model doesn't generate quads between them. But quads of adjacent bits shouldn't generate for any bits of any state if the quads are opaque, yet they do. The outer quads should also be culled by adjacent blocks with solid textures that completely obscure them, but they don't (even if they are the same block state).

For example, here are two chiseled blocks next to each other; each with a pair of different opaque blocktypes in them:

![Outside Adjacent Chiseled Blocks](https://i.postimg.cc/3xVGdVN8/Outside-Adjacent-Chiseled-Blocks.png)

Nothing should render when the camera is inside either or them, or between them, yet here is a view from almost exactly between them:

![Inside Adjacent Chiseled Blocks](https://i.postimg.cc/fbd9XCSx/Inside-Adjacent-Chiseled-Blocks.png)

**Comment by MattB70** [comment]
Optimizing this would be incredibly helpful.
