### ISSUE TITLE
The character gets stuck when standing on the bit

### ISSUE THREAD

**Issue by sakurano-sora** [ChiselsAndBits/Chisels-and-Bits#949]
The character gets stuck when I set ”bit-size = "ONE_HALF" or “bit-size = "ONE_QUARTER"” and stand on the bit

* MC Version:1.16.5
* C&B Version:1.0.63
* Do You have Optifine: no

**Comment by marchermans** [comment]
Known issue but sadly 1.16.5 won't receive an updates any more due to time constraints in my RL.

1.18 is the forge LTS and 1.19 will be the next release for C&B.
