### ISSUE TITLE
Forge 1.16.5 C&B + Rubidium Misaligned pixels

### ISSUE THREAD

**Issue by SparkdotIe** [ChiselsAndBits/Chisels-and-Bits#955]
When using the most up to date version of Chisels and Bits (as of 4:10 am GMT-5 7/4/22), plus the unofficial port of sodium, called Rubidium, The pixels of a C&B block will misalign like so:

![2022-07-04_03 55 40](https://user-images.githubusercontent.com/26665237/177122236-dd3f36e3-7914-473c-b67d-e080170485f3.png)

This happens regardless of distance from 0 0, and with every surface of the block

As much as I'd like to just remove Rubidium, my game would hate me for it. 
(P.S. This is also going to be put on the Rubidium page incase it's something they can fix.)

**Comment by marchermans** [comment]
Sorry Rubidium is officially not supported.
There are so many compatibility problem with such a mod that I have no way to fix this.

Also next time please actually specify which version you are using.
I use the vanilla FaceBakery with quad interpolation which is not something new.
