### ISSUE TITLE
Removing all bits of a given type from a chiseled block causes remaining types to have incorrect or missing textures

### ISSUE THREAD

**Issue by Phylogeny** [ChiselsAndBits/Chisels-and-Bits#958]
First, here's a chiseled block with 6 bit types placed in order, left to right. The block below it is, for the moment, made identically, and servers as a representation of an array of each texture present in the above block:

![Image 1](https://i.postimg.cc/cJrbVZrw/Incorrect-Bit-Textures-1.png)

Now, the second added bit type is removed:

![Image 2](https://i.postimg.cc/8C90G363/Incorrect-Bit-Textures-2.png)

The last type added is transparent, and each type after the removed one appears shifted by one. Updating the bottom texture set representation confirms this:

![Image 3](https://i.postimg.cc/2yf9bZT7/Incorrect-Bit-Textures-3.png)

Now here's the fourth added type removed, and the texture set representation updated:

![Image 4](https://i.postimg.cc/fLdgRK7b/Incorrect-Bit-Textures.png)

The pattern holds when adding back a previously removed type (in this case, the second type added) anywhere in the block space and updating the representation:

![Image 5](https://i.postimg.cc/P5673Nrd/Incorrect-Bit-Textures-5.png)

Adding more bits of a type with a currently incorrect texture (in this case, spruce logs) results in the same incorrect texture for the new bits:

![Image 6](https://i.postimg.cc/dVQXjGFW/Incorrect-Bit-Textures-6.png)

It's as if there's some kind of texture array that the bit types have references to, and that those references don't update when the array updates; and that the textures are transparent when the cached reference is outside the arrays range.

This shares the same root cause as #951

C&B 1.18.2-1.2.90; Forge 40.0.46; No Optifine

**Comment by marchermans** [comment]
What the f.......
I think their might be a bug in the palette system. I will fix this tomorrow
