### ISSUE TITLE
Problem with Tinkers Construct 

### ISSUE THREAD

**Issue by N1elkyfan** [ChiselsAndBits/Chisels-and-Bits#96]
I found that I am unable to Chisel the clear glass from tinkers construct.

**Comment by AlgorithmX2** [comment]
Please ensure your using the latest build of TiC.

Clear glass is white-listed ( https://github.com/SlimeKnights/TinkersConstruct/blob/0076db29be2ad1c8ec84989e86866d1b738a1542/src/main/java/slimeknights/tconstruct/plugin/ChiselAndBits.java#L23 )

**Comment by AlgorithmX2** [comment]
I tested it with a Jenkins build of TiC and its working, so I'd just recommend updating.
