### ISSUE TITLE
Client crash, rendering, Exit Code -1

### ISSUE THREAD

**Issue by PaterFrog** [ChiselsAndBits/Chisels-and-Bits#967]
[crash-2022-07-10_12.17.22-client.txt](https://github.com/ChiselsAndBits/Chisels-and-Bits/files/9078865/crash-2022-07-10_12.17.22-client.txt)

**Comment by PaterFrog** [comment]
This one is frequent, but not entirely consistent. I'm often able to start the game eventually.

**Comment by marchermans** [comment]
Please try to reproduce this with vanilla + C&B only.
I had reports like this comming in, but I am using the event. There seem to be mods out there which mess with the order and C&B is just un unlikely victim of it.

**Comment by PaterFrog** [comment]
There was a rash of updates this weekend, haven't this crash since. I figure someone fixed something important somewhere.
