### ISSUE TITLE
Unknown non-recoverable crash

### ISSUE THREAD

**Issue by CorenAlbrich** [ChiselsAndBits/Chisels-and-Bits#97]
This has happened twice. I was playing in a single player world designing something when (and this is conjecture) I think I touched, as in my player collided with, a chiseled block, and I crashed.

Crash report: http://pastebin.com/idkLHBWq

I think I might have glitched into the block, somehow leading to a crash...? When I startup the world, I see what looks like the inside of a block, then it crashes again. I know it's c&b because when I uninstalled it and loaded the world, everything was fine.

In case you need them, the other mods:
Chameleon (Jaquadro)
Storage drawers (Jaquadro)
Chisel (tterrag1098)
FixChiselStoneGeneration (connorrowe)
Chisels % Bits (AlgorithmX2)
Flat Colored Blocks (AlgorithmX2)
Mantle (mDiyo)
Psi (Vazkii)

**Comment by AlgorithmX2** [comment]
This has actually been fixed... ( https://github.com/AlgorithmX2/Chisels-and-Bits/issues/89 )

But I have been pretty distracted and haven't released the new version yet, I'll try and get it released in a bit here.

**Comment by AlgorithmX2** [comment]
Errr.. on second thought...

Please download and try this, http://minecraft.curseforge.com/projects/chisels-bits/files/2316811

**Comment by AlgorithmX2** [comment]
I goofed the version number on the last release so your probably still using the old 11.5 ( confusing I know ) 

But that file should have the fix for your crash, if it doesn't I need to confirm it either way.

**Comment by CorenAlbrich** [comment]
Yup seems to be fixed, loaded up with no problems... I'll let you know if it happens again later. CHEERS!
