### ISSUE TITLE
Incorrect Culling with C&B Fabric and certain block models.

### ISSUE THREAD

**Issue by Aurailus** [ChiselsAndBits/Chisels-and-Bits#983]
Certain block models, such as stairs and slabs, incorrectly occlude block face culling for Chisels and Bits blocks. See the attached image for an example, where I've only removed a single bit from the block and it's not rendering the entire side facing the stair. This happens for most modded non-full blocks as well, making it very hard to decorate. The image attached was reproduced with ONLY C&B and Fabric API.

* MC Version: 1.18.2
* C&B Version: ChiselsBits-fabric-1.18.2-1.2.113
* Do You have Optifine: No.

![2022-08-06_00 04 02](https://user-images.githubusercontent.com/22041561/183238557-bfcd4391-4dbf-4e4b-98cc-67569f23e0c7.png)

**Comment by Game-Log** [comment]
I'm having this issue as well. Currently playing on 1.18.2 with Mod Version 1.2.113. I hope this can be resolved soon.
