### ISSUE TITLE
Suggestion - Incredible Shrinking Machine

### ISSUE THREAD

**Issue by Apocryphai** [ChiselsAndBits/Chisels-and-Bits#99]
Just an idea: a device that scans a 16 x 16 x 16 block area and converts anything built with compatible, whole blocks into a 1 block Chisels & Bits chiselled item, effectively shrinking it 16-fold. 

It could give an error or warning if unsuitable blocks were in the scan area and it would need to be fed the correct materials to build with. It would also require supplying with some other resources, e.g. a supply of chisels (maybe expensive industrial-grade chisels?), RF, water (for cooling), etc. Adjustable for balancing purposes.

Not sure if this fits with either your intentions for the mod, or your available time, but I thought I'd share the idea anyway :)

**Comment by AlgorithmX2** [comment]
Not sure having a block delete 99.97% of your resources is a great feature.... and if it doesn't "shrink" but instead make a new block based on a template i'm not sure that its a "shrinking machine" more of a "template chiseling machine"

Either way I'm not sure it really belongs in C&B, C&B is at its core a mod about sculpting and building; if someone else wanted they could probably make an addon to do something like this, but I don't think it fits with the base mod.

**Comment by Apocryphai** [comment]
Fair enough, was just a shower thought :)
