### ISSUE TITLE
[1.16.5]unable to connect

### ISSUE THREAD

**Issue by StrictMaple** [ChiselsAndBits/Chisels-and-Bits#991]
Chisels & Bits cannot connect when using bungee to connect
[https://upload.cc/i1/2022/08/23/fyPvNS.png
](url)

**Comment by marchermans** [comment]
Use the same version as the server or stop using proxy systems on the server side.

**Comment by StrictMaple** [comment]
Background display
[https://upload.cc/i1/2022/08/23/yul8Pe.png
](url)
