### ISSUE TITLE
C&B blocks used in 1.16.5 not shown in 1.18.2 version

### ISSUE THREAD

**Issue by jeksbox** [ChiselsAndBits/Chisels-and-Bits#994]
My first build includes:
Minecraft Forge1.16.5 36.1.0
Chiselsandbits-0.2.10-RELEASE

Update: my world and c&b blocks also works in forge 1.17.1
chiselsandbits-1.1.39-ALPHA is working

Tried updating to 1.18.2. The c&b mod itself loads/works correctly, but nothing that has been created before using C&B mod is seen anymore when loading my world&structures in 1.18.2.  Basic Minecraft blocks are shown correctly. C&B blocks are invisible.

Minecraft Forge 1.18.2 40.1.0
ChiselsBits-forge-1.18.2-1.2.113-universal

**Comment by marchermans** [comment]
This is caused by vanilla.
Modded tile entities are not kept after the world update.
There is nothing I can do.
