### ISSUE TITLE
Create and C&B

### ISSUE THREAD

**Issue by EFriseer** [ChiselsAndBits/Chisels-and-Bits#998]
* MC Version: 1.18.2
* C&B Version: Latest as of 09/08/2022
* Do You have Optifine: No

So I spent almost 3/4 hours building a train using the Create and C&B mod in my survival server to at the end find out that for whatever reason the train just won't move the blocks I sculpted with the C&B mod (See Attached screenshots). Is there anything I can do to fix this? I have to wait for a fix on either mods side? There's anything that can be done? Thanks in advance.
![Desktop Screenshot 2022 09 08 - 23 00 55 92](https://user-images.githubusercontent.com/84281548/189230251-d81e879c-c893-4def-9475-3f315a224b41.png)
![Desktop Screenshot 2022 09 08 - 22 53 10 04](https://user-images.githubusercontent.com/84281548/189230257-5183a1e5-a518-42ee-a5ef-34b90d2098b5.png)
![Desktop Screenshot 2022 09 08 - 22 53 35 44](https://user-images.githubusercontent.com/84281548/189230262-6f6649d4-da26-4225-94be-fd2ee73ab7ff.png)

**Comment by JoshHawley** [comment]
Ive had this happen before with non C&B blocks. did you try regluing the whole thing? Use a huge single glue area

**Comment by EFriseer** [comment]
> Ive had this happen before with non C&B blocks. did you try regluing the whole thing? Use a huge single glue area

Reading stuffs on the Create's Discord server seems like the problem is that to be usable with Create's contraptions C&B has to add all the possible models for blocks as blockstates. I don't know what this exactly means and how it would be done but looks like it's a C&B problem.

**Comment by ghost** [comment]
wouldn't that take like ages (as in several years) and also have a massive filesize?
because that is 16x16x702 which is 179712 if my math is correct
unless, the game could do it dynamically and do it when a block is chiseled
but idk how it would be done either, maybe with a python script or dynamically in game

**Comment by edgarogh** [comment]
> wouldn't that take like ages (as in several years) and also have a massive filesize? because that is 16x16x702 which is 179712 if my math is correct unless, the game could do it dynamically and do it when a block is chiseled but idk how it would be done either, maybe with a python script or dynamically in game

No, that's actually $702^{(16 \times 16 \times 16)}$ which is approximately $3.951948566051159719898223115\ldots \times 10^{11658}$ different combinations.
"Massive filesize" is an understatement, the number of combinations is $10^{145}$ times larger than the amount of atoms in the observable universe.

(sorry for the useless comment :see_no_evil:)

**Comment by marchermans** [comment]
On 1.19.2 forge this is now officially supported. On fabric this has to wait for an update on creates side.
