### ISSUE TITLE
Bugged render

### ISSUE THREAD

**Issue by lynrayy** [ChiselsAndBits/Chisels-and-Bits#999]
Before continuing if you are reporting an issue, please ensure that all mods involved are updated to the latest version available, if your issue with with intermod compatibility such mixing C&B bits with other blocks make sure that MCMP is also updated. If your issue is a crash, be sure to include the crash log with your report.
![image](https://user-images.githubusercontent.com/59417884/191542620-8873d200-bb61-42be-b56e-6310a4f4e3aa.png)
![image](https://user-images.githubusercontent.com/59417884/191542638-1c73b33d-c3be-4b6b-aa63-3dc9dfc6d6c0.png)

For any bug reports please provide the following details as well,
* MC Version: 1.18.2
* C&B Version: [ChiselsBits-forge-1.18.2-1.2.114-universal.jar](https://www.curseforge.com/minecraft/mc-mods/chisels-bits/files/3957651)
* Do You have Optifine: YES. And i WILL NOT REMOVE THAT

**Comment by marchermans** [comment]
Remove optfine
